### ISSUE TITLE
Optional title missing

### ISSUE THREAD

**Issue by molmich** [asciidoctor/asciidoctor-pdf#101]
have noticed that all "optional title" are missing, for example:

.My title
bla bla bla 

in pdf I see only:

bla bla bla

. Does anyone have an idea, wats worng!?

**Comment by madmas** [comment]
This seems to be related to #98 and #67 and thus might be fixed by #96

**Comment by mojavelinux** [comment]
Yep, mainly a duplicate of #67. Scheduled for 1.5.0.
