### ISSUE TITLE
Confused how to use custom theming

### ISSUE THREAD

**Issue by lrxw** [asciidoctor/asciidoctor-pdf#1011]
I went through this description https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc to create a custom theme which should just change the footer of my generated pdf. What I unterstand from the description is, that I can just overwrite the properties I want to change and the rest will look the same as without any custom theme. 

> When creating a new theme, you only have to define the keys you want to override from the base theme, which is loaded prior to loading your custom theme.

But it seems something is messing up with the fonts. Which is - to be fair - pointed out directly beneath

> If you start a new theme from scratch, we strongly recommend defining TrueType fonts and specifying them in the base and literal categories. Otherwise, Asciidoctor PDF will use built-in AFM fonts, which can result in missing functionality and warnings. 

So I have to wrestle with the fonts, which I don't want to change? Or did I make a mistake?

**Comment by mojavelinux** [comment]
> When creating a new theme, you only have to define the keys you want to override from the base theme, which is loaded prior to loading your custom theme.

This is describing the bare minimum so that you understand the boundaries. You are going to end up with a severely understyled document if you don't start with the default theme. That includes the fonts. Here's the default theme file: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml

**Comment by mojavelinux** [comment]
Just copy that file, tweak it and you'll be off to the races.

**Comment by lrxw** [comment]
Thanks. That first quoted paragraph just mislead me. But it would be nice if I just could change the values I would like to and get the default settings anyway. Convention over configuration :)

**Comment by mojavelinux** [comment]
It's now possible to extend themes, which will make this a lot easier. You can see this in action in the theme for the chronicles example. https://github.com/asciidoctor/asciidoctor-pdf/blob/master/examples/chronicles-theme.yml

**Comment by mojavelinux** [comment]
See #367 for details about how this got fixed.
