### ISSUE TITLE
qanda support

### ISSUE THREAD

**Issue by csmart** [asciidoctor/asciidoctor-pdf#1013]
I'm probably missing something, but does asciidoctor-pdf support qanda? A basic adoc file with the sample qanda below renders correctly to html with asciidoctor but not with asciidoctor-pdf.

For example:
```adoc
[qanda]
What is Asciidoctor?::
  An implementation of the AsciiDoc processor in Ruby.
What is the answer to the Ultimate Question?::
  42
```
HTML correct render:
![asciidoc_qanda](https://user-images.githubusercontent.com/43712/55042317-0d912800-5085-11e9-8417-2225045b3990.png)

PDF incorrect render:
![asciidoctor-pdf_qanda](https://user-images.githubusercontent.com/43712/55042339-17b32680-5085-11e9-9986-495d955dfcaf.png)

**Comment by YenForYang** [comment]
Having the same issue here -- is this something we have to theme on our own? My main issue is with the lack of numbering.

**Comment by mojavelinux** [comment]
> does asciidoctor-pdf support qanda

No, it does not. PRs welcome (especially now that we have a test suite!)
