### ISSUE TITLE
Table with only one row ignores attributes

### ISSUE THREAD

**Issue by schulle877** [asciidoctor/asciidoctor-pdf#1014]
I build a table with the following attributes:
```
[discrete]
== Table of images
[stripes=none, frame=none, grid=none]
|===
|${list_of_images}
|===
```
On generating the document, I fill the `${list_of_images}`-placeholder with a generated one-column-table, listing all the images in the document. If there is only one image and only one row to fill, the single row is displayed as a header. With a background and bold. When generating the table with at least two images, the attributes are not ignored and the table is displayed correctly.

**Comment by schulle877** [comment]
The problem was a trailing line break after the row.
Incorrect:
```
[discrete]
== Table of images
[stripes=none, frame=none, grid=none]
|===
|<<image1>>

|===
```
Correct:
```
[discrete]
== Table of images
[stripes=none, frame=none, grid=none]
|===
|<<image1>>
|===
```

**Comment by mojavelinux** [comment]
There you go!
