### ISSUE TITLE
Plantuml diagram is not correctly rendered

### ISSUE THREAD

**Issue by gembin** [asciidoctor/asciidoctor-pdf#102]
``` xml
<dependency>
	<groupId>rubygems</groupId>
	<artifactId>asciidoctor-diagram</artifactId>
	<version>1.2.1</version>
	<type>gem</type>
	<scope>provided</scope>
	<exclusions>
		<exclusion>
			<groupId>rubygems</groupId>
			<artifactId>asciidoctor</artifactId>
		</exclusion>
	</exclusions>
</dependency> 
```
rendered:
---------------
![screen shot 2015-04-02 at 6 28 08 pm](https://cloud.githubusercontent.com/assets/26495/6962398/b892d6d0-d966-11e4-9a27-95bdd130639e.png)

should be:
---------------
![screen shot 2015-04-02 at 6 28 25 pm](https://cloud.githubusercontent.com/assets/26495/6962386/a65b78c8-d966-11e4-880c-54ebcfeb1e2f.png)

**Comment by mojavelinux** [comment]
Could you provide the source of the diagram? There's a chance this has to do with a bug in the Prawn SVG support (see https://github.com/mogest/prawn-svg). We've seen similar rendering problems in the past (which have always been addressed in a timely manner with a proper example). I'll verify on my end that it's a problem embedding the diagram, then we can proceed by filing an issue upstream.

**Comment by gembin** [comment]
Oh, sorry, I forgot to paste the source.

```
[plantuml, seq-diagram-1, svg]
-----

Alice->Bob : hello
note left: this is a first note

Bob->Alice : ok
note right: this is another note

Bob->Bob : I am thinking
note left
	a note
	can also be defined
	on several lines
end note
-----
```

**Comment by mojavelinux** [comment]
I generated the SVG of the diagram and then used Prawn + Prawn SVG alone to embed the SVG using the following code:

```
require 'prawn'
require 'prawn-svg'

Prawn::Document.generate 'test.pdf' do
  svg IO.read('seq-diagram-1.svg'), at: [0, cursor]
end
```

I can confirm that this is an issue with Prawn SVG because that produces the same result you are seeing. If that doesn't work, it won't work in Asciidoctor PDF. It seems like the problem is with the polygon fills. This is a great test case for Prawn SVG and it should be possible to get it resolved there.

**Comment by mojavelinux** [comment]
When you fill the issue at https://github.com/mogest/prawn-svg, be sure to link to it here so we can track the progress.

**Comment by gembin** [comment]
Resolved by Prawn SVG in in version 0.17.0.

**Comment by mojavelinux** [comment]
Great news!

Does this mean we need to upgrade prawn-svg in Asciidoctor PDF? (See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/asciidoctor-pdf.gemspec#L43).

**Comment by mojavelinux** [comment]
I'm going to assume the answer is yes. I'll update.

**Comment by gembin** [comment]
Yes need to upgrade prawn-svg.

**Comment by mojavelinux** [comment]
Update made.
