### ISSUE TITLE
start_at: toc does not work

### ISSUE THREAD

**Issue by equamo** [asciidoctor/asciidoctor-pdf#1028]
Hello,

_running_content:
  start_at: toc_

..,has no effect.

For this reason, I can not control from which side of the footer or header to be applied.

Best regards

Martin

**Comment by mojavelinux** [comment]
That's because the feature has not been released yet. You can either test against master or wait for the 1.5.0.alpha.17 release to be published. (The fix was tracked by this issue: https://github.com/asciidoctor/asciidoctor-pdf/issues/606).

**Comment by Alyaksej** [comment]
When it will be work?

**Comment by mojavelinux** [comment]
When the milestone for #606 shows up here https://rubygems.org/gems/asciidoctor-pdf, then you can expect it to work.
