### ISSUE TITLE
Internal cross references not working

### ISSUE THREAD

**Issue by gembin** [asciidoctor/asciidoctor-pdf#103]
Example: the chapter1 link is not working.

```
[[chapter1]]
=== chapter1
some content here ... 

=== chapter2
some content here ... and reference <<chapter1>>
```

**Comment by mojavelinux** [comment]
This is known (and there is even a pending fix). It's going to be one of the first things I work to fix once I get to Asciidoctor PDF hacking this month-ish.

See #56.

**Comment by mojavelinux** [comment]
This is now resolved.
