### ISSUE TITLE
running_content_start_at should not alter page numbering

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1041]
The page numbering should not be altered if the running_content_start_at is set to title or toc. Instead, roman numerals should be used for any page that proceeds the body.

(If we do want to alter the page numbering, that should be handled by a different setting).

**Comment by mojavelinux** [comment]
cc: @habamax

**Comment by habamax** [comment]
Not sure I get what is the bug.

Is it about page_numbers should always start from the non toc/title pages?

title -- pagenum ==0
toc page 1 -- pagenum ==0
toc page N -- pagenum == 0
content first page -- pagenum ==1
?

If so, then for my article type docs I am not sure I want that behavior.

**Comment by mojavelinux** [comment]
Just because we're adding the running content on the toc and/or title pages doesn't mean all of a sudden we should start numbering pages differently. These are front matter pages and have special (roman numeral) page numbering already (deeply rooted in PDF / book layout).

Now, we could allow the page numbering to be shifted (so that the front matter numbering isn't used), but that's a separate behavior that should be controlled by a separate setting.

> my article type docs I am not sure I want that behavior.

None of this applies to the article doctype since the article doctype doesn't have a title and toc page (except when using the legacy title-page attribute).

**Comment by mojavelinux** [comment]
(Look at the outline of the PDF for how pages are numbered normally. There, you will see "i" for the title page and "ii" for the toc page).

**Comment by habamax** [comment]
>None of this applies to the article doctype since the article doctype doesn't have a title and toc page (except when using the legacy title-page attribute).

I didn't know title-page is legacy. I use it quite extensively (80% of my "printed" docs) -- asciidoctor doesn't have report type which is between article and book (in latex), so this option let me mimic report type.

**Comment by habamax** [comment]
> (Look at the outline of the PDF for how pages are numbered normally. There, you will see "i" for the title page and "ii" for the toc page).

Ahh, yes, I remember I saw it. Usually in the pdfs that are "professionally" crafted/done but ugly as hell in my opinion.

Anyway, I agree it makes sense

**Comment by mojavelinux** [comment]
It's legacy because it was the wrong behavior to begin with (since Asciidoctor PDF was originally only made for books).

**Comment by mojavelinux** [comment]
Regardless, I'm not saying you can't have the behavior you want. I'm saying it's not correct for the page numbering to be affected by running_content_start_at. We need a separate property for that since it's fundamentally a different thing.
