### ISSUE TITLE
Title page is not generated in version 1.5.0.alpha.17

### ISSUE THREAD

**Issue by equamo** [asciidoctor/asciidoctor-pdf#1043]
The following customized title_page worked perfectly (in Version alpha.16) for me:

title_page:
  align: left
  logo:
    top: 65%
  logo_image: image:..\images/Test-A.png[width=373.5, height= 330.8, align=center]
  title:
    top: 1%
    font_size: $heading_h1_font_size
    font_color: $heading_h1_font_color
    font_style: bold
    font_family: $heading_h1_font_family
    line_height: 1.5
  subtitle:
    font_size: $heading_h1_font_size
    font_style: normal
    font_family: Calibri
    font_color: $heading_h1_font_color
    line_height: 1
  authors:
    margin_top: $base_font_size * 1.25
    font_size: $base_font_size_large
  revision:
    margin_top: $base_font_size * 1.25

but now since i updated to alpha.17 the title page is not generated.

**Comment by mojavelinux** [comment]
If you are generating an article doctype (the default) and want to include a title page (as before), you now need to set the `title-page` attribute in the document header.

```
= Article Title
:title-page

content
```

An article is not suppose to have a title page (by default). That layout is reserved for the book doctype. This was a long-standing issue in Asciidoctor PDF which was corrected in the last week. However, we decided to leave the option to include it for those who prefer the book style.

**Comment by mojavelinux** [comment]
The title-page attribute is documented here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#theme-related-document-attributes

**Comment by geoffwhittington** [comment]
Thanks! This worked for me. I did deviate a bit, however, by using `:title-page:` in my source.

**Comment by mojavelinux** [comment]
Yep, that's the right way to do it.

**Comment by equamo** [comment]
@mojavelinux
thanks a lot. Now the toc where generated.
But i the title-page-logo where not generated.
Could it also be that, I use the old wrong way?

In the Version 1.5.0.alpha.16 this solution worked perfectly for me:

```
title_page:
  align: left
  logo:
    image: image:..\images/logo.png[width=373.5, height= 330.8, align=center]
```

but now there are obviously some problems.

**Comment by mojavelinux** [comment]
Hmm. That scenario is not tested. I'll look into it. Thanks for letting me
know.

**Comment by equamo** [comment]
@mojavelinux 
Ok, so it would be nice, if you can let me know if/how the combination of title-page(with logo) and toc work.

**Comment by equamo** [comment]
@mojavelinux 

I have noticed that since the update, the logo dont work  **independent of the toc** (if i remove the toc, the logo also won't be generated ), so it must be due to my syntax. 
How do I correctly insert a title-page_logo?
Do i have to do something in the .adoc file or just in the theme.yml?

**Comment by mojavelinux** [comment]
Please be patient while I look into it. I assure you I will reply once I have investigated. If necessary, I will open a new issue to track it.

**Comment by mojavelinux** [comment]
I can't reproduce this problem. Can you please set up a GitHub project that demonstrates the problem so I can figure out what the scenario is?

> By the way, it seems to me that the title-page is not really an extra page, because also the footer and header where generated on this "title-page", but the footer and header just schould be generated at the content-pages (by default).

I noticed this:

> `:title-page`

This line is missing the closing `:`. That could be your problem.

**Comment by equamo** [comment]
@mojavelinux
Thanks Dan,

The mistake was too obvious, so I did not found it.

Know it works perfectly for me.

**Comment by mojavelinux** [comment]
@equamo I'm very glad to hear that!
