### ISSUE TITLE
How to customize the footnote style?

### ISSUE THREAD

**Issue by nhanngo** [asciidoctor/asciidoctor-pdf#1045]
Let say if I want to use smaller font and grey color for the footnotes but still can't figure out where to get it in https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc

**Comment by mojavelinux** [comment]
I forgot to add it to the theming guide. The top-level key is "footnotes". Thus, it would be:

```
footnotes:
  font_size: 9
```

etc.
