### ISSUE TITLE
code_font_family not applied to inline code

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#1046]
Given a theme:

```
code:
  font_family: MyCodeFont
```

and some Asciidoctor:

```
[source]
----
class FooBar { }
----

Some inline `Code`.
```

the custom font gets applied to the code block but not the inline code. The latter still uses Courier. Is there another attribute I have to configure the font to be used for inline code?

**Comment by odrotbohm** [comment]
Nevermind, I found the configuration options for `literal`. Does it make sense to hint to that from the theming docs for `code` as literals are quite often used for inline code expressions?

**Comment by mojavelinux** [comment]
You've got it.

Yes, that would be a good hint to add. When I created the schema, I was trying something different with the terminology, but in the end I don't think it really worked out. So the naming itself likely needs to be revisited.

**Comment by mojavelinux** [comment]
See #1796.
