### ISSUE TITLE
Disable table stripes by default

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1049]
To align with the behavior of Asciidoctor 2, disable table stripes (aka row shading) by default. The stripes can be enabled per table using the stripes block attribute (e.g., `stripes=even`) or globally using the table-stripes document attribute (e.g., `:table-stripes: even`).

NOTE: Although this issue was filed after the 1.5.0.alpha.17 release, it was already fixed in that release.

**Comment by andraz-kozelj** [comment]
Fix the documentation, where it states that "even" is the default.

"Applied to even rows by default; controlled using stripes attribute (even, odd, all, none) on table or table-stripes attribute on document (or the stripes attribute on the document if using Asciidoctor < 2)."

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc

**Comment by mojavelinux** [comment]
Oops, I had updated the Asciidoctor user manual, but forgot about the theming guide. Thanks for the reminder.

...

and fixed.
