### ISSUE TITLE
Table Cell Padding not working

### ISSUE THREAD

**Issue by 1marc1** [asciidoctor/asciidoctor-pdf#1053]
[The theming guide](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-table) indicates that value type for table_cell_padding is either "Measurement" or "Measurement[top,right,bottom,left]". When specifying a top,right,bottom,left measurement (irrespective of what was specified), the row spacing becomes cumulatively larger for each new table. This seems to be introduced with version 1.5.0.alpha.17 as this was not the case in 1.5.0.alpha.16. When a single "Measurement" is used, this problem does not occur.

Consider the following input file containing multiple tables:
```
== Testing with tables

=== First table

[%autowidth.spread,frame=topbot,grid=rows,options="header"]
.Test Table 1
|===
| Column1 | Column2 | Column3 
| Row 1 | Row 1 | Row 1 
| Row 2 | Row 2 | Row 2 
| Row 3 | Row 3 | Row 3
|===

=== Second table

[%autowidth.spread,frame=topbot,grid=rows,options="header"]
.Test Table 2
|===
| Column1 | Column2 | Column3 
| Row 1 | Row 1 | Row 1 
| Row 2 | Row 2 | Row 2 
| Row 3 | Row 3 | Row 3
|===

=== Third table

[%autowidth.spread,frame=topbot,grid=rows,options="header"]
.Test Table 3
|===
| Column1 | Column2 | Column3 
| Row 1 | Row 1 | Row 1 
| Row 2 | Row 2 | Row 2 
| Row 3 | Row 3 | Row 3
|===
```
When the table_cell_padding is set to [4,2,2,2], then the output generated by asciidoctor-pdf 1.5.0.alpha.17 looks like this (notice how the row spacing increases with each table):
![alpha17_tcp_4222](https://user-images.githubusercontent.com/18713538/57194786-4b3f7580-6f8e-11e9-82f0-d99ea00536e2.png)

The output in asciidoctor-pdf 1.5.0.alpha.17 with table_cell_padding set to "3" resembles the ouput generated by asciidoctor-pdf 1.5.0.alpha.16 with table_cell_padding set to [4,2,2,2]:
![alpha17_tcp_3](https://user-images.githubusercontent.com/18713538/57194827-b5f0b100-6f8e-11e9-8492-031c1c11537c.png)

Marc.

**Comment by mojavelinux** [comment]
Thanks for preparing this report. Something definitely seems amiss. I'll dive in and see if I can figure out what's going wrong.

**Comment by fritz-hh** [comment]
Cool, I just wanted to open an issue for this, and see that it is already solved :-)
Thanks a lot!
