### ISSUE TITLE
Get the file name in a Preprocessor extension

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor-pdf#1057]
Hello,

I updated my environment with asciidoctor 2.0.9 and asciidoctor-pdf 1.5.0.alpha.17 and I have a problem with an extension that I created.
It contains this code
```
class Check < Asciidoctor::Extensions::Preprocessor     
    def process document, reader  
	fileName = reader.file
```
I call this extension as well by converting my document into HTML and PDF.
It works fine when converting to HTML (the variable fileName contains the name of my adoc file) but in PDF conversion, `reader.file` returns Nil.

`warn reader` returns
in HTML converting : 
     `#<Asciidoctor::PreprocessorReader@43493400 {path: "myDoc.adoc", line: 1, include depth: 0, include stack: []}>`

in PDF converting : 
     `#<Asciidoctor::PreprocessorReader@59295140 {path: "<stdin>", line: 1, include depth: 0, include stack: []}>`
why `<stdin>` for path ?

Is it a bug in asciidoctor-pdf 1.5.0.alpha.17 ? (It was OK with 1.5.0.alpha.15)
Or I must use another method to get the name of the document (which one ?)

Thank you,
Jérôme

**Comment by mojavelinux** [comment]
I expect that to work fine. Asciidoctor PDF does not create any readers itself. There must be something else going on that we're not accounting for.

Can you isolate this into a reproducible scenario? Also, double check that the upgrade to Asciidoctor PDF 1.5.0.alpha.17 was clean (you don't have more than one version of the gem installed).

**Comment by mojavelinux** [comment]
Can you provide an example?

**Comment by JBR69** [comment]
On my post I actually have 2 environments asciidoctor (ruby 2.4 ; asciidoctor 1.5.6 ; asciidoctor-pdf 1.5.0-alpha.15 // ruby 2.6 ; asciidoctor 2.0.9 ; asciidoctor-pdf 1.5.0-alpha.17) .
I paid attention to environment variables (PATH, RUBY_HOME, etc ...) but a priori it is not enough.

On a virgin VM, it works fine (with ruby 2.6 and asciidoctor 2.0.9 and asciidoctor-pdf 1.5.0-alpha.17); it is therefore a problem with the cohabitation of the two environments.

**Comment by mojavelinux** [comment]
Thanks for confirming.

You do need to be careful with mixing installation paths because, just like in any language, the wrong source files can get picked up.

If you're able to reproduce the issue in likely combination, then I can look into whether there's a code change that can be made. Otherwise, I'd say this was just a corrupted installation.

**Comment by JBR69** [comment]
it comes from a problem with a Rouge theme that I use.
I created it inspired by [example of the wiki](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#source-highlighting-theme).

Still on my post with the 2 environments, if I replace in my Rouge theme, the line
`require 'red' unless defined? ::Rouge.version`
by
`require 'red'`

it works

**Comment by JBR69** [comment]
I reopen the issue because there is a problem even on the VM containing only an asciidoctor version.
The problem is related to using a Rouge theme that returns the following error
`C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rouge (LoadError)`

I will put an example

**Comment by JBR69** [comment]
In fact the error occurs when there is a combination of an asciidoctor extension and the use of a Rouge theme.
With the files provided in the Zip [adoc_1057.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/3172983/adoc_1057.zip), the execution of the command

`asciidoctor-pdf -r ./ext/myExtension.rb -r ./my-rouge-theme.rb myDoc.adoc`

1- works with environment "Ruby 2.4.0 + asciidoctor 1.5.6 + asciidoctor-pdf 1.5.0.Alpha.15 + rouge 2.1.1"

2- causes an error with the environment "Ruby 2.6.0 + asciidoctor 2.0.9 + asciidoctor-pdf 1.5.0.Alpha.17 + rouge 3.3.0"
```C: /Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb: 54: in `require ': can not load such file - rouge (LoadError)```

**Comment by mojavelinux** [comment]
I'll have a look at the attached project.

**Comment by mojavelinux** [comment]
This issue is with this line:

```
include Asciidoctor
```

It's leads to a fundamental incompatibility between Rouge and how the top-level API functions are now defined in Asciidoctor. This seems to be some sort of bug in the Ruby language, but in general I just don't recommend importing a type like this because it leads to esoteric bugs. If you take that away, it will work (though you do have to qualify your references to Asciidoctor types).

**Comment by mojavelinux** [comment]
Here's the simplest script to reproduce the problem:

```
require 'asciidoctor'
include Asciidoctor
require 'rouge'
```

(It works with Asciidoctor 1.5.8 but fails with Asciidoctor 2).

**Comment by mojavelinux** [comment]
It has to do with the fact that Rouge uses load instead of require, which IMO it should NOT be doing.

**Comment by mojavelinux** [comment]
One way to fix this, if you don't want to change your code otherwise, is to use:

```
require 'asciidoctor'
include Asciidoctor
alias :load :require
require 'rouge'
```

**Comment by mojavelinux** [comment]
Per the bug in Ruby, it seems like "include" modifies the behavior of "load".

Thus, another way to solve the problem is to require rouge first:

```
asciidoctor-pdf -r ./my-rouge-theme.rb -r ./ext/myExtension.rb myDoc.adoc

```

**Comment by mojavelinux** [comment]
Aha! I see what it is. When you use `include Asciidoctor` with Asciidoctor 2.0, it promotes Asciidoctor's `load` function to the top level, which shadows the `load` function from Kernel.

But that takes me back to my point that I strongly discourage the use of `include Asciidoctor` unless you know what you are doing (and are prepared for the side effects it brings).

I'll emphasize this point in the docs.

**Comment by JBR69** [comment]
Thank you, it works fine

**Comment by mojavelinux** [comment]
Glad to hear it!
