### ISSUE TITLE
Unexpected treatment of code strings

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/asciidoctor-pdf#106]
When using something like 

    `------------------------------`

Id expect to get the exact number of underscores (this does happen with asciidoctor) but with asciidoctor-pdf

~~~~
Signed:: `_______________________________________`
Date:: `__/__/__`
Print Name:: `_______________________________________`
Position:: `_______________________________________`
~~~~

turns into 

![image](https://cloud.githubusercontent.com/assets/95874/7318824/2d73f526-ea90-11e4-85a8-d97bfd10208e.png)

**Comment by mojavelinux** [comment]
This is because you need to use the 1.5.0 syntax:

```
`+_________+`
```

You need both monospace and passthrough. Otherwise, you get italicized empty characters :)

**Comment by mojavelinux** [comment]
Feel free to reopen if this is still an issue.

**Comment by plaindocs** [comment]
That is fine - just needs documenting. But I've not checked that recently. I've been meaning to add a few of these issue to the docs, but very short on time right now.

**Comment by mojavelinux** [comment]
I kind of see this is a core Asciidoctor issue since it involves the syntax. The syntax change for 1.5.0 is covered here.

http://asciidoctor.org/docs/migration/

We should definitely add reference from the user manual to this migration guide.
