### ISSUE TITLE
Prawn error when using autowidth ("~") column

### ISSUE THREAD

**Issue by fritz-hh** [asciidoctor/asciidoctor-pdf#1060]
Using: Asciidoctor PDF 1.5.0.alpha.17 using Asciidoctor 2.0.9 [https://asciidoctor.org]

A `Prawn::Errors::CannotFit (Prawn::Errors::CannotFit)` is returned when a column is set to autowidth using `~`:

```
[cols="1,~", options="header",]
|===
|Col1|Col2
|`0x00`|`UNSPECIFIED`
|`0x01`|`OK`
|===

```

If the `~` is removed (see below), the pdf generation works without problem:

```
[cols="1,5", options="header",]
|===
|Col1|Col2
|`0x00`|`UNSPECIFIED`
|`0x01`|`OK`
|===
```

**Comment by mojavelinux** [comment]
Are you using the version of prawn-table from master? The released version
still has layout problems if memory serves me correctly.

**Comment by fritz-hh** [comment]
I am using:

```
prawn (2.2.2)
prawn-icon (2.3.0)
prawn-svg (0.29.1)
prawn-table (0.2.2)
prawn-templates (0.1.1)
```

What should I use instead?

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/Gemfile#L8

**Comment by fritz-hh** [comment]
Thanks!

**Comment by mojavelinux** [comment]
I just tested with prawn-table master and it seems like this is still a problem.

**Comment by mojavelinux** [comment]
Oh, I see. The autowidth column is simply not implemented in Asciidoctor PDF.

**Comment by mojavelinux** [comment]
Actually, the problem is that you're trying to set the column width to a value which is too small. Effectively, you're using `cols="1,99"`. Prawn does not resize a fixed-width column based on content. Thus, the result is a cannot fit error. You need to reserve more room for the first column. For example, `cols="10,~"`. This is a fundamental limitation in Prawn.

**Comment by fritz-hh** [comment]
Thanks for the clarification. I did not realize that the col width becomes a percentage when at least 1 column width is set to `~` (but it is indeed very clearly documented in the user guide)
If I remember well, in the antora output the size of the 1st column wasn't constrained to 1% (I have to check though), but seems to use the as much as needed to fit the content. Is it intended to be like that?

**Comment by fritz-hh** [comment]
OK. I just checked, the HTML output from antora.
It contains `width: 1%`, the browser (chrome and firefox) nevertheless not constrain the width to 1%, but gives that column more space.
That's what mislead me...

Below an example with 3 cols:

![image](https://user-images.githubusercontent.com/3517966/57574285-73b7eb80-7436-11e9-96ed-701e0ed7a3bd.png)

![image](https://user-images.githubusercontent.com/3517966/57574296-abbf2e80-7436-11e9-8908-73de66e2e9b6.png)
