### ISSUE TITLE
Reference to bibliography item in footnote fails

### ISSUE THREAD

**Issue by fritz-hh** [asciidoctor/asciidoctor-pdf#1061]
asciidoctor-pdf returns an error when encountering a footnote that contains a reference to a bibliography item.

**Example:**

```
Test footnote:[test <<TEST>> test]

[[references]]
[bibliography]
== References

* [[[TEST]]] test.
```

**Error message:**

```
asciidoctor: ERROR: failed to parse formatted text: Test <a name="_footnoteref_1"> </a><sup>[<a anchor="_footnotedef_1">1</a>]</sup></a> test]
asciidoctor: ERROR: failed to parse formatted text: <a name="_footnotedef_1"> </a>[<a anchor="_footnoteref_1">1</a>] test <a anchor="TEST">[TEST
```

**Used version:**

`Asciidoctor PDF 1.5.0.alpha.17 using Asciidoctor 2.0.9 [https://asciidoctor.org]`

**Comment by mojavelinux** [comment]
This is not a use case that is supported in AsciiDoc in general. Try it with HTML output and you will see it doesn't work there either.

**Comment by fritz-hh** [comment]
I am not sure to understand what you mean.
The HTML generated with antora seems to work well in this regard (href in the footnote working well and displayed as expected in chrome) 

With the atom asciidoctor-preview plugin I get:

![image](https://user-images.githubusercontent.com/3517966/57574433-5a646e80-7439-11e9-8d3c-0622636fffdf.png)

```
<body>
<div id="wrapper">
<div class="article">
<div id="__asciidoctor-preview-1__" class="paragraph">
<p>Test <sup class="footnote">[<a id="_footnoteref_1" class="footnote" href="#_footnotedef_1" title="View footnote.">1</a>]</sup></p>
</div>
<div class="sect1">
<h2 id="references">References</h2>
<div class="sectionbody">
<div id="__asciidoctor-preview-2__" class="ulist bibliography">
<ul class="bibliography">
<li>
<p><a id="TEST"></a>[TEST] test.</p>
</li>
</ul>
</div>
</div>
</div>
<div id="footnotes">
<hr>
<div class="footnote" id="_footnotedef_1">
<a href="#_footnoteref_1">1</a>. test <a href="#TEST">[TEST]</a> test
</div>
</div>
</div>
</div>
</body>
```

Of course I can easily find a workaround for this wrt the PDF generation.

I thought, its always better to report issues. even minor ones :-)
I was surprised by the error message and the PDF output (see PDF output of the footnote part for a similar example below), given that I did not detect any issue in the antora output.

![image](https://user-images.githubusercontent.com/3517966/57574553-897bdf80-743b-11e9-8a34-7d8596f7bcbc.png)

**Comment by mojavelinux** [comment]
I figured out how to solve this in the PDF converter. PR on the way.

**Comment by mojavelinux** [comment]
> The HTML generated with antora seems to work well in this regard

Not in Asciidoctor 2.

**Comment by mojavelinux** [comment]
> I thought, its always better to report issues. even minor ones :-)

I'm glad you reported it. You have uncovered a difference between the converters that will need to be addressed. We can start with PDF. HTML is going to be another challenge.

**Comment by mojavelinux** [comment]
(Right now, not all the platforms are using the same version of Asciidoctor core, which is why we can't always assume they will produce the same result).

**Comment by fritz-hh** [comment]
That was quick ! Thanks

**Comment by mojavelinux** [comment]
I'll have a new release out soon to test.

**Comment by fritz-hh** [comment]
I just tested it with `v1.5.0.alpha.18`
It works great :-)
Thanks a lot!

**Comment by mojavelinux** [comment]
Thanks for confirming the fix!
