### ISSUE TITLE
in `<class:Converter>': uninitialized constant Asciidoctor::Converter (NameError) when trying to run asciidoctor-pdf

### ISSUE THREAD

**Issue by erik-brangs** [asciidoctor/asciidoctor-pdf#107]
I've cloned the asciidoctor-pdf GitHub repository and used bundler to install the dependencies. However, asciidoctor-pdf doesn't seem to work out of the box. I'm using Ubuntu 15.04 and getting the error message below:

```
git-repos/asciidoctor-pdf/lib/asciidoctor-pdf/converter.rb:17:in `<class:Converter>': uninitialized constant Asciidoctor::Converter (NameError)
	from git-repos/asciidoctor-pdf/lib/asciidoctor-pdf/converter.rb:16:in `<module:Pdf>'
	from git-repos/asciidoctor-pdf/lib/asciidoctor-pdf/converter.rb:15:in `<module:Asciidoctor>'
	from git-repos/asciidoctor-pdf/lib/asciidoctor-pdf/converter.rb:14:in `<top (required)>'
	from git-repos/asciidoctor-pdf/lib/asciidoctor-pdf.rb:3:in `require_relative'
	from git-repos/asciidoctor-pdf/lib/asciidoctor-pdf.rb:3:in `<top (required)>'
	from ./bin/asciidoctor-pdf:3:in `require_relative'
	from ./bin/asciidoctor-pdf:3:in `<main>'
```

What am I doing wrong?

**Comment by mojavelinux** [comment]
I'm not sure what your Ruby setup is, but have you tried `bundle exec`?

```
$ bundle exec ./bin/asciidoctor-pdf README.adoc
```

I use RVM with custom gemsets, which is why it isn't necessary for me to use `bundle exec`. However, if you aren't using RVM, this is probably required.

**Comment by mojavelinux** [comment]
There's a chance you have Asciidoctor installed already (maybe 0.1.4) and without `bundle exec`, Ruby gets confused about which Asciidoctor to load.

**Comment by erik-brangs** [comment]
Thanks, it works using ```bundle exec```. I already had Asciidoctor 1.5.2 installed.

Should the README be updated to recommend using bundler for execution when it was used during installation?

**Comment by mojavelinux** [comment]
> Should the README be updated to recommend using bundler for execution when it was used during installation?

Yes. It should mention that if you aren't using a Ruby manager like RVM, then you should use `bundle exec` in front of the command. Would you like to send a pull request?
