### ISSUE TITLE
Auto-numbered callouts not rendered in source block

### ISSUE THREAD

**Issue by hakuseki** [asciidoctor/asciidoctor-pdf#1076]
When having callouts in code and typed as auto-numbered callouts they do not get rendered in the source block, only below.

```yaml
importer:
    startup: true
    sources: # <.>
        - name: ACME
          split: row
          type: xml
```
```java
public class Source {
    /**
     * The Type.
     */
    @NonNull
    private String type; // <.>
    /**
     * The Split.
     */
    @NonNull
    private String split; // <.>
    /**
     * The Name.
     */
    @NonNull
    private String name; // <.>
}
```

Java and yaml tested with rouge and coderay as highlighters

MacOs
Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Asciidoctor PDF 1.5.0.alpha.17 using Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

*** LOCAL GEMS ***

asciidoctor-rouge (0.4.0)
rouge (3.3.0)
coderay (1.1.2)
![Legal_Reporting_Module_Data_Importer](https://user-images.githubusercontent.com/5478862/58318436-05046600-7e18-11e9-9f64-d7f400355304.png)

**Comment by hakuseki** [comment]
![Legal_Reporting_Module_Data_Importer](https://user-images.githubusercontent.com/5478862/58318532-3f6e0300-7e18-11e9-88ba-d5ceda22020a.png)
Submitting a more accurate screenshot

**Comment by mojavelinux** [comment]
This definitely looks like an oversight.

**Comment by hakuseki** [comment]
When rendering using maven I get this

```
[INFO] asciidoctor: ERROR: README.adoc: line 573: include file not found: /Users/mgr/IdeaProjects/dataimporter/src/main/java/java/com/css/tradechannel/dataimporter/beans/Source.java
[INFO] asciidoctor: WARN: README.adoc: line 575: no callout found for <1>
[INFO] asciidoctor: WARN: README.adoc: line 576: no callout found for <2>
[INFO] asciidoctor: WARN: README.adoc: line 577: no callout found for <3>
[INFO] asciidoctor: ERROR: README.adoc: line 582: include file not found: /Users/mgr/IdeaProjects/dataimporter/src/main/java/resources/LegalReportingModuleDataImporter/application.yml
[INFO] asciidoctor: WARN: README.adoc: line 584: no callout found for <1>
```

These are the rows shown in screenshot
