### ISSUE TITLE
Front cover not generated

### ISSUE THREAD

**Issue by jstxu** [asciidoctor/asciidoctor-pdf#1081]
Hi, on the last build 1.5.0.alpha.17 the generation of the front cover or title page stopped working.

What I get now is on the first page of the document, the title on top and the ToC just below. Instead of having the front cover with the :title-logo-image: on the first page and the ToC on the second.

If I port back to 1.5.0.alpha.16 it works again. 

I don't see any errors in the generation of the pdf though.

Thank you

**Comment by mojavelinux** [comment]
What you are asking about is the title page, not the cover page. And you are correct. In the last release, the default doctype of article is now honored. An article does not have a title page. Instead, the document title (doctitle) is placed at the top of the first page with the TOC below it. If you want to have a dedicated title page, you either need to set the doctype to book or set the title-page attribute, which will revert to the old behavior.

doctype=book option

```
= Document Title
:doctype: book
:title-logo-image: image:logo.png[]

content
```

title-page attribute

```
= Document Title
:title-page:
:title-logo-image: image:logo.png[]

content
```

This change is covered in the release notes and in the [theming guide](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#theme-related-document-attributes).

**Comment by jstxu** [comment]
Thanks @mojavelinux :)
