### ISSUE TITLE
How to install from source

### ISSUE THREAD

**Issue by rockeet** [asciidoctor/asciidoctor-pdf#1082]
I can not find instructions about how to install `asciidoctor-pdf` in README.md, there are lots of bundle bundle ....

**Comment by mojavelinux** [comment]
It's README.adoc ;)

I've added a section that explains how to install the application.

https://github.com/asciidoctor/asciidoctor-pdf#install-the-application-optional

You still need bundler, since that's how the application is built.

Btw, a new release is on its way.

**Comment by mojavelinux** [comment]
Please reopen or file another issue if the updated information is still not sufficient.
