### ISSUE TITLE
table stripeing broken in alpha.17

### ISSUE THREAD

**Issue by terefang** [asciidoctor/asciidoctor-pdf#1083]
table stripeing broken in 1.5.0-alpha.17 environment:

``
<asciidoctor.maven.plugin.version>1.5.8</asciidoctor.maven.plugin.version>
<asciidoctorj.pdf.version>1.5.0-alpha.17</asciidoctorj.pdf.version>
<asciidoctorj.version>1.6.0</asciidoctorj.version>
<asciidoctorj.diagram.version>1.5.11</asciidoctorj.diagram.version>
<jruby.version>9.1.17.0</jruby.version>
``

OR

``
<asciidoctor.maven.plugin.version>1.6.0</asciidoctor.maven.plugin.version>
<asciidoctorj.pdf.version>1.5.0-alpha.17</asciidoctorj.pdf.version>
<asciidoctorj.version>1.6.2</asciidoctorj.version>
<asciidoctorj.diagram.version>1.5.12</asciidoctorj.diagram.version>
<jruby.version>9.2.6.0</jruby.version>
``

verified against earlier versions:

``
<asciidoctor.maven.plugin.version>1.5.8</asciidoctor.maven.plugin.version>
<asciidoctorj.pdf.version>1.5.0-alpha.15</asciidoctorj.pdf.version>
<asciidoctorj.version>1.6.0</asciidoctorj.version>
<asciidoctorj.diagram.version>1.5.11</asciidoctorj.diagram.version>
<jruby.version>9.1.17.0</jruby.version>
``

AND

``
<asciidoctor.maven.plugin.version>1.6.0</asciidoctor.maven.plugin.version>
<asciidoctorj.pdf.version>1.5.0-alpha.16</asciidoctorj.pdf.version>
<asciidoctorj.version>1.6.2</asciidoctorj.version>
<asciidoctorj.diagram.version>1.5.12</asciidoctorj.diagram.version>
<jruby.version>9.2.6.0</jruby.version>
``

**Comment by mojavelinux** [comment]
It's not broken, it's just not enabled by default anymore. You can enable it per table using the stripes table attribute or for all tables using the `table-stripes` document attribute. See https://asciidoctor.org/docs/user-manual/#striping for details.

**Comment by mojavelinux** [comment]
Please reopen if you need more information.

**Comment by terefang** [comment]
ok upgraded and put ":table-stripes: even" as document option.
still no stripes detected in pdf output

".stripes-even" does not work either in pdf output
".stripes=even" does not work either in pdf output

only "stripes=even" in the table does work in pdf output

hmmm ... seam to be a documentation bug:
":stripes: even" as document option does actually work.

**Comment by mojavelinux** [comment]
If you're using AsciidoctorJ < 2.0, then it's `:stripes: even`. If you're using AsciidoctorJ 2 and up, then it's `:table-stripes: even`. I strongly recommend upgrading AsciidoctorJ.

**Comment by mojavelinux** [comment]
You are correct that the role shorthand doesn't work. That's intended for HTML only.

**Comment by terefang** [comment]
i have upgraded to:
<asciidoctor.maven.plugin.version>2.0.0-RC.1</asciidoctor.maven.plugin.version>
<asciidoctorj.version>2.0.0</asciidoctorj.version>
<asciidoctorj.pdf.version>1.5.0-alpha.18</asciidoctorj.pdf.version>
<asciidoctorj.diagram.version>1.5.18</asciidoctorj.diagram.version>
<jruby.version>9.2.7.0</jruby.version>

seams to be the problem that the user-manual and themeing-guide versions are not easiely recognizeable (at leat for me).

https://asciidoctor.org/docs/user-manual/ hits at version 1.5.6.2, but the striping section seams to be at 2.0.

for docs/theming-guide.adoc you have to loop tru commit logs to for the proper version since some needed updates happened after the (pre-)released version.

but i am ok with it now, as it needs to stabilize in the 2.0 branch.

many thanks for the progress !

**Comment by mojavelinux** [comment]
Getting the documentation in alignment is something we're working on (call it our summer project). Then it will be very clear which documentation goes with which version. We're also tightening release schedules so there is less stuff hanging out in master. Easier said than done, but we're on the path.
