### ISSUE TITLE
Page layout (landscape/portrait) stuck in landscape.

### ISSUE THREAD

**Issue by dalemartin** [asciidoctor/asciidoctor-pdf#1091]
When using Asciidoctor PDF backend, 
```
[.landscape]
<<<
``` 
works to flip the page, but 
```
[.portrait]
<<<
``` 
doesn't flip it back.

The `[.landscape]` and `[.portrait]` directives are in a nested document; observed behavior is (obviously) in the document that includes it.

This is my setup (Windows 10):
```bash
$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

$ asciidoctor -v
Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:IBM437 ex:IBM437)

$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.18 using Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:IBM437 ex:IBM437)
```

**Comment by mojavelinux** [comment]
:eyes: Looks like we need a new test!

**Comment by mojavelinux** [comment]
I can explain what's happening. If you hit a page break, but the page break falls at a natural page break, the page break is skipped, but so is the directive. We need to check for this case. I'll add a test case for both scenarios (with and without this condition being met).

**Comment by mojavelinux** [comment]
I've submitted a PR (#1092) if you'd like to try it.

**Comment by dalemartin** [comment]
Thanks for the quick changes! Do you want feedback comments on the PR testing here or on the PR discussion?
