### ISSUE TITLE
Allowing borders on each of the columns in the running content

### ISSUE THREAD

**Issue by marcdexet-cnrs** [asciidoctor/asciidoctor-pdf#1093]
Allowing borders on each of the columns in the running content.

It's the follow up of  #1075 into a separate issue as asked by @mojavelinux .

**Comment by mojavelinux** [comment]
I did look into this briefly. It's not terribly hard to add the border, but it does open up a lot of edge cases. For example, should the padding for the column be inside or outside the border (my guess is outside, but sometimes you need both). It's also not clear whether the border should extend to the height of the periphery, or within the content area (my guess is the content area). Even then, should it include the vertical padding or not.

**Comment by marcdexet-cnrs** [comment]
To my humble opinion, choose the simplest solution : each column could be "boxed" without margin and little padding.
If you have the possibility to create as much options as you describe (margin, padding, ...) feel free to add.

Just remember from past discussion people just need to get a kind of tabular header in running content to comply to document-look policy, just as spreadsheet cells with border.

**Comment by mojavelinux** [comment]
I understand what you're suggesting. Just keep in mind that code must be precise, so the exact specifications matter a lot. We can't be hand-wavy about it or else we end up with something that doesn't meet expectations.

**Comment by marcdexet-cnrs** [comment]
I understand for sure, writing expectations is a part of my job, but who is legitimate to write expectations ? As you wrote in the current configuration is a kind of a trick, I don't ask too much.

My expectations would the following :

* Allow to write the 3 columns as a bordered row and cell in a table
* Allow choice of color, thickness and style
* Allow padding
* Allow margin for the row
* Don't bother with margin between columns.

That's my expectations.

**Comment by mojavelinux** [comment]
Thanks! That gives me a much better idea, and something to ask follow-up about.

> Allow padding; Allow margin for the row

Currently, the columns (which are effectively cells) each have a padding, as defined by `footer_padding` and `header_padding`). Are we to assume that the column line extends the entire height of the periphery, or should the height be confined inside the top and bottom padding?

I'm not really prepared to add new padding controls (or margin, for that matter), so really the choice is one of those two right now. I suppose we could do an outer margin in a separate issue (how far the periphery is offset from the edge of the page; top for header, bottom for footer).

**Comment by marcdexet-cnrs** [comment]
`footer_padding` and `header_padding` are enough.
Your assumptions are mines :  the column line extends the entire height of the periphery.

Let just try these and we will see for outer margin later.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
After doing some testing, I determined that we'll need some sort of horizontal spacing between the column rule and the content. So I also introduced column_rule_spacing to control this. It basically makes room for the column rule.
