### ISSUE TITLE
Asciidoctor-pdf fails when used with Asciidoctor 1.5.5

### ISSUE THREAD

**Issue by dohliam** [asciidoctor/asciidoctor-pdf#1095]
Fresh install of asciidoctor-pdf fails on attempting to convert any file with the following error:

    uninitialized constant PDF::Core::Page::ZERO_INDENTS
      Use --trace for backtrace

I see that this issue was supposed to have been fixed in #775 and #883.

This is on updated version of Ubuntu Bionic.

ruby-prawn:

      Installed: 2.1.0+dfsg-1

`asciidoctor -v`:

    Asciidoctor 1.5.5 [http://asciidoctor.org]
    Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

`asciidoctor-pdf -v`

    Asciidoctor PDF 1.5.0.alpha.18 using Asciidoctor 1.5.5 [http://asciidoctor.org]
    Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

Backtrace (`asciidoctor-pdf --trace basic-example.adoc`):

    Traceback (most recent call last):
	    18: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	    17: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	    16: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/bin/asciidoctor-pdf:31:in `<top (required)>'
	    15: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:87:in `invoke!'
	    14: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:87:in `each'
	    13: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:95:in `block in invoke!'
	    12: from /usr/lib/ruby/vendor_ruby/asciidoctor.rb:1506:in `convert'
	    11: from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1050:in `convert'
	    10: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:127:in `convert'
	    9: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:152:in `convert_document'
	    8: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:309:in `init_pdf'
	    7: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:309:in `call'
	    6: from /usr/lib/ruby/vendor_ruby/prawn/document.rb:221:in `initialize'
	    5: from /var/lib/gems/2.5.0/gems/prawn-templates-0.1.1/lib/prawn/templates.rb:17:in `initialize_first_page'
	    4: from /usr/lib/ruby/vendor_ruby/prawn/document.rb:633:in `initialize_first_page'
	    3: from /var/lib/gems/2.5.0/gems/prawn-templates-0.1.1/lib/prawn/templates.rb:27:in `start_new_page'
	    2: from /usr/lib/ruby/vendor_ruby/prawn/document.rb:263:in `start_new_page'
	    1: from /usr/lib/ruby/vendor_ruby/prawn/document.rb:263:in `new'
    /var/lib/gems/2.5.0/gems/prawn-templates-0.1.1/lib/pdf/core/page.rb:13:in `initialize': uninitialized constant PDF::Core::Page::ZERO_INDENTS (NameError)

Installing newer version of prawn gem did not resolve the issue. (Although from #775 it seems that there are issues with newer versions of prawn in any case.)

What _did_ work was installing asciidoctor-pdf from source using bundler (following the instructions in the [README](https://github.com/asciidoctor/asciidoctor-pdf#development)). Everything works fine with this version of asciidoctor-pdf.

`bundle exec asciidoctor-pdf -v`:

    Asciidoctor PDF 1.5.0.beta.1.dev using Asciidoctor 2.0.10 [https://asciidoctor.org]
    Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

This made it clear that the problem was likely the distro version of Asciidoctor (1.5.5 vs. 2.0.10). Removing the repository version of Asciidoctor and reinstalling from the gem using `gem install asciidoctor` finally fixed the problem with asciidoctor-pdf.

Since the problem has now been resolved I considered not submitting this issue. However, the cause of the issue was in no way obvious until the end of the process of writing up this bug report, so this may be helpful to others who may have unwittingly installed a much older version of Asciidoctor from their distro repository.

Perhaps a warning somewhere in the install documentation about needing the latest version of Asciidoctor might help -- the installation instructions specify that asciidoctor-pdf requires at least Asciidoctor 1.5.3, but as the above shows, the current version does not seem to work with versions as new as Asciidoctor 1.5.5.

**Comment by mojavelinux** [comment]
Thanks for pointing this out. I can say for certain this has nothing to do with the Asciidoctor version because this constant is not in Asciidoctor nor does Asciidoctor refer to it. This is a problem with how Asciidoctor PDF is packaged, and clearly that packaging is not running the test suite (as it should).

> /var/lib/gems/2.5.0/gems/prawn-templates-0.1.1/lib/pdf/core/page.rb:13:in `initialize': uninitialized constant PDF::Core::Page::ZERO_INDENTS (NameError)

In fact, this bug isn't even in Asciidoctor PDF. It's coming from ruby-pdf-core, which is not compatible with prawn-templates. That constant is not defined in 0.6.1:

https://github.com/prawnpdf/pdf-core/blob/0.6.1/lib/pdf/core/page.rb

but it is installed in 0.7.0

https://github.com/prawnpdf/pdf-core/blob/0.7.0/lib/pdf/core/page.rb

So this is definitely a problem with the packaging of asciidoctor-pdf on Ubuntu.

> the installation instructions specify that asciidoctor-pdf requires at  least Asciidoctor 1.5.3, but as the above shows, the current version  does not seem to work with versions as new as Asciidoctor 1.5.5.

This is not true. The Asciidoctor PDF verifies and proves that Asciidoctor PDF works with Asciidoctor 1.5.3 and above.

**Comment by mojavelinux** [comment]
Please report this bug in Ubuntu (or wherever the issue tracker is for the ruby-prawn-templates and/or ruby-pdf-core package).

**Comment by dohliam** [comment]
Thanks for clarifying that this is an issue with the Ubuntu package. It was difficult to get a working install of asciidoctor-pdf as a result so perhaps this will still help someone else if they run into the same issue and search here. Will take a look at who is responsible for the relevant packages and report this issue there when I have some time.

**Comment by mojavelinux** [comment]
Indeed. Having the information reported here is an important sign post. We can add the link to the issue in Ubuntu too, once it's available. Thanks again!
