### ISSUE TITLE
ADOC Theming Caption Color issue

### ISSUE THREAD

**Issue by DanielGrigoras** [asciidoctor/asciidoctor-pdf#1096]
I just noticed that the text marked up as code within a table caption (.\`\*Execute Buffer\*\` Payload Bytes) was not colored as per the ADOC Theme together with the rest of the table caption, as shown in the screen capture below.

![image](https://user-images.githubusercontent.com/15011993/59272842-8a34ab00-8c5f-11e9-985d-de45c02d9270.png)

**Comment by mojavelinux** [comment]
That's per design. The code span (aka literal) is colored in a redish color by default. If you want a different color, set it in your theme. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-literal

**Comment by mojavelinux** [comment]
> ADOC

Technically it's the Ascidoctor PDF theme, though since this repository is about Asciidoctor PDF, you can just say theme ;)

**Comment by mojavelinux** [comment]
This can now be resolved by defining a custom role in the theme and applying it to the monospaced text.

```
extends: default
roles:
  caption-code:
    font-color: ~
```

```
.[.caption-code]`Execute buffer` Payload Bytes
|===
|content
|===
```
