### ISSUE TITLE
asciidoctor does not render table correctly: one row per page

### ISSUE THREAD

**Issue by mahmoudparsian** [asciidoctor/asciidoctor-pdf#1097]
I am using the following to generate a PDF for my book:

asciidoctor --backend=pdf --require=asciidoctor-pdf  --destination-dir=_build --out-file=book.pdf master.adoc; \

But tables are not rendered correctly: it puts one row per page (which looks very ugly).

this is my sample table:

.Performance for DNA Base Count
|===
|Input Data (in bytes) | Version-1   | Version-2   | Version-3
|  253,935,557         |  72 seconds |  27 seconds | 18 seconds
|1,095,573,358         | 258 seconds |  79 seconds | 57 seconds
|===

But when I view the table in AsccidocFX, it looks fine.
Any idea how can I solve this problem.

Thanks,
Mahmoud

**Comment by mojavelinux** [comment]
Mahmoud, I'm unable to reproduce your problem. Can you tell me which version of Asciidoctor PDF you are using?

```
asciidoctor-pdf -v
```

Are you sure you are able to reproduce it strictly with the sample document you provided? If so, could you also attach a PDF that shows how it looks?

**Comment by mahmoudparsian** [comment]
Hello & Thank you very much!

$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.17 using Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

I chopped off most of the chapters: now table row heights are shrunk  a little bit, but still does not look good. Sample tables are included.

[book.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3279842/book.pdf)

**Comment by mojavelinux** [comment]
I think you are hitting this issue: https://github.com/asciidoctor/asciidoctor-pdf/issues/1053 You're one version back from the latest release, which fixes this bug. Could you try alpha.18?

It appears you're using a custom theme. If upgrading doesn't fix the problem, could you share that theme file (perhaps using a gist or a temporary repository on GitHub)?

**Comment by mahmoudparsian** [comment]
Thank you so much for looking into this issue.

In my mac book, how do I upgrade  to alpha.18?

thank you again!
best,
Mahmoud

**Comment by mahmoudparsian** [comment]
Hello Dan, 

Following your instructions: the tables look GREAT!
THANK YOU SO MUCH!!!

$ sudo gem install asciidoctor-pdf --pre
Password:
Fetching: asciidoctor-pdf-1.5.0.alpha.18.gem (100%)
Successfully installed asciidoctor-pdf-1.5.0.alpha.18
Parsing documentation for asciidoctor-pdf-1.5.0.alpha.18
Installing ri documentation for asciidoctor-pdf-1.5.0.alpha.18
Done installing documentation for asciidoctor-pdf after 1 seconds

 $ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.18 using Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

**Comment by mahmoudparsian** [comment]
Thank you again!

**Comment by mojavelinux** [comment]
I'm glad to hear it! Thanks for confirming the fix.

**Comment by mahmoudparsian** [comment]
Dan, Thank you very much!
