### ISSUE TITLE
Table cell padding setting not affect table header cells

### ISSUE THREAD

**Issue by Glaberrd** [asciidoctor/asciidoctor-pdf#1098]
When working with version:
```
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 2.0.5 [https://asciidoctor.org]
Runtime Environment (ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
Following setting in custom theme:
```
table:
  cell:
    padding: 3
```
Was affecting also cells in table header row. That is not the case for later versions - table header cells padding can't be customized anymore.

**Comment by mojavelinux** [comment]
You're absolutely right. Somehow, that got dropped. I'll fix it, add support for table_head_cell_padding as well, then add a test.

**Comment by mojavelinux** [comment]
Of course, if you'd like to have a go at it, feel free!

Here's the logic needed in the head section:

```
padding: theme.table_head_cell_padding || theme.table_cell_padding,
```

**Comment by Glaberrd** [comment]
Unfortunately, I don't possess any Ruby skills so it would be hard to provide any solution from my side (not even saying about proper one with tests and support for table_head_cell_padding)

**Comment by mojavelinux** [comment]
No worries. I just wanted to make sure I didn't step in front of you if it's something you could do.

**Comment by mojavelinux** [comment]
This got missed because the reference PDF for the chronicles example was created after the regression occurred. Had it been the other way around, the visual test would have caught it. But the test suite will catch any future regression.
