### ISSUE TITLE
Running header content missing

### ISSUE THREAD

**Issue by dalemartin** [asciidoctor/asciidoctor-pdf#1099]
Any text content defined by `header-recto-[left|right|center]-content` in my theme.yml has disappeared since upgrading from `1.5.0.alpha.17` to `1.5.0.alpha.18`. 

Windows 10 setup for broken version:
```
$ asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.alpha.18 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:IBM437 ex:IBM437)
```

This build seems fine (pulled `master` branch at time of post) so maybe not worth fixing?
```
$ bundle exec asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.beta.1.dev using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:IBM437 ex:IBM437)
```

**Comment by mojavelinux** [comment]
This is a known issue with the alpha.18 release which has been fixed in master (and the upcoming beta.1 release). See #1087 for an explanation.

**Comment by dalemartin** [comment]
Thanks @mojavelinux!
