### ISSUE TITLE
Plantuml diagram links are blank

### ISSUE THREAD

**Issue by gregLibert** [asciidoctor/asciidoctor-pdf#1105]
Hi,
I've got an issue when generating plantuml diagram with html links: they are all blanks as show in the picture above.

![asciidoctor-pdf_blank](https://user-images.githubusercontent.com/16623956/59691803-ed848700-91e3-11e9-9238-d7e2440d1321.png)

It's working with html generation as show in the picture above:

![asciidoctor-pdf_normal](https://user-images.githubusercontent.com/16623956/59691869-0b51ec00-91e4-11e9-8d33-6b8a1cc522fb.png)

The following attributes are used for plantuml block definition:
```
[plantuml, debit_then_credit, svg, opts=interactive]
```
Furthermore, I'm using the following version/environment:
```
asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.alpha.18 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
Please provide the diagram source so I can test.

What I can tell you right away is that prawn-svg does not support HTML embedded in the SVG. If there's a link, it must be defined using a xlink:href.

A browser doesn't have this restriction because it can understand arbitrary HTML in an SVG because it's an HTML environment. In other words, the browser is not really rendering an SVG so much as enhanced HTML.

**Comment by gregLibert** [comment]
Thank you for your answer.
Here is a code sample directly copied from [plantuml sample](http://plantuml.com/fr/link):
```asciidoc
[plantuml, test_link, svg, opts=interactive]
----
actor Bob [[http://plantuml.com/sequence]]
actor "This is [[http://plantuml.com/sequence Alice]] actor" as Alice
Bob -> Alice [[http://plantuml.com/start]] : hello
note left [[http://plantuml.com/start]]
  a note with a link
end note
Alice -> Bob : hello with [[http://plantuml.com/start{Tooltip for message} some link]]
note right [[http://plantuml.com/start]] : another note
note left of Bob
You can use [[http://plantuml.com/start links in notes]] also.
end note
----
```
Do you have any idea of how I could include xlink:href in svg diagram through plantuml ?

**Comment by mojavelinux** [comment]
plantuml is putting an `<a>` tag around the text (which happens to use the `xlink:href` attribute). It looks the fact that this results in blank text is a bug / shortcoming in prawn-svg. I could manipulate the SVG data to strip the enclosing `<a>` tag, but it think it would be better to see if prawn-svg would be willing to address this.

I've filed an issue in prawn-svg to discuss. See https://github.com/mogest/prawn-svg/issues/111

**Comment by mojavelinux** [comment]
This has been implemented upstream. We're now just waiting on a release.
