### ISSUE TITLE
Running content image overlaps with border

### ISSUE THREAD

**Issue by programming-wolf** [asciidoctor/asciidoctor-pdf#1107]
I realised today, that, if I use an image in the header, it overlaps with the border. 

<img width="1075" alt="image_overlap" src="https://user-images.githubusercontent.com/30000147/59767612-ef614f80-92a2-11e9-8b88-a17e2fba6926.png">

Is this a bug? Or is it because of the image's size? If so, can I adjust the padding/margin of the image?

**Comment by mojavelinux** [comment]
You either need to adjust the image size or adjust the size of the header. One way to adjust the size of the image is to use the `fit` attribute.

* fit=contain
* fit=scale-down
* or pdfwidth=1in

see https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#images-1

I'll leave this open since there's currently no test for this and I'd like to add one or two.

**Comment by programming-wolf** [comment]
Great, thanks for the reply! I’ll test that. I already reduced the image size a bit, but will give it a shot with an even smaller size and the additional parameter.

**Comment by mojavelinux** [comment]
Great!

And by reduce the image size, I was talking about an explicit width, not necessarily the implicit size of the image (though you are free to do both).

**Comment by programming-wolf** [comment]
I also meant using `width` (which I’m already doing) 🙂

**Comment by mojavelinux** [comment]
Great! Though, it's better to use `pdfwidth` when controlling the width for PDF.

**Comment by mojavelinux** [comment]
I submitted a PR with a bunch of tests. It doesn't cover all scenarios, but at least it's hitting a good chunk of the functionality now.

**Comment by programming-wolf** [comment]
I tried the `scale-down` configuration (in combination with `width`) and the image still overlaps by one or two pixels (right third of the image):
<img width="578" alt="Screenshot 2019-06-21 at 09 14 52" src="https://user-images.githubusercontent.com/30000147/59905009-3ebf9100-9405-11e9-8c46-d82c63dc26b9.png">

The image is definitely not too big. If I omit the `width` attribute, `scale-down` makes three times as big as I want it to have.

**Comment by mojavelinux** [comment]
Can you please provide a sample project? I have no way of testing what it is you're talking about based on the information you've provided.

**Comment by programming-wolf** [comment]
Yes, sure, apologies for not doing this in the first place. I'm developing a template for multiple documents for the iSAQB (www.isaqb.org). I am currently trying to properly place the logo in the top right corner of the header. That version is currently available in this branch:
https://github.com/isaqb-org/pdf-theme/tree/15-adjust-font-sizes

The configuration to build a pdf with that template is as follows:
```
:doctype: book
:icons: font
:sectnumlevels: 2
:imagesdir: images
:chapter-label: 
:curriculum-header-title: iSAQB-Curriculum
```

The template repository is here: https://github.com/isaqb-org/advanced-template

Does this help?

**Comment by mojavelinux** [comment]
Thanks! I'll have a look.

**Comment by mojavelinux** [comment]
I tried your theme and it works exactly as expected with fit or pdfwidth.

Here's the output when I used fit=scale-down.

[index.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3324462/index.pdf)

If you wanted a specific size, you can use pdfwidth. For example, pdfwidth=2cm. The width attribute is not really relevant in PDF (though it does get used as a fallback).

Keep in mind I am using 1.5.0.beta.1, not 1.5.0.alpha.17 (the later of which is very outdated at this point).

If you can demonstrate that there is still an issue, please open a separate issue with a reproducible case.

**Comment by mojavelinux** [comment]
Are you specifically asking why the image overlaps the border? If that's the case, you need to add just a bit of bottom padding. The border is considered part of the content area.

```
header:
  height: 2cm
  image_vertical_align: bottom
  vertical_align: bottom
  border_color: dddddd
  padding: [0, 0, 0.5, 0]
  ...
```

**Comment by mojavelinux** [comment]
So to answer your original question, yes, the border is considered part of the content area. I suppose we could subtract that out when computing the size of the content area.

**Comment by mojavelinux** [comment]
I get it now. Opened as #1109.

**Comment by programming-wolf** [comment]
Very nice, thank you. I somehow didn't see that padding was possible in the header, too. 
I'm using 1.5.0alpha.18 for my tests, I eagerly wait for the beta release. 😃
