### ISSUE TITLE
Version as variable on title page not working

### ISSUE THREAD

**Issue by RobertdeLeeuw-IHomer** [asciidoctor/asciidoctor-pdf#1112]
When generating PDF with asciidoctor-pdf I want to have the version of the document as a variable, as it is used more often in the document it self.

My document starts with:

    :toc: macro
    :toclevels: 4
    :sectnumlevels: 4
    :numbered:
    :pagenums:
    :year: 2019
    :revision_date: 06-21-{year}
    :document_ver: 3.0

    = Document Title: Document Subtitle
    https://www.server.com
    {document_ver}, {revision_date}

But this does not work, the variable is not seen, the output of the last line is: 

    https://www.server.com
    Version , 06-21-2019

If I dont use a variable it works:

    = Document Title: Document Subtitle
    https://www.server.com
    3.0, {revision_date}

result: 

    https://www.server.com
    Version 3.0, 06-21-2019

I did some testing. Any none numeric characters before any number in the version/date line of the title page will not be shown.

So my guess is that a variable is not seen as a number, but as a string.
I tried to switch the 2 lines around, I dont mind which line comes first:

    = Document Title: Document Subtitle
    Version: {document_ver}, {revision_date}
    https://www.server.com

Then the version line is correct, but the url is not visible.
Result: 

    Version 3.0, 06-21-2019
    https

The semicolon make asciidoctor-pdf stop.
When I remove the semicolon the result is:

    Version 3.0, 06-21-2019
    https//www.server.com

Is there a workaround to have the version/date line show the entire string?

**Comment by mojavelinux** [comment]
The version has to start with a "v" (which gets dropped). That's how the parser knows it's the version.

In other words:

```
= Document Title
Author Name
v3.0, 2019-06-21

{revnumber}
```

If you are struggling to get the implicit line to work, just switch to explicit attribute names:

```
= Document Title
Author Name
:revnumber: 3.0
:revdate: 2019-06-21
```

Please consult the documentation for the header for further details. https://asciidoctor.org/docs/user-manual/#doc-header

**Comment by RobertdeLeeuw-IHomer** [comment]
Thanks for the quick response, explicit attribute names works for me!!

**Comment by mojavelinux** [comment]
:+1:
