### ISSUE TITLE
The title page background image is applied to wrong pages

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1144]
The title page background image (at least the one defined by the title-page-background-image document attribute) is being applied to the page after the title page instead of the title page itself. In fact, it seems to be all recto pages.

There is a missing test for this scenario.

**Comment by akhayyat** [comment]
Is the fix released? I tried asciidoctor-pdf 1.5.0.beta.1, but this issue was not resolved in that version.

**Comment by mojavelinux** [comment]
Not yet. I'm finishing one last issue, then I'll put out the beta.2 release. My goal is the end of the week, sooner if I can.
