### ISSUE TITLE
Page numbers in the TOC should extend from wrapped line

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1152]
If an entry in the TOC wraps, the page number (and the dots leading up to it) should extend from the last line instead of the first line. In other words, it should look like this:

```
A very long section title that
wraps ........................ 1
```

**Comment by mojavelinux** [comment]
See #635 for a screenshot of how it should work.

**Comment by mojavelinux** [comment]
I believe the way to implement this is to register a "render in front" callback on the last fragment of the section title. That callback should record the cursor position at the end of the last word. The page number should then extend from there horizontally to the right margin, with the dots leading up to them.

The callback is necessary since Prawn does not provide any other way to detect where the last character in wrapped text was printed on the page.

**Comment by habamax** [comment]
Thx! Looks good!

**Comment by mojavelinux** [comment]
:tada:
