### ISSUE TITLE
Current documentation uses pdf-themesdir/pdf-theme which do not work in 1.5.8 (1.5.0.alpha.17.dev)

### ISSUE THREAD

**Issue by vanous** [asciidoctor/asciidoctor-pdf#1163]
Hello awesome people,

asciidoc/tor is great.

It took me some time to discover that while this works:

asciidoctor-pdf -a **pdf-stylesdir**=resources/themes -a **pdf-style**=basic  file.adoc

this silently fails to load custom pdf template config:

asciidoctor-pdf -a **pdf-themesdir**=resources/themes -a **pdf-theme**=basic  file.adoc

-v  provides this not very useful info:

```/usr/lib/ruby/vendor_ruby/asciidoctor-pdf/pdf-core_ext/page.rb:23: warning: instance variable @imported_page not initialized
/usr/lib/ruby/vendor_ruby/asciidoctor-pdf/pdf-core_ext/page.rb:23: warning: instance variable @imported_page not initialized
/usr/lib/ruby/vendor_ruby/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/usr/lib/ruby/vendor_ruby/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/usr/lib/ruby/vendor_ruby/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/usr/lib/ruby/vendor_ruby/prawn/font/ttf.rb:117: warning: instance variable @italic_angle not initialized
/usr/lib/ruby/vendor_ruby/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/usr/lib/ruby/vendor_ruby/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/usr/lib/ruby/vendor_ruby/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/usr/lib/ruby/vendor_ruby/prawn/font/ttf.rb:117: warning: instance variable @italic_angle not initialized
```

Both are listed as acceptable options, but the later skips the custom theming silently. I have seen #1127 so perhaps this will be solved soon and the docs [1] can remain as they are, so just a heads up, as this is default behavior of the Debian asciidoc package:

`Asciidoctor PDF 1.5.0.alpha.17.dev using Asciidoctor 1.5.8 [https://asciidoctor.org]`
`Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8) 
`

[1] https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#applying-your-theme

**Comment by mojavelinux** [comment]
Both will continue to work well into the future. It was renamed to remove the cognitive dissonance, but both get checked (with pdf-theme*) being the preferred name.

**Comment by mojavelinux** [comment]
Aha. You are simply falling victim to the active development during the transition from alpha to beta. The new names (pdf-themesdir and pdf-theme) were introduced in beta.1. Follow the release notes to stay informed of all the latest changes: https://github.com/asciidoctor/asciidoctor-pdf/releases

If you're still using alpha.17, you'll need to follow the docs from that tag. See https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.0.alpha.17/docs/theming-guide.adoc. Once beta.2 is released, all the docs in the master branch will become current.

**Comment by vanous** [comment]
Clear. Thank you very much!
