### ISSUE TITLE
Clarification on the way `extends` work

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1165]
I have just found that there was `extends` added to theming which is awesome (My 6 themes would become much easier to support)

But I am not sure how it should work. There is a clause in theming-guide:

```
## Extends
....
Currently, the base theme is always loaded first. 
Then, the files referenced by the extends key are loaded in order. 
Finally, the keys in the current file are loaded. 
Each time a theme is loaded, the keys are overlaid onto the keys from the previous theme.
```

Reading this I imagine it should apply MY basic-theme first then whatever it extends and then the current theme.

But in my case it doesn't work this way.

I have a `basic-theme.yml` in my themes folder and a sample file:

```
= Test Asciidoctor: Various stuff
:author: Maxim Kim

== test 1
привет
```

1. if no pdf-style is set up I expect it to use my basic-theme from my themes folder (I pass it to asciidoctor-pdf) -- asciidoctor-pdf tries to use default theme and fails

2. If I add a blank `default-theme.yml` to my themes folder -- asciidoctor clearly uses some other `basic-theme` as it fails to convert russian text due to lack of characters in supplied font which is set up on bundled themes (in my basic-theme I use different fonts).

3. If I add `extends: basic` to the `default-theme.yml` then everything works

So it kind of doesn't match to what documentation says or I misread it?

I end up making all my themes to `extends: basic` which I was thinking/reading you don't have to do.

**Comment by mojavelinux** [comment]
When using extends, you almost always want to use a relative path like this:

```
extends: ./basic-theme.yml
```

That will relative relative to the current file.

The exception is if you want to extend a built-in theme, like base or default. Then, you just use the keyword:

```
extends: default
```

It's very important to be explicit since there are so many different paths involved, it makes it less confusing.

**Comment by mojavelinux** [comment]
> if no pdf-style is set up I expect it to use my basic-theme from my themes folder

How would it know this?

It should be:

```
asciidoctor-pdf -a pdf-themesdir=./themes -a pdf-theme=basic
```

Now, if you want to extend basic, then you would first make a theme named actual-theme.yml like:

```
extends: ./basic-theme.yml
base:
  font-color: 'ff0000'
```

Then you can load it like:

```
asciidoctor-pdf -a pdf-themesdir=./themes -a pdf-theme=actual
```

If there is no extends keyword, it implies `extends: base`. (You can force it to not extend anything using `extends: ~`.

**Comment by habamax** [comment]
> When using extends, you almost always want to use a relative path like this:

Here it was not the case -- without any pdf-styles with only pdfstylesdir setup I was expecting that my base-theme would be loaded instead of built in. But it turns out that it tries to load default theme from this path instead of basic one

PS, non relative path works for me for `extends: basic` -- it uses my own theme from my path, but I will change it as you suggest just to be on the safer side.

**Comment by mojavelinux** [comment]
> without any pdf-styles with only pdfstylesdir setup I was expecting that my base-theme would be loaded instead of built in.

How does it know to load your theme if you don't specify pdf-theme (or pdf-style)?

**Comment by habamax** [comment]
> 
> 
> > without any pdf-styles with only pdfstylesdir setup I was expecting that my base-theme would be loaded instead of built in.
> 
> How does it know to load your theme if you don't specify pdf-theme (or pdf-style)?

Well it tries to load my default-theme from my path and I probably I misread the doc then :) thinking:

> Currently, the base theme is always loaded first.

would also load base theme from my path.

**Comment by habamax** [comment]
Anyway, now it is clear for me that I don't have to have basic-theme, I need default-theme instead (that will be used if no pdf-style is provided to asciidoctor-pdf) and all other themes should extend default one.

**Comment by mojavelinux** [comment]
> would also load base theme from my path.

No, the special keywords "default" and "base" should always load from the gem. If it works otherwise, that is a bug.

**Comment by mojavelinux** [comment]
> I need default-theme instead (that will be used if no pdf-style is provided to asciidoctor-pdf) and all other themes should extend default one.

Please don't do this. I'm going to change Asciidoctor PDF so this doesn't work because that is not the intended behavior. It should either load the default theme from the gem or you should have to specify a theme to load.

**Comment by habamax** [comment]
> 
> 
> > would also load base theme from my path.
> 
> No, the special keywords "default" and "base" should always load from the gem. If it works otherwise, that is a bug.

Aha! I didn't know this is unexpected behavior and used it for quite some time :)

**Comment by mojavelinux** [comment]
And I didn't realize that was working ;)

**Comment by habamax** [comment]
> 
> 
> And I didn't realize that was working ;)

And for me it was quite expected behaviour :)

Anyway, will update my templates, thank you!

**Comment by mojavelinux** [comment]
:+1:
