### ISSUE TITLE
Title page not correctly rendered

### ISSUE THREAD

**Issue by Thalamos** [asciidoctor/asciidoctor-pdf#1171]
Since using the 1.5.0.beta.1 the rendering of the title page is broke. Instead of generating a standalone page with a centered title, everything gets rendered just as it would do with a normal chapter. So the title sits on top of the page immediately followed by the table of content and depending on the toc's size even the first chapter gets rendered onto the 'title page'. 
Using the older alpha version, the document renders as it should.

![bad_page](https://user-images.githubusercontent.com/31256934/61777106-a863fe00-adfc-11e9-940d-01af2db5b099.png)

**Comment by mojavelinux** [comment]
This is now the default for the article doctype. If you want to restore the old behavior, set the `title-page` attribute in your document header. See https://github.com/asciidoctor/asciidoctor-pdf#title-page for details.

**Comment by mojavelinux** [comment]
> the document renders as it should.

should is debatable and the whole reason we had this issue: https://github.com/asciidoctor/asciidoctor-pdf/issues/95
