### ISSUE TITLE
Custom/alternate sort for index term

### ISSUE THREAD

**Issue by rpavlik** [asciidoctor/asciidoctor-pdf#1174]
When using asciidoctor to document an API/specification, the automatic index (used when in the PDF backend - I generate acsiidoctor source for html backend) is somewhat weakened by the presence of a namespace-prefix on all the entries. If the whole document is filed under "X" because everything starts with "xr", "Xr", or "XR_" that's not very helpful :D

I've figured out a small workaround but it's less than ideal - I generate the index terms to look like this:

```
[[xrCreateInstance]]
indexterm:[CreateInstance (function),xrCreateInstance]
```

resulting in an index entry like this:

![image](https://user-images.githubusercontent.com/61129/61815243-6e502780-ae0f-11e9-87e7-17e0b78c78a2.png)

It works, but it's awkward looking and somewhat an abuse of the syntax.

It would be nice if there was a way to either override the sorting of terms, or specify a (hidden) value to sort by instead of the main term, so that `xrCreateInstance` would appear as itself only, but be sorted under "C".

**Comment by mojavelinux** [comment]
I have no idea how this could be generalized. You're going to need to use custom code to override how the index term is stored. The code does not account for a difference between the visible term and a sortable value, but you can perform the substitution wherever the term is compared.

Here's very rudimentary code you could use to accomplish what you want:

```rb
require 'asciidoctor-pdf'

module Asciidoctor::PDF
  IndexCatalog.prepend (::Module.new do
    def store_primary_term name, dest = nil
      store_dest dest if dest
      category = uppercase_mb (name.delete_prefix 'xr').chr
      (init_category category).store_term name, dest
    end
  end)
  
  IndexTermGroup.prepend (::Module.new do
    def <=> other
      this = @name.delete_prefix 'xr'
      that = other.name.delete_prefix 'xr'
      (val = this.casecmp that) == 0 ? this <=> that : val
    end
  end)
end
```

Load this when calling Asciidoctor PDF as follows:

```
asciidoctor-pdf -r ./custom-indexterm-sorting.rb doc.adoc
```

**Comment by mojavelinux** [comment]
This is now documented in the README. See https://github.com/asciidoctor/asciidoctor-pdf#how-index-terms-are-grouped-and-sorted

**Comment by mojavelinux** [comment]
If that information isn't clear, please feel free to reopen.

**Comment by rpavlik** [comment]
awesome, thank you!
