### ISSUE TITLE
background_image

### ISSUE THREAD

**Issue by vanous** [asciidoctor/asciidoctor-pdf#1175]
When using Asciidoctor PDF 1.5.0.beta.1 using Asciidoctor 2.0.10 [https://asciidoctor.org]

title_page:
  background-image: image:images/title.png[]

is used on every other page of generated pdf.
1.5.0.alpha.18 doesn't have this issue.

**Comment by vanous** [comment]
Sorry, this was a mistake, the issue is already logged at https://github.com/asciidoctor/asciidoctor-pdf/issues/1144

**Comment by mojavelinux** [comment]
Yep. The fix will be in beta.2.
