### ISSUE TITLE
Header and footer images not found or not readable

### ISSUE THREAD

**Issue by bitarch** [asciidoctor/asciidoctor-pdf#1180]
Hi,

I'm facing this issue after upgrading from asciidoctor-pdf-1.5.0.alpha.17 to asciidoctor-pdf-1.5.0.beta.2.

```
$ gem install asciidoctor-pdf -v 1.5.0.alpha.17
Successfully installed asciidoctor-pdf-1.5.0.alpha.17
Parsing documentation for asciidoctor-pdf-1.5.0.alpha.17
Installing ri documentation for asciidoctor-pdf-1.5.0.alpha.17
Done installing documentation for asciidoctor-pdf after 2 seconds
1 gem installed
```

```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.17 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:UTF-8 ex:UTF-8)
```

```
$ asciidoctor-pdf ./header-footer-image-test.adoc -o ./header-footer-image-test-1.5.0.alpha.17.pdf
```

```
$ gem update asciidoctor-pdf
Updating installed gems
Updating asciidoctor-pdf
Successfully installed asciidoctor-pdf-1.5.0.beta.2
Parsing documentation for asciidoctor-pdf-1.5.0.beta.2
Installing ri documentation for asciidoctor-pdf-1.5.0.beta.2
Installing darkfish documentation for asciidoctor-pdf-1.5.0.beta.2
Done installing documentation for asciidoctor-pdf after 4 seconds
Parsing documentation for asciidoctor-pdf-1.5.0.beta.2
Done installing documentation for asciidoctor-pdf after 1 seconds
Gems updated: asciidoctor-pdf
```

```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.2 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:UTF-8 ex:UTF-8)
```

```
$ asciidoctor-pdf ./header-footer-image-test.adoc -o ./header-footer-image-test-1.5.0.beta.2.pdf
asciidoctor: WARNING: image to embed not found or not readable: <PATH_TO_ROOT_DIR>/styles/pdf/logo.svg
asciidoctor: WARNING: image to embed not found or not readable: <PATH_TO_ROOT_DIR>/styles/pdf/test.svg
```

Sources and output files attached.
[header-footer-image-test-1.5.0.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/3452233/header-footer-image-test-1.5.0.zip)

It looks like this behavior has been around since asciidoctor-pdf-1.5.0.alpha.18.
Could you please have a look at it? Thank you.

Regards

**Comment by mojavelinux** [comment]
Images in the theme file are resolved relative to pdf-themesdir (which is the directory where the theme file is located). This was unclear before and was fixed going into beta. In your case, the image references in the theme file need to be as follows:

```
image:../../images/test.svg[width=25]
```

(Or you can move the images into the themes folder, which is where they should be located).

We could consider adding support for the `docdir` and/or `docimagesdir` attribute references in the theme to reference locations relative to the current document. This could be related to #588.

**Comment by mojavelinux** [comment]
Images in the theme file are now resolved consistently (always relative to pdf-themesdir).

I'll file a separate issue to make the `docdir` (or `docimagesdir`) attributes available to the theme.

**Comment by bitarch** [comment]
Thanks Dan for the clarification and the proposed enhancement.
TODO update the Theming Guide.

**Comment by mojavelinux** [comment]
I've already documented it here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#images

**Comment by bitarch** [comment]
Yes, sorry, I was looking for it here : https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#images-1

**Comment by mojavelinux** [comment]
I went ahead and added the info there too.
