### ISSUE TITLE
Blank page before title page (doctype=book,media=prepress)

### ISSUE THREAD

**Issue by ianss** [asciidoctor/asciidoctor-pdf#1181]
Versions beta 1 and beta 2 of Asciidoctor PDF render a blank page before the title page when the following AsciiDoc attributes are set:

```
:doctype: book
:media: prepress
```

The blank page is not compatible with Adobe Acrobat's booklet printing mode, which expects the first page of the PDF to be the front cover of the booklet.

**Comment by rosieyohannan** [comment]
I had this problem too and I think it's because title page is actually the first page inside the front cover, rather than the cover itself. So the prepress media type pushes it to the recto position. I fixed it by using a cover image PDF (:front-cover-image:) generated from a separate asciidoc file, and then using the :notitle: attribute for the main doc. I may well be wrong with this but it's worked out so far.

**Comment by ianss** [comment]
Thanks for your help @rosieyohannan . I hadn't realised the blank front page in my `:media: prepress` document was a placeholder for a front cover image. This wasn't the behaviour in Asciidoctor PDF 1.5.0 Alpha 18 and earlier versions, so I assumed it was just a blank page.

As this change was introduced when Asciidoctor PDF moved from Alpha to Beta, it may be that a `:media: prepress` document was always intended to have a front cover image, and that this behaviour has only been enforced from the beta versions.

I found the earlier behaviour, where the front cover was optional for `:media: prepress` documents, very convenient -- the title page formed a useful auto-generated cover for a printed booklet.

I'm hoping the old behaviour might be restored in later versions. For now I'll follow your advice to disable the title page and maintain my own cover instead.

**Comment by mojavelinux** [comment]
While a lot changed in the code with how the cover and title pages are created, I didn't expect a change in the prepress behavior. But given this is one of the areas the test suite doesn't yet cover, I'm not surprised that we're seeing a regression. I'll dive in to see what's happening while at the same time adding tests for this behavior so we can avoid regressions in the future. This is why we beta ;)

**Comment by mojavelinux** [comment]
I can confirm that the prepress behavior as it related to the title page was totally broken. PR with tests is now pending.

**Comment by ianss** [comment]
Many thanks for fixing this so quickly @mojavelinux
