### ISSUE TITLE
Formatting error with prepress only

### ISSUE THREAD

**Issue by rosieyohannan** [asciidoctor/asciidoctor-pdf#1188]
I'm getting this error when building a PDF, but only with :media: prepress, doesn't show if using :media: print:

asciidoctor: ERROR: failed to parse formatted text: <a href="https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NET_README.md#measurements&#8212;&#8203;fields">Networking</a> [<font size="0.85em">https://github.com/​influxdata/​telegraf/​blob/​master/​plugins/​inputs/​net/​NET_README.md#​measurements&#​8212;&#​8203;fields</font>&#93;

And its line 27 here causing the error I believe: https://github.com/rosieyohannan/circleci-docs/edit/server/tranfer-content/jekyll/_cci2/monitoring.adoc

**Comment by rosieyohannan** [comment]
* Hmm seems I was mistaken with the error and I'm getting that error whenever I use the :media: attribute, regardless of whether it's prepress or print. If I comment it out, the error goes away.

* Also, I've just noticed when I do see the error, all external links in the PDF are displayed as normal but with the URL printed out in square brackets straight after.

**Comment by rosieyohannan** [comment]
with :media: set in header:
<img width="512" alt="Screenshot 2019-08-02 at 17 47 37" src="https://user-images.githubusercontent.com/24589403/62385687-a95c0480-b54d-11e9-8e7d-c908941e2399.png">

Without:
<img width="534" alt="Screenshot 2019-08-02 at 17 49 10" src="https://user-images.githubusercontent.com/24589403/62385784-de685700-b54d-11e9-9576-3f796e5d6482.png">

**Comment by rosieyohannan** [comment]
Oh this is all explained here: https://github.com/asciidoctor/asciidoctor-pdf/issues/951

Closing!

**Comment by mojavelinux** [comment]
Did you manage to resolve the error too?

**Comment by mojavelinux** [comment]
(I'm curious because perhaps we need an additional test).

**Comment by rosieyohannan** [comment]
Ah no I didn’t, I just decided to use :media: screen, so the error went away. Next time I’m at my work computer I’ll post the output associated with the error if that helps :-)

**Comment by mojavelinux** [comment]
Ah, the issue is that you need to escape the double hyphen in the URL. Otherwise, it becomes an entity and that, in turn, isn't parsed correctly by the print-oriented output.

```
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NET_README.md#measurements--fields[Networking]
```

must be:

```
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NET_README.md#measurements\--fields[Networking]
```

(it also fixes the URL, which which otherwise be wrong).

I'll see if the print-oriented output can avoid issuing the warning.

**Comment by mojavelinux** [comment]
Btw, the only time you would use `media=prepress` is if you were intending to send the output to a printer / publisher. Otherwise, you want `media=screen` for viewing with a PDF reader or `media=print` for printing.

**Comment by rosieyohannan** [comment]
Thanks for your help @mojavelinux, I understand now 🎉
