### ISSUE TITLE
revremark on title page?

### ISSUE THREAD

**Issue by rosieyohannan** [asciidoctor/asciidoctor-pdf#1198]
I can't seem to get the revremark to appear on the title page, I have title, subtitle, author, revnumber, revdate all showing, but it would be really useful to be able to display: Draft, Final etc. if possible. :-)

**Comment by mojavelinux** [comment]
The revremark was completely overlooked in Asciidoctor PDF. I suppose, as you suggest, the simplest thing to do is to display it in the revision line on the title page, as in `v1.0: Draft`.

**Comment by mojavelinux** [comment]
Turns out that was pretty easy to implement ;)
