### ISSUE TITLE
Allow image macro to specify which page in the PDF to import

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1202]
Currently, when the target of an image macro is a PDF document, the converter always inserts the first page. It should be possible to specify the page number to import using the `page` attribute on the image macro.

```
image::custom-page.pdf[page=2]
```

**Comment by mojavelinux** [comment]
@nuket this might be of interest to you.

**Comment by nuket** [comment]
Cool beans. I've also been playing with scripting Inkscape to auto-generate chapter title pages with full-bleed color based on an SVG template, though these end up being single page PDF exports by default.
