### ISSUE TITLE
Limit on the number of subsections?

### ISSUE THREAD

**Issue by mahmoudparsian** [asciidoctor/asciidoctor-pdf#1214]
Hi,

I have an appendix:

[appendix]
== Questions and Answers

==== What is Apache Spark?

==== What is PySpark?
...
...
...

I have 52 of "====" subsections, but only 51 of them appear in the generated PDF.
Is there a limit on the number of subsections?

Thank you!
best regards,
Mahmoud

**Comment by mojavelinux** [comment]
No, there is no limit.

Perhaps the last one is getting cut off. Can you share a complete sample document that is impacted by this issue?

**Comment by mahmoudparsian** [comment]
I can not post the actual document: since it is not published yet, but hope this helps.
The last one: "How to Read Objects from DynamoDB?" does not appear in the generated pdf:

this is the command I use:

asciidoctor --backend=pdf --require=asciidoctor-pdf  --destination-dir=_build --out-file=book.pdf master.adoc; \

Thank you!
Mahmoud

 $ grep '^====' appendix_QA.adoc
==== What is Apache Spark?
==== What is a Cluster Manager?
==== What is PySpark?
==== What is MapReduce?
==== How is Spark different from MapReduce?
==== How do you Compare Spark and Hadoop
==== What are Spark's data abstractions?
==== What is a `SparkSession`?
==== What are ((actions)) and ((transformations))?
==== What is a `SparkContext`?
==== What is an RDD?
==== How to create an RDD from a text file?
==== How to create an RDD from a Python collection?
==== What are Spark's Actions?
==== What is a Pair RDD?
==== What is a classic Word Count problem?
==== How to filter RDD
==== What is a DataFrame?
==== How to create a DataFrame from a text file?
==== How to create a DataFrame from a Python collection?
==== How to use `DataFrame.groupBy()`?
==== What is a Parquet file format?
==== How to create a Parquet file format using PySpark?
==== How to add a new column to a DataFrame?
==== How to read a Parquet file format using PySpark?
==== What are Partitions and Partitioning?
==== How to Partition a DataFrame based on Column Value?
==== What is the function of `coalesce()`
==== How to create an RDD with specific number of partitions?
==== How to use `reduceByKey()` Transformation
==== How to use `groupByKey()` Transformation
==== How to use `combineByKey()` Transformation
==== How to use `mapPartitions()` Transformation
==== How to use `map()` Transformation
==== How to use `flatMap()` Transformation
==== How to use `join()` on 2 RDDs?
==== Is there a Graph API in Spark?
==== What is a PageRank Algorithm?
==== What are Broadcast Variables?
==== How is machine learning implemented in Spark?
==== What is Spark SQL?
==== How to Create a DataFrame from JSON
==== What is Lazy Evaluation in Spark?
==== What are the various levels of persistence in Spark?
==== What is Lineage Graph?
==== How do you monitor Spark jobs?
==== What is `foreach()`?
==== Explain Spark's `countByKey()` operation
==== What is Spark Streaming?
==== How to read LIBSVM data format?
==== How to generate sliding data?
==== How to Read Objects from DynamoDB?
===== Input
===== Read by Python
===== Read by PySpark

**Comment by mojavelinux** [comment]
> I can not post the actual document: since it is not published yet

That's why I said sample document.

If you want me to take the time to fix this, then you need to take the time to create a complete reproducible document.

**Comment by mojavelinux** [comment]
Btw, your section titles are out of sequence. You should be seeing a warning about this:

```
[appendix]
== Questions and Answers

==== What is Apache Spark?
```

You can't jump from level 1 to level 3.

**Comment by mahmoudparsian** [comment]
Hello Dan,

You are an excellent detective! 
You found the solution: "You can't jump from level 1 to level 3."

The problem is fixed by not jumping from level 1 to level 3.

Thank you very much for your help.

best regards,
Mahmoud

**Comment by mojavelinux** [comment]
\o/
