### ISSUE TITLE
How to generate PDF with all Bookmarks collapsed

### ISSUE THREAD

**Issue by RobertdeLeeuw-IHomer** [asciidoctor/asciidoctor-pdf#1224]
I can generate PDFs. When I open them, in the left panel all the bookmarks are 'open'.
I can then manually collapse all the bookmarks and safe the PDF file again.
But it would be simpler if I could just generate the PDF with all the bookmarks collapsed.

**Comment by mojavelinux** [comment]
I have no idea how that's done. If you know the PDF commands, or if Prawn provides that option, let me know and I'd be open to finding a way to make it an option in the converter.

**Comment by mojavelinux** [comment]
I found it in the PDF spec:

> If the outline item is closed, Count is negative and its absolute value is
> the number of descendants that would be visible if the outline item
> were opened.

**Comment by mojavelinux** [comment]
And it turns out Prawn supports this option.

To control the level at which the outline is expanded (by default), I propose adding a second argument to the value of the outlinelevels attribute. For example, to show 3 levels of outline, but only expand 1 level, you'd use:

```
:outlinelevels: 3:1
```

**Comment by RobertdeLeeuw-IHomer** [comment]
Wrapping up a new release of my document, upgraded to newest beta for this. Works like a charm. Thanks!!

**Comment by mojavelinux** [comment]
Fantastic! Thanks for testing!
