### ISSUE TITLE
Table with autowidth: Rename role "spread" to "stretch"

### ISSUE THREAD

**Issue by abosshard** [asciidoctor/asciidoctor-pdf#1225]
When the `autowidth` option is set on a table, the converter recognizes the role `spread` to mean "100% width" ([Issue 519](https://github.com/asciidoctor/asciidoctor-pdf/issues/519)).

This role should be renamed to `stretch` to be consistent with the [User Manual](https://asciidoctor.org/docs/user-manual/#table-width):

> If you want each column to have an automatic width, but want the table to span the width of the content area, add the `stretch` role to the table or set the `width` attribute to `100%`.

**Comment by mojavelinux** [comment]
We'll continue to support the spread role since Asciidoctor PDF works with Asciidoctor >= 1.5.3.

**Comment by abosshard** [comment]
Thank you!
