### ISSUE TITLE
Add support for highlighting mark

### ISSUE THREAD

**Issue by PierreR** [asciidoctor/asciidoctor-pdf#1226]
As discussed in Gitter, highlighting mark could be supported  now that Asciidoctor PDF supports inline background colors.

Workaround: declare an explicit role name
```
[.mark]+foo+
```

**Comment by mojavelinux** [comment]
To be clear, what we're talking about is:

```
#foo#
```

It should appear with a background color in a highlight color like yellow. This setting should be configurable in the theme (i.e., mark.background-color)
