### ISSUE TITLE
Render table footer row

### ISSUE THREAD

**Issue by kastork** [asciidoctor/asciidoctor-pdf#123]
When specifying table options like so

    [cols="60,40", options="header,footer"]

The table's header row is formatted and rendered, but the footer row is not rendered at all (it is completely missing in the pdf, but present and formatted specially in the html5).

**Comment by mojavelinux** [comment]
Yep, this is known. It just hasn't been implemented. I've been meaning to add a warning until it is implemented.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L813

I'm working on tables as part of #6. I could try to add the footer row while I'm in there.
