### ISSUE TITLE
Support for PDF/X-1a and X3 compatible PDF documents

### ISSUE THREAD

**Issue by IbnSaeed** [asciidoctor/asciidoctor-pdf#125]
Hello 

are there any plans for supporting  PDF/X-1a and X3 compatible PDF's for getting the final pdf Print Ready ?

**Comment by mojavelinux** [comment]
Could you expand what you mean by this. In other words, what is required and how do we test it?

I'll note that we are limited at the moment by what Prawn can support. So I'd first check to see if this is supported by Prawn. If so, then the answer is most certainly yes. If not, then we have to address it there first.

**Comment by mojavelinux** [comment]
https://github.com/prawnpdf/prawn

We are still using an older version of Prawn (1.2.1), but obviously we need to upgrade.

**Comment by IbnSaeed** [comment]
They have a 2.0 release out, ill have to take a look at their docs to find out if they support PDF/X-1a compliant pdf's

**Comment by IbnSaeed** [comment]
I have opened up an issue here since i could not find any mention of PDF/X-1a in their doc.

https://github.com/prawnpdf/prawn/issues/877

**Comment by IbnSaeed** [comment]
Right now, i use Adobe Acrobat Pro's preflight feature to test if a PDF is PDF/X-1a compiant or not. Not sure about asciidoctor though as i did not have enough info .

**Comment by IbnSaeed** [comment]
here is some information on PDF/X

http://en.wikipedia.org/wiki/PDF/X

http://www.prepressure.com/pdf/basics/pdfx-1a

**Comment by IbnSaeed** [comment]
@mojavelinux If you dont mind me asking, what does Tracking label mean?

**Comment by mojavelinux** [comment]
Tracking means that this issue is dependent on or linked to an upstream issue. There's no other way to filter on that field in GitHub issues without that label.

**Comment by IbnSaeed** [comment]
thanks

**Comment by mojavelinux** [comment]
Looks like we're going to have to take this on in Asciidoctor PDF (or create another gem for it) as it was closed upstream (for no good reason).

Here's the code that implements this support (at least the essential parts).

https://gist.github.com/fidothe/32613b44a5b6588531d9

**Comment by IbnSaeed** [comment]
So what can we do to make this happen ?

**Comment by mojavelinux** [comment]
You could try to weave the referenced code into Asciidoctor PDF. Ideally, we want to be able to include it from a module so it has minimal impact on the size of the converter class (which is already getting quite big).

Another solution is to create extensions to Prawn (even if it's overridding internal Prawn stuff) so we can isolate the code, maybe even into a gem. We need to demonstrate that this can easily be merged into Prawn. The more code you show up with, the more open the Prawn developers seem to actually integrate the code.

**Comment by jessedoyle** [comment]
@mojavelinux: It's looking like some PDF/X functionality is going to make its way into Prawn::Core. See [here](https://github.com/prawnpdf/pdf-core/pull/17). I'd give it some time to see where this is headed before making dramatic changes.

**Comment by mojavelinux** [comment]
I really hope so. Of course, we can help be a part of making it happen :)

**Comment by mojavelinux** [comment]
What's good for Prawn is good for Asciidoctor PDF.

**Comment by IbnSaeed** [comment]
This is good news. I hope they make it into Prawn so Asciidocter can make use of it as well.

**Comment by mojavelinux** [comment]
FYI, there's an open pull request to add support in Prawn. See prawnpdf/prawn#1029.

**Comment by mojavelinux** [comment]
As is turns out, if you install rghost (a binding for GhostScript) and pass `-a optimize=prepress` when calling `asciidoctor-pdf`, you end up with a valid PDF/A document.

**Comment by mojavelinux** [comment]
We could add support for specifying the PDF variant, which maps to the `-dPDF` flag (either `-dPDFX` or `-dPDFA`). Something like `pdf-device=A`.

**Comment by mojavelinux** [comment]
Since we have limited control over the PDF library (Prawn), all we can offer is to add a switch to the optimizer to produce a PDF/X or PDF/A compliant file. The compliance setting must be specified in the value of the `optimize` attribute, separate from the quality by a comma. For example:

```
-a optimize=print,PDF/A
```

By configuring the optimizer to remove non-printable (hyperlink) annotations, it's able to produce a PDF/A-compliant file. However, it's not able to produce a PDF/X-compliant field because it says the TrimBox doesn't fit inside BleedBox. Please file that issue with Prawn.

**Comment by mojavelinux** [comment]
Beyond relying on the optimizer to distill the PDF into a PDF/A or PDF/X-compliant file, I won't be pursuing this issue any further. PDF spec compliance is not a concern of this library. It has to happen either upstream (Prawn / pdf-core) or downstream (GhostScript, hexapdf, etc). This library only uses the PDF-generation APIs that are available. We cannot get sidetracked trying to hack around the PDF that it generates as it only holds up progress in other areas where our time can make a real difference.
