### ISSUE TITLE
Can't run asciidoctor-pdf 1.5.0.beta.3 in asciidoctorj-pdf

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor-pdf#1250]
I am currently trying to bring asciidoctor-pdf 1.5.0.beta.3 to asciidoctorj-pdf.
However the tests currently fail here in `Converter#register_fonts`:
https://github.com/asciidoctor/asciidoctor-pdf/blob/946339c1fea1d2b1c97158993fddfdc5fb97ab7f/lib/asciidoctor-pdf/converter.rb#L3333

This seems to be because `fonts_dir` is a URI to an internal resource that is retrieved via the Ruby classloader here:
https://github.com/asciidoctor/asciidoctor-pdf/blob/946339c1fea1d2b1c97158993fddfdc5fb97ab7f/lib/asciidoctor-pdf/converter.rb#L3321-L3323

Using my `puts` debugging superpowers I figured out that dirs resolves to this:
```
["uri", "classloader", "/gems/asciidoctor-pdf-1.5.0.beta.3/data/fonts"]
```

(As it splits on the system path separator – which is `:` on my machine – I can imagine that this even runs on Windows :-D)

**Comment by mojavelinux** [comment]
> As it splits on the system path separator – which is : on my machine – I can imagine that this even runs on Windows :-D

Dang it. Windows is suppose to be using `;` as the path separator (not the file separator). But on JRuby, this doesn't seem to be the case. And then there are JAR paths, which further complicate the matter.

**Comment by mojavelinux** [comment]
I verified that on CRuby on Windows, File::PATH_SEPARATOR is `;`. So JRuby is incorrect here.

However, there is still the large issue of the JAR filename in JRuby, which would certainly break JRuby on non-Windows.

**Comment by robertpanzer** [comment]
My last comment was probably misleading, sorry about this ;-)

It doesn't run on my Mac, and I suppose it will also fail on Linux, because without any further customization `fonts-dir` is `uri:classloader:/gems/asciidoctor-pdf-1.5.0.beta.3/data/fonts`.
This is split to the 3 elements of `dirs` `usr`, `class loader` and `/gems/asciidoctor-pdf-1.5.0.beta.3/data/fonts`.
And neither of these 3 elements is a path that exists in the filesystem,.

**Comment by mojavelinux** [comment]
Yes, that's what I suspected. The JAR paths are interfering with the assumption that we can separate entries using the path separator. Back to the drawing board.

**Comment by mojavelinux** [comment]
We'll just change it to always be semicolon. That seems safe.

**Comment by mojavelinux** [comment]
Another option is to detect `uri:classloader:` and skip it. I'm going to try it both ways and see which one feels better.

**Comment by mojavelinux** [comment]
What's interesting is that now we see how to load fonts out of a JAR.

```
-a pdf-fontsdir=uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.9/data/fonts
```

That makes me think that just standardizing on the `;` as a separator is the way to go.

**Comment by robertpanzer** [comment]
:+1:
I like the approach of treating  `uri:classloader:`, but then I was thinking that it might also be possible to load fonts from URLs. (If I understood correctly what the open-uri gem does).
So a `;` is probably better.

**Comment by mojavelinux** [comment]
Yeah. And it seems like Java uses `;` in a lot of places for this very purpose...so it seems like a reasonable and safe thing to do.

**Comment by mojavelinux** [comment]
Thanks for the heads up on this and good detective work. :male_detective:

**Comment by robertpanzer** [comment]
Thanks! ☺️

**Comment by mojavelinux** [comment]
Keep in mind that when specifying multiple font dirs on the CLI, it's necessary to either escape the semi-colon or enclose the value in double quotes. Otherwise, the shell will interpret it as a command separator.
