### ISSUE TITLE
Line break within a word leads to 'non-searchability'

### ISSUE THREAD

**Issue by yannickguth** [asciidoctor/asciidoctor-pdf#1253]
Hi everybody, 

with regard to this old topic: 

http://discuss.asciidoctor.org/Prevent-line-break-for-wrapped-text-td4514.html

I would like to point out a problem that I noticed during the rendering into a PDF document. 

In my asciidoc document I import some csv tables which contain very long property names like the following: 

`webcontroller.outboundservice.cmis.repositoryId `

The problem is that these properties are too long to be displayed within a row of the table column - the line is therefore wrapped at the end. 
In the rendered PDF the table cell looks like this: 

```
webcontroller.outboundservice.cm 
is.repositoryId 
```

If I now search for this property in the created pdf document, it will not be found, because the end of the line "cuts up" the text. So the PDF document interprets each line as a separate text. 

My first thought was that it was the PDF format itself. But if I use the same table in Microsoft Word and save it as "accessible" pdf, I can find the property as "whole word". 

Are there any workarounds to fix this problem in asciidoctor? 

Thanks in advance.

**Comment by mojavelinux** [comment]
This is a [Prawn](https://github.com/prawnpdf/prawn) issue (the PDF generator), not an Asciidoctor PDF issue. Asciidoctor hands the text to Prawn and Prawn decides how to break it into lines. So whatever Prawn is doing that Microsoft Word is not doing has to be solved in Prawn.

You could try to create a simple PDF both ways and see if you can see what's different in the PDF source. But again, you'd need to report it to Prawn.

**Comment by mojavelinux** [comment]
What you are likely referring to is https://support.office.com/en-us/article/Create-accessible-PDFs-064625E0-56EA-4E16-AD71-3AA33BB4B7ED[accessible PDFs]. Prawn doesn't support that feature, and therefore Asciidoctor PDF cannot either. When Prawn prints lines of text, it prints them as separate text objects.

Refer to upstream issue: https://github.com/prawnpdf/prawn/issues/1131.
