### ISSUE TITLE
Formatting of roles containing hyphens are not applied

### ISSUE THREAD

**Issue by weph** [asciidoctor/asciidoctor-pdf#1254]
Here's another one I just stumbled upon.

**test.adoc**
```
= Test
:toc:
:pdf-theme: test
:pdf-themesdir: ./

[.red-text]#Red text#
```

**test-theme.yml**
```
role:
    red-text:
        font-color: #ff0000
```

**Comment by mojavelinux** [comment]
Your observation is correct. This is a limitation with how the theme data is interpreted. However, I think I may know how to lift the restriction in this case.

**Comment by mojavelinux** [comment]
Got it.
