### ISSUE TITLE
Angstrom Å symbol in default font(s)

### ISSUE THREAD

**Issue by RarrugasTetra** [asciidoctor/asciidoctor-pdf#1257]
Dear Developers,
would you please add the Angstrom Å symbol to your custom fonts?
Right now I cannot use &#8491; in my source files -- the pdf is rendered with missing symbol (note, in HTML output is everything fine). I know about possibility to use my own fonts, but why would I do this only because of only one symbol.

Thank you!

**Comment by mojavelinux** [comment]
Not that I really understand the different, but you seem to be using the incorrect (maybe) angstrom. Here's the one supported by the font:

```
Å
```

Here's the one you are typing:

```
Å
```

Can you explain why you are choosing this one? What language uses that range? Is this a math symbol?

**Comment by mojavelinux** [comment]
If it's a math symbol, I'm happy to add it. Let's just not miss any related symbols.

**Comment by RarrugasTetra** [comment]
Hm, it looks like I am using not the best code for the angstom symbol. I was using `&#8491;` as suggested in https://www.toptal.com/designers/htmlarrows/symbols/angstrom-sign/
or
https://www.w3schools.com/charsets/ref_utf_letterlike.asp

But as I read now, wikipedia recommends to use the other code `&#197;`, which fortunately exists in your custom fonts.

Thus, the problem is solved, thank you for info and sorry for disturbing.

**Comment by mojavelinux** [comment]
That's great news.

Wikipedia also seems to suggest the Swedish capital A. https://en.wikipedia.org/wiki/Angstrom
