### ISSUE TITLE
Table column with auto width causes CannotFit error

### ISSUE THREAD

**Issue by weph** [asciidoctor/asciidoctor-pdf#1259]
Using a [column with auto width](https://github.com/asciidoctor/asciidoctor/issues/1844) causes `Prawn::Errors::CannotFit`. I played around with different number of columns and percentages but it seems that the tilde is causing the error.

**Example**
```
[cols="~,100%"]
|===
| | Header
| X | Value
|===
```

[trace.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/3582369/trace.txt)

**Comment by mojavelinux** [comment]
This is a known restriction / limitation of the PDF converter. When using an autowidth column, the total percentage must add up to 100%. Thus, the percentage of the first column becomes 0%, which is not enough to draw any text. Unlike HTML, PDF doesn't bend to make room. It can only take the room you allocate. So if you allocate 0%, it will try to use 0% and fail.

You have to be careful with this feature (and autowidth in general) when converting to PDF. I'm happy to include this information in the README.

**Comment by mojavelinux** [comment]
There's even a test for this scenario. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/spec/table_spec.rb#L178-L187

**Comment by weph** [comment]
Yes, that totally makes sense. I guess I'm so used to those HTML quirks that things that act right seems wrong 😆

**Comment by mojavelinux** [comment]
I'll admit that having these restriction can be a drag. It's one of the reasons why I believe that browser-based rendering is the future of PDF generation in Asciidoctor. It will afford us a lot more flexibility and control over layout.
