### ISSUE TITLE
Font issues again (Ellipsis, Right arrow, ...)

### ISSUE THREAD

**Issue by RarrugasTetra** [asciidoctor/asciidoctor-pdf#1274]
In Asciidoctor some character combinations like `...`, `->` (see [here](https://asciidoctor.org/docs/user-manual/#replacements) for the list) are replaced by respective codes like `&#8230;`, `&#8594;`, for which asciidoctor-pdf has no fonts. (Till now I needed only these two symbols, but maybe others from the aforementioned list are also missing). Would you please add these glyphs to your default fonts?

**Comment by mojavelinux** [comment]
The default font in Asciidoctor PDF supports all built-in characters / symbols, which include the right arrow and ellipsis. And we have tests to prove it. If you are using your own font, then you may need to either use a [fallback font](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#fallback-fonts) or [prepare your font for Asciidoctor PDF](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#appendix-a-preparing-a-custom-font).

**Comment by RarrugasTetra** [comment]
Sorry, I should have mentioned, that these codes do not work in _monospaced text_.
For example, this
```
= Test
Me <me@me.com>

`Test ... ->`
```
produces pdf without required symbols.

**Comment by mojavelinux** [comment]
Thank you for that clarification. You are correct that they should. I will revisit the test to make sure those symbols are covered.
