### ISSUE TITLE
font_style: normal --> Error "value must be enumerable"

### ISSUE THREAD

**Issue by RarrugasTetra** [asciidoctor/asciidoctor-pdf#1286]
Dear Developers,
I am trying to use a modified theme where I added a new role with `font_style: normal`. However, building a pdf with this theme produces an error "value must be enumerable". Ideally, I would use `font_style: $base_font_style` but this gives me the same error. You can also reproduce this problem just by adding `font_style: normal` to one of already defined roles, `big` or `small`, and using them in source file as e.g. `[small]#test#`.

Is this a bug or how do I get a normal text otherwise?

Thank you!

**Comment by mojavelinux** [comment]
You're absolutely correct. The `normal` value is not being processed correctly.
