### ISSUE TITLE
Image caption position relative to block width not page width

### ISSUE THREAD

**Issue by nobecutan** [asciidoctor/asciidoctor-pdf#1291]
When using center aligned images that are only, say, 80% of the page width, it would be great if the caption of that image is also aligned with the image.

Current behaviour:
![test](https://user-images.githubusercontent.com/3648330/65514082-dccb6780-dedc-11e9-8021-60accf3dcb87.png)

Expected behaviour:
![test_expected](https://user-images.githubusercontent.com/3648330/65514230-3338a600-dedd-11e9-891b-33680fa557a8.png)

The behaviour of
```
caption:
  align: center
```
would still be the same, however, left and right alignment would be limited to the image width.

**Comment by mojavelinux** [comment]
We should follow what we did for tables and allow the `image_caption_max_width` key to be set to `fit-content`.
