### ISSUE TITLE
Title page for each chapter?

### ISSUE THREAD

**Issue by chuck-confluent** [asciidoctor/asciidoctor-pdf#1297]
Is it possible to have a title page for each chapter? I have an asciidoc similar to the following:

```
= My title: Subtitle
:revnumber: Blah.1.0
:revremark: CONFIDENTIAL
:title-page:
:toc:
:toclevels: 1
:source-highlighter: rouge
:icons: font
:doctype: book

:leveloffset: +1

[preface]
include::preface.adoc[]

:module-number: 1

include::welcome.adoc[]

:module-number: 2

include::mod2.adoc[]

:module-number: 3

include::mod3.adoc[]

:module-number: 4

include::mod4.adoc[]

:module-number: 5

include::mod5.adoc[]

:module-number: 6

include::mod6.adoc[]

:module-number: 7

include::mod7.adoc[]

:module-number: 8

include::mod8.adoc[]

:module-number: 9

include::mod9.adoc[]

:module-number: 10

include::mod10.adoc[]

:module-number: 11

include::ending.adoc[]

[appendix]
include::appendix1.adoc[]

[appendix]
include::appendix2.adoc[]

:leveloffset: -1
```

Each one of the `.adoc` files has `:title-page:` declared, but it seems that with the `:doctype: book` at the top level, the title pages for the individual modules don't show up. Is there a way for the individual modules to also call the `:title-page:` attribute?

Please feel free to poke holes in my understanding of how this should work or point out places where I'm doing things sub-optimally. Thanks!

**Comment by mojavelinux** [comment]
> Is it possible to have a title page for each chapter?

Not built in.

The converter is designed be extended for addressing precisely this type of use case. You can find information about how to extend the converter here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#extending-the-converter

Here's an example:

```rb
class CustomPDFConverter < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def layout_chapter_title node, title, opts = {}
    layout_heading title, opts
    stroke_horizontal_rule 'DDDDDD', line_width: 0.5
    move_down @theme.block_margin_bottom
    theme_font :base do
      layout_prose 'More text here'
    end
    start_new_page
  end 
end
```

> Each one of the .adoc files has :title-page: declared

That's not the purpose of the `title-page` attribute. The `title-page` attribute is to enable the title page for the article doctype, which normally doesn't get one.

If you were to extend the converter, I would recommend using a different attribute name.

(You might also consider just using parts, which already get a dedicated page).

**Comment by chuck-confluent** [comment]
Interesting! Thank you! I'll look into this. In the short term, I just put up an image as the first page of each chapter.
