### ISSUE TITLE
Use pagenums attribute to toggle page numbers

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#13]
Only add page numbers if the pagenums attribute is set. Set the attribute by default.

**Comment by gAmUssA** [comment]
@mojavelinux is there a way to specify page numbers placement (top or bottom of a page) ?

**Comment by mojavelinux** [comment]
Not at the moment. That would likely be a theme setting.

**Comment by gAmUssA** [comment]
@mojavelinux Thanks!

**Comment by mojavelinux** [comment]
Feel free to file a separate issue so we don't forget ;)
