### ISSUE TITLE
Load a base theme that provide defaults for all required keys

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#132]
Currently, each theme must provide all required values or else the converter will crash. It would be better if a theme only had to specify values for keys it wants to override / customize. This can be accomplished by introducing a base theme. The base theme should be loaded before the specified theme and provide defaults for all required values.

You can think of the base theme as a “CSS reset”.

**Comment by mojavelinux** [comment]
The base theme also allows us to introduce new theme settings without the risk of breaking existing themes.

**Comment by mojavelinux** [comment]
Once we have a base theme in place, we should remove all the unnecessary fallbacks when we check for keys...or, these fallbacks should be preconfigured.

Case in point:

```
@theme.prose_margin_bottom || @theme.vertical_rhythm
```

We have to assume we're going to have a value for the `prose_margin_bottom` key or the code is just ugly.

**Comment by wolandscat** [comment]
Now that I have Asciidoctor PDF 1.5.0.alpha.8, do I assume that theme base + overriding is working yet, or do I still need to copy the base theme?

**Comment by mojavelinux** [comment]
It's best to start with the default theme and modify it at this point. I'm
still working on the base theme feature. It will make the next release
(alpha.9 or beta.1).

**Comment by rmpestano** [comment]
Hi guys, i'm using alpha8 and can't load my custom theme. I've just put my theme file in same directory as my adoc document  and ran asciidoctor-pdf myfile.adoc. The theme file is name myfile-theme.yml

**Comment by rmpestano** [comment]
managed to load my theme using pdf-style and styledir options:

´´´
asciidoctor-pdf myfile.adoc -a pdf-style=myfile -a pdf-stylesdir=/home/pestano/projects
´´´

It would be nice if it used adoc file path as default pdf-stylesdir and adoc filename(plus -theme sulfix) as default pdf-style. If no pdf-style is found then use basic-theme.yml. 
Does it makes sense? I think it should work like docinfo.html

**Comment by mojavelinux** [comment]
Please file a separate issue for this enhancement and we'll discuss /
design / consider it there. Thanks!
