### ISSUE TITLE
Small documentation inconsistency

### ISSUE THREAD

**Issue by lurch** [asciidoctor/asciidoctor-pdf#1324]
https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-running-content (in the `header` section) says:
"vertical-align: top | middle | bottom (default: middle)"
but then in the example shows:
```
header:
  vertical-align: center
```

**Comment by mojavelinux** [comment]
Technically it's not incorrect since `center` is an alias for `middle`. But I agree it looks inconsistent, so let's fix it.

**Comment by mojavelinux** [comment]
If you see something small like this, you can just go ahead and submit a PR instead of an issue.

**Comment by lurch** [comment]
> If you see something small like this, you can just go ahead and submit a PR instead of an issue.

I would have done (just like I have been with the typos I've been PRing :wink: ), but in this case I wasn't sure if it was the "left hand side" that was incorrect for not showing `center`, or if it was the "right hand side" that was incorrect for using the invalid value `center`.

**Comment by mojavelinux** [comment]
Gotcha. :+1:
