### ISSUE TITLE
Font support failing in 1.5.0.beta6

### ISSUE THREAD

**Issue by dutrow** [asciidoctor/asciidoctor-pdf#1327]
When updating to asciidoctor-pdf-1.5.0.beta.6, our use of fonts is failing. This issue does not surface when reverting to 1.5.0.beta.5

Verb and Calluna are unzipped and made available via `-a pdf-fontsdir=resources/Fonts`
The style is defined as follows:
```
font:
  catalog:
    Verb:
      normal: Verb-ttf/verbcondregular-webfont.ttf
      italic: Verb-ttf/verblight-italic-webfont.ttf
      bold: Verb-ttf/verblight-webfont.ttf
    Calluna:
      normal: Calluna-ttf/Calluna-Regular.ttf
      italic: Calluna-ttf/Calluna-It.ttf
      bold: Calluna-ttf/Calluna-Bold.ttf
      bold_italic: Calluna-ttf/Calluna-BoldIt.ttf
    Apple:
      normal: Apple-Symbols.ttf
  fallbacks:
    - Apple
```
The error message is as such:

/var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font/afm.rb:53:in `initialize':  is not a known font. (Prawn::Errors::UnknownFont)

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:301:in `new'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:301:in `load'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:253:in `find_font'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:57:in `font'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/ext/prawn/extensions.rb:204:in `font'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:169:in `block in apply_font_settings'

	from /var/lib/gems/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:214:in `character_spacing'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:166:in `apply_font_settings'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:77:in `apply_font_settings_and_add_fragment_to_line'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:47:in `wrap_line'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/wrap.rb:53:in `wrap'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/formatted_text/inline_image_arranger.rb:22:in `wrap'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:226:in `block (4 levels) in render'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:101:in `font_size'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/ext/prawn/extensions.rb:261:in `font_size'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:219:in `block (3 levels) in render'

	from /var/lib/gems/2.3.0/gems/prawn-templates-0.1.1/lib/prawn/text.rb:19:in `text_rendering_mode'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:214:in `block (2 levels) in render'

	from /var/lib/gems/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:214:in `character_spacing'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:213:in `block in render'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:212:in `render'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text.rb:380:in `fill_formatted_text_box'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text.rb:217:in `formatted_text'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/text.rb:166:in `text'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:3693:in `typeset_text'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:2802:in `layout_prose'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:1177:in `block (3 levels) in convert_dlist'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:1175:in `each'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:1175:in `block (2 levels) in convert_dlist'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:3583:in `block in theme_font'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:62:in `block in font'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'

	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:60:in `font'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/ext/prawn/extensions.rb:204:in `font'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:3582:in `theme_font'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:1171:in `block in convert_dlist'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:1167:in `each'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:1167:in `convert_dlist'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:138:in `convert'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/list.rb:30:in `convert'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:154:in `convert_content_for_block'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:549:in `convert_section'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:138:in `convert'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:154:in `convert_content_for_block'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:252:in `convert_document'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/lib/asciidoctor/pdf/converter.rb:138:in `convert'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'

	from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'

	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.6/bin/asciidoctor-pdf:32:in `<top (required)>'

	from /usr/local/bin/asciidoctor-pdf:22:in `load'

	from /usr/local/bin/asciidoctor-pdf:22:in `<main>'

**Comment by mojavelinux** [comment]
Please provide a sample repository or a failing test case.

**Comment by dutrow** [comment]
Ok, I'll have to mock one up that doesn't contain proprietary info.

**Comment by mojavelinux** [comment]
:+1:

If you have a private repository, you can just give me access, then delete it later. That avoids having to deal with the proprietary fonts issue. (https://github.blog/2019-01-07-new-year-new-github/).

**Comment by dutrow** [comment]
https://github.com/dutrow/auto-specifications

**Comment by mojavelinux** [comment]
So here's what's happening. The converter is looking for the bold zero-width space character. In your case, it needs it for the workaround that was introduced address the problem described in #1204. Since that character is not provided by the main font, it looks in the fallback font. However, in your theme, the fallback font does not define the bold variant:

```
Apple:
  normal: Apple-Symbols.ttf
```

As a result, the processor crashes. As described in theming guide, you always need to define the fallback font with all four variants, even if you're using the same font:

```
Apple:
  normal: Apple-Symbols.ttf
  italic: Apple-Symbols.ttf
  bold: Apple-Symbols.ttf
  bold_italic: Apple-Symbols.ttf
```

If you define it that way, your document will be converted successfully.

**Comment by mojavelinux** [comment]
I recognize that the message is cryptic. That problem has already been fixed in Prawn upstream, but a version hasn't yet been released containing the fix. If you install Prawn from source, you'll see that the message improves.

Try this Gemfile:

```ruby
source 'https://rubygems.org'

gem 'asciidoctor-pdf'
gem 'prawn', github: 'prawnpdf/prawn'
```

You'd then see:

```
Apple (bold) is not a known font. (Prawn::Errors::UnknownFont)
```

**Comment by mojavelinux** [comment]
As I've explained, this is configuration error. I've further emphasized this point in the theming guide.
