### ISSUE TITLE
Allow glyph set for callout numbers to be configured by theme

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#133]
Allow the glyph set used for callout numbers to be configured by the theme. We can probably allow these to be named sets and then we handle the mapping internally. Proposed sets include:
- outline-circle
- filled-circle
- double-outline-circle

The glyphs are taken from Unicode characters. See http://www.fileformat.info/info/unicode/category/No/list.htm

**Comment by mojavelinux** [comment]
I guess to be consist with CSS, we should name them:

* circle
* disc
* double-circle

...plus, it's less to type.

**Comment by mojavelinux** [comment]
We should also allow the start glyph to be set in case the user wants to use a custom range specific to the font being used.

**Comment by mojavelinux** [comment]
As part of this issue, explain in the theming guide why callout numbers don't often appear when using a custom font (because the font doesn't have the necessary glyphs) and what to do about it.

**Comment by mojavelinux** [comment]
We will need to allow splitting the range since sometimes the numbers jump around in the unicode sequence. Something like:

```
conum:
  glyphs: \u2460-\u2473, \u3251-\u325f
```

**Comment by mojavelinux** [comment]
I decided to go with these names:

* circled (i.e., circled numbers)
* filled (i.e., negative circled numbers)
* double-circled (i.e., double circled numbers)

You can also specify explicit glyphs and/or glyph ranges.

**Comment by miaomiao-study** [comment]
Hi, I use the following settings to let circled numbers display correctly, but number 21 in the PDF is still incorrect(shows empty rectangle), and I'm not sure what to do. Can you help me? (Asciidoctor PDF 2.3.9 using Asciidoctor 2.0.20)
![image](https://github.com/asciidoctor/asciidoctor-pdf/assets/157360586/fad568b8-f09a-4b38-ac11-6ec0fa27451d)
![image](https://github.com/asciidoctor/asciidoctor-pdf/assets/157360586/6d75ba5d-3a8d-46ba-a296-249e9319717a)

**Comment by mojavelinux** [comment]
Please don't comment on closed issues asking for support. All support questions should be directed to the users/asciidoctor-pdf stream in the project chat at https://chat.asciidoctor.org. You're welcome to post your question there.
