### ISSUE TITLE
page-count attribute excludes 

### ISSUE THREAD

**Issue by lorrden** [asciidoctor/asciidoctor-pdf#1334]
This is related to Issue #869. The {page-count} attribute is the number of pages with running content, so “{page-number} of  {page-count}”, will only generate reasonable numbering if page_numbering_start_at is the same as running_content_start_at.

My usecase is to have running content starting at the TOC (and a custom title page with title-specific footers and headers generated by an extension) but page numbering starting at the title page. It seems saner to set page-count based on page_numbering_start instead of running_content_start_at.

**Comment by mojavelinux** [comment]
This looks like it will be pretty easy to fix. The converter is just using the wrong variable name when computing the page count. All the information we need to get it right is available.
