### ISSUE TITLE
Headings should not be indented with section body

### ISSUE THREAD

**Issue by hinamiqi** [asciidoctor/asciidoctor-pdf#1335]
In current realization (Asciidoctor PDF 1.5.0.beta.6 using Asciidoctor 2.0.10) indent of section is applied for subsection headings. It should only be applied on content of section and it subsections. Section titles and discrete headings should not be indented (see image for example -- "Overview" is heading of level 1, and "Product description" is heading of level 2).
![2019-10-08 10_11_57-Smart-UPS UPS Operation Manual](https://user-images.githubusercontent.com/9819411/67077055-11a6a380-f197-11e9-904e-1e38861b2cf4.png)

**Comment by mojavelinux** [comment]
Thanks for reporting!

**Comment by mojavelinux** [comment]
The indent should be applied once to the body. Then the indent should be undone when laying out any section title or discrete heading.

**Comment by mojavelinux** [comment]
I think this will be pretty easy to fix. Unfortunately, it means that as it is currently implemented, the section indent is quite broken. And that's the result of missing tests for the scenarios cited.

**Comment by mojavelinux** [comment]
I would imagine that the indent should also be undo when placing footnotes.

**Comment by mojavelinux** [comment]
I think I've managed to get this working. PR on the way.

After doing some research, I also determined that the following non-heading content should not be indented:

* index body
* footnotes
* abstract

(If other cases come up, we can address them individually).

**Comment by hinamiqi** [comment]
So, if i update it should be working?

**Comment by mojavelinux** [comment]
It hasn't been released yet.
