### ISSUE TITLE
Allow a background image to be specified for the title page

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#134]
Allow a background image to be specified for the title page. This should likely go in the theme, but since it can be closely associated with the content of the document, we can also permit it to be specified using a document attribute.

The image path should be resolved relative to the imagesdir if specified in the document and perhaps the stylesdir if specified in the theme.

For the document attribute, I propose the following name:

```
:title-page-background-image: <path>
```

For the theme, it should be specified under the key:

```
title_page:
  background_image: <path>
```

**Comment by mojavelinux** [comment]
Here's some rough code:

```ruby
bg_image_path = doc.attr 'title-page-background'
bg_image_type = ::File.extname(bg_image_path)[1..-1]
bg_image_path = resolve_image_path doc, bg_image_path
case bg_image_type
when 'svg'
  current_page = page_number
  canvas do
    svg ::IO.read(bg_image_path), at: [0, cursor], width: bounds.width
  end
  go_to_page page_number
else
  canvas do
    image bg_image_path, at: [0, cursor], fit: [bounds.width, bounds.height]
  end
end
```

We do assume that the image should fit the page. In the future we could specify an option, perhaps by honoring the inline image syntax in the value, which could specify a dimension.

**Comment by mojavelinux** [comment]
Note that I'm using the new `resolve_image_path` API that was recently merged in master. This handles all aspects of finding the image, even if it's a remote URI.

**Comment by mojavelinux** [comment]
Since we are using the attribute name `title-logo-image` for the logo image on the title page, I decided to name the attribute for setting the title page background image as `title-background-image`.

```
:title-background-image: image:title-bg.png[]
```

Note that, if specified in the document, the image path is resolved relative to the `imagesdir` attribute. URI values are permitted.

**Comment by anandchida** [comment]
I'm on Asciidoctor PDF 1.5.0.alpha.9 and trying to set a background image on title page.

I tried in the document at the top
:title-background-image: image:http://wallpapercave.com/wp/dLZ5oMU.png[] 

This does not apply the image to the title page. I tried downloading the image to the same location as the document that did not work either. I tried png as well as jpg images. No changes were done to theme.

However, when I tried the logo image on title page, it works on HTML & PDF
:title-logo-image: image:tux.jpg[]

So I'm missing something for the title background image. Any help is appreciated.

**Comment by mojavelinux** [comment]
Are you using AsciidoctorJ by chance? If so, background images won't work until we move to AsciidoctorJ 1.6.0 and Prawn 2. For details, see http://discuss.asciidoctor.org/Asciidoctor-YAML-style-file-for-PDF-and-maven-tp3849p3857.html

**Comment by anandchida** [comment]
I don't think so

Asciidoctor PDF 1.5.0.alpha.9 using Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

and gem list | grep prawn 

prawn (2.0.2)
prawn-icon (1.0.0, 0.6.4)
prawn-svg (0.21.0)
prawn-table (0.2.2)
prawn-templates (0.0.3)

Not a deal breaker .. I can report back later when new versions are made available and it fixes it.

**Comment by mojavelinux** [comment]
Great, then you've got the right versions of things. The problem appears to be that you aren't using the right attribute name. It should be `title-page-background-image`. (I'm not sure why I said in the comments that I named it `title-background-image` because that is incorrect).

```
= Document Title
:title-page-background-image: image:bg.png[]

content
```

If you want to use the image URL, remember that you need to enable the attribute `-a allow-uri-read` when you call `asciidoctor-pdf`.

**Comment by anandchida** [comment]
Thanks! this worked :)  I guess I picked up the background image attributes from your May 25 comment above.

**Comment by asilvestre** [comment]
Hi,

I'm finding a similar problem, my title page background always stays blank, I'm pretty sure I'm not using asciidoctorJ
`Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin13]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)`

and 
`prawn (1.3.0)
prawn-icon (1.0.0)
prawn-svg (0.22.1, 0.21.0)
prawn-table (0.2.2)
prawn-templates (0.0.3)`

I've tried both with customizing the theme
`title_page:
    title_font_size: 28
    background_image: image:images/title_bkg.png[width=500,align=center]`

And placing it in the document:
`= My doc
:title-background-image: image:resources/themes/images/title_bkg.png[]`

Am I doing anything wrong?

Thanks!

**Comment by mojavelinux** [comment]
Are you getting a warning message that the image can't be found or read? Keep in mind that the image will be resolved relative to the `imagesdir` attribute. How are you invoking Asciidoctor?

**Comment by asilvestre** [comment]
I don't get any warning, actually if I consciously put a wrong path I get a warning so I'm pretty sure it's not a problem about paths.

I'm using the following command:

asciidoctor-pdf -a pdf-style=tid -a pdf-fontsdir=$DIR/resources/fonts -a pdf-stylesdir=$DIR/resources/themes mydoc.adoc 

where $DIR is an absolute path

**Comment by mojavelinux** [comment]
To help you debug further, I'm probably going to need you to share a project (on GitHub) that demonstrates this problem. If the image is not showing, there could be dozens of reasons. One thought that comes to mind is that Prawn doesn't like something about that PNG. But that's just speculation.

**Comment by asilvestre** [comment]
Thanks for your help, I've just created this repo [](https://github.com/asilvestre/asciidoctor-test), the gen-doc.sh file has the command I use to call asciidoctor-pdf

**Comment by asilvestre** [comment]
Also I have to say I've tried many different images with the same result, so maybe it won't be an image encoding issue.

**Comment by mojavelinux** [comment]
I ran the gen-doc.sh script in the project you provided and I see a background image on the title page of the generated PDF.

Here's the file: [template.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/196493/template.pdf)

Are you seeing something different?

**Comment by asilvestre** [comment]
Well thanks again for the help, your result is definitely different than mine I don't see any image in the title page.

I've tried both in a osx machine and a linux one and I get the same results, could it be the version I'm using? asciidoctor-pdf-1.5.0.alpha.11 I think it's the last one, maybe I'm missing a library?

**Comment by mojavelinux** [comment]
I should add that before I ran the project, I removed all gems and executed:

```
gem install asciidoctor-pdf --pre
```

So I know I started from scratch. The next step would be to try this in the Asciidoctor Docker container. If that works fine (as I anticipate it will), the only conclusion is that there is something different about your environment.

Which version of Ruby? Are you using RVM? I can't emphasize strongly enough how much I recommend using RVM (or something equivalent like rbenv). That way, you know that Ruby was setup correctly.

**Comment by mojavelinux** [comment]
https://github.com/asciidoctor/docker-asciidoctor

**Comment by asilvestre** [comment]
Thanks a lot, removing all gems and reinstalling worked.

In case it's useful, the differences in versions after the reinstallation were:
- pdf-core 0.4.0 to 0.6.1
- before I had two versions of prawn-svg (0.21.0 and 0.22.1) now I only have the 0.21.0

I guess the problem was the unupdated pdf-core.

**Comment by mojavelinux** [comment]
Thank you for taking the time to get to the bottom of this issue!

> pdf-core 0.4.0 to 0.6.1

It's this change that was the motivation behind my question "are you using AsciidoctorJ" because it happens to be the same problem. While pdf-core is generally very stable, there was a change to page hooks between those two versions that affects how we add a background to the page (image or color). In other words, if you use pdf-core 0.4.0, backgrounds don't work. So that perfectly explains the problem you were observing.

Thanks again for sticking with it!
