### ISSUE TITLE
Add option to clear chapter-title and section-title running content attributes on chapter start page

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1343]
Typically in print, the title shown in the running content doesn't start appearing until after the first page of the chapter. That's because the chapter title is already featured prominently on the page. Asciidoctor PDF should offer a way to match this behavior.

**Comment by mojavelinux** [comment]
Or maybe no running content on these pages?

**Comment by manuel-rubio** [comment]
Yes, I think to avoid running content in those pages can be useful. Otherwise, you can create the "first" new option in the "verso" and "recto" "<side>" element. This way we can also use it to configure more things in a separate way (an increase of top margin, remove header but not footer, ...)

**Comment by joel-loewenstein** [comment]
Any further plans on that? I am exactly in need of it right now... to have a first page without header i mean...

**Comment by mojavelinux** [comment]
> to have a first page without header i mean

Do you mean the first page of the document or the first page of the chapter? If it's the first page of the document, that can already be controlled using the running_content_start_at key in the theme.

**Comment by mojavelinux** [comment]
This feature is not going to move forward until someone can propose **how** this would be configured.

**Comment by mojavelinux** [comment]
The documentation now explains how this can be done using an extended converter. It's a matter of calling `page.imported` on the page that contains the chapter or part title...or any other page the converter is handling. See https://docs.asciidoctor.org/pdf-converter/latest/extend/use-cases/#custom-part-title

If someone would like to make this configurable via the theme somehow, please come forward with a proposal in a new issue.
