### ISSUE TITLE
how to remove page number

### ISSUE THREAD

**Issue by mariomuja** [asciidoctor/asciidoctor-pdf#1356]
I am creating a letter with asciidoctor-pdf and do not want to see any page numbers in the PDF. How can I remove the default page number from the first page?

**Comment by mojavelinux** [comment]
You can remove the running content by setting the `nofooter` attribute.

```
= Letter
:nofooter:

text
```

You cannot remove it from only the first page, though.

**Comment by mariomuja** [comment]
= Letter
prints a big text "Letter" on the page - I do not want to add additional space or text on the page. Just remove the page number.

**Comment by mojavelinux** [comment]
That was just an example. You didn't show me your document, so I could only guess. If you don't have a doctitle, then you'd use:

```
:nofooter:

text of letter.
```

**Comment by mojavelinux** [comment]
You can also disable the running footer using a custom theme.

**my-theme.yml**
```
extends: default
footer:
  height: ~
```

Then run:

```
asciidoctor-pdf -a pdf-theme=./my-theme.yml letter.adoc
```

This is all documented in the theming guide. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#running-content-header--footer

**Comment by mariomuja** [comment]
you saved my day - thanks a lot - also in general for your efforts - we can now throw away our expensive report generators and concentrate on creating raw text files :-)

**Comment by mojavelinux** [comment]
Fantastic! And thanks. I'm really glad to hear it's working out for you. That makes all the efforts worth it.

**Comment by LIttleAncientForestKami** [comment]
My big thanks for your work on this, Dan and folks. <bows>

This comment is just to save others from hours of digging/searching/experimenting, not wishing to reopen or anything. Alternative solution to removing the page numbers BUT KEEPING THE FOOTER is to have a theme with footer being set to one column, have whatever you want in that column (in my case it was a legal clause) and that's it. 

Also, if you're looking for a forum to ask user questions, head over to https://chat.asciidoctor.org.
