### ISSUE TITLE
Include and render HTML into existing adoc file using asciidoctor

### ISSUE THREAD

**Issue by MaciejBala** [asciidoctor/asciidoctor-pdf#1360]
So I have an exisiting adoc template in which I want to include and render HTML file and save it to output PDF file.
The template file includes the following code:
`include::header.adoct[]
include::../owasp_report.html[]`
PDF is generated using gradle command.

I've tried to use .md file as an input but generated PDF file does not render the way I would expect - e.g. markdown `<p>`  is displayed as raw markdown and its values are not rendered.

**Comment by mojavelinux** [comment]
This converter does not support the inclusion of HTML content*. You might be interested in trying [asciidoctor-pdf.js](https://github.com/mogztter/asciidoctor-pdf.js), which is an alternative HTML and browser-based PDF converter.

\* It only supports a small subset of inline HTML, which is really more of a pseudo-language designed for inline formatting.
