### ISSUE TITLE
Wrong position of TOC in PDF outline when using ":toc: macro"

### ISSUE THREAD

**Issue by alexandre-frey** [asciidoctor/asciidoctor-pdf#1361]
- define ":toc: macro" to manually control the location of the toc
- place the toc at the end of the document with "toc::[]"
- convert to PDF using asciidoctor-pdf 1.5.0-beta.7
- look at generated PDF outline: the TOC still appears after the title rather than at the end of the document

![image](https://user-images.githubusercontent.com/3897711/67951129-349b7380-fbeb-11e9-8ef5-14d2b5ae8296.png)

reproducer:
[example.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/3793959/example.zip)

**Comment by mojavelinux** [comment]
Good catch! It certainly makes sense that the outline would reflect the location of the table of contents in the document. I hadn't thought of that.
