### ISSUE TITLE
Rendering of `<` and `>` in literal table cells

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-pdf#1370]
I just noticed that the 'less-than' (`<`) and 'greater-than' (`>`) characters are rendered as their HTML entities `&lt;` and `&gt;` when used in a literal table cell.

Example:

```
|===
l| < and >
|===
```

appears as:

```
&lt; and &gt;
```

**Comment by mojavelinux** [comment]
Right you are! It looks like core is escaping the text for HTML, but that's not needed here. I'll get that fixed and add a test for it. Thanks for catching!
