### ISSUE TITLE
PDF Theming doean'y seem to work, always.

### ISSUE THREAD

**Issue by NormanDunbar** [asciidoctor/asciidoctor-pdf#1381]
Good Afternoon.

I recently updated asciidoctor-pdf from 1.5.0 alpha 16 to 1.5.0 beta 7 and at the same time, asciidoctor updated from 2.0.2 to 2.0.10. This is on WIndows 7 64 bit with these versions:

````
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]

Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:UTF-8 ex:UTF-8)

Asciidoctor PDF 1.5.0.beta.7 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:UTF-8 ex:UTF-8)
````

I have (had) a pdf-theme which added a logo image on the title page,  changed the colour of the background in code blocks and left justified the output as the default (justify) was not very nice - all of which worked nicely. 

Sadly, since the upgrade, it has stopped working. In addition, other changes made to the default theme (I kept a copy!) don't work either. For example, in my customised theme I have this as a quick test, in the correct location, as `E:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\asciidoctor-pdf-1.5.0.beta.7\data\themes\mytheme-theme.yml`:

````
extends: default
base:
  align: left
````

When I execute the command `asciidoctor-pdf -a pdf-style=mytheme test.adoc`, I get the default justification, which I'm trying to avoid. If I directly edit the `default-theme.yml` file and change it there, it works.

However, changing the `code: background_color` in either my theme or the default one, has no effect. This lack of change applied to font colours, background colours for the whole page etc. 

I'm wondering if something changed that has broken pdf-theme styles?

Many thanks.

Cheers,
Norm.

**Comment by mojavelinux** [comment]
A *lot* has changed between those releases, but there are also now over 750 tests to ensure there are no regressions. It's possible something unexpected has slipped through. I'll need a concrete example that shows what stopped working. You can create a sample project on GitHub or upload a zip file that demonstrates the problem.

> For example, in my customised theme I have this as a quick test, in the correct location

You should not be putting custom themes inside the installed gem location. You should put them either in the same project as the document or in your home / user directory somewhere. The invocation should look like:

```
asciidoctor-pdf -a pdf-theme=./mytheme-theme.yml test.adoc
```

(pdf-theme accepts a path anywhere on the filesystem).

**Comment by NormanDunbar** [comment]
Good Evening @mojavelinux 

Thanks for the quick response. When I get back to work and have a coffee break, I'll get a test case for you.

The reason my theme is in the standard location is to avoid having it in numerous different document locations, however, I'll create a central location and use that path instead.

Cheers,
Norm.

**Comment by NormanDunbar** [comment]
Good Morning @mojavelinux,

It wasn't the theming that was broken, it seems it was the system location for the themes itself.

When I used a local theme, as suggested above, it worked fine. (All the changes I wanted were applied). 

When I used a theme in the system location, as advised _against_ above, it didn't work. I wonder why? A bit of digging and I found this:

````
gem contents asciidoctor-pdf --show-install-dir
E:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0-alpha.16
````
For some reason, the old `alpha 16` asciidoctor-pdf gem's path is being used instead of the `beta 7`. When I moved my theme in there, again, against your advice, it did work as expected. However, I'm now using local themes as per your advice above. (Thanks.)

So, now, how do I get the path corrected I wonder? Can I simply gem uninstall (or similar) the old version(s) or is there a command to update things? Sorry, I'm not a Ruby developer so I'm not able to make a suggestion here. (Windows 7)

Thanks.


Cheers,
Norm.

**Comment by mojavelinux** [comment]
And now you know why we recommend against putting themes directly into the gem installation directory ;)

It sounds like you have two versions of the gem installed. If you run `gem uninstall`, you should see a menu that allows you to uninstall older versions.

**Comment by NormanDunbar** [comment]
Good Evening @mojavelinux.

My theme(s) shall forever remain separate! 

I have uninstalled the old versions and the path is now correctly defined for the latest beta.

As ever, many thanks for all the hard work you do for us.


Cheers,
Norm.

**Comment by mojavelinux** [comment]
Glad to hear it, Norm!
