### ISSUE TITLE
Render < and > in tables

### ISSUE THREAD

**Issue by mcfly83** [asciidoctor/asciidoctor-pdf#1389]
When using < or > in tables, these are rendered to &lt; and &gt; in the PDF. Is there any way to escape these characters?

**Comment by mojavelinux** [comment]
Is this a duplicate of #1370, or are you asking for something different? If so, please provide a sample document (in a code block).

**Comment by mcfly83** [comment]
You're right, sorry for the duplicated issue. Looks like this will be fixed in the next release then, right?
I'll go ahead and close this.

**Comment by mojavelinux** [comment]
Yep. And a new release is likely coming this weekend.
