### ISSUE TITLE
Need a parameter in basic-theme.yml that forces linefeed on special character

### ISSUE THREAD

**Issue by regdorf59** [asciidoctor/asciidoctor-pdf#1390]
**Situation**:
In adoc tables with fixed column widths, text wraps arbitrarily, and in sometimes undesirable locations. 

**Example:**
contactList[].address[].attentionLi
ne

**Issue/Bug:**
When rendered as PDF, search for the wrapped text (i.e., attentionLine), yields no result. 

**Recommendation:**
Create a parameter that can be set in the yml file that forces a line feed at specific characters (i.e., [].)

**Comment by mojavelinux** [comment]
There's already a character to do this. It's the zero-width space. It introduces a break opportunity if one is needed. Here's how you'd write it:

```
[cols=2;1,width=50%]
|===
|contactList[]{zwsp}.address[]{zwsp}.attentionLine | veeeeeeery long
|===
```

(If you need this to be automatic, you can use a TreeProcessor extension to modify the contents of the cells with custom logic).

> When rendered as PDF, search for the wrapped text (i.e., attentionLine), yields no result.

This has nothing to do with this converter, as established in #1253. Please follow the upstream issue to advocate for an improvement to the PDF library.

**Comment by regdorf59** [comment]
Thanks for the suggestions, but I've decided that PDF is too limiting and frustrating to work with as an electronic delivery format. Instead, I'm now publishing good ol' HTML. :)

**Comment by mojavelinux** [comment]
I think that's a wise choice ;)
