### ISSUE TITLE
Regression: Text formatting not being applied to footnotes

### ISSUE THREAD

**Issue by dohliam** [asciidoctor/asciidoctor-pdf#1397]
This specifically affects footnotes called using attribute references. Any formatting (other than links) is ignored.

Version: Asciidoctor PDF 1.5.0.beta.7

This was working perfectly in Asciidoctor PDF 1.5.0.alpha.18.

## Minimal test document

```asciidoc
:fn-att: footnote:[Some footnote text with _italics_ and *bold* and a https://asciidoctor.org[URL] link.]

Text with a footnote.footnote:[Some footnote text with _italics_ and *bold* and a https://asciidoctor.org[URL] link.]

Text with a footnote in an attribute.{fn-att}
```

Result:

![image](https://user-images.githubusercontent.com/9295750/69139263-00420700-0a75-11ea-8c03-db957b527d92.png)

**Comment by mojavelinux** [comment]
Very likely this issue has to do with a change to Asciidoctor core, not Asciidoctor PDF. It's just that when you upgraded, you likely changed version of Asciidoctor core too. And in core, the order of substitutions changed.

I strongly recommend against defining the footnote macro in an attribute. It's fine to define the text that way, but the macro should be defined at the point of use.

Here's how I recommend writing this:

```
:fn-text: pass:n[Some footnote text with _italics_ and *bold* and a https://asciidoctor.org[URL] link.]

Text with a footnote.footnote:[{fn-text}]
```

**Comment by mojavelinux** [comment]
It turns out this was not a change in core. If you test any version of core, you'll find your syntax does not work. So that the fact that it did work in Asciidoctor PDF at some point was, itself, a bug.

**Comment by mojavelinux** [comment]
I tried with Asciidoctor PDF 1.5.0.alpha.18 and I observe that your syntax doesn't even work there. But it doesn't really matter, because what I know for sure is that the syntax is incorrect.

**Comment by dohliam** [comment]
Thanks for the quick response! I tried out the version with the footnote in place, and it does indeed work fine. (I had been avoiding using a passthrough since -- at least in previous versions -- asciidoctor-pdf has not seemed to support them.)

If this syntax has been deprecated, the docs should probably be updated, since using the footnote macro in an attribute is specifically recommended there in the section on [Externalizing a Footnote](https://asciidoctor.org/docs/user-manual/#externalizing-a-footnote):

> Since footnotes are defined using an inline macro, the footnote content ends up right alongside the text it’s annotating, making that text harder to read. You can solve this probably by externalizing your footnotes using document attributes.

And the example given there is:

```asciidoc
:fn-hail-and-rainbow: footnote:[The double hail-and-rainbow level makes my toes tingle.]
:fn-disclaimer: footnote:disclaimer[Opinions are my own.]

The hail-and-rainbow protocol can be initiated at five levels:
double, tertiary, supernumerary, supermassive, and apocalyptic party.{fn-hail-and-rainbow}
A bold statement!{fn-disclaimer}

Another outrageous statement.{fn-disclaimer}
```

If you add some text formatting to the example above from the User Manual, it also does not work in asciidoctor-pdf.

By the way, is the `pass:n` syntax documented somewhere? It seems useful, but a search in the manual doesn't turn up any results. Previously I have been using `pass:q` with the HTML backend, which has usually worked well (though of course not for the PDF backend).

**Comment by mojavelinux** [comment]
> By the way, is the pass:n syntax documented somewhere

"n" is for normal". "q" is for just quotes, which you need to be careful with. It's documented here: https://asciidoctor.org/docs/user-manual/#inline-pass-macro-and-explicit-substitutions

**Comment by dohliam** [comment]
Thanks -- I see there that the following are listed:

* `c` = special characters
* `q` = quotes
* `a` = attributes
* `r` = replacements
* `m` = macros
* `p` = post replacements

I'm familiar with these already, but I don't see any mention of "`n` = normal". Perhaps it could be added once the new docs site is up?

**Comment by dflock** [comment]
I've just bumped into this too! I followed the documentation here [Externalizing a Footnote](https://docs.asciidoctor.org/asciidoc/latest/macros/footnote/#externalizing-a-footnote) and found that formatting doesn't work inside footnotes. In order to get text formatting to work in footnotes, I had to find this issue via google, then change this:

```asciidoc
:fn-disclaimer: footnote:disclaimer[Opinions are *my own*.]

A bold statement!{fn-disclaimer}
```

to this:

```asciidoc
:fn-disclaimer: pass:n[Opinions are *my own*.]

A bold statement!footnote:[{fn-disclaimer}]
```

**Comment by dflock** [comment]
Hmmm. This, combined with this https://github.com/asciidoctor/asciidoctor/issues/3690#issuecomment-778956139 - means that you can't have text formatting in an externalized footnote, if you want to use it more than once, because then it'll get repeated - because the `:fn-1: pass:n[...]` form doesn't have an ID. :disappointed:

**Comment by mojavelinux** [comment]
You can. You just have to declare the ID each time you use the footnote:

```
:fn-disclaimer: pass:n[Opinions are *my own*.]

A bold statement!footnote:disclaimer[{fn-disclaimer}]

Another bold statement!footnote:disclaimer[{fn-disclaimer}]
```

Another approach is to define it this way:

```
:fn-disclaimer: pass:q[footnote:disclaimer[Opinions are *my own*.]]

A bold statement!{fn-disclaimer}

Another bold statement!{fn-disclaimer}
```

You do have to be mindful of how you are applying substitutions, but it is possible if you use the right combo.

**Comment by mojavelinux** [comment]
Since we know that text formatting can be applied in a footnote, I'm closing this issue. Please open a new one if there's a specific use case you cannot achieve.
