### ISSUE TITLE
Autowidth not working properly with table headers

### ISSUE THREAD

**Issue by lorrden** [asciidoctor/asciidoctor-pdf#1399]
I have a table like:

```
[%autowidth]
|===
| Foobar | Fooo | Baaar 

| - | - | -
|===
```

When rendered the heading text gets wrapped before the last character.

**Comment by mojavelinux** [comment]
You need to use the unreleased version of prawn-table to get this feature. See https://github.com/asciidoctor/asciidoctor-pdf#upgrade-prawn-and-extensions-optional
