### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-pdf#14]
I haven't been able to install `asciidoctor-pdf` in my system configuration, as opposed to one tailored specifically for `asciidoctor-pdf`.  I  need this because I need to call `/usr/bin/asciidoctor-pdf` 
(from a mac osx app, [asciihelper](https://github.com/jxxcarlson/asciihelper).  

Below is a log of my failure to install: (1) Just try to do it - fail on pdf-core (2) Install pdf-core by itself; (3) retry and fail with message that contradicts the facts: pdf-core was installed,
and Ruby _is_ of version >= 1.9.3.

(1) Just try to do it.
```
$ rvm system
$ rvm list

rvm rubies

   ruby-1.9.3-p429 [ x86_64 ]
   ruby-1.9.3-p547 [ x86_64 ]
   ruby-2.0.0-p195 [ x86_64 ]
   ruby-2.0.0-p451 [ x86_64 ]
   ruby-2.1.0 [ x86_64 ]
   ruby-2.1.1 [ x86_64 ]
 * ruby-2.1.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

$ bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Enter your password to install the bundled RubyGems to your system: 
Using rake (10.3.2) 
Using Ascii85 (1.0.2) 
Using afm (0.2.2) 
Using asciidoctor (1.5.0.rc.6) 
Using coderay (1.1.0) 
Installing pdf-core (0.2.5) 
Gem::InstallError: pdf-core requires Ruby version >= 1.9.3.
An error occurred while installing pdf-core (0.2.5), and Bundler cannot continue.
Make sure that `gem install pdf-core -v '0.2.5'` succeeds before bundling.
```

(2) Install pdf-core by itself
```
$ gem install pdf-core -v '0.2.5'
Fetching: pdf-core-0.2.5.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
$ sudo gem install pdf-core -v '0.2.5'
Fetching: pdf-core-0.2.5.gem (100%)
Successfully installed pdf-core-0.2.5
Parsing documentation for pdf-core-0.2.5
Installing ri documentation for pdf-core-0.2.5
1 gem installed
```
3) retry and fail with message that contradicts the facts: pdf-core was installed,
and Ruby _is_ of version >= 1.9.3.
```
$ bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake (10.3.2) 
Using Ascii85 (1.0.2) 
Using afm (0.2.2) 
Using asciidoctor (1.5.0.rc.6) 
Using coderay (1.1.0) 
Installing pdf-core (0.2.5) 
Gem::InstallError: pdf-core requires Ruby version >= 1.9.3.
An error occurred while installing pdf-core (0.2.5), and Bundler cannot continue.
Make sure that `gem install pdf-core -v '0.2.5'` succeeds before bundling.
```

**Comment by graphitefriction** [comment]
@jxxcarlson @mojavelinux As we're prepping for Alpha 9 I was doing a little issue gardening - have all the issues/observations reported above been parsed out into their own issues yet? And if so, you know what you can do with this one :grinning:

**Comment by mojavelinux** [comment]
I'm pretty sure we've captured all the feedback. If something slipped through, just file a new issue and we'll take care of it!
