### ISSUE TITLE
How to set the width of PlantUML UML?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-pdf#1402]
I include some PlantUML diagram to the AsciiDoctor.
If I set the width to 100%, the HTML is OK. But the PDF is too small. 
If I set the width to 960px, the PDF is OK. 

**Why does not the 100% width work  for PDF?**

**Comment by habamax** [comment]
I guess you have to use either `pdfwidth=100%` or `scaledwidth=100%` ?

Check documentation: https://asciidoctor.org/docs/user-manual/#pdfwidth

It states that `width` for pdf accepts pixels only.

**Comment by mojavelinux** [comment]
@habamax is correct. Currently, Asciidoctor PDF assumes that the value of the width attribute is in pixels. It ignores the % unit. You must specify the pdfwidth attribute if you want to use a % width in PDF.

```
[plantuml,width=50%,pdfwidth=50%]
....
E.T. -> Home: Phone
rnote over Home: silence
....
```

I don't see any reason not to support the % value on the width attribute in Asciidoctor PDF, so I'll go ahead and add it.
