### ISSUE TITLE
How to show the footnotes at the end of the current page?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-pdf#1412]
Today, I test the footnotes. They are shown at the end of the chapter.
**How to show the footnotes at the end of the current page?**

**Comment by mojavelinux** [comment]
They cannot be shown at the end of the current page. The way this converter is written, and the capabilities that Prawn (the PDF generator) offers just make that impossible. The best we can do is at the end of a content break (chapter for book, document for article).

**Comment by diguage** [comment]
Recently, I configure the Chinese theme well, the Maven AsciiDoctor plugin can generate PDF document. It's great. I appreciate AsciiDoctor and you. Thanks a lot.

I read  [CSS Secrets: Better Solutions to Everyday Web Design Problems: Lea Verou](https://www.amazon.com/CSS-Secrets-Solutions-Everyday-Problems/dp/1449372635/). Lea Verou said the book was generated by O’Reilly Safari Book. It was written on the AsciiDoctor. The sidebar (maybe footnote) is very fantastic. Maybe it is a goode example. Hope the AsciiDoctor PDF reach the target as soon so possible.

![image](https://user-images.githubusercontent.com/2121467/69790317-3ada3b00-11fd-11ea-8d6a-324930a41c50.png)


![image](https://user-images.githubusercontent.com/2121467/69790605-b5a35600-11fd-11ea-8019-bcf99952c458.png)

**Comment by mojavelinux** [comment]
> Hope the AsciiDoctor PDF reach the target as soon so possible.

That's not a goal for this converter. That's something that asciidoctor-pdf.js can help you achieve.
