### ISSUE TITLE
asciidoc-pdf ignores {zwsp} if and only if pdf-theme is used

### ISSUE THREAD

**Issue by JayanSmartACI** [asciidoctor/asciidoctor-pdf#1413]
When I render the below asciidoc I get different outputs if a pdf-theme is applied or not:

------------------------------
:myWord: This{zwsp}Is{zwsp}My{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Long{zwsp}Word{zwsp}That{zwsp}Needs{zwsp}To{zwsp}Break{zwsp}Correctly

[cols="85,15"]
|===
| No zwsp
| ThisIsMyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongWordThatNeedsToBreakCorrectly

| No Substitution used
| This{zwsp}Is{zwsp}My{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Really{zwsp}Long{zwsp}Word{zwsp}That{zwsp}Needs{zwsp}To{zwsp}Break{zwsp}Correctly

| With substitution
| {myWord}
|===

------------------------------

The pdf output using the following command:
asciidoctorj.bat -b pdf -a pdf-theme=theme/sandbox-theme.yml -o ./sandbox.pdf ./sandbox.adoc

Tables ignore the {zwsp} tags in the content.

![image](https://user-images.githubusercontent.com/58257621/69726725-c5ea0100-1129-11ea-8bad-81847b457ca2.png)

But when the command used does not include "-a pdf-theme" then the output is correct.

![image](https://user-images.githubusercontent.com/58257621/69726660-a81c9c00-1129-11ea-86d4-b02b1dfc685d.png)

When I started investigating this I assumed it was my use of substitutions in the tables causing the issue, but this does not appear to be the case.

**Comment by mojavelinux** [comment]
What font are you using? Can you share your theme file?

Note that the zero-width space feature is not supported when using AFM fonts (i.e., built-in PDF fonts).

**Comment by JayanSmartACI** [comment]
My theme file only contains: extends: default

Is there a font you recommend me trying?

**Comment by JayanSmartACI** [comment]
The following theme produced working behavior:
-----

extends: default
font:
  catalog:
    M+ 1mn:
      normal: mplus1mn-regular-subset.ttf
      bold: mplus1mn-bold-subset.ttf
      italic: mplus1mn-italic-subset.ttf
      bold_italic: mplus1mn-bold_italic-subset.ttf
base:
  font_family: M+ 1mn

-----

![image](https://user-images.githubusercontent.com/58257621/69801072-28510900-11df-11ea-8acc-36d089f836a9.png)

**Comment by mojavelinux** [comment]
I see you are using AsciidoctorJ. Which version of AsciidoctorJ PDF? It seems to me that it's using the AFM font, which indicates it's a version of AsciidoctorJ PDF that predated the "extends" feature. So, in fact, your theme is blank.

I tested with AsciidoctorJ PDF 1.5.0-beta.5 and the line breaks at the zwsp.

**Comment by JayanSmartACI** [comment]
Here are all my versions:
----------------------------
asciidoctorj-2.0.0.jar
asciidoctorj-api-2.0.0.jar
asciidoctorj-diagram-1.5.16.jar
asciidoctorj-epub3-1.5.0-alpha.9.jar
asciidoctorj-pdf-1.5.0-alpha.17.jar
jcommander-1.35.jar
jruby-complete-9.2.7.0.jar

**Comment by mojavelinux** [comment]
As I suspected, that version is substantially out of date. We're now up to 1.5.0-beta.8. You're using a version that predated the `extends` keyword in the theme file. So your theme is blank, which is why it's defaulting to the Helvetica AFM font. As you have already figured out, you can add the font catalog and set the font manually. You just can't use `extends: default` without upgrading.

**Comment by JayanSmartACI** [comment]
Hi,

I have confirmed that new versions fix all my problems (including a bunch of other ones I have been trying to fix). Who'd have thought it, new versions actually help...

Thanks for your help and quick response. You can close this issue.
