### ISSUE TITLE
Indent new hardbreak line

### ISSUE THREAD

**Issue by terzim** [asciidoctor/asciidoctor-pdf#1417]
It appears asciidoctor-pdf can only indent paragraphs, not hardbreak lines. 

The fix below would not work, as it would affect all the text and not distinguish between hardbreaks and paragraphs. 
prose:
  text-indent: 18
  margin-inner: 0

**Comment by mojavelinux** [comment]
Yes, that's correct. A hard line break doesn't create a separate paragraph, so the line after it doesn't get indented. This is consistent with how CSS works.

**Comment by blling** [comment]
How to do hard break in `CJK`? CJK and English combined with line breaks look ugly

**Comment by mojavelinux** [comment]
Please ask this question in the chat channel at https://gitter.im/asciidoctor/asciidoctor.
