### ISSUE TITLE
Square root symbol is not displayed correctly

### ISSUE THREAD

**Issue by feliwir** [asciidoctor/asciidoctor-pdf#1418]
So I'm using `asciidoctor-pdf` together with `asciidoctor-mathematical`. As the stem i'm using `latexmath`. I producude both HTML and PDFs from my formula and the HTML output is looking correct:
![image](https://user-images.githubusercontent.com/2104576/69944632-12e22480-14e8-11ea-82ba-55f5f912f175.png)

The PDF output looks like the following:
![image](https://user-images.githubusercontent.com/2104576/69944699-2db49900-14e8-11ea-85cb-3dd0aa941351.png)

I'm using the following stem expression:
`stem:[\epsilon_{max} = ps*\sqrt{1+r^2}, r > 1]` 

I also verified that this error is not related to my custom theme, by using the default theme. Any ideas on how i could avoid this issue?

**Comment by feliwir** [comment]
This is by the way not a duplicate of: https://github.com/asciidoctor/asciidoctor-mathematical/issues/42
Installing the dejavu package makes no difference.

**Comment by mojavelinux** [comment]
It appears you are missing fonts required by mathematical. This doesn't pertain in any way to Asciidoctor PDF or the custom theme. Asciidoctor Mathematical generates a raster image of the expression, then Asciidoctor PDF embeds that image into the document.

I tried your example using the [Asciidoctor Docker](https://github.com/asciidoctor/docker-asciidoctor) image and it worked fine. Here's what I see:

![stem-f381a9c98229e489ba55b40a89ea2eff](https://user-images.githubusercontent.com/79351/70514477-f5691800-1af0-11ea-83f5-56b14f57be07.png)

Perhaps you can use the Docker image as your guide to figure out what you might be missing.

**Comment by yota-code** [comment]
I stumbled today on the exact same issue !

@feliwir did you found which font was missing ?
