### ISSUE TITLE
Document attributes in `include`d files

### ISSUE THREAD

**Issue by rschuetzler** [asciidoctor/asciidoctor-pdf#1420]
I am working on a book/website project and have every chapter separated into different files, each with their own attributes (so they can be rendered individually for the website). When I try to create the master "book.adoc" file that includes the chapters, I end up with a paragraph blob of metadata in each chapter. 

For example, the `book.adoc` file:

```asciidoc
= Title
My name <myemail@email.org>
v0.1
:page-published: false
:doctype: book
:source-highlighter: coderay
:icons: font

include::chapter1.adoc[]
```

And the `chapter1.adoc` file:

```
= Chapter 1
My name <myemail@email.org>
v0.1, 2018-05-05
:icons: font
```

Ends up with an output like this for chapter 1:

![image](https://user-images.githubusercontent.com/600775/70287357-3b8e4680-1794-11ea-9125-5f67ce4e7f3f.png)

I am fairly certain I've used these same files, or files like them, with older versions of `asciidoctor-pdf` and not had this issue. Is there a way I can get the document header to be processed for `include`d files?

**Comment by mojavelinux** [comment]
The include directive does not weave together subdocuments. Instead, it takes the lines from the included file and dumps them into the stream. Therefore, it doesn't have any awareness of other document headers. You need to use the explicit attribute form for your chapters.

```
= Chapter 1
:author: My name
:email: myemail@email.org
:revnumber: v0.1
:revdate: 2018-05-05
:icons: font
```
