### ISSUE TITLE
asciidoctor: WARNING: conversion missing in backend pdf for stem

### ISSUE THREAD

**Issue by uweschmitt** [asciidoctor/asciidoctor-pdf#1424]
I installed `asciidoctor` and `asciidoctor-mathematical` successfully, but get the following warnings:
```
$ asciidoctor-pdf -r asciidoctor-mathematical /documents/main.adoc
asciidoctor: WARNING: conversion missing in backend pdf for stem
asciidoctor: WARNING: conversion missing in backend pdf for stem
```

More info:
```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.8 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]) (lc:US-ASCII fs:US-ASCII in:US-ASCII ex:US-ASCII)
```
and:
`asciidoctor-mathematical` is of version `0.3.1`

Any idea what I did wrong?

**Comment by mojavelinux** [comment]
This is an indication you are missing the required `stem` attribute in the document header to active stem support.

```
:stem: latexmath

[stem]
++++
sig = enc(H(D), s)
++++
```

Please try again with this attribute set. (You can also set it via the CLI).

**Comment by uweschmitt** [comment]
Thanks for the reply, regrettably I have this setting `:stem: latexmath` already in my document.

**Comment by mojavelinux** [comment]
Can you please provide a reproducible example?

My guess is that where you are setting `stem` is not in the header. The warning only happens if asciidoctor-mathematical isn't activated. And the way it is activated is by setting the stem attribute to `latexmath`.

You might also try:

```
asciidoctor-pdf -a stem=latexmath -r asciidoctor-mathematical /documents/main.adoc
```

**Comment by uweschmitt** [comment]
Here is my minimal example:

```
=== Example
:doctype: book
:stem: latexmath


[latexmath]
++++
\sqrt{4} = 2
++++
```

**Comment by mojavelinux** [comment]
As I suspected, you aren't setting `stem` in the document header. A level-2 heading does not create a document header. Here's how you would express it instead:

```
:doctype: book
:stem: latexmath

=== Example

[latexmath]
++++
\sqrt{4} = 2
++++
```

But setting the `stem` attribute from the CLI would also work.

**Comment by uweschmitt** [comment]
Thanks for clarifying this!
