### ISSUE TITLE
Add a way to hide level 0

### ISSUE THREAD

**Issue by sabatmonk** [asciidoctor/asciidoctor-pdf#1427]
*It might be i am using wrong settings*
Is there a way to hide level 0 from ToC and the document without disabling front page? I have documents  that are 1 chapter but need a title page. Those documents do not need to include the title as a first level in ToC and in the pdf itself. Can it be hidden?

**Comment by sabatmonk** [comment]
there was an issue with my source, a conflict error made a second level 1 appear(it was the same text, so i assumed it was the lvl 0), there is no issues

sorry

**Comment by mojavelinux** [comment]
You can try to add `[abstract]` above the chapter title to see if that gives you what you want. The abstract is not included in the TOC.
