### ISSUE TITLE
afdko is a better set of tools for fonts.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-pdf#1438]
I wanted the ttf fonts of Source Han Serif. So I submit an issue on the repo. 

The maintainer replied to the issue and recommend a tool, the `otf2ttf` tool from the AFDKO. 

Then I tested the tool. I think **it is a better and simpler tool than FontForge. I recommend adding a document about the tools.** 

The reply is: <https://github.com/adobe-fonts/source-han-serif/issues/82#issuecomment-567161775>.

The document of the tools: [afdko | Adobe Font Development Kit for OpenType](http://adobe-type-tools.github.io/afdko/AFDKO-Overview.html).

The repo of the tools: [adobe-type-tools/afdko: Adobe Font Development Kit for OpenType](https://github.com/adobe-type-tools/afdko/).

**Comment by mojavelinux** [comment]
That's good to know. Thanks for sharing. If you'd like to include this information in the README or theming guide, feel free to submit a PR.

From what I can see, FontForge can do many more things than afdko, such as copying glyphs around, but I can see room for afdko when the needs are simpler.

**Comment by diguage** [comment]
OK. Let me try it.

**Comment by mojavelinux** [comment]
I think FontForge is sufficient for what we're trying to do, and easier for users to understand. If you want to provide a tutorial for how to use afdko, I will consider it for the docs. Or, you could publish a blog post somewhere that explains how to use it. I'm not going to take the time right now to look into afdko.
