### ISSUE TITLE
table verse cells are not verse

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1448]
# Test document
```
= Test


[cols=".^1,.^2", options="header"]
|=============================================================================

| header1
| header1

v|this
should
be
on
different
lines
| another cell 

|=============================================================================

.Regular verse
[verse]
_______
this
should
be
on
different
lines
_______
```

# Result PDF
![image](https://user-images.githubusercontent.com/234774/71510314-8553e380-289f-11ea-99d1-76267468a8c5.png)

I remember it worked at least several months ago

**Comment by mojavelinux** [comment]
FYI, verse table cells have been deprecated in AsciiDoc. The reason is that a cell doesn't provide the structure necessary to support the element properly. The preferred approach is to use a verse block inside an AsciiDoc table cell.

I may still include the verse cell in Asciidoctor PDF 1.5.0 and drop it in Asciidoctor 2.0.0 (to follow what core did). But either way, it's not long for this world.

**Comment by habamax** [comment]
Ok, got it. What about documentation? It is still there

**Comment by mojavelinux** [comment]
It will be removed from the documentation soon being launched at docs.asciidoctor.org.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor/issues/3111 for reference.

**Comment by habamax** [comment]
I have used versed table cells and I did miss that issue you have mentioned.

Regular verse block in a `a|` style table cell is not the same as it has additional formatting from the theme :).

Anyway I have resolved it with `+` at the end of the lines.

**Comment by mojavelinux** [comment]
> Regular verse block in a a| style table cell is not the same as it has additional formatting from the theme :).

As it should. Anything else would be something undefined.

> Anyway I have resolved it with + at the end of the lines.

That's the correct way to have hardbreaks for a normal table cell.

**Comment by habamax** [comment]
Just to give you impression where it could be used :)

![image](https://user-images.githubusercontent.com/234774/71511418-59d2f800-28a3-11ea-82fa-037d87d22d64.png)

**Comment by mojavelinux** [comment]
This is a key reason why the verse style was dropped. It was being used for things that are clearly not a verse.

**Comment by habamax** [comment]
> This is a key reason why the verse style was dropped. It was being used for things that are clearly not a verse.

That is true, indeed!

**Comment by mojavelinux** [comment]
I will very likely restore support for 1.5.0 and drop in 2.0.0. (The reason it broke is because there's no test for it).

**Comment by mojavelinux** [comment]
I just realized I can't restore support because the parsing of the style is handled in core. So this is controlled by what version of core you are using. In order for the verse style to work in the old way, you'd need to use Asciidoctor < 2.0.0.

**Comment by habamax** [comment]
> I just realized I can't restore support because the parsing of the style is handled in core. So this is controlled by what version of core you are using. In order for the verse style to work in the old way, you'd need to use Asciidoctor < 2.0.0.

I don't think this is a problem, hardbreaks for the rescue
