### ISSUE TITLE
Undefined header_cell_font_style

### ISSUE THREAD

**Issue by dutrow** [asciidoctor/asciidoctor-pdf#1468]
We are running asciidoctor-pdf-1.5.0.rc.1

When building, we get the following error:
undefined local variable or method `header_cell_font_style' for #<Asciidoctor::PDF::Converter:0x00007ffb4082d2f8>

when building a doc that contains a table that looks like the following:

[width=100%,cols="<h,<h", frame=none, grid=none]
|=======================================================================
| Standard Services
| Professional Services
|=======================================================================

with the following settings and a theme I can provide by request.

:title-page:
:table-stripes: even
// enabling font-awesome fonts and making a check shortcut
:icons: font
:icon-set: fa
:y: icon:check[]

**Comment by dutrow** [comment]
Should lib/asciidoctor/pdf/converter.rb line 1957 refer to header_cell_font_info instead? The build hint suggests it should: 

Did you mean?  header_cell_font_info

**Comment by mojavelinux** [comment]
Yep, that looks like a bug. My main concern is that the test suite didn't catch it. So the fix is to add a failing test, then fix the bug.

**Comment by habamax** [comment]
Oh, it is in your repo, not in asciidoctor pdf yet. :)

Thx!

**Comment by mojavelinux** [comment]
PR https://github.com/asciidoctor/asciidoctor-pdf/pull/1470

**Comment by habamax** [comment]
Thank you!
