### ISSUE TITLE
missing fonts (5714a6 + FontAwesome5Free-Solid) in a produced pdf file

### ISSUE THREAD

**Issue by dusicong** [asciidoctor/asciidoctor-pdf#1469]
I finally produced an English pdf file after I cloned to the very right now version. (same with issue#1461 before)
However, when I open the file, there comes the caution.

![image](https://user-images.githubusercontent.com/20656749/71871245-ef03a580-315b-11ea-97ba-83e57d77e241.png)

It means "5714a6 + FontAwesome5Free-Solid can not be found so that some characters cannot be shown correctly, nor be printed".
And after I checked the content, it turns out all the "g" is missing(I suppose they are 5714a6 ?). And a note icon also isn't shown.

Could you help me fix the problem?
By the way, my ruby version:
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x64-mingw32]

**Comment by dusicong** [comment]
I found out the reason.
That is I have two versions of prawn-icon, and two versions of prawn-svg in my gem.
That makes conflicts.

Sorry for bothering.

**Comment by mojavelinux** [comment]
Please use 1.5.0.rc.1 and make sure to clean out your gems so you get the correct versions.
