### ISSUE TITLE
[FATAL] Failed to allocate memory

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1473]
Current (today's) master on Win10 using default theme.

I have tried to recompile my current document and it takes quite a lot of time (~30 seconds) and then dies with FATAL error.

![image](https://user-images.githubusercontent.com/234774/71890250-ed82af00-3154-11ea-90c6-3cf82adc02b2.png)

I will try to simplify document and provide it to you.

**Comment by habamax** [comment]
Hmm

```
|| Error: Could not create the Java Virtual Machine.
|| Error: A fatal exception has occurred. Program will exit.
issue-1473.adoc|398| Failed to generate image: undefined method `[]' for nil:NilClass
issue-1473.adoc|765| Failed to generate image: Broken pipe
issue-1473.adoc|975| Failed to generate image: Broken pipe
|| asciidoctor: WARNING: image to embed not found or not readable: C:/Users/maksim.kim/docs/test/images/hl-arch-v12-migration.svg
|| asciidoctor: WARNING: image to embed not found or not readable: C:/Users/maksim.kim/docs/test/images/img_rbbg-dq-solution-design_1.png
|| asciidoctor: WARNING: image to embed not found or not readable: C:/Users/maksim.kim/docs/test/images/hl-arch.svg
|| asciidoctor: WARNING: image to embed not found or not readable: C:/Users/maksim.kim/docs/test/images/dq-framework-int-arch.svg
|| asciidoctor: WARNING: image to embed not found or not readable: C:/Users/maksim.kim/docs/test/images/img_rbbg-dq-solution-design_2.png
|| [FATAL] failed to allocate memory
```

**Comment by mojavelinux** [comment]
I highly doubt this was due to a change in the converter as nothing fundamental changed in how the document is produced. This seems to be more a problem with your environment. Based on the output, it seems you are invoking via JRuby. Is there a reason you are using JRuby instead of just C Ruby?

**Comment by habamax** [comment]
# Test File
```
= Issue 1473: Plantuml? asciidoctor-diagram?
:imagesdir: images

== Introduction

[plantuml, hello_world, svg, width=70%]
....
skinparam monochrome true
skinparam shadowing true
skinparam dpi 300
skinparam backgroundcolor transparent
skinparam classarrowFontSize 8

!define table(x) class x << (T,#ede7aa) >>
!define view(x) class x << (V,lightblue) >>
!define f(n,t) {field}n <color:gray>: t</color>
!define string(n,size) {field}n <color:gray>: varchar(size)</color>

hide methods
hide stereotypes

table(DQI_ENGINE.DQI_SCHEDULE) {
	f(**sch_id**, **number**)
	..
	string(dqi_plan_name, 500)
	string(sch_type, 20)
	f(priority, number)
	string(day_of_month, 100)
	string(day_of_week, 100)
	string(hour, 100)
	string(reference_date, 10)
	f(is_enabled, boolean)
}

....

```

# command
`asciidoctor-pdf -r asciidoctor-diagram issue-1473.adoc`

# output
NONE,  20 minutes passed, it still "works"

**Comment by habamax** [comment]
> Based on the output, it seems you are invoking via JRuby. Is there a reason you are using JRuby instead of just C Ruby?

I dont use JRuby. I suspect it is the output from the asciidoctor-diagram plantuml.

**Comment by mojavelinux** [comment]
Yes, I see that now with your second example.

**Comment by mojavelinux** [comment]
I would try generating HTML output using asciidoctor. If that doesn't work, then the issue is with asciidoctor-diagram (or with how your system is invoking it). I really don't see how this is an Asciidoctor PDF issue.

**Comment by mojavelinux** [comment]
Btw, the example works for me. (Make sure you clean out your gems and reinstall to be sure there isn't a bad mix of dependencies).

**Comment by habamax** [comment]
> I would try generating HTML output using asciidoctor. If that doesn't work, then the issue is with asciidoctor-diagram

Doesn't work with asciidoctor. Will try to reinstall it.

**Comment by mojavelinux** [comment]
:+1:

**Comment by habamax** [comment]
I have reinstalled everything:

0. kill ruby 2.6 with all gems
1. install ruby 2.7
2. install gems

everything with asciidoctor-diagram just hangs.

Kind of weird as most of my docs include diagrams and suddenly I am in trouble :)

Is there a way to install previous version gem of asciidoctor-diagram?

**Comment by habamax** [comment]
Yes!

![image](https://user-images.githubusercontent.com/234774/71896172-0ba3db80-3164-11ea-8b35-1a10b9005716.png)


The issue is in asciidoctor-diagram 2.0.0

I have reinstalled previous version with `gem install asciidoctor-diagram -v 1.5.9` and with that version everything works!

**Comment by habamax** [comment]
This is funny...

It turns out that asciidoctor-diagram v 2.0.0 (the same way as prev version) also works just fine... unless in the document there is a table with header cells with the issue https://github.com/asciidoctor/asciidoctor-pdf/issues/1474 

Then I got this weird behavior of 10+ minutes to compile a document that usually takes a couple of seconds.

If I remove header cells from the document I can compile it without a problem and it takes 2 secs.

**Comment by habamax** [comment]
And this becomes even more weird as with 2.0.0 I am not able to convert test file attached here:

![vim-asciidoctor-diagram1](https://user-images.githubusercontent.com/234774/71900711-60991f00-316f-11ea-8adc-26f79a7230a2.gif)


But I can do it with 1.5.19 easily:

![vim-asciidoctor-diagram2](https://user-images.githubusercontent.com/234774/71900732-6c84e100-316f-11ea-9a64-5254420b4141.gif)

**Comment by habamax** [comment]
That is asciidoctor-diagram issue https://github.com/asciidoctor/asciidoctor-diagram/issues/254#issuecomment-571632957

**Comment by habamax** [comment]
Just to clarify my prev comments.


> 
> This is funny...
> 
> It turns out that asciidoctor-diagram v 2.0.0 also works just fine... unless in the document there is a table with header cells with the issue #1474

It doesn't work -- if there are generated images exist then it should do nothing and it does nothing.
If there is no generated image -- it tries to generate it and hangs.

It turned out that I have generated images with 1.5.19 version and then tried 2.0.0 without deleting them.
