### ISSUE TITLE
Souce highlighter in asciidoctor-pdf 1.5.0-rc1 uses now a foreground and background color for certain parts at the same time.

### ISSUE THREAD

**Issue by lwolter** [asciidoctor/asciidoctor-pdf#1482]
source-highlighter=pygments
pygments-css=style
pygments-linenums-mode=inline

```
[source,ps1]
----
$backupDirConstPart = "backup_inc_"
----
```

"backup_inc_" text color: red; background color: light red -- similar highlight color

**Comment by mojavelinux** [comment]
That's how the Pygments style you're using (pastie) is configured. Asciidoctor PDF is honoring those settings. You can confirm this by converting to HTML.

![pastie-style](https://user-images.githubusercontent.com/79351/72013874-fee2be80-321b-11ea-8d95-8e470db75bb2.png)

If you don't like that look, you can use a different style.

```
-a pygments-style=default
```

Then you'll get:

![default-style](https://user-images.githubusercontent.com/79351/72013964-33567a80-321c-11ea-8a80-7bd403ef2b18.png)

**Comment by lwolter** [comment]
Many thanks!! 

So far, I had not explicitly specified the style.

**Comment by mojavelinux** [comment]
Yes, because Asciidoctor PDF didn't full support all the style properties. Now it does.
