### ISSUE TITLE
How to number and reference equations in PDF

### ISSUE THREAD

**Issue by aldib** [asciidoctor/asciidoctor-pdf#1487]
I was able to get STEM blocks to work with asciidoctor-pdf but I can't figure out how to number and reference equations.

Is **:eqnums:** supported in asciidoctor-pdf? 
If yes, how do I enable it and reference an equation?
If not, what's the best way to manually/automatically create a referenceable call-out/anchor for a STEM block?

Any help is appreciated and thank you in advance.

**Comment by mojavelinux** [comment]
> Is :eqnums: supported in asciidoctor-pdf?

Only if is supported by asciidoctor-mathematical...so I doubt it. This referencing is not really something that's in scope for Asciidoctor PDF. It's probably something we'll revisit for asciidoctor-pdf.js, though it may even require help from core.

**Comment by graphitefriction** [comment]
You can assign an ID to stem blocks for referencing them. The equation number must be added by Asciidoctor Mathematical.
