### ISSUE TITLE
Allow vertical-align theme key for header and footer to be numeric

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1488]
All the vertical-align key for the header and footer categories in the theme (i.e., the running content) to be a numeric value. A positive value is interpreted as an offset from the top of the box (like a top padding). A negative value is interpreted as an offset from the bottom of the box (like a bottom padding). A zero value is an alias of top.

Note that the behavior of this key differs from the matching property in CSS (where it is ill-defined anyway).

**Comment by mojavelinux** [comment]
There's one other way we could interpret this value. We could compute it as an offset from the middle vertical alignment (positive for up, negative for down). That way, you can control alignment with respect to the middle of the box.

**Comment by 1marc1** [comment]
Dan,

Just thinking about this. Let's take the foyer as an example. Say on the left you have the document title along with the project name (something that can get lengthy and result in two lines of text). On the right you have something like the page number. 

How would you control that the page number ends up on the same line as the first or second line of the left hand side content?

Marc.

**Comment by 1marc1** [comment]
Thinking about it some more, would the offset be controllable for left, centre and right side running content?

Marc.

**Comment by 1marc1** [comment]
For example, does the solution cater for the following scenarios:

****
My document.                 Page 1
XYZ Project.
****

****
My document.
XYZ Project.                        Page 1
****

Marc.

**Comment by 1marc1** [comment]
On the previous example the "Page 1" bit belongs to the right side. 

Marc.

**Comment by mojavelinux** [comment]
> Thinking about it some more, would the offset be controllable for left, centre and right side running content?

Let's keep this in scope. We are talking about vertical alignment here.

**Comment by mojavelinux** [comment]
> How would you control that the page number ends up on the same line as the first or second line of the left hand side content?

That's what makes this difficult. Is the goal to control the position of the vertical center of the text, or is the goal to control the position of the boundary (top or bottom) of the text? And since CSS doesn't really implement vertical-align in an sort of sensible way, we lack a good mental model to build on.

I think the right solution here is to go with a computed value so it's clear. First you set the vertical alignment, then an offset from that position. 10 points from the top would be `top+10`. 10 points from the bottom would be `bottom-10`. And 2 points down from center would be `middle+2`.

So to answer your question, you would set `top+offset` to achieve your first scenario and `bottom+offset` to achieve your second. And the offset is only required if not already accounted for in the overall padding.

**Comment by mojavelinux** [comment]
Except to make this work, we need to use an array. The first element is text vertical-align, the second is the numeric offset.

**Comment by mojavelinux** [comment]
So that idea worked out when I implemented it. It's a bit awkward to use two values, but ultimately it gives you the most control where you need it.

```
footer:
  vertical-align: [bottom, -10]
```

or

```
footer:
  vertical-align: [middle, 5]
```

**Comment by 1marc1** [comment]
Sounds good. I like the idea of the flexibility.
So, if my understanding is correct, specifying something like:
```
footer:
  vertical-align: [top, 10]
```
will be interpreted in code as: start the first line of footer text at the position 10 down from the top of the footer box.

While specifying something like:
```
footer:
  vertical-align: [bottom, -10]
```
will be interpreted as: ensure the last line of footer text ends up at the position 10 up from the bottom of the footer box. The code will then ensure that if it is printing a multi-line string, the start position will be higher up on the page than if it were printing a single-line string. Is that correct?

Marc.

**Comment by mojavelinux** [comment]
Precisely.
