### ISSUE TITLE
custom-theme.yml - "extends: default" differs from the actual default pdf theme

### ISSUE THREAD

**Issue by xorcus** [asciidoctor/asciidoctor-pdf#1489]
Hi, I am using asciidoctor pdf gradle plugin 2.4.0

If I do **not** set attribute 'pdf-stylesdir' and 'pdf-style', I get a nice looking PDF with gray text, light blue links, etc.

On the other hand, if I set the two attributes to use my `custom-theme.yml` (as shown in the example [asciidoc-to-pdf-with-theme-example](https://github.com/asciidoctor/asciidoctor-gradle-examples/tree/master/asciidoc-to-pdf-with-theme-example)), having the `custom-theme.yml` with only the one line:

```
extends: default
```

I get a not so nicely looking PDF (e.g. the text color is black, the links are a different blue, etc.). I have also tried with `extends: base`, but the effect seems to be the same.

Is there a way to use `extends` and have exactly the same styling as we get when the 'pdf-stylesdir' and 'pdf-style' attributes are omitted?

**Comment by mojavelinux** [comment]
> Is there a way to use extends and have exactly the same styling as we get when the 'pdf-stylesdir' and 'pdf-style' attributes are omitted?

That's exactly what `extends: default` does.

Are you sure you're using a recent version (1.5.0 RC 2)?

**Comment by mojavelinux** [comment]
(Btw, the attributes have been renamed to `pdf-themesdir` and `pdf-theme`).

**Comment by mojavelinux** [comment]
Yep, the version you're using is too old. These feature was added in alpha.18. See https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.5.0.alpha.18.

**Comment by xorcus** [comment]
gradle plugin `2.4.0` seems to be using asciidoctor-pdf `1.5.0-alpha.16`
gradle plugin `3.0.0-alpha4` (the latest one at the moment) seems to be using asciidoctor-pdf `1.5.0-beta.8`

**Comment by mojavelinux** [comment]
To be clear, all you need to do with the example is change:

1.5.5 -> 1.5.8

1.5.0-alpha.15 -> 1.5.0-alpha.18

Trying to upgrade to the new Gradle plugin is a much more involved task.

**Comment by mojavelinux** [comment]
So it will look like this at the top of build.gradle:

```groovy
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.8.1'
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.18'
    }
}

plugins {
    id 'org.asciidoctor.convert' version '1.5.8.1'
}
```

**Comment by xorcus** [comment]
Perfect, thx!
