### ISSUE TITLE
Travis CI cache is reuploaded for every build

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-pdf#1500]
For example: https://travis-ci.org/asciidoctor/asciidoctor-pdf/jobs/637866445#L655

```
store build cache
$ bundle clean
changes detected (content changed, file is created, or file is deleted):
/home/travis/build/asciidoctor/asciidoctor-pdf/.bundle/gems/ruby/2.5.0/bundler/gems/prawn-table-515f2db29486/.git/index
/home/travis/build/asciidoctor/asciidoctor-pdf/.bundle/gems/ruby/2.5.0/bundler/gems/prawn-table-515f2db29486/.git/logs/HEAD
changes detected, packing new archive
uploading master/cache--linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--rvm-2.5.7--gemfile-Gemfile.tgz
cache uploaded
```

I believe this happens for every build.

**Comment by mojavelinux** [comment]
Yes, my understand is that's just how it works. Do you have a proposal to modify the behavior?

**Comment by slonopotamus** [comment]
This costs 25-30s per each job on Travis currently. And reupload happens because of that prawn-table file. If that single file didn't change, cache would not be reuploaded, because your dependencies didn't change since previous run.

**Comment by slonopotamus** [comment]
Can you download prawn-table through more conventional means, like rubygems?

**Comment by slonopotamus** [comment]
Here's an example (from a different project) of build that does not reupload anything: https://travis-ci.org/slonopotamus/kindlegen/jobs/639359718#L228

**Comment by mojavelinux** [comment]
> Can you download prawn-table through more conventional means, like rubygems?

**Comment by mojavelinux** [comment]
We might be able to remove the .git directory inside of bundler's cache before the build is done so that it doesn't think it has changed.

Honestly, though, I really don't care that much that it adds half a minute since the JRuby build takes so much time anyway. That's really the bottleneck.

**Comment by mojavelinux** [comment]
I may need to make follow-up commits. I'll post once it's all working.

**Comment by slonopotamus** [comment]
Yep, you need to build at least twice on the same branch to see that it is really fixed.

**Comment by mojavelinux** [comment]
```
nothing changed
```

I think we got it.
