### ISSUE TITLE
Make CI builds on Travis run faster

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-pdf#1503]
0. Each of JRuby jobs takes ~12min.
1. `bundle exec rake lint` runs in every job (including JRuby). On JRuby, it takes 2min 50s. Suggested solution: only run lint on one platform.
2. `JRUBY_OPTS='--dev'` makes tests run *slower*. With it: [5min 50s](https://travis-ci.org/asciidoctor/asciidoctor-pdf/jobs/640321762#L680). Without it: [4min 50s](https://travis-ci.org/asciidoctor/asciidoctor-pdf/jobs/640327161#L685). Suggested solution: remove `JRUBY_OPTS`.
3. It is a common situation when all other jobs have finished, but JRuby is still running, leading to increased wallclock time of a build. This happens because JRuby jobs are near the end of job + the fact that number of jobs is greater than number of runners. Suggested solution: move JRuby jobs to the beginning of job list.

**Comment by mojavelinux** [comment]
> only run lint on one platform.

That's very reasonable. We should also see if we can run it first so that we know something is wrong right away (maybe even fail fast).

**Comment by mojavelinux** [comment]
> JRUBY_OPTS='--dev' makes tests run slower. 

According to the JRuby docs: "you can pass the --dev option to JRuby to choose the fastest-starting JVM and JRuby flags (at the expense of long-running code speed)."

So I guess we have enough tests now that we've transitioned into "long-running code". And in that case, you're right, we want the optimizer.

**Comment by mojavelinux** [comment]
> move JRuby jobs to the beginning of job list.

Seems reasonable.

**Comment by mojavelinux** [comment]
We should identify what our current run time is so we know what we're measuring against. Here's a sample run:

Ran for 17 min 14 sec
Total time 58 min 5 sec
Ruby: 2.7.0 - 4 min 50 sec
Ruby: 2.6.5 - 4 min 42 sec
Ruby: 2.5.7 - 4 min 56 sec
Ruby: 2.4.9 - 4 min 43 sec
Ruby: 2.3.8 - 5 min 26 sec
Ruby: jruby-9.2.9.0 - 12 min 4 sec
Ruby: jruby-9.1.17.0 - 11 min 26 sec
Ruby: 2.3.8 ASCIIDOCTOR_VERSION=1.5.3 - 5 min
Ruby: 2.3.8 ROUGE_VERSION='~> 2.0.0' - 4 min 58 sec

**Comment by slonopotamus** [comment]
> Ran for 17 min 14 sec

Be careful here, it is affected by the number of available runners. Normally, Travis gives 5 runners but sometimes when there are other builds running (PRs or whatever), so we do not get all 5.

**Comment by mojavelinux** [comment]
The numbers seem pretty consistent to me. So whatever limits we get assigned, it seems we get them consistently.

**Comment by mojavelinux** [comment]
12 minutes total seems the be the low end, 20 minutes seems to be the high end based on a quick survey of runs.

**Comment by mojavelinux** [comment]
One of the main issues with testing on JRuby on Travis is an RVM problem. JRuby is being downloaded and installed each time, and it's very slow. If Travis could provide JRuby (as part of RVM), then we wouldn't be waiting around for this.

```
rvm use jruby-9.2.9.0 --install --binary --fuzzy (90s)
```

**Comment by slonopotamus** [comment]
> I really can't understand why Travis leaves RVM installs so out of date.

You're running on Ubuntu 14.04. I really can't understand why Travis still supports it at all ;)

**Comment by mojavelinux** [comment]
There's a lot to not understand about Travis, TBH. The infrastructure is woefully out of date.

**Comment by mojavelinux** [comment]
> You're running on Ubuntu 14.04.

That has nothing to do with RVM. RVM is a user space program. (Thought it's still a good point).

Last I checked, trusty was all they offered.

**Comment by mojavelinux** [comment]
Oh yeah, they finally have new versions of Ubuntu: https://docs.travis-ci.com/user/reference/linux#overview

I don't see why would shouldn't be using the highest one.

**Comment by slonopotamus** [comment]
> That has nothing to do with RVM.

Travis has different versions of development software pre-installed on different OS versions.

**Comment by mojavelinux** [comment]
Ah, I was wrong about this. You're right. They have coupled RVM with the OS. I can't really understand why. The whole point of RVM is that you aren't bound to the OS. But whatever. That's the way it is.

Bionic includes Ruby 2.6, so we definitely want to be on that.
