### ISSUE TITLE
landscape mode

### ISSUE THREAD

**Issue by janicemhdc** [asciidoctor/asciidoctor-pdf#1510]
I would like to be able to create PDF documents in landscape mode. I want to make quick reference cards that use the same source as my main documentation but in order to fit the information into as small a space as possible I need landscape mode.

I apologize if I missed this, but the only support I see is landscape mode for tables for docbook output only.

**Comment by mojavelinux** [comment]
You can set landscape mode using the following attribute in the document header:

```
:pdf-page-layout: landscape
```

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#theme-related-document-attributes

**Comment by janicemhdc** [comment]
Thanks! I did look through documentation but it didn't occur to me to look at a theming guide if I wasn't creating a full theme. Sorry.

**Comment by mojavelinux** [comment]
No need to apologize. The docs aren't the easiest to find right. Once we roll out docs.asciidoctor.org, there will be separate pages for each major topic such as this one. Then, it will be much easier to find what you're looking for. We're just not moving anything around until that change happens. So you're concern has definitely been heard.
