### ISSUE TITLE
u

### ISSUE THREAD

**Issue by Doktor210488** [asciidoctor/asciidoctor-pdf#1514]
data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMyIgaGVpZ2h0PSIxMyIgdmlld0JveD0iMCAwIDMgMTMiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIG9wYWNpdHk9IjAuNSIgZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0zIDEuNUMzIDIuMzI4NDMgMi4zMjg0MyAzIDEuNSAzQzAuNjcxNTczIDMgMCAyLjMyODQzIDAgMS41QzAgMC42NzE1NzMgMC42NzE1NzMgMCAxLjUgMEMyLjMyODQzIDAgMyAwLjY3MTU3MyAzIDEuNVpNMyA2LjVDMyA3LjMyODQzIDIuMzI4NDMgOCAxLjUgOEMwLjY3MTU3MyA4IDAgNy4zMjg0MyAwIDYuNUMwIDUuNjcxNTcgMC42NzE1NzMgNSAxLjUgNUMyLjMyODQzIDUgMyA1LjY3MTU3IDMgNi41Wk0xLjUgMTNDMi4zMjg0MyAxMyAzIDEyLjMyODQgMyAxMS41QzMgMTAuNjcxNiAyLjMyODQzIDEwIDEuNSAxMEMwLjY3MTU3MyAxMCAwIDEwLjY3MTYgMCAxMS41QzAgMTIuMzI4NCAwLjY3MTU3MyAxMyAxLjUgMTNaIiBmaWxsPSJibGFjayIvPgo8L3N2Zz4K

**Comment by mojavelinux** [comment]
Closing for being incomplete. Please refile with a proper subject and description.
