### ISSUE TITLE
pdf-page-size attribute not working

### ISSUE THREAD

**Issue by janicemhdc** [asciidoctor/asciidoctor-pdf#1518]
I placed the following at the top of my main adoc file:

`:pdf-page-size: 11in x 14in`

which, according to the PDF Theming Guide, should work as a document attribute:

```
pdf-page-size | Named size \| Measurement[width, height] | :pdf-page-size: 6in x 9in
```

(see https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#theme-related-document-attributes)

But it has no effect at all on my PDF output. It's still generating a standard 8.5x11 page

**Comment by rillbert** [comment]
Could it be that you need to have the measures in the same format as the pdf-page-margin attribute, that is:

`:pdf-page-size: [11in, 14in]`

and that the example in the guide has a typo?

/Anders

**Comment by janicemhdc** [comment]
Yes, that's it! Thanks! I'll submit a doc PR with the update

**Comment by mojavelinux** [comment]
The original example is valid syntax. There's even a test to verify it. https://github.com/asciidoctor/asciidoctor-pdf/blob/master/spec/page_spec.rb#L45-L53 Are you using the 1.5.0.rc.2 release?

**Comment by janicemhdc** [comment]
asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.beta.8 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17])

**Comment by janicemhdc** [comment]
Assuming the test is run in isolation, I respectfully submit that it's not a valid test given that it's setting the size to the default used if no size is specified.

**Comment by mojavelinux** [comment]
Please use 1.5.0.rc.2. It could be that this was fixed in one of the recent releases.

**Comment by mojavelinux** [comment]
> it may not be a valid test given that it's setting the size to the default used if no size is specified.

The default if not size is specified is A4. The test is changing it to Letter. So the test is valid.

**Comment by mojavelinux** [comment]
I checked and this works even on beta.8. So there must be something incorrect / incompatible about your document. Could you share a complete sample that demonstrates the issue?

**Comment by mojavelinux** [comment]
We need to figure out what the scenario is so that we can add a better test, if necessary ;)

**Comment by janicemhdc** [comment]
hmmm, if the default is A4 then why aren't things running off the bottom of the page when I use it in portrait? I'm pretty sure A4 is a fair bit longer than letter. In any case I will follow up on the requests above but it will likely be a few days.

**Comment by mojavelinux** [comment]
I'm not sure, but the default is definitely A4. See: https://github.com/asciidoctor/asciidoctor-pdf/blob/f24a0de771e72c45b8cc38b493bf885b11027fff/data/themes/default-theme.yml#L23

A4 is somewhat taller than Letter, but not substantially.

A4 = 8.26in x 11.69in
Letter = 8.5in x 11in

**Comment by janicemhdc** [comment]
I don't know what was going on the other day, but the [Nin x Min] format appears to be working now (no version upgrade). I guess I'll close this and reopen it if it happens again. I hate inconsistent behavior.

**Comment by janicemhdc** [comment]
Wait, it was the other syntax that wasn't working. Sigh, I clearly should not be working right now.

**Comment by mojavelinux** [comment]
Happens to me all the time ;)

**Comment by janicemhdc** [comment]
Okay, this time I triple checked. Both syntaxes are currently working. Hopefully it stays that way :) I have no idea what happened before.

**Comment by mayeulk** [comment]
Hi,
I had difficulties having this work (especially since comments above say "widht x heigh" is OK) **with the command line**. So this might help others.
This works for me:

     asciidoctor-pdf --attribute=pdf-page-size="[14cm, 14cm]" myfile.asciidoc

The following DOES NOT worked:
`asciidoctor-pdf  attribute=pdf-page-size="[14cm x 14cm]" action-bookmark.asciidoc`

Config:
Asciidoctor PDF 2.3.19 using Asciidoctor 2.0.23 [https://asciidoctor.org]
Runtime Environment (ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
