### ISSUE TITLE
Add CI testing for JRuby on Windows

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-pdf#1520]
Subj. This is a very fragile environment with its own class of bugs that deserves dedicated testing.

**Comment by slonopotamus** [comment]
Current Windows+JRuby picture: https://github.com/slonopotamus/asciidoctor-pdf/runs/408612060?check_suite_focus=true#step:5:17

**Comment by slonopotamus** [comment]
After a bit of fixing, there are only [5 failing tests](https://github.com/slonopotamus/asciidoctor-pdf/runs/408999273?check_suite_focus=true#step:5:53)

**Comment by mojavelinux** [comment]
If you rebase, the CLI path test should now be working.

**Comment by slonopotamus** [comment]
I [did](https://github.com/asciidoctor/asciidoctor-pdf/pull/1496#issuecomment-578488161) and yes, it passes now.

**Comment by mojavelinux** [comment]
Try again. We should be down to 0. If not, then the redirection just doesn't work on JRuby on Windows and we'll disable it.

**Comment by slonopotamus** [comment]
Oh, we forgot about this PR. Resolved by #1496.

**Comment by mojavelinux** [comment]
This is now working.
