### ISSUE TITLE
Only report "Could not locate the character" message once per character

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-pdf#1545]
As mentioned https://github.com/asciidoctor/asciidoctor-maven-examples/pull/94, this message can appear a lot of times (in https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-cjk-example appears hundreds of times).

While not an issue, it would help to diagnose and treat errors if each missing character only appeared once in the output.

**Comment by mojavelinux** [comment]
It will need to be once per character + font set (since the same character could be missing from multiple fonts).
