### ISSUE TITLE
Prawn::Icon - DEPRECATION WARNING 

### ISSUE THREAD

**Issue by joaompinto** [asciidoctor/asciidoctor-pdf#1554]
While generating a PDF for an .adoc file containing:
`:icons: font`
I get the following warning:

> [Prawn::Icon - DEPRECATION WARNING]
>   FontAwesome 4 icon was referenced as 'fa-exclamation-triangle'.
>   Use the FontAwesome 5 icon 'fas-exclamation-triangle' instead.
>   This compatibility layer will be removed in Prawn::Icon 3.0.0.

**Comment by mojavelinux** [comment]
Yes, that's correct. Is there something unclear about the message?

**Comment by mojavelinux** [comment]
Hmm, actually, I see that it's the same icon name. Let me look closer.

**Comment by joaompinto** [comment]
I am not using --warnings, shouldn't this warning be disabled by default ?

**Comment by mojavelinux** [comment]
It looks like you have some old gems lying around. Can you run `gem list`?

**Comment by joaompinto** [comment]
```
$ gem list

*** LOCAL GEMS ***

addressable (2.5.2)
afm (0.2.2)
Ascii85 (1.0.3)
asciidoctor (2.0.10)
asciidoctor-pdf (1.5.0.alpha.17.dev)
atomic (1.1.16)
bigdecimal (default: 1.3.4)
cmath (default: 1.0.0)
concurrent-ruby (1.0.5)
css_parser (1.6.0)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.1)
etc (default: 1.0.0)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
hashery (2.1.2)
i18n (0.7.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
minitest (5.11.3)
net-telnet (0.1.1)
openssl (default: 2.1.2)
pdf-core (0.8.1)
pdf-reader (2.1.0)
polyglot (0.3.4)
power_assert (1.1.1)
prawn (2.2.0)
prawn-icon (2.4.0)
prawn-svg (0.29.1)
prawn-table (0.2.2)
psych (default: 3.0.2)
public_suffix (3.0.3)
rake (12.3.1)
rdoc (default: 6.0.1)
rouge (3.8.0)
ruby-rc4 (0.1.5)
safe_yaml (1.0.4)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.8)
thread_safe (0.3.6)
treetop (1.6.7)
ttfunk (1.5.1)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)

```

**Comment by joaompinto** [comment]
Sorry, everything is fine after a gem update.
Thanks

**Comment by mojavelinux** [comment]
Yeah, you were on an old alpha. That issue did exist, but was fixed.

If the icon is not found in Font Awesome 5, and you have verbose mode on (meaning info-level messages), you will see a message like this:

```
asciidoctor: INFO: vcard icon found in deprecated fa icon set; using address-card from fas icon set instead
```
