### ISSUE TITLE
Hyphenation: superflous dash if the word to split contains a dash already

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#1562]
Given the term "Domain-Driven Design" and hyphenation to be applied between "Domain" and "Driven", the result is:

…Domain--
Driven Design

Note the extra dash added to the line ending.

**Comment by mojavelinux** [comment]
It's the PDF generator that's adding this extra dash. It adds a dash without considering whether the preceding character is a dash. I'll see if we can patch it.

**Comment by mojavelinux** [comment]
Backport this to 1.5.x.
