### ISSUE TITLE
Some image files are not closed after being read

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1566]
Prawn does not close image files by default. While there is code to address this problem in Asciidoctor PDF, some of the cases are being missed. Specifically, background images and admonition icon images are not being closed.

While this doesn't generally cause problems on Linux, it can cause problems on Windows. We can observe this problem in our own test suite as the attempt to unlink temporary image files is failing.

**Comment by mojavelinux** [comment]
backport this to 1.5.x

**Comment by slonopotamus** [comment]
> the attempt to unlink temporary image files is failing

Maybe it should mark test as failed?

**Comment by mojavelinux** [comment]
Yep, good idea. At first I thought it wasn't possible, but then I thought of a way.

**Comment by slonopotamus** [comment]
I can't believe that file deletion API wouldn't tell you whether it succeeded deleting or not :)

**Comment by mojavelinux** [comment]
It does. I didn't realize that the error was in our log. Plus, I realized there were other cases we were missing.

**Comment by mojavelinux** [comment]
It turns out that due to the order of call operations, temporary files generated by the running content weren't being deleted either.
