### ISSUE TITLE
Adding TOC entry for a table

### ISSUE THREAD

**Issue by beratozbay** [asciidoctor/asciidoctor-pdf#1569]
Hello,

Is there any way to add an entry to TOC. I wanted to add a table to TOC and luckly i have a heading in the table. But heading doesn't appear in the TOC.

```asciidoc
= Test
:toc:

== Section X

[cols="2*"]
|===

a| == Section Y
| Nope

| Nope
| Nope

|===

```

So, I just wanted to add "Section Y" to TOC.

**Comment by mojavelinux** [comment]
Section titles inside of an AsciiDoc table cell are considered part of a different document and thus will not show up in the TOC. The TOC only includes headings from the primary document.

If you want to add additional items to the toc, you can extend the converter and override the layout_toc_level method. It's possible to reuse the existing logic using a call to `super`.

```rb
class MyPDFConverter < (Asciidoctor::Converter.for 'pdf')
  def layout_toc_level sections, num_levels, line_metrics, dot_leader, num_front_matter_pages = 0
    super
  end
end
```

"sections" is the variable you'll want to manipulate.

**Comment by mojavelinux** [comment]
This is going to be made easier by #2097.

**Comment by mojavelinux** [comment]
> Is there any way to add an entry to TOC. I wanted to add a table to TOC and luckly i have a heading in the table. But heading doesn't appear in the TOC.

You are actually asking something different than what the subject suggests. Sections inside an AsciiDoc table cell are not part of the same document and therefore do not appear in the TOC. If you want the section title to be in the TOC, you need to take it out of the table.

Since this issue is too vague to act on, I'm going to close it.
