### ISSUE TITLE
Support different footer_background_image for landscape and portrait page orientation

### ISSUE THREAD

**Issue by thucke** [asciidoctor/asciidoctor-pdf#1570]
Hi,

when I switch page orientation for individual pages (using [.landscape] and [.portrait]) I also want to set a new background image for that page(s).
The new image should respect the wider aspect without being scaled vertically like now.
Best would be in my opinion if it'd be possible to define different images in the theme yaml (e.g. `footer_background_image` as default and optionally `footer_background_image_portrait` and `footer_background_image_landscape`).

Thanks in advance
Thomas

**Comment by mojavelinux** [comment]
We substitute attribute references in the target of the image macro (i.e., the image path). So what we could do is temporary define and attribute to represent the page orientation. Then, you could use this attribute reference in the image path so that you get the image that matches the layout.

For example:

```
footer:
  background-image: image:footer-bg-{current-page-layout}.png[]
```

wdyt?

**Comment by thucke** [comment]
Thank you for picking my issue.
Do I understand correctly that additionally to the switch of the page orientation an author has to set the attribute in the document?
I'm not sure if I would prefer that way as it would be redundant work.
What if you just look for files that end with '*-portrait.png' or '*-landscape.png' in addition to the default '*.png'. By convention over coding this would minimize the fault risk on the authors side and gives theme authors full control over their design.

**Comment by mojavelinux** [comment]
> Do I understand correctly that additionally to the switch of the page orientation an author has to set the attribute in the document?

No, it would be dynamic.

**Comment by mojavelinux** [comment]
> What if you just look for files that end with '-portrait.png' or '-landscape.png' in addition to the default '*.png'. 

That feels like too much magic to me and is not how any other part of the converter works. It's better to require that it be a dynamic segment of the path.

**Comment by thucke** [comment]
Now then. I'm convinced you're much more familiar in all those mechanisms than I do.
I'm still in the beginning using this great authoring tool.
Would be great having a tiny working example for better understanding when you're done.
Greets
Thomas

**Comment by thucke** [comment]
Hi @mojavelinux ,

I spent some thoughts about your suggestion. I think now I understand it right ;-)
If I configure the image resource in the template as you suggested I only have to put two image files into the template directory:
```
1. footer-bg-portrait.png[]
2. footer-bg-landscape.png[]
```
When the converter recognizes `{current-page-layout}` in the resource definition it automatically replaces it according to the current page layout.

That would really be a perfect solution!
Sorry for my lack of understanding as of yesterday.

Greets 
Thomas

**Comment by thucke** [comment]
Hi @mojavelinux ,

hoping you're well and in good health this times.
I tried this enhancement using v1.5.3 without success.
In my theme I've got ``footer_background_image: image:images/footerBackground-{page-layout}.png[]`` having two files in the directory ``images``:
* ``footerBackground-portrait.png``
* ``footerBackground-landscape.png``

Building the PDF I got the following INFO message:
``asciidoctor: WARN: footer background image not found or readable: /home/thucke/devJava/dokumentation/betriebskonzept/src/main/resources/themes/images/footerBackground-{page-layout}.png``

What am I doing wrong?

Greets
Thomas

**Comment by mojavelinux** [comment]
> I tried this enhancement using v1.5.3 without success.

It's not available in 1.5.3. It has been solved in the upcoming 2.0.0 release.

**Comment by thucke** [comment]
Thank you. I  thought the merge was already in version 1.5.3.

**Comment by mojavelinux** [comment]
If you would be willing to test master, that would ensure it's right when 2.0.0 is released. (Instructions in https://github.com/asciidoctor/asciidoctor-pdf/blob/master/CONTRIBUTING-CODE.adoc).
