### ISSUE TITLE
image align not working on custom theme

### ISSUE THREAD

**Issue by jerCarre** [asciidoctor/asciidoctor-pdf#1592]
Hello,

I define a new theme (for slides) and I want to center all my images.
I add this code in my yml : 

image:
  align: center

But all my images stay on left.
I don't extend any theme.

Also, is it possible to define image alignment inside macro part like pdfwidth
`image:images/logo.png[pdfwidth=40%]`

thx

**Comment by tolgacanatan** [comment]
I have reproduced same issue. I also reproduced it with `width` key. 

My example is:

* I'm using  ` image:images/logo.png[]` in the .adoc file
* I'm using following image definition on my theme .yml file (it is extending default theme)
```
image:
  width: 50%
```

`width: 50%` is not working on .pdf output. All images has appeared at their actual size without shrinking width values by 50%.

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#image

My asciidoctor-pdf version is :
```
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

I also attached my .yml theme file. [myexample-theme.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/4294422/myexample-theme.zip)
Am I missing something? 

Thanks.

**Comment by mojavelinux** [comment]
The alignment applies to block images, not inline images. The example you have provided uses an inline image. Use two colons instead of one to make a block image.

You can set the image alignment globally using the theme:

```
image:
  align: center
```

Or per image using the align attribute.

```
image::logo.png[pdfwidth=40%,align=center]
```

**Comment by jerCarre** [comment]
Thank you !
I used pandoc to transform md to asciidoc but images were converted to inline format, with kramdoc all is Ok !!
