### ISSUE TITLE
Change bars to track modifications

### ISSUE THREAD

**Issue by reliable-sylvain** [asciidoctor/asciidoctor-pdf#1597]
I found several traces of this kind of request, and I understand that asciidoc is not intended to track changes in a document.
However, when using to produce technical content that will be reviewed, it is absolutely necessary to have a way to identify which par of the content have been modified.

To do so, I plan to use the diff function of GIT and inject a role in the document to identify the pieces that have been modified.
Now, what is needed is to have a way to create a change bar on the side associated to the role.
Here is the solution I found:

Stylesheet yml:
```
role:
  Changed:
    border:
      width: .25
      changebar: 1
      color: $base_font_color
      offset: 2
```
Note the changebar entry this is used as a key to key to create the bars.

transform.rb line18 :
```
       'border_changebar' => :border_changebar,
```
text_background_and_border_renderer.rb line 38:
```
if (border_width = data[:border_changebar])
        border_width = 1
        border_color = data[:border_color]
        prev_stroke_color = pdf.stroke_color
        prev_line_width = pdf.line_width
        pdf.stroke_color border_color
        pdf.line_width border_width
        pdf.stroke_vertical_line fragment.top + border_offset, fragment.top-height, :at => 50 - pdf.bounds.absolute_left 
        pdf.stroke_color prev_stroke_color
        pdf.line_width prev_line_width
      elsif (border_width = data[:border_width])

```
asciidoc code:
```
== [.Changed]#SELECT clause#

Text without the change bar

[.Changed]#Text with the change bar#
```

Here is a sample of the result:
![image](https://user-images.githubusercontent.com/53840819/76189809-ce29f180-6198-11ea-93c5-5c1b51f06c5e.png)

**Comment by 1marc1** [comment]
I really like this idea and would also be keen to see how you would inject the role.

**Comment by elisa-riscv** [comment]
Being able to render change bars on a paragraph level, would be very useful. It looks like it's possible to get information about changed lines from a PR in git by querying the url of the PR. With that information it does seem possible that something could be scripted to inject the information for the pdf--I am not, however, a software programmer. Is anyone interested in pursuing this further?

**Comment by holgerbrandl** [comment]
Such a rendering mode would be indeed awesome.

**Comment by mojavelinux** [comment]
There is an example in the docs that shows how to number paragraphs. https://docs.asciidoctor.org/pdf-converter/latest/extend/use-cases/#paragraph-numbering This could be extended to look for some sort of role or other metadata and add a vertical line next to the text. I have added such an example to the docs.

**Comment by specialpointcentral** [comment]
I have some questions about that.

If I use code in "https://docs.asciidoctor.org/pdf-converter/latest/extend/use-cases/#paragraph-numbering", I only set the change bar at paragraphs. Some areas, like code areas, cannot be set.
What can I do about that?

Thx.

**Comment by mojavelinux** [comment]
Please direct questions about the example code to the project chat at https://chat.asciidoctor.org. Thanks!
