### ISSUE TITLE
Request for new characters in fallback font

### ISSUE THREAD

**Issue by christianpeel** [asciidoctor/asciidoctor-pdf#1600]
Issue #1129 suggests that we make a new issue if we find Unicode or Emoji characters that we'd like support for.  I've found a few unicode characters that I'd like support for: 
* "₁": A subscript 1
* "₂": A subscript 2
* "ℯ": Used to represent the Euler number

For background, `asciidoctor` works fine to generate HTML for the [characters](https://introajulia.org/#_entrada_de_unicode) we're trying to generate, but `asciidoctor-pdf` doesn't give us all the characters we want, even with [Noto Emoji](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/fonts/notoemoji-subset.ttf) as fallback.

Also, let's say I don't care about the file size; is there some massive font file that has color emoji and every possible character I'd ever want?

**Comment by mojavelinux** [comment]
We can only add characters which exist in the font we are using as the fallback font, which is M+ 1p. The subscript numbers exist, so we could add those, but the Euler number does not (which seems strange).

> For background, asciidoctor works fine to generate HTML for the characters we're trying to generate

This is normal. The browser uses all the system fonts available, and thus can almost always find a glyph for the character.

> is there some massive font file that has color emoji and every possible character I'd ever want

ttfunk doesn't support color emoji. However, there are fonts that cover almost every character in the unicode range. One example is VLGothic, which comes with Linux.

**Comment by christianpeel** [comment]
Thanks for looking at this.  FYI, there's a bit more info on the "ℯ" character at [unicode-table.com](https://unicode-table.com/en/212F/).   Also, it appears that the [Nova Mono](https://fonts.google.com/specimen/Nova+Mono?preview.text=%E2%84%AF&preview.text_type=custom) font has the "ℯ" character.

**Comment by mojavelinux** [comment]
You could certainly use that in your theme.

I do see the slot for the character in the M+ 1p font. It's just empty. And that's the fallback font we're sticking with because changing it would be extremely difficult right now. But that's also why we've made it very easy to add fonts using the theming system.

**Comment by christianpeel** [comment]
I was able to download and use the GNU fonts.  I followed your suggestions in other issues and was able to make a custom theme which used fallback fonts.  Of course now I have other problems :-) but at least this problem appears to be solved.

Thanks!
