### ISSUE TITLE
Large table overflows subsequent sections

### ISSUE THREAD

**Issue by behrangsa** [asciidoctor/asciidoctor-pdf#1623]
Here's a sample broken rendering:

![Screenshot from 2020-03-27 14-05-14](https://user-images.githubusercontent.com/18451/77717369-60087a00-7034-11ea-9a5f-9b9fc6123633.png)

Example input and output are [attached](https://github.com/asciidoctor/asciidoctor-pdf/files/4391261/test.zip).

To reproduce:

```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$ asciidoctor-pdf test.adoc
```

**Comment by mojavelinux** [comment]
This case is documented in the README as a known limitation:

> Table cells that exceed height of a single page will be truncated (see prawn-table#41).

The handling of the table cell is out of our hands. The PDF generator does not support a single table cell that overflows a page, and apparently the solution is exceedingly complicated.

This is a duplicate (though a variation) of #1199. I'll closing this one to consolidate the discussion.

**Comment by mojavelinux** [comment]
Actually, I want to open this one back up because the cell should be truncated. It should not be allowed to overrun the page like it's doing currently.

**Comment by mojavelinux** [comment]
And the fact that it's crashing into the running footer is also an issue.

**Comment by mojavelinux** [comment]
I think we should warn when this happens so that at least the user is aware of the truncation.
