### ISSUE TITLE
Default font (Noto Serif) difference with regular Noto Serif

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1625]
Hi,

Does Noto Serif used by asciidoctor-pdf exclude characters? I am interested in `№` which is widely used in Russian documents (means Number).

Currently in PDFs I get empty square instead of №, while Noto Serif, for example in google fonts has it:
https://fonts.google.com/specimen/Noto+Serif?preview.text=Char+%E2%84%96+is+available&preview.text_type=custom

![image](https://user-images.githubusercontent.com/234774/77752914-85e44d80-7039-11ea-84b4-25747387f62a.png)

PDF:
![image](https://user-images.githubusercontent.com/234774/77753008-b88e4600-7039-11ea-9af7-db25f0402776.png)

If there are chars specifically excluded I can use non-bundled Noto Serif for my documents (using theming) but is there any specific additional chars you include into default font?

**Comment by habamax** [comment]
I have found https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/fonts/ABOUT-notoserif-subset

So, how can a mere human do the same for the non-default font + add 1 additional char? :)

**Comment by habamax** [comment]
Hm, I can take font from the repo and add a single char with fontforge I guess...

**Comment by habamax** [comment]
I have added № to bundled font (although font sizes are twice less after ttf creation, hopefully it is ok)

Is there a way I can help you adding this char to default Noto Serif or you prefer not to have it there?

**Comment by habamax** [comment]
https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#preparing-a-custom-font

Feel a bit ashamed :)

**Comment by mojavelinux** [comment]
We can add individual characters to the subset upon request. This seems like a reasonable addition, so I'll add it (for 2.0).

Btw, you can find a list of characters in the subsets in these files:

* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/fonts/ABOUT-notoserif-subset
* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/fonts/ABOUT-mplus1mn-subset
* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/fonts/ABOUT-mplus1p-subset

**Comment by habamax** [comment]
Thank you!
