### ISSUE TITLE
Warn if table cell overflows bounds of page

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1626]
The table layout engine (provided by prawn-table) truncates the contents of table cell if it overflows the boundaries of a single page. When this happens, Asciidoctor PDF should issue a warning to alert the user of the situation so the user knows to address it.

**Comment by habamax** [comment]
Having quite a lot of warnings from embedded svgs (from plantuml) which are always ignored could lead to ignoring this important one.

And making it an error is not an option, right?

**Comment by mojavelinux** [comment]
> Having quite a lot of warnings from embedded svgs (from plantuml) which are always ignored 

Let's deal with that separately (for example, we could filter superfluous warnings).

> And making it an error is not an option

This might be a case where we want to log at the ERROR level since it's dropping content. Seems reasonable to me.

**Comment by habamax** [comment]
> This might be a case where we want to log at the ERROR level since it's dropping content. Seems reasonable to me.

Sounds good to me

**Comment by habamax** [comment]
> > Having quite a lot of warnings from embedded svgs (from plantuml) which are always ignored
> 
> Let's deal with that separately (for example, we could filter superfluous warnings).

I am not sure how superfluous those warnings, but they are for plantuml svgs.
I can create a separate issue to decide what to do with them.

**Comment by mojavelinux** [comment]
> I can create a separate issue to decide what to do with them.

Thanks.
