### ISSUE TITLE
Relative links broken

### ISSUE THREAD

**Issue by ggenzone** [asciidoctor/asciidoctor-pdf#1630]
We are trying to generate a bunch of PDFs files and usually we have relative links to the result of another AsciiDoc file in HTML.

Something like this

`link:another_page.html[Another Page]`

this works properly in the web but when we process this file with asciidoctor-pdf and download the file to your local machine, the link will be broken and make sense that (because it will use the local current path)

Is there any workaround to resolve relative links with a prefix URL something similiar to :imagesdir but remotely ?

Would be great if it is possible to resolve relative links like this 
`https://example.com/<relative-link> `

**Comment by mojavelinux** [comment]
I would recommend using an attribute reference that resolves to base URL. In the HTML backend, you can set the value to blank.

```
link:{link-base-url}another_page.html[Another Page]
```

You can define it at the top of your document as follows:

```
:link-base-url:
ifdef::backend-pdf[:link-base-url: https://example.com/]
```

**Comment by ggenzone** [comment]
Thank you for the anwser!

   In this case is not an option there are more than 500 files, and also I can't modify the content.

But I will try to make a few regexp to match relative links and fix it before execute asciidoctor-pdf convert.

Thank you!

**Comment by mojavelinux** [comment]
If you use source-to-source xrefs, then you can take advantage of the built-in `relfileprefix` attribute.

```
:relfileprefix: https://example.org/

xref:another_page.adoc[Another Page]
```

Which gives you:

```
<a href="https://example.org/another_page.html">Another Page</a>
```

Unlike the xref macro, the link macro isn't aware of whether it's linking a relative, root-relative, or absolute URL. It just passes the target through.
