### ISSUE TITLE
Feature Request: Flag that allows footnotes to be placed at bottom of page instead of end of the chapter

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-pdf#1636]
Hello,

This is a feature request to support a flag that would allow footnotes to be placed at bottom of page instead of end of the chapter.

Sid

**Comment by mojavelinux** [comment]
As I've explained numerous times, and stated in the README, this converter cannot support placing footnotes at the bottom of the page. The reason is that the PDF generation library that we use (Prawn) doesn't support content reflows.
