### ISSUE TITLE
Feature Request: Allow author to dictate Section Number

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-pdf#1637]
refer: https://discuss.asciidoctor.org/How-to-declare-custom-prefix-to-the-sections-in-asciidoc-td7826.html

I am writing a book in asciidoc. I want to declare a custom prefix that I would like to be used for the sections in my appendices or chapters. E.g., if my prefix is P, I want sections to be numbered as:

Appendix P
  P.1 Subsection 1

**Comment by mojavelinux** [comment]
This is already supported. You need to enable `sectnums`.

```
= Document Title
:sectnums:
:appendix-caption!:

[appendix]
== Title of Appendix

=== Appendix Subsection
```

If you need further customization, you'll have to do so using an extension (or otherwise manipulate the document model programmatically).

**Comment by mojavelinux** [comment]
See https://docs.asciidoctor.org/asciidoc/latest/sections/appendix/
