### ISSUE TITLE
Feature Request: Support outputting each chapter into its own PDF

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-pdf#1638]
I am using asciidoctorpdf to write a book. I write each chapter in its own .adoc and then have a master .adoc in which I include all the chapters. I run the converter on my master .adoc and it works fine but I'd like to have a flag using which I can tell the converter to place each chapter into its own PDF as that is what my publisher is asking for.

**Comment by mojavelinux** [comment]
This is not something I'm interested in supporting in this converter. However, you are free to reuse the code from this converter to implement a multi-document PDF converter. I recommend either splitting the document up at the source level or loading the document as a whole and splitting up the document model into separate objects. You can get some ideas from this extension: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/multipage-html5-converter.rb

**Comment by mojavelinux** [comment]
If you want each chapter in it's own PDF file, you will need to convert each chapter individually. You can set the chapter number using the `chapter-number` attribute. Here's how you can convert just chapter 2.

```
asciidoctor-pdf -a doctype=book -a chapter-number=1@ -a sectnums ch02.adoc
```
