### ISSUE TITLE
Reset footnote numbering for each chapter of a book

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-pdf#1639]
Per this thread:
https://discuss.asciidoctor.org/How-to-reset-footnotes-counter-in-asciidoc-td7702.html

When writing a book, one would like to reset the footnote counter at beginning of each chapter. This can be accomplished using

```
:!footnote-number:
```

at any time start counting with 1 again.

Expected
=======

Footnote counter should reset

Observed
=======

Footnote counter is reset but there is an unpleasant side-effect that asciidoc now thinks there are multiple footnotes with same identifier and links are broken

**Comment by siddjain** [comment]
Thank you.

________________________________

**Comment by mojavelinux** [comment]
The one thing we'll have to consider is what happens if a footnote reference refers to a footnote defined in a previous chapter. I think the solution would be to append the xreftext for the chapter in which the footnote is located to the footnote label. (e.g., `[1 - Chapter 1]`).

**Comment by siddjain** [comment]
Thanks for bringing that up - I hadn't thought about it.

Could you please provide some flags to the user using which the user can customize the display text and reftext of the footnotes? E.g., someone might want footnotes to be prefixed with chapter name in that case so they become
{chapter}.{footnote} like 3.1, 3.2, 3.3 and so on.

Providing rich configurable flags - with documentation of course - using which users can customize the experience they want is key to success of any platform.

________________________________

**Comment by mojavelinux** [comment]
I should add that the xreftext in the footnote follows the `xrefstyle` setting.

At this point, I'm not prepared to offer more customization than what `xrefstyle` offers. This situation should be rare anyway since it is not conventional for a footnote in a book to exceed the boundaries of a chapter.
