### ISSUE TITLE
No blank page for media: prepress 

### ISSUE THREAD

**Issue by pponec** [asciidoctor/asciidoctor-pdf#1641]
Hello, 

I need a PDF document with different **inner and outer margins** of the page (:doctype: book, :media: prepress)  with **no blank page** also.
However I have  the one blank page before the Table of Content always.
How can I disable all blank pages in result PDF?

My environment:

```text
$ asciidoctor-pdf --version
Asciidoctor PDF 1.5.0 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]) 
(lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

Thank you for a help.

**Comment by mojavelinux** [comment]
These two features are linked to the prepress media mode. You either get both of them by setting media to prepress or neither of them by setting media to print (or screen). That can't be changed.

**Comment by pponec** [comment]
This is a pity, because in that case there is no possible to deploy a PDF with the blank page a Amazon's paperback.

**Comment by mojavelinux** [comment]
If you have a proposal for how this can be expressed / configured, please come forward with it. But you need to propose something.

**Comment by pponec** [comment]
Unfortunately, I found no solution.

**Comment by mojavelinux** [comment]
Take some time to think about it and feel free to work through ideas here.

**Comment by pponec** [comment]
According to the documentation, the attribute `showtitle!` (located in the document header or via the CLI or API)  should suppress the printing of the first page, unfortunately it seems does not work.

> You can control whether or not the document title appears in the converted document using the showtitle attribute.

I am sorry, but I still don't see a usable solution.

**Comment by mojavelinux** [comment]
> According to the documentation, the attribute showtitle! (located in the document header or via the CLI or API) should suppress the printing of the first page, unfortunately it seems to have no effect.

Please use `notitle` instead. There seems to be a problem with its negated form, `showtitle!`.

**Comment by mojavelinux** [comment]
> I am sorry, but I still don't see a usable solution.

Then I'm confused why you opened the issue. An open source project relies on collaboration with the requester. That means to get the behavior you want, you need to be willing to participate in the design of that feature. What I'm asking is for you to propose how you would like to configure the feature and I can give you feedback on that design.

**Comment by pponec** [comment]
Ok, my suggestion is: if the document is compiled according to the pattern:

```bash
asciidoctor-pdf -o book.pdf -a showtitle! book.adoc
```

The first page including the followed white page will be **removed** from the resulting PDF. The version `Asciidoctor PDF 1.5.0 using Asciidoctor 2.0.10`  generates a title page followed by a white page.

Sample of document:

```asciidoc
= AsciiDoc Article Title
Firstname Lastname <author@asciidoctor.org>
1.0, July 29, 2014, Asciidoctor 1.5 article template
:toc:
:icons: font
:doctype: book
:media: prepress
:showtitle!:

Content entered directly below the header but before the first section heading is called the preamble.

== First level heading

This is a paragraph with a *bold* word and an _italicized_ word.

This is another paragraph.

== Next level heading

.Unordered list title
* list item 1
* list item 2

This is a paragraph.
```

In this case the PDF document will be started with heading: **Table of Contents**.

**Comment by mojavelinux** [comment]
Have you tried the same command with the notitle attribute instead?

**Comment by pponec** [comment]
Parameter `notitle` works as expected, thank you very much for the help.

I propose to correct the documentation: https://asciidoctor-docs.netlify.com/asciidoc/1.5/header/title/

**Comment by mojavelinux** [comment]
I'm glad to hear that's working for you! I apologize for misunderstanding your original question. You have identified an inconsistency in the behavior and/or documentation. And we're also missing tests for this case in Asciidoctor PDF. In brief, the `showtitle` attribute is not currently not reliable. The `notitle` attribute is the preferred approach.

**Comment by mojavelinux** [comment]
For the record, this is documented here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#title-page
