### ISSUE TITLE
How to remove "example" wording from %collapsible?

### ISSUE THREAD

**Issue by petko** [asciidoctor/asciidoctor-pdf#1660]
I have the following in my .adoc file:

```
.Title
[%collapsible]
====
. Step 1
. Step 2
====
```

This produces a collapsed `Title` in HTML, which when clicked, is expanded, so that step 1 and step 2 are now visible.

The same code in asciidoctor-pdf produces:

```
Example 1. Title
1. Step 1
2. Step 2
```

How can I remove the `example` wording and the number from the produced PDF?

**Comment by mojavelinux** [comment]
Aha. Asciidoctor PDF is not supposed to be adding the caption prefix in this case. I'll update the code.

In the meantime, you can use this as a workaround.

```
.Title
[%collapsible,caption=]
====
. Step 1
. Step 2
====
```

**Comment by petko** [comment]
Thank you very much!
