### ISSUE TITLE
Change section size 

### ISSUE THREAD

**Issue by Staubgeborener** [asciidoctor/asciidoctor-pdf#1671]
The size of my section is way too big. I am forced to press a lot of text into a heading (which cannot be avoided) and the current settings ensure that a section easily takes up half a page.

Example:

```
= Title
:toc:
:numbered:
:toc-placement!:

:toc::[]

== this could be a pretty big section for example, which I just have to use, can actually not be avoided and is therefore not a solution, I have to get it as small as section level 4 or level 5 without ruining my table of contents
```

I convert my .adoc-files with `asciidoctor-pdf` in terminal:
`asciidoctor-pdf myfile.adoc`

Already tried even more equals like `===== section`, sure, my section is now way smaller and perfect, but my toc is destroid.

**Comment by mojavelinux** [comment]
Please study the theming guide. That's how you can customize the appearance of the text in the PDF. See https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc#keys-heading

**Comment by mojavelinux** [comment]
Here's how you can adjust the section title size using a custom theme named my-theme.yml:

```
extends: default
heading:
  h2-font-size: $base-font-size * 1.25
```

Then run using:

```
asciidoctor-pdf -a pdf-theme=./my-theme.yml doc.adoc
```
