### ISSUE TITLE
URLs with an #id are not rendered correctly.

### ISSUE THREAD

**Issue by kristvanbesien** [asciidoctor/asciidoctor-pdf#1677]
When I have link in my source doc like this:

`https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/storage/configuring-persistent-storage#persistent-storage-using-vsphere[]`

the resulting link in the pdf does not work. The text shown is correct, but in the hyperlink the '#' gets replaced with '%23'

So I end up with:

`https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/storage/configuring-persistent-storage%23persistent-storage-using-vsphere`

Bug? Regressions? Or am I doing it wrong?

**Comment by kristvanbesien** [comment]
I tried using link:<url> and link:++<url>++, but with no avail...

**Comment by mojavelinux** [comment]
Can you share which version of Asciidoctor PDF you're using?

**Comment by kristvanbesien** [comment]
```
gem info asciidoctor-pdf

*** LOCAL GEMS ***

asciidoctor-pdf (1.5.3)
    Authors: Dan Allen, Sarah White
    Homepage: https://asciidoctor.org/docs/asciidoctor-pdf
    License: MIT
    Installed at: /Users/krist/.gem/ruby/2.6.0

    Converts AsciiDoc documents to PDF using Asciidoctor and Prawn

gem info prawn

*** LOCAL GEMS ***

prawn (2.2.2)
    Authors: Gregory Brown, Brad Ediger, Daniel Nelson, Jonathan
    Greenberg, James Healy
    Homepage: http://prawnpdf.org
    Licenses: PRAWN, GPL-2.0, GPL-3.0
    Installed at: /Users/krist/.gem/ruby/2.6.0

    A fast and nimble PDF generator for Ruby
```

**Comment by mojavelinux** [comment]
Are you using extensions? My hunch is that something else is modifying the source. The converter itself does not encode the hash. There's a test to verify this: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/spec/link_spec.rb#L52-L61

**Comment by kristvanbesien** [comment]
I did a simple test as wollows:

test.adoc:
```
= Asciidoctor PDF link test

https://asciidoctor.org/docs/user-manual/#what-is-asciidoctor

https://asciidoctor.org/docs/user-manual/#installing-the-asciidoctor-ruby-gem
```

Then just converted it with asciidoctor-pdf (without any custom stylesheets). 

The links in the resulting PDF do not work as expected...

**Comment by mojavelinux** [comment]
There's something wrong with your setup because this is not how Asciidoctor PDF works.

How did you install Asciidoctor PDF?

What PDF reader are you using to view the PDF?

**Comment by kristvanbesien** [comment]
I installed asciidoctor and asciidoctor-pdf using gems. And I updated just before doing my test.
This is all on a mac, and I use preview as pdf viewer. 

But testing in acrobat I notice that the link is correct. So this is a mac osx preview issue?

**Comment by mojavelinux** [comment]
> So this is a mac osx preview issue?

Sounds plausible.

To test, you could create a PDF that includes that link using different software (like MS Word or OpenOffice Writer) and test it with that reader. See if it has the same problem.

**Comment by kristvanbesien** [comment]
Just did that.

Created a document with a link with a #in word, and exported as a pdf. And then opened in preview. The link worked.

**Comment by mojavelinux** [comment]
There must be something different about how Prawn creates link annotations which this particular PDF reader doesn't like. That would be an issue that needs to be solved in Prawn itself.

To confirm, try creating a PDF using this code and see if it breaks the preview:

```rb
require 'prawn'

Prawn::Document.generate 'test.pdf' do
  text '<a href="https://asciidoctor.org/docs/user-manual/#what-is-asciidoctor">What is Asciidoctor?</a>', inline_format: true, color: '0000CC'
end
```

**Comment by mojavelinux** [comment]
Here's the raw object in the PDF source:

```
7 0 obj
<< /Border [0 0 0]
/A << /Type /Action
/S /URI
/URI (https://asciidoctor.org/docs/user-manual/#what-is-asciidoctor)
>>
/Subtype /Link
/Rect [36 744.9 144.696 756.0]
/Type /Annot
>>
endobj
```

As you can see, there is no %23.

**Comment by mojavelinux** [comment]
I don't see any difference no matter what PDF generator I use. It always embeds the link annotation the same way. If you see something we can change, I'll consider it. But I don't see what action, if any, we can take.

If you attach the PDF that works for you I'll look to see if it does something differently.

**Comment by mojavelinux** [comment]
I cannot reproduce with evince, the Firefox PDF viewer, or the Chrome PDF viewer. If you can provide a document generated by PDF that uses %23 instead of #, then please attach and reopen. Otherwise, I'm going to assume the bug is in the PDF viewer.

**Comment by DanielSWolf** [comment]
This is a bug in the Preview tool on macOS Catalina. See [this Apple Communities discussion](https://discussions.apple.com/thread/251041261) and [this question on AskDifferent](https://apple.stackexchange.com/questions/377869/apple-preview-encoding).

I can confirm that links with hashes in PDF files created by Asciidoctor-PDF work correctly in other PDF viewers. Conversely, links with hashes in PDF files created with other tools have the same problem when clicked in the Preview tool on Catalina.

**Comment by mojavelinux** [comment]
Thank you for doing this research and sharing it!

**Comment by Rasbats** [comment]
Asciidoctor did not like this:
[https://www.vaarweginformatie.nl/frp/main/#/page/infra_enc](https://www.vaarweginformatie.nl/frp/main/#/page/infra_enc)
Replaced the # with %23 and this worked.

**Comment by Rasbats** [comment]
Wrong - still having problems.

**Comment by mojavelinux** [comment]
I'm confident that the URL you posted works. It's possible, though, that if you have more than one in a line that the `#` may have to be escaped so it doesn't get interpreted as a formatting mark.

In the future, please direct usage questions and follow-ups to the project chat at https://chat.asciidoctor.org rather than posting on closed issues. Thanks!
