### ISSUE TITLE
Add "flattening" step to PDF production

### ISSUE THREAD

**Issue by gregturn** [asciidoctor/asciidoctor-pdf#1684]
I don't really know anything about PDF generating engines, but is it possible to ask the engine to "flatten" the final PDF? Or at least make that a configurable option?

I found a thread that sounded like a similar issue, and added my own bit to it for community contribution => https://discuss.asciidoctor.org/asciidoctor-pdf-style-for-KDP-print-book-td7789.html#a7978

Having the tools offer this would be nice.

**Comment by gregturn** [comment]
Turns out, "Print to PDF" is another step for PDF flattening. If there is no tweak to be made to the tools, at least update the documentation to mention this?

**Comment by mojavelinux** [comment]
Asciidoctor PDF provides a built-in optimizer. 

```
asciidoctor-pdf -a optimize doc.adoc
```

That runs it the generated PDF through ghostscript. The README also describes how to use hexapdf as an alternate way to optimize the PDF.

https://github.com/asciidoctor/asciidoctor-pdf#optimizing-the-generated-pdf

Those are the only two ways I know how we can flatten the PDF. If you know of another way, please bring those suggestions forward. Thanks!

**Comment by gregturn** [comment]
Ahh. I didn’t grok that. 

Maybe, then, we could simply update the documentation? There is no mention of “flattening” or “transparencies”, the wording KDP used when I chatted with them. 

I can draft some extra prose citing KDP and how to you probably need to do this if you’re hoping to publish with them (or possibly any publisher).

**Comment by mojavelinux** [comment]
To be honest, I've never heard of this terminology they're using. But it
you have a reference for it, and other people will come looking with that
terminology in mind, by all means we can add those references to that
section. Feel free to propose a change.

**Comment by bguiz** [comment]
Sorry to "revive" this rather old Github issue here 🙈 ... but not sure where else to ask this - can AsciiDoc now export to PDF a file that is meet's Amazon's criteria?

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org as stated on the following page in the docs: https://docs.asciidoctor.org/about/get-help/#issue-tracker
