### ISSUE TITLE
Link with inline styles is broken up into multiple links

### ISSUE THREAD

**Issue by mrotteveel** [asciidoctor/asciidoctor-pdf#1688]
When a link text has inline styles (eg emphasis), then the rendered link is broken up in multiple links (on the normal text before the line style, the text in the inline style, and on the normal text after the inline style).

This looks a bit off when clicking a link (in Adobe Acrobat), or hovering over a link in Firefox.

As a simple example, take

```
= Example with link
:doctype: book

[[normal-title]]
== Section with normal title

Some section content

[[with-emphasis]]
== Section with _emphasis_

Some section content

[[with-emphasis-middle]]
== Section with _emphasis_ in middle

Some section content

== links

* <<normal-title>>
* <<with-emphasis>>
* <<with-emphasis-middle>>
```

In Firefox, hovering over the link looks like:

Normal:
![normal-link](https://user-images.githubusercontent.com/5352689/81505105-50e04180-92ed-11ea-985f-b12da8092db6.png)

Emphasis at end:
![emphasis-1-before](https://user-images.githubusercontent.com/5352689/81505117-6190b780-92ed-11ea-8209-310353eff157.png)
![emphasis-1-on](https://user-images.githubusercontent.com/5352689/81505120-648ba800-92ed-11ea-8f24-c485eff2841d.png)

Emphasis in middle:
![emphasis-2-before](https://user-images.githubusercontent.com/5352689/81505128-6d7c7980-92ed-11ea-81f8-a60364f69797.png)
![emphasis-2-on](https://user-images.githubusercontent.com/5352689/81505133-6fded380-92ed-11ea-93fe-f770127d03d0.png)
![emphasis-2-after](https://user-images.githubusercontent.com/5352689/81505138-72d9c400-92ed-11ea-85d0-ecf933dfde0e.png)

**Comment by mojavelinux** [comment]
I'm going to assume you're referring to the PDF viewer in Firefox.

How link annotations get defined is not something that this converter has any control over. That's how Prawn works. Prawn is the PDF generator this converter uses. So you'll need to file an issue in https://github.com/prawnpdf/prawn to collapse adjacent link annotation boxes.

The way text in Prawn works is that each segment of text that has different formatting gets its own fragment, which is then placed onto the page. Here's where the link annotations get defined: https://github.com/prawnpdf/prawn/blob/master/lib/prawn/text/formatted/box.rb

I tried to see if a PDF optimizer would perform this collapsing, but it doesn't seem to be able to.

**Comment by mrotteveel** [comment]
I reported https://github.com/prawnpdf/prawn/issues/1157, but as I have no knowledge of Prawn or the internals of asciidoctor-pdf, I'm not sure if I phrased it correctly.

**Comment by mojavelinux** [comment]
@mrotteveel It seems like the developers understood your phrasing very well and explained why it's such a difficult behavior to implement.

**Comment by mojavelinux** [comment]
This is another example of a feature that we can address with Asciidoctor PDF's browser-based successor. The browser properly tracks the bounding box of a link (even across lines) and thus, when the PDF is generated, the hovering behavior will be as you expect.

**Comment by mojavelinux** [comment]
After spending a lot of time in the Prawn text-handling code, my assessment is that it has painted itself into a corner for what it can do with text. It kind of works the way it works and trying to change any part causes all sorts of other behavior to break. Alexander kind of alludes to this in his first reply.

**Comment by mrotteveel** [comment]
@mojavelinux Thanks. What is the browser-based successor you're talking about?

**Comment by mojavelinux** [comment]
I'll post about it once Asciidoctor PDF 2 is out. You can find an early prototype of it here: https://github.com/mogztter/asciidoctor-pdf.js
