### ISSUE TITLE
Generated PDFs are not rendered in Gitlab

### ISSUE THREAD

**Issue by xrayn** [asciidoctor/asciidoctor-pdf#1689]
When I generate a pdf from a .adoc file e.g. `asciidoctor-pdf test.adoc` and upload it to Gitlab, it is not rendered and Gitlab only offers to Download the file. However, nearly every other PDF I upload on Gitlab is rendered automatically when it is opened. Perhaps this is just a Gitlab issue, I don't know. 

So I am wondering if someone else has the same problems and whether this is related to asciidoctor-pdf or gitlab.

Here are the outputs from pdfinfo (these are two different files though):

Generated by asciidoctor-pdf (is not rendered in gitlab)
```
Title:          Test1
Creator:        Asciidoctor PDF 1.5.3, based on Prawn 2.2.2
Producer:       Asciidoctor PDF 1.5.3, based on Prawn 2.2.2
CreationDate:   Mon May 11 21:15:08 2020 CEST
ModDate:        Mon May 11 20:52:15 2020 CEST
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      595.28 x 841.89 pts (A4)
Page rot:       0
File size:      56389 bytes
Optimized:      no
PDF version:    1.4
```

Generated by google-chrome print to file -> pdf (is rendered in gitlab)
```
Title:          Test2
Creator:        Chromium
Producer:       Skia/PDF m81
CreationDate:   Tue May  5 19:57:46 2020 CEST
ModDate:        Tue May  5 19:57:46 2020 CEST
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          26
Encrypted:      no
Page size:      1155.12 x 743.04 pts
Page rot:       0
File size:      477782 bytes
Optimized:      no
PDF version:    1.4
```

**Comment by mojavelinux** [comment]
Can you try to generate with the `-a optimize` flag and report whether that renders?

This really sounds like an issue you need to take up with GitLab. This converter cannot control how GitLab works, and as far as I can tell, Asciidoctor PDF generates valid PDF files.

**Comment by xrayn** [comment]
@mojavelinux using -a optimize did the trick. It is now rendered. All I had to do is install gem `rghost` to make it work. What does `-a optimize` do and is it possible to include this somehow in the standard pdf engine?

**Comment by xrayn** [comment]
ok, so I played around with just `exiftool` changing some metadata and also played around with the option `:pdf-page-mode: fullscreen`. Did not change anything so far. Th unoptimized pdf is not rendered.

test1.pdf not rendered, test2.pdf rendered (-a optimized used)
```
Create Date                     : 2020:05:11 22:40:30+02:00   | Create Date                     : 2020:05:11 21:57:01+02:00
Creator                         : Asciidoctor PDF 1.5.3, base   Creator                         : Asciidoctor PDF 1.5.3, base
Directory                       : .                           | Creator Tool                    : Asciidoctor PDF 1.5.3, base
Document ID                     : uuid:23d2a3ae-cbde-11f5-000 | Directory                       : ../../
                                                              > Document ID                     : uuid:20d2a3ae-cbde-11f5-000
ExifTool Version Number         : 11.85                         ExifTool Version Number         : 11.85
File Access Date/Time           : 2020:05:11 22:46:11+02:00   | File Access Date/Time           : 2020:05:11 21:58:31+02:00
File Inode Change Date/Time     : 2020:05:11 22:46:09+02:00   | File Inode Change Date/Time     : 2020:05:11 21:58:13+02:00
File Modification Date/Time     : 2020:05:11 22:46:09+02:00   | File Modification Date/Time     : 2020:05:11 21:58:13+02:00
File Name                       : test1.pdf                     File Name                       : test2.pdf
File Permissions                : rw-r--r--                     File Permissions                : rw-r--r--
File Size                       : 59 kB                       | File Size                       : 50 kB
File Type Extension             : pdf                           File Type Extension             : pdf
File Type                       : PDF                           File Type                       : PDF
Format                          : application/pdf               Format                          : application/pdf
Linearized                      : No                            Linearized                      : No
MIME Type                       : application/pdf               MIME Type                       : application/pdf
Modify Date                     : 2020:05:11 22:40:25+02:00   | Modify Date                     : 2020:05:11 21:57:01+02:00
Page Count                      : 1                             Page Count                      : 1
Page Mode                       : FullScreen                  <
PDF Version                     : 1.4                           PDF Version                     : 1.4
Producer                        : GPL Ghostscript 9.52          Producer                        : GPL Ghostscript 9.52
Title                           : Vigenere cipher             | Title                           : Caesar cipher
XMP Toolkit                     : Image::ExifTool 11.85       | XMP Toolkit                     : XMP toolkit 2.9.1-13, frame

```

**Comment by mojavelinux** [comment]
> What does -a optimize do and is it possible to include this somehow in the standard pdf engine?

It's described here: https://github.com/asciidoctor/asciidoctor-pdf#optimizing-the-generated-pdf

Could you also try with hexapdf? If the hexapdf optimize fixes it, then the PDF renderer that GitLab uses is likely getting tripped up by some of the dangling objects that Prawn leaves behind.

**Comment by mojavelinux** [comment]
> changing some metadata 

It's not the metadata. It's like the object hierarchy. As I explain in that docs section, Prawn can leave some unreferenced objects behind, which could be the culprit.

> is it possible to include this somehow in the standard pdf engine?

No, because it requires an external tool. That's why we have the `-a optimize` flag. (It would be great if Prawn cleaned up after itself, but the reality is it doesn't and needs this extra tool in some scenarios).

**Comment by xrayn** [comment]
> > What does -a optimize do and is it possible to include this somehow in the standard pdf engine?
> 
> It's described here: https://github.com/asciidoctor/asciidoctor-pdf#optimizing-the-generated-pdf
> 
> Could you also try with hexapdf? If the hexapdf optimize fixes it, then the PDF renderer that GitLab uses is likely getting tripped up by some of the dangling objects that Prawn leaves behind.

@mojavelinux The fix with hexapdf also works. Thanks for your help!

I mean, for me it is no trouble using either hexapdf or `-a optimize` aka `rghost`. The only problem I see is that adding more and more dependencies makes it harder for people to keep track of all this stuff. Perhaps it would be a good idea to put all these (optional) dependencies somewhere close to the top of the https://github.com/asciidoctor/asciidoctor-pdf/blob/master/README.adoc document and then add links to the detailed descriptions. I guess I am not the typical user of asciidoctor-pdf, but for instance I personally need at least asciidoctor-mathematical and a syntax highlighter like rouge for asciidoctor-pdf. In addition to that now `rghost` + `ghostscript` or `hexapdf`. Additionally, for the other toolsets, e.g. asciidoctror-revealjs, I need asciidoctor-diagram, which also depends on a bunch of depdencies itself. :)

I am not complaining, but sometimes I feels that I loose track of all the packages, gems and programs I need for my asciidoctor environment.

Anyway, keep up your great work. asciidoctor is just awesome!

**Comment by mojavelinux** [comment]
@xrayn Thanks for confirming that hexapdf also solves the issue. I'll add a note about it in the README.

> sometimes I feels that I loose track of all the packages, gems and programs I need for my asciidoctor environment.

Yes, Asciidoctor provides a lot of integrations. That's one of its key strengths.
