### ISSUE TITLE
PDF formatting bug, possibly?

### ISSUE THREAD

**Issue by zajo** [asciidoctor/asciidoctor-pdf#1690]
Please look at page 3 in https://zajo.github.io/leaf/leaf.pdf, notice how the number overlaps with the source block above it. This does not occur anywhere else in the document. I failed to figure out what is special about this particular source block to cause this. Any ideas?

**Comment by mojavelinux** [comment]
This is a known issue and something I'm working on. Right now the block height is not computed accurately and can cause the shading to extend down too far. See #789.
