### ISSUE TITLE
Ellipsis in PDF output

### ISSUE THREAD

**Issue by zajo** [asciidoctor/asciidoctor-pdf#1691]
Generating a PDF from the following adoc input:

```
`Hello... World`
```

Renders incorrectly:

<img width="149" alt="Screen Shot 2020-05-11 at 13 04 26" src="https://user-images.githubusercontent.com/609498/81606455-fd6f0180-9387-11ea-9aa4-e5b852953dd2.png">

The ellipsis is rendered correctly if the text is not formatted with \`\`:

<img width="148" alt="Screen Shot 2020-05-11 at 13 08 43" src="https://user-images.githubusercontent.com/609498/81606832-94d45480-9388-11ea-96b2-970dc025f37d.png">

Incidentally, it would be great if there was a way to tell Asciidoctor that I don't want any of the substitutions, like ellipses or `->`.

**Comment by mojavelinux** [comment]
That happens to be the style of the M+1mn font. In other words, it's intentional. If you don't like how it looks, you can use another font.

**Comment by mojavelinux** [comment]
> Incidentally, it would be great if there was a way to tell Asciidoctor that I don't want any of the substitutions, like ellipses or ->.

You can do this using the subs attribute:

```
[subs=-replacements]
Hello... World
```

**Comment by zajo** [comment]
Yes I realized this was the wrong repo when you moved my other bug but I don't think I could move it once filed. Sorry about that, and thank you for the excellent Asciidoctor and the quick response!

**Comment by mojavelinux** [comment]
No problem. Just directing traffic ;)
