### ISSUE TITLE
Custom converter with parameters.

### ISSUE THREAD

**Issue by ggenzone** [asciidoctor/asciidoctor-pdf#1692]
Hi I was wondering if it is possible to read 'global' attributes inside a custom converter like this

```
require 'asciidoctor-pdf' unless defined? ::Asciidoctor::Pdf

##
# Rewrite filenames with a valid ID 
#
module AsciidoctorPdfExtensions
    def convert_inline_anchor node
      case node.type
      when :xref
        # Check if the target belong to the custom-file-list attribute
            node.target = 'ID' + (Digest::MD5.hexdigest node.target)
        super
      else
        super
      end
    end
end

Asciidoctor::Pdf::Converter.prepend AsciidoctorPdfExtensions
```

I would like to be able to pass argument when I use it in the following way

```
Asciidoctor.convert(
     content,
     backend: 'pdf',
     attributes: { 'allow-uri-read' => '' , 'custom-file-list' => ... }
)

```

Is it possible to read attributes from there? 

I was looking in the following link but it didn't help me.

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#using-the-extended-converter

Thanks

**Comment by mojavelinux** [comment]
Yes, you can access the attributes via the document object.

```
node.document.attr? 'allow-uri-read'
node.document.attr 'custom-file-list'
node.document.attributes
```

In the future, please ask questions about usage on the discussion list https://discuss.asciidoctor.org or the chat channel https://gitter.im/asciidoctor/asciidoctor. The issue tracker is for tracking bugs and feature requests. Thanks!

**Comment by mojavelinux** [comment]
> is possible to read 'global' attributes

The correct term is document attributes.

**Comment by ggenzone** [comment]
Great! thank you very much !, I'm sorry I didn't know about the other channels now I'll use the list or channel.

Agains thanks

**Comment by mojavelinux** [comment]
Sure thing. Glad to help!
