### ISSUE TITLE
For media=prepress switch base font color to black

### ISSUE THREAD

**Issue by gregturn** [asciidoctor/asciidoctor-pdf#1699]
Asciidoctor PDF uses Gray 20 (#333333), a slightly lighter-than-black as it’s base-font-color due to my references when reading a PDF on a device. 

When you’re actually going to press, you need “real” black (#000000) to avoid a faded look. 

Adjusting media=prepress to that would reduce the odds of someone sending a prepress rendered PDF KDP Print (or any other POD service) and be surprised/disgusted with the results. 

Additionally this should be mentioned in the docs.

**Comment by mojavelinux** [comment]
There are three questions we need to address before we can implement this:

1. Should it be possible to override this behavior if you really do want to use a non-black font color?
2. Should we apply this anywhere a dark gray is used in the theme, or only to specific settings like the base font color?
3. Should this also be applied when media=print?

1 & 2 kind of tells me we should have a "print safe colors" setting in the theme (which would be enabled by default when media=prepress and perhaps media=print too, but can be disabled). The idea being that any color* within a certain range of black will become black, but lighter colors would be unaffected. This would still give the author control over the colors in the theme if the author so chooses.

\* perhaps just text colors to start

**Comment by gregturn** [comment]
1. I say yes, if possible.
2. I use text everywhere (naturally), but I also use quotes/verses at the top of every chapter to lead into the chapter. The citation is in #999999. I'm okay with that in my current project, but you may wish to darken that a little. 
3. I can't really comment on `media=print`. I remember trying it and recto/facing pages not rendering properly. I tried it recently, and stuff actually flipped. Maybe that is what's supposed to happen if you plan to print it yourself? TBH, a section detailing what the media formats are might be suitable for the ref docs.

Something to ponder is B&W vs. color. I was surprised that my for-print PDF had working hypermedia AND color text. Depends on how strong of a designer you are. Rendering red text into B&W is fine with me, but people like Joe Nuxoll from the Java Posse would probably want to hand-pick every shade of gray with a deliberate B&W palette. ¯\_(ツ)_/¯

**Comment by mojavelinux** [comment]
> I can't really comment on media=print

media=print is a more lightweight version of media=prepress, designed for straight printouts (using a printer), not books. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#print In other words, media=prepress builds on media=print.

**Comment by mojavelinux** [comment]
> I was surprised that my for-print PDF had working hypermedia AND color text.

That's another good point. The print modes came later, so we've enabled stuff selectively over time. We've just never dealt with links. Though we have had requests in the past for links to work when media=print. But they certainly shouldn't be there for media=prepress.

**Comment by mojavelinux** [comment]
This is a tougher problem than at first glance because there are a lot of different elements that get a color: text, background, borders, and horizontal rules. I'm wondering if the right solution is to apply a color correction (like https://stylus-lang.com/docs/bifs.html) globally (which could then be disabled). This would provide a quick solution if you want to use the default theme, but allow you to be like Joe when applying your own theme.

The only problem with a color correction is that background colors would also get darker. But from what I've seen from printed books, that's a good thing since they can come out too light to see. Perhaps we can make this change globally, then decide if we need a correction. Or perhaps a correction per element type.

**Comment by mojavelinux** [comment]
I've given this even more thought and I'm retracting my idea of applying a color correction. There are just way too many assumptions and it would be hard to get right. However, I came up with a better idea. It's easier than ever to create new themes. And, truth be told, we want to push people to creating themes for customization. But requiring the user to maintain the default theme optimized for print would be tedious. So we'll provide one. That way, you get something out of the box, but you have the power to tweak it further if you want.

I propose naming the theme default-for-print

That way, you'll be able to invoke Asciidoctor PDF as follows:

```
asciidoctor-pdf -a media=prepress -a pdf-theme=default-for-print
```

While we could tie the theme to the media if not specified, I think that's going to make things confusing and break existing pipelines. I don't think it's too inconvenient to specify it explicitly. Let me know if you disagree.
