### ISSUE TITLE
Multiple anchors doesn't work as described in manual

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1702]
* asciidoctor-pdf: current master
* asciidoctor: latest stable from gems 

There is a https://asciidoctor.org/docs/user-manual/#multiple-anchors

Having following `test.adoc`:

```
= test anhors
:toc:

== Section 1

== Section 2

== [[term]][[terms]] Section with 2 anchors

[[term2]][[terms2]]My term:: A term

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Maecenas feugiat fermentum pretium. Cras eu dolor imperdiet justo mattis
pulvinar. Cras nec lectus ligula. Proin elementum luctus elit, a tincidunt quam
facilisis non. Nunc quis mauris non turpis finibus luctus. Maecenas ante
sapien, sagittis quis accumsan in, feugiat quis sem. Praesent et auctor libero.

Ut sed lacus id mauris mattis lobortis. Aliquam ut nisl eu neque viverra
pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam
convallis, purus sit amet rutrum porttitor, enim ante dapibus libero, finibus
tempor tortor diam sed urna. Aliquam ullamcorper ligula sit amet consequat
faucibus. Donec in nisl tristique, porttitor eros eget, pellentesque orci. Nunc
porta dolor et fringilla auctor. Vestibulum ut dapibus eros. Nunc ac cursus
nisi, at vulputate dolor. Pellentesque habitant morbi tristique senectus et
netus et malesuada fames ac turpis egestas.

== Section 3
== Section 4
== Section 5
== Section 6

Url to <<term>> and then to <<terms>>? 

Url to <<term2>> and then to <<terms2>>? 

```

I have following issues:

## Rendering of `<<anchor>>` both in PDF and HTML
![image](https://user-images.githubusercontent.com/234774/82682519-0e592600-9c58-11ea-891b-d7bbddc4897d.png)

![image](https://user-images.githubusercontent.com/234774/82682549-19ac5180-9c58-11ea-9ccc-4962971dcd2f.png)

## Incorrect link in PDF
If you press `<<terms>>`  link it goes to table of contents instead of anchor:
![asciidotor-anchors-issue](https://user-images.githubusercontent.com/234774/82682765-7445ad80-9c58-11ea-80bc-8577974c965b.gif)

**Comment by mojavelinux** [comment]
This is such a poorly defined feature in AsciiDoc and there's a lot confusion around it. I'll attempt to clarify.

AsciiDoc only supports one primary anchor per element (its ID). That's the anchor that is used for automatic xref text. For example:

```
[#mysection]
== Section with explicit ID

<<<

see <<mysection>>
```

All other anchors are intended for linking in from outside. In other words, they make a URL fragment that can be referenced in a link (aka deep link). They do not get associated with the node and thus do not pick up its reference text.

Consider this example:

```
[#mysection]
== [[alt-anchor]]Section with explicit ID
```

You can target this location from an external resource using doc.html#alt-anchor (for HTML) or doc.pdf#alt-anchor (for PDF). (The feature is intended for preserving legacy URLs). If you want to reference that anchor from within the document, you must specify link text:

```
<<alt-anchor,Section with explicit ID>>
```

It's not that the xref doesn't work. It just doesn't have automatic text.

Given how limited this feature is, it probably needs to be completely reevaluated, which would have to happen in core.

**Comment by mojavelinux** [comment]
Multiple anchors are not supported on a description list term. The manual makes no such claim, so that's not relevant to this discussion.

**Comment by mojavelinux** [comment]
I'm closing in favor of a docs issue since that's the real issue here: https://github.com/asciidoctor/asciidoctor.org/issues/949

**Comment by habamax** [comment]
> Multiple anchors are not supported on a description list term. The manual makes no such claim, so that's not relevant to this discussion.

Sure, no problem.

But multiple anchors on a section?

**Comment by mojavelinux** [comment]
> But multiple anchors on a section?

Yes, but for the purpose I described above. Let's continue the discussion in https://github.com/asciidoctor/asciidoctor.org/issues/949.

Generally, you should have one anchor per node. Multiple anchors is an advanced / specialized use case.

**Comment by habamax** [comment]
So for PDF, incorrect jump is not an issue in the first place, because ... and it will be described in manual?

**Comment by mojavelinux** [comment]
:+1:
