### ISSUE TITLE
Unable to render PDF title pages with custom theme

### ISSUE THREAD

**Issue by jlettman** [asciidoctor/asciidoctor-pdf#1712]
A while back I created a custom theme for company documents. The custom theme has a title page as nice polish:
[sample2.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/4762043/sample2.pdf)

Since upgrading `asciidoctor` for a CI/CD pipeline, the title page disappears:
[sample.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/4762042/sample.pdf)

I've lurked through previous issues which have recommended setting `:title-page:` or `:doctype: book`; however, neither resolve the missing title page.

Attached is the repository of my sample:
[asciidoctor-sample.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/4762065/asciidoctor-sample.zip)

- `sample.adoc` is the asciidoctor source file
- `resources/themes/aethon-theme.yml` is the theme definition

The `Makefile` contains the process for calling `asciidoctor-pdf` and referencing the theme.

**Comment by mojavelinux** [comment]
Thanks for providing a reproducible sample.

The problem you are running into is that you have blank lines in your document header. This causes the document header to be cut short and thus the `title-page` attribute doesn't take effect. See https://asciidoctor.org/docs/user-manual/#doc-header

The default position for background images has also changed, so you'll need to define the position of the image in your theme as follows:

```yml
title_page:
  background_image: image:images/title_page-tug.jpg[position=top center]
```

Those two changes should get you back on track.

**Comment by jlettman** [comment]
@mojavelinux fabulous! I am back on track after banging my head against this for a while. 
Thank you very much!

**Comment by mojavelinux** [comment]
Great to hear it!
