### ISSUE TITLE
Is it possible to apply a role to a table when styling a PDF (not HTML)?

### ISSUE THREAD

**Issue by wunderpraechtig** [asciidoctor/asciidoctor-pdf#1714]
Hello guys,
this is the first time I'm asking anything in a forum, so please bear with me. Also I'm very new to AsciiDoc.

I am currently styling a PDF with AsciiDoc and I'm having an issue with tables. I want to render them in different ways and thought that using roles is the right approach in order to be able to style different tables differently. I was able to get roles to work in a table entry, but what I want to do now is to style the WHOLE table - and make it transparent for instance. 

So, in my custom-theme.yml I wrote:

> role:
>   mytable:
>     font-color: #FF0000
>     border-color: transparent

(I don't know how to show the indentation when Copy-Pasting the code lines.. There is one after role and one after mytable)
 
And I tried to somehow apply it to my table in several ways. According to [this issue](https://github.com/asciidoctor/asciidoctor/issues/1119) I tried to apply the role like this:

> [.mytable]
> |===
> | Data: | Entry
> | Data2: | Entry2
> |===

Neither the color is applied nor are the borders of the table transparent. 
My questions are now

1. is it possible to apply roles when not using HTML but "normal" PDFs?
2. if it IS possible, am I doing something wrong? What am I doing wrong?

I looked at several issues that were about styling tables but I didn't feel like it helped me with my issue.

Thanks in advance for you help!
Kindest regards,
Ebru

**Comment by armakunizen** [comment]
@wunderpraechtig I found the following here: https://github.com/asciidoctor-pdf/blob/v1.5.0.beta.7/docs/theming-guide.adoc#keys-role

> Currently, custom roles only apply to inline phrases and only support changing the font properties


I would love to see more possibilities for roles in PDF styling, too

**Comment by wunderpraechtig** [comment]
Welp, that's unfortunate. @armakunizen thank you so much for answering!

**Comment by mojavelinux** [comment]
The theme system just wasn't built to allow that level of styling (even though the role information is there). We are considering how roles might work for blocks in #483. But it's unclear how much control that will provide (without making the converter extremely complex).

If you need fine-grained styling, that is what asciidoctor-web-pdf aims to provide since it's based on HTML and CSS.
