### ISSUE TITLE
Hyphenation exceptions not always respected

### ISSUE THREAD

**Issue by klonfish** [asciidoctor/asciidoctor-pdf#1715]
Some language files of `Text::Hyphen` contain exceptions for some words to explicitly specify their hyphenation (e.g. the [Dutch one](https://github.com/halostatue/text-hyphen/blob/master/lib/text/hyphen/language/1.9/nl.rb#L1174)). However, these are not respected if that word is right next to another character (e.g. punctuation).

Example:
![Comparison of hyphenation without and with adjacent character](https://user-images.githubusercontent.com/1299450/85178667-5bdca900-b27f-11ea-86c4-63f292d87e36.png)
The allowed hyphenation according to the exception is "sou-ve-niertjes".

This is because `hyphenate_words` matches on any non-whitespace character and passes the resulting tokens to the hyphenator, which then uses it for a lookup in the exceptions hash and that fails if the token includes an adjacent character.

This could be fixed by using a narrower regexp for the tokenization, e.g. `[[:alpha:]]` or `[[:word:]]`. Especially the latter seems to be exactly intended for such purposes and worked well in my tests. Do you see any problem with that? Maybe breaking the hyphenation in some special cases? Additionally, this would avoid the special handling of hyphenated hyphens, since the two words will be hyphenated separately.

**Comment by mojavelinux** [comment]
If you'd like to try to resolve this, I'll happily accept and review a PR for it. I'm not bound to how it's currently implemented.
