### ISSUE TITLE
table cell has parenthesis removed

### ISSUE THREAD

**Issue by BrianEmberling** [asciidoctor/asciidoctor-pdf#1716]
I have a simple table with 2 very similar entries with
the text of c++ expressions.  Using the default theme and version 1.5.3
the first table entry has some of the parenthesis removed, while a similar
expression on the next line has no parentheses removed.

= header
[cols="2,2", options="header, autowidth"]
|===
|field1 | field2
|entry1 | if ((n & 0xf) < (16-cntl[3:0]))  end1
|entry2 | if ((n & 0xf) >= cntl[3:0]) end2
|===

![image](https://user-images.githubusercontent.com/28990171/85187255-1f935380-b253-11ea-8e34-00d23cb41d50.png)

**Comment by mojavelinux** [comment]
The first equation is being matched as a visible index entry (this has nothing to do with tables). You can escape it using either backslash:

```
\((n & 0xf) < (16-cntl[3:0]))
```

or an inline passthrough

```
+((n & 0xf) < (16-cntl[3:0]))+
```

See https://asciidoctor.org/docs/user-manual/#index-terms
