### ISSUE TITLE
separate margin theming for portrait and landscape

### ISSUE THREAD

**Issue by dsisnero** [asciidoctor/asciidoctor-pdf#1719]
With the ability to have different page-layout in a document, need the ability to set separate page margins for portrait and landscape modes

Ultimately, it would be nice to have different named page-types but for now adding the following should suffice.

page-portrait-margin:
page-landscape-margin 

eventually look at how xsl-fo has page master and page sequences -  that would give the best flexibility theming wise

https://www.webucator.com/tutorial/learn-xsl-fo/page-layout.cfm

**Comment by mojavelinux** [comment]
The goal of this converter is to serve rudimentary use cases. The theming simply is not designed to handle general purpose layouts that cover all permutations. We can consider moving the needle on a case-by-case basis, but we do not strive to cover everything that xsl-fo provides (like page masters and page sequences).

If we were to implement margins per page orientation, I'm not keen on the orientation being in the middle of the key. I would suggest either portrait-page-margin or page-margin-portrait.

Implementing this would require respecting all the recto/verso logic, both in the main content and in the running content.

I won't have time to work on this in the foreseeable future. If someone wants to come forward to implement it, I will make time to review it.
