### ISSUE TITLE
Basic PDF Generation Fails on example.adoc

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor-pdf#172]
Even running the example.adoc in the Readme, I am getting generation errors.

I've followed the Readme to the letter and I am getting this. Any idea why, guys?

```
[jmorgan@localhost asciidoctor-pdf]$ ruby /home/jmorgan/Copy/Asciidoc_And_Asciidoctor/Example.adoc 
/home/jmorgan/Copy/Asciidoc_And_Asciidoctor/Example.adoc:1: syntax error, unexpected '='
= Document Title
 ^
/home/jmorgan/Copy/Asciidoc_And_Asciidoctor/Example.adoc:2: syntax error, unexpected tIVAR, expecting keyword_do or '{' or '('
Doc Writer <doc@example.com>
                       ^
/home/jmorgan/Copy/Asciidoc_And_Asciidoctor/Example.adoc:3: syntax error, unexpected ':', expecting end-of-input
:doctype: book
         ^
```

**Comment by mojavelinux** [comment]
Are you trying to run Ruby on the AsciiDoc file? I don't think that's what you intend to do :)

**Comment by jaredmorgs** [comment]
In the docs, it suggests running:
$ ruby bin/asciidoctor-pdf example.adoc

I'm running this command from the asciidoctor-pdf git repo because the /bin
part of the command doesn't work.

What an I doing wrong/misinterpreting from the docs?

Cheers

Jared

On Tue, Jun 2, 2015, 03:06 Dan Allen <notifications@github.com> wrote:

> Are you trying to run Ruby on the AsciiDoc file? I don't think that's what
> you intend to do :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/172#issuecomment-107640844>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Can you just install the alpha version that was just released?

gem install asciidoctor-pdf --pre

Otherwise, if you still want to use the source version, you can try:

./bin/asciidoctor-pdf

Or use bundle exec as recommended.

**Comment by jaredmorgs** [comment]
I used the gem install asciidoctor-pdf --pre approach just now.

No success on processing the index.adoc on
https://github.com/jaredmorgs/Pinball_Arcade_Users_Guide_Android/blob/master/index.adoc


It couldn't traverse the includes.

[jmorgan@localhost android-user-guide]$ asciidoctor-pdf index.adoc
asciidoctor: WARNING: index.adoc: line 22: include file not found:
/docs/Settings_Menu.adoc
asciidoctor: WARNING: index.adoc: line 24: include file not found:
/docs/Table_Menu.adoc
asciidoctor: WARNING: index.adoc: line 26: include file not found:
/docs/Google_Play_Services.adoc
asciidoctor: WARNING: index.adoc: line 28: include file not found:
/docs/Launch_Button.adoc
asciidoctor: WARNING: index.adoc: line 30: include file not found:
/docs/Controller_Settings.adoc
asciidoctor: WARNING: index.adoc: line 32: include file not found:
/docs/Android_Sound_Delay.adoc
asciidoctor: WARNING: conversion missing in backend pdf for toc

Thinking it was the TOC macro, I removed that an tried again without
success.

[jmorgan@localhost android-user-guide]$ asciidoctor-pdf index.adoc
asciidoctor: WARNING: index.adoc: line 20: include file not found:
/docs/Settings_Menu.adoc
asciidoctor: WARNING: index.adoc: line 22: include file not found:
/docs/Table_Menu.adoc
asciidoctor: WARNING: index.adoc: line 24: include file not found:
/docs/Google_Play_Services.adoc
asciidoctor: WARNING: index.adoc: line 26: include file not found:
/docs/Launch_Button.adoc
asciidoctor: WARNING: index.adoc: line 28: include file not found:
/docs/Controller_Settings.adoc
asciidoctor: WARNING: index.adoc: line 30: include file not found:
/docs/Android_Sound_Delay.adoc

I did take a look at the WORKLOG and I do understand this is very early
Alpha (wow, that is some list!).

For the record, I did try it on a much simpler document without includes
and it worked a treat. I will be using this tonight in my Asciidoctor
presentation to convert my Run-Sheet.adoc to PDF, so thanks for the quick
assist. :D

Cheers

Jared


On Tue, 2 Jun 2015 at 06:05 Dan Allen <notifications@github.com> wrote:

> Can you just install the alpha version that was just released?
>
> gem install asciidoctor-pdf --pre
>
> Otherwise, if you still want to use the source version, you can try:
>
> ./bin/asciidoctor-pdf
>
> Or use bundle exec as recommended.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/172#issuecomment-107691795>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
I've documented the new gem in
https://github.com/asciidoctor/asciidoctor.org/pull/392

On Tue, 2 Jun 2015 at 07:27 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> I used the gem install asciidoctor-pdf --pre approach just now.
>
> No success on processing the index.adoc on
> https://github.com/jaredmorgs/Pinball_Arcade_Users_Guide_Android/blob/master/index.adoc
>
>
> It couldn't traverse the includes.
>
> [jmorgan@localhost android-user-guide]$ asciidoctor-pdf index.adoc
> asciidoctor: WARNING: index.adoc: line 22: include file not found:
> /docs/Settings_Menu.adoc
> asciidoctor: WARNING: index.adoc: line 24: include file not found:
> /docs/Table_Menu.adoc
> asciidoctor: WARNING: index.adoc: line 26: include file not found:
> /docs/Google_Play_Services.adoc
> asciidoctor: WARNING: index.adoc: line 28: include file not found:
> /docs/Launch_Button.adoc
> asciidoctor: WARNING: index.adoc: line 30: include file not found:
> /docs/Controller_Settings.adoc
> asciidoctor: WARNING: index.adoc: line 32: include file not found:
> /docs/Android_Sound_Delay.adoc
> asciidoctor: WARNING: conversion missing in backend pdf for toc
>
> Thinking it was the TOC macro, I removed that an tried again without
> success.
>
> [jmorgan@localhost android-user-guide]$ asciidoctor-pdf index.adoc
> asciidoctor: WARNING: index.adoc: line 20: include file not found:
> /docs/Settings_Menu.adoc
> asciidoctor: WARNING: index.adoc: line 22: include file not found:
> /docs/Table_Menu.adoc
> asciidoctor: WARNING: index.adoc: line 24: include file not found:
> /docs/Google_Play_Services.adoc
> asciidoctor: WARNING: index.adoc: line 26: include file not found:
> /docs/Launch_Button.adoc
> asciidoctor: WARNING: index.adoc: line 28: include file not found:
> /docs/Controller_Settings.adoc
> asciidoctor: WARNING: index.adoc: line 30: include file not found:
> /docs/Android_Sound_Delay.adoc
>
> I did take a look at the WORKLOG and I do understand this is very early
> Alpha (wow, that is some list!).
>
> For the record, I did try it on a much simpler document without includes
> and it worked a treat. I will be using this tonight in my Asciidoctor
> presentation to convert my Run-Sheet.adoc to PDF, so thanks for the quick
> assist. :D
>
> Cheers
>
> Jared
>
>
> On Tue, 2 Jun 2015 at 06:05 Dan Allen <notifications@github.com> wrote:
>
>> Can you just install the alpha version that was just released?
>>
>> gem install asciidoctor-pdf --pre
>>
>> Otherwise, if you still want to use the source version, you can try:
>>
>> ./bin/asciidoctor-pdf
>>
>> Or use bundle exec as recommended.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/asciidoctor/asciidoctor-pdf/issues/172#issuecomment-107691795>
>> .
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Fantastic! I forgot about the fact that the doc on asciidoctor.org is out of date. Thanks for updating. It reminds me that we need to automate that :)

I'll take a look at the include issue. Stay tuned.

**Comment by mojavelinux** [comment]
Good luck with the presentation, btw!

**Comment by jaredmorgs** [comment]
Thanks mate! I'll link you to the presentation recording once it's
uploaded. Should have lots of AsciiDoc and Asciidoctor tech demonstrated in
it.

On Tue, 2 Jun 2015 at 08:11 Dan Allen <notifications@github.com> wrote:

> Good luck with the presentation, btw!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/172#issuecomment-107732323>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
The problem is that the paths in the includes are absolute paths. You are asking the processor to find the files in the /docs folder at the root of the system. You should remove the leading forward slash. Includes are relative to the document, so unless you are pointing to a folder somewhere else on the system, it should be a relative path.

Here's the command you need to run once you fix that:

```
asciidoctor-pdf -a doctitle='Users Guide for The Pinball Arcade on Android' -a skip-front-matter index.adoc
```

(Ignore the warning...it's harmless)

You have to pass the doctitle explicitly because it's hidden in the Markdown front matter. Jekyll AsciiDoc can read a native AsciiDoc header, so I recommend you write it this way:

```
---
email: jaredleonmorgan@gmail.com
version: 1.2
updated: 2015-04-28 
documentationExpanded: false
postsExpanded: false
---
= Users Guide for The Pinball Arcade on Android
Jared Morgan
:page-layout: default
:imagesdir: images 
:homepage: http://jaredmorgs.github.io/Pinball_Arcade_Users_Guide_Android
:sectnums:
:sectanchors:
:toc: macro
```

You can see in the plugin how AsciiDoc passes header attributes to Jekyll to populate it's front matter dictionary internally. See https://github.com/asciidoctor/jekyll-asciidoc/blob/master/lib/jekyll-asciidoc.rb#L99-L114

**Comment by mojavelinux** [comment]
Pull request sent.

**Comment by mojavelinux** [comment]
Let me know if you get it working.

**Comment by jaredmorgs** [comment]
Yep, the generated PDF works just perfectly once I ran the correct command
and implemented the changes in your PR. Thanks again for the quick assist
with this, Dan.

On Tue, 2 Jun 2015 at 09:00 Dan Allen <notifications@github.com> wrote:

> Let me know if you get it working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/172#issuecomment-107741756>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
Issue no longer presents. I even get the TOC building fine! For me, it's ready for the prime time. :+1:
