### ISSUE TITLE
Is there a way to control size of text in a callout list?

### ISSUE THREAD

**Issue by cscalfani** [asciidoctor/asciidoctor-pdf#1722]
I'd like to have the font size for the text that follows a callout to be slightly smaller than the main text. By default it's the same size and I've searched the documentation and am still not sure how to specify in my Theme YML the font size of the callout text.

**Comment by mojavelinux** [comment]
You are correct that there is currently no way to independently control the font properties of items in a callout list.

**Comment by cscalfani** [comment]
This would be such a great feature. When callout text has the same weight as other text, it fails to be subordinate to the main text.
