### ISSUE TITLE
Internal links are disabled if you import a PDF using the block image macro on the first page

### ISSUE THREAD

**Issue by divideconcept** [asciidoctor/asciidoctor-pdf#1726]
Starting your document with a cover imported from a (one page) pdf disables all internal links in your documents.

To repro, just have the very first visible content of your .adoc being something like:

`image::manualcover.pdf[]`

(this before any potential title, although if you have a cover pdf ready you usually don't need to also add a text title).
What will happen is that all links will still be highlighted in blue, but won't be clickable anymore.

Links works as expected if you insert your pdf cover after any other content (text title page, or even lower down your document). But that defeats the purpose of having a cover pdf.
Links also works as expected if you have your very first page to display a png instead of a pdf, but I didn't found any way to have that png fully covers the entire page, it somehow always end up being restricted by some margin, and having a page numbering (1) visible in the lower right corner.

This looks like a bug, but meanwhile if you have any workaround (such as being able to have a full page, borderless png as a cover, or some special formatting that would work for the cover pdf) I'd appreciate !

**Comment by mojavelinux** [comment]
Please submit a complete example that demonstrates the defect. (You can do so via an GitHub repository, gist, or zip). It's very likely there's something in the PDF you're using for the cover that is changing the internal object structure in a way that is breaking links. (And that could indicate a bug in prawn-templates). So I'd have to see what that PDF contains and what impact it is having in order to debug it.

**Comment by divideconcept** [comment]
[pdfcover-bug.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/4941397/pdfcover-bug.zip)
I attached a very minimal repro to this post. Just call `asciidoctor-pdf manual.adoc`

**Comment by mojavelinux** [comment]
You are not specifying the cover image correctly. It should be:

```
:front-cover-image: image:cover.pdf[]

This is a minimal repro of the cover PDF bug....
```

The problem isn't about a cover page at all, but rather when a PDF is imported using the block image macro. I have an idea why that is.

**Comment by divideconcept** [comment]
Oh, awesome it's indeed working now !
I think I was confused by thinking the main doc is https://asciidoctor.org/docs/asciidoctor-pdf/ and https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc (where :front-cover-image: is mentionned) was a guide to create custom stylesheets.

**Comment by mojavelinux** [comment]
The theming guide is about all things theming, both the YML file and the theme-related AsciiDoc attributes.

**Comment by mojavelinux** [comment]
So this is an issue, just not as you original described. If a PDF is imported using the image block macro, then all the anchor targets (called Names in PDF terminology) get dropped from the generated PDF. I'm not sure why that is happening.

**Comment by divideconcept** [comment]
I noticed another issue if I use `:front-cover-image: image:cover.pdf[]` as recommended : the page numbering is shifted by one. Meaning the inserted cover.pdf counts as page 0, but every pdf reader will read the final output with that cover page as page 1, so there's a desync between the pdf reader and the page number shown in the toc and at the bottom of every page.
The page number is fine if I just use `image:cover.pdf[]` without `:front-cover-image:` but then the links are broken.

Any workaround for the page numbering ?

**Comment by mojavelinux** [comment]
You seem to be confusing physical page numbers with visible page number labels. It's customary for the cover page and other front matter to be labeled using roman numerals (i, ii, iii, etc) and for the integer counting start at the first page of content (1, 2, 3, etc). PDF readers account for these two different numbering systems.

The theme can control the page on which the transition happens. However, what the theme cannot do is start the visible numbering on the cover page. But that's a good idea. I'll open a separate issue for that. (Currently, the allowable values are title, toc, body, or a body offset, as described by the theming guide).

**Comment by divideconcept** [comment]
To illustrate what I mean, here's my pdf as seen in Google Chrome : see the page number by Chrome at the top, and the page number by AsciiDoctor at the bottom.
![image](https://user-images.githubusercontent.com/3392900/87885060-2e685400-ca13-11ea-8a67-88b64161decf.png)

**Comment by mojavelinux** [comment]
Indeed, that's what we expect. Chrome is counting physical page numbers. Asciidoctor PDF is labeling logical / visible page numbers.

I realize that this topic isn't covered well in the theming guide, so I will add a section.

**Comment by mojavelinux** [comment]
I've discovered that the root cause of this issue is the delete_page method, which removes the current (blank) page to make way for the imported page. The delete_page tries to remove the references to the deleted page. In doing so, it corrupts the internal reference tables that Prawn uses. The fix is to defer vacuuming refs until after the document has been completely converted to PDF.
