### ISSUE TITLE
converter.rb:537:in `convert_colist': undefined method `-' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor-pdf#173]
Trying to build asciidoctor-pdf from the tagged version Release 1.5.0.alpha.7 fails with:

````
/home/david/code/personal/git/asciidoctor-pdf/lib/asciidoctor-pdf/converter.rb:537:in `convert_colist': undefined method `-' for nil:NilClass (NoMethodError)
        from /home/david/code/personal/git/asciidoctor-pdf/lib/asciidoctor-pdf/converter.rb:76:in `convert'
        from /home/david/.rvm/gems/ruby-2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:71:in `convert'
````

Using this diff clears the error, but I am just skipping whatever the code is doing:

````diff
diff --git lib/asciidoctor-pdf/converter.rb lib/asciidoctor-pdf/converter.rb
index 920992e..7a8403d 100644
--- lib/asciidoctor-pdf/converter.rb
+++ lib/asciidoctor-pdf/converter.rb
@@ -533,7 +533,7 @@ class Converter < ::Prawn::Document
   def convert_colist node
     # HACK undo the margin below previous listing or literal block
     # TODO allow this to be set using colist_margin_top
-    unless at_page_top? || (self_idx = node.parent.blocks.index node) == 0 ||
+    unless at_page_top? || (self_idx = node.parent.blocks.index node) == 0 || self_idx.nil? ||
         ![:listing, :literal].include?(node.parent.blocks[self_idx - 1].context)
       move_up ((@theme.block_margin_bottom || @theme.vertical_rhythm) / 2.0)
       # or we could do...
````

I don't know what it means for `self_idx` to be `nil`.

**Comment by mojavelinux** [comment]
That's very strange because it means that the colist node is not in the tree. Can you isolate this down to a small AsciiDoc file that demonstrates the issue? I'm also curious about what causes it. Maybe I've got a false assumption here.

**Comment by DavidGamba** [comment]
Narrowed down to this:

````adoc
= Installing

. Some step:
+
.Example list of dependency RPMs
[subs="verbatim,attributes"]
----
jdk-{java_version}-fcs.x86_64 <1>
jre-{java_version}-fcs.x86_64 <1>
----
<1> Either the `jdk` or `jre` rpm must be installed.

````

I run it with:

`bundle exec ~/code/personal/git/asciidoctor-pdf/bin/asciidoctor-pdf installing_product.adoc -a java_version=1.7`

**Comment by mojavelinux** [comment]
Thanks! Exactly what I need to investigate.

**Comment by mojavelinux** [comment]
I remember this problem. The parent of a block attached to a list item is the list, not the list item. Therefore, the block is failing to locate itself within the parent.

I'm not sure yet if I want to add a hack or just check for nil (as you have done), then fix it upstream and let the behavior activate once Asciidoctor 1.5.3 is out.

The behavior is to reduce the gap between the listing block and the callout list when they are adjacent.

**Comment by mojavelinux** [comment]
I've opened https://github.com/asciidoctor/asciidoctor/issues/1359 to address the root cause. Therefore, I'd like to proceed by simply adding the nil check and allowing the behavior to activate when Asciidoctor 1.5.3 or better is used.

**Comment by DavidGamba** [comment]
Thanks for the quick fix. I'll hopefully have a chance to test your latest changes in the next couple of days.
