### ISSUE TITLE
Option to place example and code captions below block

### ISSUE THREAD

**Issue by mafritsch** [asciidoctor/asciidoctor-pdf#1730]
I searched the documentation and found no way to number example or code captions and move them below the example/code. Similar to tables with the  

```
caption:
    side: bottom
```

option in custom themes.

**Comment by mojavelinux** [comment]
Example blocks are numbered by default if the block has a title.

```
.Title
====
content
====
```

You can enable the same behavior for listing and source blocks by setting the following AsciiDoc attribute in the document header:

```
:listing-caption: Listing

.Title
----
code
----
```

As for where the caption is placed, that's a separate issue. For example blocks and listing/source blocks, the caption location is fixed above the block.

**Comment by mojavelinux** [comment]
The tradeoff here is that the converter will not protect against the caption being widowed on the next page. The logic to arrange blocks does not account for that scenario, and it's quite difficult to know what to do in any case. Ideally, it would pull the block down if unbreakable is set on the block, but we're not able to do that right now.

**Comment by aburkov** [comment]
> As for where the caption is placed, that's a separate issue. For example blocks and listing/source blocks, the caption location is fixed above the block.

Is there a way to put them below the block?

**Comment by mojavelinux** [comment]
Please direct questions to the project chat at https://chat.asciidoctor.org.
