### ISSUE TITLE
Table in pdf extends past edge of page

### ISSUE THREAD

**Issue by atomlin** [asciidoctor/asciidoctor-pdf#1731]
I have a table that formats ok in html but the pdf version spills off the page, any solutions?
HTML
![html](https://user-images.githubusercontent.com/7913505/87949677-30ee9c00-ca5b-11ea-9a3e-fed47c8a83d1.png)
PDF
![pdf](https://user-images.githubusercontent.com/7913505/87949747-45329900-ca5b-11ea-9de1-9b8c641fbc25.png)

Version info
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Table source

```
== MAP

=== AndyTable Rev1 (FE -> MAP) 

[cols="1,9,5,20,9", stripes=even]
|===
2+h|Function {set:cellbgcolor:skyblue}
3+|AtomicAbort {set:cellbgcolor:default}


2+h|From -> To {set:cellbgcolor:skyblue}
3+|FE ->MAP {set:cellbgcolor:default}

2+h|HW Name {set:cellbgcolor:skyblue}
3+|fe_map_atomic_abort {set:cellbgcolor:default}

2+h|I/F Type {set:cellbgcolor:skyblue}
3+|rdy_vld {set:cellbgcolor:default}

2+h|Description {set:cellbgcolor:skyblue}
3+|Abort Atomic command. Roll back operation.{set:cellbgcolor:default}

2+h|Call Struct {set:cellbgcolor:skyblue}
3+|atomic_abort_st {set:cellbgcolor:default}

.4+| 
^h|Field {set:cellbgcolor:skyblue}
^h|Bits 
2+h|Description

>|cmdid {set:cellbgcolor:aliceblue}
^|10 {set:cellbgcolor:default}
2+|<<NUM_CMDS_LOG2>> Internal Command Identifier


>|atomic_tag {set:cellbgcolor:aliceblue}
^|5 {set:cellbgcolor:default}
2+|<<NUM_ATOMIC_TAGS_LOG2>> Atomic tag, used for managing
atomic commands

|===

```

**Comment by mojavelinux** [comment]
This is working as designed. If there's not enough room for the table to fit on the remaining space on the page, it will be split. A cell which spans multiple rows will not be split, so the whole cell and the rows it covers will be moved to the next page. The splitting logic is handling in prawn-table, so it is not something this converter can influence.
