### ISSUE TITLE
Too many index entries breaks TOC layout when using section indent.

### ISSUE THREAD

**Issue by divideconcept** [asciidoctor/asciidoctor-pdf#1735]
I noticed that when using section indent (>0), as soon as index entries generates more than one page of index, it breaks the TOC layout.

When more than one page of index entries are generated, instead of properly applying section indent to TOC, it is applied "negatively": the TOC title is shifted horizontally to the left by the value of indent, while the content of the TOC considers an indent of zero.

To be clear, I'm talking about this value:
```
section:
  indent: 50
```
If I reduce the number of index entries so that it fits one page, or if I reduce the font size for the whole document so that index entries fits one page, the problem does not occur.

I attached a couple PDF examples to this post.

[one index page doesnt break TOC with section indent (fewer entries).pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/4975277/one.index.page.doesnt.break.TOC.with.section.indent.fewer.entries.pdf)
[one index page doesnt break TOC with section indent (smaller font).pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/4975280/one.index.page.doesnt.break.TOC.with.section.indent.smaller.font.pdf)
[two index pages breaks TOC with section indent.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/4975281/two.index.pages.breaks.TOC.with.section.indent.pdf)

**Comment by mojavelinux** [comment]
Can you provide a sample AsciiDoc document that I can use for testing?

**Comment by divideconcept** [comment]
Sure, here's a minimal example to repro.
If you comment 2 lines of indexed content, the TOC gets a normal layout again (since the Index is then only one page instead of 2).
[PDF TOC layout issue because of large index.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/5080464/PDF.TOC.layout.issue.because.of.large.index.zip)

**Comment by mojavelinux** [comment]
I see the problem. Thank you. It seems like when the index exceeds a page, it leaves the cursor in an inconsistent state, which then impacts the TOC. The TOC is rendered last since it needs to know where the content ended up.

**Comment by mojavelinux** [comment]
Looks like a bug in Prawn with the column_box helper, but we can work around it.

**Comment by divideconcept** [comment]
Thanks, I indeed confirm the issue is fixed with your patch.

**Comment by mojavelinux** [comment]
Thanks for testing and verifying! And thanks again for test case. It made fixing it easy. Great teamwork!
