### ISSUE TITLE
How to create fancy theme

### ISSUE THREAD

**Issue by kwoot** [asciidoctor/asciidoctor-pdf#1736]
Hi,

So, some well known publisher has a nice layout for the first page of every chapter:

```
             Chapter X
----------------------
         Chapter-title
```

Would that somehow be possible to create in a theme that extends default? 
I can't seem to find a way to select first page of chapter or am I not seeing it?

Anybody any thoughts or pointers?

Regards,
Jeroen

**Comment by mojavelinux** [comment]
The theme cannot affect the layout, with the exception of spacing in certain places. If you want a custom layout, you must extend the converter. This process is described in the theming guide. https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#extending-the-converter

If there's information in that section you feel is missing, please reopen and describe where you got stuck. I'll then improve the documentation.

**Comment by kwoot** [comment]
Got it. Thanks! Note to self: learn Ruby. :-)
