### ISSUE TITLE
How to insert a space at the head of line?

### ISSUE THREAD

**Issue by blling** [asciidoctor/asciidoctor-pdf#1738]
eg,
```
你好！
```
to
```
    你好！
```

**Comment by mojavelinux** [comment]
You can use the no-break space character.

```
{nbsp}{nbsp}你好！
```

or the zero-width character followed by the space character:

```
{zwsp}{sp}{zwsp}{sp}你好！
```

However, both of these solutions lack proper semantics. Perhaps a verse would be a better option?

```
[verse]
  你好！
```

**Comment by blling** [comment]
@mojavelinux Thanks at first, i use `{emsp}{emsp}` instead because i use chinese.

[verse] not meet my need, because it case all break line has two spaces, but i just need the first has two spaces. 

Thanks for you great work again, i can use this instead of `GitBook` now :-)
