### ISSUE TITLE
Cannot use {lt} inline like you can use {gt}.

### ISSUE THREAD

**Issue by cscalfani** [asciidoctor/asciidoctor-pdf#1740]
If I do the following:

```
The forward arrow looks like this `-{gt}`
```
It renders as `->`.

But if I do:

```
The backward arrow looks like `{lt}-`
```

I get the following error: 

```
asciidoctor: ERROR: failed to parse formatted text: The backward arrow looks like <code><-</code>
```

**Comment by mojavelinux** [comment]
This is the expected behavior. The `{lt}` attribute emits a raw `<` sign to bypass processing, which is most likely going to lead to invalid output. The correct character reference in this case is `&lt;`.

**Comment by mojavelinux** [comment]
The reason `{gt}` works is because, alone, > is not a special HTML character. Only when paired with < does it become special.

**Comment by cscalfani** [comment]
Thanks for the explanation and solution. Worked great!!
