### ISSUE TITLE
SVG in Header loose a color

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1742]
If you have an image big enough + headers with colored svg:

![image](https://user-images.githubusercontent.com/234774/89542076-dcdc0980-d807-11ea-9126-8d87f8675763.png)

source data:

[bug.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/5035348/bug.zip)

asciidoctor-pdf version is today master c5b82196532db9111286130c9ebfdabfbdead558

**Comment by mojavelinux** [comment]
Aha! Yes! You found me my missing test case.

Check out this comment: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor/pdf/converter.rb#L1554-L1557

I couldn't figure out how to reproduce it. Now I can. I'll add the test then restore the disabled method call. Thanks!

**Comment by habamax** [comment]
Glad it was helpful. I had this bug popping out from time to time and yesterday I was able to narrow it to a minimal example.

**Comment by mojavelinux** [comment]
Thank you so much for taking the time to do it. It helped me pinpoint the source of the error in minutes.

**Comment by habamax** [comment]
Thx, looks fixed for me!

**Comment by mojavelinux** [comment]
Fantastic! Thanks for verifying. And sorry for the delay.
