### ISSUE TITLE
Build pdf using two themes?

### ISSUE THREAD

**Issue by daveshook** [asciidoctor/asciidoctor-pdf#1743]
Is there a way to build a pdf that includes multiple .adoc files and specify the theme at the individual .adoc file level?

Currently we build separate pdf files using a different theme for each. I would like to combine these two pdf files into a single file. I know there are tools available to merge the pdf files but I would prefer to accomplish this using the artifact builder.

**Comment by mojavelinux** [comment]
The theme can be specified in the header of the AsciiDoc file (using the pdf-theme attribute). There's no other way to specify different themes for different files in the same run. (You'd have to write a script to do something more sophisticated).

**Comment by daveshook** [comment]
My build is done with an AsciiDoc file that that specifies additional AsciiDoc files using `:include:` references. I added a `:pdf-theme:` attribute to one of the included AsciiDoc files but it did not override the default theme.  I thought the previous response indicated this is possible. Did I understood incorrectly or is my `:pdf-theme:` attribute is specified using the wrong format?

**Comment by mojavelinux** [comment]
The `pdf-theme` attribute must be set in the document header. It cannot be set at an arbitrary location within the document.
