### ISSUE TITLE
Subscript chars in literals are not output

### ISSUE THREAD

**Issue by andraz-kozelj** [asciidoctor/asciidoctor-pdf#1745]
My settings:
```
literal:
  font:
    color: $better_color_orange
    size: 0.9em
    family: LibreFranklin
```
With LibreFranklin being my default font.

The document has the following content:
```
`data[at0001]/events[at0002, 'Scale 2']/data[at0003]/items[at0006, 'SpO~2~ Scale 2']/value/normal_status/code_string`

`+data[at0001]/events[at0002, 'Scale 2']/data[at0003]/items[at0006, 'SpO~2~ Scale 2']/value/normal_status/code_string+`

data[at0001]/events[at0002, 'Scale 2']/data[at0003]/items[at0006, 'SpO~2~ Scale 2']/value/normal_status/code_string
```

In html (Asciidoctor output) all is fine:
![image](https://user-images.githubusercontent.com/2230309/90130770-4cec1180-dd6b-11ea-8349-e633c5b339a1.png)

In PDF there is subscript missing (see first line):
![image](https://user-images.githubusercontent.com/2230309/90130807-60977800-dd6b-11ea-998a-894e5d301929.png)

**Comment by mojavelinux** [comment]
It seems to work fine when I try it both the with default theme and a theme that uses LibreFranklin.

Can you provide a full sample project on GitHub that reproduces the issue? There may be another factor at play here that I'm not considering.

**Comment by mojavelinux** [comment]
Aha! I just figured it out. It's the `0.9em`. It appears that the value is not being handled correctly once subscript is added.

**Comment by mojavelinux** [comment]
As a workaround, you can use a fixed number for the literal font size.

**Comment by mojavelinux** [comment]
Btw, the character is there. It's just too small to be rendered.

**Comment by mojavelinux** [comment]
The underlying issue here is that the superscript / subscript routine does not properly compute the relative font size when the font size has `em` units.

**Comment by andraz-kozelj** [comment]
Got it, changed to a fixed number.
