### ISSUE TITLE
SVG image format not recognized 

### ISSUE THREAD

**Issue by fhaefemeier** [asciidoctor/asciidoctor-pdf#1746]
I want to embed an SVG image download from https://img.shields.io/badge/Status-Open-red but I get the warning "asciidoctor: WARNING: could not embed image: /tmp/image-20200813-6-1ymd8ff; image file is an unrecognized format; install prawn-gmagick gem to add support".

**Comment by mojavelinux** [comment]
When specifying a path or URL, you need to indicate the format. You can do so either by appending the file extension .svg or declaring it in a macro attribute format=svg.

```
image:https://img.shields.io/badge/Status-Open-red.svg[]

or

image:https://img.shields.io/badge/Status-Open-red[format=svg]
```

**Comment by fhaefemeier** [comment]
Thanks for the hint. It works with two exceptions:

1. the included image is printed without color (black background and white text), but it should be black/red background. It shows a badge create and loaded from [shield.io](https://img.shields.io/badge/Status-Open-red)
1. It prints the following warnings independently using the svg extension or macro attribute
> /usr/lib/ruby/gems/2.7.0/gems/prawn-svg-0.30.0/lib/prawn/svg/interface.rb:123: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
> /usr/lib/ruby/gems/2.7.0/gems/prawn-2.2.2/lib/prawn/graphics/patterns.rb:67: warning: The called method `fill_gradient' is defined

**Comment by mojavelinux** [comment]
There are limits to what the SVG renderer that Asciidoctor PDF uses can handle. And the shields.io SVGs exceed those limits. Please direct your request for improvement / enhancement to the [prawn-svg](https://github.com/mogest/prawn-svg) project.
