### ISSUE TITLE
Add support for the after-toc keyword for start-at keys in theme

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1763]
If you want to start the page numbering or running content after the toc in a book (doctype=book), and the toc is in the default location, you can use the keyword "body". However, if the toc is placed after the preamble, or in a custom location using the toc macro, you after to specify a body offset (integer value). However, you don't know this offset until the document is converted.

To simplify this configuration, it should be possible to specify the keyword value "after-toc". When this value is specified, the converter will compute the body offset and start the page numbering and running content after it.

The advantage of this keyword is that this will work regardless of the content in the document.

**Comment by mojavelinux** [comment]
Note that when the toc is in the default location, after-toc and body are synonymous.

**Comment by Leon0402** [comment]
Nice! Looking very much forward to it :)

**Comment by mojavelinux** [comment]
PR submitted for testing.
