### ISSUE TITLE
TOC is displayed incorrectly

### ISSUE THREAD

**Issue by F4IL3D** [asciidoctor/asciidoctor-pdf#1764]
The toc is displayed incorrectly with the default theme.

![image](https://user-images.githubusercontent.com/48415231/92233512-b239ab00-eeb0-11ea-90ac-78c7062b5440.png)

If I change the theme like this

```
 dot_leader:
    content: "."
```

or this 

```
dot_leader:
    content: " "
```

the result looks like okay.

![image](https://user-images.githubusercontent.com/48415231/92234022-997dc500-eeb1-11ea-8507-40c5447ec28f.png)

![image](https://user-images.githubusercontent.com/48415231/92234325-1c068480-eeb2-11ea-9abd-c98fe7f84353.png)

Environment:
WSL 2, Ubuntu 20.04

Asciidoctor PDF 1.5.0.alpha.17.dev using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Reader: Adobe Reader (latest Version)

Example .adoc
```
= doc test
:author: F1AL3D
:revnumber: V 1.0
:revdate: 09/03/2020
:pdf-page-size: A4
:experimental:
:icons: font
:toc:
:toclevel: 3
:toc-title: Content
:sectnums:
:doctype: book

== Test
Test



=== Test 2
Test



=== Test 3
Test



== Test 4
Test



=== Test 5
Test
```

**Comment by mojavelinux** [comment]
The version of Asciidoctor PDF you are using is substantially out of date and known to have issues. Please use Asciidoctor PDF 1.5.3 and retest.
