### ISSUE TITLE
Release new version to support prawn:2.3 and ttfunk:1.6

### ISSUE THREAD

**Issue by pevik** [asciidoctor/asciidoctor-pdf#1771]
Could you make a new release to allow people get support of prawn:2.3 and ttfunk:1.6 (commits 0aaf347c3659e562f0bff759dd4cf367c8dd1c40 and 3eec734a33ce848bc37a6bd84fb8868d80422922)?

**Comment by mojavelinux** [comment]
I will be making a prerelease of Asciidoctor 2 later this week.

Since this is not itself a bug or a feature, you should ask it either on the mailinglist or the chat channel. Thanks.

**Comment by pevik** [comment]
Thanks a lot! And sorry for not using ML (normally I do for kernel, C projects, but for ruby I'm just a distro packager).
