### ISSUE TITLE
Duplicated footnotes when applied in Description List

### ISSUE THREAD

**Issue by jawira** [asciidoctor/asciidoctor-pdf#1775]
First of all, thank you for Asciidoctor it's fantastic software.

I have a problem with _footnotes_, when I use footnotes on a _Description List_ they appear in double at the end of the page.

My `asciidoctor-pdf` version:

```console
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

This is my Asciidoctor file:

```adoc
// demo.adoc
= Lorem Ipsum

[horizontal]
First:: Ut ut tempor ipsum.footnote:[Integer sed malesuada enim.]
Second:: Maecenas viverra eleifend suscipit.footnote:[Ut rhoncus sem non ornare posuere.]
```

This is the output when I execute `$ asciidoctor-pdf demo.adoc`:

![Screenshot from 2020-09-28 21-46-01](https://user-images.githubusercontent.com/496541/94478797-101d9200-01d4-11eb-82c0-613bd00173d7.png)

As you can see, the document has four footnotes but only two had been declared.

**Comment by mojavelinux** [comment]
Thanks for pointing this out. I know exactly why this is happening. We had the same problem with other types of blocks, but missed this case when applying the fix for it. I'll put in the necessary logic.

**Comment by mojavelinux** [comment]
I should point out this is specifically a problem with horizontal description lists, not all description lists.
