### ISSUE TITLE
Using a single theme for PDF and HTML generation

### ISSUE THREAD

**Issue by JayanSmartACI** [asciidoctor/asciidoctor-pdf#1784]
I have a document which currently builds a PDF using a yaml theme. We would also like to host this document on a website and build it to an HTML page, however reading the documentation it looks like I would need to build a second HTML theme using CSS. 

Would it be possible to use a single YAML file as a theme for both PDF and HTML generation?

**Comment by mojavelinux** [comment]
What you are asking about is not possible. These are different theming systems.
