### ISSUE TITLE
asciidoctor-pdf does not seem to understand ifdef:: correctly

### ISSUE THREAD

**Issue by mkvonarx** [asciidoctor/asciidoctor-pdf#1788]
I have two issues with ifdef:: and asciidoctor-pdf

**Issue 1**: I have an ifdef::basebackend-html[] section near the beginning of my asciidoc file that defines some CSS styles. This works for HTML output. When creating a PDF with `asciidoctor-pdf myfile.adoc`, the content of the ifdef section is printed into the PDF. Either I'm not using ifdef:: correctly, or asciidoctor-pdf does not understand ifdef::

My asciidoc file:
```
ifdef::basebackend-html[]
++++
<style>
.mytodo { background-color: yellow; }
.myhelp { font-size: 0.875em; color: grey; background-color: lightgrey; }
</style>
++++
endif::basebackend-html[]
```

What I see in my PDF: a rectangle with a rounded border, gray background color and the following text:
```
<style>
.mytodo { background-color: yellow; }
.myhelp { font-size: 0.875em; color: grey; background-color: lightgrey; }
</style>
```

**Issue 2**: I also tried to use the ifdef to define different logic for table column widths (because asciidoctor-pdf does not understand the ~ column width). This also does work with HTML output, but does not work with asciidoctor-pdf. In the created PDF, all columns have the same width.

asciidoc markup:
```
ifdef::backend-pdf[]
[options="header",cols="1,1,1,3"]
endif::[]
ifdef::basebackend-html[]
[options="header",cols="~,~,~,~"]
endif::[]
|===
```

Versions & Environment:
* Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
* Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
* (Ubuntu 18.04 running inside WSL 1)

**Comment by mojavelinux** [comment]
The basebackend for the PDF converter is HTML (because it uses the HTML converter under the covers). You can check for backend-pdf. But when you check for basebackend-html, it overwrites the previous line as it applies to both converters.

**Comment by mkvonarx** [comment]
Thanks! So the mistake was mine. Using ifdef::backend-html5[] works as expected in both cases.
