### ISSUE TITLE
Additional spaces added when using footnotes or full URL paths in a paragraph

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#179]
It seems like whenever I add a footnote or a footnote in a bullet list it seems to add additional unwanted spaces. It does not always do this but seems to happen often enough. I've attached a screenshot from my rendered pdf
![selection_200](https://cloud.githubusercontent.com/assets/8877333/8059038/53cac53a-0e83-11e5-86c4-b6744ad52481.png)

As for additional spaces added, usually if providing a long URL path within a paragraph it can cause these additional spaces to happen as well. I think it happens usually if the URL wraps to the next line. Easy workaround for this is to just use hyperlinked text.

**Comment by mojavelinux** [comment]
What you are observing is the text justification that is used in the default theme. It is attempting to justify the text. A quick way to fix this is to change the default text alignment in your theme:

```
base:
  align: left
```

Of course, the fact that the footnote text is being placed inline is also part of the issue here. See #85.

**Comment by mojavelinux** [comment]
I think the change I'd like to make here is that "simple" lists (lists that don't have complex content) should be forced to use left alignment. It's very unlikely that you would want justified text in these cases. We could also consider a dedicated key in the theme for this.

**Comment by mojavelinux** [comment]
We already add a similar hack for bibliography lists. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L728-L734

**Comment by rlopez133** [comment]
Changing my theme from align: justify to align: left fixed that issue. I was thinking a nice solution would be something similar to http://asciidoctor.org/docs/user-manual/#applying-substitutions as you mentioned in my issue #180. For instance, I create a list and above the list I could set an alignment attribute for that particular list. This gives me the option of say leaving base at whatever alignment I so chose in my theme and modifying the list accordingly via attribute in the doc. Not sure if it can be done like this but figured I'd throw that out there.

**Comment by mojavelinux** [comment]
I realized that we have this control for paragraphs:

```
[.text-left]
Content aligned to left regardless of theme setting.
```

So we just need to add this is lists as well:

```
[.text-left]
* align to left
* align to left
```

I'll file a related issue. See https://github.com/asciidoctor/asciidoctor-pdf/issues/182.

**Comment by mojavelinux** [comment]
All of the proposed changes have been implemented. Starting in alpha.17, you can change the text alignment for list items using:

```
[.text-left]
* Linpack [Linpack - http://software.intel.com/en-us/articles/intel-math-kernel-library-documentation/] is where it's at
```

Or for the whole document using:

```
= Document Title
:text-alignment: left

* Linpack [Linpack - http://software.intel.com/en-us/articles/intel-math-kernel-library-documentation/] is where it's at
```

It's also possible to extend the default theme, so it's very easy to apply a small tweak like this:

```yml
extends: default
base:
  align: left
```

or

```yml
extends: default
outline_list:
  text_align: left
```

So you have lots of options now.
