### ISSUE TITLE
imagesdir is resolved relatively to document

### ISSUE THREAD

**Issue by thorstenkampe** [asciidoctor/asciidoctor-pdf#18]
`imagesdir` is resolved relatively to document location.

Setting

    :imagesdir:   /home/thorsten/.asciidoc/images

results in

    ./asciidoctor-pdf document.adoc
    WARNING: /home/thorsten/bin/asciidoctor-pdf/bin/home/thorsten/.asciidoc/images/DIRECTORY/FILE.png not found

**Comment by plaindocs** [comment]
I'm not sure if this is relevant to #93 or not?

**Comment by mojavelinux** [comment]
Quite possibly. I'll know more when I look into it...thought the fact that we are using the hack that we are using right now could explain a lot of things going wrong with images ;)

**Comment by mojavelinux** [comment]
> I'm not sure if this is relevant to #93 or not?

Actually, it's different. I commented in that issue as to why I believe so.

**Comment by mojavelinux** [comment]
This issue was resolved by https://github.com/asciidoctor/asciidoctor-pdf/commit/0b554c2443f29debaab360093d58638721c4ecc5 as part of the fix for #87. Images should now be resolved consistently with how they work in Asciidoctor core.
