### ISSUE TITLE
Allow custom hyphenation exceptions

### ISSUE THREAD

**Issue by klonfish** [asciidoctor/asciidoctor-pdf#1805]
I think it would be useful to be able to define custom hyphenation exceptions for words that aren't hyphenated correctly. This could be configured similarly to the [`hyphenation`](https://en.wikibooks.org/wiki/LaTeX/Text_Formatting#Hyphenation) command of LaTeX, i.e. a list or white-space separated string of words containing hyphens at the positions where they can be split.

I already did a bit of testing and have some working code for this feature, so i can send a PR if you are interested.
According to the discussion in #1713, I guess the implementation should also use a theme key for that, e.g. `hyphenation`. However, this would "tear apart" the configuration to enable hyphenation and the one for the exceptions. So, maybe version 2.0 it would be a good opportunity to deprecate the `hyphens` document attribute and migrate it into the theme?

**Comment by mojavelinux** [comment]
> maybe version 2.0 it would be a good opportunity to deprecate the hyphens document attribute and migrate it into the theme?

I agree with this assertion.

**Comment by klonfish** [comment]
> I agree with this assertion.

Nice to hear that you agree on that. So, this should probably go before adding further hyphenation options.

What do you think about the proposal to add custom exceptions itself?

**Comment by mojavelinux** [comment]
How the hyphenation itself is preformed really isn't something I think this
converter should be concerning itself with. This feels more like something
the hyphenation library should be providing. It should pick up a
configuration / customization file somewhere in the path.

If that project is not open to this idea, we can add a wrapper around it
and load our own configuration. But it would not be something in the theme
file. That's too coupled. We're configuring the hyphenator, not the
converter. And that's what this proposal should focus on.

For example, the configuration could be loaded and used independent of it's
use in the converter. It's important to maintain these boundaries of
responsibility.

**Comment by graphitefriction** [comment]
Hyphens can now be controlled in the theme using `base-hyphens` (see #2161). As Dan pointed out, behavior of the hyphenation controlled by the text-hyphen gem and not Asciidoctor PDF.
