### ISSUE TITLE
Suppress mailto link when media=prepress

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-pdf#1806]
I am writing an asciidoc document and converting it to PDF using asciidoctorpdf. I am using the `media=prepress` option. When my document has an email address in it e.g., myname@example.com it appears with a mailto link in the PDF which should not happen. This is with asciidoctorpdf 1.5.3

originally reported at https://discuss.asciidoctor.org/How-to-prevent-asciidoctorpdf-from-inserting-mailto-link-in-PDF-td8289.html

**Comment by mojavelinux** [comment]
What we are looking for here is the same logic used for URLs.

**Comment by mojavelinux** [comment]
I discovered that the workaround is to set the `hide-uri-scheme` attribute. However, this attribute does have other side effects. The desired behavior should work regardless of whether that attribute is set.

**Comment by siddjain** [comment]
what side-effects does it have?
how do we set this attribute?
thanks.

________________________________

**Comment by mojavelinux** [comment]
To clarify, the point of this issue is to not need any attribute.

If you use the workaround of setting the hide-uri-scheme attribute, then
the scheme (aka protocol) is dropped from any bare URL. This is documented
in the Asciidoctor user manual.
