### ISSUE TITLE
Up/down arrow symbols not rendered to pdf

### ISSUE THREAD

**Issue by AndreasEhret** [asciidoctor/asciidoctor-pdf#1811]
I have the following asciidoc shortcut cheatsheet that uses arrow key symbols:
```
= Shortcuts
----
Ctrl + →            Alles aufklappen
Ctrl + ←            Alles zuklappen
Ctrl + ↑            Nach oben verschieben
Ctrl + ↓            Nach unten verschieben
----

|===
|Ctrl + → |Alles aufklappen
|Ctrl + ← |Alles zuklappen
|Ctrl + ↑ |Nach oben verschieben
|Ctrl + ↓ |Nach unten verschieben
|===

|===
|Ctrl + &#8594; |Alles aufklappen
|Ctrl + &#8592; |Alles zuklappen
|Ctrl + &#8593; |Nach oben verschieben
|Ctrl + &#8595; |Nach unten verschieben
|===
```

When I render this to PDF the left and right arrow are fine but the up and down arrows are not displayed correctly, neither in the block nor in the table:

<img width="400" alt="cheatsheet_result_pdf" src="https://user-images.githubusercontent.com/9326167/97968627-37611380-1dbf-11eb-8f8a-9475aa16a594.png">

I've already tried to change font by applying a custom theme without any success.

I am using asciidoctorj-pdf version 1.5.3, asciidoctorj 2.4.1, asciidoctor-maven-plugin 2.1.0.

Any ideas what is going wrong and why it works for left/right but not for up/down?

**Comment by mojavelinux** [comment]
The provided default theme does not provide all the glyphs in Unicode. Usually, you can find them in the default-with-fallback-font theme (pdf-theme=default-with-fallback-font). That seems to be the case here.

If the default-with-fallback-font theme does not provide a glyph you want to use, then you'll need to add your own font or fallback font. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#fonts

**Comment by AndreasEhret** [comment]
switching from default to default-with-fallback-font do the trick with the missing arrow symbols. Thanks for the fast help!
