### ISSUE TITLE
Add power (^) operator or function

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor-pdf#1813]
Power operator or function makes it easier to use typographic scales when defining font size. It is not supported yet. So we can have something like this:

```
title-page:
  font-size: $base-font-size * (1.25)^5
```

**Comment by mojavelinux** [comment]
Seems reasonable to me. Is this something you would be able to implement? No need to justify either way. I just need to know.

**Comment by shahryareiv** [comment]
I have no background in Ruby. So, sorry cannot help in the code.

PS: If scales are important one can think of looking at how some CSS frameworks are dealing with that, like this:
https://moderncss.dev/generating-font-size-css-rules-and-creating-a-fluid-type-scale/

**Comment by mojavelinux** [comment]
No problem.

For now, I think we'll just stick with the math operator.

**Comment by mojavelinux** [comment]
Note that, at this time, brackets are not honored. So you need to write the expression in the order in which it will be evaluated.

```
1.25 ^ 5 * $base-font-size
```

If you write it with the power operator at the end, it will be applied to the accumulated result to its left. In other words, this:

```
$base-font-size * 1.25 ^ 5
```

is interpreted as `($base-font-size * 1.25) ^ 5`.

The theme parser was not designed to accommodate complex operations.

**Comment by shahryareiv** [comment]
That looks logical. Thanks!
