### ISSUE TITLE
Add macOS to the CI job matrix

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1817]
Run one or more of the CI jobs on macOS to verify compatibility with that platform.

It's probably not necessary to test all versions of Ruby, so let's start with the latest version of C Ruby and go from there.

**Comment by slonopotamus** [comment]
Note that I was getting Pygments timeouts on MacOS until increased its time limit: https://github.com/asciidoctor/asciidoctor-epub3/commit/3cf1b101e5d02daccfeb486434d7b0be61c26fdd
Actually, it is very weird that they have some random time limit enabled by default and don't have any way to make it unlimited.

**Comment by slonopotamus** [comment]
I believe you're hitting the same issue: https://github.com/mojavelinux/asciidoctor-pdf/runs/1389317463#step:11:15

**Comment by mojavelinux** [comment]
Yes, in fact I am. And I was wondering what to do about it. Thanks for the tip!

**Comment by mojavelinux** [comment]
Fix applied.
