### ISSUE TITLE
Allow text alignment to be controlled in lists using a role

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#182]
It's possible to control the text alignment on paragraphs (overriding the value in the theme) using the roles text-left, text-center, text-right, text-justify. (See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L363-L372). Similar control should be added to outline lists (ordered an unordered).

For example:

```
[.text-left]
* align text to left for this list only
* align text to left for this list only
```

**Comment by mojavelinux** [comment]
This gives the option of leaving whatever alignment you want in the theme and modifying the list accordingly via an attribute.

**Comment by mojavelinux** [comment]
cc: @rlopez133

**Comment by mojavelinux** [comment]
One open question is whether we should automatically use left alignment for the text of a list item.

**Comment by mojavelinux** [comment]
This turns out to be a rather complex issue because it raises the question of how to handle inheritance. The default stylesheet for the HTML output inherits the alignment to all nested blocks (unless the alignment is overridden by a more specific style).

What I decided to do is inherit the alignment to discrete headings and paragraphs, but not other types of blocks.

```
[.text-center]
* Centered list text
** Centered list text

+
--
Centered paragraph text

[discrete]
== Centered Heading
--

* Centered list text
```

![list-alignment](https://cloud.githubusercontent.com/assets/79351/19416880/e00893f4-9359-11e6-8c8f-963bf6178621.png)

I also added a property to the theme that can be used to set the alignment for the item text only (no inheritance).

```
outline_list:
  text_align: left
```

Time and experience will perhaps tell whether this is the correct behavior or whether more control is needed. We may need a way for the role to specify an alignment for the item text only. Perhaps `item-text-<align>`.

**Comment by ITler** [comment]
Does this work for lists in table cells, too? I'm just facing this kind of issue, that list text is justified to cell borders

**Comment by mojavelinux** [comment]
Yes, once implemented, it will apply anywhere a list can be used.

**Comment by ecki** [comment]
Just to be sure, `outline_list_(text_)align: left` does not work work with Alpha16 at all? Looks always justified in my tests

**Comment by mojavelinux** [comment]
I decided to remove the inheriting stuff for now. Aside from that, the change is now in master. (Please consult the milestone to know when an issue got fixed).
