### ISSUE TITLE
Floating section link in repository README is incorrect

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor-pdf#1823]
https://github.com/asciidoctor/asciidoctor-pdf#optimizing-the-generated-pdf should land on the "Optimizing the Generated PDF" section but doesn't as the floating link (selected by the paragraph icon to the left of the section title) has this anchor, but the generated ID in the HTML prefixes the actual HTML anchor to be 'user-content-optimizing-the-generated-pdf'. This is true of other section anchors as well. Maybe this is something weird about Github's asciidoctor viewer?

**Comment by mojavelinux** [comment]
The addition of user-content- prefix is the standard behavior of GitHub. There is a script to maps the fragment in the URL to this prefixed ID, thus making it transparent. You can find an explanation of how it works in this issue and other linked references https://github.com/github/markup/issues/425

From time to time, GitHub rolls out or A-B tests changes to the UI. These changes sometimes break behavior. It's likely that in a few days, you will no longer see this problem. If it persists, then it needs to be filed in the issue tracker I referenced above.
