### ISSUE TITLE
creation of links to external files fails when the path contains spaces

### ISSUE THREAD

**Issue by heiwilOS** [asciidoctor/asciidoctor-pdf#1825]
when using asciidoctor-pdf links like this:
`link:Dir\SubDir With Space\File.pdf[Linkname]`
or
`link:Dir\SubDir\File With Space.pdf[Linkname]`
do not create hyperlinks

Heiko

**Comment by mojavelinux** [comment]
This is normal behavior in AsciiDoc. The target of a link cannot have a space unless escaped or encoded. Here are three ways to write it:

Using an encoded space:

```
link:Dir\SubDir%20With%20Space\File.pdf[Linkname]
```

Using a character reference:

```
link:Dir\SubDir&#32;With&#32;Space\File.pdf[Linkname]
```

Using an inline passthrough:

```
link:pass:[Dir\SubDir With Space\File.pdf][Linkname]
```
