### ISSUE TITLE
Loading images in theme from classpath/jar file

### ISSUE THREAD

**Issue by ldesgrange** [asciidoctor/asciidoctor-pdf#1829]
Hi,

I'm new to Asciidoctor and I'm a bit confused about theme images. From within a java application, I'd like to generate a PDF file from an adoc file with a custom theme.

I can load the theme thanks to `uri:classloader`, it seems to work the same for fonts (I haven't tried), but for images the documentation says by default it's relative to `pdf-themesdir` (or `pdf-theme`) but I don't seem to manage to load any images like that.

I set `pdf-theme` to `uri:classloader:/demo/theme/demo-theme.yml`, the document is in `/demo`, all of that in the classpath (I haven't tried within a jar yet).

With the following theme:

```yaml
extends: default
header:
  height: 20mm
  recto:
    center:
      content: image:logo.png[]
page:
  background-image: image:logo.png[]
```

I get the following error messages and no images in the PDF file:

```
Nov 20, 2020 10:47:37 PM uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb resolve_background_image
WARNING: could not retrieve remote image: uri:classloader:/demo/theme/logo.png; undefined method `buffer_open' for #<URI::Generic uri:classloader:/demo/theme/logo.png>
Nov 20, 2020 10:47:39 PM uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb allocate_running_content_layout
WARNING: could not retrieve remote image: uri:classloader:/demo/theme/logo.png; undefined method `buffer_open' for #<URI::Generic uri:classloader:/demo/theme/logo.png>
```

So, is there a way to load images from within the classpath (and ultimately from within a jar file)?

While trying to figure all that out I also noticed the following "strange" behavior. The documentation says I can use `{docdir}` to load the image relatively to the document I'm converting. In that case with a theme like:

```yaml
extends: default
header:
  height: 20mm
  recto:
    center:
      content: image:{docdir}/theme/logo.png[]
page:
  background-image: image:{docdir}/theme/logo.png[]
```

The referenced image is the same, none are displayed in the PDF and I get 2 different error messages:

```
Nov 20, 2020 10:28:26 PM uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb resolve_background_image
WARNING: could not retrieve remote image: /Users/user/project/out/production/resources/demo/theme/logo.png; relative URI: /Users/user/project/out/production/resources/demo/theme/logo.png
Nov 20, 2020 10:28:30 PM uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb allocate_running_content_layout
WARNING: could not retrieve remote image: uri:classloader:/demo/theme/{docdir}/theme/logo.png; bad URI(is not URI?): uri:classloader:/demo/theme/{docdir}/theme/logo.png
```

For the first message (background image), `/Users/user/project/out/production/resources/demo/theme/logo.png` is really where the image is.
For the second message (header content), it looks like `{docdir}` is not recognized at all and is added directly relatively to the theme path.

What am I doing wrong?

**Comment by mojavelinux** [comment]
You're not doing anything wrong. This is a bug in the code when running on JRuby. It's incorrectly treating a classloader resource path (i.e., a path that begins with `uri:classloader:/`) as a remote resource. It should instead delegate to the built-in Ruby file loader since that file loader in JRuby understands how to handle a classloader resource path.

**Comment by mojavelinux** [comment]
The issues with `{docdir}` is probably a different bug in 1.5.3. I have fixed a ton of path resolution logic in the upcoming 2.0.0 release (master branch), so it's likely it has already been addressed. It definitely should not be treating an absolute path as a remote resource.

**Comment by mojavelinux** [comment]
> It definitely should not be treating an absolute path as a remote resource.

It seems like this is still happening when the theme file is loaded from the classpath. I've managed to make a reproducible test case, so I'm investigating.

**Comment by mojavelinux** [comment]
Aha. I see the problem. Looks like the same line of logic which is failing.

**Comment by mojavelinux** [comment]
I figured out the problem and submitted a PR. I don't intend to backport this to 1.5.x. However, if someone wants to do so, I'll review it and merge it when ready.

**Comment by mojavelinux** [comment]
In the end, this wasn't that big of a change. I think at least attempt to backport it to 1.5.x.

**Comment by sschuberth** [comment]
Can there possibly be some regression @mojavelinux? It seems despite me specifying a `pdf-themesdir` (as a `uri:classpath`), the `background-image` is being prefixed with a local path. [This code](https://github.com/oss-review-toolkit/ort/pull/6290/commits/8e2b413021485cfcec79e0ff948f34aa65b96416) triggers

> Dec 29, 2022 7:50:30 PM uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/converter.rb resolve_background_image
WARNING: title page background image not found or readable: C:/Users/SEBAST~1/AppData/Local/Temp/ort-PdfTemplateReporter-asciidoc8842694912548045678/uri:classloader:/images/ort.png

Hmm, or does `pdf-themesdir` (in contrast to `pdf-fontsdir`) not support `uri:classpath`? At least it's not explicitly mentioned in the [docs](https://docs.asciidoctor.org/pdf-converter/latest/theme/apply-theme/#theme-and-font-directories).
