### ISSUE TITLE
Invalid Page Break added to long code block leaving initial page blank

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#183]
Sorry the title isn't the best, hard to describe the behavior in one line.

I currently have a script that I'm including in my document's appendix section labeled Linpack CBTOOL Client Script (LinpackProvisioningVMs.py). If the script code is longer than a full page, the PDF generates a page break with a page just showing the title of the appendix section leaves the rest of the page blank and then on the following page inserts the code block.To reproduce:

````
[appendix]
==  Linpack CBTOOL Client Script (LinpackProvisioningVMs.py)
----
Super long code block that would fill more than one page
----
````

Output: 
![selection_210](https://cloud.githubusercontent.com/assets/8877333/8098850/f8a569e2-0fba-11e5-85e1-3daef64eec8a.png)

**Comment by mojavelinux** [comment]
Yep, this is indeed an issue and on my list. I'll schedule it for 1.5.0.

**Comment by mojavelinux** [comment]
I found the following written in the WORKLOG:

"don't advance to new page if listing isn't going to fit on a whole page anyway"

:)

**Comment by mojavelinux** [comment]
This turns out to be a pretty simple fix. Before we insert a page break, first check if the content height exceeds the height of the writable area of the page. If so, skip the page break.

**Comment by rlopez133** [comment]
This works perfectly! :) Just tried it :+1:

**Comment by mojavelinux** [comment]
Excellent! I'll merge!
