### ISSUE TITLE
Position footnotes (endnotes) at the bottom of the last page of the chapter

### ISSUE THREAD

**Issue by radekosmulski** [asciidoctor/asciidoctor-pdf#1833]
By default the footnotes appear after the text of a chapter. But it doesn't look that great. I think it would be much nicer if we could position them at the bottom of the last page of a chapter, keeping as much vertical space after the text and before the footnotes as possible.

Could I please ask how this can be done?

**Comment by mojavelinux** [comment]
This seems like a reasonable request. Before writing the footnotes to the last page of the chapter of a book or the end of the document for an article, we can dry run the footnotes to see how tall they are. If they're shorter than the available space on the page, the cursor should be moved down by that distance before writing them. That will make them effectively vertically aligned to the bottom.

**Comment by radekosmulski** [comment]
Thank you very much for taking this into consideration, really appreciate that 🙂

I am not sure where I could ask this, and I couldn't find any information on that anywhere, but is the positioning of all footnotes all lumped together at the end of the book possible right now? They seem to be numbered across chapters, which would indicate that might be the case, but I couldn't find any information on how to do this, how to move them all into a 'footnotes' section at the end.

(I am really not a big fan of where the footnotes begin directly after the text as it is right now, hence me asking - sorry for the bother, and thank you very much for all your help!)

**Comment by mojavelinux** [comment]
> I am not sure where I could ask this

The best place to ask general questions is either the mailing list at https://discuss.asciidoctor.org or the Gitter channel at https://gitter.im/asciidoctor/asciidoctor

> is the positioning of all footnotes all lumped together at the end of the book possible right now

No, it is not. When the doctype is book, the footnotes are per chapter. Many, many people asked for us to implement footnotes as chapter endnotes (since the converter cannot place them at the bottom of the page), so that is what we did.

**Comment by mojavelinux** [comment]
I've decided to backport this feature to the v1.6.x branch.
