### ISSUE TITLE
Color in tables

### ISSUE THREAD

**Issue by albcorare26** [asciidoctor/asciidoctor-pdf#1841]
Hi! I'm making a table, and I'd like to put a background color on it, but when I upload it to GitHub I can't see the color.
I used the following code:

```
|===
|Slack
{set:cellbgcolor:blue}
|===
```

**Comment by mojavelinux** [comment]
This converter does not supported named colors. You must use a hex value instead, such as `{set:cellbgcolor:#0000FF}`.

**Comment by albcorare26** [comment]
I used the code, but no color appeared in GitHub.

**Comment by albcorare26** [comment]
> This converter does not supported named colors. You must use a hex value instead, such as `{set:cellbgcolor:#0000FF}`.

I used the code, but no color appeared in GitHub.

**Comment by mojavelinux** [comment]
I don't know what you mean by "no color appeared on GitHub". Could you be more specific? Are you saying the PDF doesn't display properly on GitHub? Can you point to an example?

**Comment by albcorare26** [comment]
My question is: What if I view an adoc file in GitHub do I see the colors or does it have to be in PDF format to see the colors?


> I don't know what you mean by "no color appeared on GitHub". Could you be more specific? Are you saying the PDF doesn't display properly on GitHub? Can you point to an example?

**Comment by mojavelinux** [comment]
We have no control over how an AsciiDoc file is displayed on GitHub. It's going to display with whatever generic styles GitHub applies to documents. This has nothing to do with PDF or this converter. If you want to see the file rendered as a PDF on GitHub, then you can add the PDF to the repository.
