### ISSUE TITLE
Source code blocks lack bottom margin when followed by callouts

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#1844]
A block of source code followed by some text looks as follows:

![Bildschirmfoto 2020-12-19 um 01 28 45](https://user-images.githubusercontent.com/128577/102675476-cb354600-4199-11eb-922d-a7e9ea441e8f.png)

Note the ~ one line margin below the source block. If the source block uses callouts they immediately follow the block:

![Bildschirmfoto 2020-12-19 um 01 28 12](https://user-images.githubusercontent.com/128577/102675487-dd16e900-4199-11eb-95c4-f9272ecca50c.png)

I haven't found a theming setting to control that margin but I'd argue a reasonable default would be to apply the same `margin-bottom` of the code block when rendering the callouts.

**Comment by mojavelinux** [comment]
The lack of spacing here is intention to indicate correlation. However, you're not the first who has requested that it be possible to control it from the theme. In fact, that setting was introduced in the main branch by the fix for #1895.

**Comment by odrotbohm** [comment]
Ah, that makes sense. I've noticed that on the 2.0 dev builds that I've used in the meantime, the default actually looked less dense than in the screenshot I posted. Great to have to option available, though. Can confirm it works as expected when using a build from `main`. 👍

**Comment by mojavelinux** [comment]
Thanks for testing!
