### ISSUE TITLE
'a' adds bottom padding on row

### ISSUE THREAD

**Issue by Baerbeisser** [asciidoctor/asciidoctor-pdf#1845]
```
.Example
[cols="3,4"]
|===
.3+|text
|- |- |-

|text |-

a|interpreted text |-
a|interpreted text |-
|===

[cols="3,4a"]
|===
.3+|text
|- |- |-

|text |-
|text |-
|===
```

Creates
![different-lineheight](https://user-images.githubusercontent.com/22264628/102901824-5c443f80-446e-11eb-9d92-e472367239b1.png)

As far as i can tell, 'a' adds bottom padding to each row, to the first one with multiple rows and if applied globally to each new row.
While rows in asciidoctor (html) all render the same.
Is this intended?

**Comment by mojavelinux** [comment]
This is a known issue that is being addressed by #1515.
