### ISSUE TITLE
Add support for Ruby 3

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1848]
At the time Ruby 3 was released, some of the dependencies had version locks that prevented them from being installed on Ruby 3. This, in turn, prevented Asciidoctor PDF from being installed. Those dependencies have since been upgraded to support Ruby 3. Asciidoctor PDF now must be updated (and verified) to use them.

The goal of this issue is to update Asciidoctor PDF so it can be installed on Ruby 3 and verified to work on Ruby 3 through CI.

Start by focusing on the upcoming 2.0 release in the master branch. Then make a determination if this change can be backported to the 1.5 branch.

**Comment by mojavelinux** [comment]
I was able to upgrade the master branch to Ruby 3. However, this is going to be extremely problematic to support in 1.5.x because it requires upgrading Prawn and ttfunk, which in turn drops support for Ruby 2.3. We can't drop major Ruby versions in minor releases. So either we break the contract in 1.5.x, or we lock 1.5.x to Ruby 2 and instruct users of Ruby 3 to upgrade to 2.x. But that means getting 2.x out there. It's probably time to get serious about making that alpha.

**Comment by mojavelinux** [comment]
You can now use the code from the master branch to run Asciidoctor PDF on Ruby 3.

**Comment by slonopotamus** [comment]
> it requires upgrading Prawn and ttfunk, which in turn drops support for Ruby 2.3.

Can't you just declare that asciidoctor-pdf works with both versions of Prawn and let gem dependency resolution logic pick one that works on current Ruby?

**Comment by mojavelinux** [comment]
No, because it breaks many assertions in our test logic. Those aren't bad tests. It proves that ttfunk is not backward compatible. So we cannot make this jump until we release a major version.

**Comment by slonopotamus** [comment]
Well, then making a 2.x release makes sense. You're currently holding back almost a year of unreleased changes on `master` branch.

**Comment by mojavelinux** [comment]
Trust me, I realize that. It's tormenting the hell out of me right now. But I'm stretched very thin and I'm doing the best I can do.

**Comment by mojavelinux** [comment]
See upstream issue for rexml dependency: https://github.com/mogest/prawn-svg/pull/132

**Comment by mojavelinux** [comment]
This has been resolved in master by PR #1850.
