### ISSUE TITLE
Support for drop cap initial

### ISSUE THREAD

**Issue by johnsgp** [asciidoctor/asciidoctor-pdf#1849]
Is there a built-in way to do a [drop cap](https://en.wikipedia.org/wiki/Initial#Drop_cap) in AsciiDoctor or is the best way to make an image for each capital letter and insert it as use an image?  I was hoping not to have resolution issues which might arise from using a screenshot image of the letter in something like a PNG file.

This is for PDF output using [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml).

**Comment by mojavelinux** [comment]
I've transferred the issue.

**Comment by mojavelinux** [comment]
No, this is not something that's currently possible using Asciidoctor PDF out of the box. You can extend the converter to add support for it. As Guillaume mentioned, you can achieve it in the HTML output using custom CSS.

**Comment by johnsgp** [comment]
Thank you @Mogztter and @mojavelinux.  Happy New Year!  I'm happy for this issue to be closed as I mostly wanted to know for sure that there was no built-in solution. I was aware of the HTML solution from a Google search but I was getting nowhere with PDF after several hours of reading the manual and experimentation. I've since decided that the document I was working on was better done with MS Word, as it's a one-off with no future editing and very limited audience.

I haven't closed this issue myself in case you would like it to be added to a list of future features. Happy for you to close it.
