### ISSUE TITLE
Making a listing block text smaller

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#185]
I have some output that I want to make smaller so that it doesn't wrap and looks more like my gedit screen. I tried using the [small] attribute, and it does make it smaller but leaves [small] visible in the output and still wraps. I'm pretty sure I'm just not doing it right.

Question
1) Can I make listing block text smaller than what [small] does?
2) How do I get rid it showing [small] # # 

What my gedit screen looks like with asciidoc

![selection_212](https://cloud.githubusercontent.com/assets/8877333/8117675/a4527476-104f-11e5-9834-8d5aaf252b69.png)

Output looks like:
![selection_213](https://cloud.githubusercontent.com/assets/8877333/8117678/b259f71a-104f-11e5-808f-7c6c30896303.png)

**Comment by mojavelinux** [comment]
You'll be happy to know that this is another task that's on my list for 1.5.0. I just hadn't gotten around to filing an issue, but now that's done!

What I plan to do is implement a "shrink to fit" features (which happens to be supported in Prawn). Then, you'll be able to type:

```
[%autofit]
----
really long text that doesn't want to fit on a single line with the default font size, so we'll make it shrink to fit.
----
```

...and it won't wrap.

**Comment by mojavelinux** [comment]
It would really help when you file tickets if you can paste the raw AsciiDoc source in the issue in addition to whatever screenshots you add. Otherwise, I have to transpose the AsciiDoc visually to test it :)

**Comment by mojavelinux** [comment]
Btw, using small is a hack, so we want a solution that doesn't resort to that :)

**Comment by rlopez133** [comment]
Yes, sorry for not adding the asciidoc source on there.

**Comment by mojavelinux** [comment]
With the pull request I've proposed, you'll be able to set `autofit` either on the block:

```
[%autofit]
----
really long text that doesn't want to fit on a single line with the default font size, so we'll make it shrink to fit.
----
```

or on the document:

```
:source-autofit:

----
really long text that doesn't want to fit on a single line with the default font size, so we'll make it shrink to fit.
----
```

I'm not sure if `source-autofit` is the right attribute name. We might want `option-autofit` instead. I need to think about it.

**Comment by rlopez133** [comment]
Works like a champ! i've only tried the [%autofit] though.

**Comment by rlopez133** [comment]
I didn't realize this before, but when you autofit with a list, it is adding spaces between the text instructions and then the source block

example:
````
. Generate SSH keys on the Ceph Admin Server using `+ssh-keygen+` and copy the generated ssh keys to the managed hosts
+
[subs=+quotes]
----
# *ssh-keygen*
# **for HOST in ctrl{1,2,3} osd{1,2,3,4}; do ssh-copy-id $HOST; done**
----
+

. Update all managed hosts within the _/etc/hosts_ provisioning network entries. 
+
[subs=+quotes]
[%autofit]
----
# **for i in ctrl{1,2,3} osd{1,2,3,4}; do cat /etc/hosts | grep -i 20.0.0 | ssh $i "cat >> /etc/hosts"; done**
----
+
````
If you look at the output, you can see the gap difference

![selection_216](https://cloud.githubusercontent.com/assets/8877333/8135343/48685aa6-10fc-11e5-91fc-fa5a6c8a255e.png)

**Comment by mojavelinux** [comment]
Try putting all the block attributes in a single line. This may be a
limitation of AsciiDoc inside a list.

[%autofit, subs=+quotes]

**Comment by rlopez133** [comment]
Nope, same behavior.

**Comment by mojavelinux** [comment]
Oops, I was leaving behind space while doing the calculation. Just pushed a fix.

You are going to run into the problem that formatting the text causes the font size to shrink too much. I'll address the main cases of that scenario.

**Comment by rlopez133** [comment]
Yeah, I figured that formating the text causes the font size to shrink too much. I figured for those edge cases I'd probably not do the autofit. However, a nice feature would be something that does autofit up to a font size of X, if requires smaller font wrap.

Also, the fix you just made of removing that space really fixed it. It looks like this now:

![selection_218](https://cloud.githubusercontent.com/assets/8877333/8137586/010b6ec4-110a-11e5-91ce-d2b865cbb3c7.png)

**Comment by mojavelinux** [comment]
> I figured that formating the text causes the font size to shrink too much.

It's not too hard to fix. We're counting the XML tag as part of the line width, which is obviously not right. I just need to strip those out when measuring the line length.

> However, a nice feature would be something that does autofit up to a font size of X, if requires smaller font wrap.

Definitely. I'll add that in.

**Comment by mojavelinux** [comment]
> Also, the fix you just made of removing that space really fixed it.

\o/

**Comment by mojavelinux** [comment]
I've implemented the min font size and set a value in the default theme (`$base_font_size * 0.75`).

You can set the min font size either in the base:

```
base:
  font_size_min: $base_font_size * 0.75
```

or in the specific category:

```
code:
  font_size_min: $code_font_size * 0.75
```

**Comment by mojavelinux** [comment]
Should we reuse the `nowrap` option that already exists?

It's hard to say. On the one hand, we can't always honor `nowrap` (due to the min font size), so it's not technically the same. We might also want to implement `autofit` in the future in the HTML output. I think I may have convinced myself that `autofit` is a distinct option from `nowrap`. wdyt?

**Comment by mojavelinux** [comment]
I think that if `nowrap` is set, we should actually truncate the lines that overflow (if we want to truly honor the option specified). There may be cases when this is the desired behavior.

**Comment by mojavelinux** [comment]
> formatting the text causes the font size to shrink too much.

This is all that's left to fix.

**Comment by mojavelinux** [comment]
...and I think I've got it worked out. Stay tuned.

**Comment by mojavelinux** [comment]
I'm not very happy with the implementation. It should now correctly autofit no matter what content is in the code block. It also works even if you don't use a monospaced font. Rock solid.

**Comment by jinahya** [comment]
Is `[%autofit]` also supposed to work with `asciidoctor-maven-plugin`?
I'm using following configuration and it seems `[%autofit]` doesn't effect at all in both `html5` and `pdf` backends.
Thanks.
```xml
      <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <configuration>
          ..
        </configuration>
        <executions>
          ...
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>1.5.4</version>
          </dependency>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>1.5.0-alpha.11</version>
          </dependency>
          <dependency>
            <groupId>org.jruby</groupId>
            <artifactId>jruby-complete</artifactId>
            <version>9.0.4.0</version>
          </dependency>
        </dependencies>
      </plugin>
```

**Comment by jinahya** [comment]
@mojavelinux I found solution on https://github.com/asciidoctor/asciidoctor-pdf/issues/385.
Now I wonder is there any way for `html5` backend. Thank you.

**Comment by mojavelinux** [comment]
There's nothing like this for the html5 converter. It would need to be solved via JavaScript, so you could write some JavaScript and append it via docinfo. In that case, you'd need to add the "autofit" role (not option) to the block so that it gets passed through to the HTML.
