### ISSUE TITLE
running headers and footers per "region"

### ISSUE THREAD

**Issue by mark-summerfield** [asciidoctor/asciidoctor-pdf#1855]
I'm trying to use asciidoctor-pdf to make a book.
Most books can be viewed as having 7 regions:

1. Pre-contents forematter, e.g., title page, blank page, title/subtitle/author page, copyright page, dedication page [forematter]
2. Table of contents page(s) [toc]
3. Optional preface and/or introduction [prechapters]
4. Chapters [chapters]
5. Optional appendix(es) [appendixes]
6. Optional index(es) [indexes]
7. Optional colophon [endmatter]

Ideally the running headers and footers should be able to be specified per region, i.e.,
```
footer-prechapters: ...
footer-chapters: ...
```
etc.

**Comment by mojavelinux** [comment]
This is way beyond the scope of what this converter is designed to do. The logic for the running heading and footer is already complicated enough, and this would make it so tremendously complicated that it would simply be unmaintainable.
