### ISSUE TITLE
Special diacritic characters not rendered

### ISSUE THREAD

**Issue by geckolinux** [asciidoctor/asciidoctor-pdf#1856]
Hi there, I'm having trouble with an unusual character set that I need to use for diacritic marks together with a monospace font. There are some underlined characters, as well as some superscript characters. Here's the test word I'm using for this bug report:

`Testi̱ṉgⁱ`

It appears that the asciidoctor-pdf default Noto mono font does support these characters, and asciidoctor also appears to work with them, as the Atom editor asciidoctor preview also renders them correctly. But they are getting lost at some point in the PDF conversion. Thanks for the help!

![Screenshot_2021-01-07_08-47-31](https://user-images.githubusercontent.com/2692138/103901090-afe99680-50c6-11eb-8886-2a8eb10b354a.png)

![Screenshot_2021-01-07_08-50-45](https://user-images.githubusercontent.com/2692138/103901098-b415b400-50c6-11eb-823e-afab54b66f0a.png)

![Screenshot_2021-01-07_08-52-46](https://user-images.githubusercontent.com/2692138/103901107-b6780e00-50c6-11eb-8002-a83beedccabe.png)

![Screenshot_2021-01-07_09-02-06](https://user-images.githubusercontent.com/2692138/103901380-12429700-50c7-11eb-9fc9-be82686a07c9.png)

[test.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/5781996/test.pdf)

```
asciidoctor-pdf --version
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
You are correct that the default theme only links to fonts that support characters in commonly used character sets. If you need support for characters in other character sets, you need to use the default-with-fallback-font theme:

```
asciidoctor-pdf -a pdf-theme=default-with-fallback-font test.adoc
```

If that still doesn't provide the characters you need, then you'll need to use your own font. See https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc#fallback-fonts

**Comment by mojavelinux** [comment]
I checked and the default fallback font does not provide these characters. So you'll have to provide your own font. See https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc#custom-fonts

There are very few fonts that provide all the glyphs in Unicode, so when you start to use characters which are not as prevalent, you end up needing to load your own font. PDF doesn't provide fallback fonts for you like a web browser does. This is just an inherent limitation of the PDF format.

**Comment by geckolinux** [comment]
Hi @mojavelinux , thanks very much for your time and the fast response.

I don't understand how LibreOffice correctly generates a PDF with those same special characters, the only fonts that usually have trouble with them are Ubuntu Mono and Droid Sans Mono, as seen here:

![Screenshot_2021-01-07_19-30-19](https://user-images.githubusercontent.com/2692138/103960008-42b61f80-511f-11eb-954e-ff7e414846d0.png)

**Comment by mojavelinux** [comment]
It's because LibreOffice is taking fonts from the system and embedding them into the generated PDF. So it is doing exactly the same thing I'm talking about, it just happens to do it automatically for you. Asciidoctor PDF does not scan the system for suitable fonts to use because it's just not in scope for this application.

**Comment by mojavelinux** [comment]
If you want to use Droid Sans Mono or Ubuntu Mono, then you need to configure your theme to use them as described at https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc#custom-fonts
