### ISSUE TITLE
Feature request? Ability to change cell padding on a per-table basis

### ISSUE THREAD

**Issue by kwoot** [asciidoctor/asciidoctor-pdf#1866]
I can change the cell padding only in the theme file with table: padding: 0
Using padding=0 does not work in the table header itself.
[cols="1,1",frame=none, grid=none, padding=0  ]  
But would solve one of my layout problems (too much vertical whitespace in table)
Regards,
Jeroen Baten

**Comment by mojavelinux** [comment]
If this were to be implemented, it would be linked to block roles, as proposed in #483. We don't put theme properties in the AsciiDoc (it's a slippery slope of mixing content and presentation that roles were designed to mitigate, just like with CSS).

**Comment by kwoot** [comment]
I understand the wish to separate content from styling, but I can do many individual things in a document, like table: grid=None and border=None, or immage:: pdfwidth=x%. If it were to be implemented in a block role, that would work too. :-)

**Comment by mojavelinux** [comment]
The grid and border controls have always been there and are necessary to support for backwards compatibility. I don't want to deeper down that hole by adding more formatting attributes. As to whether grid and border can be controlled via a role, that's a different matter. It's possible in the HTML converter, but not currently possible in this converter. Though a strong case could be made that it should be possible.

**Comment by kwoot** [comment]
I understand. Thanks for your clarification. And thanks again for your great work.

**Comment by mojavelinux** [comment]
Keep an eye on #483. If we decide to split it into multiple issues, I'll link to them from there.

**Comment by kwoot** [comment]
Seems a good place. :-)
