### ISSUE TITLE
Can't install with Ruby 3.0

### ISSUE THREAD

**Issue by hexindent** [asciidoctor/asciidoctor-pdf#1870]
`gem install asciidoctor-pdf` returns
```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
```

`gem install asciidoctor` worsk fine

my env:
- macOS Mojave
- RUBYGEMS VERSION: 3.2.6
- RUBY VERSION: 3.0.0 (2020-12-25 patchlevel 0) [x86_64-darwin18]

**Comment by hexindent** [comment]
Solved by using the Pre-Release channel `gem install --pre asciidoctor-pdf`

Forgot the "Good Old" way after so long time. Hope it can get in the regular release channel.

**Comment by mojavelinux** [comment]
As stated in the README for the current release, Asciidoctor 1.5.x does not work with Ruby 3 (due to incompatible upgrades). See https://github.com/asciidoctor/asciidoctor-pdf/tree/v1.5.x#prerequisites. Ruby 3 is supported in the master branch and will be included in the Asciidoctor PDF 2 release.
