### ISSUE TITLE
Adding an arbitrary anchor to the table of contents

### ISSUE THREAD

**Issue by vonas** [asciidoctor/asciidoctor-pdf#1872]
Hello there. I would like to be able to add an anchor that's in my document to the automatically generated table of contents (`:toc:`). Normally only section titles are added to it, but having the option of making arbitrary anchors appear in there sounds like a great and flexible addition to me. This is already possible with the HTML backend (and potentially also various others) by adding a role `[.role]` to a paragraph and then modifying the output with e.g. an extension.

## Examples

Here's an example with normal sections in the table of contents (input and PDF output written as plain text):
```adoc
[#foo]
== Foo

== Bar

```
```
Table of Contents
Foo . . . . . . 1
Bar . . . . . . 1
```

And these are examples of how one could go about making arbitrary entries in the TOC:

```adoc
[#foo]
== Foo

[#bar]
[toc="What is the the purpose of Bar?"]
Bar is often used as a placeholder for demonstration purposes.
```
```adoc
[#foo]
== Foo

[#bar]
[.hide-title]
== What is the the purpose of Bar?
Bar is often used as a placeholder for demonstration purposes.
```

The former example would be some kind of directive that tells the converter that the anchor before or after it should appear in the table of contents (`toc`) and it's assigned a title text with `="..."`.

The latter example is the simplest as it just hides the section title in the output but still shows the section anchor and the title text in the table of contents. What could get problematic here is that not hiding the section title properly could lead to additional whitespace between paragraphs (because of section title margins).

There are certainly better ways to do this and I'd be happy to hear about any suggestions.

## My use case

I am writing a software specification in which I write each goal and requirement of the project in a single paragraph. Each of them get a unique identifier. They're written down like this: `*GO-0101* Make sure to ...`. I wrote a rudimentary extension that processes these lines, extracts the IDs and prepends an anchor in front of the paragraph.

Now this would suffice, but I also have another case where I am using the same ID format, and that's my User Stories. Each scenario gets it's own section title like this: `== *SC-0101* Downloading data from ...` a table with metadata and a rather long description of what's happening in that scenario. Because of this format each scenario has an entry in the table of contents, because the id and the short description is in the section title.

Consequently I would like other components of my specification that are identified by an ID to also appear in the table of contents, so that it looks like this:

```
Table of Contents
Goals
  *GO-0101* Make sure to ...  . . . . . . 1
User Storys . . . . . . . . . . . . . . . 1
  *SC-0101* Downloading data from ... . . 2
```

The only option I see currently is to write each goal into a section title. Unfortunately this would make the entire text bold, large and add a large margin around it. Trying to change the format of that section title with a role and a PDF theme for that role also changes the visuals in the table of contents. e.g. if I color the section title red the TOC entry also becomes red.

If my example above would work as displayed I could easily use a preprocessor extension to insert the `[toc="..."]` attribute in front of my paragraph with the same content as the paragraph:

```adoc
[#GO-0101]
[toc="*GO-0101* Make sure to ..."]
*GO-0101* Make sure to ...
```

---

I am posting this here because I am not a Ruby programmer and the codebase is so large and complex that I don't really want to mess things around without at least some guidance. I've skimmed through the code this evening, mainly [**converter.rb**](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor/pdf/converter.rb) and played around by installing the Gem locally, but nothing really came from that.

I'd be happy if someone could share their opinion about this with me and maybe give me directions towards how one could achieve this. Maybe even without changing the PDF converter! I'm rather new to AsciiDoc and especially Ruby, so I might not be informed enough to know about some options that might exist.

Thanks for reading!

**Comment by mojavelinux** [comment]
This is now covered by #2114.
