### ISSUE TITLE
Allow vertical and horizontal lines of table grid to be styled independently

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1875]
Currently, the vertical and horizontal lines of the table grid can only be controlled uniformly (same color, width, and style). Allow the theme to control the properties of each axis independently.

**Comment by mojavelinux** [comment]
The proposed solution is to allow the values for table_grid_* keys to be a matrix, where the first entry is the x-axis and the second entry is the y-axis.

**Comment by Hextremist** [comment]
FYI Dan: Your refactoring of my commit broke grid-color:
```
table:
  grid-color: [220,1,0]
```
This would previously (and after my commit) give a red grid.  After the refactoring it has become black.  The reason is that you removed val.size == 2 in theme_loader.rb here:
```
if key == 'table_grid_color' && ::Array === val && val.size == 2 # x,y
```

**Comment by Hextremist** [comment]
I see you already fixed it.  Good :)

**Comment by mojavelinux** [comment]
Yep! It turns out we were missing several important tests.
