### ISSUE TITLE
Add better sanity checking to the theme parsing

### ISSUE THREAD

**Issue by Hextremist** [asciidoctor/asciidoctor-pdf#1876]
When there is a simple error in the theme file, you will typically not get a meaningful error message.  For this theme file:

```
extends: default
table:
  grid-width: 2b
```
The error message you end up with is:
```
$ asciidoctor-pdf -a pdf-theme=theme.yml test.adoc
comparison of String with 0 failed
  Use --trace for backtrace
```
If would be nice to at least get something like
```
Theme variable table-grid-width is not numeric
```

**Comment by mojavelinux** [comment]
I like the idea, but I have no plans to implement it. I'm going to mark it as "tabled", which means it's a viable idea and someone would have to come forward to implement it if it's going to be considered.
