### ISSUE TITLE
Possible typo in Theme Guidline for ordered list

### ISSUE THREAD

**Issue by mcp292** [asciidoctor/asciidoctor-pdf#1884]
https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.4/docs/theming-guide.adoc#outline-list

I don't see any documentation for an outline list. Is it possible this was supposed to be "ordered list"?

**Comment by mojavelinux** [comment]
Outline list is a generic term I came up with to refer to both unordered and ordered lists. I'm going to be renaming this to just "list" in the future. Right now, that theme key configures both types of lists. Then there are some keys for configuring each type individually.

**Comment by mcp292** [comment]
Got it thanks!
