### ISSUE TITLE
I know this is weird but I think I found a bug but need some help zooming in.

### ISSUE THREAD

**Issue by kwoot** [asciidoctor/asciidoctor-pdf#1890]
Hi,

I am writing an update to an educational book. Syntax hightlighting with Rouge works, but not with Pygments or Coderay.
Running the Syntax highlighting test document with all three works and produces colored output so the colorizers seem to be installed correctly.
Trace gives no errors.
Is there some way to zoom in on the source of this weird behaviour?
Any and all tips greatly appreciated.

**Comment by mojavelinux** [comment]
Could you explain what you mean by this?

> Running the Syntax highlighting test document with all three works and produces colored output so the colorizers seem to be installed correctly.

Are you saying Asciidoctor PDF works fine with a test document, but not with your book?

Providing a project to look at would be helpful. It's very difficult to debug something by relying on a description of the problem alone.

**Comment by kwoot** [comment]
Hi! 

So, I am trying to get code blocks colored. I used the test code on the page describing syntax colouring. Installed all three libraries (Rouge, Pygments and Coderay) and ran the test doc with all three. For me this meant I decided I like the Coderay colouring the most.

So I switched on the colouring in my book and nothing happens. Same with Pygments. But when I configure it to Rouge it colourizes all the code blocks in my book (except the last shell $ always has a different color than the preceding shell $ in that block, but that is of probably a separate bug). I played around with a few of the attributes but there are many and it could also be that Coderay trips somewhere in my code but I don't have a clue how to zoom in on what is causing this.

I love to share my project with you but the book source is closed source so if you tell me how you would like to see my code I will make arrangements. Would giving you access to a private github repo work for you?

**Comment by mojavelinux** [comment]
> Would giving you access to a private github repo work for you?

Sure. I'll have a quick glance and share my observation about the configuration (or misconfiguration) so others may benefit in the spirit of transparency.

> So I switched on the colouring in my book and nothing happens.

This is still extremely vague. In order for me to help you, I need to know what exact steps you took. What changes did you make? Which guide are you following? etc.

> I decided I like the Coderay colouring the most.

Please note that the CodeRay integration is our least recommended choice. That's because it doesn't have support for styles like we see in both Rouge and Pygments. And the later two integrations have received a lot more attention. If you're choosing one because of colors, know that both Rouge and Pygments have a whole slew of colors to choose from. Run `rougify help style` to get a list.

**Comment by kwoot** [comment]
Okay. Simply for the purpose of not wasting your time I will try to have a better look at Rouge first and see if another theme works out better for me.

**Comment by kwoot** [comment]
I tested the Rouge with different themes. The test doc from https://asciidoctor.org/docs/asciidoctor-pdf/ shows clear and nice differences. Still, no joy on my end. I created a private repo with the source of my book and kindly ask you to have a look at it.

**Comment by mojavelinux** [comment]
When I tried it with your book, I was able to get all 3 syntax highlighters working. However, I think I understand why you're having difficulty. It's important to remember that Asciidoctor PDF does not integrate with the globally installed syntax highlighter. It integrations with the gem that is in the same Ruby installation as Asciidoctor PDF itself.

What I recommend is switching to Bundler to manage your gems. Here's how you do that.

0. (Optional) Use RVM to manage Ruby. Then you never have to worry about using `sudo`. See https://rvm.io.
   ```
   rvm use 2.7
   ```
1. Install Bundler (if you're not using RVM, then you need to prefix this command with `sudo`)
   ```
   $ gem install bundle
   ```

2. Create a Gemfile in root of the project to declare your Ruby dependencies (aka gems)
   ```ruby
   source 'https://rubygems.org'

   gem 'asciidoctor-pdf'
   gem 'coderay'
   gem 'pygments.rb'
   gem 'rouge'
   ```

3. Install the gems using Bundler:
   ```
   rm -f Gemfile.lock
   bundle --path=.bundle/gems
   ```

4. Prefix any command provided by a gem using `bundle exec`. For example:
   ```
   $ bundle exec asciidoctor-pdf -v
   ```

Now you can be sure you always have the right Ruby applications and libraries available to the project without relying on system paths and the complexities that come with depending on them.

---

p.s. I strongly recommend removing the blank lines you have added above the document title.

**Comment by kwoot** [comment]
Thank you so much for these tips. I followed your instructions and everything still works. 
At first still no difference. Then I copied the structure of the first part of the earlier mentioned test document to the front of my file.
And that did the trick! Thank you so much for helping me with this issue!
