### ISSUE TITLE
relax prawn-svg dependency to allow 0.32.0

### ISSUE THREAD

**Issue by mtasaka** [asciidoctor/asciidoctor-pdf#1891]
Currently `asciidoctor-pdf` has dependency for `prawn-svg ~> 0.31.0` https://github.com/asciidoctor/asciidoctor-pdf/blob/45db8c65056b4754ffac5e82ec57a5380f8498f6/asciidoctor-pdf.gemspec#L41 , which does not allow 0.32.0.

`prawn-svg` 0.31.0 was not compatible with ruby 3.0, ref: https://github.com/mogest/prawn-svg/pull/133 , to support ruby 3.0, this pull request was merged and new version 0.32.0 was released. Since the difference between `prawn-svg` 0.31.0 v.s. 0.32.0 is effectively only this change, I think making `asciidoctor-pdf` allow `prawn-svg` 0.32.0 is safe - and as to use ruby 3.0, `prawn-svg` 0.32.0 is needed, so I request to relax prawn-svg dependency.

**Comment by mojavelinux** [comment]
I can certainly make this update on the main branch. You should know, however, that while prawn-svg 0.31.0 was not compatible with Ruby 3, Asciidoctor PDF is currently applying a patch that makes it compatible. So you can currently use the main branch with Ruby 3.0. And when we upgrade, we'll want to remove that patch.
