### ISSUE TITLE
Use doc-title as pdf file name

### ISSUE THREAD

**Issue by ineffective** [asciidoctor/asciidoctor-pdf#1892]
Hi,

Lets say I'm converting `main.adoc` using the following:

```shell
asciidoctor-pdf.bat main.adoc
```

Lets say I do this for multiple documents in different directories. Is there a way to force `asciidoctor-pdf` to write resulting pdf files to `{doc-title}.pdf`? I can live with errors stemming from titles that can't be converted to proper paths (e.g. document is not generated).

Right now I have powershell script that extracts `{doc-title}` from `main.adoc` and passes it as --output-file parameter, but this is cumbersome plus I need this script in shell for Linux builders. Can `asciidoctor-pdf` do it on its own?

Ability to use the following:

```shell
asciidoctor-pdf.bat main.adoc -o '{doc-title}-{doc-version}.pdf'
```
would be ULTRA cool.

Thanks for an answer.

**Comment by mojavelinux** [comment]
This is not something the converter controls, but rather the core processor. This is roughly the same issue as asciidoctor/asciidoctor#1992. I have documented a way to do it in the following comment: https://github.com/asciidoctor/asciidoctor/issues/1992#issuecomment-801492006

**Comment by ineffective** [comment]
Thanks a lot, I thought this is related to `asciidoctor-pdf` specifically, since `html` documentation tends to start with `index.html` or similiar. Sorry for the noise.

**Comment by mojavelinux** [comment]
No worries. It prompted me to share that extension code, which hopefully helps others as well.
