### ISSUE TITLE
Allow theme to control top margin of callout list

### ISSUE THREAD

**Issue by irodori-git** [asciidoctor/asciidoctor-pdf#1895]
When I wrote Japanese text then first line of callout block render on over of source code block. I found this behavior could control `outline_list_item_spacing` key but I didn’t wish to change item spacing.

Conveniently, the soruce code has a task to create a `colist_margin_top` as a todo, so I used it.

**Comment by mojavelinux** [comment]
Since we only want this to impact the top margin of a colist that immediately follows a code (aka verbatim) block, I think the key should be `code_callout_list_margin_top` (indicating that the callout list is part of the code block).

**Comment by irodori-git** [comment]
I agree with your opinion. Thanks!
