### ISSUE TITLE
Only the last 2 callout marks of each line in a source block are turned into glyphs

### ISSUE THREAD

**Issue by andswitch** [asciidoctor/asciidoctor-pdf#1898]
If you have something like

```
[source,python]
----
def foo(x,y): # <1> <2> <3>
  return x + y
----
<1> bar
<2> baz
<3> quux
```

Then, in the source block itself, only callout marks 2 and 3 are turned into glyphs. In the callout list, nothing is wrong.

This is happening consistently in every source block for me. The pattern seems to be that only the last two callout marks of a line are turned into glyphs.

**Comment by mojavelinux** [comment]
Yep, it looks like there's an error in the match when there are spaces between consecutive callout numbers and there are at least three in the sequence.

Although it's not well documented, putting spaces between consecutive callout numbers in the source blocks is generally discouraged. If you remove them, the glyphs will be displayed properly.

I'll go ahead and fix this case and add a test for it.
