### ISSUE TITLE
NoMethodError while installing the GEM

### ISSUE THREAD

**Issue by amjadtbssm** [asciidoctor/asciidoctor-pdf#1903]
I am trying to install asiidoctor-pdf with the following command
`gem install asciidoctor-pdf`
But I get his error on the terminal. I am using windows 10 and Ruby v3.0 Please help
```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
```

**Comment by mojavelinux** [comment]
As stated in the README, Asciidoctor PDF 1.5.x is not compatible with Ruby 3. You'll need to either use Ruby < 3 or wait for the prerelease of Asciidoctor PDF 2 to become available.

https://github.com/asciidoctor/asciidoctor-pdf/tree/v1.5.x#prerequisites

**Comment by mcp292** [comment]
This is not reflected off github

https://asciidoctor.org/docs/asciidoctor-pdf/#prerequisites

**Comment by mojavelinux** [comment]
@mcp292 That's that README for the upcoming 2.0.x release line. The README for the 1.5.x release line can be found here: https://github.com/asciidoctor/asciidoctor-pdf/tree/v1.5.x#readme I've added a note to the README on the main branch to communicate this.

**Comment by mcp292** [comment]
Got it thanks!

**Comment by amjadtbssm** [comment]
> 
> 
> @mcp292 That's that README for the upcoming 2.0.x release line (which does have support for Ruby 3). The README for the 1.5.x release line can be found here: https://github.com/asciidoctor/asciidoctor-pdf/tree/v1.5.x#readme I've added a note to the README on the main branch to communicate this.

Thanks that'll do

**Comment by amjadtbssm** [comment]
> 
> 
> @mcp292 That's that README for the upcoming 2.0.x release line (which does have support for Ruby 3). The README for the 1.5.x release line can be found here: https://github.com/asciidoctor/asciidoctor-pdf/tree/v1.5.x#readme I've added a note to the README on the main branch to communicate this.

Can we add the gem ourselves to Ruby 3 without using the gem install command??? If so can 2.0.x release be added too?? Just a little curious.

**Comment by mojavelinux** [comment]
If you want to install the gem using the code from the master branch, please follow these instructions: https://github.com/asciidoctor/asciidoctor-pdf/blob/main/CONTRIBUTING-CODE.adoc#install-the-application-optional

**Comment by mcp292** [comment]
> Asciidoctor PDF 1.6.0 is now available with support for Ruby 3. See https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.6.0

Thanks for the heads up!

**Comment by amjadtbssm** [comment]
> Asciidoctor PDF 1.6.0 is now available with support for Ruby 3. See https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.6.0

Glad to hear it @mojavelinux , It's too nice to have Asciidoctor PDF in Ruby 3.
