### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by hyandell** [asciidoctor/asciidoctor-pdf#1908]
Hi Asciidoctor folk,

Looking at this file - https://github.com/asciidoctor/asciidoctor-pdf/blob/main/lib/asciidoctor/pdf/ext/prawn/coderay_encoder.rb - the licensing is GPL-3.0, which seems out of sync with the MIT licensing of Asciidoctor-pdf as a whole. (Earliest GitHub history here: https://github.com/asciidoctor/asciidoctor-pdf/commit/326e586c77c8c13b29df5339679133d819acd9cf#diff-4708f6bc776d6777ed49242a50fcf745256c2bc1c8757a49f5e62217d994deb2 )

It looks like it might have originally been this file https://github.com/prawnpdf/prawn-manual_builder/blob/1fdbb0beaa1b9d1ddf403640d70907d19c652d60/lib/prawn/manual_builder/syntax_highlight.rb - which seems to be under the Ruby tri-license of Matz's terms, GPL-2.0 OR GPL-3.0 ( https://github.com/prawnpdf/prawn-manual_builder/blob/master/COPYING ), as with the rest of the Prawn code included in the build.

Do you have any detail on the licensing situation here?

**Comment by mojavelinux** [comment]
That file is licensed differently. That does not affect the licensing of Asciidoctor PDF itself, which is MIT.

**Comment by mojavelinux** [comment]
This is covered in the NOTICE file. https://github.com/asciidoctor/asciidoctor-pdf/blob/main/NOTICE.adoc

If anything is missing from the NOTICE file, please point it out and I'll update it.

**Comment by hyandell** [comment]
Thank you Dan; apologies for missing the mention in the NOTICE.adoc file; I was digging into the Maven jar and failed to subsequently notice it on the GitHub source.

Just to be transparent; I work in the AWS OSPO and the file auto-flagged as an oddity given the jar's overall licensing. It's the dependency of a dependency of a dependency of a ... (you get the picture; usual Maven story :) ). Coincidentally, I'm a big fan of asciidoctor on the personal side, using it to generate clean html and pdf documents for gaming rules in a community I'm a part of; so it's kinda fun to have it show up at work :)

Putting myself in the shoes of a project owner, the encoder file would concern me; or wearing my inactive hat as an Apache legal committee member, if that feels less corporately self-interested than a company OSPO :) It's all wrapped up in the jar and gem files, making the copylefting unclear, and it feels like an odd inclusion license-wise given it's tying together asciidoctor-pdf (MIT), coderay (MIT), and Prawn (Ruby-licensed). 

[If relicensing was a topic of interest, the history here looks like it might be fairly simple even if Felipe is unavailable. The earliest version in GitHub is effectively the same as the current version in Prawn with the addition of some more colors (presumably the tokens are defined by asciidoctor). If no one but you has touched the file since, I think you could recreate the file with no licensing issue under Ruby-license.]

If this feels too pushy, let me know; I'm not intending to be a demanding pain in the derriere.

**Comment by mojavelinux** [comment]
Thanks for providing more context. I understand it's a challenging situation to analyze.

> I think you could recreate the file with no licensing issue under Ruby-license

Actually, I don't have to recreate the file. I just need to clarify that it's triple-licensed, since it always has been. The code came from Prawn, so it shares the Prawn license. I just didn't state that fully. I'll go ahead and do that.

**Comment by hyandell** [comment]
Awesome - thank you :)

**Comment by mojavelinux** [comment]
Thank you! It's really nice to have feedback from someone who is looking at things this closely.

**Comment by amznpurple** [comment]
FYI for any future watchers: Out of this chat this commit: https://github.com/asciidoctor/asciidoctor-pdf/commit/d3d96cf38c46db898cb7958001c393e42c5e11e1 seems to have been added.

**Comment by mojavelinux** [comment]
Thanks for pointing that out. I forgot to mention that I had made the update. I'll also apply it to the v1.5.x branch for completeness.
