### ISSUE TITLE
When reporting missing characters in a font, escape characters

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-pdf#1909]
When reporting a missing character in a font, that character could be a non-printable character like a zero-width-space.

This results in a warning message: 

```
Could not locate the character `​'
````

This leaves the user dazzled.

One idea could be to always print the missing character in escaped notation, or even skip the `​' if there is a non-printable character. 

An updated warning message could read: 

```
Could not locate the character `​' (\u200b)
```

**Comment by mojavelinux** [comment]
I want to point out that the error message has already been improved in the upcoming Asciidoctor PDF 2 release. It now prints:

```
Could not locate the character `' in the following fonts: YourFont
```

Adding the Unicode escape sequence seems reasonable as it will help to find the character in the font when you go looking for it.

> even skip the `​' if there is a non-printable character.

We wouldn't be able to tell what characters are printable or not as this is up the terminal application. However, printing the unicode escape sequence will make it clear that something is there.
