### ISSUE TITLE
Allow text-indent to be specified for paragraphs

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#191]
Long prose works tend to use leading indentation for paragraphs to visually separate them instead of a paragraph gap. Allow the text-indent property to be set on the prose key (or perhaps the paragraph key) in the theme.

The key part of implementing this feature is getting paragraph indentation to work so that it respects the line spacing (a known issue in Prawn).

**Comment by kongou-ae** [comment]
+1

**Comment by kongou-ae** [comment]
+1

**Comment by nathany** [comment]
This could also help cut down on the page count.

**Comment by oliviercailloux** [comment]
Any update on this? I think this is the number one limitation of asciidoctor for us right now, considering that I don’t know of any workaround to this, even ugly. Producing a one-page document is much more difficult when forced to vertically separate paragraphs. (And having no possibility to indent them effectively forces us to separate them.)

**Comment by jstasiak** [comment]
I'm currently using a fork that applies an updated version of #192 on top of current master, seems to do the job! The commit I'm running is https://github.com/jstasiak/asciidoctor-pdf/commit/80c5ce01c5d3819dbf1e042114d35a5c6ca0dedd if anyone's interested

**Comment by mojavelinux** [comment]
There are two challenges we have to solve in order to implement this correctly:

* our custom text formatter causes the indentation provided by Prawn to stop working
* the space between paragraphs needs to be removed if the text indent is set
* an option to override this behavior on a per-paragraph basis in cases when indentation is the wrong behavior

@rainboyan Have you been able to address these issues in your proposal?

**Comment by mojavelinux** [comment]
To be clear, the PR #192 is incomplete, which is why it has never been merged.

**Comment by mojavelinux** [comment]
> our custom text formatter causes the indentation provided by Prawn to stop working

This no longer seems to be the case.

> an option to override this behavior on a per-paragraph basis in cases when indentation is the wrong behavior

I think this should be handled in a follow-up issue.

> the space between paragraphs needs to be removed if the text indent is set

My proposal is to add prose_margin_inner to control the margin between paragraphs. If we try to reuse margin_top and margin_bottom, we introduce all sorts of formatting edge cases that will be too big to solve as part of this change.

**Comment by oliviercailloux** [comment]
It would be nice to be able (in supplement?) to indicate intent (“I want to indent paragraphs rather than vertically separate them”) rather than fine formatting details (how large should the margin be). 

I, for example, have no idea how much the margin should be if I choose to indent, and I’d be happy that Asciidoctor chooses reasonable defaults for me, once I have told it that I want “some” indent. (The intent being that the indentation should be visible but not huge, I suppose, and follow best practices known by typographers if any.) (Haha, intent of indent.)

**Comment by mojavelinux** [comment]
You will have to provide a value. You can use variables to grab a value from somewhere else in the theme, but Asciidoctor will not guess.

**Comment by oliviercailloux** [comment]
Sorry, I just realized you were talking about themes. That’s fine, I suppose.

(My point was about document writers, not theme writers. I suppose this is a different issue.)

**Comment by mojavelinux** [comment]
Yes, this is a theme issue. The writer won't do anything different. The publisher can now apply traditional paragraph indentation in the theme.
