### ISSUE TITLE
icon link not clickable

### ISSUE THREAD

**Issue by harveydov** [asciidoctor/asciidoctor-pdf#1915]
OS: Ubuntu 20.04
`asciidoctor` Version = 2.0.10 (Installed by `apt`)
`asciidoctor-pdf` Version = 1.5.4 (Installed by `gem`)

Adding the following:

`icon:download[link=https://rubygems.org/downloads/whizbang-1.0.0.gem, window=_blank]` as per https://docs.asciidoctor.org/asciidoc/latest/macros/icon-macro/ and running through `asciidoctor` provides the expected result of an icon that is clickable.

With `asciidoctor-pdf` the icon is visible but not 

`:icons: font` is located at the head of the doc

**Comment by mojavelinux** [comment]
This functionality has not yet been implemented in this converter. I've scheduled it for 2.0.0.

**Comment by harveydov** [comment]
Thanks @mojavelinux
