### ISSUE TITLE
Author metadata not set when no title page present and using author attribute

### ISSUE THREAD

**Issue by 1marc1** [asciidoctor/asciidoctor-pdf#1922]
When a document does not have a title page and the document attribute **author** is set, then the value of the attribute is not set in the metadata of the resulting PDF file.

If the attribute **authors** is set, then the value of the attribute is set in the metadata of the resulting PDF file.

Example 1:
```
:author: Kismet R. Lee
== Test document

Author name is not recorded in metadata.
```

Example 2:
```
:authors: Kismet R. Lee
== Test document

Author name is recorded in metadata.
```

Marc.

**Comment by mojavelinux** [comment]
This is a combination between a quirk in how Asciidoctor parses the document header when there is no doctitle and the logic for how the authors are resolved in this converter. Fortunately, I can see a way we can support both cases you cited.

As a side note, when you define a document header, you should always offset it by an empty line.

```
:author: Kismet R. Lee

== Test document

Author name is not recorded in metadata.
```

**Comment by 1marc1** [comment]
Thanks Dan, much appreciated as always!
