### ISSUE TITLE
Theme not applied with ruby 3?

### ISSUE THREAD

**Issue by mpretzer** [asciidoctor/asciidoctor-pdf#1925]
Hi,

I have a custom theme, which works fine with ruby 2. With ruby 3, the theme does not seem to be applied at all.

Dockerfile:
```
FROM ruby:alpine

WORKDIR /src
CMD sh

COPY theme /theme/
COPY asciidoctor-pdf /

RUN gem install rouge -v 3.6.0
RUN gem install asciidoctor-pdf --pre
```

Currently, this is
```
/src # /usr/local/bundle/bin/asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 2.0.15 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in
:UTF-8 ex:UTF-8)
```

`/asciidoctor-pdf` is just a frontend to add required args to the invocation, essentially:

```
/usr/local/bundle/bin/asciidoctor-pdf \
  -a pdf-fontsdir=/theme/Font \
  -a pdf-themesdir=/theme/Theme/ -a pdf-theme=kdo -a icons=font@ "$*"
```

`/theme` is:
```
/theme/
├── Font
│   ├── rotis-sans-serif-bold.TTF
│   ├── rotis-sans-serif-exbd.TTF
│   ├── rotis-sans-serif-italic.TTF
│   ├── rotis-sans-serif-light.TTF
│   ├── rotis-sans-serif-light_italic.TTF
│   └── rotis-sans-serif-normal.TTF
├── Icons
│   └── square.png
├── Templates
│   ├── kdo-footer-kurz.adoc
│   ├── kdo-footer-mit-cl.adoc
│   ├── kdo-footer.adoc
│   └── locale
│       └── attributes.adoc
└── Theme
    ├── KDO-Logo-RGB.png
    ├── digit-cluster-small.png
    ├── kdo-background-page.png
    ├── kdo-background-title.png
    ├── kdo-kurz-theme.yml
    ├── kdo-theme.yml
    └── kdo.rb
```

Running this, I get
```
/theme/Font/notoserif-regular-subset.ttf not found
  Use --trace for backtrace
```
but notoserif is not at all used in my theme.

Why isn't asciidoctor-pdf applying my theme?

**Comment by mojavelinux** [comment]
The version of Asciidoctor PDF you are using is substantially out of date (and also an alpha version). The current stable version is 1.5.4. Please upgrade and you will find that this likely fixes your error.

If you want to use a Docker container that has the correct version of Asciidoctor PDF already available, consider using the [Antora Docker container](https://github.com/asciidoctor/docker-asciidoctor).

**Comment by mpretzer** [comment]
Ok, I actually didn't realize that using `--pre` would install such an old version. I tried this as suggested in https://github.com/asciidoctor/asciidoctor-pdf/issues/1870#issuecomment-770520162 in order to get a version compatible with ruby 3.

The Dockerfile was just my way of trying to provide a concise description of my environment. My real deploy target is fedora 34, which ships ruby 3.

I think it might be a good idea, to add a more clear warning that as of now, no (current) asciidoctor-pdf gem is compatible with ruby 3. Would have saved at least me a couple of hours an might save you from further issues. I'd suspect, more people will be getting problems due to more linux distros switching to ruby 3.

Any ETA when 2.0 or maybe a preview will be available as a gem?

Thanks for an otherwise great product.

**Comment by mojavelinux** [comment]
> I tried this as suggested in #1870 (comment) in order to get a version compatible with ruby 3.

As I stated in that thread, the only way to get Ruby 3 support is to use the code from the main branch.

> I think it might be a good idea, to add a more clear warning that as of now, no (current) asciidoctor-pdf gem is compatible with ruby 3.

The warning is the first item under known limitations in the README. https://github.com/asciidoctor/asciidoctor-pdf/tree/v1.5.x#known-limitations I don't know how to be any more clear.

> Any ETA when 2.0 or maybe a preview will be available as a gem?

I can't give you a time, but I can say that I am treating it as a priority and will do it as soon as I can do it.
