### ISSUE TITLE
Honor pre-wrap role on monospaced phrase

### ISSUE THREAD

**Issue by CWempe** [asciidoctor/asciidoctor-pdf#1927]
As I pointed out in https://github.com/asciidoctor/asciidoctor/issues/4050 double spaces get reduced to single spaces.

@mojavelinux gave me a work aropund [here](https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/double.20spaces.20inline/near/237985263).

```
`06 {zwsp} S.05.10.B. {zwsp} 07`
```

But it would be nice to have this supported in general.

**Comment by mojavelinux** [comment]
> But it would be nice to have this supported in general.

What that entails is supporting the following:

```
[.pre-wrap]`06   S.05.10.B.   07`
```
