### ISSUE TITLE
Index pages do not follow "prepress" formats

### ISSUE THREAD

**Issue by realharry** [asciidoctor/asciidoctor-pdf#1929]
I use a theme file to set page attributes `margin-inner` and `margin-outer`. But, it seems that they are not honored by the generated index pages. I include the index as follows:

```
ifdef::backend-pdf[]
include::book/index.adoc[]
endif::[]
```

// index.adoc
```
[index]
= Index
```

**Comment by mojavelinux** [comment]
Thanks for pointing this out. I can confirm your observation. This appears to be a bug in Prawn's column box. It's not honoring the margins of the new page. I'll patch it.

**Comment by realharry** [comment]
Thanks very much, Dan!

Also, thanks so much for working on these asciidoc tools. I just published a kindle ebook ("Introduction to programming in Golang") as well as a paperback (that's how I discovered this issue). And, these are just fantastic tools! Thanks!

**Comment by mojavelinux** [comment]
You're welcome!

There are many people who help to make the Asciidoctor tool suite what it is. It's not just me. I encourage you to join the community chat at https://asciidoctor.zulipchat.com and let the other maintainers know you appreciate their work.
