### ISSUE TITLE
Scale images in PDF relative to its original size

### ISSUE THREAD

**Issue by tedour** [asciidoctor/asciidoctor-pdf#1933]
Now all options to scale images are relative to the width of the content area (https://asciidoctor.org/docs/asciidoctor-pdf/#image-scaling).
I'd like to have an option to scale the image based of it's original size (1300px => 100% of the width, 650px => 50% of the width for example, 325px => 25%, etc)
Prawn seem to be able to do it (https://prawnpdf.org/docs/0.11.1/Prawn/Images.html) with scale argument.

**Comment by mojavelinux** [comment]
This would entail implementing support for the `scale` attribute in this converter.

**Comment by mojavelinux** [comment]
I implemented this by adding support for the scale attribute (e.g., `scale=0.5`) as well as the `iw` units on the `pdfwidth` attribute (`pdfwidth=0.5iw`).
