### ISSUE TITLE
broken rendering of source blocks under certain conditions

### ISSUE THREAD

**Issue by wklaebe** [asciidoctor/asciidoctor-pdf#1934]
In https://github.com/asciidoctor/asciidoctorj-pdf/issues/61, I reported a problem rendering source blocks with Courier and a fix which modifies the packaged prawn gem. I also opened https://github.com/prawnpdf/prawn/issues/1207. Would that be the correct fix or should this be addressed in asciidoctor-pdf itself?

**Comment by mojavelinux** [comment]
Patching Prawn is not the right solution in this case. The method you're replacing issues a warning that the character cannot be encoded. Asciidoctor PDF happens to be suppressing this warning. As we have done elsewhere in Asciidoctor PDF, we need to use a fallback when a positioning character like the one used here cannot be rendered with an AFM font. I will look into it and see what we can do.

In the meantime, I strongly encourage you to use a TTF font. AFM fonts are severally hindered. You can still use Courier. However, you'd need to specify the path to font in TTF format.

**Comment by mojavelinux** [comment]
I recommend retracting the issue you filed against Prawn.

**Comment by wklaebe** [comment]
> I recommend retracting the issue you filed against Prawn.

Thanks, I closed that issue.

**Comment by mojavelinux** [comment]
I discovered the problem. When the converter creates the text for the indentation, it does not properly encode that text. So the problem does come from this converter, not Prawn.
