### ISSUE TITLE
{nbsp} is displayed in PDF as a smiley on iOS

### ISSUE THREAD

**Issue by pdorrestijn** [asciidoctor/asciidoctor-pdf#1938]
Hi,

To insert a blank page (for press purposes) using:

<<<

{nbsp}

The pdf generated by an openjdk:16 docker image looks fine on windows, but on iOS it shows a smiley?
I have my own theme with custom font not extending any basic theme.

What could be the problem here?

**Comment by pdorrestijn** [comment]
Please see the example
[nbsp-issue.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/6638699/nbsp-issue.pdf)

**Comment by pdorrestijn** [comment]
And the adoc
[nbsp-issue.adoc.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/6638710/nbsp-issue.adoc.pdf)

**Comment by pdorrestijn** [comment]
And hex view of the adoc
[nbsp-issue.adoc.hexed.it.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/6638726/nbsp-issue.adoc.hexed.it.pdf)

**Comment by pdorrestijn** [comment]
The smiley...
![Image from iOS](https://user-images.githubusercontent.com/3603626/121717375-63750d80-cae1-11eb-804f-dcd5e767a19b.png)

**Comment by mojavelinux** [comment]
It appears that the font (or fallback font) you are using has remapped `&#160;` to a smiley. I cannot think of any other possible explanation. Can you try with the built-in fonts to confirm that it solves the problem? If it does, then the problem is with the font. There's nothing the converter can do if that font is incorrect.

**Comment by mojavelinux** [comment]
You might also try `{zwsp}` instead, which is actually what you want because it should leave nothing behind.

**Comment by mojavelinux** [comment]
It's also sufficient to use `{blank}`, which also leaves nothing behind.

**Comment by pdorrestijn** [comment]
thnx, {zwsp} wokred nicely.
I suspect you're right on the fallback font mapping in iOS.
