### ISSUE TITLE
Inline image should inherit border applied to inline phrase

### ISSUE THREAD

**Issue by CWempe** [asciidoctor/asciidoctor-pdf#1939]
The converter does not currently support adding borders to inline images. While you can define a border on an inline role and wrap that around an inline image, the border does not get applied to the image.

Let's assume we define an inline role in the theme as follows:

```yaml
role:
  border:
    border-width: 1
    border-color: '000000'
```

Then apply the role to a phrase that encloses an inline image:

```
[.border]#before image:image-with-border.png[] after#
```

The border is applied to the text, but not the image. There is something currently preventing that from working properly. Presumably, the border is not being inherited

**Comment by mojavelinux** [comment]
I figured out how to support the role on the image itself as well as the inherited role. Previously, the code was not even checking for a role and propagating its associated properties in either case.
