### ISSUE TITLE
Spanning too many rows causes extended cell

### ISSUE THREAD

**Issue by 1marc1** [asciidoctor/asciidoctor-pdf#1946]
Thank you to everyone for their wonderful work on the Asciidoctor suite of software.

I have ran into an issue whereby the bottom of a table does not run flat across cells. The issue occurs when I specify a span of too many rows. Of course, I have to be specific and specify the correct number of rows for the span, however I found that when creating HTML output of the same table, the issue does not occur.

Here is what my table looks like:

```
[cols="1,1",frame=all,grid=all]
|===
<.<| Check <.<| Checking 
<.<| Observation <.<| Observing 
<.<| Impact <.<| Impacting 
1.5+<.<| Recommendation <.<| Step 1 
 <.<| Step 2 
 <.<| Step 3 
|===
```
And here is how it renders in PDF. Notice the uneven bottom of the table.

![image](https://user-images.githubusercontent.com/18713538/124483048-433d2380-dded-11eb-9118-5e353422ddab.png)

Given that the HTML output does not portray this issue, could the PDF conversion be updated to also tolerate the user mistake?

Thank you.

Marc.

**Comment by mojavelinux** [comment]
I don't want to defensively code for incorrect syntax. The correct solution is to fix the AsciiDoc source. (And even if we did decide to pursue a fix, the correct place would be core. A converter should not be responsible for validating or correcting the AsciiDoc source).

> Given that the HTML output does not portray this issue

This isn't entirely an accurate statement. In HTML, the bottom border is missing. So even in that case the error is evident.
