### ISSUE TITLE
"sectnumlevels" in Theme

### ISSUE THREAD

**Issue by ribase** [asciidoctor/asciidoctor-pdf#1951]
Hi There

Is there any possibility to provide the `sectnumlevels` in the theme.yml file?

We have the case that in all of our documents we only provide 2 levels of section numbers.

Otherwise we have to add this in every document which is very inconvenient and may lead to several mistakes.

Regards

**Comment by mojavelinux** [comment]
No, there is not. Section numbering is not something that's controlled by the converter, and thus not controlled by the theme. What I would suggest is passing this setting to the processor using whatever mechanism you're using to invoke it. For example:

```
asciidoctor-pdf -a sectnumlevels=2 document.adoc
```
