### ISSUE TITLE
Indent levels of headings?

### ISSUE THREAD

**Issue by jwittorf** [asciidoctor/asciidoctor-pdf#1952]
Hi, maybe I'm just missing the option, I'd like to format my different levels of headings not via font-size but via indention:

![image](https://user-images.githubusercontent.com/2085721/127302541-cb3e08b9-a94e-4dcf-98e7-7806e563ebf3.png)

Is that possible and if yes, what option do I need to use?

**Comment by mojavelinux** [comment]
That is not something the theming system supports.

What you can do is set indentation on the section body. https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.6.x/docs/theming-guide.adoc#keys-section

**Comment by mojavelinux** [comment]
In the future, please ask questions about usage and use cases in the community chat at https://asciidoctor.zulipchat.com. Thanks!

**Comment by jwittorf** [comment]
Okay, thanks! I've managed to get it done (for all headings) using a negative `section.indent` and a positive `page.margin`.

**Comment by mojavelinux** [comment]
Nice trick! I suppose we could mention that in the theming guide.
