### ISSUE TITLE
Cross-references in PDF have spaces

### ISSUE THREAD

**Issue by ivanmanning** [asciidoctor/asciidoctor-pdf#1957]
When I generate the PDF with asciidoctor-pdf, the cross-references have space between section/listing/figure/table numbers. 
No matter if I use :xrefstyle: short or :xrefstyle: full, the space is always present as you can see from the attached screenshots. 

![image](https://user-images.githubusercontent.com/76814717/129346386-10e6403c-c393-4b0b-bd08-80e88a4ec56d.png)

![image](https://user-images.githubusercontent.com/76814717/129346351-7af29c0d-705b-429a-9637-31ebeb17284a.png)

Am I doing something wrong here? 
The workaround is to add custom reftext to each referenced object (reftext="{chapter}.{counter:listing}") but when you have hundreds of cross-references, that simply takes time...

**Comment by mojavelinux** [comment]
This is the first I've ever heard of this issue. I can't see anywhere in the code where an extra space is added, nor do I know why it would be happening. And there are tests to ensure it doesn't. Are you sure you aren't passing the PDF that Asciidoctor PDF generates through some other tool?

Can you please share more information about your environment and/or provide a reproducible example?

> The workaround is to add custom reftext to each referenced object (reftext="{chapter}.{counter:listing}") but when you have hundreds of cross-references, that simply takes time...

I agree that would be totally impractical.

**Comment by ivanmanning** [comment]
Yes, I'm sure that I'm not using some other tool. And this is the command I use to generate the PDF: 

asciidoctor-pdf
  -a pdf-style=<path_to_the_theme>
  -a pdf-style=<name_of_the_style>
  -a pdf-fontsdir=<path_to_the_fonts>
  <path_to_the_file>

I'm working on a Windows 10 Home machine (v 10.0.19043).

Following is the version of asciidoctor that I'm using:  Asciidoctor 2.0.12 [https://asciidoctor.org], and the Runtime Environment (ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

And following is the version of asciidoctor-pdf that I'm using: Asciidoctor PDF 1.5.4 using Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Each chapter file has the following heading: 

:chapter: x
:sectnums:
:figure-caption: Figure {chapter}.
:listing-caption: Listing {chapter}.
:table-caption: Table {chapter}.
:sectnumoffset: y 
:leveloffset: 1
:bitmap_ext: png
:!figure-number:
:!listing-number:
:!table-number:

= Chapter title 

where x is the number of the chapter, and y is (chapter - 1). 

If I add attribute :xrefstyle: short and continue with asciidoctor's values for the figures/listings/tables, I end up with a cross-reference that has space between the chapter value and figure/listing/table as well as figure/listing/table captions themselves as you can see on the screenshot below. 

Following are examples of ID's

`[#listing_id_1]`
`[#table_id_1]`
`[#figure_id_1]`

![image](https://user-images.githubusercontent.com/76814717/129718182-69062125-84a9-45e4-861b-6e30669fe039.png)

If I remove that attribute and add my custom counters for figures/listings/tables, then the cross-reference is ok, but the issue with figure/listing/table captions is still present - they have a space in their values as you can see on the screenshot below.  

Following are the examples of my custom counters

`[#listing_id_1,reftext="{chapter}.{counter:listing}"]`
`[#table_id_1,reftext="{chapter}.{counter:table}"]`
`[#figure_id_1,reftext="{chapter}.{counter:figure}"]`

![image](https://user-images.githubusercontent.com/76814717/129718099-1434010e-4c7c-4af8-99eb-2da65be73f05.png)

**Comment by mojavelinux** [comment]
Aha, this is the problem:

```
:figure-caption: Figure {chapter}.
:listing-caption: Listing {chapter}.
:table-caption: Table {chapter}.
```

The captions are not intended to have numbers. That's not a supported use case and explains where the extra space is coming from. They can only contain the label. The number is something that is computed automatically.

If you need this feature, you will either have to extend the converter and customize it or wait for https://github.com/asciidoctor/asciidoctor/issues/2291 to be implemented. We can't provide support for it the way you are trying to do it.

**Comment by ivanmanning** [comment]
That explains it. OK, then I'll wait for [asciidoctor/asciidoctor#2291](https://github.com/asciidoctor/asciidoctor/issues/2291) to be implemented. 

Thanks, Dan.
