### ISSUE TITLE
Conum with background color

### ISSUE THREAD

**Issue by felipin85** [asciidoctor/asciidoctor-pdf#1960]
Hi,

I'm trying change my theme to define a callout num as circle filled with background color and the font with white property. But, I don't find how i can do. Is It possible?

Regards

**Comment by mojavelinux** [comment]
You can change the characters used for the callout numbers using the glyphs key. See https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.6.x/docs/theming-guide.adoc#keys-callout-numbers You'll want to set it to use the filled circled numbers for the font, starting from https://www.fileformat.info/info/unicode/char/2776/index.htm. That will allow you to set what looks like the background color, but it's really the font color. You can't set the color of the negative region, so it will be transparent.

In the future, please ask usage questions in the community chat at https://asciidoctor.zulipchat.com.

**Comment by felipin85** [comment]
Thanks for your response. I will ask in zulipchat because I have a stranger behaviour, only list 1 item when i put callout. If change the value to circle works fine.
Thanks
