### ISSUE TITLE
Question: Is the issue #1623 going to be rebased to the 1.6 branch?

### ISSUE THREAD

**Issue by IAmWebSA** [asciidoctor/asciidoctor-pdf#1969]
I am facing the same issue like:
[](https://github.com/asciidoctor/asciidoctor-pdf/issues/1623)
with the overlapping the table cells.

So I wanted to ask if you would be so kind to rebase this to 1.6.x Branch.

Best regards

**Comment by mojavelinux** [comment]
Instead of opening a new issue, please ask questions about project status in the #users/asciidoctor-pdf channel of the community chat at https://asciidoctor.zulipchat.com.
