### ISSUE TITLE
Error with bibliography

### ISSUE THREAD

**Issue by peter-jerry-ye** [asciidoctor/asciidoctor-pdf#1973]
Hello,

I'm using asciidoctor-pdf to generate a file containing bibliography. However the bibliography is not treated correctly.

Version:
Asciidoctor PDF 1.5.0.alpha.17.dev using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Here's my file:
```asciidoc
= HomeWork Week 1
:doctype: article

== Test

This is cited <<test>>.

And by <<something>>.

== Bibliography

[bibliography]

* [[[test]]] Peleg, Hila, Roi Gabay, Shachar Itzhaky, and Eran Yahav. “Programming with a Read-Eval-Synth Loop.” Proceedings of the ACM on Programming Languages 4, no. OOPSLA (November 13, 2020): 159:1-159:30. https://doi.org/10.1145/3428227.

* [[[something]]] This is something else
```

and the result:
![image](https://user-images.githubusercontent.com/16731997/135482570-24fc52fe-ad2e-47ee-84eb-00a5ec0504cc.png)

**Comment by mojavelinux** [comment]
Asciidoctor PDF 1.5.0.alpha.17.dev is not a supported version of Asciidoctor PDF. Please upgrade to Asciidoctor PDF 1.6.0. If you continue to experience a problem, you can reopen the issue.
