### ISSUE TITLE
pdf theme issues with footer and background images in prepress mode (1.5.3 to 1.6.0)

### ISSUE THREAD

**Issue by pdorrestijn** [asciidoctor/asciidoctor-pdf#1974]
For some unknown reason I experience issues with the pdf output when generating a prepress pdf.
I have alternating layouts (recto/verso).
The output is fine when I don't use prepress.

Issues:
- pdf gradle plugin 1.6.0
font-color is grey on empty page after each chapter (set in theme after each level 2 heading)
background images are not set on each page

- pdf gradle plugin 1.5.3 and 1.5.4
font-color is grey on empty page after each chapter (set in theme after each level 2 heading)

I use gradle version 7.0

I assume this is a bug?
I can't use the prepress output with these issues, can it be fixed?

**Comment by pdorrestijn** [comment]
Update: reason for the background images (svg) with plugin version 1.6.0 appears to be related to the svg library
Already noticed that this library is brittle or at least that svg's created with Inkscape are not garanteed to be displayed properly.
Previously I noticed this with object references in the xml and opacities.

**Comment by pdorrestijn** [comment]
Sample of a very simple svg which is correctly put in the background in prepress mode with pdf plugin versions 1.5.3 and 4, but not with version 1.6.0.

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   viewBox="0 0 816.37797 1145.1969"
   height="303mm"
   width="216mm"
   xml:space="preserve"
   id="svg2"
   version="1.1"
   sodipodi:docname="achtergrond-links-prepress.svg"
   inkscape:export-filename="C:\Users\Pim\Documents\JDriven\huisstijl\Achtergronden\JDriven_Brochure_2.png"
   inkscape:export-xdpi="1200"
   inkscape:export-ydpi="1200"
   inkscape:version="1.1 (c68e22c387, 2021-05-23)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:dc="http://purl.org/dc/elements/1.1/"><sodipodi:namedview
   pagecolor="#ffffff"
   bordercolor="#666666"
   borderopacity="1"
   objecttolerance="10"
   gridtolerance="10"
   guidetolerance="10"
   inkscape:pageopacity="0"
   inkscape:pageshadow="2"
   inkscape:window-width="3440"
   inkscape:window-height="1377"
   id="namedview17"
   showgrid="false"
   inkscape:zoom="15.327233"
   inkscape:cx="8.4490136"
   inkscape:cy="1119.9347"
   inkscape:window-x="-8"
   inkscape:window-y="-8"
   inkscape:window-maximized="1"
   inkscape:current-layer="svg2"
   units="mm"
   inkscape:pagecheckerboard="0"
   inkscape:document-units="mm"
   width="216mm" /><metadata
   id="metadata8"><rdf:RDF><cc:Work
       rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
         rdf:resource="http://purl.org/dc/dcmitype/StillImage" /></cc:Work></rdf:RDF></metadata><defs
   id="defs6" />



<rect
   style="fill:#fef1f3;fill-opacity:1;stroke:none;stroke-width:1.29549;stroke-linecap:square;stroke-dasharray:0.323876, 0.323876;paint-order:stroke fill markers"
   id="rect601"
   width="816.37799"
   height="49.133858"
   x="-1.3877788e-17"
   y="1096.063" /></svg>
`

**Comment by pdorrestijn** [comment]
so I'll downgrade to 1.5.4 but still would like a fix for honoring the font-color on the empty page after a chapter in prepress mode:
`footer:
  height: 47
  sectlevels: 1
  margin: 0
  verso:
    left:
      font-color: #E71939
      content: '*{page-number}* | *{chapter-title}*'
    right:
      font-color: #E71939
      content: '&#169; {docyear} Infuze'
  recto:
    left:
      font-color: #41415c
      content: '&#169; {docyear} Infuze'
    right:
      font-color: #41415c
      content: '*{chapter-title}* | *{page-number}*'
`

**Comment by mojavelinux** [comment]
I can confirm that this issue is resolve in 1.6.2. The provided SVG no longer impacts the rendering of the text.

I'm not sure I understand why you are using a background image for this purpose. It seems to be applying a background color to the footer. The PDF theme can already do that for you, and will add it only on pages where the footer is rendered.

> Already noticed that this library is brittle or at least that svg's created with Inkscape are not garanteed to be displayed properly.

The SVG library is very accurate to the SVG 1.1 specification, and the author works very hard on it. Please don't toss around accusations. When you save SVGs from Inkscape, you should create an optimized SVG so it does not have non-compliant information in it. That will ensure that you get the result you expect in the future.
