### ISSUE TITLE
AsciiDoc - Increase fontsize of the title

### ISSUE THREAD

**Issue by Johan1974** [asciidoctor/asciidoctor-pdf#1975]
Hello,

Is there a way to increase the fontsize of my document title without using the header functions. 
The thing is when using h1 it is also used within the toc and that is what i do not want. 

I was surprised there is no easy method for only increasing the font size of a specific text. 

Johan

**Comment by mojavelinux** [comment]
When the title page is enabled (doctype=book or title-page attribute is set), the font properties of the document title is controlled by the [title-page-title key](https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.6.x/docs/theming-guide.adoc#key-prefix-title-page-title) in the theme file. 

When the title page is not enabled (doctype=article and the title-page attribute is not set), the font properties of the document title is controlled by the [heading-h1 key](https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.6.x/docs/theming-guide.adoc#key-prefix-heading-level) in the theme file.

The document title is never shown in the TOC.

In the future, please direct usage questions to the `#users/asciidoctor-pdf` stream of the community chat at https://asciidoctor.zulipchat.com.
