### ISSUE TITLE
Table of content is mixed up with the beginning of the document

### ISSUE THREAD

**Issue by matdere** [asciidoctor/asciidoctor-pdf#198]
The first chapter is mixed up with the first chapter of the document. 

![image](https://cloud.githubusercontent.com/assets/608703/8165412/84ef1942-1390-11e5-899d-3bf843d6df9d.png)

PDF viewer is the standard mac os X viewer.

**Comment by mojavelinux** [comment]
This has been fixed for the 1.5.0.alpha.8 release (this week) by https://github.com/asciidoctor/asciidoctor-pdf/commit/8b83f7681b2373e2dd9b8b5985f833b9533bb4ed.

**Comment by matdere** [comment]
Sorry for that ! Keep going @mojavelinux  ! This rocks !

**Comment by mojavelinux** [comment]
:+1:
