### ISSUE TITLE
Upper-case hex digits in character references are not recognized

### ISSUE THREAD

**Issue by etihwnad** [asciidoctor/asciidoctor-pdf#1990]
Example using &Omega;:

* `&Omega;` does not work (as expected)
* &#937; (`&#937;`) works (as expected)
* &#x003a9 (`&#x003a9`) works (as expected, since https://github.com/asciidoctor/asciidoctor-pdf/issues/486)
* &#x003A9 (`&#x003A9`) does not work (but should)

**Comment by mojavelinux** [comment]
The reason for the restriction was to try to encourage consistency and slightly improve performance. However, since Asciidoctor core allows the letters to be uppercase, it's reasonable to assume that Asciidoctor PDF should as well. Therefore, we can proceed with this change.
