### ISSUE TITLE
How to put an image before a chapter name in a page of a book

### ISSUE THREAD

**Issue by diarmuidkieran** [asciidoctor/asciidoctor-pdf#1993]
I have a book which includes various adoc files, each of which are basically chapters. On the top of each file, I want to place an image BEFORE the chapter name. Basically, the image will be some sort of fancy looking number "1" icon for chapter 1, "2" for chapter 2 etc.

I tried the following putting an image containing the icon (in the appropriate top left corner location) as a background image at the top of the adoc file (before the "= Chapter 1" text), as follows:

`:page-background-image: image:Chapter_1_background_image.png 

== Introduction`

This has no effect, the image does not show up. Is there anything wrong with my syntax ? 

Or is there an alternative, better way to do this ?

**Comment by mojavelinux** [comment]
This can be accomplished using an extended converter. The method you will want to override is `layout_chapter_title`.

Information about how to write an extended converter can be found in the docs at https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/modules/extend/pages/define-converter.adoc (soon to be located at https://docs.asciidoctor.org).

Begin by defining the converter as follows:

```rb
class MyPdfConverter < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def layout_chapter_title sect, title, opts
    if (image_path = sect.attr 'image')
      image_attrs = { 'target' => image_path, 'pdfwidth' => '1in' }
      image_block = ::Asciidoctor::Block.new sect.document, :image, content_model: :empty, attributes: image_attrs
      convert_image image_block, relative_to_imagesdir: true, pinned: true
    end
    super
  end
end
```

Here's an example of how the image is defined in the AsciiDoc source:

```
= Document Title
:doctype: book
:imagesdir: images

[image=tux.png]
== First Chapter

content

[image=tux-note.svg]
== Last Chapter

content
```

You may find this API helpful when writing the custom logic: https://www.rubydoc.info/gems/asciidoctor-pdf/Asciidoctor/PDF/Converter

Save this file as `pdf-converter.rb`. Then, load it when running Asciidoctor PDF as follows:

```rb
asciidoctor-pdf -r ./pdf-converter.rb book.adoc
```
