### ISSUE TITLE
Horizontal description lists ignore theme's term font color

### ISSUE THREAD

**Issue by BrianEmberling** [asciidoctor/asciidoctor-pdf#1994]
It seems like description lists which use [horizontal] ignore the theme's font color for the term.
In the example below (and attached), the horizontal descriptions keep the default (black) font color,
but the non-horizontal ones pick up the theme's green font color.
(using asciidoctor-pdf 1.6.2)

**Theme:**
extends: default
description_list:
  term_font_color: 0fff00

**ADOC file:**
= horizontal descriptions ignore color
:doctype: article

== Header1

[horizontal]
DEF1::  here is a defintion for some stuff
DEF2::  here is a defintion for some stuff

some text

DEF1::  here is a defintion for some stuff
DEF2::  here is a defintion for some stuff

![bug](https://user-images.githubusercontent.com/28990171/154588295-25663061-2222-4120-8a85-077705fec5af.jpg)

[bug2.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/7966649/bug2.zip)

**Comment by mojavelinux** [comment]
Thanks for pointing this out. I added support for the font color and text transform. I did not add support for font size because that can really mess up the layout in this context.
