### ISSUE TITLE
Cross references pointing to files that contain tags do not function properly

### ISSUE THREAD

**Issue by Patrick-LuoYu** [asciidoctor/asciidoctor-pdf#1998]
Assume the following files:

|--chapter.adoc
|--chpaters
    |--chpater-1.adoc
    |--chapter-2.adoc
    |--chapter-2
        |--first-steps.adoc

chpater.doc

```asciidoc
= Book Title
:doctype: book

include::chapters/chapter-1.adoc[]

include::chapters/chapter-2.adoc[]
```
chapter-1.adoc

```asciidoc
== Chapter 1

We cover a little bit here.
The rest you can find in <<chapters/chapter-2.adoc#_chapter_2,Chapter 2>>.
```

chapter-2.adoc

```asciidoc
== Chapter 2

Prepare to be educated.
This chapter has it all!

To begin, jump to <<chapters/chapter-2/first-steps.adoc#_first_steps,first steps>>.


// tag::test[]

test

// end::test[]

<<<

include::chapter-2/first-steps.adoc[]
```

first-steps.adoc

```asciidoc
=== First Steps

Let's start small.

include::../chapter-2.adoc[tags=test]
```

If we convert `chapter.adoc` into a PDF file, the cross reference `<<chapters/chapter-2.adoc#_chapter_2,Chapter 2>>` in `chapter-1.adoc` is faulty. However, if we remove the tag statements in `chapter-2.adoc` or remove  `include::../chapter-2.adoc[tags=test]` in `first-steps.adoc`, everything works fine.

Please help resolve the problem. Thanks!

**Comment by mojavelinux** [comment]
The remapping of interdocument xrefs across includes does not work if the include uses tags. These two features are not compatible. That is a limitation of Asciidoctor itself, not Asciidoctor PDF. And I don't know of any way these two features can be used together as tags can be anywhere in the file and we cannot determine from that if the xref points within the same document.

To work around the problem, you need to include the file without using tags. That might mean breaking up the file into smaller parts. Currently, that is the only solution I can offer.

As this issue does not pertain specifically to Asciidoctor PDF, I will be closing it.

**Comment by Patrick-LuoYu** [comment]
Thank you for looking into this issue. I will post this issue to Asciidoctor to see whether there is a solution on the Asciidoctor side.

**Comment by mojavelinux** [comment]
Sorry if I wanted clear. These two features cannot be used together in Asciidoctor, which means Asciidoctor PDF as well.

> we cannot determine from that if the xref points within the same document.

That's not going to change.

**Comment by Patrick-LuoYu** [comment]
Sorry, I'm not quite sure whether this is an intended behavior of Asciidoctor. Logically, if a tagged region of a file is included in another file, xrefs pointing to the former file should not become broken, because the former file is not changed except that tags have been added to it. Maybe the xref should be allowed to become broken only when a) the xref points to the tagged region; b) the tagged region is somehow filtered out and does not exist in the final assembly file (`chapter.adoc`).

It will be excellent if this issue can be resolved in future versions!

**Comment by mojavelinux** [comment]
I'm sorry to disappoint you, but I don't see how this can be implemented. If you know of a way, feel free to submit a PR to Asciidoctor to show me how it's done. But logically, it cannot be supported for the reasons I have cited. The preprocessor does not know anything about the document structure. Therefore, if you include a file partially, we have no way of knowing whether what got included contains the target anchor that the xref points to. So we have to assume it's not there.
