### ISSUE TITLE
How to support Emoji？

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-pdf#1999]
I use [asciidoctor/asciidoctor-maven-plugin](https://github.com/asciidoctor/asciidoctor-maven-plugin) to generate PDF document.

I write the AsciiDoc documents in Chinese, so I configure the theme and the fonts. But when I use Emoji in the document and generate the PDF document, it throws some warnings:

```
...
[INFO] asciidoctor: WARN: Could not locate the character `😜' in the following fonts: Source Han Serif SC, Source Han Serif SC
...
[INFO] asciidoctor: WARN: Could not locate the character `😂' in the following fonts: Source Han Serif SC, Source Han Serif SC
...
```

The document is:  https://github.com/diguage/jdk-source-analysis/blob/master/docs/preface.adoc 

![image](https://user-images.githubusercontent.com/2121467/155918211-9d465af2-9af3-4a42-b0a1-a2d95775c9ea.png)

The Example Repo: https://github.com/diguage/jdk-source-analysis

**Comment by mojavelinux** [comment]
Please direct questions about usage to the asciidoctor-pdf stream in the project chat at https://asciidoctor.zulipchat.com. I'd be happy to follow-up on your question there. The issue tracker is now reserved for verified bug reports and new feature requests.

**Comment by brunchboy** [comment]
Zulip is in beta for the ability to make streams public, without login, which will solve the external search issue. Until then, you can search inside the Zulip client.

**Comment by mojavelinux** [comment]
@diguage As the maintainer of this project and the lead of the Asciidoctor community, I am asking you to honor my request to ask questions in the Zulip-based chat. That's the direction we have decided to go in this community to make it more sustainable and engaging for users. You can learn lots of tips from what other people share there, even more so than from the issue tracker. Given that I'm the one who handles the bulk of the issues, it also makes it a lot easier for me to do my job so I have more time to work on the software.

To address the concern you raised about searching, you'll find that the Zulip interface provides both a topic and full text search across all project streams. The search returns very relevant results, far more accurate than what a generic search engine can provide. As James mentioned, we will enable public archives as soon as Zulip enables them on zulipchat.com. We expect that to happen soon. Even then, I think you'll get better results using the Zulip interface.

**Comment by diguage** [comment]
@mojavelinux Thank you very much. Asciidoctor is a great and complex project. Thank you for creating such a wonderful project and toolset.

I respect your request and have sent the question to Zulip.

**Comment by mojavelinux** [comment]
Thanks! I look forward to chatting with you there.
