### ISSUE TITLE
Truncate toc entry if its length exceeds a single line

### ISSUE THREAD

**Issue by rmannibucau** [asciidoctor/asciidoctor-pdf#200]
Depending the text

```
num_dots = ((bounds.width - (width_of %(#{sect_title}#{sect_page_num}), inline_format: true) - spacer_width) / dot_width).floor
```

can be negative.

In this case the next line (1571 in converter.rb):

```
%(#{(@theme.toc_dot_leader_content || DotLeaderDefault) * num_dots})
```

will fail with

```
Caused by: org.jruby.exceptions.RaiseException: (ArgumentError) negative argument
```

Would be great to
- prevent negative size
- print a message (warning?)

**Comment by mojavelinux** [comment]
Zonk! I never thought of that case. This will definitely make a great test case.

I did some research on this and determined that a quick fix is to just set the number of dots to 0 if the calculated result is less than zero.

However, the title text will still wrap. So the next fix is to only allow the title to consume a single line.

However, then the text could still overlap the page number. The final fix is to prevent the title text from expanding past a fixed column (better that it is fixed I think for consistency). Perhaps something like 80 or 90% of the page. That should leave enough room for the page numbers. In this case, the dots get a bit off, but I don't think that's a huge concern atm.

**Comment by mojavelinux** [comment]
I think I'll move forward with (a) and (b) right away so that the processor isn't crashing. Then, I'll try to arrive at a nice solution for (c).

**Comment by mojavelinux** [comment]
I've done (a) in master just so that you can move forward.

**Comment by rmannibucau** [comment]
personally I just used a max between computed number and 0. If it is not enough wrapping or whatever solution makes rendering less nice IMO and needs "writer" works. That said if you manage to get a nicer default it is really better.

**Comment by mojavelinux** [comment]
:+1: 

Btw, thanks for pointing this out!

**Comment by graphitefriction** [comment]
@mojavelinux Per the release notes for Alpha 8, it says this issue is closed ... but it looks like it is still open?

**Comment by mojavelinux** [comment]
This is only partially addressed. A quick fix is in place, but there's still work to do to make it cover all cases in the proper way.

**Comment by mojavelinux** [comment]
The milestone should be set to 1.5.0.beta.1 for now.

**Comment by mojavelinux** [comment]
I've decided to split the remaining changes off into #1152 and #1153. I've also added a test to cover the fix that was made in this issue. Therefore, this issue can now be closed.
