### ISSUE TITLE
The width of the inline image is error.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-pdf#2000]
I use [asciidoctor/asciidoctor-maven-plugin](https://github.com/asciidoctor/asciidoctor-maven-plugin) to generate PDF document.

I write the AsciiDoc documents in Chinese, so I configure the theme and the fonts. But when generate the PDF  document, the width of the inline image is error.

The document is:  https://github.com/diguage/jdk-source-analysis/blob/master/docs/preface.adoc 

```
[cols="2*^",frame=none]
|===
| image:images/alipay.png[title="支付宝", alt="支付宝", width="90%"] | image:images/wxpay.png[title="微信", alt="微信", width="90%"]
|===
```

![image](https://user-images.githubusercontent.com/2121467/155918604-ea97074f-a42a-4208-92d2-50314c2e4dae.png)

![image](https://user-images.githubusercontent.com/2121467/155919088-861e96f0-743b-40e6-83ad-c0d872b38845.png)

The Example Repo: https://github.com/diguage/jdk-source-analysis

```bash
# 1. download the fonts
$ bash cfg/fonts/download-fonts.sh

# 2. Run the command to generate PDF document
$ mvn package 
```

**Comment by mojavelinux** [comment]
pdfwidth is the preferred attribute to control with width of an image in PDF. The width attribute is not meant to be used in this context and its interpretation of a percentage value varies widely between output formats.

Also note that inline images in a table cell are not well supported. It's better if you use a block image in an AsciiDoc table cell as the README suggests.

In the future, please direct questions about usage to the asciidoctor-pdf stream in the project chat at https://asciidoctor.zulipchat.com. I'd be happy to work through the issue with you there.
