### ISSUE TITLE
Use scratch document to compute extent for content block in primary document

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-pdf#2003]
The converter needs to compute a block's boundaries, that is, its extent, so it can determine where to:

* start a block
* draw a background under the block (if applicable)
* draw a border around the block (if applicable)

### Existing logic

Currently, the converter only computes a block's effective height from the top of the page in a scratch document. Since this logic only guarantees that the height is accurate when computed from the top of the page, it requires blocks which don't fit on the current page to be advanced to the next page (i.e., keep together). Still, even when it appears the block can fit on the current page, the margin behavior may be different, resulting in the block being rendered incorrectly. Furthermore, providing only the height of the block makes the boundaries of the background and/or border more complicated to compute, debugging harder, and keep together behavior mandatory.

### New logic

Instead of determining a block's effective height, the converter should compute a block's extent. The extent will always start from the same place in the scratch document as it will start from in the main document.

The extent stores:

* the start page and cursor
* the end page and cursor
* the current page and cursor

The extent also provides helper methods to query the state, such as whether the extent (and hence block) is only a single page or whether it must be advanced to a new page. The new logic should be able to accommodate both breakable and unbreakable blocks.

Here's a summary of the new logic:

* rename `keep_together` DSL method to `arrange_block`
* always set keep together unless cursor is at top of page (changing this behavior will be addressed in a separate issue)
* run `dry_run` with the provided proc to compute the extent of the block in the scratch document
* if `keep_together` is set: convert the block starting from the top of a new page until the end of the page is reached; if the block spills over to another page, start over again from the cursor location in the main document*
* if cursor is at top of page: convert the block fully starting from the top of a new page in the scratch document
* if cursor is not at the top of the page: convert the block starting from the cursor location in the main document until the end of the page is reached; if the block spills over to another page, and the previous page is empty (or only has the block caption), start over again from the top of the page
* compute the extent of the block in the scratch document
* if the block needs to be pushed to a new page, advance the page in the main document
* use the scratch extent to compute the extent in the main document
* run the proc again to convert the content of the block, this time passing in the extent for it to use to draw the background and/or border

To halt conversion of the block early, the converter will raise the `StopIteration` exception provided by Ruby. This allows the dry run process to avoid doing unnecessary work.

(*) Currently, if a block must be split because it doesn't fit on a single page, it's still advanced to the start of the next page. In this situation, the block should start from the cursor. This avoids a big gap at the bottom of the current page when the block must be split anyway.

This issue replaces #789.

**Comment by graphitefriction** [comment]
As part of this issue, we need to update the dev guide to explain how `arrange_block` works.

For clarity, the new logic applies to all delimited blocks (listing, quote, sidebar, open, etc.) and admonitions.

Also note that if a cell in a table is longer/larger than an entire page, it can't be kept together. However, the new logic will enable us to keep together a table and it's caption, but we'll address that fix in another issue.

**Comment by mojavelinux** [comment]
Here are the test cases we have so far:

<details>
<summary>Asciidoctor::PDF::Converter#arrange_block</summary>
<pre>
Asciidoctor::PDF::Converter#arrange_block
should paint background over extent of empty block
unbreakable block
  at top
    should keep block on current page if it fits
    should split block taller than page across pages starting from page top
    should split block taller than several pages across pages starting from page top
  below top
    should keep block on current page if it fits
    should advance block shorter than page to next page to avoid breaking
    should advance block shorter than page and with caption to next page to avoid breaking
    should advance block shorter than page and with caption that wraps to next page to avoid breaking
    should split block taller than page across pages starting from current position
    should restart dry run at current position once content exceeds height of first page
    should restart dry run at current position once content exceeds height of first page inside nested block
    should advance block taller than page to next page if only caption fits on current page
    should advance block taller than page to next page if no content fits on current page
    should preserve indentation across pages in scratch document
breakable block
  at top
    should keep block on current page if it fits
    should split block taller than page across pages starting from page top
    should split block taller than several pages starting from page top
    should split block across pages that contains image that does not fit in remaining space on current page
    should split block across pages that contains image taller than page that follows text
  below top
    should keep block on current page if it fits
    should advance block shorter than page to next page if only caption fits on current page
    should advance block shorter than page to next page if no content fits on current page
    should advance block taller than page to next page if only caption fits on current page
    should advance block taller than page to next page if no content fits on current page
    should split block shorter than page across pages starting from current position if it does not fit on current page
    should split block taller than page across pages starting from current position
    should split block across pages that contains image that does not fit in remaining space on current page
    should advance block that starts with image that does not fit in remaining space on current page to next page
    should advance block with caption that starts with image that does not fit in remaining space on current page to next page
multiple
  should arrange block after another block has been arranged
table cell
  at top
    should keep block on current page if it fits
    should draw border around block extent when table cell has large padding
    should truncate block taller than page within table cell
    should scale font when computing height of block
  below top
    should advance table cell that contains block shorter than page but does not fit on current page
    should advance table cell that contains unbreakable block that does not fit on current page
    should advance table cell and truncate child block taller than page
anchor
  should keep anchor with unbreakable block when advanced to new page
  should keep anchor with breakable block when advanced to next page
</pre>
</details>

**Comment by mojavelinux** [comment]
Done!
