### ISSUE TITLE
Make delimited blocks breakable by default

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-pdf#2004]
Currently, most delimited blocks are treated as unbreakable in Asciidoctor PDF and there's no way to turn off the setting. (The only exception is the open block, which follows the spec). The unbreakable behavior was applied in order to be able to apply a background and/or border to the block across page boundaries with accuracy. However, once the fix for #2003 in place, this behavior will no longer be mandatory. The new logic can precisely determine a block's extent regardless of where it starts and thus can apply a background and/or border to it. In light of that improvement, we're proposing that the converter return to making breakable the default for delimited blocks and only treating it as unbreakable if requested by the author using the option with the same name.

The fix for #2003 will lay the groundwork for this change. All that needs to be done for this issue is to check for the `unbreakable` option on the block to determine whether "keep together" logic should be activated:

```rb
keep_together = (node.option? 'unbreakable') && !at_page_top?
```

Keep in mind that if a block starts at the top of the page, it's implicitly breakable since it's already given the maximum space possible to avoid a break.

**Comment by mojavelinux** [comment]
It's happening! :scream:
