### ISSUE TITLE
Listings spanning multiple pages begin on a new page even if current page contains only one line

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor-pdf#201]
With the following document the source block starts on a new page even though the current page only contains one word.
It seems to be that a listing block not fitting on the same page always starts on the next page.

I tested with this extreme example:

```
= Test

Test

[source]
----
This





is






a







very












long














listing 


















block
----
```

**Comment by robertpanzer** [comment]
Maybe it would make sense to add an option to a block that defines to insert a page-break if only less than `n` lines would fit on the current page.

**Comment by robertpanzer** [comment]
Just tried with Head. 
Seems to be already fixed.

**Comment by mojavelinux** [comment]
Yep, I just fixed it over the weekend. Now the page break only occurs if
the listing will fit on the next page. However, we may still need to
consider having more control in the future.
