### ISSUE TITLE
Performance issue generating a simple one pager pdf

### ISSUE THREAD

**Issue by wolftobias** [asciidoctor/asciidoctor-pdf#2018]
I have a simple one page text-only asciidoc template, generate it to a pdf and it takes about 1,5 minutes.
I'm using latest java libraries from maven and openjdk 11 on windows 10.

**Comment by mojavelinux** [comment]
Without a reproducible example, there's no way to track down this problem. Please raise this in users/asciidoctorj stream of the project chat at https://chat.asciidoctor.org along with an example, where we can try to help you work through it. If we determine that there is a problem with the converter, then we can proceed with opening a new issue with more detail.
