### ISSUE TITLE
Allow to control where prose indent is applied

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#2034]
Defining a `prose.indent` property causes the first line of *every* paragraph indented. However, in books that first line indentation is often skipped for the first paragraph after a heading, table, image, i.e. if the preceding content element is not a paragraph in turn.

It would be nice if one could choose between these application modes of the setting.

**Comment by mojavelinux** [comment]
Can you point me a book that uses this style so that I can study it?

**Comment by odrotbohm** [comment]
<img width="1912" alt="Screenshot 2022-04-15 at 23 48 45" src="https://user-images.githubusercontent.com/128577/163635990-c4466e77-82e5-45f9-9ae7-18dc8968fda5.png">
Does this help?

**Comment by mojavelinux** [comment]
Can you cite which book that is an in which reader you are using to view it?

**Comment by mojavelinux** [comment]
I found two references for this rule, which seems to be called "full out indent".

* https://selfpublishingadvice.org/10-typesetting-rules-for-indie-authors/
* https://www.louiseharnbyproofreader.com/blog/when-to-indent-text-laying-out-narrative-and-dialogue-in-fiction

**Comment by mojavelinux** [comment]
Both Chicago and APA require the indentation on the first paragraph, so there are clearly two styles.

As far as the code is concerned, we do have the ability to check if the previous sibling is a paragraph, so technically its possible to support. Though we do need to decide how this is going to be expressed in the theme. To keep with the CSS theme, we could using something like `prose_first_of_group_indent` which would allow you to zero it out for the first paragraph in a sequence of paragraphs. The other option would be to focus on the indent key itself, such as `prose_indent_style: full-out`.

**Comment by mojavelinux** [comment]
I also found this reference on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent#skipping_indentation_on_the_first_paragraph

**Comment by mojavelinux** [comment]
Here's what I propose. If `prose-text-indent` is set, then it is applied to every paragraph. If `prose-adjacent-text-indent` is set, it is only applied to a paragraph that follows an adjacent paragraph.

```yaml
prose:
  margin-inner: 0
  adjacent-text-indent: 10.5
```

Does that sound reasonable?

**Comment by odrotbohm** [comment]
Thanks for all this research, Dan. Happy to let you decide here, as you're by far more intimate in how the inter-relationship of configured properties works in other places already.

**Comment by mojavelinux** [comment]
Thanks for the feedback Oliver.

I was thinking that since we use the term "inner" to refer to the margin between adjacent paragraphs, we should stick with that terminology here as well. That could help make the key more intuitive.

```yaml
prose:
  margin-inner: 0
  inner-text-indent: 10.5
```

Unless there is an objection, I'll move forward with this proposal.

**Comment by mojavelinux** [comment]
When coming back to this with fresh eyes, I realized that the placement of the "inner" keyword is not consistent between the two terms, which could be confusing. I propose making it parallel:

```yaml
prose:
  margin-inner: 0
  text-indent-inner: 10.5
```

The `inner` qualifier means it only applies at the intersection of two adjacent paragraphs.

**Comment by odrotbohm** [comment]
I can confirm this now works as expected. Happy to adjust configuration property name as you see fit.
<img width="1500" alt="Screenshot 2022-04-19 at 10 43 09" src="https://user-images.githubusercontent.com/128577/163962746-4918a5e4-75f8-41a6-ab71-3b4d2632f607.png">

**Comment by mojavelinux** [comment]
That looks great! Thanks for sharing!

**Comment by odrotbohm** [comment]
I have a tiny follow-up for this one: Asciidoctor Bibtex extension renders each entry as paragraph, which now causes all entries but the first one to be indented (see below). I fully understand why it renders the way it renders and am afraid that it's hard to fix without Bibtex fundamentally changing the way it renders the entries.

Do you see a short-term workaround accidentally?

<img width="385" alt="Screenshot 2022-04-26 at 14 32 47" src="https://user-images.githubusercontent.com/128577/165300866-cc6540b8-0fe1-4f98-b046-12396450c176.png">

**Comment by mojavelinux** [comment]
[As I've expressed before](https://github.com/asciidoctor/asciidoctor-pdf/issues/1889#issuecomment-802608267), asciidoctor-bibtex should be generating the bibliography as a list, not as separate paragraphs. If that extension were producing a list, you would not get this behavior.

**Comment by odrotbohm** [comment]
Using asciidoctor/asciidoctor-bibtex#84 as a hacky workaround for now.
