### ISSUE TITLE
Update installation instructions of required and optional libraries

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-pdf#2040]
In preparation for 2.0, we need to review and update the installation instructions for the required and optional libraries. This includes specifying the supported versions for each library. ~~A PR for this issue can't be submitted until #2035 has been merged.~~

Specifically, these items need to be addressed:

- Review Asciidoctor PDF installation instructions (ROOT:install.adoc); update as needed
  - Since Asciidoctor core is a prereq, shouldn't we add an xref to the Asciidoctor installation page?
  - The RVM conundrum ... the PDF docs (see the troubleshooting section on ROOT:install.adoc) point to https://asciidoctor.org/docs/install-asciidoctor-macos/#rvm-procedure-recommended. After a quick review of the existing docs in other components, no other Ruby gem we have has RVM instructions (they just say manage Ruby with RVM and point to the RVM home page):
    - Is RVM still the recommended method? If it isn't, should we replace this reference with something else (just the homepage of RVM like some of the other projects) or do we delete this content all together?
    - If RVM is still recommended, do we port the instructions from https://asciidoctor.org/docs/install-asciidoctor-macos/#rvm-procedure-recommended (and I'd port them into Asciidoctor core, and then xref to those instructions from PDF)?
- Specify the minimum supported versions of the required and optional libraries Asciidoctor PDF depends on or integrates with.
  - Create section at bottom of ROOT:install.adoc (unless we want a separate page, e.g., support-platforms.adoc) for supported platforms and create table with required prerequisites and minimum supported version and optional prerequisites with minimum supported version (use the model on file:///home/apex/projects/docs.asciidoctor.org/public/asciidoctor/2.0/install/supported-platforms.html or https://docs.antora.org/antora/latest/install/supported-platforms/#platforms)
  - What about Mathematical and Diagram, are there minimum versions?
  - What about prawn-table, prawn-icons, and so forth. Does Asciidoctor PDF pull them in automatically or do some of them need to be installed separately?
  - The gmagick version should not be mentioned in the content of ROOT:image-paths-and-formats.adoc, instead it should be specified in the optional prerequisites (or whatever we decide to call it) table. Once done, remove the version number from the content and TODO comment on ROOT:image-paths-and-formats.adoc page.
 - Review optional library installation instructions, update as needed
   - hexapdf (ROOT:optimize-pdf.adoc)
   - rghost (ROOT:optimize-pdf.adoc)
   - What is text-hyphen? There's no information in the PDF docs on it except to install the gem on ROOT:install.adoc. It needs a dedicated home or needs to be removed.
- Update references to Ruby 2.5 to ? in the content and examples (could set up a component version attribute)
- Update references to JRuby 9.1 to ? in the content and examples (could set up a component version attribute)
- Determine and communicate support status of Asciidoctor PDF 1.5 and 1.6
- Update the README with the minimum installation information needed, add relevant links to docs from README for further installation info
- Update Contributing Code doc to align with new installation information where appropriate

**Comment by mojavelinux** [comment]
> Since Asciidoctor core is a prereq, shouldn't we add an xref to the Asciidoctor installation page?

Installing Asciidoctor PDF installs Asciidoctor as a transitive dependency. I've added this information under the install command.

> Is RVM still the recommended method?

I think so, though there may be better alternatives for those unfamiliar with the ecosystem.

> If it isn't, should we replace this reference with something else (just the homepage of RVM like some of the other projects) or do we delete this content all together?

Let's just link to rvm.io until we have instructions of our own.

I was clearer about the minimum Ruby and JRuby versions. The minimum is 2.7 and 9.2, respectively, but we always recommend using the greatest version available.

> Specify the minimum supported versions of the required and optional libraries Asciidoctor PDF depends on or integrates with.

There are two types of dependencies in Asciidoctor PDF. There are mandatory transitive dependencies, like prawn. No one should be messing or worrying about this version. It's very much linked to the Asciidoctor PDF version.

What we can do is list optional dependencies, the minimum supported versions, and which features they enable.

**Comment by mojavelinux** [comment]
> There's no information in the PDF docs on it except to install the gem on ROOT:install.adoc. It needs a dedicated home or needs to be removed.

I've provided some context. We need a dedicated page on the `hyphens` attribute and what it does. text-hyphen is not a transitive dependency because a) it's huge and b) it hasn't been released in 10 years, which spells a lot of risk.
