### ISSUE TITLE
Set up What's New page for Asciidoctor 2.0

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-pdf#2044]
In the new documentation for Asciidoctor 2.0, create a What's New page (ROOT:whats-new.adoc), add it to the nav list, and populate it with key items from the CHANGELOG. Use the Antora What's New page as a model (see document attibutes, etc.). **A PR for this issue can't be submitted until https://github.com/asciidoctor/asciidoctor-pdf/pull/2035 has been merged.**

**Comment by mojavelinux** [comment]
:tada:
