### ISSUE TITLE
Build fails for coderay pygments.rb on cygwin

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#207]
Windows 8 / cygwin64 / Ruby 2.2.2

asciidoctor-pdf installed fine

Here's the output for the coderay pygments install:

```
$ gem install coderay pygments.rb
Successfully installed coderay-1.1.0
invalid options: -SNw2
(invalid options are ignored)
Parsing documentation for coderay-1.1.0
Done installing documentation for coderay after 2 seconds
Building native extensions.  This could take a while...
ERROR:  Error installing pygments.rb:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby.exe -r ./siteconf20150620-209396-li4c3o.rb extconf.rb
creating Makefile

make "DESTDIR=" clean
rm -f
rm -f yajl.so  *.o  *.bak mkmf.log .*.time

make "DESTDIR="
gcc -I. -I/usr/include/ruby-2.2.0 -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I.    -ggdb -O2 -pipe -Wimplicit-function-declaration   -Wall -funroll-loops  -o yajl.o -c yajl.c
yajl.c: In function ‘yajl_status_to_string’:
yajl.c:61:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 }
 ^
yajl.c: In function ‘yajl_alloc’:
yajl.c:105:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 }
 ^
yajl.c: In function ‘yajl_reset_parser’:
yajl.c:110:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 }
 ^
yajl.c: In function ‘yajl_free’:
yajl.c:119:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
...
gcc -shared -o yajl.so yajl.o yajl_alloc.o yajl_buf.o yajl_encode.o yajl_ext.o yajl_gen.o yajl_lex.o yajl_parser.o yajl_version.o -L. -L/usr/lib -L. -fstack-protector -Wl,--export-all-symbols -Wl,--enable-auto-image-base,--enable-auto-import    -lruby220  -lpthread -lgmp -ldl -lcrypt
/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lgmp
/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lcrypt
collect2: error: ld returned 1 exit status
Makefile:254: recipe for target 'yajl.so' failed
make: *** [yajl.so] Error 1

```

I checked the installation of gmp and crypt libs - they are there.

Anyone else seen this?

**Comment by mojavelinux** [comment]
I think it's asking for more than just the libs. It needs the development headers. That means you need something like libcrypt-devel. On Linux, libcrypt is provided by glibc. On Cygwin, it's a separate package. 

Your report made me realize that we don't need to recommend using Pygments anymore. Now that callout number support has been added when using CodeRay, it's sufficient to use CodeRay in most cases. I'd only recommend Pygments if it highlights a language not supported by CodeRay...but then getting it installed is outside the scope of Asciidoctor PDF.

**Comment by mojavelinux** [comment]
I changed the recommendation in this commit: https://github.com/asciidoctor/asciidoctor-pdf/commit/0f464514368b1e2d8cb865bef3413ba8a0b46e45.

**Comment by wolandscat** [comment]
NB: I am using Pygments, and it supports a lot more languages than Coderay, so I think it will be needed in many cases. I have not investigated the relative ease of the methods in each to add a new language, which is something I need to do.

I did get Pygments working fine, so I think again it's just a problem that can be solved by a better gem design, and/or better help info on installing it.

**Comment by mojavelinux** [comment]
I recognize that Pygments is better than CodeRay. However, installing
Pygments is not really a concern of Asciidoctor PDF since it's an optional,
third-party library. pygments.rb installation is something we can address
on asciidoctor.org, so let's follow up there (as it pertains to Asciidoctor
generally).

Note that we're also looking into adopting a Pygments clone written in Ruby
called Rouge, which should install without incident. I'll file an issue to
look into using it.
