### ISSUE TITLE
Support keep together for section titles

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2075]
If the `%breakable` option is set on the section, keep it with the first block of content.

```
[%breakable]
== Section Title

[%unbreakable]
****
sidebar

on

next

page
****
```

This matches the pattern of using the `%breakable` option on a table to keep the caption with the first row of the table. Sections are implicitly breakable. And the converter always tries to leave enough room for one line of content (controlled by the `heading_min_height_after` theme key). But this breaks down if the first block doesn't fit on the current page. The `%breakable` option provides a hint to the converter to do the extra work to keep the section title with whatever comes after it. But doing so incurs a slight cost, which is why we put it behind an option.

**Comment by mojavelinux** [comment]
I've documented the logic behind this behavior on the following page: https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/modules/extend/pages/define-converter.adoc#keep-section-title-with-content

**Comment by gautaz** [comment]
Hello,

Is `[%breakable]` supposed to work when the first element after the section header is a diagram?

I am currently trying something close to this:

```
[%breakable]
==== Section header

[plantuml]
....
<diagram details>
....
```

But `ascidoctor-pdf` still puts the section header at the end of a page and the diagram and the beginning of the next one.

Am I using `[%breakable]` in the wrong context?

**Comment by mojavelinux** [comment]
That's correct. However, if the diagram can't fit on the page with the section title, it will then be advanced. So it depends on the size of the diagram. Please ask your question in the project chat at https://chat.asciidoctor.org and provide a reproducible example. Thanks!

**Comment by gautaz** [comment]
@mojavelinux Reducing slightly the size of the diagram fixed the issue (I first thought that both the diagram and the header would fit on the page, seems it was a matter of a few pixels :see_no_evil:).
Thanks for your help!
