### ISSUE TITLE
Logical TOC nesting broken

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#2085]
I am using Asciidoctor PDF builds straight from `main` and can see the logical TOC's (not the one rendered on the pages) nesting is currently broken:

<img width="349" alt="Screenshot 2022-04-26 at 15 32 50" src="https://user-images.githubusercontent.com/128577/165314738-ff864b31-3410-4957-94ab-225266da87f5.png">

Note, how section 2.3 is a sibling of 2.2.1, 3 is a sibling of 2.3. This continues on into all following sections. It looks like at some point the "unnesting" breaks and is never added again. I am currently running 6eb9e43b.

**Comment by odrotbohm** [comment]
Nevermind this one. This seems to have been caused by me trying to add additional pages to the generated PDF using Ghostscript. That apparently messed up both the TOC and the linking. Definitely not an issue on your side.

**Comment by mojavelinux** [comment]
Glad you got it sorted out. I'm sure that was a tricky one to solve!
