### ISSUE TITLE
front-cover-image breaks font in v2.0.0 prerelease

### ISSUE THREAD

**Issue by metent** [asciidoctor/asciidoctor-pdf#2092]
Generated pdf without `front-cover-image`:

```
:doctype: book

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
```
![image](https://user-images.githubusercontent.com/90848000/165582021-1ee21e9f-36a9-44f8-89a1-85154eeea818.png)

Gererated pdf with `front-cover-image`:

```
:doctype: book
:front-cover-page: any.pdf

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
```

![image](https://user-images.githubusercontent.com/90848000/165582203-21b48273-e12f-4604-9bb4-458af070ccdf.png)

**Comment by mojavelinux** [comment]
Can you share the front cover image you are using? Or can it be reproduced with any front cover that is itself a PDF?

**Comment by mojavelinux** [comment]
To answer my own question, the front cover pdf has to use a different font and the title page has to be off (either no document title or `-a notitle`). Then I can reproduce this issue.

I think the base font needs to be set after the front cover has been added. I'll add a test for this and figure out how to solve it.

**Comment by mojavelinux** [comment]
Actually, it's any cover that's a PDF. It's because inserting the cover in this case advances the page, which causes the logic to skip setting the base font. Now I know what to fix.
