### ISSUE TITLE
Image caption side

### ISSUE THREAD

**Issue by Zhou-Yicheng** [asciidoctor/asciidoctor-pdf#2115]
I could change the table caption side to **bottom** but could not change the image caption side to **top** using a theme yml file  
```
image:
  caption:
    side: top
```

> Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.17
> Runtime Environment (ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux])

**Comment by mojavelinux** [comment]
This seems reasonable to support.

**Comment by mojavelinux** [comment]
> Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.17

Btw, please test Asciidoctor PDF 2 when requesting new features. Asciidoctor PDF 1.6.x is now in code freeze.
