### ISSUE TITLE
Footnote location too high if footnote wraps around

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#213]
````
* Validating the level of performance provided by the physical hardware prior to deploying the OpenStack environment using eDeploy's Automatic Health Check (AHC)
* Deploying Red Hat OpenStack Platform 6 using the Red Hat OpenStack Installer using ephermal storage
* Deploying Red Hat OpenStack Platform 6 using the Red Hat OpenStack Installer using Ceph Storagefootnote:[Ceph Storage - http://www.inktank.com/openstack-storage-solutions/]
* Validating the OpenStack deployment to ensure proper OpenStack functionality using Tempest footnote:[Tempest- http://docs.openstack.org/developer/tempest/overview.html] 


* Capture, present, and analyze benchmark results using Linpackfootnote:[Linpack - http://www.netlib.org]
* Capture, present, and analyze different benchmark workload scenario results using Rallyfootnote:[Rally - https://wiki.openstack.org/wiki/Rally]
* Capture, present, and analyze different benchmark workload scenario results using the Cloud Rapid Experimentation and Analysis Toolkit  (CBTOOL)footnote:[CBTOOL - https://pypi.python.org/pypi/cloudbench/0.14.1]
* Detail the best practices to optimize a Red Hat OpenStack Platform 6 environment
````

Output:

![selection_223](https://cloud.githubusercontent.com/assets/8877333/8295412/0aa0f91a-190a-11e5-9441-045c1f8658d5.png)

**Comment by mojavelinux** [comment]
This is probably moot given that we just need to bite the bullet and implement footnotes properly. A quick hack for this is probably to change from using superscript to subscript. The reason I changed it from normal text is so that it's easier to see where the footnotes are.

**Comment by rlopez133** [comment]
Yes implementing it in the footer is the def the way to go. I also just wanted to show you what it looks like in a paragraph. Personally it just looks odd to me... While I didn't like that it was hard to differentiate it from normal text, the new way, if anything too small and too high. 

![selection_231](https://cloud.githubusercontent.com/assets/8877333/8295959/bf13a6f4-190f-11e5-8ac1-d31a9f4a5637.png)

**Comment by mojavelinux** [comment]
I'm 100% in agreement that it looks odd.

**Comment by mojavelinux** [comment]
I've resolved this by moving the footnotes back inline in a lighter shade of color. See fa40a56d01acfcefe7520b8213173b220533afe1.

**Comment by mojavelinux** [comment]
A real fix for footnotes is coming.

**Comment by rlopez133** [comment]
Sounds great!

**Comment by rlopez133** [comment]
It looks much better with the footnotes back inline in a lighter shade for the numbers 1,2,3, etc of the footnote. At least until the real fix anyway. :)

**Comment by mojavelinux** [comment]
:+1:
