### ISSUE TITLE
outlinelevels set on section isn't overriding global outlinelevels

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-pdf#2145]
I'm using the document attributes and document shown in the block below with Asciidoctor PDF 2.0.0-beta.1. Notice I've set `outlinelevels` to `2:1` in the document header, and that works as expected.

However, when trying out `outlinelevels` on a section (see the section titled "A Recipe for Potion That Will Ensure You Win the Hearts (level 3)"), and assigning it the value `3` (and then `4` in another try), I continue to get a PDF outline that only shows up to level 2 section titles (see image below). I've also tried this when the doctype is `book` and the result is the same. I may be doing something wrong, but it feels like a bug.

(This work is following up on the CHANGELOG item "allow section to override outlinelevels for self and children using `outlinelevels` attribute on section" for documentation purposes.)

```
= The Intrepid Chronicles: Based on True Events
Kismet Caméléon; Lazarus het_Draeke
v1.0, 2023-01-01
:reproducible:
:listing-caption: Listing
:source-highlighter: rouge
:experimental:
:toc:
:toclevels: 5
:outline-title: The Chronicles
:outlinelevels: 2:1
:icons: font
:preface-title: Preface

[%notitle]
--
[abstract]
This journey begins one late Monday afternoon.
--

== It's a City (level 1)

Our team needs coffee, _desperately_, but none of us dare open the theater doors...

Behold -> the horror!

.Wolpertinger, stuffed
[.left.thumb]
image::wolpertinger.jpg[Wolpertinger,pdfwidth=50%,link={uri-wolpertinger}]

=== Rendezvous Point (level 2)

Come on, _Bier Central_, of course!
Did you have to ask?
If you beat me there, order me a St. Bernardus Abt 12.
Here's some &#x20ac;.

[#ravages]
== The Ravages of Writing (level 1)

Crystalline XML tags relentlessly bombarded the theater.

.XML tags
[,xml]
----
<author id="1">
  <personname>
    <firstname>Lazarus</firstname>
    <surname>het Draeke</surname>
  </personname>
</author>
----

=== DefOps Plan (level 2)

Click btn:[Download Zip] to download the defensive operation plan bundle.

OMG!
I want my mum -- and an extra-large double macchiato, please.

==== Introduction (level 3)

A paragraph.

=== Main (level 2)

Here's how you say "`Hello, World!`" in Prawn:

.Create a basic PDF document using Prawn
[source,ruby]
----
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!'
end
----

[outlinelevels=3]
==== A Recipe for Potion That Will Ensure You Win the Hearts (level 3)

This potion for a sample document contains the following ingredients, which are listed in a very random, chaotically nested order.

.Ingredients for Potion that Demystifies Documents
* all the headings
** syntax highlighted source code
*** non-syntax highlighted source code or just a listing block
* quote block
** verse block
*** table with some cell formatting

===== Searching for Burdockian (level 4)

.Steps for finding and preparing Burdockian leaves
. Locate dusty botany
.. Sneeze
... Sneeze some more

====== Level 5

What is there to do?

* [x] Done
* [ ] Next
* Who's counting?

== Conclusion (level 1)

That's all, folks!
```

![image](https://user-images.githubusercontent.com/1124042/167219963-7448194b-08cc-4626-836e-b411828b6236.png)

**Comment by mojavelinux** [comment]
The trick here is that the outlinelevels has to go on the parent of the section you want to include in the outline. So in this case, outlinelevels needs to go on `Main (Level 2)`:

```
[outlinelevels=3]
=== Main (level 2)
```

That says that for the level 2 section, which is already included, broaden outlinelevels to include another level. It can't go on the section you want to add since the converter never gets to that section when walking the hierarchy.

**Comment by graphitefriction** [comment]
Got it, will change this to a docs issue. Thanks!
