### ISSUE TITLE
Docs: table-caption-end should be table-caption-side

### ISSUE THREAD

**Issue by ponchofiesta** [asciidoctor/asciidoctor-pdf#2148]
In the [theming guide](https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#keys-table) under table key there is caption-end: top|bottom.
Isn't this caption-side?

In my test caption-end had no effect, caption-side worked to bring down below the caption.

**Comment by mojavelinux** [comment]
The official docs for the theming guide are now located at https://docs.asciidoctor.org/pdf-converter/latest/theme/keys/. The theming guide in the repository will soon be removed and redirected.

The `caption-end` key refer to Asciidoctor PDF 2. That is the correct name for the key, and it is tested. See https://github.com/asciidoctor/asciidoctor-pdf/blob/main/spec/table_spec.rb#L2426-L2443 However, the `caption-side` will continue to work for backwards compatibility with Asciidoctor PDF 1.6.

If you are looking for the docs for Asciidoctor PDF 1.6, you can find them in the v1.6.x branch. See https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.6.x/docs/theming-guide.adoc
