### ISSUE TITLE
References format

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#217]
Is there anyway to have references look similar to this? I like having the Title of the reference and under it in smaller text the hyperlink. Not sure if there is a way to mimic this.

Output:

![selection_232](https://cloud.githubusercontent.com/assets/8877333/8296021/974e6e78-1910-11e5-82c9-13351a171a66.png)

**Comment by mojavelinux** [comment]
The best way I can suggest to do this at the moment is either a definition list with an explicit bold term:

```
*TECH: Unix Semaphores and Shared Memory Explained*::
http://docs.oracle.com/cd/E11/pre_install.htm

*Oracle Grid Infrastructure, Oracle Documentation*::
http://docs.oracle.com/cd/E11/oraclerestart.htm
```

or as paragraphs with hardbreaks:

```
*TECH: Unix Semaphores and Shared Memory Explained* +
http://docs.oracle.com/cd/E11/pre_install.htm

*Oracle Grid Infrastructure, Oracle Documentation* +
http://docs.oracle.com/cd/E11/oraclerestart.htm
```

We do have something like this planned that we devised in Asciidoctor EPUB3. See https://github.com/asciidoctor/asciidoctor-pdf/issues/219.

**Comment by mojavelinux** [comment]
There isn't currently a way to shrink text arbitrarily, but it's a reasonable thing to add.

**Comment by mojavelinux** [comment]
The idea I had suggested is now implemented. See #1280.

For example:

```
[unordered]
TECH: Unix Semaphores and Shared Memory Explained::
http://docs.oracle.com/cd/E11/pre_install.htm

Oracle Grid Infrastructure, Oracle Documentation::
http://docs.oracle.com/cd/E11/oraclerestart.htm
```

Combined with all the new theming capabilities, I believe it's possible to achieve the original request.
