### ISSUE TITLE
Wishlist/Enhancement: enable creating ISO 14289 (PDF/UA) compliant documents

### ISSUE THREAD

**Issue by mach-wkl** [asciidoctor/asciidoctor-pdf#2187]
I wish for the asciidoctor pdf backend to be able to generate ISO 14289 (PDF/UA) compliant documents.

Currently, I am able to generate compliant documents with only a subset of the features I want via a long and ugly toolchain: adoc -> docbook -> xml-fo -> pdf/ua.

Among the features I'm missing with my current docbook/xsltproc/fop toolchain are:
- source code highlighting
- using the same theme for both html5 and pdf output
- forced page breaks
- only needing one software instead of four

I'd love to instead be able to directly generate compliant documents with the pdf backend.

**Comment by mojavelinux** [comment]
The PDF generation library that we use, Prawn, generates PDF documents in line with at least the "standard" PDF 1.4 specification (and higher when it's called for). As such, we have no control over how the PDF is made. What we do offer is running the generated document through Ghostscript to produce a PDF/A or PDF/X compliant document. Here's how that's done:

```
asciidoctor-pdf -a optimize=PDF/A document.adoc
```

This is covered in the docs on the following page: https://docs.asciidoctor.org/pdf-converter/latest/optimize-pdf/

We will not be doing anything else in this converter to support other compliance levels or specifications. It's out of scope.

You can find more discussion about this topic in #125, which is what led to the decision to focus on using the optimizer to target different compliance standards.
