### ISSUE TITLE
Theming key entry missing in docs for `toc-dot-leader.font-size`

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#2191]
The [new & noteworthy of 2.0](https://docs.asciidoctor.org/pdf-converter/latest/whats-new/#toc-and-pdf-outline) mention the new theming key but [the reference](https://docs.asciidoctor.org/pdf-converter/latest/theme/toc/#dot) does not actually list it.

**Comment by mojavelinux** [comment]
Wow, good eye! I've added it.

I also clarified that this key needs to be used carefully. It's purpose is to slightly increase the size of a symbol within the line. If the value is too large, it can throw off the alignment of the title and page number. The computation around the layout of this text is very complicated.
