### ISSUE TITLE
optimize-pdf does not optimize

### ISSUE THREAD

**Issue by thorstenkampe** [asciidoctor/asciidoctor-pdf#22]
Just an example for a document with 26 PNGs:
- the Asciidoctor generated HTML file is 2.06 MiB
- Asciidoctor PDF generated PDF file is 1.52 MiB
- the optimize-pdf "optimized" PDF file is 3.70 MiB

**Comment by mojavelinux** [comment]
The action here is that if the optimized file is not smaller than the original, don't overwrite the file. There's nothing I can do about Ghostscript not actually making the file smaller. There's no guarantee of that.

**Comment by mojavelinux** [comment]
There are two solutions to this problem. In the next release, you'll be able to activate the optimizer and control the quality using the `optimize` attribute. For example, `-a optimize=screen` may, in fact, decrease the size.

The other solution is to use hexapdf as documented in the README.

Beyond that, this is really outside the scope of what Asciidoctor PDF can do.

**Comment by mojavelinux** [comment]
I'm going to close as a duplicate since #535 will address this in part, and using hexapdf as an alternative has already been documented.
