### ISSUE TITLE
Different scale of math block in v2

### ISSUE THREAD

**Issue by edward-encoord** [asciidoctor/asciidoctor-pdf#2213]
@mojavelinux Thanks for your reply in https://github.com/asciidoctor/asciidoctor-pdf/issues/2011#issuecomment-1115338781.

> If you can prepare a reproducible example, could you file an issue so I can investigate it?

I just created a reproducible example as [a GitHub gist](https://gist.github.com/edward-encoord/681bb7b19962c404613745c212d0b466). The output from v1.6.2 is:

![image](https://user-images.githubusercontent.com/88771308/170687661-38a9cc07-e7a9-4853-9933-bc8781789d40.png)

versus that from v2.0.5:

![image](https://user-images.githubusercontent.com/88771308/170687716-038cfa67-1c69-4cf1-be9c-2f8d0e500bef.png)

The generated SVGs for the math block are the same, so the issue is not related to AsciiDoctor Mathematical.

**Comment by mojavelinux** [comment]
I'll investigate.

FYI, image_fit is not a valid theme key.

**Comment by mojavelinux** [comment]
I can confirm that the SVG is scaled differently between Asciidoctor PDF 2 and Asciidoctor PDF 1.6. I can reproduce it by embedding the SVG directly, so this has nothing at all to do with Asciidoctor Mathematical. It's possible you are seeing the result of a bug fix, but I need to dive a bit deeper to know what's going on.

**Comment by mojavelinux** [comment]
What Asciidoctor PDF 2 is doing here is actually correct. There was a bug in Asciidoctor PDF 1.6 that it would incorrectly apply px to pt conversion for an SVG whose width is defined using pt units. Now it honors the pt units. This change was made in d863c14776bfcbd31672407ba076ebca9f4cc74a.

What I'm noticing, however, is that Asciidoctor PDF 2 will not apply the px to pt conversion for an SVG whose width is defined using px units. I think it should. Though that doesn't impact this particular scenario.

**Comment by mojavelinux** [comment]
As I concluded, the behavior of Asciidoctor PDF 2 is correct. However, what I discovered is that if the value were to have the units px, the behavior / scaling would not be correct. I opened a new issue to address this problem. See #2215.

**Comment by mojavelinux** [comment]
Thanks for testing and verifying the fix!

**Comment by edward-encoord** [comment]
> I can confirm the problem has been resolved since v2.0.7. Thanks a lot.

It seems the problem has not been resolved. I just continued the conversation in [`zulipchat`](https://asciidoctor.zulipchat.com/#narrow/stream/288690-users.2Fasciidoctor-pdf/topic/font.20size.20latexmath).

**Comment by mojavelinux** [comment]
I assure you the problem is resolved. Asciidoctor PDF renders the SVG exactly as it is requested. If there is a problem with the size, it needs to be set in Asciidoctor Mathematical correctly.
