### ISSUE TITLE
Indent content and add bottom margin to collapsible block

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2219]
To match the display of the (open) collapsible block in the HTML output, the content of the collapsible block should be indented by the width of the marker and the block should be offset from the next enclosed block by the bottom block margin. Additionally, if a title is not specified, it should default to "Details".

Here's how it currently looks:

![actual](https://user-images.githubusercontent.com/79351/170820893-e8e86d55-ac57-47c6-9697-389b072f82fa.png)

Here's how it should look:

![expected](https://user-images.githubusercontent.com/79351/170820899-71f5ed3c-c8e7-4d45-8e45-70101646a742.png)

**Comment by edward-encoord** [comment]
Thanks for the quick response. This is indeed very helpful.
