### ISSUE TITLE
Upgrade from 1.6.2 to 2.0.3 leads to WARN: image icon for 'check' not found

### ISSUE THREAD

**Issue by srcnuzn** [asciidoctor/asciidoctor-pdf#2225]
After upgrading from 1.6.2 to 2.0.3 we experienced the following error message:

**WARN: image icon for 'check' not found or not readable**

There were no further code changes. With the previous versions, we had no problems regarding the check icon. Downgrading back to 1.6.2 helped.

**Comment by mojavelinux** [comment]
It sounds to me like you have the `icons` attribute set on the doument and there's an icon macro in your document that refers to the icon named "check":

```
icon:check[]
```

The converter is going to look for an image icon that matches that name. If it can't find the icon, it will log a warning. This is an enhancement that was introduced in 2.0.0.alpha.2, which is cited in the CHANGELOG:

> add support for image-based icons, resolved from `iconsdir` and having the `icontype` file extension (#1770)

The message should be telling you exactly what file the converter looking for. The message should actually look like this:

> asciidoctor: WARNING: image icon for 'check' not found or not readable: /path/to/project/images/icons/check.png

If you need more assistance with using this feature, please ask your question in the project chat at https://chat.asciidoctor.org.
