### ISSUE TITLE
Page break may happen after titles for tables, lists, and paragraphs

### ISSUE THREAD

**Issue by elsav-emrs** [asciidoctor/asciidoctor-pdf#2260]
### Config:
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-2.1.1/lib/asciidoctor-pdf.rb

### Description:

When generating PDF I noticed we could have page breaks right after a title for tables, lists or paragraphs,

For tables, I would expect to have the title, header and first row together. 

Below are some PDF output examples of the issue.

#### Paragraphs
![image](https://user-images.githubusercontent.com/69378793/175616349-797a121f-69b6-4414-b1da-87aa72219e5c.png)

#### Lists
![image](https://user-images.githubusercontent.com/69378793/175616932-c551de4f-17e6-47c1-b863-49d7a03e10d3.png)

#### Tables
![image](https://user-images.githubusercontent.com/69378793/175616772-0509b8af-027f-4ef1-8e95-10d4a7e08410.png)

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org.

The docs clearly state what orphan prevention behavior is provided by this converter and how to make use of it. See https://docs.asciidoctor.org/pdf-converter/latest/breakable-and-unbreakable/
