### ISSUE TITLE
Is this a bug: code-caption-margin-outside moves caption text but not background

### ISSUE THREAD

**Issue by mygithubdevaccount** [asciidoctor/asciidoctor-pdf#2271]
When I specify:

```yaml
code-caption-margin-outside: 6pt
code-caption-background-color: #EFEFEF
```

then the caption text moves down, and the background color moves up, like this:

![screenshot](https://user-images.githubusercontent.com/101020513/176859721-06c0264f-e71d-4ab8-ac13-05b53066dcba.png)

Maybe it's intended. I don't know. 

My expectation would be:

![expectation](https://user-images.githubusercontent.com/101020513/176861196-c59dfd6c-9a06-4fb7-bfc5-c91089428f7b.png)

p.s. thanks for your awesome work

**Comment by mojavelinux** [comment]
Yep, you're right. The margin is being added instead of subtracted, which puts it on the wrong side of the boundary.

**Comment by mygithubdevaccount** [comment]
Thank you, Tested it locally, and it works now as expected! Thank you for that quick fix!

**Comment by mojavelinux** [comment]
Thank you for testing and verifying the fix!

I'm going to wait a few days to see if any other issues arise. If not, I'll push out a patch release that includes the fix.
