### ISSUE TITLE
Inline source/literals do not render in the correct monospace font

### ISSUE THREAD

**Issue by KerimG** [asciidoctor/asciidoctor-pdf#2273]
Repository to reproduce here: https://github.com/KerimG/asciidoc-inline-literal-problem

I am trying to use the literals , as in `` `+literals+` `` in the same font as codeblocks in the PDF but for some reason the font is a completely different one and I cannot figure out why.

![image](https://user-images.githubusercontent.com/9061713/177309600-a7460acf-3ccf-428b-9fd7-628863569427.png)

**Comment by mojavelinux** [comment]
There appears to be a problem in how you have configured your theme. Please direct questions about usage to the #users/asciidoctor-pdf stream in the project chat at https://chat.asciidoctor.org. When you do, please include the theme file you are using. Either myself or someone else will help you work though the problem.
