### ISSUE TITLE
Whitespace lost between words when text block is wrapped

### ISSUE THREAD

**Issue by m8rges** [asciidoctor/asciidoctor-pdf#2275]
When i have a text block, that will be wrapped on creating pdf, between those words, where the line break is done, the white space is dropped.

For example:
_"This is my text"_
will become
_"This is
my text"_ (where the space character after "is" is missing)

This makes problems especially in source blocks, where readers may copy the source code, what will make problems on execution of code.

**Comment by mojavelinux** [comment]
I'm sorry, but this is just the nature of PDF, in particular the PDF writer that Asciidoctor PDF uses. Copying and pasting text from a PDF is not a reliable operation and you should not depend on it. Text in a PDF is broken up into fragments and positioned absolutely on the canvas. Sometimes, that means non-visible characters are not rendered, such as spaces at the end of a line. Sometimes, it means that special characters must be inserted to get the PDF reader to preserve indentation. There is no way I know (using Prawn) to do it any other way. And often times, the decision is up to Prawn to decide which non-visible characters to preserve. Even then, I've seen different PDF readers copy text differently. PDF is designed for print and this is a case where that bias shines through.

**Comment by mojavelinux** [comment]
Previously reported in #832 and #1629.

**Comment by m8rges** [comment]
Thanks for that fast reply. 
Sad about such problems on wrapping with Prawn. Other PDF writers just keep the space character at the end of line.
But otherwise asciidoctor-pdf is a nice gadget  :thumbsup:

**Comment by mojavelinux** [comment]
Again, it's an extremely complex issue. While other PDF writers might keep the space in certain cases, that space may also cause problems that Prawn/Asciidoctor PDF does not have. And no PDF writer is going accommodate when the text is split across pages, or text needs to be indented without special guard characters. PDF is not intended to be a copy/paste format (at least not without the accessibility metadata that was added to the PDF spec to handle this case). So I don't view this as sad. I view it the nature of PDF.

But if you are anyone else knows how the code could be changed to better accommodate copy, feel free to show me what needs to be done.
