### ISSUE TITLE
Title partitioning not working

### ISSUE THREAD

**Issue by alpinus4** [asciidoctor/asciidoctor-pdf#2296]
Hi
Title partitioning seems not to work for me.

_test.adoc_
```adoc
= Main title: Subtitle

content content
```

When running `asciidoctor-pdf test.adoc` I get such output:
![image](https://user-images.githubusercontent.com/25907897/180807170-804adf8e-986f-4c5f-b143-2807b7746b7d.png)

However I would like subtitle to be in the next line.

```
$ asciidoctor-pdf --version
Asciidoctor PDF 2.2.0 using Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

Any help?

**Comment by mojavelinux** [comment]
Subtitle partitioning is only done on the title page. You must set the doctype to book or set the title-page attribute. As the docs state [here](https://docs.asciidoctor.org/pdf-converter/latest/theme/title-page/#subtitle):

> Subtitle partitioning of the document title is only enabled when the title page is also enabled.

In the future, please direct questions about usage to the project chat at https://chat.asciidoctor.org. That helps us to better manage the project. Thanks.
