### ISSUE TITLE
PDF generation using PDF theme file dies

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#230]
I started to use asciidoctor-pdf theme file, and built a very basic one. When running asciidoctor, the PDF generation dies as follows:

```
Thomas@seawolf /cygdrive/c/dev/openEHR/spec-publish-asciidoc
$ ./publish.sh -pt
---------------------- publishing AOM2 ----------------------
generated /cygdrive/c/dev/openEHR/spec-publish-asciidoc/docs/AOM2/AOM2.html
/usr/local/gems/prawn-2.0.1/lib/prawn/document/bounding_box.rb:304:in `-': nil can't be coerced into Fixnum (TypeError)
        from /usr/local/gems/prawn-2.0.1/lib/prawn/document/bounding_box.rb:304:in `subtract_left_padding'
        from /usr/local/gems/prawn-2.0.1/lib/prawn/document/bounding_box.rb:289:in `ensure in indent'
        from /usr/local/gems/prawn-2.0.1/lib/prawn/document/bounding_box.rb:290:in `indent'
        from /usr/local/gems/prawn-2.0.1/lib/prawn/document.rb:483:in `indent'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/converter.rb:1675:in `block in layout_toc_level                 '
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/converter.rb:1644:in `each'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/converter.rb:1644:in `layout_toc_level'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/converter.rb:1635:in `layout_toc'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/converter.rb:139:in `block in convert_document'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/prawn_ext/extensions.rb:654:in `instance_exec'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/prawn_ext/extensions.rb:654:in `block in dry_ru                 n'
        from /usr/local/gems/prawn-2.0.1/lib/prawn/font.rb:63:in `block in font'
        from /usr/local/gems/prawn-2.0.1/lib/prawn/font.rb:208:in `save_font'
        from /usr/local/gems/prawn-2.0.1/lib/prawn/font.rb:61:in `font'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/prawn_ext/extensions.rb:161:in `font'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/prawn_ext/extensions.rb:653:in `dry_run'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/converter.rb:138:in `convert_document'
        from /usr/local/gems/asciidoctor-pdf-1.5.0.alpha.8/lib/asciidoctor-pdf/converter.rb:88:in `convert'
        from /home/Thomas/.gem/ruby/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1028:in `convert'
        from /home/Thomas/.gem/ruby/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1499:in `convert'
        from /home/Thomas/.gem/ruby/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
        from /home/Thomas/.gem/ruby/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `each'
        from /home/Thomas/.gem/ruby/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
        from /home/Thomas/.gem/ruby/gems/asciidoctor-1.5.2/bin/asciidoctor:10:in `<top (required)>'
        from /home/Thomas/bin/asciidoctor:23:in `load'
        from /home/Thomas/bin/asciidoctor:23:in `<main>'
```

The YAML theme file is [here](https://github.com/openEHR/spec-publish-asciidoc/blob/master/resources/openehr_pdf_theme.yml), but note that *even if I cull it back to the first 2 lines, it still dies, but in a different way*.

This can be reproduced by:
* cloning https://github.com/openEHR/spec-publish-asciidoc
* cd to the repo root dir and do `./publish.sh -pt` (-p = PDF, -t = trace)

**Comment by mojavelinux** [comment]
Very likely that the problem here is that expected keys are missing. It's
still best to start by modifying the default theme (copying it as your own)
and going from there. This is exactly why we need that base theme plus some
validation.

**Comment by wolandscat** [comment]
Seems you are right. I copied the default and made changes to it; these are now coming through, so the basic machinery is functioning. There are quite a lot of issues in the PDF output - do you want me to report each one as a separate issue here?

**Comment by mojavelinux** [comment]
> There are quite a lot of issues in the PDF output - do you want me to report each one as a separate issue here?

Yes, please.

Hence the alpha label :)

**Comment by wolandscat** [comment]
Just on the original cause of this issue - I think it probably needs to say in the documentation on the PDF theme facility that currently, the process is copy and update, rather than building an overrides file. The documentation is currently a bit ahead of where things stand right now (where things stand is fine, but the online info just needs to reflect that). Other than that, I am fine with the issue being closed. I'll report other issues separately.

**Comment by mojavelinux** [comment]
You're right that the documentation is ahead. I wrote it thinking I would get to the base theme before alpha.8 was out, but other pressure led it to be released sooner. I'll update the note in the docs, but then focus on getting the base theme implemented.

**Comment by mojavelinux** [comment]
I think that the documentation is much clearer now. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#language-overview
