### ISSUE TITLE
Unnumbered list in PDF table cell not rendered

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#231]
A bullet list in a cell in the Amendment table is [rendered normally in the HTML - see row for 2.1.0](https://rawgit.com/openEHR/spec-publish-asciidoc/master/docs/AOM2/AOM2.html#_amendment_record), but rendered in the PDF as just text with original '*' characters interspersed.

SPEC-270. Add specialisation semantics to ADL
and AOM. Add various attributes and functions
to ARCHETYPE_CONSTRAINT descendant classes. *
move C_PRIMITIVE.assumed_value to attribute slot
in UML \* rename C_DEFINED_OBJECT
.default_value function to prototype_value *
correct assumed_value definition to be like ;
remove its entry from all of the C_PRIMITIVE
subtypes \* convert BOOLEAN flag representation
of patterns to functions and add a String data
member for the pattern value, thus matching
the XSDs and ADL \* add ARCHETYPE.is_template
attribute. \* add ARCHETYPE.is_component
attribute. \* allow computed as well as stored
attributes. \* make ONTOLOGY
.terminologies_available computed.

To reproduce, see [test project](https://github.com/openEHR/spec-publish-asciidoc).

**Comment by mojavelinux** [comment]
This is related to (and will be resolved by) #6.

**Comment by mojavelinux** [comment]
This has long since been resolved.
