### ISSUE TITLE
Table cell colours that were set from the source disappear in the PDF output

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#234]
The [HTML output](https://rawgit.com/openEHR/spec-publish-asciidoc/master/docs/AOM2/AOM2.html#_archetype_class) shows how the colouring should look; completely absent in the PDF. 

Example of the adoc source of these tables [here](https://raw.githubusercontent.com/openEHR/spec-publish-asciidoc/master/docs/AOM2/classes/archetype.adoc).

PDF output:
![image](https://cloud.githubusercontent.com/assets/1481744/8368100/efa5fbce-1b9d-11e5-96cf-795d91687826.png)

**Comment by mojavelinux** [comment]
Did you mean to post an example?

**Comment by wolandscat** [comment]
Updated with some examples.

**Comment by mojavelinux** [comment]
This is related to #86. I don't think we should implement table cell colors that are manually set in the AsciiDoc source since it is very far from semantic content. Instead, this should be controlled by the theme. You can control the color of header rows and cells using the theme. (Actually, I'm not sure about header cells, but you should be able to control the color...if not we need to fix that).

You can see examples of using the theme to set header row colors in #214.

**Comment by mojavelinux** [comment]
I filed #239 as a follow-up issue since I can see that we are not applying the table head styles to the head er cells.

**Comment by wolandscat** [comment]
If we can set semantic styles for table cells in adoc source, it's easy for us to change our generator. We just need to a) know how to do it and b) have it generate the right outcome for both HTML and PDF.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor/issues/1338. For a generic solution, we have to agree on that first, then we can do something in Asciidoctor PDF.

Keep in mind we may be able to handle some of your use cases by realizing that we are trying to style header cells within the body (a built-in role). So perhaps a first step we can take is allowing the theme to control the style of these cells.

**Comment by mojavelinux** [comment]
I'm going to create a more specific issue for that last point. See #272.

**Comment by schneefisch** [comment]
I would like to push the importance of this ticket up ;)

**Comment by ukazap** [comment]
Any news?

**Comment by mojavelinux** [comment]
I'm fine with moving ahead with this, caveats in all. When AsciiDoc supports roles on cells, then we can come back and do it the right way later.
