### ISSUE TITLE
ubuntu pdf reader hyperlinks not work

### ISSUE THREAD

**Issue by kandido** [asciidoctor/asciidoctor-pdf#2341]
Hi,

I have download chronicles-example folder from [example pdf](https://github.com/asciidoctor/asciidoctor-pdf/tree/main/examples) and generate chronicles-example.pdf  with `asciidoctor -b pdf -r asciidoctor-pdf -a pdf-theme=chronicles-dark-theme.yml chronicles-example.adoc` command. With FoxitReader I can open hyperlinks but with Evince and Acroread not. When I click the hyperlink reference the ERROR message is "[51715:51715:0914/111901.415578:FATAL:spawn_subprocess.cc(221)] posix_spawn: Permission denied (13)".  I have installed "Asciidoctor 2.0.17" with bundle manager. The downloaded chronicles-example.pdf have not this errors, but the generated chronicles-example.pdf from me it has.

Thanks in advance

**Comment by mojavelinux** [comment]
It sounds to me like you may not have followed all the instructions under the Development heading in the contributing guide. Please refer to https://github.com/asciidoctor/asciidoctor-pdf/blob/main/CONTRIBUTING-CODE.adoc#development

In the future, if you have trouble using this repository or Asciidoctor PDF, please post your question to the project chat at https://chat.asciidoctor.org. Thanks!
