### ISSUE TITLE
Source code blocks don't seem to honor "breakable" properly by default, or after setting "breakable" option.

### ISSUE THREAD

**Issue by initialcommit-io** [asciidoctor/asciidoctor-pdf#2346]
Hi there,

I'm using asciidoctor-pdf and my code blocks don't seem to be breaking and splitting onto multiple pages (unless they are larger than 1 full page length). Instead, it's putting in a page break and adding the code block on the new page.  The docs clearly state that the default option in asciidoctor 2.0+ is breakable.  I tried manually enabling the setting, disabling line numbers, and using a regular listing but it didn't seem to work.  Below is an example of my source block:

```
=== Code snippets

Here is the part of the code that fills in the base character array with the directory and filename of the object using the object's SHA-1 hash value.

[source,c,start=403]
----
/*
 * Fill in the rest of the object path (object directory and filename)
 * using the object's SHA1 hash value.
 *
 * Convert each number in the sha1 array (ranging from 0 to 255) to a 
 * two-digit hexadecimal number (ranging from 00 to ff). The first 
 * two-digit hexadecimal number will form part of the object directory. 
 * The rest of the two-digit hexadecimal numbers will comprise the object 
 * filename. 
 */
for (i = 0; i < 20; i++) {
    /*  
     * Lookup array for getting the hexadecimal representation of a 
     * number from 0 to 15. 
     */  
    static char hex[] = "0123456789abcdef";
    /* Get the current number from sha1. */
    unsigned int val = sha1[i];
    /*  
     * Set the index of the base array. This will be name + 0, name + 3,
     * name + 5, name + 7,..., name + 39. 
     */  
    char *pos = name + i*2 + (i > 0); 
    *pos++ = hex[val >> 4];   /* Convert the 4 high bits to hex. */
    *pos = hex[val & 0xf];    /* Convert the 4 low bits to hex. */
}
----
```

Any suggestions, maybe I'm missing something? Below are my command version and OS info, I tried upgrading with brew but I seem to have the latest versions.

$ asciidoctor --version
Asciidoctor 2.0.17 [https://asciidoctor.org]

$ asciidoc --version
asciidoc 10.2.0

$ uname -a
Darwin MacBook-Pro-3.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 x86_64

**Comment by mojavelinux** [comment]
Please confirm that you are using at least Asciidoctor PDF 2.

```
asciidoctor-pdf -v
```

I suspect that's not the case based on the description in your report. The behavior you are describing is how the converter worked prior to the 2.0.0 release.

> The docs clearly state that the default option in asciidoctor 2.0+ is breakable.

**Asciidoctor PDF** 2. Asciidoctor 2 is a separate piece of software (on which Asciidoctor PDF is built).

**Comment by initialcommit-io** [comment]
Yes I suspected I was on the lower version, and that appears to be the default installed via brew:

$ asciidoctor-pdf -v
Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.17 [https://asciidoctor.org]

Is it possible to upgrade it via brew?  Or does it need to be installed separated as a gem?

**Comment by initialcommit-io** [comment]
Nevermind I was able to set up rvm and install a newer ruby version, and get the latest asciidoctor-pdf 2+, it works now.  Thanks!
