### ISSUE TITLE
monospace and italic do not work together

### ISSUE THREAD

**Issue by fekir** [asciidoctor/asciidoctor-pdf#2350]
Consider following document

````
= Test

**S**ome *bold* text.

__T__his is is _italic_.
**__B__**old *_italic_*.

``T``his is `monospace`.
``**T**``his is `*bold and monospace*`.
``**__T__**``his is `*_monospace_*; *bold* and _italic_`.

##S##ome #highlighted text#.
##``**__T__**``##his is #`*_highlighted, bold, italic and monospace_*`#.

````

with `asciidoctor-pdf`, the output looks like 

![image](https://user-images.githubusercontent.com/11912465/193136830-0304c072-9f22-426d-b757-235ba32516b1.png)

and with `asciidoctor` the output looks like

![image](https://user-images.githubusercontent.com/11912465/193136986-f8c927a0-f6f5-42bb-99fc-79c524dcb019.png)

It seems that in the pdf output, italic and monospace do not work together, as the text is not italic, while in the html output, italic and monospace work as expected

If it helps, I can also upload the generated document

````
Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
````

**Comment by mojavelinux** [comment]
Please see my comment here: https://github.com/asciidoctor/asciidoctor/issues/4360

**Comment by fekir** [comment]
@mojavelinux 

Similar to https://github.com/asciidoctor/asciidoctor/issues/4360, the issue is with monospace and italic, two formattings, not more. (I reused the same example for both tickets as I was lazy)

**Comment by mojavelinux** [comment]
The issue at play here is that the background on the code phrase prevents the background on the mark phrase from being inherited. If you want the background on the mark to be inherited, customize the theme to take away the background on the code phrase.

```
extends: default
code:
  background: none
```

**Comment by mojavelinux** [comment]
> In PDF, the italic and monospace do not work together

That's because the monospace font provided by the default theme uses font weight instead of oblique characters to represent italic. The font used does not have an italic form. If you need different behavior, you can provide your own font. https://docs.asciidoctor.org/pdf-converter/latest/theme/custom-font/
