### ISSUE TITLE
code block with default syntax highlightning and `subs="quotes"` breaks code

### ISSUE THREAD

**Issue by fekir** [asciidoctor/asciidoctor-pdf#2351]
Consider following document

````
= Test

[source,c,subs="quotes"]
----
int [.line-through]#foo(int)#;
int [underline]#bar(void)#;
````

and generate a pdf with `asciidoctor-pdf --attribute "source-highlighter=pygments" --attribute 'pygments-style=solarized-light' test.adoc`, and one with `asciidoctor-pdf test.adoc`

The two document looks like (left side without `pygments`)

![image](https://user-images.githubusercontent.com/11912465/193139048-a1165e8a-0bae-4bf6-a0c3-6e266989268f.png)

But the expected behavirou is that the document on the right side should look like the one on the left side, as syntax hihglightning is not enabled (because of `subs="quotes"`), and the underlined/striked code should be underlined/striked instead of having a `span`

note that normally pygments works correctly:

![image](https://user-images.githubusercontent.com/11912465/193139610-648eeb49-840a-495f-9b84-cdd107d0db7c.png)

created from 
````
[source,c]
----
int foo(int);
int bar(void);
----
````

````
Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
````

**Comment by mojavelinux** [comment]
You cannot combine quotes subs with syntax highlighting in PDF. They are fundamentally not compatible. This is documented in the list of limitations. See https://docs.asciidoctor.org/pdf-converter/latest/features/#limitations

As of 2.3.0, the converter will gracefully degrade by removing all markup from the source. See https://github.com/asciidoctor/asciidoctor-pdf/issues/2086 I'll make sure this is clearer in the documentation.

Btw, the subs should be `subs=+quotes`, not `subs=quotes`. The later disables the specialchars substitutions, which can lead to problems.

**Comment by fekir** [comment]
@mojavelinux Thank you for the clarification, in fact I was going to add to the description also

````
[source,java,subs="verbatim,quotes"]
----
System.out.println("Hello *<name>*")
----
````

which adds `<bold>` instead of making the characters bold.

I did not use `subs=+quotes` because it seems to produce invalid HTML (as it does not disable syntax highlighting and thus tags are not closed correctly), while `subs=quotes` avoids the issue.

**Comment by mojavelinux** [comment]
The problem is that you are using an outdated/unsupported version of Asciidoctor PDF. If you use Asciidoctor PDF 2.3, this problem is fixed. You can safely use `subs=+quotes`, which is the correct way of enabling the quotes substitution on a source block.
