### ISSUE TITLE
Cannot Center Heading For One Specific Section Only

### ISSUE THREAD

**Issue by chrisjd20** [asciidoctor/asciidoctor-pdf#2367]
I'm on `Asciidoctor PDF 2.3.4 using Asciidoctor 2.0.17 `

I've checked through documentation and can't seem to find how to center the heading on one section only. My default theme is to align headers left (which is good for most of my document but not this one page).

What I'm trying to do is center the heading for this one section only:

```
[.text-center]
== This Heading Wont Be Centered

[.text-center]
But this Text Will Be Centered
```

How do I center my heading Text? I don't care if its a lack-luster method of centering it. Perhaps is there a way for me to escape spaces in the title heading so I can shift the heading to the center using spaces?

**Comment by chrisjd20** [comment]
Ok I found out I could use `{nbsp}` to add spaces. But would be nice if I didnt have to rely on this.

**Comment by chrisjd20** [comment]
Actually that doesn't work. It throws off the table of contents

![image](https://user-images.githubusercontent.com/11812223/201149259-030090bc-6099-40cd-8912-509732ec7b70.png)

**Comment by mojavelinux** [comment]
It's not possible to center a single section title.

The way you are using `{nbsp}` is strongly discouraged here, for reasons you are observing.

**Comment by chrisjd20** [comment]
I'll close this then. Thanks. Might be a nice feature to add!
