### ISSUE TITLE
Index section with no terms swallows next section

### ISSUE THREAD

**Issue by georgeraraujo** [asciidoctor/asciidoctor-pdf#2368]
Versions:
```
$ asciidoctor-pdf --version
Asciidoctor PDF 2.3.3 using Asciidoctor 2.0.18 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

Source, with commented index terms:
```asciidoc
= Sample book with index section, but no index terms
Author
:doctype: book
:nofooter:
:toc: left

[[chapter-one]]
== Chapter one

// indexterm2:[Lancelot] was one of the Knights of the Round Table.
// indexterm:[knight, Knight of the Round Table, Lancelot]

[[the-index]]
[index]
== Index

[[the-glossary]]
[glossary]
== Glossary

[[the-bibliography]]
[bibliography]
== Bibliography

[[the-colophon]]
[colophon]
== Colophon

```

Output:
[index-with-no-terms.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/9997950/index-with-no-terms.pdf)

The TOC does not show the index section, nor the PDF has it.
The TOC shows the Glossary section, but the PDF does not have it, and its page shows up as `?` in the TOC page.

Now with the index terms uncommented:
```asciidoc
= Sample book with index section, and with index terms
Author
:doctype: book
:nofooter:
:toc: left

[[chapter-one]]
== Chapter one

indexterm2:[Lancelot] was one of the Knights of the Round Table.
indexterm:[knight, Knight of the Round Table, Lancelot]

[[the-index]]
[index]
== Index

[[the-glossary]]
[glossary]
== Glossary

[[the-bibliography]]
[bibliography]
== Bibliography

[[the-colophon]]
[colophon]
== Colophon

```

Output:
[index-with-terms.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/9997952/index-with-terms.pdf)

The TOC shows the index section, and the PDF has it.
The TOC shows the Glossary section, the PDF has it, and its page shows up correctly in the TOC page.

**Comment by georgeraraujo** [comment]
I just tested with 2.3.4, and the result is the same.

**Comment by mojavelinux** [comment]
I can confirm this bug. When the index section is removed, it affects the iteration over the sibling blocks. A different strategy will be needed.
