### ISSUE TITLE
Can't set cell background color AND have cell interpreted as asciidoc at the same time.

### ISSUE THREAD

**Issue by chrisjd20** [asciidoctor/asciidoctor-pdf#2371]
Version `Asciidoctor PDF 2.3.4 using Asciidoctor 2.0.17`.

Does not seem like I can have a table cell formatted as asciidoc and also set the background color of that cell. Either that, or I am just doing it wrong.

For example, in the second-row and first cell I can set the color to grey using `|{set:cellbgcolor:#f2f2f2} Description`. However, in the next cell, `a|{set:cellbgcolor:#ffffff}` does have it interpret it as asciidoc but fails to set the color back to white.

Heres an example:
```
[cols="20%,80%",stripes=none]
|===
|{set:cellbgcolor:#6f2f9f} *[white]#Critical#*         |{set:cellbgcolor:#f2f2f2} Some Title Goes Here
|{set:cellbgcolor:#f2f2f2} Description     a|{set:cellbgcolor:#ffffff}
PUT YOUR DESCRIPTION HERE

|{set:cellbgcolor:#f2f2f2} Recommendations a|{set:cellbgcolor:#ffffff}
You should

* Do something.
* Do the thing in foo.
* Do the final thing in bar.

|===
```

This shows:

![image](https://user-images.githubusercontent.com/11812223/201786043-6928d821-f95f-4bb6-bad8-056f8664e3ac.png)

The cells I circled in red should have a white background but they dont.

Is there something I'm missing? Or Perhaps there is some work-around for me?

**Comment by mojavelinux** [comment]
Applying background colors to cells this way is deprecated and not something we're going to support in Asciidoctor PDF. If it works partially, it is undefined behavior.

**Comment by chrisjd20** [comment]
> Applying background colors to cells this way is deprecated in AsciiDoc and not something we're going to support in Asciidoctor PDF. If it works partially, it is undefined behavior.

So is there. No other way of accomplishing the same result?

**Comment by mojavelinux** [comment]
You can extend the converter and/or patch Prawn table to add color. https://docs.asciidoctor.org/pdf-converter/latest/extend/

Ideally AsciiDoc would support applying a role to a cell. Currently, it does not, but the idea has been proposed for the AsciiDoc language. When that idea makes it's way into the language, then it might be something Asciidoctor PDF could support using its theming system. But that's not anywhere on my roadmap right now.

**Comment by chrisjd20** [comment]
Ok thanks for the guidance. Please dont remove this depricated feature until yall have the system in place (just a suggestion). Feel free to close this issue if you like.

**Comment by chrisjd20** [comment]
Ok, last thing I swear! (thanks for your help). I'm not afraid of coding but perhaps you can point me in the right direction with a bit more guidance?

So I know that I need to extend the converter using `asciidoctor-pdf -r ./extended-pdf-converter.rb doc.adoc`

Looks like I can override based on [override a method](https://docs.asciidoctor.org/pdf-converter/latest/extend/create-converter/#override-a-method).

Based on that example, I could use something like:

``` ruby
class ExtendedPDFConverter < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def convert_thematic_break node
    theme_margin :thematic_break, :top
    stroke_horizontal_rule 'FF0000', line_width: 0.5, line_style: :solid
    move_down 1
    stroke_horizontal_rule 'FF0000', line_width: 1, line_style: :solid
    move_down 1
    stroke_horizontal_rule 'FF0000', line_width: 0.5, line_style: :solid
    theme_margin :thematic_break, ((block_next = next_enclosed_block node) ? :bottom : :top), block_next || true
  end
end
```

My question though is which method in question do I need to override to accomplish my original task mentioned above instead of `convert_thematic_break` (since that was just an example on  the page)? 

If you could just get me to the right method, I can tinker around enough until I figure out how to accomplish what I need.

Also is this where I donate to asciidoctor? I really appreciate your product. Its a life saver. https://opencollective.com/asciidoctor/donate?amount=20

**Comment by mojavelinux** [comment]
I'm glad you found a path forward.

The link you cited at OpenCollective is indeed the way to support the project. And those donations are supporting all my work on Asciidoctor PDF at this point.

In the future, I think discussions like this are better suited for the project chat at https://chat.asciidoctor.org. There, you conduct general discussions and share the progress of your experimentation without having to worry about issue status.

> Please dont remove this depricated feature until yall have the new system in place

As of now, the behavior is use at your own risk. Since this is open source software, you are free to make whatever choice you make. But there's no guarantee it will be there in a future release. However, you can rely on your own extended converter.
