### ISSUE TITLE
Missing table bottom margin when using the unbreakable/breakable option

### ISSUE THREAD

**Issue by jwar-fugro** [asciidoctor/asciidoctor-pdf#2379]
Hi, I seem to be experiencing some issues with table margins when using the `breakable`/`unbreakable` option on them.

Example Asciidoc:

```
Lorem ipsum 1

|===
| This is a simple table
|===

Lorem ipsum 2

[%unbreakable]
|===
| This is a simple table with `unbreakable` set
|===

Lorem ipsum 3

.This is a simple table
[%breakable]
|===
| This is a simple table with title and `breakable` set
|===

Lorem ipsum 4

[%breakable]
|===
| This is a simple table with no title and `breakable` set
|===

Lorem ipsum 5
```

Is rendered as:
![image](https://user-images.githubusercontent.com/71654625/207013532-166e5884-5952-4677-88fb-c2f10ecb887e.png)

Note how there is no spacing between "Lorem ipsum 3" and its preceding table. The same behaviour can be observed for "Lorem ipsum 4". Maybe I am misunderstanding something (or using the options incorrectly) but I don't think this is intended behaviour?

For context, the above example was generated by running `asciidoctor-pdf` on a simple file with just the content shown. `asciidoctor-pdf` version string: `Asciidoctor PDF 2.3.4 using Asciidoctor 2.0.18`

**Comment by mojavelinux** [comment]
This is some sort of unexpected side effect of the table height computation that we have to do to support unbreakable. It appears to only happen when unbreakable is on a table, not any other type of block. That at least narrows it down when looking for the problem.

**Comment by mojavelinux** [comment]
Aha, I see. The logic that looks for the next block in document order does not properly handle a table that is wrapped in a breakable/unbreakable container.

**Comment by mojavelinux** [comment]
Related to this, the wrapped table does not honor the theme settings for the table caption.
