### ISSUE TITLE
Cell with AsciiDoc content and style roles

### ISSUE THREAD

**Issue by ericis** [asciidoctor/asciidoctor-pdf#2380]
## Summary

After reading issue #6, I assumed that it might be possible to render AsciiDoc content inside of a table cell and to format it using both column-level style formats, cell style formats and inner-cell content roles.

## Expected

Column and cell styles to be applied and the ability to use roles to customize content styles.

## Actual

Styles are ignored and the role `[.important]` is output to the PDF's content.

## Example

```asciidoc
.Table styles example
[cols="1a,1e"]
|===

|AsciiDoc content
|Default Emphasis content

e|Cell-style emphasis
a|Cell-style AsciiDoc

a|[.important]The "important" role applied to a cell's AsciiDoc content
a|... doesn't seem to work.

|===
```

```yaml
extends: default
role:
  important:
    font-style: bold
    text-transform: uppercase
```

## Version

Docker image: [asciidoctor/docker-asciidoctor:1.36](https://hub.docker.com/layers/asciidoctor/docker-asciidoctor/1.36/images/sha256-62a686e68d1827b519f7dff9c6179f9fbbe7ea862735f338ee17756eda64ece8?context=explore)

**Comment by mojavelinux** [comment]
Please direct usage questions to the project chat at https://chat.asciidoctor.org.

I'll leave a few notes here out of courtesy. You don't need to use an AsciiDoc table cell for inline formatting. The AsciiDoc table cell is only to support block-level content. And you are missing the enclosing formatting marks around the phrase to apply the role. See https://docs.asciidoctor.org/asciidoc/latest/text/custom-inline-styles/

**Comment by ericis** [comment]
Thanks @mojavelinux . That chat URL is blocked by corporate firewalls. We were attempting complex layouts and assumed we would have to use tables for PDF output. I think we will need to shift to use this project for our needs:
https://github.com/Mogztter/asciidoctor-web-pdf

*I recognize I'm commenting on a closed issue, but thought I'd share since I can't join the chat (from this computer).

**Comment by mojavelinux** [comment]
> We were attempting complex layouts and assumed we would have to use tables for PDF output.

There are certainly limits to what can be achieved in terms of layout with Asciidoctor PDF, though I'd argue that the combination of table-based layouts and the [extended converter](https://docs.asciidoctor.org/pdf-converter/latest/extend/) should be sufficient for most reasonable needs.

> That chat URL is blocked by corporate firewalls.

I'm sorry that's the case. Unfortunately, that's how this project is being managed, so I can't offer an alternative. Regardless, it's not a sufficient justification for circumventing project policy.
