### ISSUE TITLE
Per-part chapter signifiers

### ISSUE THREAD

**Issue by trombonehero** [asciidoctor/asciidoctor-pdf#2381]
It would be lovely if I could specify a different `chapter-signifier` in each part of a `book`. For example:

```adoc
= Our organization's constitution

:chapter-signifier: Article

== The first article

== The second article

= Our by-laws

:chapter-signifier: By-Law

== The first by-law
```

**Comment by mojavelinux** [comment]
This should already be possible. The chapter signifier is referenced when it is needed, so it will see the latest assignment. The only thing that would prevent this from working is even if the title has been cached by an earlier xref.

```
= Our organization's constitution
:chapter-signifier: Article
:doctype: book
:sectnums:

== The first article

== The second article

= Our by-laws

:chapter-signifier: By-Law

== The first by-law
```

If you have other questions about this behavior, please direct those questions to the project chat at https://chat.asciidoctor.org.
