### ISSUE TITLE
Chapter number styling

### ISSUE THREAD

**Issue by trombonehero** [asciidoctor/asciidoctor-pdf#2382]
It would be handy if chapter numbering could be customized to use, e.g., the `upperroman` numbering style.

**Comment by mojavelinux** [comment]
If you need this capability, you can either extend the converter or override the `sectnum` method of the `Section` class. This is not a feature we are considering right now for Asciidoctor and its converters.

If you need help with how to customize Asciidoctor or Asciidoctor PDF, please ask in the project chat at https://chat.asciidoctor.org.
