### ISSUE TITLE
Can not export Chinese document

### ISSUE THREAD

**Issue by god464** [asciidoctor/asciidoctor-pdf#2385]
I'm trying to export my document accoding to this [guide](https://docs.asciidoctor.org/pdf-converter/latest/theme/cjk/). Unfortunately, it can not display text correctly. But when I try to run `asciidoctor-pdf -a scripts=cjk -a pdf-theme=pdf-theme=default-with-fallback-font -a pdf-fontsdir=./themes test.adoc`, it can display some letters normally. What can I do?

PS:
1. My `asciidoctor-pdf` version is 2.3.4.
2. `config-theme.yml` is same as the doc, fonts are also downloading from doc.

**Comment by mojavelinux** [comment]
Please direct questions about using Asciidoctor PDF to the project chat at https://chat.asciidoctor.org. Someone there will be able to help you. The issue tracker is not a support portal.

When you post, please share a sample document so that someone else can test what you are trying to convert.
