### ISSUE TITLE
Error message printing special characters

### ISSUE THREAD

**Issue by ciampix** [asciidoctor/asciidoctor-pdf#2387]
This example fires some error messages and the characters are not printed (but it works with asciidoctor -> html output):

> = Title
> 
> This fires an error (from an electrical CAD manual) using asciidoctor-pdf: `&mu;` `4.7k&ohm;`

but perhaps I'm missing something.

**Comment by mojavelinux** [comment]
This is a known restriction. Asciidoctor PDF does not support named entities. You must use numerical character references instead. See https://docs.asciidoctor.org/pdf-converter/latest/features/#limitations

I would prefer if you asked questions about using Asciidoctor PDF in the project chat at https://chat.asciidoctor.org. We reserved the issue tracker for **confirmed** bug reports. That helps us to better manage this project.
