### ISSUE TITLE
Define different width for Page Columns

### ISSUE THREAD

**Issue by madduci** [asciidoctor/asciidoctor-pdf#2389]
Hi

it's more a feature request than a bug reporting. First of all, thanks for the great job. 

I'd like to ask if it would be possible to define (maybe through YAML theme file?) the width of the columns, to create some kind of effect like a shorter column on left and a bigger one on right or viceversa (similar to a sidebar).
Maybe the different columns could be identified with an `id` label, to make the configuration in the YAML easier

```
[type=column,id=first-col]

Content Here for First Column

[type=column,id=second-col]
<<<

Content Here for Second Column
```

**Comment by madduci** [comment]
Nevermind, i was able to achieve the desired result with `sidebar` and a negative value for `column_gap`

**Comment by mojavelinux** [comment]
Glad to hear you figured it out.

In the future, I'd prefer if you raised these kinds of use case questions in the project chat at https://docs.asciidoctor.org. That gives us more room to discuss and share solutions. Thanks!
