### ISSUE TITLE
Apply table head styles to header cells

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#239]
The table head styles (background and font color) should be applied to header cells (update: by default) in addition to the cells in the head row.

**Comment by mojavelinux** [comment]
Two open questions:

1. Should we separate the styles for header cells from styles for the header row?
2. Should we rename the `head` key to `header` (e.g., `table_header_background_color`)?

**Comment by wolandscat** [comment]
Logically I would say it's pretty common to need special shading / colouring on the basis of whole rows or columns, e.g. top row, other rows, and typically column 1. [Example](https://rawgit.com/openEHR/spec-publish-asciidoc/master/docs/AOM2/AOM2.html#_archetype_class).

Note that this isn't a generic style in our case - we need different types of tables. So a 'class specification table' has a certain style of shading. 

Probably I want to have a style 'class_table_header' (where 'class_table' here refers to our idea of UML class specification tables - nothing to do with HTML/CSS classes) that can be applied in rows and or columns, or rows with some cell span, e.g. no span = all; else an integer = that many cells from the left side of the row.

If this is too complicated, just a per cell style would probably be ok.

**Comment by mojavelinux** [comment]
Related to #272.

**Comment by mojavelinux** [comment]
This was implemented in 1.5.0.alpha.9 as a separate category, `table_header_cell`. Do you think that addresses this issue?

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#table

The open question, I suppose, is whether the table_header_cell keys should inherit from the table_head keys. Do you think we should do that?

**Comment by wolandscat** [comment]
It would seem logical to me to inherit, based on the keys that are there and the logical semantics. Header cells will pick the text_transform in addition if you do that, but that seems logical as well.

**Comment by mojavelinux** [comment]
Okay, I'll proceed with inheriting the settings. I think it's important to have the override because header cells in the body may be different from header cells in the header. But it's logical that they have the same settings by default.

**Comment by wolandscat** [comment]
Right. In our style of tables and a lot I see in tech docs, it's pretty normal that the 'header' style cells thoughout the table are the same, +/- the top header row sometimes being different.
