### ISSUE TITLE
Author and Revision not showing in Title Page

### ISSUE THREAD

**Issue by shadyvd** [asciidoctor/asciidoctor-pdf#2399]
**index.adoc**
```
= Testing AsciiDoc: How will the PDF look?
:doctype: book

:author: Author Test
:email: email@example.org
```

**Environment**
```
$ asciidoctor-pdf --version
Asciidoctor PDF 2.3.4 using Asciidoctor 2.0.18 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
**Command**
```
$ asciidoctor-pdf index.adoc
```

**Expected Output**
Title Page with Title, Subtitle, and Author Information

**Actual Output**
PDF title page without author information - see attached [index.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/10915130/index.pdf) for details

**Comment by mojavelinux** [comment]
You have an empty line in your document header, which causes it to end early. See https://docs.asciidoctor.org/asciidoc/latest/document/header/#document-header-structure

In the future, please ask question about usage in the project chat first at https://chat.asciidoctor.org. Thanks.

**Comment by shadyvd** [comment]
Thank you.
