### ISSUE TITLE
Theming the conum in code style vs document text

### ISSUE THREAD

**Issue by lirantal** [asciidoctor/asciidoctor-pdf#2400]
Hi folks,

Is it possible to theme the call outs (`conum`) differently like in the following case where I want to use a black code style background but the PDF background for the text document itself is white?

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/316371/224480144-52e2f5e4-3afe-4eae-bf4c-084e87c2819c.png">

So effectively I would want to color the background for the (1) in white when it is drawn on the code highlight block.

**Comment by lirantal** [comment]
I posted the ask on the community channel (at https://asciidoctor.zulipchat.com/#narrow/stream/288690-users.2Fasciidoctor-pdf) as I saw that is preferred over a GitHub issue. Thanks folks!

**Comment by mojavelinux** [comment]
Thanks @lirantal! I'll follow up there.
