### ISSUE TITLE
Allow color of conums in callout lists to be controlled using the callout-list-marker-font-color theme key

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2402]
To align with the theme settings for regular lists, allow the color of conum marker in a callout list to be controlled using the `callout-list-marker-font-color` theme key. If this key is not specified, the color of the conum will match the color used for the target conum (the one in the verbatim block).

**Comment by RasstAdonai** [comment]
> To align with the theme settings for regular lists, allow the color of conum marker in a callout list to be controlled using the `callout-list-marker-font-color` theme key. If this key is not specified, the color of the conum will match the color used for the target conum (the one in the verbatim block).

>
>Null

**Comment by RasstAdonai** [comment]
># frozen_string_literal: Delete
> To align with the theme settings for regular lists, allow the color of conum marker in a callout list to be controlled using the `callout-list-marker-font-color` theme key. If this key is not specified, the color of the conum will match the color used for the target conum (the one in the verbatim block).
