### ISSUE TITLE
When generating PDF, how can I have a level title generated from a new page?

### ISSUE THREAD

**Issue by CheneyDu0129** [asciidoctor/asciidoctor-pdf#2408]
As you can see, the title starts on a new page

![image](https://user-images.githubusercontent.com/72074750/226254551-5853618f-1afe-4200-aa3b-e668d9f4d527.png)

**Comment by mojavelinux** [comment]
Please ask questions in the project chat at https://chat.asciidoctor.org as the issue template requested. The issue tracker is not a support portal.
