### ISSUE TITLE
A list in a table cell that runs over the end of a PDF page is unexpectedly truncated and falsely reported as an error

### ISSUE THREAD

**Issue by randomuser369** [asciidoctor/asciidoctor-pdf#2426]
Affects: Asciidoctor PDF 2.3.7 using Asciidoctor 2.0.18 [https://asciidoctor.org]

Say, I have a table:

```
[width="100%",cols="13%,87%a",options="header",]
|===
|Property 
|Description

|State
|One of the following:

* Option 1: Blah blah
* Option 2: Blah blah
* Option 3: Blah blah

|Blah
|Blah blah
|===
```

In the output pdf, say this table starts 4/5 down a page, and runs over the end of the page (Option 2 is the last text that fits on the pdf page). asciidoctor-pdf responds:

- Truncates the list. It shouldn't - it should move the entire row onto the next page, like a page break.
- During PDF generation, it raises an error `asciidoctor: ERROR: the table cell on page <X>has been truncated; Asciidoctor PDF does not support table cell content that exceeds the height of a single page`. This error is inaccurate - the cell height fits well within a single page.

The workaround is to replace the list with a description list.

```
[width="100%",cols="13%,87%a",options="header",]
|===
|Property 
|Description

|State
|One of the following:

[horizontal]
Option 1:: Blah blah
Option 2:: Blah blah
Option 3:: Blah blah

|Blah
|Blah blah
|===
```

In this case, asciidoctor-pdf responds as one would expect:

- The row is moved to the next page, not truncated.
- No error is raised.

The fix is to have this behaviour in the case of a list in a table cell overrunning the end of a PDF page.

**Comment by mojavelinux** [comment]
Please provide a reproducible test case or sample project. Otherwise, I'm going to close this issue as inaccurate.
