### ISSUE TITLE
text-transform doesn't transform headings in index

### ISSUE THREAD

**Issue by dsisnero** [asciidoctor/asciidoctor-pdf#2427]
When applying the text-transform in the headings = It correctly transforms the heading in document but it doesn't transform the heading in the index.  Want all my headings to be transformed to uppercase also.

**Comment by mojavelinux** [comment]
I'm not able to reproduce this. Can you please provide an example?

**Comment by mojavelinux** [comment]
Please provide a reproducible test case or sample project. Otherwise, I'm going to close this issue as inaccurate.

**Comment by mojavelinux** [comment]
Without any additional information, I have to mark this report as invalid. Feel free to reopen if you're able to provide the necessary information to reproduce it.
