### ISSUE TITLE
asciidoctor: ERROR: could not locate or load the built-in pdf theme `' because of ArgumentError unknown keywords: aliases, filename; reverting to default theme

### ISSUE THREAD

**Issue by sqzsq** [asciidoctor/asciidoctor-pdf#2446]
I installed asciidoctor using gem and got this error.

The invocation:

asciidoctor-pdf \
-a toc \
-a compress \
-o test.pdf test.adoc

The result:

asciidoctor: ERROR: could not locate or load the built-in pdf theme `' because of ArgumentError unknown keywords: aliases, filename; reverting to default theme
unknown keywords: aliases, filename
  Use --trace to show backtrace

The version is:

Asciidoctor PDF 2.3.9 using Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

This can be reproduced using an empty .adoc file

Looks like a broken dependency.

PS: While you're working on it, what is the latest stable version?

**Comment by mojavelinux** [comment]
The version of Ruby you are using is no longer supported. Asciidoctor PDF requires at least Ruby 2.7.

In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org. Thanks.
