### ISSUE TITLE
Not Showing diagram generated by Plantuml via Kroki in generated pdf.

### ISSUE THREAD

**Issue by azafar1991** [asciidoctor/asciidoctor-pdf#2457]
Hello,
Using asciidoctor-pdf with asciidoctor extension in vscode. 
I am using Kroki (local-Server) for diagrams.On generating the pdf ,it shows plant uml code instead of diagram although in preview it is working fine.

===  Sample Diagrams

.This is a puml code.
[plantuml,"test-1",svg,inline]
....
@startuml

node "Test1" as tst1
node "Test2" as tst2
tst1 --> tst2: Relation

@enduml
....

**Comment by mojavelinux** [comment]
This sounds like asciidoctor-kroki is not being loaded/required when converting to PDF. This is not something that can be solved in this repository. You might want to ask in the project chat at https://chat.asciidoctor.org or file an issue with the VS Code extension.
