### ISSUE TITLE
Add support for the Rouge syntax highlighter

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#247]
Allow the use of the [Rouge syntax highlighter](https://github.com/jneen/rouge) by setting the value of the `source-highlighter` attribute to `rouge`.

**Comment by mojavelinux** [comment]
Before merging, I'd like to implement a Prawn formatter that creates text fragments directly to avoid having to parse the generated HTML. This is similar to what we've done for CodeRay.

**Comment by mojavelinux** [comment]
And once that is done, I think we should just drop support for Coderay and map the "coderay" source highlighter value to Rouge.

**Comment by mojavelinux** [comment]
Prawn formatter implemented. I also implemented support for line numbers (with primitive, but sufficient, output).

**Comment by mojavelinux** [comment]
All that's really left to do is allow the start number to be customized when line numbers are enabled.

**Comment by mojavelinux** [comment]
We have to add a trailing endline or else certain highlighting rules don't take affect on the last line. (See  https://github.com/jneen/rouge/issues/279). Although this endline is benign in Prawn, we could strip it out before applying the formatting using the following code:

```ruby
tokens = tokens.entries
if (last_token = tokens_a[-1])
  if (last_val = last_token[-1]) == EOL
    tokens.pop
  else
    last_token[-1] = last_val.chomp
  end
end
```

**Comment by rlopez133** [comment]
:+1:  on Rogue highlighter

**Comment by mojavelinux** [comment]
I'd like to do some side-by-side comparison of real-world code snippets to see how good a job Rouge does vs CodeRay and Pygments. I've got a bunch of repositories cloned, so I'll do a quick scan and see what comes up. If you're following this issue, free to test on any snippets you have to see if any deficiency come up in Rouge.
