### ISSUE TITLE
Do not inseart page break between table and it's caption

### ISSUE THREAD

**Issue by jaskij** [asciidoctor/asciidoctor-pdf#2470]
If a table would start at the very end of a page but there is not enough space for it, a page break can be inserted between the caption and the table. This is obviously undesirable. As a workaround, one can insert a manual page break before the table, but  it should not be needed.

**Comment by mojavelinux** [comment]
This is already supported. See https://docs.asciidoctor.org/pdf-converter/latest/breakable-and-unbreakable/#breakable
