### ISSUE TITLE
Add support for temporarily breaking out of multi-column mode.

### ISSUE THREAD

**Issue by studio315b** [asciidoctor/asciidoctor-pdf#2475]
I have a wide diagram I want to insert into a page at full width, but setting pdf width to something greater than the column width does not cause the text in other columns to wrap around.

It would be really useful to have the ability to insert large images into documents that have multiple columns.

A special block tag would suffice in this situation for ease of implementation

Expected (Mocked up using LibreWriter):
![image](https://github.com/asciidoctor/asciidoctor-pdf/assets/1725393/cf68efee-d29e-488d-abbb-40a980cd9384)

Actual:
![image](https://github.com/asciidoctor/asciidoctor-pdf/assets/1725393/7fb10f84-4a26-4b80-8bf4-f65587deafca)

**Comment by mojavelinux** [comment]
This is not something that's reasonable to implement in Asciidoctor PDF and therefore not something I plan to add. It's requires detailed knowledge of the content and is therefore a bespoke layout, not something a generic converter can do.

If you need this kind of functionality, you will need to extend the converter and find some way to reserve space for the image, then come back to the page and place it.
