### ISSUE TITLE
Add support for SVG to image reference in SVG encoded as a data URI (SVG data loader)

### ISSUE THREAD

**Issue by scuba1012002** [asciidoctor/asciidoctor-pdf#2512]
In the file from the asciidoctor-pdf repo
lib/asciidoctor/pdf/ext/prawn-svg/loaders/data.rb it was advised to remove the 
 regex 
`REGEXP = %r(\Adata:image/(?:png|jpe?g);base64(?:;[a-z0-9]+)*,)i`
restriction now that prawn-svg supports SVG image references in SVG

Regex from prawn:
`REGEXP = %r{\Adata:image/(png|jpeg|svg\+xml);base64(;[a-z0-9]+)*,}i`

**Comment by mojavelinux** [comment]
This is related to prawn-svg upgrade in 2.3.14.
