### ISSUE TITLE
Alternative to prawn-gmagick?

### ISSUE THREAD

**Issue by Baerbeisser** [asciidoctor/asciidoctor-pdf#2514]
```
Asciidoctor PDF 2.3.15 using Asciidoctor 2.0.22 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
gem v. 3.3.25
```

Hi,

My project contains some gif, so they don't get embedded in pdf and i get a warning:

> asciidoctor: WARNING: GIF image format not supported. Install the prawn-gmagick gem or convert Birds are super-efficient breathers - Science World-Dateien/how-we-breathe.gif to PNG.

Yet i can't compile prawn, be it with `gem install prawn-gmagick` nor manually via git clone.

```
compiling image.c
image.c:3:10: fatal error: wand/magick_wand.h: No such file or directory
    3 | #include <wand/magick_wand.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:246: image.o] Error 1
```

I guess that could be fixed but [the repo](https://github.com/packetmonkey/prawn-gmagick) had its last activity 5 years ago (guess it was the thing with [alpha transparency blowing up](https://github.com/asciidoctor/asciidoctor-pdf/issues/831))

What is the plan here, someone wants to pick prawn-gmagick up again, is an alternative planned or will gif and tiff support be removed (warning should be changed/removed then) ?

**Comment by mojavelinux** [comment]
There is no other alternative for adding gif support to Asciidoctor PDF than to use prawn-gmagick. I cannot comment on the state of that project as it is not part of the Asciidoctor organization. You could ask that project directly.

In the future, please ask questions like this in the project chat at https://chat.asciidoctor.org. The issue tracker is not a support portal, as stated on the get help page in the docs: https://docs.asciidoctor.org/about/get-help/#issue-tracker

**Comment by Baerbeisser** [comment]
Ok, again in short; prawn-gmagick is abandoned for at least 5 years and doesn't compile anymore. I ask how you want to proceed: drop support for the formats asciidoctor-pdf uses prawn-gmagick for or use another solution.

I think this is clearly a related technical issue and not a support question.

I mean, i get that you get a lot of non-issues all day here.
