### ISSUE TITLE
asciidoctor: WARNING: unknown unordered list style: something

### ISSUE THREAD

**Issue by RuffaloLavoisier** [asciidoctor/asciidoctor-pdf#2515]
https://github.com/asciidoctor/asciidoctor-pdf/blob/5aebe179c9c8931de4ba5e501696cadb3206d469/lib/asciidoctor/pdf/converter.rb#L1575

```
=== title

[something]
* blah blah
```

Hello, I encountered a warning while building asciidoctor-pdf. 

I would like to connect js, css to adoc.

When does this happen and what options should I add?

**Comment by mojavelinux** [comment]
The behavior here is correct. `something` is not a valid list style according to https://docs.asciidoctor.org/asciidoc/latest/lists/unordered/#custom-markers

If you need help with AsciiDoc, please ask in the project chat at https://chat.asciidoctor.org.

**Comment by RuffaloLavoisier** [comment]
Thanks for answer ! 👍
