### ISSUE TITLE
add log messages from document

### ISSUE THREAD

**Issue by 42sol-eu** [asciidoctor/asciidoctor-pdf#2525]
The error and warning message are sometimes hard to find in the asciidoc file. 

I was wondering if I could add log messages from my files to have a better understanding of where the error or warning is located.

I would be willing to add the message manually into the necessary places.

Another approach would be to generate automatic messages from chapters and idenified blocks (like table names ...)

I could not really find documentation on this. I assume a extension could do the trick, right?

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org as the issue template requested. Thanks.
