### ISSUE TITLE
Incorrectly Formatted Content by Column When Spanning Rows

### ISSUE THREAD

**Issue by tomas182470** [asciidoctor/asciidoctor-pdf#2533]
Cells are not properly formatted when the format is applied to a column while some rows are merged.

Consider the following example:

[cols="d,m"]
|===
|Default |Monospace

|Default OK
|Monospace OK

.2+|Default OK
|Monospace OK
|Monospace FAIL
|===

It will render the following output:

![image](https://github.com/user-attachments/assets/c2738048-ef9f-4738-b095-b75fe5836bca)

I would expect all Monospace cells to be formatted in a monospace font.

**Comment by tomas182470** [comment]
Once I posted the issue, I realized I should have posted it to the Asciidoctor Core issue tracker. Sorry for the inconvenience.

**Comment by mojavelinux** [comment]
This is a well known issue in Asciidoctor core. You need to style the cells individually when this happens. See https://github.com/asciidoctor/asciidoctor/issues/989
