### ISSUE TITLE
asciidoctor pdf command pipe

### ISSUE THREAD

**Issue by jeremyVignelles** [asciidoctor/asciidoctor-pdf#254]
I'm trying to use the asciidoctor-pdf with pipes for integration inside a gulp script (the .js  I found on the web are too young yet and does not provide the PDF backend)

I found that when I'm trying this command
```bash
$ cat test.adoc | asciidoc-pdf -o - - > test.pdf
```

and the error I get is 
```
can't convert IO into String
  Use --trace for backtrace
```

The error disappears when I use the following syntax
```bash
$ cat test.adoc | asciidoc-pdf -o test.pdf -
```

Thanks,

--------

For those who are looking for a gulp integration of the asciidoctor command line, here is what I do:
```javascript
function genAsciiDoc(file, backend) {
    var args = [];
    if(backend == 'pdf') {
        args = args.concat(['-r', 'asciidoctor-pdf'])
    }

    args = args.concat([
        '-b',
        backend,
        '-o',
        '-',
        '-'
    ]);

    var ext = (backend == 'html5' ? 'html' : backend);

    return gulp.src(file)
    .pipe(spawn({
        cmd: 'asciidoctor',
        args: args
    }))
    .pipe(ext_replace('.' + ext))
    .pipe(gulp.dest('doc/'));
}
```

**Comment by mojavelinux** [comment]
Thanks for pointing this out. It looks like Prawn's `render_file` method doesn't support IO objects, so we'll need to handle this ourselves in the converter.

Here's code I just tested that seems to work

```ruby
  def write pdf_doc, target
    if ::IO === target
      if target == STDOUT
        ::StringIO.open do |io|
          pdf_doc.render io
          io.rewind
          target.write io.read
        end
      else
        pdf_doc.render target
      end
    else
      pdf_doc.render_file target
      @pdfmarks.generate_file target if @pdfmarks
    end
    nil
  end
```

Sadly, we can't stream to STDOUT as Prawn relies on the `size` method, which isn't available on the STDOUT object.

**Comment by mojavelinux** [comment]
PR sent. Please check it out when you get a chance.

**Comment by jeremyVignelles** [comment]
Hi,
Sorry for the delay but I was on other topics these days. I tried your code and it worked as expected using the command line. I did not try using my gulp plugin yet, as I don't know how to say which asciidoctor-pdf to use in the command line.

I hope this could be merged and released soon :smile:

**Comment by mojavelinux** [comment]
Thanks for the feedback @jeremyVignelles! I'll try to get this into the upcoming 1.5.0.alpha.9 release, out by the end of this week hopefully.

**Comment by mojavelinux** [comment]
I sorted out how to get streaming to STDOUT working! \o/

I had to wrap STDOUT in a decorator to track the size and expose that information using an accessor. Then, it works!
