### ISSUE TITLE
add support for ligatures

### ISSUE THREAD

**Issue by mark-summerfield** [asciidoctor/asciidoctor-pdf#2543]
asciidoctor-pdf already supports a number of Text Replacements, e.g., `=>` to `⇒`.

I think it would be helpful to add ligatures so that the following substitutions are done automatically (except as noted below). Replace ff, fi, fl, ffi, ffl, with their corresponding ligatures ﬀ, ﬁ, ﬂ, ﬃ, ﬄ.

But do _not_ do any such replacements inside any of:
```
<<cross-refs>>
((index terms))
`code`
``code``
#id_names
:items (e.g., include:filename.txt[])
nor within listing, literal, or indented blocks
```

**Comment by mark-summerfield** [comment]
The reason I think it belongs in asccidoctor-pdf is because surely a font library can only mechanically replace each, say, fl with ﬂ, but _cannot_ distinguish when this should—or should not—be done.

For example, how can a font library know that
```
The file's name is `filename.txt`.
```
should become:
```
The ﬁle’s name is `filename.txt`.
```
i.e., the _first_ "fi" should be converted to a ligature, but not the second?

**Comment by mojavelinux** [comment]
I'm sorry, but it's just out of scope given the current state of this project. We aren't adding any more features to Asciidoctor PDF unless they are absolutely essential. You're welcome to use an Asciidoctor extension or extended converter to accomplish this, which is very much possible.

**Comment by mark-summerfield** [comment]
I wrote a program that I run over my `*.adoc` files which pretty well does it, so I'll keep using that. Thanks.

**Comment by mojavelinux** [comment]
If you'd like to discuss other ideas, or how to use an extension to do the replacement contextually, I'm always open to have a conversation in the chat.

**Comment by mark-summerfield** [comment]
Doing the replacement contextually sounds good. Basically I need each word and its context. Is there an example you could point to?

**Comment by mojavelinux** [comment]
Please ask in the chat as I suggested.
