### ISSUE TITLE
Table rowspan layout bug

### ISSUE THREAD

**Issue by yaskawaglobal** [asciidoctor/asciidoctor-pdf#2549]
Using a table in which some cells have a large row span, they render correctly in HTML5 output, but in PDF output they're badly wrong.

Here is a sample table for which the layout is broken:

```adoc
[[SupportedInformCommands]]
.Supported Commands
[%header]
|===
| | Smart View | Classic View

.8+| *General*
| Comment | COMMENT INST
| SetShockDetection | SHCKSET
| ResetShockDetection | SHCKRST
| AdvInit | ADVINIT
| AdvStop | ADVSTOP
| SkillSend | SKILLSND
| EnableAvoidance | EI LEVEL=1
| DisableAvoidance | DI LEVEL=1

.18+| *Motion*
| JointMove | MOVJ
| LinearMove | MOVL
| CircleMove | MOVC
| SplineMove | MOVS
| Incremental | IMOV
| SetSpeed | SPEED
| ShiftOn | SFTON
| ShiftOff | SFTOF
| ShiftOn3D | SFTON3D
| ShiftOff3D | SFTOF3D
| MakeShift | MSHIFT
| HighAccuracyPathOn | HTRAJON
| HighAccuracyPathOff | HTRAJOF
| SpeedPriorityOn | HPVELON
| SpeedPriorityOff | HPVELOF
| MultiMoveOn | HPMMVON
| MultiMoveOff | HPMMVOF
| Smooth | SMOOTH

.7+| *I/O*
| DigitalOut | DOUT
| DigitalIn | DIN
| PulseOut | PULSE
| Wait | WAIT
| AnalogOut | AOUT
| AOutRatioOfSpeedOn | ARATION
| AOutRatioOfSpeedOff | ARATIOF

.34+| *Math*
| Set | SET
| Increment | INC
| Decrement | DEC
| Add | ADD
| Subtract | SUB
| Multiply | MUL
| Divide | DIV
| Clear | CLEAR
| Convert | CNVRT
| And | AND
| Or | OR
| Not | NOT
| Xor | XOR
| SetElement | SETE
| GetElement | GETE
| GetSystemVar | GETS
| SquareRoot | SQRT
| Sine | SIN
| Cosine | COS
| ArcTanget | ATAN
| MultiplyMatrix | MULMAT
| Invert Matrix | INVMAT
| GetPosition | GETPOS
| MakeFrame | MFRAME
| StringToValue | VAL
| ValueToString | VAL2STR
| CharToInt | ASC
| IntToChar | CHR$
| SubString | MID$
| StringLength | LEN
| ConcatenateString | CAT$
| SearchString | STRSTR
| SetRegister | SETREG
| GetRegister | GETREG

.21+| *Control*
| Label | LABEL
| Jump | JUMP
| IfThen | IFTHEN
| ElseIf | ELSEIF
| Else | ELSE
| While | WHILE
| For | FOR
| Call | CALL
| GetArgument | GETARG
| Return | RET
| Timer | TIMER
| Pause | PAUSE
| Abort | ABORT
| SetUserAlarm | SETUALM
| Message | MSG
| Switch | SWITCH
| Case | CASE
| Default | DEFAULT
| StartParallelJob | PSTART
| WaitForParallelJob | PWAIT
| ThreadSync | TSYNC

.8+| *Application*
| ArcWeldingOn | ARCON
| ArcWeldingOff | ARCOF
| WeldVoltage | VWELD
| WeldCurrent | AWELD
| SetWeldingCondition | ARCSET
| WeavingOn | WVON
| WeavingOff | WVOF
| SetpointAdjustFromStart | ARCCTS
|===
```

And a screenshot of part of the partial layout from the generated PDF is attached.
![image](https://github.com/user-attachments/assets/4373164d-d0df-4d5c-945e-4d48f21e0e99)

(also, suggestions on how to work-around this  - or fix it - welcome.  My constraint is that I'm matching an existing FrameMaker document, so I need to maintain table numbering)

**Comment by davidljung** [comment]
Oops - posted above as org account.

**Comment by mojavelinux** [comment]
It's well known with Asciidoctor PDF that a cell cannot span the height of a page. When it does, things can go haywire. This is a limitation of prawn-table and there is nothing we can do about it.

If you need further assistance, please ask in the project chat at https://chat.asciidoctor.org. Thanks.

**Comment by davidljung** [comment]
ok - I'll check if one of those spans is longer than a page.  
Is this in a list of well-known bugs somewhere? (this *is* a bug in asciidoctor-pdf, after all).  It may be that asciidoctor-pdf's implementation uses prawn-table and it is a bug in that, but, by extension, then it is a bug in asciidoctor-pdf (- regular users don't care what dependencies asciidoctor uses or where the issue is precisely).
So, I guess this is closed as 'wont to fix' (impractical without ditching prawn-table or fixing that, I'm guessing), rather than 'not a bug'.
I'll post back here if I find any useful info about the prawn-table bug (- just as soon as I find out what prawn-table is...)
