### ISSUE TITLE
Active state styles for links

### ISSUE THREAD

**Issue by ttucker** [asciidoctor/asciidoctor-pdf#256]
Hello,

I'm trying to style the links within my generated PDF using a theme YML, and currently when they are clicked (i.e. a:active in CSS) the background color turns to #212121 and text color #041018 according to a screen capture.

I am able to change the default (inactive) link color no problem, but not sure it's possible to style the various states. Can you advise how to style links when clicked/on mousedown?

Thanks!

**Comment by mojavelinux** [comment]
I don't see any way in PDF to set styles for active links (click/mousedown). At the moment, the font color is not a result of making the text a link. We are just setting the text color when we add link behavior (see https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/formatted_text/transform.rb#L171-L185).

If you have a reference to how this is done in PDF, please point us to information about it. Then, it will likely need to be added to Prawn (see https://github.com/prawnpdf/prawn), at which point Asciidoctor PDF can use it.

**Comment by mojavelinux** [comment]
To my knowledge, this is not possible in PDF. If you know of a way, feel free to reopen with more information.
