### ISSUE TITLE
Table width is not honored

### ISSUE THREAD

**Issue by kongou-ae** [asciidoctor/asciidoctor-pdf#258]
The attribute of width for table is not performed. Is this attribute not supported ?

```
[width="50%"]
|=======================
|Col 1|Col 2      |Col 3

|1    |Item 1     |a

|2    |Item 2     |b

|3    |Item 3     |c

|=======================
```

asciidoctor-pdf changes this adoc into this image.

![](http://aimless.jp/blog/wp-content/uploads/2015/07/table_with_width.png)

**Comment by mojavelinux** [comment]
It's not implemented yet in Asciidoctor PDF. I ran into the same problem
just yesterday. Thanks for reporting!

**Comment by kongou-ae** [comment]
Thank you very much. 

I tested using Asciidoctor PDF 1.5.0.alpha.9.

```
[.text-center]
.ほげほげ一覧
[width="50",cols="<1,^1,^1",options="header,strong"]
|=======================
|Col 1|Col 2      |Col 3
|1    |Item 1     |a
|2    |Item 2     |b
|3    |Item 3     |c
|=======================

ああああ

[.text-center]
.ほげほげ
[align="center",width="50",options="header"]
|=======================
|Col 1|Col 2      |Col 3
|1    |Item 1     |a
|2    |Item 2     |b
|3    |Item 3     |c
|4    |Item 4     |d
|=======================
```

asciidoctor-pdf changes this adoc into this image.The width of table is 50%!!!

![](http://aimless.jp/blog/wp-content/uploads/2015/08/asciidoc-table-center.png)

**Comment by mojavelinux** [comment]
Thanks for testing!!
