### ISSUE TITLE
Renders [?] rather than advanced characters when using non-standard fonts

### ISSUE THREAD

**Issue by atsansone** [asciidoctor/asciidoctor-pdf#260]
When rendering a PDF and including fonts with limited character sets (i.e. only part of the entire Unicode character set), the rendered PDF shows [?] instead. This is because of the unicode_char for different types of spaces in the converter.rb file. Not all fonts support:

  NarrowSpace = unicode_char 0x2009
  NarrowNoBreakSpace = unicode_char 0x202f
  ZeroWidthSpace = unicode_char 0x200b
  HairSpace = unicode_char 0x200a

If there could either be a check or a replacement with a standard font (Arial, etc.) for these invisible characters, it would help when using fonts from foundries like MonoType or others. As written, when using a font like Avenir, the button declarations and the table of contents become unreadable.

**Comment by mojavelinux** [comment]
This is what the fallback font is supposed to handle. I do agree, however, that in certain circumstances we should check the font first before using certain characters. I think the solution here is both documentation and perhaps a change to the code. I'll explore the possible solutions.

**Comment by mojavelinux** [comment]
It's now far easier to define a theme with custom fonts (including a fallback font) and we've thoroughly documented all the non-typical glyphs that Asciidoctor PDF relies on. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#preparing-a-custom-font. Therefore, I'm considering this issue resolved.
