### ISSUE TITLE
spacing issue on code block

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#269]
The following code block doesn't show proper spacing on my end. Something to do with sub quotes?

````
[subs=+quotes]
----
# *ceph osd tree*

[ ... Output Appreviated ... ]

-5	10.8		host mac90b11c094248
84	0.9			osd.84	up	1	
85	0.9			osd.85	up	1	
86	0.9			osd.86	up	1	
87	0.9			osd.87	up	1	
88	0.9			osd.88	up	1	
89	0.9			osd.89	up	1	
90	0.9			osd.90	up	1	
91	0.9			osd.91	up	1	
92	0.9			osd.92	up	1	
93	0.9			osd.93	up	1	
94	0.9			osd.94	up	1	
95	0.9			osd.95	up	1	
----
````

![selection_243](https://cloud.githubusercontent.com/assets/8877333/8663202/d5d01b78-298d-11e5-8f23-7edcb8ac6d3e.png)

**Comment by mojavelinux** [comment]
Are you referring to the line spacing?

**Comment by rlopez133** [comment]
yes

**Comment by mojavelinux** [comment]
Thanks for the clarification. I'll have a look.

**Comment by mojavelinux** [comment]
I get the same box height in both cases. Perhaps you just aren't used to seeing so many similar lines together? In the theme, the line height is set to 1.25, which is very close to being single-spaced. Perhaps you want to increase that to 1.4?

**Comment by rlopez133** [comment]
For example, if you see the code block line:
````
-5  10.8        host mac90b11c094248
````
reads like:
-510.8host mac90b11c094248

There should be more spacing.

**Comment by mojavelinux** [comment]
Oh, that's not line spacing then (the spacing between lines), that's a
problem with whitespace being persevered within the line. I'll have another
look now that I know what I should be paying attention to. Thanks for the
clarification.

**Comment by mojavelinux** [comment]
I wonder if those are tabs in the input (which might have been expanded to spaces when you pasted it into the issue). Can you check to see if the original source has tabs in it?

If so, I recently fixed the handling of tabs in Asciidoctor PDF. Do you have the latest master?

It would be helpful if you could push a file with a sample AsciiDoc snippet to redhat-refarch. However, you need to make sure that you make it in the same way you made the file in question to preserve the characters exactly as they are. Thanks!

**Comment by mojavelinux** [comment]
It reminds me that I do need to document how tabs are now handled. You can set the `tabsize` using the `tabsize` attribute, but it will be fixed to a width of 4 unless you are using Asciidoctor core 1.5.3.dev.

```
:tabsize: 4
```

**Comment by mojavelinux** [comment]
I just checked the source and I can verify that the sample block does use tabs to separate the columns. I'm confident that this issue has been resolved in the upcoming 1.5.0.alpha.9 release.

**Comment by rlopez133** [comment]
Yes adding the tabsize 4 option works like a charm. Thanks!

**Comment by mojavelinux** [comment]
Super!

**Comment by rlopez133** [comment]
Random Q,

I got Atom to work with Live Preview, but the syntax highlighting kinda
sucks. I really liked the one I was using on gedit. Is there a way to
convert the .lang file to be used for Atom?
