### ISSUE TITLE
border of blockquote cut of or on wrong section or page

### ISSUE THREAD

**Issue by MaWiMa** [asciidoctor/asciidoctor-pdf#270]
Every pagebreak inside blockquotes, for example because of long blockquotes, moves border to wrong page or cuts border. (see pic asciidoctor-pdf-blockquote-A5-15-07-10.png)

Same source in A3 instead of A5 works fine (see pic asciidoctor-pdf-blockquote-A3-15-07-10.png).
Sometimes this happens with short quotes at the bottom too (see pic asciidoctor-pdf-blockquote-A4-15-07-10.png).   

---

![asciidoctor-pdf-blockquote-a5-15-07-10](https://cloud.githubusercontent.com/assets/4765542/8697280/02a30086-2af4-11e5-87bc-bc43bf1c7320.png)

---

![asciidoctor-pdf-blockquote-a4-15-07-10](https://cloud.githubusercontent.com/assets/4765542/8697279/029f4a04-2af4-11e5-95d7-175037a547db.png)

---

![asciidoctor-pdf-blockquote-a3-15-07-10](https://cloud.githubusercontent.com/assets/4765542/8697278/029b9b7a-2af4-11e5-9218-f2a6878c2846.png)

**Comment by mojavelinux** [comment]
This is related to #259. Every block that has some sort of border or shading needs the same treatment to handle "drawing" across multiple pages.

**Comment by mojavelinux** [comment]
Here are the issues to track multi-page support for various block types for reference:

quote/verse block - #270
sidebar block - #259
example block - #362
