### ISSUE TITLE
PDF generation reports parse failure. then hangs - but HTML generates fine.

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#280]
The source docs convert to HTML no problem with Asciidoctor 1.5.2. But when I run a PDF conversion, I get an error:

```
Failed to parse formatted text: The old quoting rules based on XML/ISO mnemonic patterns 
(<code>&ohmgr;</code> etc) are replaced by specifying ADL to be UTF-8 based, and any 
exceptions to this requiring ASCII encoding should use the <code>\Uhhhh</code> style of 
quoting unicode used in various programming languages.
```

Asciidoctor then appears to hang.

The command line was:

```
asciidoctor -a current_year=2015 \
    -a stylesdir=../../../spec-publish-asciidoc/resources/css   \
    -a resources_dir=../../../spec-publish-asciidoc/resources \
    -a base_dir=../../../specifications-BASE \
    -a uml_export_dir=../UML \
    -a pdf-style=openehr_full_pdf-theme.yml \
    -a pdf-stylesdir=../../../spec-publish-asciidoc/resources \
    -r asciidoctor-pdf -b pdf --out-file=ADL2.pdf --trace master.adoc
```

The .adoc source of that text is:

```
The old quoting rules based on XML/ISO mnemonic patterns (`&ohmgr;` etc) are replaced by specifying ADL to be UTF-8 based, and any exceptions to this requiring ASCII encoding should use the `\Uhhhh` style of quoting unicode used in various programming languages.
```

**Comment by mojavelinux** [comment]
I doubt that the hang is related to the warning. The warning is caused because you have a named entity that isn't one of the built-in XML entity names. Though, looking at your source, you probably want to escape them, so you need to add a passthrough:

```
`+&ohmgr;+`
```

I'll try to run the document and see if I can figure out what's causing Asciidoctor to hang.

**Comment by mojavelinux** [comment]
It took awhile, but the PDF eventually finished (all 166 pages). Are you sure it's hanging indefinitely?

I noticed that you are adding an image before the document title? As a result, a formal title page is not created. Is this intentional? (The title page does support a graphic if that's what you are trying to achieve. However, I have a feeling it has to do with #233).

**Comment by wolandscat** [comment]
I wondered about a passthrough, I have used it elsewhere, but wasn't sure if the backquotes were being read as purely monospace format, or as protecting the contents from processing as well.

The appearance of the specs is as you see [here](https://rawgit.com/openEHR/specifications-AM/master/docs/ADL2/ADL2.html) - the front page in the PDF would be down to the end of the licence block (i.e. the Amendment Record would start on a new page. So if you add in page breaks and headers and footers, you can more or less imagine this in PDF.

I did manage to get a PDF for some of the docs. Not too pretty yet - I suspect we need to wait for the next release of asciidoctor-pdf to make more progress on them.

**Comment by mojavelinux** [comment]
> wasn't sure if the backquotes were being read as purely monospace format

They are not. See explanation here: http://asciidoctor.org/docs/migration/#migration-cheatsheet

> I did manage to get a PDF for some of the docs.

Is there a doc that you cannot generate? If so, I'd like to focus my attention on debugging it.

**Comment by wolandscat** [comment]
To replicate things, I think the following should work.

Setup:

* nothing special on the asciidoctor side
* other than pygments. See [here](https://bitbucket.org/thomas_beale/pygments-main/src/818aab0a0687c6a0a5ec02ecfd3a64273cd8d474/pygments/lexers/archetype.py?at=default) for the lexer file that I use for the various syntaxes in the docs. 
* to make the above work, it needs an install of pygments.rb (as we already discussed, that's not well designed - it contains a static copy of an older pygments release in 'vendor'. I just replace this whole thing with a new copy, including my syntax file. Then you have to run 'cache-lexers.rb' in the root of pygments.rb.

The above pygments stuff can possibly be ignored - it just means asciidoctor will not know most of the syntaxes and just render everything in some default way (but... see below).

If you then do the following you should be able to replicate PDF problems for 3 of our larger sized docs.

```
$ git clone https://github.com/openEHR/spec-publish-asciidoc.git 
$ cd spec-publish-asciidoc
$ ./publish.sh          # this will generate the HTML
$ ./publish.sh -pt     # this will (try to) generate PDF; -t = trace
```
Have a look at the `publish.sh` script to see how it builds the command line.

Currently, this appears to hang on the ADL2 document. I do wonder if this is to do with pygments somehow, because if the Pygments lexer gets stuck in a state, it will hang. But.... everything works properly in HTML, so the lexer looks right to me. If you hit ctrl-C once, it goes onto the AOM2 doc, which it does generate, and then the ODIN doc. If you compare syntax colouring in ODIN.html with ODIN.pdf, you'll see they are different, but I don't know why that is - something strange is happening there.

The root doc file of all docs is `master.adoc`; you'll see a bit of tricky including to get boilerplate, references etc pulled in. You'll also see the TOC set up in a way that makes sense for generated HTML, but clearly doesn't work for PDF. The `publish.sh` script sets up the command line properly to make the inclusions work.

I have not worked much on making the PDF side work in the last few weeks - but there are many things not working, some of which probably just need tweaks:

* PNG images - much too small
* SVGs of UML - about the right size, but rendering is a total mess (BTW we removed graduated backgrounds)
* table cell colouring - not working (discussed elsewhere)
* various para types which can probably be fixed in the yml files (see `resources` dir)

PDF running header / footer is sort of working ok. See the HTML for the proper appearance of the docs.

**Comment by mojavelinux** [comment]
> If you compare syntax colouring in ODIN.html with ODIN.pdf, you'll see they are different, but I don't know why that is - something strange is happening there.

This probably has to do with this fix coming in 1.5.0.alpha.9.

https://github.com/asciidoctor/asciidoctor-pdf/commit/0ca198fbdda6f61dad47d8dd1045d68cbe3fac7c

There was an error in the HTML parser that was preventing the styles from being interpreted correctly. It was the HTML generated by Pygments, in particular, that was being affected.

**Comment by mojavelinux** [comment]
> SVGs of UML - about the right size, but rendering is a total mess (BTW we removed graduated backgrounds)

Progress is being made on Prawn core and Prawn SVG to get SVGs rendering better. The Prawn SVG author knows his stuff, so I'm confident that SVG rendering is going to continue to improve over time. It's important that we raise these issues in Prawn SVG as we find them so that we can be sure they are being addressed.

To provide a bit of background, the SVG must be parsed, interpretted and translated into PDF objects as PDF doesn't have native support for SVG objects. I'm quite amazed at how well it works already considering this is what has to be done. Prawn SVG is (or needs to be) a complete implementation of an SVG "viewer".

**Comment by mojavelinux** [comment]
> PDF running header / footer is sort of working ok. 

I've added some more controls in 1.5.0.alpha.9 that should get us a step closer to the look you're after. And, of course, we can continue working at it.

**Comment by mojavelinux** [comment]
> PNG images - much too small

This happens because you are using a percentage value in the width attribute, which is not technically legal (though does work in the HTML due to non-conforming browser behavior). The proper solution here is to add `pdfwidth=50%` or another measurement value (such as 4.25in). I believe we previously discussed the problem w/ percentage widths for HTML. It's something we still need to solve, but the browser kind of has our hands tied.

**Comment by mojavelinux** [comment]
Note that the names of the built-in fonts is going to change in 1.5.0.alpha.9. You'll need to update your font catalog as follows:

```yaml
font:
  catalog:
    Noto Serif:
      normal: notoserif-regular-subset.ttf
      bold: notoserif-bold-subset.ttf
      italic: notoserif-italic-subset.ttf
      bold_italic: notoserif-bold_italic-subset.ttf
    M+ 1mn:
      normal: mplus1mn-regular-ascii-conums.ttf
      bold: mplus1mn-bold-ascii.ttf
      italic: mplus1mn-italic-ascii.ttf
      bold_italic: mplus1mn-bold_italic-ascii.ttf
    M+ 1p Fallback:
      normal: mplus1p-regular-fallback.ttf
      bold: mplus1p-regular-fallback.ttf
      italic: mplus1p-regular-fallback.ttf
      bold_italic: mplus1p-regular-fallback.ttf
  fallbacks:
    - M+ 1p Fallback
```

However, it makes me realize that it would be nice if you could "import" the default font catalog in a custom theme without having to redefine the whole thing. Perhaps something like:

```yaml
font:
  catalog: @default
```

wdyt?

**Comment by mojavelinux** [comment]
> this appears to hang on the ADL2 document.

It works for me, it just takes a long time (a minute or so) and gets my fan going. If I disable syntax highlighting, it goes quicker, but still chews on it.

**Comment by mojavelinux** [comment]
40 seconds w/o syntax highlighting, 50 seconds with syntax highlighting.

Part of the reason the PDF generation is slow is due to PNG decompression. Ruby is incredibly slow at decompressing PNG files. One solution is to have your script decompress them ahead of time using ImageMagick (which has the tradeoff of creating enormous temporary files).

```
convert -define png:compression-level=0 \
  -define png:compression-filter=0 \
  -define png:color-type=2 \
  "$i" "$i-uncompressed.png"
```

**Comment by mojavelinux** [comment]
I'm able to shave off about ~10 seconds with the image optimization.

**Comment by wolandscat** [comment]
For the SVG rendering-in-PDF problem - I wonder if there should be a 'png' alternative specifiable somehow. Our UML extractor produces svgs and PNGs (obviously the latter at some fixed size). So wherever I have an image include line for an svg (which we want for web), a PNG is actually available.

Could it make sense for the short/medium term while prawn gets sorted out to have a :use_svg_alternative_in_pdf: kind of directive, where obvious aternatives like PNG, JPG etc would be looked for?

**Comment by wolandscat** [comment]
Font catalog - dumb question: if my custom theme just doesn't have a 'catalog' section, isn't the assumption that the default theme catalog is being used? I thought that would be the idea for all settings in a differentially expressed custom theme. Since you're not saying that I'm missing something obvious here...

**Comment by wolandscat** [comment]
RE: different behaviour on same syntax in HTML and PDF - if the colourisation is occurring properly and quickly on HTML, but taking a long time on PDF, what's happening? I see from the fix you referred to that the PDF one is probably choosing a fallback syntax highlighter, but if I do the same manually (e.g. just remove a [source, odin] line or whatever, the HTML still renders at normal speed in wrong colours. I don't like not knowing why CPU is being hit hard! Any ideas on that?

**Comment by mojavelinux** [comment]
>  I wonder if there should be a 'png' alternative specifiable somehow.

There is already. Just add the following in your document's header:

```
ifdef::backend-pdf[:diagram-ext: png]
ifndef::backend-pdf[:diagram-ext: svg]
```

Then use this attribute in the path to the image:

```
image::diagram.{diagram-ext}[]
```

Voila!

**Comment by mojavelinux** [comment]
> if my custom theme just doesn't have a 'catalog' section, isn't the assumption that the default theme catalog is being used?

For now, I decided that the base theme should not add any fonts (it just references the built-in, AFM fonts). That's why I'm proposing that we add a simple keyword for loading them. That way, the behavior can be controlled.

**Comment by mojavelinux** [comment]
> but still chews on it.

...meaning, still chews on PDF creation, not syntax highlighting. PDF creation still isn't the most efficient process. There are some things we can do, but a lot of this is going to be up to how well Prawn can perform. My instinct tells me that a lot of the time is spent dealing with the image data.

**Comment by mojavelinux** [comment]
Where are we with this issue? I'm looking for an actionable item. If there are still outstanding issues, it would be better if you opened discrete issues that focus on a specific problem. That way, I can schedule it, solve it, and make the fix part of a release.

**Comment by wolandscat** [comment]
Give me a few days to look back into this and try to reproduce the original problem, and I'll signal the result here.

**Comment by Hextremist** [comment]
Actually, decompressing is not that slow.  What is really slow is processing the alpha channel.  I did a test where I included an image of of size 3500x2500 pixels.  With jpeg, this completed in under 1 second.  With stripped alpha channel it took 1.5 seconds and with alpha channel it took no less than 9.5 seconds.

https://github.com/prawnpdf/prawn/issues/952

Btw, the alpha channel may be removed by the help of ImageMagick:
convert input.png -alpha off output.png

**Comment by mojavelinux** [comment]
Thanks for the insight @Hextremist. I'd be happy to add this tip the README.

Keep in mind, another solution is to install prawn-gmagick, which accelerates image processing considerable. (This tip is already mentioned in the README).

**Comment by mojavelinux** [comment]
This issue turned into a general conversation. While useful, it's not actionable. Therefore, I'm going to close it out now. If there are still outstanding issues, please file them in dedicated issues so we can take action to address them. Thanks!
