### ISSUE TITLE
Inline images don't work in normal table cells

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#295]
Inline images don't work in non-AsciiDoc table cells. Likely the callbacks for rendering inline images need to be registered specifically on the table cell so that they get invoked.

**Comment by mojavelinux** [comment]
Actually, they do work, so long as they fit within the table cell. If the image is too big to fit in the table cell, it will not show. The cell should be expanded in size to fit the image (or the restriction needs to be documented).

**Comment by mojavelinux** [comment]
...so to reproduce the issue, make the image width sufficiently large.

**Comment by wingfire** [comment]
Do you have an easy way to adjust the height of the cell/row?

**Comment by mojavelinux** [comment]
Not at the moment. The height adjusts based on the text content.

**Comment by mojavelinux** [comment]
I gave my answer assuming you were asking whether it's possible to set the height from AsciiDoc. I'm sure there's a way we can tell Prawn to increase the height internally.

**Comment by davidfavor** [comment]
Comments suggest this has been fixed + still appears broken.

This works...

image::/your-connection-is-not-private.jpg[]

This fails...

[cols="2*^"]
|===
|image::/your-connection-is-not-private.jpg[]|Cell #1-2
2+|Cell #2
|===

**Comment by davidfavor** [comment]
Hum...

image: (one colon) seems to work + image:: (two colons) seems to fail.

**Comment by mojavelinux** [comment]
You are correct. One colon is an inline image, and that works in table cells (with the exception that the image must fit within the size of the cell). Two colons is a block image and that doesn't work yet because Asciidoctor PDF doesn't yet support AsciiDoc table cells. See #6.

**Comment by mojavelinux** [comment]
Even with the fix for #620 (and even #388), it seems like we have an ordering issue in the calculation. The image cell is trying to make a determination about the available space for the image and getting it wrong. I can't even quite determine how it is doing the calculation.

The best workaround is to size the image so it's small enough to fit in the cell.

**Comment by mojavelinux** [comment]
Aha!!! I figured it out. When we set the font properties on the placeholder fragment, we aren't distributing the height correctly. This leads to a negative line gap, which causes the cell to not leave enough space for the image. I'll submit a patch to correct these assignments.

**Comment by lukesahula** [comment]
Is this issue really resolved? I am using Asciidoctor PDF 1.5.0.alpha.13 and I am experiencing exactly the same thing. I have a table with 2 columns, the first one containing an image, the second one its description. When the description is stretched across more lines, the image gets shown when it is small enough, but if its bigger, then there is an empty space even though the row itself is much higher than the text in the second column.

**Comment by mojavelinux** [comment]
Could you please retest with the latest release of Asciidoctor PDF? The latest release is 1.5.0.alpha.16.

**Comment by lukesahula** [comment]
Right, my mistake, it is indeed working. Thank you for the answer.
