### ISSUE TITLE
Set line height of text in table cell

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#296]
The the line height (specified using the "leading" property) on the text in a monospaced table cell. Right now, it's using a line height of 1, which looks pretty bad when the line wraps.

**Comment by mojavelinux** [comment]
The same has to be done for literal table cells.

**Comment by mojavelinux** [comment]
Actually, this isn't limited to literal or monospaced table cells. The line height (and line metrics in general) aren't being set for any table cells.

**Comment by madmas** [comment]
👍 for this one ;-) I'm surprised to see taht it has not been of more interest for so long - is noone using tables in a custom themed document? ;-)
Would be happy to help out, but I need to find someone to give me a quick dive into the ruby sources first ;-)

**Comment by madmas** [comment]
Proposed a fix in #838 and provided a example.

**Comment by mojavelinux** [comment]
Thanks @madmas!

You've got the right area of the code, but there's one piece still missing. We can't rely on Prawn's "leading" functionality alone since it is incomplete. We have to also apply some of our own padding above and below the prose to ensure all lines get the spacing. We have to do something similar for paragraphs. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L3033-L3043.

I realize this is massively confusing. But Prawn gets line heights wrong (at least when compared to CSS) and we have to compensate.
