### ISSUE TITLE
readme.adoc , basic-examples adoc link broken

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#298]
link to basic examples is broken: https://github.com/asciidoctor/asciidoctor-pdf/blob/9d7ddc77bb73a868855f8d68056ca0e9865deebd/blob/masterexamples/basic-example.adoc

**Comment by mojavelinux** [comment]
It looks like the upgrade to Asciidoctor 1.5.2 "broke" the links in that the relfileprefix was introduced in 1.5.x and finally got activated...except it had the wrong value. We don't need it anyway, so I just dropped it.

**Comment by mojavelinux** [comment]
Thanks for pointing this out, @rlopez133!
