### ISSUE TITLE
Table align is not honored

### ISSUE THREAD

**Issue by kongou-ae** [asciidoctor/asciidoctor-pdf#299]
The "align" attributes of table is not supported?

My environment is "Asciidoctor PDF 1.5.0.alpha.9 using Asciidoctor 1.5.2". This Asciidoctor PDF  changes this adoc into this image.

```
[.text-center]
.ほげほげ一覧
[align="right",width="50",cols="<1,^1,^1",options="header,strong"]
|=======================
|Col 1|Col 2      |Col 3
|1    |Item 1     |a
|2    |Item 2     |b
|3    |Item 3     |c
|=======================

ああああ

[.text-center]
.ほげほげ
[align="center",width="50",options="header"]
|=======================
|Col 1|Col 2      |Col 3
|1    |Item 1     |a
|2    |Item 2     |b
|3    |Item 3     |c
|4    |Item 4     |d
|=======================

```

![](http://aimless.jp/blog/wp-content/uploads/2015/08/asciidoctor-pdf-table-align.png)

If not support, is it possible to center the table in the page in a different way?

**Comment by mojavelinux** [comment]
I guess we hadn't thought of it yet because we always had tables that are 100%. Prawn Table supports it, so we just need to implement it.

**Comment by mojavelinux** [comment]
It will be necessary to use the role "left", "center" or "right" to be consistent with how the HTML works.

```
[.center, width=50%]
|===
|Column A |Column B

|A1
|B1

|A2
|B2
|===
```

**Comment by mojavelinux** [comment]
I decided to implement the align attribute as well as an alternative (though this doesn't currently work in the HTML converter).

**Comment by kongou-ae** [comment]
Thanks. Using `.center` , I can place the table in the center.
```
.ほげほげ一覧
[.right,width="50",cols="<1,^1,^1",options="header,strong"]
|=======================
|Col 1|Col 2      |Col 3
|1    |Item 1     |a
|2    |Item 2     |b
|3    |Item 3     |c
|=======================

ああああ

.ほげほげ
[.center,width="50",options="header"]
|=======================
|Col 1|Col 2      |Col 3
|1    |Item 1     |a
|2    |Item 2     |b
|3    |Item 3     |c
|4    |Item 4     |d
|=======================
```

![](http://dev.aimless.jp/images/result.png)
