### ISSUE TITLE
Incorrect fonts referenced in the theme

### ISSUE THREAD

**Issue by otavio** [asciidoctor/asciidoctor-pdf#300]
/home/otavio/.gem/ruby/2.2.0/bundler/gems/asciidoctor-pdf-23a4f951666b/data/fonts/notoserif-regular-latin.ttf not found
  Use --trace for backtrace

**Comment by mojavelinux** [comment]
As I mentioned in the release notes, you have to update the font names if you are using a custom theme.

See https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.5.0.alpha.9

**Comment by otavio** [comment]
However the asciidoctor theme is outdated in the source code; I copied it over mine and it fails.

**Comment by mojavelinux** [comment]
Are you sure you are using Asciidoctor 1.5.0.alpha.9? I can't tell from the bundler path you posted since it looks like a development checkout.

**Comment by otavio** [comment]
I am current tip: 23a4f951 and this can be seen in the patch ;-)

So I am in today's tip.

**Comment by mojavelinux** [comment]
Thanks for the clarification.

You can see that the font names are as follows:

https://github.com/asciidoctor/asciidoctor-pdf/tree/master/data/fonts

And that should line up with what I recommended in the release notes:

https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.5.0.alpha.9

Can you spot where the error is? I'm looking, but I'm not seeing any misalignment.

Are you using a custom theme (yml) file?

**Comment by otavio** [comment]
I got what I did wrong; when I tried to sync up the theme, it was copied from the older release so it didn't work.

I now redid the sync and it works like a charm.

Sorry for the noise.

**Comment by mojavelinux** [comment]
\o/

Sorry for messing up your workflow. I'm trying to get all the breaking changes wrapped up asap (many in alpha.9) so that we can get beyond alpha and into stability.
