### ISSUE TITLE
/ViewerPreferences [/FitWindow]

### ISSUE THREAD

**Issue by THausherr** [asciidoctor/asciidoctor-pdf#303]
I found this in a PDF created with your software:
```
1 0 obj
<< /Title (Example Manual)
/Author (Doc Writer)
/Creator (Asciidoctor PDF 1.5.0.alpha.9, based on Prawn 1.3.0)
/Producer (Doc Writer)
/CreationDate (D:20150807192809+02'00')
/ModDate (D:20150807192809+02'00')
>>
endobj
2 0 obj
<< /Type /Catalog
/Pages 3 0 R
/Names 14 0 R
/Outlines 70 0 R
/PageLabels 86 0 R
/PageMode /UseOutlines
/ViewerPreferences [/FitWindow]
>>
endobj
```
Viewer preferences dictionary is a dictionary, not an array. Such wrong PDFs can result in problems with PDF software, as shown here:
https://issues.apache.org/jira/browse/PDFBOX-2924

**Comment by mojavelinux** [comment]
Can you explain what it should be?

I believe I set it this way because it's the only thing that made evince work correctly. Of course, I'll try it with the way you propose to verify that evince responds to a dictionary as well.

**Comment by THausherr** [comment]
Probably like this:
```
/ViewerPreferences <</FitWindow true>>
```

**Comment by mojavelinux** [comment]
Thanks for the clarification.

I learned a few things here. First, that `/ViewerPreferences` is indeed supposed to be a map. Once I switched to a map, I realized that `/FitWindow` isn't the preference we want anyway. That adjusts the window size to fit the initial magnification, which is not what we want. Instead, we need to use `/OpenAction` to control the initial magnification (and the first page to open, which we'll set to page 1 for now).

I'm also going to enable the `/DisplayDocTitle` to show the document title in the window title bar.

**Comment by mojavelinux** [comment]
How does the solution in #304 look to you, @THausherr?

**Comment by THausherr** [comment]
I would have to see a PDF generated with your software. I am not a user of your software, I just got in trouble with a software generated with your product. Either point me to an URL where it is (maybe in the repository), or e-mail it to me here: tilman at snafu dot de.

**Comment by mojavelinux** [comment]
Oops! I forgot to regenerate the example PDF files. Once I do that, you can pull it directly out of the repo. Stay tuned.

**Comment by mojavelinux** [comment]
@THausherr I have made the example PDFs available in the following directory:

https://github.com/asciidoctor/asciidoctor-pdf/tree/master/examples

Here's how the header is now written:

```
2 0 obj
<< /Type /Catalog
/Pages 3 0 R
/Names 15 0 R
/Outlines 22 0 R
/PageLabels 25 0 R
/PageMode /UseOutlines
/OpenAction [7 0 R /FitH 793.0]
/ViewerPreferences << /DisplayDocTitle true
>>
>>
endobj
```

**Comment by THausherr** [comment]
2 files were updated, but these 2 don't have any ViewerPreferences?!

**Comment by mojavelinux** [comment]
It's there, but these files have compression applied so the settings are in
a compressed stream. Do they open okay?

**Comment by THausherr** [comment]
I answered several days ago, and my comment is gone?!

this is the basic-example.pdf file:


```
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Outlines 5 0 R
/PageLabels<<
/Nums [0 <<
/P (i)
>> 2 <<
/P (2)
>>]
>>
/Metadata 44 0 R
>>
endobj
```

no /OpenAction, no /ViewerPreferences.

**Comment by mojavelinux** [comment]
> I answered several days ago, and my comment is gone?!

:worried: That's troubling. Are you sure it posted? The last notification I received was the comment from Aug 13 (5 days ago), so perhaps the browser didn't submit it successfully (or the other end didn't receive).

I'll go ahead and link to an uncompressed version of the file so that you can see the output exactly as it is generated.

* Gist: https://gist.github.com/mojavelinux/95fade7b8dfc24e3b4da
* Direct link to PDF: https://gist.github.com/mojavelinux/95fade7b8dfc24e3b4da/raw/d1cf6349b45fce195fc6a5273d1fc60c765afb48/basic-example.pdf

Note that it was generated from the master branch, not from a release.

**Comment by THausherr** [comment]
The new file is fine, both internally and does have the expected effects when opening with Adobe Reader. The file from 6 days ago doesn't.

**Comment by mojavelinux** [comment]
\o/

**Comment by mojavelinux** [comment]
Thanks for testing!
