### ISSUE TITLE
Callout support

### ISSUE THREAD

**Issue by gibiansky** [asciidoctor/asciidoctor-pdf#31]
`asciidoctor-pdf` does not seem to support callouts. Is there a way to enable this?

This may or may not be related to https://github.com/asciidoctor/asciidoctor-pdf/issues/15, I'm not sure.

**Comment by plaindocs** [comment]
This still does not work in asciidoctor-pdf.
I get the icon after the code block, but there is no substitution inside the code block.

**Comment by yfain** [comment]
Callouts are generated fine for HTML, but when I use asciidoctor-pdf, I'm getting "asciidoctor: WARNING: conversion missing in backend pdf for inline_callout" and no callouts are included in the PDF file". Is there a workaround for this problem? I'm using Asciidoctor 1.5.2.

**Comment by mojavelinux** [comment]
These are not yet implemented. It's on the roadmap for Asciidoctor PDF 1.5.0. The inline stuff like callouts and icons are one of the first things I'll get working once I pick it back up again...maybe at a hackergarten :)

**Comment by plaindocs** [comment]
Is there a list of what is not implemented in asciidoctor-pdf?

**Comment by mojavelinux** [comment]
It's mostly just the inline imagery because it requires special handling to make it work in Prawn. I've filed many of the issues against the 1.5.0 milestone. See https://github.com/asciidoctor/asciidoctor-pdf/milestones/v1.5.0

**Comment by mojavelinux** [comment]
> I get the icon after the code block, but there is no substitution inside the code block.

Callouts work with pygments, but not with coderay. The code used when the source highlighter is pygments just needs to be ported to the section on coderay.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L656-L672

We can probably do it cleaner too. That was just a quick hack.

**Comment by plaindocs** [comment]
Callouts work with pygments, but not with coderay.
DEFINITELY needs to be in the docs. :-p

**Comment by mojavelinux** [comment]
Or just fixed :) It probably won't take me much longer to make it right.

**Comment by mojavelinux** [comment]
All cases of using callout numbers should now be covered. Of course, if you find a corner case, please speak up!

**Comment by r0ckarong** [comment]
Again me with the non AFM font =) Callouts are not supported and fall back to the "not" glyph in the coderay hightlighted blocks and to the correct number but in the wrong color (white).

![screenshot from 2017-04-03 14-29-48](https://cloud.githubusercontent.com/assets/4920542/24609164/0b8045ea-187a-11e7-9bab-39d98ec9d5a5.png)

**Comment by mojavelinux** [comment]
> EDIT: Forget it, just have to set literal to a supported font manually then it will work.

Yep. For now, I strongly recommend using the provided M+ 1mn font as it has the necessary characters. Once there is a guide available for how to rebuild the monospace font, then it will be worth the time to look for a replacement.

**Comment by RemonSinnema** [comment]
For me, the callout numbers only work up to and including 20. In HTML there are all there, but in PDF they are not. For instance, in the image below numbers 21-24 are missing:
![no_callout_numbers_over_20](https://cloud.githubusercontent.com/assets/3496035/26819440/1e3f058e-4a9f-11e7-87fe-1a90258e991f.png)

**Comment by mojavelinux** [comment]
You are correct. There are only 20 circled numbers in Unicode, so that's how far we can go. We'd have to stop using special glyphs at that point and switch to regular numbers if we wanted to support it. However, more than 20 numbers in a callout list is really a usability issue.
