### ISSUE TITLE
Failed to parse formatted text: URL extraction

### ISSUE THREAD

**Issue by orloffm** [asciidoctor/asciidoctor-pdf#311]
Compiling this:

```
Test
====

http://ya.ru/{nbsp}&#8212; see this.
```

yields this:

```
Failed to parse formatted text: <a href="http://ya.ru/&#160;&#8212" class="bare">http://ya.ru/&#160;&#8212</a>; see this.
```

I'm using {nbsp} here to keep a space before em-dash.

Can this be fixed, or should I decorate the em-dash with spaces some other way? In Russian typography (and in European in general, I think) em-dashes are surrounded with space, and the preceding should not be a line break.

**Comment by mojavelinux** [comment]
I believe if you write it as follows it will work:

```
link:http://ya.ru/[] -- see this
```

I noticed that if you take away the macro syntax and just use a raw URL, then the dash gets caught up in the link, but only in Asciidoctor PDF. That looks like a bug in the parser.

**Comment by mojavelinux** [comment]
I reported this problem upstream as https://github.com/asciidoctor/asciidoctor/issues/1490.

**Comment by mojavelinux** [comment]
Since this problem has to do with the parser, and not with Asciidoctor PDF, I'm closing the issue on this side. Currently, the emdash following a URL gets caught up in the link because the adjacent `&#8201;` is a valid sequence for a URL. We'll deal with it in core (and the language spec).
