### ISSUE TITLE
Show UI macros in PDF output

### ISSUE THREAD

**Issue by jniggemann** [asciidoctor/asciidoctor-pdf#313]
I frequently write manuals and one of the features for which I prefer using asciidoctor over pandoc (i.e. asciidoc oder markdown) are the UI macros, especially kbd shortcuts.

Given that ATM they are still experimental, I understand that UI macros haven't yet made it to asciidoctor-pdf. 
- kbd shortcuts result in just the word being written
- menu selections are displayed with a pipe symbol instead of a triangle.

I thought I open a ticket so this can be tracked...

**Comment by mojavelinux** [comment]
Thanks for reporting @jniggemann. You are correct that we don't yet style these elements. However, we have all the raw material in place that we would need in order to do it, so let's just schedule it to happen.

Regardless of how the macros get enabled, Asciidoctor PDF will still need to style them, so I think we should proceed despite the experimental label.

**Comment by mojavelinux** [comment]
> menu selections are displayed with a pipe symbol instead of a triangle.

This part of the issue is now resolved and will be available in the 1.5.0.alpha.12 release.

**Comment by jniggemann** [comment]
Great to hear, thank you! I'm looking forward to test this and I'll report back...

**Comment by jniggemann** [comment]
I confirm menu selections working in 1.5.0 Alpha 12 :-)
Thank you very much!

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
We still have the kbd macro remaining.

**Comment by jniggemann** [comment]
> We still have the kbd macro remaining.
I'm ready for testing and waiting :-)

**Comment by CapitanPrimate** [comment]
Hello.

Any news about supporting the kbd macro?

Thanks in advance!

**Comment by elmajime** [comment]
Hi!

I'm really looking forward to this feature as it could enable my team to move all our documentation to Asciidoctor!

Do you have any news to share?

**Comment by n2o** [comment]
We would also love to see this feature in asciidoctor-pdf :+1:

**Comment by mojavelinux** [comment]
Now that the background color and border is supported for a phrase, we can move forward with this. We just need to port the logic used for the button. See #451.

**Comment by mojavelinux** [comment]
It's now possible to control the style of the menu, button, and key (kbd) elements in one form or another. There are still some limitations due to the capabilities of Prawn, but you should be able to get pretty close to the styling you'd use in HTML/CSS.

**Comment by mojavelinux** [comment]
Refer to the theming guide for details.

**Comment by jniggemann** [comment]
This is great, thank you very much for your hard work!
I'll try this ASAP, but in this case ASAP means after the summer holidays.

**Comment by edward-encoord** [comment]
I can confirm it works perfectly with `Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.17`:

![image](https://user-images.githubusercontent.com/88771308/162213835-8e036dad-e1e9-44e2-85fd-c283b221412c.png)

**Comment by mojavelinux** [comment]
Thanks for confirming!
