### ISSUE TITLE
How do I create lists within a table cell?

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#315]
What I currently have:

```
|====
^|Revision ^|Release Date ^|Author(s) ^|Notes

^| 1.1 ^| Wednesday Sept 9, 2015 ^| Joe Talerico, Roger Lopez ^a| * Grammatical error and acronym fixes 
^| 1.0 ^| Friday July 17, 2015 ^| Joe Talerico, Roger Lopez ^a| * Initial Release
4+^.e| PDF generated by https://github.com/asciidoctor/asciidoctor-pdf[Asciidoctor PDF]
|====
```

I read in the syntax guide that all I needed to put was an "a" in front of the cell and that would work but its not working for me. I'm sure I'm just doing it wrong.

**Comment by mojavelinux** [comment]
AsciiDoc table content still isn't supported yet. That includes lists, so it's covered by #6.
