### ISSUE TITLE
PDF backend not rendering block titles for lists

### ISSUE THREAD

**Issue by k-mack** [asciidoctor/asciidoctor-pdf#316]
Hi, 

I'm using the Gradle plugins to build my documents, and I'm having trouble getting the PDF backend to render block titles for lists and checklists. They do render for plain text. Below is the example I'm using.

= Tests

\.Test1
Test

\.Test2
\* Test

\.Test3
\- Test

\.Test4
\- [ ] Test

They render with the HTML5 backend but not with the PDF backend.

**Comment by mojavelinux** [comment]
As a workaround until there's a solution, I recommend using a discrete heading.

```
[discrete]
=== Test

* item
* item
* item
```

**Comment by k-mack** [comment]
Good point. I forgot about discrete headings.
