### ISSUE TITLE
Bug with empty adoc files / only a first row title 

### ISSUE THREAD

**Issue by cbouveresse** [asciidoctor/asciidoctor-pdf#317]
Hi,

I've been looking to debug the following build failure in my Asciidoctor **Maven** project (plugin version 1.5.2.1) for 2 hours...  And I've finally found a simple issue on asciidoctor pdf.

BUILD FAILURE:

```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:
process-asciidoc (generate-pdf-doc) on project asciidoctor-pdf-example: Executio
n generate-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:proc
ess-asciidoc failed: (NoMethodError) undefined method `margins' for nil:NilClass
```

Let's explain the issue with the [asciidoctor-pdf-example](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example) from Asciidoctor Maven Examples. 

Let's modify the content of a [random .adoc file](https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoctor-pdf-example/src/docs/asciidoc/example-manual.adoc) from this project:

**If I empty the file content , build failure:**

```

```

**If I only put a main title in this in the file, build failure:**

```
= Main Title
```

If I only put a second title content in the file, build success:

```
== Main Title
```

**If I put a main title with content in the file, build failure:**

```
= Main Title
a
```

If I put a main title, skip a line, and put content in the file, build success:

```
= Main Title

a
```

I therefore suppose this small issue comes from Asciidoctor PDF ! HTML works well.

**Comment by mojavelinux** [comment]
This definitely seems like an Asciidoctor PDF issue. I'll mark it as a bug and schedule to get it fixed for the beta.

**Comment by mojavelinux** [comment]
This was fixed by https://github.com/asciidoctor/asciidoctor-pdf/commit/31d7c2740ddb2353dfe8c0425b7bb1fa4450dea5, which was included in the alpha.13 release.
