### ISSUE TITLE
Allow to embed an image in base64

### ISSUE THREAD

**Issue by flarcher** [asciidoctor/asciidoctor-pdf#318]
Hello, 

I would like to insert an image in the generated PDF having the Blob in the _base64_ format. 
This is related with the closed issue https://github.com/asciidoctor/asciidoctor/issues/986 ( I would like to do the same with the PDF backend ).

I tried to add
```
image::data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==[]
```
in the document and I got in the logs the following line :
```
asciidoctor: WARNING: image to embed not found or not readable: data:image/png;base64,iVBOR...
```
Here is the command returned by the logs :
```
asciidoctor -B /home/fabrice/tmp -S SAFE -o /home/fabrice/tmp/test.pdf -b pdf -a docdate=2015-09-10 -a data-uri -a allow-uri-read -a doctime=11:34:51 CEST -a icons=font -
```

I am using `org.asciidoctor:asciidoctorj:1.5.2` and `org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.9`. 
Is there a workaround ? Or is it planed for a coming release ?
Many thanks

_PS : Was actually the issue https://github.com/asciidoctor/asciidoctor/issues/1481 (created in wrong project)_

**Comment by mojavelinux** [comment]
There's no known workaround. This will require a code change. Unlike the HTML backend, a data URI can't simply be passed through, so we have to do some processing internally to convert it to a PDF object.

**Comment by cmgdev** [comment]
This seems to be top search result for embedding a base64 image with asciidoctor-pdf, so to save future searchers some heartache... 

There seems to be a typo in the original example. It should be:
> image:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==[]

Note that there is only one colon (:) after image, not two.

**Comment by mojavelinux** [comment]
@cmgdev that depends on whether the image is inline or standalone (block). If it's inline, you only use a single colon. If it's on a line by itself, the block form (two colons) is preferred. That's an AsciiDoc thing.
