### ISSUE TITLE
Default pdf-page-size

### ISSUE THREAD

**Issue by fwilhe** [asciidoctor/asciidoctor-pdf#319]
Hello,

the current default `pdf-page-size` is `US Letter`. Most of the world uses the `A` format (most commonly `A4`). I would like to discuss, if we could introduce this as the default format in `asciidoctor-pdf`.

Of course, one format has to be the default, and everyone prefers the one that she uses on a daily bases. I think going for the ISO standard is a reasonable choice.

Also, the property that the `A` format scales nicely to bigger and smaller sheets (two `A5` sheets being exactly one `A4`, etc, due to the aspect ratio) makes it superior format (in my completely biased point of view, at least).

Any thoughts on that?

**Comment by orloffm** [comment]
...and also the default font color isn't black, so it appears gray on Kindles. And font is quite small for A4. Etc, etc.

So just create your own style and have by your document.

**Comment by mojavelinux** [comment]
Most of the PDF writers I've seen use A4 by default, so it's clear that we should align with this default. We will need to check the fonts when we make this change to make sure they are properly sized (thanks for mentioning that @orloffm).

It's very likely that the Letter page size is a requirement that got inadvertently carried over from the contract for which we originally created Asciidoctor PDF. For general purpose, I think it's clear that A4 should be the default.

**Comment by mojavelinux** [comment]
> so it appears gray on Kindles

I'm assuming you mean a grayscale Kindle? If so, it's unfortunate that Kindle doesn't properly shade off-black text. It's well documented that slightly off-black text is better for readability on color screens (as it softens the otherwise stark contrast).

**Comment by orloffm** [comment]
Yes, I've got a Kindle DX. It has lower DPI then modern Kindles and the grayish text is blurry.

**Comment by mojavelinux** [comment]
That's really odd that the Kindle DX applies the CSS even though it is a black and white device. However, there is a solution for this. CSS has a media query for color devices. We should move all colors in the stylesheet inside that media query so that the black and white devices only see black and white color settings.

See http://www.sitepoint.com/web-foundations/media-queries/#d5e1351

**Comment by mojavelinux** [comment]
Oops, I was thinking we were talking about EPUB3. In the case of PDF, I'm not sure there is much we can do. Of course, you can use your own theme to set the text color in PDF.
