### ISSUE TITLE
Override "Figure" and "Table" from theme?

### ISSUE THREAD

**Issue by SandMann1** [asciidoctor/asciidoctor-pdf#320]
Is there a way to override the label figure and table ? I write in another language and need to override these labels to suit this language.

**Comment by mojavelinux** [comment]
Not via the theme, but you can do it via AsciiDoc attributes defined, among other places, in the header of your document:

```
= Document Title
:table-caption: Table
:figure-caption: Figure
```

For more information about this feature and its future, see https://github.com/asciidoctor/asciidoctor/issues/1129

**Comment by SandMann1** [comment]
Great. Thanks!

**Comment by mbartelsm** [comment]
Is there a way to change this but for chapters? Right now chapters are prefixed by "Chapter #." I'd like to know if there is a way to change this string and if there is a way to completely remove it

**Comment by mojavelinux** [comment]
Yes. It's `chapter-label` (though yet undocumented).

The following will turn it off.

```
:chapter-label:
```
