### ISSUE TITLE
Inserting an SVG title-logo-image renders a blank page after the ToC

### ISSUE THREAD

**Issue by fgoujeon** [asciidoctor/asciidoctor-pdf#322]
Inserting an SVG title-logo-image renders a blank page after the ToC.

Command line:
```
asciidoctor-pdf test.asciidoc
```

`test.asciidoc`:
```
= Title
:toc:
:title-logo-image: test.svg

== Section

Section text.
```

`test.svg`:
```
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="100" height="100">
  <rect width="100" height="100" x="0" y="0" fill="green" />
</svg>
```

I'm using these versions of Asciidoctor, Asciidoctor-pdf and their dependencies:

* addressable-2.3.8
* afm-0.2.2
* Ascii85-1.0.2
* asciidoctor-1.5.2
* asciidoctor-pdf-1.5.0.alpha.9
* coderay-1.1.0
* css_parser-1.3.6
* hashery-2.1.1
* minitest-5.4.3
* pdf-core-0.6.0
* pdf-reader-1.3.3
* polyglot-0.3.5
* power_assert-0.2.2
* prawn-2.0.2
* prawn-icon-0.6.4
* prawn-svg-0.21.0
* prawn-table-0.2.2
* prawn-templates-0.0.3
* rake-10.4.2
* rdoc-4.2.0
* ruby-rc4-0.1.5
* safe_yaml-1.0.4
* test-unit-3.0.8
* thread_safe-0.3.5
* treetop-1.5.3
* ttfunk-1.4.0

Thank you for your excellent work.

**Comment by mojavelinux** [comment]
I do know that if the image is too big, it will spill outside the bounds and potentially create a new page. We do need to truncate or resize the image so this doesn't happen. Until then, you can try to play around with the size of the image.

You can force a size using the inline image macro syntax:

```
:title-logo-image: image:test.svg[pdfwidth=50]
```

(pdfwidth can have units of pt, in, cm or mm)

**Comment by fgoujeon** [comment]
A 1*1 pixel SVG image also trigs the creation of a blank page, even if I force a pdfwidth of 1.

However, the insertion of the exact same image in PNG format doesn't cause any problem.

**Comment by mojavelinux** [comment]
Aha, that's the info I needed. I know exactly what that's happening. We need to reset the page after inserting the SVG. I'll get that fixed.

**Comment by mojavelinux** [comment]
This seems to only happen when the toc is enabled. So it's having an impact on how many pages are reserved for the toc. That's where the empty page is coming from.
