### ISSUE TITLE
List title not shown in output

### ISSUE THREAD

**Issue by sdaschner** [asciidoctor/asciidoctor-pdf#324]
When writing an AsciiDoc list with title, that title is not shown in the resulting PDF - tried with both the default and the base theme.

Following markup ...

```
= Test
Sebastian Daschner

.Hello World
- Lorem ipsum
- dolor
- sit amet.
```

... is converted into PDF missing the *Hello World* title, see screenshot - uploading the PDF in Github did not work somehow.

Did i miss something here?
![test](https://cloud.githubusercontent.com/assets/6815170/9991790/698d1efe-606d-11e5-9d77-f20e98505968.png)

**Comment by mojavelinux** [comment]
This is the same issue as reported in #316.

**Comment by sdaschner** [comment]
Hmm, I did indeed search for existing issues but haven't found that one, sorry 🙈

**Comment by mojavelinux** [comment]
No problem at all. I just wanted to make a note of the relationship so that I could be sure to wrap up both issues when I get to a fix...which I think I've got working.

**Comment by mojavelinux** [comment]
#316 is now fixed (in HEAD). Will be available in beta1 (or alpha10, if we decide to put out another alpha).
