### ISSUE TITLE
When adding backcover pdf, it adds an additional blank pdf page

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#328]
I can't say this happens everytime, meaning if you try on a very small doc example you won't necessarily see it. However, in our bigger documents, if I go and add a backcover pdf, the back cover pdf will be added, but an additional blank page is also added as well. 

Dan, can you check and see if you can reproduce this? I have many on my team that can produce this with alpha9. I've also experienced it with dev (pull date 9-10-2015) but probably still there on latest dev. 

Thanks,

Roger

**Comment by mojavelinux** [comment]
I'll take a look. Very likely has to do with the fact that the image is causing Prawn to advance to the next page and we're probably not checking for that.

Is there any way you can give me a sample project that reproduces the issue. That saves me a lot of time having to figure out how to reproduce it. Then I can get right to fixing it.

**Comment by mojavelinux** [comment]
Yep, I can see where the problem likely is. The PDF insertion process always adds a trailing page, but we aren't coming through and cleaning it up in that scenario. I'll make sure this page gets truncated.

**Comment by rlopez133** [comment]
Dan,

I apologize for not responding to this. I meant too and forgot too :) I tested it and works as intended using the latest dev.

**Comment by mojavelinux** [comment]
Thanks for verifying @rlopez133!
