### ISSUE TITLE
Title problems when using doctype book

### ISSUE THREAD

**Issue by mbartelsm** [asciidoctor/asciidoctor-pdf#329]
When I use the doctype book attribute in a document, book parts (level 0 title) render on the same page as lower attributes (ie: immediately after). But level 1 titles have page breaks before them.

The problem causes book parts (level 0 sections) to be rendered on the same page as text from previous parts, but any following  lower level titles are rendered on following pages. Also, chapter numbering completely ignores book parts, not resetting after them

But when the doctype is not set everything renders continuously and correctly, chapter numbers are reset after book parts and no weird page breaks are added, the only problem is that the "chapter" prefix is removed and the command prompt outputs an error reading "only book doctypes can contain level 0 sections", even though the PDF renders them correctly and correctly adds them to the TOC.

**Comment by mojavelinux** [comment]
The page-break behavior you are observing is because the doctype book setting is literally attempting to layout the content as a book (where chapters start on a new page). This was done to fill a requirement of Asciidoctor PDF when it was created. There is an open issue to make this behavior configurable via the theme. See #74.

Just so you are aware, it is possible to override the layout_chapter method if you are using the Asciidoctor PDF API. But that's a fairly advanced usage.

> chapter numbering completely ignores book parts, not resetting after them

This is just how AsciiDoc / Asciidoctor works. This is a change that would need to happen in core and is being discussed there. See https://github.com/asciidoctor/asciidoctor/issues/979.

**Comment by mojavelinux** [comment]
As a workaround for the page break issue, I recommend using the article doctype and ignoring the warning. The warning is actually harmless.

**Comment by mbartelsm** [comment]
Well, the issue is not really that chapters have pagebreaks, but the fact that parts do not, resulting in the following:
![untitled](https://cloud.githubusercontent.com/assets/5376208/10272975/0072d3b0-6aee-11e5-9cbe-bf87a65b9d4a.png)

**Comment by mojavelinux** [comment]
Ah, I see. Thanks for the clarification.

Parts were not in the original requirements for Asciidoctor PDF, so they didn't get implemented properly. But this still traces back to #74 that we need the correct page breaks and they need to be configurable. These issues are now linked, so it should be clear that we need to check all the levels.

**Comment by nathany** [comment]
Just ran into this issue today when generating a PDF with `:doctype: book` (rather than individual chapters). 

I wouldn't need it to be configurable (#74) if it just does what's expected for a given doctype.

**Comment by nathany** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=27163586)](https://www.bountysource.com/issues/27163586-title-problems-when-using-doctype-book?utm_source=27163586&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by vogella** [comment]
I'm currently putting in manually <<< but it would be nice if "=" puts in automatically a page break.

**Comment by mojavelinux** [comment]
I'm going to move this issue up to 1.5.0.alpha.13 and just add the page break for parts when the doctype is book. That way, we get sane behavior right away, and pursue configurability via the theme in #74.

**Comment by mojavelinux** [comment]
Let me know what you think of the implementation. See #527.

**Comment by vogella** [comment]
From what I can understand from reading the implementation: +2

**Comment by mojavelinux** [comment]
@nathany Is this the behavior you were hoping to have?

**Comment by nathany** [comment]
I can't tell by looking at the code -- and I'm not totally sure how to test it.

**Comment by mojavelinux** [comment]
@nathany I'm asking more about what your expectations are. As described above, I'm simply starting a new page at the beginning of a part (in addition to starting a new page at the beginning of a chapter). Does that match your expectations?

Btw, if you wanted to test the gem, you'd need to follow the steps described in: https://github.com/asciidoctor/asciidoctor-pdf#development. You can download the zip of the PR from https://github.com/mojavelinux/asciidoctor-pdf/tree/issue-329.

**Comment by nathany** [comment]
Yes, that's what I'm looking for.

I also changed my Gemfile and tested it out. Works great! Thanks.

```diff
- gem 'asciidoctor-pdf', '~> 1.5.0.alpha.12'
+ gem 'asciidoctor-pdf', github: 'mojavelinux/asciidoctor-pdf', branch: 'issue-329'
```

**Comment by mojavelinux** [comment]
> Yes, that's what I'm looking for.

:+1: Then I'll proceed with merging.

> I also changed my Gemfile and tested it out.

Ah yes, that works too. I've noted down to document these steps more clearly in the README.

**Comment by nathany** [comment]
Thank you Dan.
