### ISSUE TITLE
Rendering asciidoc to pdf on a mac

### ISSUE THREAD

**Issue by oliverkent** [asciidoctor/asciidoctor-pdf#347]
Hi, 

I would like detailed, simple instructions on how to do the above. I am a beginning TW and have only converted some asciidoc text to Html (as the default). 

I need to know how to download the proper plug-ins, and not just the commands. 

I am running on Mac osx el capitan, 10.11.1 

Many thanks!

**Comment by mojavelinux** [comment]
All the instructions you need should be here:

http://asciidoctor.org/docs/install-asciidoctor-macosx/

except you have to add one line at the end to get the `asciidoctor-pdf` command:

```
$ gem install asciidoctor-pdf --pre
```

**Comment by oliverkent** [comment]
I entered your line of command, $ gem install asciidoctor-pdf --pre, and is said Successfully installed pdf-reader-1.3.3

but when I commanded it thus: $ -b pdf /Users/oliverkent/Documents/DESK/asciidoc\ work/mysample.adoc

is still said -bash: -b: command not found

I don't know what I'm doing wrong.

**Comment by mojavelinux** [comment]
The command should be:

```
$ asciidoctor-pdf /Users/oliverkent/Documents/DESK/asciidoc\ work/mysample.adoc
```

**Comment by oliverkent** [comment]
Thanks. That worked. The command I tried was what asciidoctor said. I would love to know the reason as I'm new but the ends supersedes the means at this point!

**Comment by mojavelinux** [comment]
Great news!

> The command I tried was what asciidoctor said

Could you link to where you found the incorrect command? Or was a message printed in the console?

**Comment by oliverkent** [comment]
Is was the $ asciidoctor -b pdf sample.adoc command.

I don't think it's incorrect but perhaps I don't have the right
applications or plug-ins installed (correct me if I've got the incorrect
nomenclature:)

Many thanks.

On Wed, Nov 4, 2015 at 9:51 PM, Dan Allen <notifications@github.com> wrote:

> Great news!
>
> The command I tried was what asciidoctor said
>
> Could you link to where you found the incorrect command? Or was a message
> printed in the console?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/347#issuecomment-153861338>
> .
>



-- 
Oliver Kent

**Comment by mojavelinux** [comment]
`-b pdf` alone wouldn't be enough. You also have to require the library:

```
$ asciidoctor -b pdf -r asciidoctor-pdf sample.adoc
```

But that's why we made the `asciidoctor-pdf` command, so you don't have to worry about all those flags :)

**Comment by oliverkent** [comment]
Thanks for the explanation.

Just getting into asciidoctor.

Please point me in the direction of all the commands, and syntax or <insert
terminology here> to make:


   - x of y formatting for pages



   - alphabetized multi-paragaraphs


and anything else please.

I am already familiar with asciidoctor however.

On Thu, Nov 5, 2015 at 5:56 AM, Dan Allen <notifications@github.com> wrote:

> -b pdf alone wouldn't be enough. You also have to require the library:
>
> $ asciidoctor -b pdf -r asciidoctor-pdf sample.adoc
>
> But that's why we made the asciidoctor-pdf command, so you don't have to
> worry about all those flags :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/347#issuecomment-153957638>
> .
>



-- 
Oliver Kent

**Comment by mojavelinux** [comment]
I advise you to check out the theming guide for tips on how to format the document. There are limitations, but what is there is pretty powerful already. https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc (best viewed raw using the Chrome or Firefox extension).

I also recommend checking out the user manual as its a wealth of information. Again, there are still things missing, but it covers a lot. http://asciidoctor.org/docs/user-manual/#terms-and-concepts

**Comment by oliverkent** [comment]
I will.

Thanks again!

On Fri, Nov 6, 2015 at 3:39 AM, Dan Allen <notifications@github.com> wrote:

> I advise you to check out the theming guide for tips on how to format the
> document. There are limitations, but what is there is pretty powerful
> already.
> https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc
> (best viewed raw using the Chrome or Firefox extension).
>
> I also recommend checking out the user manual as its a wealth of
> information. Again, there are still things missing, but it covers a lot.
> http://asciidoctor.org/docs/user-manual/#terms-and-concepts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/347#issuecomment-154266146>
> .
>



-- 
Oliver Kent
