### ISSUE TITLE
Allow color to be specified for a font-based icon

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#349]
Allow the `color` attribute to be specified on the `icon` macro to control the color of the font. The color can be specified using any format that is permitted in the PDF theme file (see https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#colors).

Example:

```
icon:heart[color=ff0000]
icon:heart[color="255,0,0"]
icon:heart[color="0,0.99,1,0"]
```

**Comment by mojavelinux** [comment]
Currently, the workaround is to use Prawn-specific markup to set the color:

```
+++<color rgb="ff0000">+++icon:heart[]+++</color>+++
```

**Comment by lit-uriy** [comment]
Why another attribute?
In the User manual (http://asciidoctor.org/docs/user-manual/#inline-icons) already provided color throw role, like this:
```
icon:tags[role="blue"] ruby, asciidoctor
```

My code:
```
WARNING: Этот WARNING.

Это icon:flag[role="red"] инлайн иконка с красным флажком, а эта icon:tags[role="blue"] с синим ярлыком
```
But in HTML output icon with color,
![screenshot_28](https://cloud.githubusercontent.com/assets/6910067/26151785/b695c548-3b1d-11e7-821c-72a2698de51f.png)

but PDF output - WITHOUT
![screenshot_29](https://cloud.githubusercontent.com/assets/6910067/26151790/bb0c1898-3b1d-11e7-8264-0f1020d3d941.png)
----
P.S. To avoid confusion in the attributes, it is better to use only one, of course, the attribute "color" is more obvious, but then you need to remove from the documentation the attribute "role" (to leave just for compatibility).

**Comment by mojavelinux** [comment]
I agree that a role (aka class) would be better. But that would mean we need to implement generic roles in the theme. We could make that part of this fix, or at least a simplified version of it (where we just look for the color).

**Comment by mojavelinux** [comment]
Something like this in the theme:

```
role:
  red: #ff0000
```

And this in the AsciiDoc:

```
icon:heart[role=red]
```

I'd be happy with that.

(I put the role under the role category so it doesn't conflict with other top-level category names).

**Comment by lit-uriy** [comment]
When can this feature appear in Asciidoctor-pdf?

**Comment by mojavelinux** [comment]
I've already scheduled it for the next alpha, so I will try to stick to that if I can. Right now I'm busy working on the next release of Asciidoctor core.

**Comment by lit-uriy** [comment]
**mojavelinux**, thank you

**Comment by mojavelinux** [comment]
Roles for inline elements are now supported. Now we just need to apply the role to the icon.
