### ISSUE TITLE
Multi page table of contents overflows to body

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor-pdf#35]

**Comment by akamch** [comment]
Alas, the issue is still there. TOC is on a sigle page.
![toc-overflow-asciidoctor-pdf-bug](https://cloud.githubusercontent.com/assets/83824/5696068/16945ffa-99d0-11e4-93c2-44750ee9b284.png)

**Comment by mojavelinux** [comment]
Could you please provide the AsciiDoc document that exhibits this error. That way, I can be sure we cover that scenario. Thanks!

**Comment by akamch** [comment]
As it happens, the problem disappeared for unknown reasons :rabbit2: All kinds of TOC work perfectly now on two machines I test asciidoctor-pdf. Next time I'll be certain to craft a minimal example or something before raising alarm.

**Comment by mojavelinux** [comment]
@akamch that actually makes me very happy to hear that. Please do keep an eye on the situation and let me know as soon as you see it misbehave again. I do hope that doesn't happen, though ;) :beers:
