### ISSUE TITLE
Allow unicode characters to be rendered in page footer, header and title 

### ISSUE THREAD

**Issue by AlexanderZobkov** [asciidoctor/asciidoctor-pdf#352]
Unicode characters defined in a theme/style configuration file are not rendered correctly. 
For example, copyright symbol specified as \u00A9 in theme/style configuration file is rendered in PDF as \u00A9.

Extraction from the theme configuration file:
footer:
  height: 0.75in
  line_height: 1
  recto_content:
    right: 'Page {page-number}'
    center: '\u00A9 Copyright 2015 xxxxxxxxxxxxxxx'

**Comment by mojavelinux** [comment]
For now, you should insert the unicode glyph directly. You can also use AsciiDoc replacements such as `(C)` for copyright or numeric HTML entities such as `&#169;`.

Support for unicode escape sequences would need to be added into core first. In fact, there is an open issue already. See https://github.com/asciidoctor/asciidoctor/issues/787

**Comment by mojavelinux** [comment]
I've now documented this in the theming guide.

**Comment by AlexanderZobkov** [comment]
Thank you Dan

**Comment by mojavelinux** [comment]
:+1:
