### ISSUE TITLE
Drop leading blanks

### ISSUE THREAD

**Issue by molmich** [asciidoctor/asciidoctor-pdf#355]
if I generate PDF document, where I use blanks for better ASCIDOC format/look, this blanks are not deleted/dropped!

for example:
```
...
ATTENTION: This is an example of 
           leading blank.
...
```
has in PDF:
```
...
ATTENTION: This is an example of            leading blank.
...
```
is it possible to dron leading blanks?

**Comment by mojavelinux** [comment]
Doh! That is definitely an issue. Unlike HTML, PDF treats repeating spaces as significant, whereas HTML consolidates them. So, we'll need to do that consolidation. Thanks for reporting!

**Comment by mojavelinux** [comment]
The problem here is that we are only replacing endlines with single spaces. We are not then collapsing the repeated spaces or tabs. The normalize step needs to be updated to collapse all consecutive whitespace characters into a single space (matching the rules of HTML).
