### ISSUE TITLE
AsciiDoc Content in Tables Do Not Render (Unordered Lists)

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor-pdf#358]
I've noticed that unordered lists in tables don't seem to render correctly.

If I have the following structure:

```
[[personal-mobile]]
.User Expectations
[cols="2a,2a"]
|===
|Expected or Permitted Behaviors |Forbidden Behaviors

|
Immediately inform your line manager if:

* your device is lost.
* your device is stolen.
* you believe any of your accounts (business and personal) you access from that device have been compromised.

|
Wait for a few days to see if someone hands in your personal device before you let your line manager know it is missing.

|===
```

The list renders like this in the PDF:

<img width="827" alt="screenshot 2015-11-17 11 30 45" src="https://cloud.githubusercontent.com/assets/952793/11200102/b5e9cf08-8d1e-11e5-9e44-272bd1a5ef7d.png">

**Comment by veeg** [comment]
AsciiDoc cell content (including lists), which is enabled in AsciiDoc with the `e` prefix to the cell divider, e.g.,
```
|===
e| This cell supports AsciiDoc content!
|===
```

is not currently supported in Asciidoctor-pdf. 
Se main issue #6, and duplicate issues reported #231 and #315.

**Comment by mojavelinux** [comment]
As @veeg points out, these are known issues. We need to create a custom cell type in Prawn in order to support complex (aka AsciiDoc) content in table cells.
