### ISSUE TITLE
Empty code block when at the end of a page

### ISSUE THREAD

**Issue by antoyo** [asciidoctor/asciidoctor-pdf#361]
Hello.
If I have a code block that happens to start at the end of a page, we will see an empty code block, which is followed by the code block on the next page.
See this screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/584972/11313889/9620428c-8fae-11e5-81df-bec084f92822.png)
I could use `<<<`, but I think it should be automatic.
Thanks to fix this issue.

**Comment by mojavelinux** [comment]
We need to check that we can write at least one line on a page before painting the background. This check is actually needed a lot of places because we never know when we're about to bump to a new page.

**Comment by antoyo** [comment]
For your information, it can also happen at the start of a new page (when the code is supposed to end at the bottom of a page).

**Comment by mojavelinux** [comment]
It turns out there was a bug in how we were reporting the total height of the box. We were not accounting for the excess bottom padding that is normally dropped. That excess padding was causing a new page to be created.
