### ISSUE TITLE
Example block on multiple pages

### ISSUE THREAD

**Issue by antoyo** [asciidoctor/asciidoctor-pdf#362]
Hello.
If a have an example block spanning on multiple pages, the example border continues until the very bottom of the first page and does not continue on the next pages.
Here is a screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/584972/11314019/b2845d0e-8faf-11e5-932e-f82e1b077b66.png)
Thanks to fix this issue.

**Comment by mojavelinux** [comment]
Same problem that affects sidebars (see #259).

**Comment by rlopez133** [comment]
Dan,

Appreciate all that you do here with asciidoctor :) Quick question, is there an ETA on this bug by chance? I noticed the beta tag but not sure when that will be released. Some teammates are running across this issue.

Thanks,

Roger

**Comment by mojavelinux** [comment]
I don't have an ETA on beta.1 yet. I am planning on releasing alpha.12 any day now.

**Comment by rlopez133** [comment]
Ok, is there anyway to move this bug into a future alpha schedule instead of beta? Figured I'd ask :)

**Comment by mojavelinux** [comment]
The beta should be the next release. I have to do the alpha because we still don't have a test suite and I won't do a beta until we have a test suite. I don't really want to do another alpha....but I've changed my mind before ;)

**Comment by mojavelinux** [comment]
Be sure to implement the dotted border at the page boundaries, just like is done for sidebar blocks.

**Comment by mojavelinux** [comment]
We should be able to use the exact same logic that is used by the sidebar block.
