### ISSUE TITLE
Transform to uppercase for umlauts not working

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor-pdf#363]
Transforming a heading to uppercase with
````
heading:
  text_transform: uppercase
````
does not work for umlauts.

Line 1 shows the result for transform where the heading should look like line 2 (uppercase chars in the adoc file)

![30-11-2015 14-42-43](https://cloud.githubusercontent.com/assets/8215179/11473500/19b542b6-9773-11e5-9a6e-b51d7fe25485.png)

**Comment by mojavelinux** [comment]
This is where we need to be using the unicode gem (or similar). https://github.com/blackwinter/unicode

**Comment by mojavelinux** [comment]
Basically, Ruby upcase doesn't support the full Unicode range of letters out of the box, sadly.

**Comment by mojavelinux** [comment]
I've learned that the downcase and upcase methods on String in Ruby 2.4 are going to support multibyte characters. \o/ So this will just work.

For Ruby < 2.4, what we could do is detect if the mb_chars method is available on String and use that to transform the characters instead.
