### ISSUE TITLE
Allow themes to be inherited (or imported)

### ISSUE THREAD

**Issue by and3k** [asciidoctor/asciidoctor-pdf#367]
Hi!

Is this possible? I would like to use the default theme (https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml) and just change a few things (and put those changes in a new YAML file instead of editing the default theme)?

Thanks,
Bela

**Comment by mojavelinux** [comment]
Not yet. This is a duplicate (though more specific) of https://github.com/asciidoctor/asciidoctor-pdf/issues/131#issuecomment-104757104. Since the goal is stated more clearly in this issue, we'll keep it as a discrete request.

**Comment by mojavelinux** [comment]
I updated the title to make it more clear what we are requesting. I think we should consider the idea of a theme import as an alternative approach, similar to `@import` in CSS.

**Comment by and3k** [comment]
Yeah! And maybe also the possibility to list multiple themes in the pdf-style attributes?

**Comment by mojavelinux** [comment]
@and3k exactly, that would be the other approach. So to clarify, it would be nice to have two ways to composite themes:

1. `@import` statement in a master theme file
2. Comma-separated themes in pdf-style attribute

**Comment by bshannon** [comment]
Just to be clear, there's still no way for themes to be inherited, right?

Where do I find the default theme, so I can copy it and modify just the parts that I need to change?

**Comment by mojavelinux** [comment]
That's correct, the theme cannot currently be inherited.

Here's the default theme: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml

I recommend following this guide: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc

**Comment by mojavelinux** [comment]
I've submitted an initial prototype. It works using the `extends` key in the theme file. The values are either "default" (to import the default theme), or a file path resolved relative to the pdf-stylesdir.

Here's an example of how to extend the default theme:

```
extends:
- default
base:
  font_color: ff0000
```

Here's an example of how to extend a custom theme (which itself could use the extends key):

```
extends:
- ./base-theme.yml
base:
  font_color: 222222
```

There are still some limitations / quirks when it comes to paths. For example, it's still only possible to load fonts from a single directory.
