### ISSUE TITLE
Setup a test suite

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#37]
Because, quality.

It probably makes sense to use whatever Prawn is using so that we have lots of examples of how to create tests for Prawn data structures and output.

**Comment by mojavelinux** [comment]
While RSpec2 is the goto framework, it's reasonable to at least consider MiniTest. See http://blog.plataformatec.com.br/2015/05/nobody-told-me-minitest-was-this-fun/

Here's an example of a test in Prawn. https://github.com/prawnpdf/prawn/blob/master/spec/text_spec.rb

**Comment by mojavelinux** [comment]
I'd really like to avoid copying the test suite from Asciidoctor core because it's very sub-optimal. We should either be using a modern, clean-room setup for MiniTest 5 or RSpec2. If we go with RSpec, we can probably use what prawn uses. I'd really like the test suite to be approachable though. That's essential.

**Comment by DavidGamba** [comment]
Should this plan on using: https://github.com/asciidoctor/asciidoctor-doctest? @jirutka would probably be interested in looking into how Prawn is doing things and use asciidoctor-doctest with asciidoctor-pdf.

**Comment by jirutka** [comment]
@DavidGamba DocTest is designed for testing converters with a _textual_ output, but PDF is a binary format.

**Comment by mojavelinux** [comment]
@DavidGamba @jirutka Exactly. This is going to require specialized assertion logic. We might be able to find a way to make doctest fit this eventually, but I'd rather start with a custom test suite like in prawn. We can also consider using Origami PDF, which is another PDF inspection library specifically designed for tests.

PDF is sort of strange because it's not actually a binary format. It's a text format with encoded streams throughout. It may be hard to compare the whole output to another whole output, but we could do text assertions of extracted fragments. For instance, ensure the reference table matches text of some sort. It will be a fun exploration.

**Comment by mojavelinux** [comment]
We could combine pdf.js, Selenium and an image comparison tool to perform visual testing on the PDF output. I can't see a good way of testing the styles and layout by simply looking at the PDF structure itself.

**Comment by jirutka** [comment]
:+1:

**Comment by mojavelinux** [comment]
I want to clarify that there is still plenty of things to test without the visual testing part, but the visual testing part will give us total confidence in our tests as a whole.

**Comment by mojavelinux** [comment]
A useful cheat sheet for the basics of RSpec. http://www.rubypigeon.com/posts/rspec-core-cheat-sheet/
