### ISSUE TITLE
background_color and background_image are not working on Title Page

### ISSUE THREAD

**Issue by lask79** [asciidoctor/asciidoctor-pdf#371]
I am using asciidoctor-gradle:1.5.3 und asciidoctor-pdf:1.5.0.aplha.10.1 and I changed the default theme by setting:

title_page:
  background_color: #eaeaea
  background_image: image:background.png[]

When I generate the PDF the background always stays white. I also tried to set only the color or the image. Result is stll the same: still white.

I am also setting the logo_image which is working just fine. But I cannot get the background_image or background_color to work. Even if I am setting those values in the asciidoc file directly.

Do I miss something?

Regards
Lasse

**Comment by mojavelinux** [comment]
The background image and color will not be available in AsciidoctorJ PDF until we are able to upgrade to Prawn 2 (it's currently using Prawn 1.3.1, which has a bug that causes this problem). But Prawn 2 requires Ruby 2, which JRuby 1.7 doesn't fully support.

The expectation we are setting is that this will work once AsciidoctorJ 1.6.0 is out and we move AsciidoctorJ PDF to Prawn 2. So for now, the solution is wait.

**Comment by mojavelinux** [comment]
To answer your question, you did not miss anything.

**Comment by lask79** [comment]
Ok, thanks for the info. I wasn't aware of this. Maybe you can add to the theming-guide which things are currently not working for asciidoctorj-pdf so that there are less suprises when someone is starting to use it with gradle.

Regards
Lasse

**Comment by mojavelinux** [comment]
Sure thing, I can add a note. This is the only exception in AsciidoctorJ PDF because it's a bug we currently can't move past.

**Comment by mojavelinux** [comment]
Documented.

**Comment by lask79** [comment]
That was fast :-)

**Comment by AlexanderZobkov** [comment]
Dan, probably it makes sense to document the workaround for the issue or add a link to the workaround described in http://discuss.asciidoctor.org/Asciidoctor-YAML-style-file-for-PDF-and-maven-td3849.html.

**Comment by mojavelinux** [comment]
I'll add a link to the thread, but I don't want to mull over it too much because what we really want to do is move past it. We're working to make that happen.
