### ISSUE TITLE
Support color and text formatting

### ISSUE THREAD

**Issue by mimiz** [asciidoctor/asciidoctor-pdf#376]
Hi, 
  I used the doc here http://www.methods.co.nz/asciidoc/chunked/ch10.html to write a word in red. For example : 

```
If you do this [red]#*and*# this, you should not 
```

But when processing in PDF all the text is black, is there a way to enable the text color as described in the documentation http://www.methods.co.nz/asciidoc/chunked/ch10.html ?

Thank you 

Remi

**Comment by mojavelinux** [comment]
This is being discussed as part of #350.

**Comment by mojavelinux** [comment]
This was resolved in 1.5.0.beta.2. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-role
