### ISSUE TITLE
Harcoded bold for first line of abstract

### ISSUE THREAD

**Issue by nawroth** [asciidoctor/asciidoctor-pdf#378]
This means that font styling can't really be used for `abstract`, it will look silly for any setting other than `bold`. For styling of the first line altering the indentation might make sense in some cases, but why a different font style would be used makes no sense to me!

It would be an improvement to simply drop `first_line_options` in this context. It could then be re-introduced with more flexibility and controlled from the theme later on.

Code is here:
https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L339

**Comment by mojavelinux** [comment]
As discussed in the pull request, we'll introduce a theme setting named `abstract_first_line_font_style` to allow this setting to be configured.
