### ISSUE TITLE
Override label "Table of Contents"

### ISSUE THREAD

**Issue by jdebouil** [asciidoctor/asciidoctor-pdf#380]
Is there a way to override the label "Table of Contents" ? I write in french language and need to override this label to suit this language.
I tried to use parameter `:lang: fr` but it doesn't update the label "Table of Contents"

**Comment by jdebouil** [comment]
I added `:toc-title: Sommaire` and the label "Table of Contents" has been replaced by "Sommaire".
So it's ok !

**Comment by mojavelinux** [comment]
:+1: 

Asciidoctor doesn't yet support loading a language file so that this is automatic. That's planned as part of https://github.com/asciidoctor/asciidoctor/issues/1129.
