### ISSUE TITLE
Generate an index

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#386]
If the document has a section with the style "index", add an index to the output document at that location.

For more details about index creation, see https://github.com/asciidoctor/asciidoctor/issues/450

**Comment by AVGP** [comment]
Any hints on how to make this happen? I'd love to help & I pretty much need an index and the Docbook-fop-PDF chain is just annoying.

So - where do I start?

**Comment by mojavelinux** [comment]
I went ahead and took a stab at this. As it turns out, I couldn't use the references table since it doesn't contain any page number information. However, I can override `convert_inline_indexterm` to build the index incrementally, then emit it at the end in the `convert_index` method.

First, here's how I decide to (re)model the index data:

```ruby
index = {
  'B' => {
    'Bengal Tiger' => [{ anchor: '__idx-234234', page: 3 }],
    'Big cats' => {
      'Lions' => [{ anchor: '___idx-873424', page: 1 }],
      'Tigers' => {
        'Bengal Tiger' => [{ anchor: '__idx-234234', page: 3 }],
        'Siberian Tiger' => [{ anchor: '__idx-234234', page: 3 }, { anchor: '__idx-89743', page: 5 }]
      }
    }
  }
}
```

Each level of nesting represents a term weight (primary, secondary, tertiary). The array are the references, which include the anchor and page number. This structure makes it easy to consume.

Here's the pull request containing the concept. https://github.com/asciidoctor/asciidoctor-pdf/pull/562

**Comment by mojavelinux** [comment]
In theory, we could cut out the first level of the data structure and simply use a loop to detect when we change letters.

**Comment by mojavelinux** [comment]
I forgot to mentioned that I arranged the index using the styles for the description list. Eventually, we'll probably want dedicated styles, but that should suffice for now.

**Comment by AVGP** [comment]
@mojavelinux Your branch seems to work great!
I got around testing it and haven't seen issues with it so far - what's blocking this from landing in master?

**Comment by mojavelinux** [comment]
@AVGP Your review ;)

One thing I was wondering is whether we should use two columns for the index. Most books do so and Prawn supports this.

**Comment by mojavelinux** [comment]
I forgot about the case when a group can also have a reference. Therefore, we'll need to take the structure a bit deeper and introduce a refs key.

```ruby
index = {
  'B' => {
    'Bengal Tiger' => {
      refs: [{ anchor: '__idx-234234', page: 3 }]
    },
    'Big cats' => {
      'Lions' => {
        refs: [{ anchor: '___idx-873424', page: 1 }]
      },
      'Tigers' => {
        refs: [{ anchor: '__idx-898971', page: 2 }],
        'Bengal Tiger' => {
          refs: [{ anchor: '__idx-234234', page: 3 }]
        },
        'Siberian Tiger' => {
          refs: [{ anchor: '__idx-234234', page: 3 }, { anchor: '__idx-89743', page: 5 }]
        }
      }
    }
  }
}
```

**Comment by mojavelinux** [comment]
The index is now organized in two columns. I also implemented logic to prevent a letter category from being orphaned on a page by itself.

**Comment by mojavelinux** [comment]
Due to how the index data is built, the index does have to be the last section in the document.

**Comment by mojavelinux** [comment]
I decided to introduce a model to hold the index terms. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/index_catalog.rb
