### ISSUE TITLE
Adding index entries changes the intention of the next paragraph

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#391]
If I add index entries to a section I get a longer top margin than without. Example:

With Index entries:

=== Create a new Git repository
(((Repository, create)))
(((Create Git repository)))

The following explanation is based on a
non-bare repository. See ? for the difference between a bare repository
and a non-bare repository with a _working tree_ .

![image](https://cloud.githubusercontent.com/assets/139910/12390299/f5dc7b9c-bdde-11e5-834b-b68b137056e2.png)

Without index entries:

=== Create a new Git repository

The following explanation is based on a
non-bare repository. See ? for the difference between a bare repository
and a non-bare repository with a _working tree_ .

![image](https://cloud.githubusercontent.com/assets/139910/12390316/0aa683e2-bddf-11e5-9f76-94ed798ed96a.png)

**Comment by vogella** [comment]
Not sure which syntax to use to show the full Asciidoc, please switch to edit to see it.

**Comment by vogella** [comment]
I think my issue is invalid, if I leave out the empty line after the index entries the generated output is correct.

This issue seems INVALID

**Comment by mojavelinux** [comment]
You are correct. (Hidden) index entries are parsed as content, but do not get displayed. By offsetting them from the paragraph below by a blank line, you are creating a blank paragraph. You should always "attach" them to host paragraph content to be sure you don't get any extra blank lines.

(Whether blank paragraphs should be discarded is another issue).

**Comment by mojavelinux** [comment]
This is also an important tip for the user manual. See https://github.com/asciidoctor/asciidoctor.org/issues/479.

It probably make sense to consider a way to add index entries to a section title using block attributes. Something like:

```
[indexterms="Repository,create; Create Git repository"]
=== Create a new Git repository
```

That would need to be discussed upstream in core.

**Comment by mojavelinux** [comment]
Actually, I think you can put index entries in the section title.

```
=== Create a new Git repository(((Repository, create)))(((Create Git repository)))
```
