### ISSUE TITLE
unable to use themes in java

### ISSUE THREAD

**Issue by rathishkumar89** [asciidoctor/asciidoctor-pdf#392]
I have a PDF generated from an ascii through asciidoctor i need to make the PDF in a presentable way like setting the background color for the code block and changing the fonts for a product.I am not seeing any doc for java.

**Comment by mojavelinux** [comment]
Please see https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-with-theme-example.

**Comment by rathishkumar89** [comment]
Its not applying can you provide a code snippet to add to options map or how to include in java??

**Comment by mojavelinux** [comment]
You just need to specify the `pdf-style` attribute to the file path of a YAML theme file.

```java
import java.io.File;
import org.asciidoctor.Asciidoctor;
import org.asciidoctor.Attributes;
import org.asciidoctor.Options;
import static org.asciidoctor.AttributesBuilder.attributes;
import static org.asciidoctor.OptionsBuilder.options;

public class Test {
    public static void main(String[] args) {
        Asciidoctor asciidoctor = Asciidoctor.Factory.create();
        Attributes attributes = attributes().attribute("pdf-style", "pdf-theme.yml").get();
        Options options = options().backend("pdf").attributes(attributes).get();
        asciidoctor.convertFile(new File(args[0]), options);
    }
}
```

**Comment by rathishkumar89** [comment]
And is it possible to load a .css theme file instead of .yml??

**Comment by rathishkumar89** [comment]
And when use the attributes am getting attributes() is not defined and am using 

		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj-pdf</artifactId>
			<version>1.5.0-alpha.9</version>
		</dependency>
		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj</artifactId>
			<version>1.5.2</version>
		</dependency>

**Comment by mojavelinux** [comment]
It is not possible to use CSS with Asciidoctor PDF. That's not the design goal of the library. We are writing directly into the PDF object and CSS is not available there. The yml file is our attempt to provide a familiar environment for a web developer, but specifically designed for styling PDF.

**Comment by rathishkumar89** [comment]
is it possible to print the JSON instead of Table ??

**Comment by rathishkumar89** [comment]
@mojavelinux is there any provision for displaying JSON Schema in its own format inistead of showing them as Tables??

**Comment by mojavelinux** [comment]
I don't understand the question you are asking. Could you clarify or perhaps provide an example?

**Comment by rathishkumar89** [comment]
**https://github.com/rathishkumar89/swaggerAsciiTest** this is the example am working i am pulling the JSON over HTTP and converting it into ascii **https://github.com/rathishkumar89/swaggerAsciiTest/blob/master/ascii-to-pdf/src/main/java/com/ascii/asciidoc/swaggerstaticdoc/core/FrameJson.java Lno :85** am taking the schema and even without the schema option also the result is ended up with table structure.But, the expected is from ASCII doc if i convert to PDF it should end up with JSON Structure .May i know the syntax or any switch we need to include at time of PDF Creation?

**Comment by mojavelinux** [comment]
This seems to me like a swagger2markup question. Asciidoctor doesn't do anything with JSON schemas. It just converts the AsciiDoc it is given.

**Comment by Skilly** [comment]
The java examples above seem to be addressing the same need that I'm trying to address in ruby. I'm guessing my syntax is incorrect?

I have the following code that is trying to reference a theme folder,  yaml file within the theme folder and also a fonts folder:
`Asciidoctor.convert_file adoc_file, :backend => 'pdf', :in_place => true, :pdf_stylesdir => './public/resources/themes', :pdf_style => './public/enqabile-theme.yml', :fonts_dir => './public/resources/fonts' # creates a pdf file`

Any tips will be appreciated

**Comment by mojavelinux** [comment]
First, you need to use attributes, not options, to specify the location of the PDF theme and resources. Second, the `pdf-style` is relative to the `pdf-stylesdir`. In other words, here's what you need to use:

```ruby
Asciidoctor.convert_file adoc_file,
  backend: 'pdf',
  attributes: {
    'pdf-stylesdir' => 'public/resources/themes',
    'pdf-style' => 'enqabile',
    'pdf-fontsdir' => 'public/resources/fonts'
  }
```

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#applying-your-theme for more details.

**Comment by Skilly** [comment]
Thanks Dan, that did the trick!

**Comment by mojavelinux** [comment]
I'm glad to hear it!
