### ISSUE TITLE
How do I get this to properly bold?

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#394]
Trying to bold the following command:

````
----
$ **export ANSIBLE_SSH_ARGS='-F ./path/to/env_machines' **
----
````

The ** has alway worked in the past. I'm pretty sure the ' is messing with things, but not sure how to fix. 

Thanks,

Roger

**Comment by mojavelinux** [comment]
I think the problem is that you are missing the subs configuration.

```
[subs=+quotes]
----
$ **export ANSIBLE_SSH_ARGS='-F ./path/to/env_machines'**
----
```

The single quote shouldn't have any impact here.

**Comment by rlopez133** [comment]
Oops! Yes you are correct. I did forget that.

Sorry about that.

**Comment by mojavelinux** [comment]
No problem. It's definitely something we still need to document better, so a good reminder.
