### ISSUE TITLE
Allow base (or text) alignment to be controlled using a document attribute

### ISSUE THREAD

**Issue by dkotrada** [asciidoctor/asciidoctor-pdf#396]
If I use asciidoctor-pdf myfile.adoc I get pdf output with block style paragraphs.
For now I use on each paragraph [.text-left]. How can I set it for entire document?

**Comment by mojavelinux** [comment]
Right now, to set alignment globally, you need to create a theme and define the `base_align` property. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#base.

I've considered allowing this option to be specified in the document header for convenience. It's mentioned in the WORKLOG. This is the first time it's been filed as an issue.

Perhaps:

```
:align-text: left
```

**Comment by mojavelinux** [comment]
I'm leaning towards naming this attribute `text-alignment`. It will override the value of the `base_align` key in the theme since that's currently how the alignment of paragraph text is controlled. In the future, we may repurpose this a bit.
