### ISSUE TITLE
Passing POM properties to :revnumber: does not resolve

### ISSUE THREAD

**Issue by gtapper** [asciidoctor/asciidoctor-pdf#397]
Using the instructions under Passing POM Properties in https://github.com/asciidoctor/asciidoctor-maven-plugin#configuration-options.

The :revnumber: {product-version} resolves properly in the html5 output but not in the PDF version, where the output becomes "Version {product-version}".

**Comment by mojavelinux** [comment]
This appears to work for me. Could you be more specific about your setup? Perhaps it would be most efficient to reproduce this in the Asciidoctor PDF example. That would also give others a starting point for doing the same.

https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example

**Comment by gtapper** [comment]
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

<asciidoctor.maven.plugin.version>1.5.2.1</asciidoctor.maven.plugin.version>
    <asciidoctorj.pdf.version>1.5.0-alpha.11</asciidoctorj.pdf.version>
    <asciidoctorj.version>1.5.4</asciidoctorj.version>
    <rubygems.prawn.version>2.0.2</rubygems.prawn.version>
    <jruby.version>9.0.4.0</jruby.version>
  </properties>


I build a book.

Excerpt from the pom.xml

          <execution>
            <id>generate-pdf-doc</id>
            <phase>site</phase>
            <goals>
              <goal>process-asciidoc</goal>
            </goals>
            <configuration>
              <doctype>book</doctype>
              <backend>pdf</backend>
              <sourceHighlighter>coderay</sourceHighlighter>
              <outputDirectory>${basedir}/target</outputDirectory>
              <attributes>
                <pdf-stylesdir>${basedir}/../shared</pdf-stylesdir>
                <pdf-style>trafodion</pdf-style>
                <icons>font</icons>
                <pagenums/>
                <toc/>
                <idprefix/>
                <idseparator>-</idseparator>
                <project-version>${env.TRAFODION_VER}</project-version>
                <build-date>${maven.build.timestamp}</build-date>
              </attributes>
            </configuration>
          </execution>

Given that this is a book, there's an index.adoc file with:

= Trafodion Client Installation Guide
:doctype: book
:numbered:
:toc: left
:toclevels: 3
:toc-title: Table of Contents
:icons: font
:iconsdir: icons
:experimental:
:source-language: text
:revnumber: {product-version}

The title page contains:

Trafodion Client Installation Guide
Version {product-version}

I can upload the source files to Google drive if that'd help.



On Tue, Feb 9, 2016 at 10:50 PM, Dan Allen <notifications@github.com> wrote:

> This appears to work for me. Could you be more specific about your setup?
> Perhaps it would be most efficient to reproduce this in the Asciidoctor PDF
> example. That would also give others a starting point for doing the same.
>
>
> https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/397#issuecomment-182208862>
> .
>



-- 
Thanks,

Gunnar
*If you think you can you can, if you think you can't you're right.*

**Comment by mojavelinux** [comment]
> I can upload the source files to Google drive if that'd help.

The most efficient way is to send a pull request to https://github.com/asciidoctor/asciidoctor-maven-examples. This serves not just as a set of examples, but as a proving ground for issues. If it works there, it should work anywhere else.

I think I see the issue, though. You are defining the attribute `project-version`, but using the attribute reference `{product-version}`. Notice the difference in the name.

**Comment by gtapper** [comment]
Duh! That's what you get for working on too many things in parallel.

Is there a way to generate a date in "Month Year" format too? Overall, I'm
trying to find a way to automatically generate revision history.

On Tue, Feb 9, 2016 at 11:03 PM, Dan Allen <notifications@github.com> wrote:

> I can upload the source files to Google drive if that'd help.
>
> The most efficient way is to send a pull request to
> https://github.com/asciidoctor/asciidoctor-maven-examples. This serves
> not just as a set of examples, but as a proving ground for issues. If it
> works there, it should work anywhere else.
>
> I think I see the issue, though. You are defining the attribute
> project-version, but using the attribute reference {product-version}.
> Notice the difference in the name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/397#issuecomment-182212822>
> .
>



-- 
Thanks,

Gunnar
*If you think you can you can, if you think you can't you're right.*

**Comment by mojavelinux** [comment]
The revdate in Asciidoctor is a string, so any value you put in there is accepted. Otherwise, it doesn't provide any date processing.

What I recommend is a custom block macro. That way, you can insert it in the document whereever you want it to go and get a hook into creating a table dynamically. That would make for a good exercise in the extension lab.

**Comment by mojavelinux** [comment]
I'm marking this question as answered. If you need further clarification, please feel free to reopen and ask a follow-up question.
