### ISSUE TITLE
Bulleted lists in table cells do not generated correctly

### ISSUE THREAD

**Issue by gtapper** [asciidoctor/asciidoctor-pdf#398]
<properties>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
       <asciidoctor.maven.plugin.version>1.5.2.1</asciidoctor.maven.plugin.version>
       <asciidoctorj.pdf.version>1.5.0-alpha.11</asciidoctorj.pdf.version>
       <asciidoctorj.version>1.5.4</asciidoctorj.version>
       <rubygems.prawn.version>2.0.2</rubygems.prawn.version>
       <jruby.version>9.0.4.0</jruby.version>
     </properties>

Table cell is defined with cols="50%a". Cell uses bulleted lists. The HTML5 generation is performed correctly, the PDF generation does not generate the bulleted list but treats the content as text.

**Comment by mojavelinux** [comment]
Asciidoctor PDF does not currently process AsciiDoc table cells. See #6.

**Comment by mojavelinux** [comment]
If you are satisfied that #6 is the same issue, I'll close this one and we'll follow-up there.

**Comment by gtapper** [comment]
Sounds good to me... do you want a copy of the file for testing before I
work around this issue?

On Tue, Feb 9, 2016 at 10:54 PM, Dan Allen <notifications@github.com> wrote:

> If you are satisfied that #6
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/6> is the same
> issue, I'll close this one and we'll follow-up there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-pdf/issues/398#issuecomment-182209379>
> .
>



-- 
Thanks,

Gunnar
*If you think you can you can, if you think you can't you're right.*

**Comment by mojavelinux** [comment]
I think I have plenty of examples for this use case. But if you'd like to post the relevant section to the comments in that issue, it could only help.
