### ISSUE TITLE
Poetry / verse style

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-pdf#40]
Would be desirable not to have gray bars on left of poems.  Also, to be able to move the left
margin to the left, since poems may consist of short lines.  Of course line length varies.  See pdf image in Issue #38.

**Comment by mojavelinux** [comment]
> to be able to move the left margin to the left

Can you clarify what you mean by this?

I think that the verse needs to have separate styles from the quote block in the theme. That way, it's possible to control the behavior separately.
