### ISSUE TITLE
Header and footer don't apply in the toc

### ISSUE THREAD

**Issue by kongou-ae** [asciidoctor/asciidoctor-pdf#401]
I built the pdf by using [this theme file](https://gist.github.com/kongou-ae/060ab427b8a44d350e09). Header and footer apply in main contents. But these don't apply in the toc.

I would like to apply header and footer in the toc. Is there a way to fix this ?

**Comment by mojavelinux** [comment]
That appears to be an oversight. The proper solution is to fix the code :)

**Comment by kongou-ae** [comment]
:+1: 

I would be glad if you could fix the code as to build different page number on the toc and main contents. For example, the pagenum of toc starts at i and the pagenum of main contents starts at 1.

**Comment by mojavelinux** [comment]
That's already implemented, so when you refer to the page number, it will emit the roman numerals on the toc pages. You can see this by looking at the outline of the PDF. These pages are numbered in this way.

**Comment by mojavelinux** [comment]
In other words, once we enable the running content, that is the page number format you will see.

**Comment by themowski** [comment]
This seems to be a subset of the functionality mentioned in #606 (it's related regardless).

**Comment by mojavelinux** [comment]
I believe this was resolved by #606, documented here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-running-content (see running-content-start-at) and here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-page (see page-numbering-start-at). Correct me if I'm wrong.
