### ISSUE TITLE
Parser should recognize up to 6 digit character references

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#404]
The parser currently only allows up to 4 digits in character references (e.g., `&#8364;`). However, to support the full unicode range, including dingbats (typically 5 digits) and emoji (typically 6 digits), we should allow up to 6 digits.

**Comment by mojavelinux** [comment]
Unfortunately, Asciidoctor PDF can only support what Asciidoctor core supports, which is 5 digits. Therefore, we'll need to make an incremental fix, then update to 6 once the equivalent fix in core is made.

**Comment by mojavelinux** [comment]
Asciidoctor PDF has been updated to support 6 digit character references as of 1.5.0.alpha.12.

**Comment by ghobona** [comment]
`&#10122;` fails to render in Asciidoctor PDF 1.5.0.alpha.16 however `&#10003;` renders correctly.

**Comment by mojavelinux** [comment]
@ghobona Asciidoctor parses the 6-digit character reference fine. The problem is that the glyph is missing from the provided font. If you need to use this glyph, then you need to specify a font (such as a fallback font) in the theme file that has this glyph.
