### ISSUE TITLE
variable in title doesn't get substituted for PDF index

### ISSUE THREAD

**Issue by gliptak** [asciidoctor/asciidoctor-pdf#408]
Here is the adoc demonstrating:

    :doctype: book
    :source-highlighter: pygments
    :title: My Book
    :chaptera: Chapter A

    = {title}

    == {chaptera}

Screenshot:
![pdf_title](https://cloud.githubusercontent.com/assets/50109/13830181/6b80f5d6-eba1-11e5-9f88-b137b46a9dc1.png)

**Comment by mojavelinux** [comment]
You've hit a sharp edge in AsciiDoc by using the `title` attribute for user-defined content. The `title` attribute is a reserved attribute that is used for setting the value of the `<title>` element in the HTML `<head>` or main DocBook `<info>`. If you switch to using a non-reserved attribute name, you'll get the results you expect.

```
= {book-title}
:doctype: book
:source-highlighter: pygments
:book-title: My Book
:chapter-a: Chapter A

== {chapter-a}

content
```

I'll make a note of this in the user manual. See the entry in http://asciidoctor.org/docs/user-manual/#builtin-attributes-table.

**Comment by mojavelinux** [comment]
Btw, thanks for pointing this out!

**Comment by gliptak** [comment]
Thank you for the detailed explanation. I will go with ```book-title```.

PS Maybe the ```pdf``` backend could treat ```html``` specific attribute as a regular one? Or a warning could be issued (for this and other attributes with "unexpected" behaviour)?

**Comment by mojavelinux** [comment]
The way Asciidoctor is implemented, it's not possible to treat it differently per backend and something that's hard to check for in the processor. It would be a good feature to add to a validator, something we'll be starting work on soon.
