### ISSUE TITLE
SVG files that include image elements are not rendered correctly

### ISSUE THREAD

**Issue by AlexanderZobkov** [asciidoctor/asciidoctor-pdf#414]
The version of prawn-svg library that is currently used by asciidoctor-pdf does not allow to refer to bitmap images located on disk: https://github.com/mogest/prawn-svg/issues/71. 
For example, a "title page background" image can be in SVG format and include raster elements (<image> elements that refer to png or jpg files on local computer) . These elements will not be rendered.  
As a workaround, it's possible to embed png/jpg files by converting them into base64 (~ 0.5 - 1 MB string)  and embedding into a SVG file. All these embeddings "inflate" the SVG file to enormous size and make it problematic to edit in IDE or SVG/Text editors.

However the latest version of prawn-svg library includes a fix for the issue and only needs to be integrated into asciidoctor-pdf.

**Comment by mojavelinux** [comment]
> the latest version of prawn-svg library includes a fix for the issue and only needs to be integrated into asciidoctor-pdf.

I agree! I've been tracking that issue and I also notice it just got fixed.

I have two questions. Do we need to enable the new option? Also, how does the path resolution work?

**Comment by AlexanderZobkov** [comment]
> Do we need to enable the new option? Also, how does the path resolution work?

Unfortunatly, just upgrading to the latest version of prawn-svg is not enoght. Asciidoctor-pdf needs to be modified as well by enabling a newly added option in prawn-svg lib: 

`:enable_file_requests_with_root | string | If not nil, prawn-svg will serve file: URLs from your local disk if the file is located under the specified directory. It is very dangerous to specify your root path ("/") if you're ot fully in control of your input SVG.  Defaults to nil (off).`

I've played a bit with the latest prawn-svg library and asciidoctor-pdf and it's resulted into the following changes - relative paths are resolved against the path where a svg file is located.

```
diff --git a/lib/asciidoctor-pdf/converter.rb b/lib/asciidoctor-pdf/converter.rb
index f913eff..d4322e4 100644
--- a/lib/asciidoctor-pdf/converter.rb
+++ b/lib/asciidoctor-pdf/converter.rb
@@ -816,14 +816,14 @@ class Converter < ::Prawn::Document
     when 'svg'
       begin
         svg_data = ::IO.read image_path
-        svg_obj = ::Prawn::Svg::Interface.new svg_data, self, position: position, width: width, fallback_font_name: default_svg_font
+        svg_obj = ::Prawn::Svg::Interface.new svg_data, self, position: position, width: width, fallback_font_name: default_svg_font, enable_file_requests_with_root: File.dirname(image_path)
         svg_size = svg_obj.document.sizing
         rendered_w = svg_size.output_width
         if !width && (svg_obj.document.root.attributes.key? 'width')
           # NOTE scale native width & height by 75% to convert px to pt; restrict width to bounds.width
           if (adjusted_w = [bounds.width, rendered_w * 0.75].min) != rendered_w
             # FIXME would be nice to have a resize/recalculate method; instead, just reconstruct
-            svg_obj = ::Prawn::Svg::Interface.new svg_data, self, position: position, width: (rendered_w = adjusted_w), fallback_font_name: default_svg_font
+            svg_obj = ::Prawn::Svg::Interface.new svg_data, self, position: position, width: (rendered_w = adjusted_w), fallback_font_name: default_svg_font, enable_file_requests_with_root: File.dirname(image_path)
             svg_size = svg_obj.document.sizing
           end
         end
```

**Comment by mojavelinux** [comment]
Thanks! That's exactly what I needed to know.

Do you think the root should be the resolved value of `imagesdir` or the directory containing the SVG?

**Comment by AlexanderZobkov** [comment]
I think, the root directory should be the resolved value of the directory containing the SVG. 
SVG files are usually prepared in SVG editors like Inkscape or generated programmatically by some tool. Mentioned tools are not aware of `imagedir` or asciidoctor specifics.

**Comment by mojavelinux** [comment]
A very sound point! We'll stick to your proposal then.

**Comment by mojavelinux** [comment]
Would you like to send a PR with these changes?

**Comment by AlexanderZobkov** [comment]
Sure, I'll send the PR.

**Comment by AlexanderZobkov** [comment]
Here is the PR: https://github.com/asciidoctor/asciidoctor-pdf/pull/417

**Comment by AlexanderZobkov** [comment]
Dan, Did you have a chance to review the PR?

**Comment by mojavelinux** [comment]
Not yet, but it's on my list for this weekend. :hourglass_flowing_sand:

**Comment by mojavelinux** [comment]
Merged as 4b7a667b409a03d92303882f8520ba4540caea8c. Thanks @AlexanderZobkov!

**Comment by mojavelinux** [comment]
One thing I noticed is that when I run Ghostscript (gs) on the generated PDF, I get the following warning:

```
**** Warning: stream Length incorrect.
```

This only happens when an SVG containing a linked image is included in the document. This makes me think that it is a bug somewhere in Prawn SVG.

You can verify by running the optimize-pdf shell script on the generated PDF.

**Comment by AlexanderZobkov** [comment]
I'm not sure that this is caused by Prawn SVG. I've run the optimize-pdf script with some PDF files (12) that we generate with asciidoctor-maven-plugin and for one file ghostscript (9.15 cygwin) reported
```
   **** File did not complete the page properly and may be damaged.

   **** This file had errors that were repaired or ignored.
   **** The file was produced by:
   **** >>>> Asciidoctor PDF 1.5.0.alpha.11, based on Prawn 2.0.2 <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.
```
All the PDF files include the same SVG elements in title pages. 
For me, this is something in Prawn itself. As far as I know, Prawn SVG uses only high-level Prawn API to produce vector geometry and embed images.

**Comment by mojavelinux** [comment]
> For me, this is something in Prawn itself.

I think we're saying the same thing. Somewhere, Prawn is messing up the content length when this combination of APIs are used. The next step is probably to try to duplicate this without Asciidoctor involved and see if we can get a test case. I think the test case still belongs in Prawn SVG since that is where this combination of Prawn APIs is used.

**Comment by nguillaumin** [comment]
Apologies for commenting on this old thread, but I can't seem to get my images to show up. I wonder if that works in the context of the page title image, but not with embedded SVGs in the content?

In my AsciiDoc file I have:

```
image::images/test.svg[]
```

My SVG looks like:

```svg
<svg version="1.1"
     baseProfile="full"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">

    <image xlink:href="file:tab-facet-1.png" />

    <circle cx="150" cy="100" r="12" fill="#f26835" />
    <text x="150" y="106" text-anchor="middle" fill="white">1</text>

</svg>
```

But when I render the PDF, only the circle + text is shown, the underlying background image is not. I've tried various ways to indicate the path, either relative or absolute, with or without `file:`, etc. I also tried with a remote URI, and by setting :allow-uri-read:, but to no avail.

Am I missing something?

**Comment by nguillaumin** [comment]
Replying to myself in case that helps someone else: The `<image>` tag needs to have a `width` and `height` attributes, otherwise prawn-svg will skip it.

**Comment by mojavelinux** [comment]
@nguillaumin Perhaps consider reporting that upstream in [prawn-svg](https://github.com/mogest/prawn-svg).

However, if I try to view the SVG using a desktop image viewer, I face the same restriction. So perhaps this is to spec.

**Comment by SjoerdV** [comment]
Facing the same issue with height and width specified in the svg. This image does span multiple pages, maybe that has something to do with anything?
```
<image x="-0.5" y="-0.5" width="839" height="2598" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0cAAAomCAIAAAAk6Cj4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAP+lSURBVHhe7N0HWBTHAgfw3SvA0..../>
```
