### ISSUE TITLE
quote and verse titles not rendering

### ISSUE THREAD

**Issue by pbrentlinger** [asciidoctor/asciidoctor-pdf#416]
When inserting a quote or verse the title is not showing up in the pdf, but I suspect it works for the other block types.  Attached are the tests I have run for this.
[asciidoc-pdf-tests.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/201039/asciidoc-pdf-tests.txt)

**Comment by mojavelinux** [comment]
Titles on quote and verse blocks are not currently implemented (just so you know that you aren't doing anything wrong). I'll mark this for the next release since it's a pretty simple fix.

**Comment by mojavelinux** [comment]
Since quote and verse blocks use the keep together logic, the caption will need to be accounted for in that logic.

**Comment by mojavelinux** [comment]
I decided to display the caption (aka block title) outside of the decoration. Here's a preview:

![quote-with-title](https://cloud.githubusercontent.com/assets/79351/18665076/bec4a4ca-7ee2-11e6-8f1c-55a55054ffa5.png)
