### ISSUE TITLE
Rendering of two images in header or footer fails

### ISSUE THREAD

**Issue by fbasler** [asciidoctor/asciidoctor-pdf#421]
I tried to define a theme to be used by the asciidoctor-pdf renderer which displays two images in the header - one on the left, the other one on the right.

Here's the snippet from the theme.yml:

> header:
>   height: 1.5in
>   recto_content:
>     right: image:gradle.png[width=200]
>     left: image:github.png[width=200]
>   verso_content:
>     right: $header_recto_content_right
>     left: $header_recto_content_left

Unfortunately it got rendered like this:

![image](https://cloud.githubusercontent.com/assets/18614807/14741593/bf4b4ab4-0897-11e6-91b2-2bc33089b4e5.png)

As you can see the image on the right is correctly aligned to the right but shifted down. 
If I use a similar definition for the footer, only the left image is rendered - the right one is missing altogether.

Could you please have a look at it and fix the image alignment?
Thank you in advance.

Here's a minimal sample project showing the problem:
[NoTwoHeaderImages.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/231772/NoTwoHeaderImages.zip)

**Comment by mojavelinux** [comment]
Thanks for reporting! It looks like the cursor was not being properly reset after placing the image in the running content. As a result, the image on the other side was being placed below the other when they should be aligned vertically.

I've submitted a patch with a fix. I'll include this as part of the next alpha.

**Comment by fbasler** [comment]
Thank you for the quick solution.
