### ISSUE TITLE
Allow specifying a font style for a title on the title page

### ISSUE THREAD

**Issue by AlexanderZobkov** [asciidoctor/asciidoctor-pdf#423]
There is no way to define a font style for a title, for example **bold** or ***bold italic***. Title string is always rendered with normal style. The same story with authors.

**Comment by mojavelinux** [comment]
This is possible. The keys are just missing from the theming guide. I'll mark it as a documentation issue.

**Comment by AlexanderZobkov** [comment]
Great, thanks! It looks like I overlooked these features when I was inspecting the sources.

**Comment by mojavelinux** [comment]
Would you like to update the theming guide?

**Comment by mojavelinux** [comment]
PR sent.

**Comment by AlexanderZobkov** [comment]
Looks OK. I think we can close the issue by meging the PR. Thanks for updating the theming guide,
Sorry, I didn't respond on the proposal to update the docs.

**Comment by mojavelinux** [comment]
Thanks for reviewing! You made me realize there were a few other things I wanted to fix, so I went ahead with the docs update.
