### ISSUE TITLE
Embedding remote images. Permission denied. On Windows.

### ISSUE THREAD

**Issue by JohnLukeBentley** [asciidoctor/asciidoctor-pdf#425]
I'm trying to get an embedded remote image in my resulting PDF. But I receive a "permission denied" error. I'm on Windows 10 Pro.

In my source asciidoc I have a remote block image

    image::http://www.catster.com/wp-content/uploads/2015/06/e7c8cac4a5e9838bfa3c7b1197d8fde6.jpg[height=315, height=315, width=560]

My conversion command is something like (In Powershell)

```powershell
ps> asciidoctor-pdf --attribute allow-uri-read --trace .\AcademicJournalArticleExample.adoc
```

The relevant part of the console error output

    C:/Program Files (x86)/Ruby23/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/temporary_path.rb:5:in `unlink
    ': Permission denied @ unlink_internal - C:/Users/John/AppData/Local/Temp/image-20160426-140-1rng434.jpg (Errno::EACCES)

A handy link to the relevant code file [temporary_path.rb](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/temporary_path.rb).

Apparently that ruby code file is struggling to get permissions to either my Windows directory `C:/Users/John/AppData/Local/Temp`, or the temporary image file located there.

I have tried running the console as an Administrator.

**Comment by mojavelinux** [comment]
I really don't understand how Windows doesn't allow permission to a user's own AppData folder. That seems like a permissions bug in Windows to me.

I think the best solution here is to rescue any exception encountered when trying to delete these temporary files and simply issue a warning that it was unsuccessful. I don't think a failure to delete a temporary file should halt the processor. It then becomes the user's responsibility to clean up these files if the OS forbids the application to do it.

**Comment by mojavelinux** [comment]
To be clear, add a try/catch to the unlink operation and issue a warning if it is unsuccessful.

**Comment by JohnLukeBentley** [comment]
> I really don't understand how Windows doesn't allow permission to a user's own AppData folder.

Yeah, it's really strange. That's where Apps are supposed to be allowed to read from, the `C:/Users/<user>/AppData/Local/Temp/` folder especially.

Given your clear affection for Linux might it be that you don't have a Windows environment to reproduce this error? I mean it would be wise to get this reproduced to rule out something wrong with my particular environment.

> To be clear, add a try/catch to the unlink operation and issue a warning if it is unsuccessful.

I'd suggest until we know why the error occurs we (I use the royal "we") are not going to be able to issue a warning that is more informative than the current error message.

>  I don't think a failure to delete a temporary file should halt the processor. It then becomes the user's responsibility to clean up these files if the OS forbids the application to do it.

I've since deleted the contents of C:/Users/<user>/AppData/Local/Temp/; and rebooted to rule out some weird temporary lock on the folder. Alas, no luck. 

Just to describe a bit more what's going on. Every time I run my command asciidoctor-pdf successfully writes the remote image file to the temp folder, using a semi arbitrary file name. For example since clearing my folder I've run the relevant command twice. In the temp folder I now have

    image-20160427-9104-10frpyw.jpg
    image-20160427-9296-m78dr1.jpg

... both of these are a copy of the same remote image. The error occurs and the pdf is not created. 

So it feels like the "Permission denied" references that asciidoctor-pdf can't read from C:/Users/<user>/AppData/Local/Temp/ in order to insert the downloaded image into the pdf. And it doesn't appear to be due to some kind of slovenliness on the user's part (in failing to keep the temp directory small).

Perhaps the problem lies at intersection between Ruby on Windows and Windows itself, rather than asciidoctor-pdf as such. 

And, by the way, these projects, asciidoctor and asciidoctor-pdf, are compelling in their ambition - a separation of content and presentation to make the workflow easier for writer, publisher, and reader. The web philosophy brought to the digital (and paper) word more generally. The mind expands thinking on all the future possibilities. Thanks for the all the blood you've put into it.

**Comment by JohnLukeBentley** [comment]
Embedding local images in a pdf work without a problem.

    .Block Image - local
    image::cat-roll.jpg[]

    .Thumbnail - local
    image::cat-roll.jpg[Alt text, width=128, link="cat-roll.jpg"]

**Comment by mojavelinux** [comment]
> Given your clear affection for Linux might it be that you don't have a Windows environment to reproduce this error?

I have a Windows machine which I can use to test. Once we solve #37, we'll also have tests running in a Windows CI environment (AppVeyor).

> I'd suggest until we know why the error occurs we (I use the royal "we") are not going to be able to issue a warning that is more informative than the current error message.

True, but we can prevent the processor from crashing.

I'm certain from your diagnostics that the failure comes when trying to delete the file. This is not uncommon on Windows. Windows likes to block file deletes when it thinks those files are "in use".

...

After doing a bit more research, I have discovered that the `build_image_object` function does not close the file after opening it. This is a classic case of when Windows will refuse to allow the file to be deleted.

Fortunately, the `build_image_object` method accepts an file descriptor, so we can wrap the call in our own resource handler to ensure the file descriptor gets closed properly.

**Comment by mojavelinux** [comment]
If my analysis is correct, this problem would show on any Windows machine (since they all have the same open file policy). Therefore, it's a good test to add.

**Comment by JohnLukeBentley** [comment]
Sounds like you've got a strategy in hand. Great work.

**Comment by mojavelinux** [comment]
:+1: 

I also filed an issue upstream (https://github.com/prawnpdf/prawn/issues/975) to address the problem we ran into in Prawn. We don't have to wait on that fix since I decided to take another route into the API. However, the fix would allow us to switch back to using the simpler API.

**Comment by mojavelinux** [comment]
Btw, thanks for reporting this issue @JohnLukeBentley! I had no idea that this was causing Asciidoctor PDF to fail on Windows whenever a document contained a remote image to embed.

**Comment by JohnLukeBentley** [comment]
You are most welcome Dan. 

Just to share: these days I'm being lured toward markdown and pandoc. It looks like it might be the toolset which gets me closer to my goal: Transforming a lightweight language into XHTML5; PDF (via latex); EPUB; and MOBI (Amazon) - with biblatex/bibliography handling. 

I'm also somewhat favouring markdown's purity over Asciidoc (although Asciidoc does tables superbly).

Nevertheless I appreciate all the work you have been doing with AsciiDoc. I see you have the right vision in mind - something shared with those at pandoc as far as I can tell. And it's worth having competing toolsets.

**Comment by mojavelinux** [comment]
> Transforming a lightweight language into XHTML5; PDF (via latex); EPUB; and MOBI (Amazon) - with biblatex/bibliography handling.

For the record, that's precisely our goal. I understand if you think we aren't there yet, but you should at least know that that's where we are headed.

> I'm also somewhat favouring markdown's purity over Asciidoc

I respect your viewpoint, but would argue that AsciiDoc is more pure than Markdown, primarily because it adheres to more consistent, repeatable patterns. No lightweight markup is perfect yet, but I can assure you that I strive every day to make it as intuitive as possible.

Thanks for appreciating the work! I certainly do hope that you reconsider your decision. I can also guarantee you'll have a lot more fun with the Asciidoctor community than anywhere else ;)

**Comment by JohnLukeBentley** [comment]
> I respect your viewpoint, but would argue that AsciiDoc is more pure than Markdown, primarily because it adheres to more consistent, repeatable patterns.

I don't mean to plunge us into details but It might be my allegation that asciidoc is less pure is made in virtue of Admonitions. It seems that these are specialist blocks that would be better taken care of on an ad hoc basis with a user tagging a block with an asciidoc role (which gets transformed into an html class, when doing HTML transformations, if I recall correctly). Perhaps this is a prejudice on my part in virtue of coming more from an essay writing purpose rather than a technical manual purpose (where notes/asides/"admonitions" might be more common).

Anyway, I do see that, in keeping with Gruber's original philosophy you are attempting to strike the balance between providing functionality and keeping the text spartan: not looking like it is marked up; readable as is.

As a separate point you mention somewhere that you intend asciidoc as an extensible format. I think that is key (and good) thing. But I won't say why for the sake of brevity.

> For the record, that's precisely our goal. I understand if you think we aren't there yet, but you should at least know that that's where we are headed.

Yes, I'd be surprised if that wasn't your goal (and there is plenty of evidence in the documentation that this is your goal). But it is good to hear you explicitly endorse it. Thanks for doing so.

As one qualification: I'm uneasy about the MOBI format in virtue of Amazon's closed nature. They make great readers. But when it comes time to copying and pasting one's own highlights, and, by design, you can't: then something is terribly wrong with Amazon. It makes one inclined to support more open, even if propriety, (hardware) competitors. But, of course, given Amazon's position it's a format we can't necessarily ignore - for now.

Each of the toolsets - markdown itself; markdown/pandoc; and asciidoc - appear to be at various stages of early development. Markdown/pandoc, for example, doesn't yet have a MOBI (Amazon) translator (although I've seen it flagged to be done in the issues). Markdown itself gets an attempt to reign in the flavours, through CommonMark. So yes markdown/pandoc seems a little further down the track - but it's early days for all these toolsets. And I can only imagine a benefit from a cross fertilization of ideas from these separate efforts.

And I must confess to having a somewhat shared passion for the future possibilities. Shared, I write, in virtue of seeing one of your talks. I mean I can't help think that these toolsets will emerge as a Really Big Thing. Markedly transforming the way we write, publish, and read. I can see benefit of the forced discipline of separating content and presentation, that familiar web paradigm brought into the world of plainish text, for use in everyday writing. That allows:

* For a less distracted writing experience.
* Publishers to enforce standards on writers - for an automated transformation of source documents into a consistent format.
* For "publishers" to be understood broadly: teacher's receiving essays from students; HR departments receiving resumes. In addition, that is, to those traditionally understood as publishers: Journals receiving articles; newspapers receiving reports from journalists.
* Readers to look at the content in any format they like. That solves accessibility issues at once, to say nothing of sheer personal reading preferences.
* Software source control use on collaborative writing (something I hadn't thought of before you mentioned it in one of your talks - that was received by me as quite the epiphany).

I think also of a day when one or more IDEs supplant MS Word as the preferred writing tool (or MS Word is forced to evolve). I wonder about what such an IDE would ideally look like. Perhaps source and preview side by side synchronized panels (as some Editors currently attempt at various levels of success); or, ironically, source view V WYSIWYG switching (I hold out hope that an WYSIWYG editor can be made that doesn't corrupt the source).

Anyway, if you can withstand the praise: with you at the helm of one of these toolset efforts I'm confident this Really Big Thing will be properly shepherded into existence.

**Comment by mojavelinux** [comment]
> with you at the helm of one of these toolset efforts I'm confident this Really Big Thing will be properly shepherded into existence. (Edit: Imagining sheep on a yacht).

:heart_eyes:
