### ISSUE TITLE
Document theme-related AsciiDoc attributes in theming guide

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#428]
There are certain theme-related attributes that can be set from the document instead of from the theme. Document these attributes in the theming guide to complete the picture.

The attributes are as follows:

* pdf-page-size
* title-logo-image
* front-cover-image
* back-cover-image
* autofit-option
* pagenums (legacy alternative to running content config)

(Note that pdf-page-layout is proposed)

**Comment by jaredmorgs** [comment]
Detail about front-cover-image (from tweeted question to @mojavelinux :

`front-cover-image` takes an inline image macro as a value. Can be image or PDF file.

**Comment by mojavelinux** [comment]
More info here: http://discuss.asciidoctor.org/Cover-on-AsciiDoctor-tp4378p4379.html

**Comment by mojavelinux** [comment]
Also include the following:

* chapter-label

since it doesn't yet get documented in the Asciidoctor User Manual.
