### ISSUE TITLE
Some text on svg image doesn't appear

### ISSUE THREAD

**Issue by JmyL** [asciidoctor/asciidoctor-pdf#430]
The name of each node on svg diagram doen't apear on pdf output like below.

![pdf-output](https://cloud.githubusercontent.com/assets/2654044/14905012/c64a6ec6-0de7-11e6-9e58-12197e069f19.PNG)

It works well on html.

![html-output](https://cloud.githubusercontent.com/assets/2654044/14905022/de1bd274-0de7-11e6-9c7d-9765b05e0b6f.PNG)

SVG file: [mermaid test.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/241608/mermaid.test.zip)
This SVG file is generated with asciidoctor-diagram.
The ource of mermaid diagram is on below.

``` asciidoc
["mermaid", "mermaid test", "svg"]
------------------------------------------------------------
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
------------------------------------------------------------
```

**Comment by mojavelinux** [comment]
Very likely you are hitting the scenario described in https://github.com/mogest/prawn-svg/issues/77. A fix has been committed. We're waiting on a new release of prawn-svg.

**Comment by mojavelinux** [comment]
My previous comment was misleading. This seems to be a style inheritance bug in prawn-svg. The `fill` property on the `actor` class is being inherited by the `<text>` element, so the background and the font color are the same. You can see this by highlighting the box with the mouse. The text is there, it just isn't being colored correctly. The `fill` property on is not overriding the value from the parent.

I can fix this by changing the `text.actor` selector to `.actor-text` and changing the class on `<text>` to `actor-text`. That proves to me there is some sort of property inheritance bug here. This needs to be addressed upstream in prawn-svg.

**Comment by JmyL** [comment]
Thx Dan, you're right. The text is there!

I'm now using 'img' type as alternative for mermaid script. it's not so bad ;)

**Comment by mojavelinux** [comment]
We should still peruse this problem upstream. Would you be willing to create an issue in prawn-svg for it?

**Comment by JmyL** [comment]
Sure. But plz review it ;) I'll mention this issue on there.

**Comment by JensN4** [comment]
I have a similar problem with SVG files, but in my case it is a line decorator (svg attribute "marker-end") which is not drawn correctly. I have attached a minimal example (svg inside zip), created by OmniGraffle. I tried this svg with prawn-svg-0.25.1 and there it worked. Looks as if asciidoctor is still using an older version, that is prawn-svg-0.21.0, is that correct?

So, when running
```
require 'rubygems'
require 'prawn'
require 'prawn-svg'

Prawn::Document.generate("arrow.pdf") do |pdf|
  pdf.svg File.read("arrow.svg"), :at => [0, 600], :width => 500
end
```
the arrow decorator is rendered correctly,

with 

```
image::arrow.svg[]
```

and asciidoctor pdf Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4 the arrow decorator is gone.

Unfortunately I'm not a ruby programmer, otherwise I would have tried asciidoctor-pdf with the latest prawn-svg version...

Which version of prawn-svg is used by asciidoctor? 

[arrow.svg.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/390181/arrow.svg.zip)

**Comment by JensN4** [comment]
Ah: When I enforce asciidoctor-pdf to use the prawn-svg 0.25.1 is is working.

When will this be available in the installable asciidoctor-pdf version?
   gem install asciidoctor-pdf --pre 
installes 1.5.0.alpha.11. Is there a way to install the alpha.12 already (Sorry, I'm really no ruby guy)

**Comment by mojavelinux** [comment]
I'm in the process of getting alpha.12 released.

**Comment by mojavelinux** [comment]
I've filed the bug regarding the text color upstream as https://github.com/mogest/prawn-svg/issues/79. We'll have to wait for that to be resolved before it can be fixed in Asciidoctor PDF.

**Comment by mojavelinux** [comment]
This is working as of prawn-svg 0.29.1 and will be included in the next release.

**Comment by andrea-ligios** [comment]
Hi @mojavelinux, I don't think this is solved.

While it works great on `sequenceDiagram` now, the same error keep happening on `Graphs`:

```
[mermaid, "mermaid test", "svg", width="200"]
----
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
----

```
PDF embedding **mermaid test.svg**:

![immagine](https://user-images.githubusercontent.com/11974750/59864642-94555880-9387-11e9-8a50-b39182df2bde.png)


**mermaid test.svg** opened in a browser:

![immagine](https://user-images.githubusercontent.com/11974750/59864592-6c65f500-9387-11e9-8c89-345666654692.png)

**Comment by mojavelinux** [comment]
Please direct issues with SVG rendering to prawn-svg. Asciidoctor PDF
doesn't render SVG images itself. It just delegates to prawn-svg.

>

**Comment by mojavelinux** [comment]
Also related to: https://github.com/asciidoctor/asciidoctor-diagram/issues/398#issuecomment-1403104176
