### ISSUE TITLE
Linebreaks for URLs when creating PDFs

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-pdf#432]
When putting URLs in documentation, they only line-break at hyphens, but not after "/" or ".". 

I found a workaround to add the link as a description with zero-width-space what leads to

https://www.homepage.com/subdir/subdir/file.html[https://{zwsp}www.{zwsp}homepage.{zwsp}com/{zwsp}subdir/{zwsp}subdir/{zwsp}file.html]

I wonder if either asciidoctor or asciidoctor-pdf could do this automatically (adding a ZWSP after every dot and slash).

**Comment by mojavelinux** [comment]
Using a manual zwsp is the correct way to handle this scenario at the moment.

I suppose it would be nice to be able to specify implicit break points, perhaps controlled using a document attribute.

We need to define the precise rules for handling URLs in print. I found the following FAQ: http://www.chicagomanualofstyle.org/qanda/data/faq/topics/URLs/faq0008.html

> break before a period and most other marks of punctuation—including a slash (but not a double slash; always break after “http://”)

You could use a Treeprocessor to implement this behavior.

**Comment by mojavelinux** [comment]
This functionality was implemented by #563. Note that it does not apply to URIs that are not links (escaped URIs) since Asciidoctor doesn't distinguish these from regular text.
