### ISSUE TITLE
Add support for setting borders for chapter/section headers

### ISSUE THREAD

**Issue by AlexanderZobkov** [asciidoctor/asciidoctor-pdf#434]
Allow to set borders for chapter/section headers. Each heading level (1..6) should allow to configure its own border settings. Border settings include: color, width, side => {top, bottom, left, right}.
Visually it looks like: 
![capture](https://cloud.githubusercontent.com/assets/3214752/14952021/92d9bd00-1065-11e6-9d42-dcb9970b999a.PNG)

**Comment by MonaElsa** [comment]
Hello, 
I'm designing a PDF document with Asciidoctor. I need a possibility to set borders for section headers. Is there currently a possibility?

**Comment by mojavelinux** [comment]
As documented in the theming guide, this is not currently possible using the theme file alone. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-heading

You'd have to extend the converter to add your own logic. You may be interested in the methods `layout_part_title`, `layout_chapter_title`, and `layout_heading`.

**Comment by MonaElsa** [comment]
Thank you for your reply. 
And Sorry for the duplicated Issue. 

When Do you think will be implement the border sets for the theme file?

**Comment by vivien** [comment]
This Header 2 styling is exactly what I'm looking for!

**Comment by mojavelinux** [comment]
Keep in mind you can add a text decoration (e.g., underline) and set the color and width. The difference is that it only spans the width of the text, not the page. See https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc#key-prefix-heading

**Comment by vivien** [comment]
Thank you. This full width decoration helps separating sections nicely in vertical (and justified) documents such as resume, but the text decoration will do just fine in the meantime. Can I increase the vertical space between the heading and its underline though?

**Comment by mojavelinux** [comment]
> This full width decoration helps separating sections nicely in vertical (and justified) documents

Yep, I understand these are mutually exclusive options.

> Can I increase the vertical space between the heading and its underline though?

No, the distance is controlled by Prawn (the PDF generator library) and is fixed.

**Comment by mojavelinux** [comment]
I was going to document how to add this using a custom converter, but honestly it's easier just to implement it. Only the top and bottom border will be supported (left and right values are ignored), and the line will be placed directly adjacent to the text on either end. You can control the distance by adjusting the line height.

```yaml
heading:
  h2:
    border-width: [0, 0, 2, 0]
    border-color: 0000FF
```

One open question is whether we should assume that a singular value is a bottom border only, or whether the singular value should set both top and bottom borders.

If you need more control, you will need to do so using a custom converter. In the future, we may add support for padding, but I'm not making any commitments to that right now.

**Comment by mojavelinux** [comment]
Since headings already support top and bottom margin, I decided to add support for top and bottom padding too, but only per level. The intention of the padding properties is to control the space between the text and the border. They should not otherwise be used.

**Comment by mojavelinux** [comment]
After doing some refactoring of the code for other issues, I've concluded that we can support both padding and border on all 4 edges of a heading per heading level. So we won't need any special exceptions or limitations after all.

The only thing that's not possible is to add a background color. That's even more work and we can address it separately if it is truly needed.

**Comment by mojavelinux** [comment]
It's in!

**Comment by MonaElsa** [comment]
Thank you very much for the Implementation! 

We use it successfully (-:

**Comment by mojavelinux** [comment]
I'm very happy to hear that!
