### ISSUE TITLE
Option to make URLs visible in printed PDF

### ISSUE THREAD

**Issue by fwilhe** [asciidoctor/asciidoctor-pdf#435]
Links in an Asciidoc become links in the PDF. That's fine for screen reading, but not so much for printing. I would like to have an option to specify that links are displayed in a "reference notation", like 

> this is important [1], and so on
>
> 1: http://foo.bar

**Comment by mojavelinux** [comment]
This is a duplicate of #463, which is now resolve. The details about how to use it are documented in that issue.
