### ISSUE TITLE
AsciiDoc table cell styling not functioning in PDF output

### ISSUE THREAD

**Issue by royemmerich** [asciidoctor/asciidoctor-pdf#445]
# Version

```
$ asciidoctor-pdf -V
Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```
# My Wish

To insert an unordered list in the cell of a table in a PDF file.
# The Problem

The table below is a direct copy from the code block example entitled:

**Comparing cells using AsciiDoc styles and no AsciiDoc styles**

from the [asciidoc table cell formatting section](http://asciidoctor.org/docs/user-manual/#cell) of the Asciidoctor Manual.

``` asciidoc
[cols="2"]
|===

a|This cell is prefixed with an `a` so the following list is rendered with the AsciiDoc list element styles.

* List item 1
* List item 2
* List item 3
|This cell *is not* prefixed with an `a` so the following list is not rendered with the AsciiDoc list element styles.

* List item 1
* List item 2
* List item 3

a|This cell is prefixed with an `a` so the following paragraph is rendered with the `lead` style.

[.lead]
I am a paragraph styled with the lead attribute.
|This cell *is not* prefixed with an `a` so the following paragraph is not rendered with the `lead` style.

[.lead]
I am a paragraph styled with the lead attribute.

|===
```

When I generate the PDF the end result looks like this:
![screen shot 2016-05-17 at 11 30 12](https://cloud.githubusercontent.com/assets/3904395/15317673/c84e721e-1c22-11e6-8c27-ab8660db1e97.png)

when it should look like this (screenshot from Asciidoctor manual):

![screen shot 2016-05-17 at 11 32 16](https://cloud.githubusercontent.com/assets/3904395/15317738/0e3d05e2-1c23-11e6-9d75-c25c24fb59ea.png)

**Comment by mojavelinux** [comment]
This is a known limitation right now. See #6.

**Comment by mojavelinux** [comment]
As I mention in #6, what we're going to need to do is implement a custom cell handler in Prawn. That's the only way we'll be able to delegate back into the converter so that the page calculations can be handled by Prawn.
