### ISSUE TITLE
links are html escaped but should not be

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/asciidoctor-pdf#448]
The link 

`https://github.com?foo=1&bar=2[Hello World]
`

in the generated PDF goes to:

`https://github.com/?foo=1&amp;bar=2
`

The ampersand in the url is HTML escaped but should not be.

**Comment by mojavelinux** [comment]
Nice catch! Our text parser handles character references in regular text, but it does not handle them inside attribute values. The main case of this is the link target. We can at least handle that case.

**Comment by mojavelinux** [comment]
PR sent!
