### ISSUE TITLE
Document options for scaling an image

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#453]
Document how images are scaled in Aciidoctor PDF. Explain the following scenarios and how the units are interpreted in each case:

* no dimensions are specified
* height and width are specified (or just height or width)
* pdfwidth (or scaledwidth) is specified

The pdfwidth attribute is the preferred way to control the width of the image in Asciidoctor PDF.

**Comment by mojavelinux** [comment]
This probably belongs in the README for now.

**Comment by mojavelinux** [comment]
Comment from the code:

```
Resolves the explicit width, first considering the pdfwidth attribute, then
the scaledwidth attribute and finally the width attribute. If the specified
value is in pixels, the value is scaled by 75% to perform approximate
CSS px to PDF pt conversion. If the resolved width is larger than the
available width, the available width is returned.
```

**Comment by mojavelinux** [comment]
Note that the height is always ignored. Sizing is always based off of the width.

**Comment by vogella** [comment]
Is it possible to define a general sizing factor? In my DocBook builds I had a XSL customization which used a default scale factor if nothing was specified. This would be super useful to me: Use default scaling factor if nothing is specified on the image, otherwise use the specified value.
-----
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:fo="http://www.w3.org/1999/XSL/Format"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:param name="default.image.scale" select="'0.4'" />

<xsl:template name="image.scale">
    <xsl:choose>
        <xsl:when test="$ignore.image.scaling != 0">0</xsl:when>
            <xsl:when test="@contentwidth or @contentdepth">1.0</xsl:when>
            <xsl:when test="@scale">
                <xsl:value-of select="@scale div 100.0"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="$default.image.scale"/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
</xsl:stylesheet>

----

**Comment by mojavelinux** [comment]
We had a fallback value, but it was removed. Now that I've reworked how the size is calculated, I can see where this could be reintroduced. We should open a separate issue for that. In short, allow the theme to specify a default pdfwidth value for images to be used if the pdfwidth attribute is not specified. Let's discuss in that issue.

**Comment by paolobazzi** [comment]
Could you give a short preview example on how to use pdfwith? With which version of asciidoctor-pdf was this feature introduced?

I tried to scale a PNG (1114x649px) using the following commands:

image:graphics\image.png[pdfwidth=70%]
-> shows the image in full-size, with overflow on the left and right side of the page

image:graphics\image.png[pdfwidth=10cm]
-> shows the image in full-size, with overflow on the left and right side of the page

So in fact, the output is the same as using no width hints:
image:graphics\image.png[]

used versions
<asciidoctor.maven.plugin.version>1.5.3</asciidoctor.maven.plugin.version>
<asciidoctorj.pdf.version>1.5.0-alpha.11</asciidoctorj.pdf.version>
<asciidoctorj.version>1.5.4</asciidoctorj.version>
<jruby.version>9.0.4.0</jruby.version>

Thanks, Paolo

**Comment by mojavelinux** [comment]
pdfwidth applies to block images only. You are currently using inline images. You need to use two colons in the image macro to make it a block image.

**Comment by mojavelinux** [comment]
Inline images are a very special use case that you should only use if you intend for the image to be in the same line as the text. Here's how an inline image is sized:

> The image height is scaled down to 75% of the specified width (px to pt conversion). If the image height is more than 1.5x the height of the surrounding line of text, the font size and line metrics of the fragment are modified to fit the image in the line.

**Comment by mojavelinux** [comment]
I've added this information to the README.

**Comment by paolobazzi** [comment]
Thanks a lot for your additional hint - now the resizing of images works perfect and as expected!

**Comment by mojavelinux** [comment]
:+1:
