### ISSUE TITLE
Allow the theme to specify a default pdfwidth value 

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#455]
The theme should allow to specify a default pdfwidth value for images to be used if the pdfwidth attribute is not specified.

See https://github.com/asciidoctor/asciidoctor-pdf/issues/453

**Comment by mojavelinux** [comment]
We have one condition to work out. If a default image width is specified in the theme, should that value take precedence over the width value in the image macro? (generally, the value of the width attribute is intended as metadata only, not for sizing).

We also need to decide on a name for the key. image_default_width? (It does have to start with image_).

**Comment by vogella** [comment]
> If a default image width is specified in the theme, should that value take precedence over the width 
> value in the image macro?

The most detailed value should be the used one. If no value is specified in image: the default value should be used, otherwise the the specified value. In DocBook I used the default one to define the size for all "normal" images, expect the very few that needed a special setting.

> image_default_width

Sounds good. If it is specific for the PDF output I would add also add pdf, e.g., image_default_pdfwidth

**Comment by mojavelinux** [comment]
>  If it is specific for the PDF output I would add also add pdf, e.g., image_default_pdfwidth

It's in the PDF theme, so PDF is already implied here.

**Comment by mojavelinux** [comment]
So to clarify, the default (specified in the theme) would not be used in this case:

```
image::file.png[Description,640,480]
```

but it would be used in this case:

```
image::file.png[Description]
```

correct?

**Comment by vogella** [comment]
> correct?
Sounds perfect for me.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
I think the default width specified in the theme (`image_width`) should take precedence over the width attribute. I say this because the width attribute is rarely meaningful for PDF, so it should have the lowest priority.

I'm proposing the following precedence:

* pdfwidth attribute
* scaledwidth attribute
* image_width theme key
* width attribute

**Comment by vogella** [comment]
I'm proposing the following precedence:

* pdfwidth attribute
* scaledwidth attribute
* image_width theme key
* width attribute

+1 for the proposal
