### ISSUE TITLE
Add change records

### ISSUE THREAD

**Issue by igagis** [asciidoctor/asciidoctor-pdf#457]
In many documents it is needed to have change records right before the table of contents.
Would be good to have this feature in asciidoctor-pdf

change records could reside in separate file of some format and .adoc could refer to it from a header attribute like

```
:change-records: records.txt
```

**Comment by igagis** [comment]
If moving TOC around the document will be possible in future, then this feature request is not needed.

**Comment by mojavelinux** [comment]
@igagis It's now possible to move the toc using the toc macro (and even to start the page numbering at an arbitrary page in the body). Does that solve your issue?

**Comment by igagis** [comment]
@mojavelinux probably, thanks for implementing it finally. But I'm not working with documents anymore, so cannot test.

**Comment by mojavelinux** [comment]
:+1:
