### ISSUE TITLE
page numbers are not correct if using custom cover page

### ISSUE THREAD

**Issue by igagis** [asciidoctor/asciidoctor-pdf#458]
The document uses :front-cover-image: instead of a title page and :notitle:, so the heading looks like:

```
= bla bla bla
//Name Surname <author@email.com>
:encoding: utf-8
:lang: en
:toc: macro
:pdf-style: pdf-theme.yml
:pdf-stylesdir: theme
:pdf-fontsdir: {pdf-stylesdir}
:toclevels: 3
:sectnums:
:doctype: article
:tabsize: 8
:front-cover-image: image:title_page.pdf[]
:notitle:
:stem:
```

then the generated PDF has wrong page numbers in PDF index. The table of contents still has correct page number. See attached screenshot.
![incorrect page numbers](https://cloud.githubusercontent.com/assets/783401/15578257/73761150-2368-11e6-9abd-9584ddcea07c.png)

Introduction should be on page 1 but in PDF index on the left hand side it says page 2. And so on with other pages.

**Comment by mojavelinux** [comment]
I want to add that it happens only for the article doctype. If you use the book doctype, then it seems to be correct.

However, I noticed when you use the book doctype, the integer page numbers are correct, but the roman numeral pages are not correct.

(side rant: page calculations have proven extremely difficult to get right)

**Comment by igagis** [comment]
ok, I'll try to fall back to book doctype for now

**Comment by igagis** [comment]
actually for book it is same, page numbers are not correct

**Comment by mojavelinux** [comment]
This is going to be resolves as part of #383. The problem was that I did not have entries in the page labels table for all front matter pages, which caused some readers to assign incorrect numbers to the content pages.

**Comment by mojavelinux** [comment]
This change has been merged if you want to try it before I release alpha 13 over the weekend.

**Comment by igagis** [comment]
Thanks! I'll wait for alpha release.
