### ISSUE TITLE
Collapse Whitespaces

### ISSUE THREAD

**Issue by nicolaiparlog** [asciidoctor/asciidoctor-pdf#465]
According to [this comment](https://github.com/asciidoctor/asciidoctor-pdf/issues/449#issuecomment-221424252) repeating white spaces should be collapsed. Unless I am doing something wrong (can I even?) this is not the case.

# Version

    asciidoctor-pdf --version
    Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4 [http://asciidoctor.org]
    Runtime Environment (ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

**Comment by mojavelinux** [comment]
Can you please be specific about where whitespace is not being collapsed? Keep in mind there have been some changes recently in master regarding whitespace, so it would be best if you tested against the development version.

**Comment by nicolaiparlog** [comment]
A simple `space.adoc` containing nothing but

    a            b

gets converted to a PDF with the same number of white space between `a` and `b`. Only in 1.5.0.alpha.11, though. 1.5.0.beta.1.dev (master from today; 62b2dce) collapses them and shows `a b`, so I guess this issue can be closed.

Is a new release planned?

**Comment by mojavelinux** [comment]
I'm working on getting the release out asap. I just have to wrap up a few small issues.

**Comment by nicolaiparlog** [comment]
Good to hear. Impressive work on Asciidoctor, btw. Working with anything else (WordPress, Markdown) feels like a punishment now. ;)

**Comment by mojavelinux** [comment]
Thanks @nicolaiparlog!
