### ISSUE TITLE
Improve dependencies

### ISSUE THREAD

**Issue by Fale** [asciidoctor/asciidoctor-pdf#466]
I'm packaging asciidoctor-pdf for Fedora, and it's dependency are a nightmare. The main reason for this is that multiple dependencies (prawn-*) are fixed to one specific version (also, it's often not the last version) so this makes packaging very hard/next to impossible. I think those dependencies should be widened a little bit (obviously, not if it breaks anything) to allow more versions (aka: newer) to be used

**Comment by mojavelinux** [comment]
I want to begin by saying how excited I am that you are working to package Asciidoctor PDF. That package will definitely make it easier for people on Fedora to use Asciidoctor PDF. Thank you for your work!

Unfortunately, the Prawn ecosystem is still moving around a lot right now and the only way we can keep Asciidoctor PDF stable (in the absence of a test suite) and compatible with AsciidoctorJ is to fix the versions...and in some cases use versions which aren't the latest. The latest Prawn, and some of its addons, require a higher version of Ruby than what AsciidoctorJ, and this ecosystem in general, requires. All that leads us into this very specific version matrix.

Having said that, what I recommend when packaging the RPM is to simply ignore the versions in the gemspec and use the version that maps to what is available release in Fedora. That's what I did when I packaged other dependency-rich gems for Fedora like Awestruct. (Until we have a test suite, it will be hard to know what that breaks, though).

I do think that we are eventually going to get Asciidoctor PDF onto the latest versions of the dependencies (perhaps for the 1.5.0 release), at which point we can loosen up the version requirements.

While I'm excited about the RPM, I recommend holding off a release to the official channels until Asciidoctor PDF is at least in beta. I'm working hard to get it there.

**Comment by veeg** [comment]
I'm also looking into bundling Asciidoctor and Asciidoctor-pdf (RPM based system) for our system/product at work. Right now this is quite hard indeed, and as of yet I have put it off to better times.

**Comment by mojavelinux** [comment]
@veeg Asciidoctor (core) is already packaged for an RPM system, so you should be able to build on that. It's easier because it has no mandatory runtime dependencies. Asciidoctor PDF is tougher because it builds on Prawn, which first needs to be packaged in order to package Asciidoctor PDF (of which several components are now available in Fedora).

**Comment by Fale** [comment]
@mojavelinux I've already made the prawn dependency (as well as others) a [little bit more flexible](http://pkgs.fedoraproject.org/cgit/rpms/rubygem-asciidoctor-pdf.git/tree/asciidoctor-pdf-fix-dependencies.patch).

More than two months passed from this thread, and now [asciidoctor-pdf is in Fedora stable](https://bodhi.fedoraproject.org/updates/?packages=rubygem-asciidoctor-pdf)

**Comment by mojavelinux** [comment]
Wow, that's brilliant! Thank you!

I think the patch against the gemspec is the right approach at this point.

I'd try out the package, but first I need to upgrade from Fedora 21 (I know, I know, I'm way behind).

Here's the other overview page of the package, for reference: https://apps.fedoraproject.org/packages/rubygem-asciidoctor-pdf

Would you be interested in having a clone of the git repository for the package in the asciidoctor organization like we do for the asciidoctor gem?

**Comment by mojavelinux** [comment]
Should we close this issue and revisit again once we get closer to 1.5.0?

**Comment by Fale** [comment]
> I'd try out the package, but first I need to upgrade from Fedora 21 (I know, I know, I'm way behind).

Yeah, F21 is EOL since many months ago :D

> Would you be interested in having a clone of the git repository for the package in the asciidoctor organization like we do for the asciidoctor gem?

If you want to do it, go for it, but since I'm not part of the asciidoctor team in github, I'm not really sure how the workflow would work/which advantages we would have.

**Comment by mojavelinux** [comment]
> For me is ok.

I can set it up and get it started. I'll you'd need to do is `git push` to that remote just to keep it synced. It's just a mirror. I'll make sure you have push access.

> I'm not really sure how the workflow would work/which advantages we would have.

That advantage is transparency. By having the mirror on GitHub, it makes people aware it exists and they can help, and it also makes people aware of it.

**Comment by veeg** [comment]
This is good news, @Fale! I might be able to work upon these specs to bundle for SuSE (our platform) as well. I'm aiming for including it in a product release in summer 2017, so I can hold off at least 6 months before attempting to bundle for it. Let things cool down a bit, hopefully.

**Comment by mojavelinux** [comment]
@Fale Could you add a "provides" alias named asciidoctor-pdf to the package so the rubygem- prefix is not required when installing or searching?

We have a similar alias in the core package. See http://pkgs.fedoraproject.org/cgit/rpms/rubygem-asciidoctor.git/tree/rubygem-asciidoctor.spec?h=f25#n37

**Comment by Fale** [comment]
@mojavelinux yes, absolutely. I was thinking about it but then I never did it.

http://pkgs.fedoraproject.org/cgit/rpms/rubygem-asciidoctor-pdf.git/commit/?id=4b8761696bf92eb8fc874a4e2c304f640aa3b27f

@mojavelinux I don't see the fedora spec repo here yet ;). Can you please add me to the asciidoctor one, since I'm now contributor and admin of that package as well? https://admin.fedoraproject.org/pkgdb/package/rpms/rubygem-asciidoctor/

**Comment by mojavelinux** [comment]
@Fale Absolutely! I'll take care of both of those requests asap.

Again, thank you for your amazing work!
