### ISSUE TITLE
Cannot produce PDF using imagesdir having a URL

### ISSUE THREAD

**Issue by rodneyFinlay** [asciidoctor/asciidoctor-pdf#467]
I need to embed images in the PDF from a central repository referenced by a URL pointed to the base location.  During the invocation to asciidoctor-pdf I'm getting the below error:
undefined local variable or method `image_base_uri' for #<Asciidoctor::Pdf::Converter:0x007fef9402fba8>
Did you mean?  image_page
  Use --trace for backtrace

All documentation seems to agree that if the base URL is in the imagesdir attribute that the image:: block should simply embed the image at that position.

Excerpt from adoc file: 
------------------------
:imagesdir: http://upload.wikimedia.org/wikipedia/commons

image::3/35/Tux.svg[Tux,250,350]

------------------------
Attempting to build using: asciidoctor-pdf -r asciidoctor-diagram -a allow-uri-read $1

using version 1.5.4 of asciidoctor-pdf

**Comment by mojavelinux** [comment]
Oops, it looks like I made several errors when programming this behavior. Thanks for bringing this to my attention! I've issued a fix as PR #468.

Even with this fix, you still need to use the https version of the URL since the wikimedia server does not support a redirect to https (at least not when using the built-in Ruby HTTP client):

```
:imagesdir: https://upload.wikimedia.org/wikipedia/commons

image::3/35/Tux.svg[Tux,250,350]
```

**Comment by rodneyFinlay** [comment]
Great news.  Thanks for addressing this problem.  When is v1.5 due to go to beta / GA?

**Comment by mojavelinux** [comment]
I'm not sure about beta, but I'm trying to get another alpha out asap. I've just been very busy lately, but it's going to happen any day now.
