### ISSUE TITLE
the original spacing of the final annotation in a code block is not respected

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/asciidoctor-pdf#470]
This only happens to the last annotation and only when it is on the last line of a code block.

In the following code block the annotations are aligned.

```
# tag::example1[]
a = 1                # <1>
b = a * 2            # <2>
# end::example1[]
```

But annotation 2 is not aligned in the generated output:

![example1](https://cloud.githubusercontent.com/assets/234664/16363043/0c6515cc-3b84-11e6-936f-6d26f6a1aa1c.png)

However, the spacing **is** respected when the last annotation is **not** on the last line of the included code block.

```
# tag::example2[]
a = 1                # <1>
b = a * 2            # <2>
c = b * 2 + 1 * 2
# end::example2[]
```

![example3](https://cloud.githubusercontent.com/assets/234664/16363182/4e25fc34-3b88-11e6-976b-24b3e8b6bea7.png)

The spacing for annotation 2 is also rendered correctly if we add another line of code with a 3rd annotation, but then that of annotation 3 is not.

```
# tag::example3[]
a = 1                # <1>
b = a * 2            # <2>
c = b * 2 + 1 * 2    # <3>
# end::example3[]

```

output:

![example2](https://cloud.githubusercontent.com/assets/234664/16363051/47e70e52-3b84-11e6-9f5c-26476e9dec4a.png)

**Comment by mojavelinux** [comment]
This is a problem that is specific to Pygments. Pygments strips trailing whitespace while highlighting the code. This affects where the conum is placed on the final line. We'll need to capture the length of the trailing whitespace beforehand and include it when placing the first conum on that line.
