### ISSUE TITLE
Performance issue generating PDF

### ISSUE THREAD

**Issue by mattadamson** [asciidoctor/asciidoctor-pdf#474]
Team,

Generation of the PDF appears to hang i.e. even after one hour it's still processing. I took a few stack trace by suspending the debugger at intervals apart. Can you see anything obvious as to what it's doing and why it could take so long?

I've attached some stacks at periodic intervals

Many thanks

[jstack.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/344638/jstack.txt)
[jstack3.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/344636/jstack3.txt)
[jstack2.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/344637/jstack2.txt)

**Comment by mojavelinux** [comment]
This issue is currently being discussed here: https://github.com/asciidoctor/asciidoctorj/issues/476

**Comment by mattadamson** [comment]
Closing as a duplicate
