### ISSUE TITLE
Release 1.5.0 Alpha 12

### ISSUE THREAD

**Issue by jniggemann** [asciidoctor/asciidoctor-pdf#477]
Please release 1.5.0 Alpha 12.

I'm impatient to try it out because of #313 but it's not yet available :-|

**Comment by mojavelinux** [comment]
I've been extremely busy lately, so this is taking me longer than expected. I was going to fix several other issues, but I've decided instead to push those to alpha.13 and do a release of alpha.12 as is. I'll try my best to get to it this week.

**Comment by jniggemann** [comment]
No worries, I know that FOSS isn't the only thing in life (dayjob, family, other hobbies, friends, ...).
Thank you very much for your work!

**Comment by kastork** [comment]
Looking forward to this.  The prawn update alone will make a big difference for me.

**Comment by mojavelinux** [comment]
Released!
