### ISSUE TITLE
Blank entries in tables

### ISSUE THREAD

**Issue by Eric-Sparks** [asciidoctor/asciidoctor-pdf#480]
I _think_ I understand the problem; just not the solution.

I'm getting this error when I try to render my text:

> data must be a non-empty, non-nil, two dimensional array of cell-convertible objects

I believe this is because I have a table that contains empty cells.  Asciidoctor doesn't have a problem rendering the table appropriately but asciidoctor-pdf complains.

Using Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4/

**Comment by Eric-Sparks** [comment]
More troubleshooting has found the problem:

.SKCC Frequencies
[options="header"]
|===
|===

With an empty table, used for holding a spot for data, asciidoctor-pdf gives the above error while asciidoctor just renders it into html as expected.  I've just commented out this portion of the code for now to get the document to render.  Not sure if you want to call this a bug or actually work it.  I suspect it would be a low priority.

**Comment by mojavelinux** [comment]
You are absolutely correct that the converter should not crash. It should simply draw a single row with a very thin cell to indicate the table has no content. This can be done by automatically adding a single empty cell if the table is empty. That will closely resemble the behavior of the HTML converter.
