### ISSUE TITLE
Items in toc are not clickable if those items contain some CJK characters.

### ISSUE THREAD

**Issue by larsenlouis** [asciidoctor/asciidoctor-pdf#481]
I render this test document with the command ` asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicCN test.asc` with the help of `asciidoctor-pdf-cjk` gem package which provides a library for a good theme and font solution.

Version info:
```
Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-cygwin]) (lc:UTF-8 fs:GBK in:- ex:UTF-8)
```

test.asc
```
= test
:doctype:   article
:docinfo:
:toc:
:toclevels: 3
:toc-title: 目录(Table of Contents)


== English clickable

== 中文 Chinese unclickable

== 한국어 Korean clickable

== カタカナ 片仮名 Japanese unclickable
```

You can also get my rendered PDF [here](https://github.com/asciidoctor/asciidoctor-pdf/files/369249/test.pdf).

**Comment by mojavelinux** [comment]
This appears to be the same problem as #308.

**Comment by mojavelinux** [comment]
When I click the two unclickable links, I get the following warnings in the console:

```
failed to look up _​中文_chinese_unclickable
failed to look up _​カタカナ_​片仮名_japanese_unclickable
```

**Comment by mojavelinux** [comment]
As you can see, PDF cannot reference internal IDs that contain characters beyond a certain range (I'm not sure what that range is). As I mention in #308, we'll need to generate internal IDs using a different strategy that adheres to the PDF specification.

**Comment by mojavelinux** [comment]
Here's the document I'm using for testing:

```
= CJK References
:doctype: book
:toc:
:toclevels: 3
:toc-title: 目录

== English (clickable)

content

== 中文 Chinese (unclickable)

content

== 한국어 Korean (clickable)

content

== カタカナ 片仮名 Japanese (unclickable)

content

See <<_中文_chinese_unclickable>>.
```

**Comment by mojavelinux** [comment]
I think the solution is to convert the anchor to hex if a call to `ascii_only?` returns false. This must be done both where the anchor is defined and where the anchor is referenced. I suppose we could do this for all anchor, but let's start by just doing it when necessary.

In the case of `中文 Chinese`, the anchor will become:

```
0x5fe4b8ade696875f6368696e657365
```

I decided to prefix the hex value with 0x to distinguish it from an ASCII ID.

This change will also squash the following warning:

```
warning: regexp match /.../n against to UTF-8 string
```

The regexp in pdf-core assumes it's working with an ASCII string, so we have to be sure to supply it with one.

**Comment by larsenlouis** [comment]
@mojavelinux  Thanks for your effort! By the way, how did you debug the reference issue you mentioned as following?
```
failed to look up _​中文_chinese_unclickable
failed to look up _​カタカナ_​片仮名_japanese_unclickable
```

**Comment by mojavelinux** [comment]
Do you mean how did I test it?

**Comment by larsenlouis** [comment]
@mojavelinux Yep. What tool did you give the error message?

**Comment by mojavelinux** [comment]
Those error messages come from evince (the PDF viewer in Gnome).
