### ISSUE TITLE
Labeled lists inside a sidebar are not generated

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-pdf#49]
asciidoctor-pdf version: alpha3.
toolchain: via gradle plugin

Snippet that does not generate
```
.Gilb's QA Values
****
Efficiency:: We will always strive to find and implement the most cost effective methods 
to assure long term system quality.
****
```

**Comment by mojavelinux** [comment]
Based on my tests, this seems to be resolved. I can't remember what I did to fix it, but it seems to be working as expected now.

**Comment by mojavelinux** [comment]
Feel free to reopen if you find another case. That way, we have something concrete to address.
