### ISSUE TITLE
SVG fonts affect subsequent text

### ISSUE THREAD

**Issue by kastork** [asciidoctor/asciidoctor-pdf#494]
```
asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.12 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

It is possible this is a prawn bug...

Using default themes and styles, font use following an SVG image matches the SVG rather than the document's style.

Example attached.

The file suffix is `.txt` due to github not accepting `.adoc`, but this is an asciidoc file.

[svg_font_reproducer.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/404161/svg_font_reproducer.txt)

[svg_font_reproducer.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/404158/svg_font_reproducer.pdf)

**Comment by mojavelinux** [comment]
Prawn SVG is only supposed to be setting the font within the block that draws the graphic object sourced from the SVG. It appears this setting is lingering. We'll have to see if this is the responsibility of Prawn SVG (which I think it is) or whether we need to revert the font settings ourselves after calling Prawn SVG.

**Comment by mojavelinux** [comment]
Thanks for reporting, @kastork!

**Comment by mojavelinux** [comment]
Here's a link to the upstream issue: https://github.com/mogest/prawn-svg/issues/80

**Comment by mojavelinux** [comment]
I can apply a workaround that will isolate the font settings that get applied by prawn-svg.

**Comment by mojavelinux** [comment]
The workaround is in place. A fix upstream in Prawn SVG will merely be redundant as far as Asciidoctor PDF is concerned, though that fix still should be made.
