### ISSUE TITLE
Support unbreakable option for quote blocks

### ISSUE THREAD

**Issue by ancarpan** [asciidoctor/asciidoctor-pdf#509]
By default, quote blocks should be split across 2 pages even if they would fit in one page. This prevents a half page empty right before such a block. The current behavior can be restored by adding the unbreakable option to the block.

**Comment by mojavelinux** [comment]
We may also want to think about orphan behavior. In order words, the block would be broken only if it is within a certain threshold of the page break (last 1/3 for instance). This threshold may be something we control globally.

**Comment by ancarpan** [comment]
Hello,
while writing some new documentation I've bumped into the same issue: small code blocks that insert a page break leaving half page empty. Do you think this enhancement will be implemented in a future release?
Thanks

**Comment by RarrugasTetra** [comment]
Is there any hope that the problem will be solved in some nearest future? I have relatively large blocks, due to which some pages are half-empty...

**Comment by mojavelinux** [comment]
Yes, Asciidoctor PDF 2 will stop defaulting to unbreakable. So you will need to add %unbreakable to get that behavior. And the logic for how both are handled will be drastically simplified.

**Comment by RarrugasTetra** [comment]
Very nice! I am really dependent on this feature.

**Comment by Joannanas** [comment]
That would be a very good feature indeed ! I also have big blocks of codes and having 3/4 of the page left blank is quite inconvenient :( 
I cut my code examples manually but I must say that it's really hideous, num lines aren't working either in those cases.

@mojavelinux I saw that there is no real deadline for the v2, do you have any vision about it ? 
I will see to contribute with this issue, but is it possible to have intermediate releases for this type of issues or is it not possible before the v2?

**Comment by mojavelinux** [comment]
Dealing with the layout of breakable and unbreakable blocks is one of the last things I need to do before v2 is released. I have a prototype already development, but it still needs work before it can be merged.

I want to get v2 out as soon as I can. That's all I can say.

**Comment by Joannanas** [comment]
Ok, thank you very much for taking the time to answer and for this clarification :)

**Comment by graphitefriction** [comment]
All delimited blocks are breakable by default in the upcoming Asciidoctor PDF 2.0 release. If you want a specific block to be unbreakable, you'll apply the `unbreakable` option to the block.

[quote%unbreakable]
____
This is a delimited quote block.
____

This issue is related to #2004. This issue was resolved by PR #2020.
