### ISSUE TITLE
Support explicit table width when autowidth option is set

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#519]
When the autowidth option is set on a table, the table should still honor an explicit width. In this case, autowidth enables automatic column sizing only.

```
[%autowidth,width=75%]
|===
| A | B B B B B B B B B B B B B B | C
|===
```

In addition to honoring the explicit width attribute, the converter should also recognize the role "spread" to mean 100% width.

```
[%autowidth.spread]
|===
| A | B B B B B B B B B B B B B B | C
|===
```

Note that an explicit width takes precedence out over the spread role if both are given.

**Comment by mojavelinux** [comment]
Eventually I would like for core to set the tablepcwidth to nil in the case an explicit width should not be used. That will simplify the logic for all the converters.

**Comment by abosshard** [comment]
Is there a special reason why asciidoctor-pdf uses the role `spread` to mean "100% width" instead of `stretch`?

From the [User Manual](https://asciidoctor.org/docs/user-manual/#table-width) on `autowidth`:
> If you want each column to have an automatic width, but want the table to span the width of the content area, add the "stretch" role to the table or set the width attribute to 100%.

**Comment by mojavelinux** [comment]
Oops. Asciidoctor PDF is out of date. That's old terminology. Can you file a new issue to have it renamed? Thanks.

**Comment by abosshard** [comment]
Thanks for the fast response! I'll do that.
