### ISSUE TITLE
Table captions beneath the table (not above)

### ISSUE THREAD

**Issue by kaysgericht** [asciidoctor/asciidoctor-pdf#531]
Is it possible to have the table captions (table 1 : xxx) positioned under the table and not above?

![image](https://cloud.githubusercontent.com/assets/21450727/18158480/dffc09d0-7023-11e6-82a4-a76c12a2969b.png)

I crawled through the sources, but wasn't able to get the result i wished for

![image](https://cloud.githubusercontent.com/assets/21450727/18158493/fd92f5d0-7023-11e6-8538-07f79bbde80c.png)

Thanks for all your great work on this project.

Regards

**Comment by mojavelinux** [comment]
Not at the moment, though I agree it would be a nice feature. I think in general we should be able to use the theme to control the caption placement (above or below).

To proceed, we need to decide how we are going to declare this. Recall that the theme tries to be as faithful as possible to CSS, so perhaps we can use something like:

```yaml
table:
  caption:
    side: bottom
```

(See https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side for the property we are emulating).

This is related to #307.

**Comment by mojavelinux** [comment]
> Thanks for all your great work on this project.

Thanks for appreciating it!

**Comment by kaysgericht** [comment]
Wow, that was fast :)

Thanks for the quick response!

**Comment by mojavelinux** [comment]
The only downside is that we won't be able to guarantee that the caption stays on the same page as the table. That would require knowing ahead of time the height of the rendered table, which would require doing a dry run. I fear that would dramatically slow down conversion. Instead, to support this feature, we might want to see if prawn-table could give us a hook to decide whether or not to advance to the next page before rendering a row.

**Comment by mojavelinux** [comment]
Of course, I realized that we don't keep the caption on the same page as the table now...so we're not losing any behavior yet ;)

**Comment by siddjain** [comment]
@mojavelinux it looks like this is done? could you please provide an example how to use this feature?

**Comment by mojavelinux** [comment]
My first comment shows an example. Here's a complete theme example:

```yml
extends: default
table:
  caption:
    side: bottom
```

**Comment by siddjain** [comment]
@mojavelinux, I was expecting an example of the form:

[id=my-table, what-do-i-insert-here-so-that-table-caption-is-displayed-at-bottom?]
.My table
|===
 3+^| blah
 3+^| blah
^| blah ^| blah ^| blah
|===

I tried caption-side=bottom but that doesn't work.
________________________________

**Comment by mojavelinux** [comment]
It cannot be controlled from the content, so I cannot provide any such
example. It can only be controlled from the theme. And that setting is
global.
