### ISSUE TITLE
Rewrite optimize-pdf as a Ruby script based on rghost

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#535]
Rewrite the `optimize-pdf` executable as a Ruby script and use [rghost](https://rubygems.org/gems/rghost) to Ghostscript. Converting the script to Ruby will allow it to be packaged with the gem, and rghost will manage the interface with Ghostscript.

This issue will also address #21.

**Comment by MaWiMa** [comment]
@mojavelinux 
I tested hexapdf, what about that? (https://github.com/gettalong/hexapdf/blob/master/examples/optimizing.rb)
Only used it to optimize the files generated with asciidoctor-pdf.
If changed compress_pages to true, this will shrink output significant.
My 2,7MB asciidoctor-pdf generated file is now only 536kB (with the bash-script 915kB) big. It is fast, you do not have to write something new, works fine from your ruby-code.

**Comment by mojavelinux** [comment]
@MaWiMa I 100% encourage you to use hexapdf as it does a great job. I plan on mentioning it in the documentation. However, we absolutely cannot integrate it into Asciidoctor PDF under its current license of AGPL. Not only is it incompatible with MIT, it would force this project to become AGPL.

**Comment by mojavelinux** [comment]
My goal is to provide some sort of interface that would allow someone to hook in another implementation, which could be hexapdf. But I can't make a reference to the library at all in this converter.

**Comment by MaWiMa** [comment]
Ok. I did not consider the licenses.

**Comment by mojavelinux** [comment]
hexapdf is now documented in the README. See https://github.com/asciidoctor/asciidoctor-pdf#hexapdf
