### ISSUE TITLE
Custom admonition icons do not render

### ISSUE THREAD

**Issue by cascer1** [asciidoctor/asciidoctor-pdf#542]
Hi,

I just tried setting a custom admonition icon in my theme:

```
admonition:
  icon:
    tip:
      name: fa-fire
```

After rendering my file I still see the admonitions with the default TIP text in front of the admonition text. 

I tried using a couple of different icons from all [available icon sets ](https://github.com/jessedoyle/prawn-icon/tree/master/data/fonts)

I'm using the asciidoctor Maven plugin. The relevant part of my pom.xml is

    <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>1.5.3</version>
        <configuration>
            <sourceDirectory>work/temp</sourceDirectory>
            <outputDirectory>work/output</outputDirectory>
            <sourceHighlighter>coderay</sourceHighlighter>
            <backend>pdf</backend>
            <doctype>book</doctype>
            <attributes>
                <pdf-stylesdir>${project.basedir}/work/template</pdf-stylesdir>
                <pdf-style>custom</pdf-style>
                <pdf-fontsdir>${project.basedir}/work/template/fonts</pdf-fontsdir>
            </attributes>
        </configuration>
        <executions>
            <execution>
                <id>convert-pdf</id>
                <phase>install</phase>
                <goals>
                    <goal>process-asciidoc</goal>
                </goals>
            </execution>
        </executions>
        <dependencies>
            <dependency>
                <groupId>org.asciidoctor</groupId>
               <artifactId>asciidoctorj</artifactId>
               <version>1.5.4</version>
               <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctorj-pdf</artifactId>
                <version>1.5.0-alpha.11</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.jruby</groupId>
                <artifactId>jruby-complete</artifactId>
                <version>1.7.21</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </plugin>

**Comment by mojavelinux** [comment]
You need to set the following attribute at the top of your AsciiDoc file:

```
:icons: font
```

Otherwise, admonition labels are rendered as text.

**Comment by cascer1** [comment]
Thanks. It now renders icons if I do not override them. When I do override them in my custom theme, I get the following error:

```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (default-cli) on project SwaggerMarkupGen: Execution default-cli of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `map' for "fa-info":String -> [Help 1]
```

This happens for any combination of icon names I try.

**Comment by cascer1** [comment]
I managed to resolve the issue. I tried to use shorter identifiers:
```
admonitions:
  icon:
    tip_name: fa-lightbulb-o
    note_name: fa-sticky-note
```

It seems I can only use the full versions:

```
admonitions:
  icon:
    tip:
      name: fa-lightbulb-o
    note:
      name: fa-sticky-note
```

**Comment by mojavelinux** [comment]
Thanks for pointing that out. Yes, the behavior of these keys is special because the hash is passed on directly to prawn-icon. I've clarified the theming guide to point out this fact. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#admonition.
