### ISSUE TITLE
could not embed image

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-pdf#545]
I embed PlantUML diagram in my doc:

```
:target_dir: target

plantuml::umls/Resource.puml[format=svg, alt="Resource Class Diagram", target="{target_dir}/umls/Resource"]
```

Then I run the following command:

```
asciidoctor-pdf -r asciidoctor-diagram diguage.adoc
```

Then throw an error. 

But, when I run the following command, that is ok:

```
asciidoctor -r asciidoctor-diagram diguage.adoc
```

__My document was written with Chinese.__

----

The versions of the gems is : 

```
asciidoctor -v
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)


asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.12 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)


asciidoctor-diagram-1.5.1
```

----
The error log:

```
asciidoctor: WARNING: could not embed image: /Users/diguage/Documents/target/umls/Resource.svg; undefined method `strip' for :italic:Symbol
/Users/diguage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pdf-core-0.6.0/lib/pdf/core/pdf_object.rb:61: warning: regexp match /.../n against to UTF-8 string
/Users/diguage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pdf-core-0.6.0/lib/pdf/core/pdf_object.rb:61: warning: regexp match /.../n against to UTF-8 string
```

**Comment by mojavelinux** [comment]
This is caused by a bug in Prawn SVG that we're in the process of fixing. See https://github.com/mogest/prawn-svg/issues/82

**Comment by mojavelinux** [comment]
I would like to get the prawn-svg upgrade included in the upcoming alpha13 release so we can avoid a lot of error reports like this one ;)

**Comment by mojavelinux** [comment]
prawn-svg 0.25.2 is now available. Just be sure to upgrade.

**Comment by diguage** [comment]
I use the latest source of asciidoctor-pdf and prawn-svg 0.25.2.  Gemfile as following:

```
gem 'asciidoctor-pdf', :github => 'asciidoctor/asciidoctor-pdf', :branch => 'master'
gem 'prawn-svg', '~> 0.25.2'
```

When I ran the command: `asciidoctor-pdf -r asciidoctor-diagram diguage.adoc`, it still threw the error:

```
asciidoctor: WARNING: could not embed image:  /Users/diguage/Documents/target/umls/Resource.svg; undefined method `strip' for :italic:Symbol
```

**Comment by mojavelinux** [comment]
Updating your Gemfile isn't often enough. You also need to delete your Gemfile.lock file, then run bundle again:

```
$ rm -f Gemfile.lock
   bundle
```

Verify that you are actually using prawn-svg 0.25.2 by checking:

```
$ bundle exec gem which prawn-svg
```

**Comment by diguage** [comment]
@mojavelinux  I did it as your advise. First delete Gemfile.lock, then bundle. The log is as following:

```
$ bundle exec gem which prawn-svg
/home/diguage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prawn-svg-0.25.2/lib/prawn-svg.rb

$ asciidoctor-pdf -r asciidoctor-diagram diguage.adoc
asciidoctor: WARNING: could not embed image: /Users/diguage/Documents/target/umls/Resource.svg; undefined method `strip' for :italic:Symbol
```

PS: my document was writen with Chinese charset.

**Comment by mojavelinux** [comment]
You also need to invoke asciidoctor-pdf using "bundle exec". Otherwise,
it's using different gems from somewhere. If you still get this error
message, it means that the new version of prawn-svg is not being used.

It might help also to add the --trace flag.

**Comment by mojavelinux** [comment]
To keep sanity about which gems are being used, I recommend using bundle in local mode. Here's how I do it:

```
rm Gemfile.lock
bundle --path=.bundle/gems
bundle exec asciidoctor-pdf -r asciidoctor-diagram diguage.adoc
```

That way, you know that the gems being used are in .bundle/gems. It isolates you from system-wide (or even user-wide) gems. As you get more comfortable knowing how RubyGems loads do I recommend using other setups.

(This is roughly equivalent to using rvm gemsets. But seeing that you use rbenv, you don't have that feature available).

**Comment by diguage** [comment]
@mojavelinux The prawn gem has an error: <https://github.com/prawnpdf/prawn/issues/983>
