### ISSUE TITLE
Text after quotation is appended into quotation

### ISSUE THREAD

**Issue by meisterluk** [asciidoctor/asciidoctor-pdf#556]
**Given:**

```
Hello World
===========

[[someid]]
____
**Subtitle:** Harhar

Inside the quotation
_____


Normal text afterwards.
```

**Expected result:** One titlepage, one quotation, normal paragraph afterwards

**Actual result:**
![quotation](https://cloud.githubusercontent.com/assets/358358/18431977/ee174dee-78df-11e6-9711-f3b39a313d72.png)

```
meisterluk@linux ~ % asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.12 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
The problem is that your block delimiters are not balanced. This is mandatory in Asciidoctor. Your first one is 4 characters, your second one is 5 characters. Therefore, the block technically never ends.

**Comment by meisterluk** [comment]
Damn, I need to be more attentive. Sorry for wasting your time.

**Comment by mojavelinux** [comment]
Not a problem. I appreciate you testing this so thoroughly. Asciidoctor PDF needs a lot of QA and you're giving it just that.

There is an open issue in core to warn when the end of the document is reached a the current block was never closed. That should help the user from tripping up. See https://github.com/asciidoctor/asciidoctor/issues/1133#issuecomment-63253015
