### ISSUE TITLE
Left border does not render for multi-page verses

### ISSUE THREAD

**Issue by cascer1** [asciidoctor/asciidoctor-pdf#558]
I just quoted a poem (We are seven, William Wordsworth) and noticed the left border does not render properly. I assume this is the case because the poem spans multiple pages.

Please see the [example PDF file](https://github.com/asciidoctor/asciidoctor-pdf/files/470069/poems-example.pdf)

**Comment by cascer1** [comment]
The example file has a long poem and then a short poem (that does not have the same issue) under it.

**Comment by mojavelinux** [comment]
This is a known limitation of the styling at the moment. It's a duplicate of #270 (the quote and verse blocks are currently handled by the same logic, hence why it falls under that issue).

**Comment by mojavelinux** [comment]
This has been resolved by 471af3702929fccf89cd30149bf6399f9dec645f.
