### ISSUE TITLE
Provide progress reporting 

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#569]
This is the opposite of critical, so as long as this is not super trivial to fix, please focus on other issues.

Not sure in which component this is but if I use the Gradle build, I get zero progress reporting.

![image](https://cloud.githubusercontent.com/assets/139910/18717637/d5d6e742-8020-11e6-8fc7-ef9d0b5ee1f7.png)

**Comment by mojavelinux** [comment]
Thanks for proposing this feature. This is definitely an interesting idea I had not thought of. It's certainly possible given that we know how many blocks are going to be processed. I think, however, that this needs to go into core because that's where we can decorate the AST traversal.

**Comment by mojavelinux** [comment]
I'm not entirely sure how we can report this progress to Gradle though. That's sort of the next step after having a way to track where we are in the conversion.

**Comment by mojavelinux** [comment]
Actually, it would be possible to do this in Asciidoctor PDF since a custom converter handles the dispatch of the convert method for each node. The question then is where does it belong.

**Comment by mojavelinux** [comment]
I experimented with a very crude solution to prove the concept:

```ruby
 def convert node, name = nil, opts = {}
    method_name = %(convert_#{name ||= node.node_name})
    result = nil
    if is_root = (method_name == 'convert_document')
      @blocks_to_convert = node.find_by {|b| b.context != :list_item }.map {|b| b.object_id }
      @blocks_to_convert.delete node.header.object_id if node.header?
      @progress_denominator = @blocks_to_convert.size / 100.0
      @blocks_converted = 0
    end
    if respond_to? method_name
      if node.block? && (is_root || !scratch?) && (@blocks_to_convert.delete node.object_id)
        $stdout.write %(\r#{((@blocks_converted += 0.5) / @progress_denominator).round}% complete)
        result = send method_name, node
        $stdout.write %(\r#{((@blocks_converted += 0.5) / @progress_denominator).round}% complete)
        $stdout.puts if is_root
      else
        result = send method_name, node
      end
    else
      warn %(asciidoctor: WARNING: conversion missing in backend #{@backend} for #{name})
    end
    ::Asciidoctor::Inline === node ? result : self
  end
```

**Comment by mojavelinux** [comment]
To summarize, we can report progress at each block. I give a half credit for starting the block and half credit for ending since we're following a depth-first traversal (so the first node we touch is the last node we finish, and so forth).

**Comment by mojavelinux** [comment]
We're still a long way from getting this information to Gradle. Ultimately, it will require a change to the Gradle plugin because it will need to pass on information (probably from AsciidoctorJ) to Gradle. So this issue requires coordination between all the layers involved.

**Comment by vogella** [comment]
Sounds like this is similar to the issue of the error propagation from
Asciidoctor to Gradle.

Am 22.09.2016 10:46 vorm. schrieb "Dan Allen" <notifications@github.com>:

**Comment by mojavelinux** [comment]
Yes, very similar.
