### ISSUE TITLE
Index entries create line breaks

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#570]
Not sure if that is a real issue, or just me using Asciidoc incorrectly. I define index entries:

```
=== What are OSGi services?
(((OSGi,Services))) 
(((Services (OSGi),seealso=Eclipse services)))

A _service_ in OSGi is defined by a standard Java class or an interface.
```

This results in a visual space in the generate PDF.

Is this my error or an error in the generator?

![image](https://cloud.githubusercontent.com/assets/139910/18727265/264ae4cc-8048-11e6-9e41-baa131bfd614.png)

**Comment by mojavelinux** [comment]
Index entries need to be "rooted" to block content. Otherwise, they end up creating a blank paragraph. In the scenario you cited, you need to move the blank line that is below the index entries above them, putting the index entries adjacent to the first paragraph.

**Comment by mojavelinux** [comment]
Note that currently, index entries can't be associated with a section title (so they can't go above it).

**Comment by vogella** [comment]
Thanks for the explanation. Shall I close this bug?

**Comment by mojavelinux** [comment]
I'd say yes, but it would make more more comfortable if we documented this point in the following section of the user guide.

http://asciidoctor.org/docs/user-manual/#user-index

That should open the conversation about whether we need to allow the placement of index entries to be more flexible. As I mentioned, right now, they are "coupled" with non-section, block-level (typically paragraphs).

**Comment by vogella** [comment]
> we need to allow the placement of index entries to be more flexible

I don't think it is required but a section header feels like the best place to put an index reference. If I put it into the text, I loose a little bit the overview of my index entries.

**Comment by vogella** [comment]
Finally tested it (sorry PDF generation takes very long and I re-ran it several times).

````
=== What are OSGi services?
(((OSGi,Services)))
(((Services, OSGi)))
A _service_ in OSGi is defined by a standard Java class or an interface.
````

still results in lot of whitespace, see screenshot from the first comment.

**Comment by mojavelinux** [comment]
I'm not seeing any excess space. Can you provide more details about how you are invoking Asciidoctor PDF (or point me to the document you are converting)?

**Comment by mojavelinux** [comment]
I cannot reproduce this report. It's possible there are other invisible characters in the text that are creating the extra line breaks. If you can submit a reproducible test, then please reopen and we'll address it.
