### ISSUE TITLE
Add support for include directive in theme file

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#571]
Add support for the include directive in the theme file to allow common themes to be combined.

The keys from the include will need to be combined using a deep merge.

I propose something like:

```
!include 'shared.yml'
```

A relative path will be resolved relative to the value of the pdf-stylesdir attribute.

**Comment by veeg** [comment]
How would you describe the role of base-theme.yml compared to this inclusion mechanism?
As of now, the base-theme is only loaded from the default theme directory location. I was looking into using this as my shared base but got rather uncertain when its not loaded dynamically to the user-provided themedir path.

**Comment by mojavelinux** [comment]
There's an ongoing discussion about support for includes in YAML here:

https://stackoverflow.com/questions/528281/how-can-i-include-an-yaml-file-inside-another

There's a Ruby library that provides an implementation of this functionality (using the extends construct)

https://github.com/entwanderer/yaml_extend

**Comment by mojavelinux** [comment]
The base theme is just there to provide sane defaults if the custom theme doesn't provide any overrides. In short, it allows Asciidoctor PDF to function.

**Comment by mojavelinux** [comment]
This became a duplicate of #367 and was resolved in 1.5.0.alpha.18.

See this section in the theming guide for details: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-extends
