### ISSUE TITLE
Support margin top for headings if they are at the top of the page

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#576]
@mojavelinux explained in https://github.com/asciidoctor/asciidoctor-pdf/issues/572#issuecomment-248993325 that margin-top are currently only supported when the heading follows other content on the same page and suggested to open a new issue for the support if its on the top of the page.

**Comment by mojavelinux** [comment]
This is related to #176, which requests for margins to be set per heading level.

**Comment by mojavelinux** [comment]
How should this be expressed? We could support padding_top, which would be non-collapsing like in CSS. Or we could support `overflow: auto` like in CSS to prevent the margin from collapsing. Or we could add `margin-top-collapse: separate` (like the experimental CSS property).

**Comment by mojavelinux** [comment]
Actually, I have a different idea which i think will work better. How about:

```
heading:
  margin-page-top: 10
```

That way, you can control the margin when the heading is at the top of the page, and perhaps even make it different.

Feel free to suggest another name if you have a better idea.
