### ISSUE TITLE
Wrong message "section title out of sequence" if [appendix] is used

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#595]
If I build a book, the message is wrong.

Example:

````
[appendix]
= Appendix

== First entry in appendix

Asciidoc supports also the definition of an appendix.
````

If I remove [appendix] all works well.

PR for the gradle-example project incoming to show this issue.

**Comment by mojavelinux** [comment]
Actually, per the structure rules for AsciiDoc, this warning message is correct. An appendix is implied to be a level-1 section (even if it is written as a level-0 section), so the first child section must be a level-2 section.

The most correct way of writing it is as follows:

```
[appendix]
== Appendix

=== First entry in appendix

AsciiDoc supports also the definition of an appendix.
```

**Comment by vogella** [comment]
Thanks. So we close this issue?

**Comment by vogella** [comment]
If I define == Appendix, it is not the same, as a part. It will become a simple section, which is not what is desired here. Reopening. 

Asciidoctor seems not to consider doctype book correctly.

**Comment by mojavelinux** [comment]
Getting the section levels for an appendix right in AsciiDoc is a little tricky, especially in a multi-part book. In fact, I even fooled myself. Here is what you want:

```
[appendix]
= Appendix

=== First Section of Appendix

AsciiDoc supports also the definition of an appendix.
```

I know it's strange that the first section of an appendix has to be level 2 (3 =) instead of level 1 (2 =), but that's because in DocBook, an appendix cannot have chapters (only sections).

(This needs to be documented in the User Manual. I'll do that now).

If you write it that way, is there something about the output that you don't expect / doesn't meet your expectations?

**Comment by vogella** [comment]
If I write it with == Appendix I get:

![image](https://cloud.githubusercontent.com/assets/139910/19104772/a9c64bde-8ade-11e6-8626-0806e095510a.png)

If I write it with = Appendix, it gets on the same level as a part.

**Comment by mojavelinux** [comment]
And where do you want it to appear?

**Comment by vogella** [comment]
> And where do you want it to appear?

Sorry I thought I said this already:
````
If I write it with = Appendix, it gets on the same level as the last part, which is what I want.
````

Screenshot:

![image](https://cloud.githubusercontent.com/assets/139910/19106068/aa68b3a4-8ae5-11e6-9205-46cd39ca2bb9.png)

**Comment by mojavelinux** [comment]
Perfect!

Btw, I updated the documentation about the appendix in the User Manual to explain this exact scenario. If you think it can be improved, don't hesitate to mention it. See http://asciidoctor.org/docs/user-manual/#user-appendix

**Comment by vogella** [comment]
Thanks. Looks good.
