### ISSUE TITLE
Ability to configure the part label

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#597]
Similar to `chapter-label`, which allow us to set the prefix of all chapters, it would be great to have `part-label`.

Example document:

```
= Book Title
:doctype: book
:part-label: P

= Part Title

== Chapter Title
```

**Comment by mojavelinux** [comment]
We'll also need to add a number (upper roman numeral) if section numbering is enabled to be consistent with DocBook / dblatex output.

**Comment by vogella** [comment]
@fap- Something for you?

**Comment by mojavelinux** [comment]
The label should only be shown if section numbering is enabled. However, since core doesn't currently number parts, we'll need to patch in that functionality.

**Comment by mojavelinux** [comment]
So in your example, the part would appear as follows:

Part I. Part Title

correct?

**Comment by vogella** [comment]
> So in your example, the part would appear as follows: Part I. Part Title
With :part-label: P is would expect an output of:

P I. Part Title

**Comment by mojavelinux** [comment]
Right, that's what I meant ;)

**Comment by mojavelinux** [comment]
To follow the terminology we worked out in core, I think the attribute should be named `part-sig` (or `part-signifier`). We are moving away from the term "label" since that is overloaded in LaTeX to mean "id".

**Comment by mojavelinux** [comment]
Here's how this will be implemented.

To add the part signifier (aka label) and part number, you must set the `partnums` attribute.

```
= Book Title
:sectnums:
:partnums:
```

You can customize the part signifier using the `part-signifier` attribute:

```
= Book Title
:sectnums:
:partnums:
:part-signifier: P
```

Not that the part signifier (as well as the chapter signifier) is not used in the table of contents.

**Comment by vogella** [comment]
Thanks. @fapdash I think we can retire your modification for this.

**Comment by mojavelinux** [comment]
That's music to my ears. I'm keen to get your feedback (while it's fresh).
