### ISSUE TITLE
Content in table head cell isn't considered when determining width of column

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#599]
The content in the table head cell (i.e. the cell in the table head row) isn't considered when determining the (automatic) width of the column. As a result, if the content in this cell needs more space than the body cells in the same column, the content in the head cell gets hard wrapped by char.

**Comment by mojavelinux** [comment]
Consider the following AsciiDoc:

```
[%header%autowidth]
|===
|Operation |Operator

|multiply
|*

|divide
|/

|add
|+

|subtract
|-
|===
```

Here's how it is rendered:

![issue-599](https://cloud.githubusercontent.com/assets/79351/19012182/1a47899e-876b-11e6-87f6-7d9a038c655f.png)

**Comment by mojavelinux** [comment]
This problem has been resolved prawn-table and the fix will be available in the next release of that library (perhaps 0.2.3). If it's released before alpha.14, I'll upgrade the version in the gemspec. If not, I'll loosen the version range to `~> 0.2.2` so the release gets picked up once available.

As described in the linked issue, the problem was the the width calculation was not being performed on the formatted (i.e., bold) text. Therefore, the calculation was off by enough to cause the content in the head cell to not fix on the line.

**Comment by owenh000** [comment]
Until a new prawn-table release, possible workarounds for this problem include:

- setting `table_head_font_style: normal` in your theme,
- not using the `autowidth` option for the affected tables, and
- adding non-breaking spaces (U+00A0) to unformatted text in a cell of the affected column.

**Comment by mojavelinux** [comment]
Another way to solve this problem is to add the following to your Gemfile:

```rb
gem 'prawn-table', github: 'prawnpdf/prawn-table'
```

Since this is solved by upgrading prawn-table, and it's possible to use the development version of prawn-table with Asciidoctor PDF, I'm going to mark this as closed (with workaround).

**Comment by mojavelinux** [comment]
It's no longer necessary to use the unreleased version of prawn-table with Asciidoctor PDF. Please use the latest release of prawn-table from rubygems.org. That's the only version that is tested with Asciidoctor PDF.
