### ISSUE TITLE
Add support for AsciiDoc cell content

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#6]
Add support for AsciiDoc cell content. Currently, the raw AsciiDoc source is passed through to the PDF file.

**Comment by mojavelinux** [comment]
I looks like we're pretty limited by what we can put into a cell in Prawn. We're going to have to focus on a subset of content that we can offer and make that as good as we can.

We can put an image in a cell, but only one. We won't be able to do arbitrary block content. We could probably fake lists. Given that images and lists are the two most likely things you put into cells...maybe source code as well.

I'm going to start by focusing on the use case of a single block image. There's actually an API for that :)

**Comment by mojavelinux** [comment]
It does look like it's possible to define our own type of Cell and respond to the `draw_content` method, which gives us the chance to write directly to the PDF. However, we'd likely need to patch prawn-table upstream (or monkeypatch it) to make it stick.

See the code for Cell::Image to get the idea: https://github.com/prawnpdf/prawn-table/blob/master/lib/prawn/table/cell/image.rb#L62-L64

**Comment by mojavelinux** [comment]
I've added initial support for AsciiDoc table cell content. See https://github.com/asciidoctor/asciidoctor-pdf/pull/120

The most important and complete support is for a table cell with a single block image. There's also good support for a table cell with a single paragraph. I've hacked in a few additional options, including basic (but incomplete) support for literal, listing, quote and verse.

cc: @paulrayner

**Comment by mojavelinux** [comment]
I'll leave this issue open a bit longer, though eventually I foresee creating more fine-grained issues so we can tackle each challenge one at a time.

**Comment by paulrayner** [comment]
:+1:

**Comment by mojavelinux** [comment]
I took this a lot further. What's there now should be sufficient to cover most, if not all, basic use cases. The layouts inside AsciiDoc table cells is a bit lacking, but the content is mostly there and styled somewhat sensibly.

In order to do this right, we need to subclass Table::Cell and tie directly into the pdf object. However, the work done in this pull request makes the requirements a bit more clear and hopefully paves the way for that refactoring.

**Comment by mojavelinux** [comment]
By basic, I mean things like stacking images in a table cell, a table cell with multiple paragraphs, a paragraph and a few list items, etc. It's not fancy, but it's something.

**Comment by mojavelinux** [comment]
I am looking for real world use cases of AsciiDoc table cell content that aren't met sufficiently by this change (or just in general).

Keep in mind that a cell must be marked as AsciiDoc content when it contains block-level AsciiDoc. The "a" essentially switches the cell from being of type paragraph (i.e., inline text) to an arbitrary number of blocks.

**Comment by paulrayner** [comment]
I'll do some experiments next week and let you know. This is exciting!



Paul

**Comment by mojavelinux** [comment]
The Groovy language guide has some pretty good examples of AsciiDoc table cells. Mostly it's a source listing in a cell. That's a case we should try to cover as well as possible (it won't be perfect, but we can make it readable at least).

**Comment by msavy** [comment]
I was playing with asciidcotor-pdf and have cooked up an example which doesn't quite render properly in PDF which may prove useful:

https://gist.github.com/msavy/7500fe0bdf08a6297888

Renders cleanly through the usual asciidoctor -> HTML pipeline

![screen shot 2015-06-19 at 11 53 10](https://cloud.githubusercontent.com/assets/423513/8252091/18b78790-167a-11e5-9868-0f1365558ada.png)

Not quite right in PDF (i.e. newline missing after initial para)

![screen shot 2015-06-19 at 11 55 58](https://cloud.githubusercontent.com/assets/423513/8252105/33cdd7dc-167a-11e5-9d40-a8b28160afd1.png)

Using latest HEAD

```
[msavy@mmbp tmp](master)$ asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.dev using Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

Hope that's helpful!

**Comment by mojavelinux** [comment]
Thanks @msavy! That's exactly the type of example I was looking for.

I'm happy to say that the pending pull request for this issue will handle this case. I think for the first iteration, I'm going to keep it simple. It will likely support the following blocks:

* block image
* paragraph
* source block
* floating title

The rest of the block types will be emitted raw, almost so it looks like the AsciiDoc source. The next step will be to implement the Cell interface so that we can render the remainder of the block types in the normal way.

**Comment by kongou-ae** [comment]
:+1:

**Comment by gtapper** [comment]
Bullet List example

```
[cols="20%a,30%a,50%a",options="header"]
|===
| User ID              | Usage           | Requirements
| Linux                | Run the Trafodion Installer, which sets up the enviroment and installs the Trafodion software.  | 
* User name or group cannot be `trafodion`.
* Passwordless ssh access to all nodes in the cluster.
* Internet access to download software packages.
* `requiretty` must be disabled in `/etc/sudoers`.
* `sudo`^1^ access to:
** Download and install software packages.
** Mofify `/etc/sudoers.d` (allow the `trafodion` user to modify floating IP: `ip` and `arping`).
** Create the `trafodion` user ID and group.
** Install Trafodion software into the HBase environment.
** Run Java version command on each node in the cluster.
** Run Hadoop version command on each node in the cluster.
** Run HBase version command on each node in the cluster.
** Create directories and files in:
*** `/etc`
*** `/usr/lib`
*** `/var/log`
** Invoke `su` to execute commands as other users; for example, `trafodion`.
** Edit `sysctl.conf` and activate changes using `sysctl -p`:
*** Modify kernel limits.
*** Reserve IP ports.

^1^ `sudo` is *required* in the current release of Trafodion. This restriction may be relaxed in later releases.
Alternative mechanisms for priviliged access (such as running as `root` or `sudo` alternative commands) are not supported.
| Distribution Manager | Modify configuration and stop/start services. | 
* Administrator user name and password.
* URL to Distribution Manager's REST API.
| HDFS Administator | Create directories and change security setting, if needed. | 
* HDFS Administrator user name and password.
* Write access to home directory on the node where the Distribution Manager is running.
| HBase Administator | | 
* HBase Administrator user name and password.
* Read access to `hbase-site.xml`.
|===

```

**Comment by Gitward** [comment]
Displaying Asciidoc content in table cells seems to work when creating the PDF using https://github.com/asciidocfx/AsciidocFX . What have they done to solve the problem?

My Test-document:

```
= Test
:doctype: article
:notitle:
:!toc:

AsciidocFX shows links in PDFs as footnotes http://stackoverflow.com[SO].

.Asciidoc in PDF does not work in Asciidoctor, but works in AsciidocFX.
[cols="2,5a"]
|===
|Line with Asciidoc code
|here comes a list:

* item 1
* item 2
* item 3

http://stackoverflow.com[Get Answers]!

|Line
|with a footnotefootnote:[footnotes do work in AsciidocFX's PDF output (but not in the preview).]

|===
```
The output of asciidoctor (using gradle):

![asciidoctor](https://cloud.githubusercontent.com/assets/8510849/15852939/532ac8de-2ca3-11e6-8908-821c0bba0895.png)

The output of asciidocFX:

![asciidocfx](https://cloud.githubusercontent.com/assets/8510849/15852949/5ac9f6be-2ca3-11e6-943e-47ba275c07bd.png)

**Comment by mojavelinux** [comment]
AsciiDocFX is not yet using Asciidoctor PDF. Instead, it uses the DocBook toolchain. It's essentially using [fopub](https://github.com/asciidoctor/asciidoctor-fopub) under the covers, which executes and manages the DocBook toolchain.

**Comment by jmini** [comment]
See also this question on StackOverflow: [Multiple paragraphs in AsciiDoctor table cell](http://stackoverflow.com/q/38123748)

**Comment by mojavelinux** [comment]
I was able to figure how to write a custom Cell implementation. However, it appears that we have a few limitations, some of which are coming from Prawn Table.

* works best if column is assigned an explicit (relative) width (otherwise, cell assumes max available width)
* does not permit content that exceeds the height of one page
* extra padding from last block is added to bottom of cell
* alignment of content within cell does not yet work

**Comment by buffe** [comment]
Hi @mojavelinux is this fix to make table cells parse as asciidoc content has released? I can see the release version is changed to 1.5.0 beta.1

**Comment by mojavelinux** [comment]
This will be fixed in alpha.14, which is the next release. The release is ready to go out, I just need to do it.

**Comment by buffe** [comment]
Awesome, looking forward to that.
