### ISSUE TITLE
Problem Windows-1252 character with version 1.5.0.alpha.13

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor-pdf#612]
with asccidoctor-pdf 1.5.0.alpha.**13** I have this problem with conum
`
The following text could not be fully converted to the Windows-1252 character set:
| ②
`
and
`
M+ 1mn is not a known font.
`

The font M+ 1mn is present in the pdf-fontsdir

I was not this problem with asccidoctor-pdf 1.5.0.alpha.**12**

ty
Jerome

**Comment by mojavelinux** [comment]
Can you provide more details about your setup? Specifically, what does the font settings in your theme look like and what attributes are you passing to Asciidoctor?

**Comment by JBR69** [comment]
theme for conum

```
conum:
  font_family: M+ 1mn
  font_color: $literal_font_color
  font_size: $base_font_size
  line_height: 4 / 3
```

and attributes  for asciidoctor
```
:doctype: book
:encoding: utf-8
:lang: fr
:toc: left
:toc-title: Table des matières
:toclevels: 6
:revnumber: 1.0 
:revdate: {localdate}
:commonResourcesDir: ../../../resources
:icons: 
:iconsdir: {commonResourcesDir}/icons
:stylesdir: {commonResourcesDir}/css
:stylesheet: theme.css
:pdf-stylesdir: {commonResourcesDir}/yaml
:pdf-fontsdir: {commonResourcesDir}/yaml/fonts
:pdf-style: pdfTheme
:pdf-page-size: A4
:specifImagesDir: ../../resources/images/CMN-AA
:title-logo-image: {commonResourcesDir}/images/logo.png
:chapter-label:
```

**Comment by JBR69** [comment]
OK it was a problem in my theme :-(

**Comment by mojavelinux** [comment]
👍

Sometimes it helps to talk through it.
