### ISSUE TITLE
SVG images in header or footer don't respect pdfwidth attributes

### ISSUE THREAD

**Issue by tkfu** [asciidoctor/asciidoctor-pdf#625]
I'm trying to put a logo in the header, which I have as a nice clean SVG. It works just fine with the pdfwidth attribute on the title page; `logo_image: image:a-plus-logo.svg[pdfwidth=25%]` gives me the expected output.

However, any sizing directives I try to give it for the one in the header or footer just get ignored. The screenshot attached here is with `content: image:a-plus-logo.svg[pdfwidth=10%]`, but I've also tried the `scaledwidth` and `width` attributes, and with different units specified (px and in). No matter what I do, the image stays the same size. I do have a workaround at the moment: I just use separate SVG files for different sizes. But that's not ideal, especially since it's a trial-and-error process to get the sizes right.

The pdfwidth attribute works as expected in the header/footer when the image is a PNG, but I'd much rather use a vector format in this case.

![screen shot 2016-10-13 at 4 27 04 pm](https://cloud.githubusercontent.com/assets/4501758/19353138/a5c7a494-9162-11e6-9584-418e145229a7.png)

**Comment by mojavelinux** [comment]
You're right. The svg method doesn't support the fit option (like for
raster images). As a result, the specified width is being ignored and the
SVG renders in the intrinsic size. I'll need to fix the options so the
width is honored.
