### ISSUE TITLE
Allow dot leaders in toc to be hidden per section level

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#631]
Allow the dot leaders between the section title and the page number to be hidden per section level, as they are not always desired.

We're considering several proposals for configuring this setting in the theme:

```yaml
toc:
  h2_dot_leader_visibility: hidden
```

or

```yaml
toc:
  dot_leader_levels: 2 3 4
```

or

```yaml
toc:
  dot_leader_visibility: hidden, hidden, visible, visible, visible
```

If not specified, the dot leaders are shown for all levels.

**Comment by mojavelinux** [comment]
The only problem I see with these proposals is that we are looking at the sections by their levels instead of their semantics. I suppose that will get us by for now, but eventually I think we're going to need to be able to address a "part" or a "chapter" instead of just a level number.

**Comment by mojavelinux** [comment]
I like proposal 2 for getting this feature implemented. I'll probably start down that path and I can adjust if we decide on another solution.

**Comment by mojavelinux** [comment]
@habamax PR available.

**Comment by habamax** [comment]
Cool!

Now I have to figure out how to check it out. I use `gem install --pre ...` and I guess raw github version should be used.

Not familiar with ruby stuff yet (how to use non-gem version of an application etc)

**Comment by habamax** [comment]
I have checked your issue-631 branch. It is ok as far as I can see.

![asciidoctor-pdf-toc-631](https://cloud.githubusercontent.com/assets/234774/19432558/be997a1e-9465-11e6-9e1e-7eb047b5aafb.png)

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
Given how I've implemented this, I've left room to refer to levels by type.

```
toc:
  dot_leader_levels: part chapter 3
```

Those keywords aren't implemented yet, but there's room for it in the future.
