### ISSUE TITLE
Long line in TOC messes leaderdot and pagenum

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#635]
Asciidoctor-pdf:

![toc-ascidoctor](https://cloud.githubusercontent.com/assets/234774/19602127/a6d0b648-97b4-11e6-8ae8-9ea4f4254252.png)

The same in msword (and I believe latex does it too)
![toc-word](https://cloud.githubusercontent.com/assets/234774/19602129/a8464830-97b4-11e6-9c4f-8a2a3441c580.png)

**Comment by mojavelinux** [comment]
This requires diving deep into the internals of text handling in Prawn to implement. I don't have any plans of doing it myself. If someone would like to contribution this change, please feel free.

**Comment by mojavelinux** [comment]
This is a duplicate of #1152. I now understand how this can be implemented.
