### ISSUE TITLE
Page number does not increment in navigator if page does not have an outline entry

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#641]
If I have a section which extends more than one page, the "logical page number" is not correct. This seems to break certain PDF printing tools.

Here is a wrong page:

![image](https://cloud.githubusercontent.com/assets/139910/19665472/5dc2a0e0-9a45-11e6-865f-3e13ed23e122.png)

Here is a correct page:

![image](https://cloud.githubusercontent.com/assets/139910/19665485/6980634a-9a45-11e6-9ecf-f81184a79768.png)

Example: https://github.com/vogellacompany/asciidoctor-gradle-examples/tree/wrongpage use the asciidoctor-gradle-examples/asciidoc-to-pdf-example example.

**Comment by vogella** [comment]
PR to demonstrate the issue: https://github.com/asciidoctor/asciidoctor-gradle-examples/pull/34

**Comment by mojavelinux** [comment]
You are testing using alpha.11. This has since been fixed (as of alpha.13). See #88.

**Comment by mojavelinux** [comment]
If you want to test Gradle using the latest gem release, you need to configure the gem in the Gradle build. I documented the steps in the following comment: https://github.com/asciidoctor/asciidoctor-pdf/issues/572#issuecomment-248848703.

Until we get AsciidoctorJ PDF releases timed with the Ruby gem release, I strongly recommend using the gem directly.

**Comment by vogella** [comment]
I also see this issue with alpha.13

**Comment by vogella** [comment]
Example can be found in the following "test case" repo: https://github.com/vogellacompany/asciidoctor-gradle-examples

Branch wrongpage, project asciidoc-to-pdf-example

Requires the alpha13.jar to be in the local maven repository

**Comment by mojavelinux** [comment]
This particular case doesn't exhibit the bug that #88 fixed, but it does address cases when the page numbers were off.

Having said that, it's important to understand that there are two sets of page numbers. There are the physical page numbers and the effective (visual) page numbers. We are doing exactly the right thing, but some PDF readers get confused.

The page number widget shows the following for the title page:

```
i (1 of 9)
```

The "i" is the visual page number and the "1" in the "1 of 9" is the physical page number.

The page number widget shows the following for the first content page:

```
1 (3 of 9)
```

Again, the "1" is the visual page number and the "3" in the "3 of 9" is the physical page number.

This is just how PDF works as far as I understand it. We aren't making those page numbers. That's how the reader is interpreting the outline. But our outline is to spec.

**Comment by vogella** [comment]
> But our outline is to spec.

Sorry, but I do not understand this comment. Why would a wrong page number display be according to spec? Currently page 2 does not exists for printing tools. And if you switch from page 1 to the next page you have page 1, after switching to the next page you have page 3.

**Comment by mojavelinux** [comment]
This sounds like the behavior from alpha.11. I can't reproduce your first screenshot.

**Comment by mojavelinux** [comment]
To clarify, what is causing the difference between screenshot 1 and screenshot 2? Are you using a different version?

**Comment by mojavelinux** [comment]
I do agree that the following is incorrect:

```
1 (4 of 9)
```

I just don't see how you are getting that.

**Comment by mojavelinux** [comment]
Oops, scratch that. I see now.

**Comment by vogella** [comment]
> Are you using a different version?

This is in the same output PDF. We have page 1, page 1 and afterwards page 3. AFAIK Github issues do not allow for attachments, if desired I can send you the generated output via email.

**Comment by mojavelinux** [comment]
I wasn't scrolling far enough. I see it now.

**Comment by vogella** [comment]
> I wasn't scrolling far enough. I see it now.

Sounds good. Thanks.

**Comment by mojavelinux** [comment]
So this is still related to #88, and addresses an open question I had. Notice that there is no heading on logical page 2 and no entry for page 2 in the outline. This seems to confuse the reader.

I think the solution is that the outline array needs a placeholder entry for any page with no matching outline entry. Otherwise, the reader doesn't know to advance the page number. This is really bizarre to me that the reader can't figure this out. At least we know what fixes it.

**Comment by mojavelinux** [comment]
In other words, we need to extend the fix for #88 to all pages, not just front matter pages. Every page must be accounted for in the outline. Specifically, hidden pages must be added for pages that have no outline entry.

**Comment by mojavelinux** [comment]
Correction. Every page must be accounted for in the page labels catalog (not the outline).

```
65 0 obj
<< /Nums [0 << /P (i)
>> 1 << /P (ii)
>> 2 << /P (1)
>> 4 << /P (3)
>> 5 << /P (4)
>> 6 << /P (5)
>>]
>>
endobj
```

Notice that the following entry is missing:

```
>> 3 << /P (2)
```

**Comment by mojavelinux** [comment]
What I said in #88 (or somewhere linked to it) is correct. Once you add page labels, you have to account for every page or else the PDF reader can't figure out how to count.

**Comment by vogella** [comment]
Thanks @mojavelinux for looking into this.

**Comment by mojavelinux** [comment]
Thanks for reporting. It took me awhile to see what you were saying, but once I got it, I realized you answered an open question I had left behind.

**Comment by mojavelinux** [comment]
Now I know. If a page is missing from the page labels, the reader doesn't know how to count it ;)

**Comment by vogella** [comment]
Thanks @mojavelinux.

@fap- maybe worth looking at the commit, to see how Asciidoctor issues can be fixed.
