### ISSUE TITLE
Images resize for sidebar does not consider max-width

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor-pdf#642]
If an image resides in sidebar it can grow out of page boundaries . It seems it does not consider max-width during scaling
![test adoc](https://cloud.githubusercontent.com/assets/3511038/19701503/fbc670ee-9afb-11e6-8e2c-8aec484017e4.png)

**Comment by mojavelinux** [comment]
Can you please share the snippet of AsciiDoc you are using to reference the image?

**Comment by shahryareiv** [comment]
```
[.marginfigurenote]
.FI-PPP project logo.
image:fig_fippp_logo.png[alt="FI-PPP project logo"] +

[.marginfigurenote]
.FIWARE platform logo.
image:fig_fiware_logo.png[FIWARE platform logo]
```

Please note that `marginfigurenote` is a role I process later in html and docbook->latex backends  and probably should not be important for asciidoctor-pdf.

**Comment by mojavelinux** [comment]
The problem is that you are using inline images, but what you intend to use are block images. To make a block image, you need to use two colons after the word "image".

The inline image is not automatically sized within the bounds like a block image. But it also doesn't support any of the other features you are trying to use like a title and a class.

**Comment by mojavelinux** [comment]
Generally speaking, you rarely use inline images. They are only used if you want to put a icon somewhere in the line of text.

**Comment by shahryareiv** [comment]
Actually the reason for using inline image was that these images reside in the sidebar and they are not supposed to be numbered as they are not in the main fellow of figures. I guess I should open a new issue on disabling figure numbers on individual figures?
![test](https://cloud.githubusercontent.com/assets/3511038/19742946/85384336-9bc7-11e6-9fc6-5dd2370bb14c.png)

**Comment by mojavelinux** [comment]
That's already possible. You just need to set the caption to blank.

```
[.marginfigurenote,caption=]
.FIWARE platform logo.
image::fig_fiware_logo.png[FIWARE platform logo]
```

That gets rid of the caption label (e.g., Figure 2). If you want to get rid of the caption all together, then don't specify a title.

```
[.marginfigurenote]
image::fig_fiware_logo.png[FIWARE platform logo]
```

**Comment by shahryareiv** [comment]
Thanks!

**Comment by mojavelinux** [comment]
Sizing for inline images is now possible. See #620.

**Comment by shahryareiv** [comment]
Nice!
