### ISSUE TITLE
Part should start on the "right" page

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#658]
The expectation for parts (=Header) is that they start on the odd page.

Example:
````
= Part 1
blabla
= Part 2
blabla
````
Currently we have page 1 with Part1 and page 2 with Part 2. This is not how a book is organized. Part 2 should be one page 3 and page 2 should be empty, similar to how DocBook XLST does it.

**Comment by vogella** [comment]
@fap- something for you?

**Comment by mojavelinux** [comment]
This is already possible. You just need to set the attribute `media=prepress`. Then, all the traditional printing rules get applied. You can set the attribute either in the document header or via the API / CLI.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#publishing-mode for details. If there is information you think is missing, please let us know.

**Comment by jnerlich** [comment]
Thanks for the info. It works perfectly. 
I just have one more question. How do I mark Parts and Chapters as nonfacing ones?

**Comment by mojavelinux** [comment]
Just add the following line above the title.

[%nonfacing]

That adds an option to the section node that tells Asciidoctor PDF to skip
this behavior.

**Comment by vogella** [comment]
Thanks @mojavelinux 

Sounds that this is one of the "book style was not considered during the initial design of the pdf generator" issues. I think for book style you want only the = Header 1 on a right hand side page. 

What do you think?

**Comment by mojavelinux** [comment]
@vogella I'm not sure what you mean. It's now implemented in the same way as other typesetting tools. You have facing pages by default when media=prepress and a way to disable that behavior for select parts and chapters.

**Comment by vogella** [comment]
@mojavelinux I compared with my old DocBook output and learned ;-) that DocBook behaves exactly like this. Thanks in this case, this is than fixed. 

@jnerlich or I will send you a PR for adding the explicit mentioning of [%nonfacing] to 
 https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#publishing-mode
As far as we can see, it is not yet included there.

**Comment by mojavelinux** [comment]
Yes! That would be fantastic!

**Comment by jnerlich** [comment]
https://github.com/asciidoctor/asciidoctor-pdf/pull/660

Let me know if this is OK for you.

**Comment by mojavelinux** [comment]
That's great.

**Comment by mojavelinux** [comment]
Can this issue be closed?

**Comment by vogella** [comment]
Yes. Sorry for leaving it open.
