### ISSUE TITLE
Customizable title page

### ISSUE THREAD

**Issue by ruabmbua** [asciidoctor/asciidoctor-pdf#66]
It would be nice, if it is possible, to define your own content for the title page. I really need this, because I have to put a table on the cover page of my document with some meta information in it. I think it is already possible, by using ruby code, but I am not so good with that language, and this feature should really be customizable with the default asciidoctor-pdf.

**Comment by plaindocs** [comment]
+1

I'd say a fairly common usage would to be to include an image below the title, as well as a logo above it.

**Comment by leif81** [comment]
> I'd say a fairly common usage would to be to include an image below the title, as well as a logo above it.

There's ability to place a log above the title with the `titlepage-logo` attribute. See http://stackoverflow.com/a/26763956/52176 for more.

**Comment by plaindocs** [comment]
Thanks - that is what I meant when I said 'as well as a logo above it'.

**Comment by plaindocs** [comment]
From what I can read `:toc-placement: preamble` is *not* implemented in asciidoctor-pdf, right As that might be enough, as long as one can avoid the pagination between title page and preamble?

**Comment by plaindocs** [comment]
I added a second image below the title by duplicating the titlpage-logo loop in the ruby.

**Comment by mojavelinux** [comment]
Customizing the Ruby is actually the way I planned for advanced users to customize the layouts. Though, we need to work on making that easier and clearer to do (and have a tutorial for it).

Having said that, getting branding images on the title pages should be something we support out of the box given it's often a core requirement. There are two key things to decide before changing the code:

1. How to express the information in AsciiDoc (clearly document-level attributes seem to be the best fit)
2. Where to place them and what constraints they will have

It's very hard to support a widely-varied layout. However, if we can imagine the page as a fixed template, then it's fairly simple to place the information into the designed places. Then, for more advanced, custom layouts, you can tweak the Ruby (until other avenues emerge in the future).

**Comment by plaindocs** [comment]
FWIIW my changes for both footer and cover image are https://github.com/plaindocs/asciidoctor-pdf/tree/feature_footer

I think the approach of adding a doc level attribute, with well documented guidelines so we don't have to do too much error checkout would work.

If you're wanting advanced users to customize the ruby it would be nice to be able to override things with config rather than changing asciidoctor-pdf directly. ie, use this entire COVER from mycover.rb instead of the normal cover.rb (does not yet exist) in asciidoctor-pdf.

**Comment by mojavelinux** [comment]
> If you're wanting advanced users to customize the ruby it would be nice to be able to override things with config rather than changing asciidoctor-pdf directly. ie, use this entire COVER from mycover.rb instead of the normal cover.rb (does not yet exist) in asciidoctor-pdf.

That's precisely what I mean by making it easier. There is a new API in the latest Prawn that will allow us to partition the code this way so that it can be much more easily customize. Now, we just have to migrate the code to that model :)

**Comment by mojavelinux** [comment]
See #53

**Comment by mojavelinux** [comment]
I've made some strides allowing the look & feel of the title page to be customized. See #135.

That change doesn't yet allow you to customize the content. I'm thinking what we'll probably do is have a custom content area into which we will load docinfo content from an adoc file. Beyond that, I think you'll need to extend the converter and override the `layout_title_page` because extension is the spirit of the Asciidoctor ecosystem.

**Comment by mfitzp** [comment]
Not sure whether this fits here or in another feature request — but in asciidoctor-epub there is now support for a image title page using `:front-cover-image:` to set an image to use as the cover. 

It would be nice to able to do this in a pdf also — either replacing the current front (probably best?) or inserting in front of it.

**Comment by mojavelinux** [comment]
:+1:

**Comment by zgrzybek** [comment]
I would really love to use AsciiDoc in my project, but unfortunately the prerequisite is to have the ability to change the template of the title page - without this I will probably need to look for a different solution.

Do you know any timelines for this feature? 
Or is there any description of how to properly extend the converter and use it together with asciidoctor-maven-plugin and asciidoctorj-pdf?

**Comment by mosabua** [comment]
I would not look for another solution just because of the title page. You can already do a lot with the existing theming and parameters and if all else fails - create a custom PDF front page any way you want and stitch it to the output of asciidoc..

**Comment by veeg** [comment]
Extend the converter and output raw prawn instructions. Quite easy to do. Look at the create_title_page function for inspiration.

**Comment by zgrzybek** [comment]
@veeg that sounds like something I could be able to do.
Are you aware of any example of how to connect such an converter extension with asciidoctor-maven-plugin execution?

**Comment by AlexanderZobkov** [comment]
This might help you http://raibledesigns.com/rd/entry/re_customizing_an_asciidoctor_pdf

**Comment by veeg** [comment]
Memory serves me wrong. It was layout_title_page as pointed out by the above link.

**Comment by mojavelinux** [comment]
> if all else fails - create a custom PDF front page any way you want and stitch it to the output of asciidoc.

Exactly. In the end, you can always replace the title page that Asciidoctor PDF generates with your own using a PDF manipulation library. I highly recommend pyPdf (which is used by pdfshuffler).

Thinking a bit beyond that, I think the best way to handle a custom title page is to make the title page function an extension point. While it's possible to override the converter today, it would be nicer if it were possible to plug in code that isn't coupled to the converter. The extension would only permit you to modify a single page, but at least you would get 100% control over it using the Prawn API. I'll have to see if I can make that work.

**Comment by ilvetz** [comment]
+1
need to add a mark for classified documents

**Comment by mojavelinux** [comment]
I merged this issue with #1006.

**Comment by Alyaksej** [comment]
What about copyright-page (author-page)? Can I add "author-page" between title-page and TOC? Maybe some macro exist? For example {author-page} and {author-page!} (as like as {toc}-{toc!} )

**Comment by mojavelinux** [comment]
You can add as many pages as you like using AsciiDoc content. For example:

```
= Document Title
Author Name
:title-page:

{authors}

<<<

rest of content
```

However, these pages will only be styled as normal pages. If you want them styled in a special way, you will need to [extend the converter](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#extending-the-converter). This converter is designed for simple / typical typesetting out of the box. If you want advanced typesetting, you need to extend the converter.

**Comment by Alyaksej** [comment]
If I do that

```
= Document Title
Author Name
:title-page:

{authors}

<<<

remaining content
```
I have no TOC in my pdf document.
In my pdf document I need this order:
1. title page
2. copyright page
3. TOC
4. text
Is it possible?

**Comment by mojavelinux** [comment]
```
= Document Title
Author Name
:title-page:
:toc: macro

{authors} or whatever

<<<

toc::[]

== Section

remaining content
```

You'll probably want to adjust the start_at value for the page_numbering and running_content in the theme as well.

**Comment by DaLynxx** [comment]
+1

Below 'my story' for the +1

For me the possibility to affect the content of the title page (and the layout/format) is important.

I have a pipeline starting from XML content which is transformed via XSLT to an asciidoctor formatted report. The customer has requirements on the resulting media, so it need to end up as a a pdf with several requirements on format and content including the the front page.

I managed to work around most of my issues by allowing "font page generator" into the pipe just in front of asciidoctor-pdf. Currently it imports an .svg template in which markers are replaced with the necessary meta-data. The .svg is then imported as the background-image for the title page.

I still got one issue left which is dynamic content that I do not have access to when the front-page-generator is running. The total number of pages of the report needs to be listed on the front-page.

A multi-pass solution is possible and probably where I will end up for now, i.e. run asciidoctor-pdf extract the number of resulting pages, update the .svg, re-run asciidoctor-pdf.
Actually it would be a nice feature if the verbose mode of asciidoctor-pdf would report on the number of pages generated.

Anyway, I vote +1 for any increased possibilities in manipulating affecting the content and format of the title page.
Regardless, tnx for a nice toolset.

**Comment by mojavelinux** [comment]
We have decided to focus on a programmatic solution to this need. The reasoning behind that choice is that there are an endless number of ways a title page could be (or must be) customized. Anything we try to come up with using a universal configuration-based approach is always going to fall short of expectations for some. But that doesn't necessarily mean you have to write code to custom it. Of course, we will encourage someone to do so. But that someone could create an add-on that reads configuration in a certain way so you can get back to using a configuration or template-based approach. What this converter is providing is the foundation to do that.

With that said, I think you'll find the code approach be reasonably straightforward. I have included an example in the documentation (https://github.com/asciidoctor/asciidoctor-pdf/pull/2184/files). We can build on that example as questions and needs arise. I've put a simple example here for reference.

*pdf-converter-custom-title-page.rb*
```rb
class PDFConverterCustomTitlePage < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def ink_title_page doc
    move_cursor_to page_height * 0.75
    theme_font :title_page do
      doctitle = doc.doctitle partition: true
      theme_font :title_page_title do
        ink_prose doctitle.main, align: :center, margin: 0
      end
      if doctitle.subtitle?
        theme_font :title_page_subtitle do
          ink_prose doctitle.subtitle, align: :center, margin: 0
        end
      end
    end
  end
end
```

Here's how you use it:

```
asciidoctor-pdf -r ./pdf-converter-custom-title-page.rb doc.adoc
```

**Comment by mojavelinux** [comment]
> What about copyright-page (or author-page)?

I have added an example to the docs that shows how to insert auxiliary pages without needing to add content to the source document.
