### ISSUE TITLE
pdfwidth problem?

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor-pdf#668]
I can't get pdfwidth to work for block images.

Converting this:
````
= Image sizing in asciidoctor-pdf

image::fox.jpg[title="pdfwidth, not-sized"]

image::fox.jpg[title="pdfwidth, twoinches", pdfwidth='2in']

image::fox.jpg[title="pdfwidth, half-size", pdfwidth='20%']

image::fox.jpg[title="pdfwidth, full-page", pdfwidth='100vw']

image::fox.jpg[title="pdfwidth, half-page", pdfwidth='50vw']

image::fox.jpg[title="pdfwidth, 20 mm", pdfwidth='20mm']

image::fox.jpg[title="pdfwidth, 72 points", pdfwidth='72pt']

image::fox.jpg[title="pdfwidth, 72 pixels", pdfwidth='72px']

image::fox.jpg[title="width, no units (px)", width='72']

image::fox.jpg[title="width, 100%", width='100%']

image::fox.jpg[title="scaledwidth, points", scaledwidth='20%']

````

using 

Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

installed from asciidoctor-pdf 1.5.0.alpha.6

pdfwidth appears to have no effect, but width and scaledwidth do. 

See https://github.com/rockyallen/asciidoctoressays/blob/master/imagesizing/pdf-demo.pdf

**Comment by mojavelinux** [comment]
> installed from asciidoctor-pdf 1.5.0.alpha.6

There's your problem. We're on alpha.13 now :)

Btw, you can put the title above the block image to make it look a bit cleaner:

```
.pdfwidth, twoinches
image::fox.jpg[pdfwidth=2in]
```

**Comment by rockyallen** [comment]
Doh...
