### ISSUE TITLE
Installing asciidoctor-pdf does not install bin/optimize-pdf

### ISSUE THREAD

**Issue by bulletmark** [asciidoctor/asciidoctor-pdf#670]
I just followed the instructions at http://asciidoctor.org/docs/convert-asciidoc-to-pdf/ exactly to install `asciidoctor-pdf` and it installed fine and I can run it. However the words on that page say `bin/optimize-pdf` should be installed but I don't have it at `~/.gem/ruby/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/bin/` or anywhere else.

I have previously installed `asciidoctor-pdf` and that time it was correctly installed at `~/.gem/ruby/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/bin/optimize-pdf`.

**Comment by mojavelinux** [comment]
The optimize-pdf script has been pulled until #535 is solved. It's not correct to bundle a Bash script in a Ruby gem. The goal of that issue is to rewrite it in Ruby. I'll be working on it soon. Marking this as a duplicate / dependency.

**Comment by bulletmark** [comment]
Perhaps those instructions that I linked to should add at least a temporary note about this?

**Comment by mojavelinux** [comment]
Those instructions actually come from the README, so that's where the update needs to occur first. (I realize the website is a little disorganized right now...we're working getting everything synchronized).

However, I plan to have this implemented very soon, so it might be faster just to fix it for alpha.14. If it takes longer, then I'll update the docs.

**Comment by nebrass** [comment]
Where is the optimize-pdf? Until now I am facing the same issue 😭

**Comment by mojavelinux** [comment]
You need to use the file from the repository. It's really just a wrapper around `gs`.

You may also be interested in the discussion in #872.

**Comment by mojavelinux** [comment]
Closing as a duplicate. See #535.
