### ISSUE TITLE
Some SVG images aren't render correctly

### ISSUE THREAD

**Issue by Nowass** [asciidoctor/asciidoctor-pdf#676]
Hi,

I use MS Visio for SVG images creation, but these images are not correctly rendered  in generated PDF output. The problem is mainly with the multi-line text where all the lines are generated in one line. Other problems are the arrows at the end of the lines.

If the same (very similar) image is created for example in LilbreOffice Draw, the output is ok. I've tried a lot of other tools for SVG images (Google draw, Smart Draw, Inkscape, Pencil, ...) and so far it seems that the problem is only with the Visio images.

See attachment with PDF output example.

Do you have any idea what can be wrong?

Thank you,
Petr

[svgTest.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/623799/svgTest.pdf)

**Comment by mojavelinux** [comment]
SVG interpretation/rendering issues should be directed to https://github.com/mogest/prawn-svg.

It's important to understand the SVG has different profiles. Prawn SVG only supports the desktop profile, which disallows embedded HTML fragments. That's usually the culprit in exports like these. You probably need to do some cleaning/postprocessing of the SVG to get it ready for use in PDF.

**Comment by Nowass** [comment]
Many thanks for your fast reply! I'll ask for this topic in prawn-svg.

Thanks & have a nice day.

**_Petr_**

**Comment by mojavelinux** [comment]
:+1:
