### ISSUE TITLE
border=0 does not eliminate border in [quote] blocks

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/asciidoctor-pdf#680]
Setting the border width to 0 or even -1 still gets a 1 pixel left border on block quotes

    blockquote:
        border_width: -1
        padding: [0, 0, 0, 0]
        border_color: 000000

sample:

![blockquote w -1 border](https://cloud.githubusercontent.com/assets/234664/20862676/0d061974-b977-11e6-83e4-328ce0bd4f6b.png)

My work around is to set the border to -1 and color to match the page so it is invisible.

**Comment by mojavelinux** [comment]
This was fixed when #270 was resolved. Can you confirm you are using at least alpha.13?

**Comment by mojavelinux** [comment]
Correction. This was resolved after alpha.13. The fix will be available in alpha.14.

**Comment by mojavelinux** [comment]
Resolved by 6b3852672d94b11d5290585675eacfe9a4c6465f.
