### ISSUE TITLE
Implement line highlighting for Rouge

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#681]
Asciidoctor supports line highlighting in source blocks. Now that we figured out how to add background colors in source listings, we should support this when highlighting with Rouge.

Example:

```
[source,groovy,linenums,highlight="7-9"]
----
package com.example
 
import static ratpack.groovy.Groovy.ratpack
 
ratpack {
    handlers {
        get {
            render "Hello, World!"
        }
    }
}
----
```

**Comment by mojavelinux** [comment]
It should be possible to control what type of highlighting is applied using the Rouge theme. For example, the author may want to make the line bold instead of adding a background color.

**Comment by r0ckarong** [comment]
Any progress on this? There is currently no available solution to use both linenums and highlighting with either coderay or pygments in PDF.

**Comment by equamo** [comment]
I'm also interested in highlight code-snippets with rouge and mark some parts of the snippets on my own (for example with the '#' attribute). But I could not figure out if there is any innovation or progress.

**Comment by mojavelinux** [comment]
It turns out we can enable this with Pygments since we now support background color on spans. I'll do that first.

**Comment by mojavelinux** [comment]
I think I've got this figured out for Rouge too.

**Comment by mojavelinux** [comment]
Note that the line numbers in the highlight attribute should take into account the start value on the block. So if the start value is 5, then highlight=5 would highlight the first line. We'll need a similar change in core.

**Comment by dvf** [comment]
Can we keep this open until a merge?

**Comment by mojavelinux** [comment]
> I'm also interested in highlight code-snippets with rouge and mark some parts of the snippets on my own (for example with the '#' attribute). But I could not figure out if there is any innovation or progress.

That's a very different issue. I've explained in other issues that because of the way the syntax highlighters works, it's not trivial or even possible. You can highlight individual words without syntax highlighting (such as on a listing block), but it won't work once the syntax highlighter gets involved because it gets confused.

**Comment by mojavelinux** [comment]
> Can we keep this open until a merge?

It is merged. See 7a87eb026a819531891b7d7b930dc8cd69f80d8a.

**Comment by dvf** [comment]
That’s fantastic news @mojavelinux thanks for all your hard work 🙏

**Comment by dvf** [comment]
Quick question, I checked the docs and it's not clear what token I need to add a style for. Am I missing something?

**Comment by mojavelinux** [comment]
@dvf You're welcome.

To highlight specific lines (in yellow), you specify the line numbers of those lines using the `highlight` attribute on the block.

```
:source-highlighter: rouge

[source,groovy,linenums,highlight=7-9]
----
package com.example

import static ratpack.groovy.Groovy.ratpack

ratpack {
  handlers {
    get {
      render "Hello, World!"
    }
  }
}
----
```

Here's how it will look:

![highlight-lines](https://user-images.githubusercontent.com/79351/71540959-f7174600-290e-11ea-8e25-3e1112866ceb.png)

**Comment by dvf** [comment]
I’ve been battling to get this to work, I’m using rouge and outputting a regular PDF

**Comment by mojavelinux** [comment]
Are you using Asciidoctor PDF from the master branch?

**Comment by dvf** [comment]
Ah, finally got it working! I come from Pythonland, so all I had to do was figure out how to build this package from source as the changes aren't in rubygems.com yet.

For those interested:

1. Clone this repo
2. Build the gem
   ```
   bundle exec rake
   ```
   This outputs something like:
   ```
   asciidoctor-pdf 1.5.0.rc.1.dev built to pkg/asciidoctor-pdf-1.5.0.rc.1.dev.gem.
   ```
3. Install the outputted gem:
   ```
   gem install pkg/asciidoctor-pdf-1.5.0.rc.1.dev.gem
   ```

PS. Still way easier than getting LaTeX to highlight code snippets.

**Comment by mojavelinux** [comment]
Most excellent!

Btw, those instructions can be found here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/CONTRIBUTING-CODE.adoc#development (though a little more detailed) ;)
