### ISSUE TITLE
Acrobat: footer disappears on pages with only (block) image

### ISSUE THREAD

**Issue by fap-** [asciidoctor/asciidoctor-pdf#688]
I've added an example on an extra branch on one of our repos: https://github.com/vogellacompany/com.vogella.tutorials.nattable/commit/c52ee8a45b6663a15e4d195fc380ddadde76139d
The example needs to get called with our theme: `[...]/asciidoctor-pdf/bin/asciidoctor-pdf -d book -a pdf-style=[...]/com.vogella.tutorials.nattable/themes/basic-theme.yml 001_book_print_test.adoc`
I've also attached already converted pdfs that show the bug. The last page of the example pdf is affected.

If the generated pdf contains a page with only an image, without text, the footer doesn't get printed and Acrobat complains about an error.
We have seen this error in Acrobat 8, Acrobat 9 and Acrobat Pro DC.
When the pdf is opened with other readers the footer gets shown without an error.
This is a problem for us because the print shops tend to use Acrobat products only.

![test_with_text](https://cloud.githubusercontent.com/assets/1610853/21007279/8577f2c4-bd3c-11e6-9a52-8b08b93d7c8d.jpg)
![test_without_text](https://cloud.githubusercontent.com/assets/1610853/21007745/857c3f62-bd3e-11e6-92cc-010def20bb1e.jpg)

[book_nattable_with_text.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/639593/book_nattable_with_text.pdf)
[book_nattable_without_text.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/639594/book_nattable_without_text.pdf)

CC @jnerlich, thank you for initial report

**Comment by vogella** [comment]
@fap- so far https://github.com/vogellacompany/com.vogella.tutorials.nattable is a private repo. I talk to Dirk, if we can make it publish. I see no reason against it, but Dirk wrote most of the content, so I need to check with him.

**Comment by fap-** [comment]
Ah, theoretically an asciidoc file with only one page and an block image should do the trick too, but I can't test it right now, need to get an Acrobat version running first.

**Comment by mojavelinux** [comment]
Variations of this issue have appeared before. The problem seems to be that a page requires certain PDF objects to be present or defined. Prawn doesn't seem to verify that the PDF structure is correct, so we end up with cases when the objects aren't constructed properly. When that happens, we see missing content in Acrobat. If I understood what to look for, I would have a better idea of how to solve this problem globally. So far, I've only been able to come up with workarounds or hacks.

So the key here is to open up the PDF source and try to study what is different about the page that has the error...or what seems missing. It often has to do with pages that have no text. Hopefully, we can finally get to the bottom of this.

**Comment by mojavelinux** [comment]
I'll share that one of the workarounds I've used in the past is this:

```
update_colors
```

I call that before starting a new page in this instance.

That seems to add some sort of declaration to the PDF page object that makes the reader happy.

**Comment by fap-** [comment]
I'm not sure how you did this.
Which function would we need to overwrite? Do you put it into the `on_page_create` block?

**Comment by mojavelinux** [comment]
When I say "open up the PDF source" I mean open up the PDF in a text editor. It's just plain text (with some encoded parts).

Essential what is missing from the page stream is something like:

```
/DeviceRGB cs
0.200 0.200 0.200 scn
/DeviceRGB CS
0.200 0.200 0.200 SCN
```

This declaration has to exist if there is any text on the page. It seems that Prawn does not check to make sure this is in the stream before creating a stamp. So we have to make sure each page has it ourselves. We could add call `update_colors` in the `convert_image` method, and that will handle this case. But there are tons of permutations when a page has no text in the content part. I really don't know a solution that is going to work universally yet. We'll just have to keep on trying.

**Comment by mojavelinux** [comment]
Maybe we can get the running content to add this to the page stream, but I don't know if that will actually work.

**Comment by mojavelinux** [comment]
Note that Ghostscript will detect this error too, so the PDF is technically invalid if text is written to a page without a color space being set at the start of the stream.

**Comment by mojavelinux** [comment]
As it turns out, I had a patch for this in the converter already, but only for certain scenarios. I missed the scenario of a page break immediately after an image occurring at the top of the page.

**Comment by mojavelinux** [comment]
I think I figured out the right fix to handle all scenarios when an image appears on a page by itself. This applies to both raster and vector images.

I also checked inline images that are on a page by themselves. It appears that in those cases, Prawn sets the color space properly, so we're covered there too.

**Comment by jnerlich** [comment]
Thanks @mojavelinux, issue is solved with this solution.

**Comment by mojavelinux** [comment]
Thanks for testing!
