### ISSUE TITLE
`+__str__+` passes the +s through to the generated PDF

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/asciidoctor-pdf#699]
Moved from: https://github.com/asciidoctor/atom-asciidoc-preview/issues/207#issuecomment-266834599 

With Asciidoctor PDF 1.5.0.alpha.13 using Asciidoctor 1.5.5 

    `+__str__+`

the +s unexpectedly pass through to the generated PDF.  Here's a snag from the PDF:

![hash and eq](https://cloud.githubusercontent.com/assets/234664/21166032/9f70b03c-c168-11e6-9efa-a81c907d627d.png)

I work around it by removing the +s from my markup and ignoring the rendering difference in Atom but thought you might like to know.

**Comment by mojavelinux** [comment]
Can you provide the text for the whole paragraph? Context is very important here and may uncover the real reason behind what you are observing.

**Comment by mojavelinux** [comment]
Are you sure you don't have compat-mode on or use the legacy document title syntax? That sounds like what is going on here.

See http://asciidoctor.org/docs/migration/#compat-mode

**Comment by handcraftsman** [comment]
Legacy document title syntax was the problem.

```
Test document
=============

= This is a test

We used both `+__hash__+` and `__eq__`.
```

Thank you.

**Comment by mojavelinux** [comment]
:+1:
