### ISSUE TITLE
Support text-transform style in running content

### ISSUE THREAD

**Issue by mdreier** [asciidoctor/asciidoctor-pdf#702]
A nice feature would be the support of `text_transform` for page headers and footers, so that the header can be converted into upper or lower case.

My requirement is to have the document title in the page header, and to have the page header in all upper case. A workaround would be to have an uppercase macro, but I was not able to find something like that,

**Comment by mojavelinux** [comment]
You are correct. Text transform is currently not supported in running content. I can add that.

> A workaround would be to have an uppercase macro, but I was not able to find something like that,

You could create your own uppercase inline macro. The text in the running header/footer is run through normal substitutions.

```ruby
require 'asciidoctor/extensions'
  
Asciidoctor::Extensions.register do
  inline_macro :upper do
    using_format :short
    process do |parent, target|
      target.upcase
    end
  end
end
```

Then you can write:

```
upper:[{document-title}]
```
