### ISSUE TITLE
Image height improperly expands to the whole page height when the image is to start a new page

### ISSUE THREAD

**Issue by zhuermao** [asciidoctor/asciidoctor-pdf#708]
Image height improperly expands to the whole page height when the image is to start a new page.

`image-correct.adoc` gets a correct result: 

    = Image Test

    == Test

    image::wolpertinger.jpg[]

    THE END.

![image-correct](https://cloud.githubusercontent.com/assets/3499765/21306571/9d07a636-c60c-11e6-8459-974f195002b9.png)

But `image-wrong.adoc` gets the wrong result:

    = Image Test

    == Test

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

    image::wolpertinger.jpg[]

    THE END.

![image-wrong1](https://cloud.githubusercontent.com/assets/3499765/21306613/e205e630-c60c-11e6-92ca-753c0d106648.png)

![image-wrong2](https://cloud.githubusercontent.com/assets/3499765/21306633/fc09b3b8-c60c-11e6-883f-29a3a6900ff7.png)

![image-wrong3](https://cloud.githubusercontent.com/assets/3499765/21306677/3292d7ca-c60d-11e6-8b63-cbd4e7a30ca6.png)

**Comment by mojavelinux** [comment]
Have you tried with the latest master? I've rewritten a lot of the image
code since the last release. (A new release is coming any day now).

**Comment by zhuermao** [comment]
Actually, I believe the issue is caused by the latest master which I pulled yesterday.
I have tried to roll back to `asciidoctor-pdf-1.5.0.alpha.11`.  And that version results the correct image size.

**Comment by zhuermao** [comment]
Great.  It works now.
Thank you.

**Comment by mojavelinux** [comment]
Great! Thanks for testing!
