### ISSUE TITLE
header/footer related attributes `section-title` `section-or-chapter-title` incorrectly use the header/footer section title of the last page

### ISSUE THREAD

**Issue by zhuermao** [asciidoctor/asciidoctor-pdf#709]
header/footer related attributes `section-title` `section-or-chapter-title` should use the title of the last section in the previous pages.

IMHO, the header/footer related attributes `section-title` `section-or-chapter-title` should:
1. If there are new sections in the page, use the title of the first section in the page.
2. If there are **NO** new sections in the page, use **the title of the last section in the previous pages**.

But by far it does not obey rule 2.
When there are **NO** new sections in the page, it **incorrectly** uses **the header/footer section title of the last page**.
I think it should be a bug.

My custom theme settings is `header_recto_content_center: '{section-title}'`
And I got this:

![section-test1](https://cloud.githubusercontent.com/assets/3499765/21307684/98b0b4b0-c611-11e6-954e-9628b575dac8.png)

![section-test2](https://cloud.githubusercontent.com/assets/3499765/21307692/a3d2b65e-c611-11e6-92f1-8f98404335d7.png)

![section-test3](https://cloud.githubusercontent.com/assets/3499765/21307700/ac44d3e4-c611-11e6-8fd2-4e4bc7e0802e.png)

I think the header section title of Page 2 should be `8. Section 8`.

**Comment by mojavelinux** [comment]
I agree, this appears to be a bug. I'll try to figure out what's going on.

**Comment by mojavelinux** [comment]
I have proposed a solution which handles this scenario.

In general, however, the code that does the page number to current section mapping really needs to be reworked to use a proper model. The hacky approach right now limits our options, isn't super efficient, and makes a lot of assumptions.

**Comment by zhuermao** [comment]
Perfect.

**Comment by mojavelinux** [comment]
:+1:
