### ISSUE TITLE
Footer font color

### ISSUE THREAD

**Issue by nvdl** [asciidoctor/asciidoctor-pdf#713]
Footer font color does not work for `verso_content`. It is always black.

footer:
  font_family: FreeSans
  font_color: #ffffff
  background_color: #00afaa
  border_color: #000000
  border_width: 1
  height: 0.4in
  line_height: 1
  recto_content:
    right: '*{section-or-chapter-title}* | {page-number} / {page-count}'
  verso_content:
    right: '*{section-or-chapter-title}* | {page-number} / {page-count}'

Tried this but of no avail:

footer:
  font_family: FreeSans
  font_color: #ffffff
  background_color: #00afaa
  border_color: #000000
  border_width: 1
  height: 0.4in
  line_height: 1
  recto_content:
    font_color: #ffffff
    right: '*{section-or-chapter-title}* | {page-number} / {page-count}'
  verso_content:
    font_color: #ffffff
    right: '*{section-or-chapter-title}* | {page-number} / {page-count}'

It happens when logo image size is beyond a specific size.

title_page:
  logo_image: image:/x/test.png[width=640,align=center]
  background_color: #ffffff
  align: center

An extra blank page is also added at the end of the document when that happens.

**Comment by mojavelinux** [comment]
Can you confirm which version of AsciidoctorJ you are using?

**Comment by mojavelinux** [comment]
Styling of text differently on the verso and recto faces is only possible using the new key structure, which is supported since alpha.13.

```yaml
footer:
  verso:
    right:
      font_color: #6CC644
```

**Comment by nvdl** [comment]
I updated now to see if it works.

Asciidoctor PDF 1.5.0.alpha.13 using Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

I had resized the image with `[width=680,align=center]` to fit into the title page without realizing that it was the issue that caused a blank page at the end.

`[width=635,align=center]` fixes the issue and the footer text color is correct for even and odd pages.

**Comment by mojavelinux** [comment]
Yes, the size of the image on the title page is a known issue. It doesn't yet have automatic fitting like images on content pages. I'll add that to the list.

**Comment by mojavelinux** [comment]
Actually, would you like to file an issue to automatically force the image on the title page to fit if it's too large?

**Comment by nvdl** [comment]
OK, the issue is not with even and odd pages.

If the logo image size is `[width=680,align=center]`, it goes the end of the document and footer text is in black (default) at that page.

If `[width=635,align=center]` is used for the logo image, it goes back to its normal place.

Image size: 1470x2079

**Comment by mojavelinux** [comment]
:+1:
