### ISSUE TITLE
Title Logo Image Size

### ISSUE THREAD

**Issue by nvdl** [asciidoctor/asciidoctor-pdf#714]
The styling allows "bigger" image sizes for the logo in which case the logo image ends up at the end of the document. The footer text color is also affected at that last page.

For example:

If the logo image size is set as `[width=680,align=center]`, it goes the end of the document and footer text is in black (default) at that page.

If `[width=635,align=center]` is used for the logo image, it goes back to its normal place.

Example image size: 1470x2079

It looks like, resizing is done but the styling allows bigger sizes without clamping those.

Interestingly, if `[width=640,align=center]` is used, a blank page appears at the end of the document while the logo image stays at its position. Footer text color is affected though; black (default).

**Comment by mojavelinux** [comment]
Since alpha.14 is heavily focused on image sizing improvements, I'll try to get this sorted out before that release.

**Comment by nvdl** [comment]
Let me know if you need help. Looks like it is Ruby based.
Any Python backend, frontend?

I am using my custom Python parser to post process the text file to add more functions.

**Comment by mojavelinux** [comment]
In this case, I've rewritten so much of the image code that it's fresh in my mind. It's probably just applying the logic similar to https://github.com/asciidoctor/asciidoctor-pdf/blob/60ac62d998d2f385bd0569a4200b787f8a66bd83/lib/asciidoctor-pdf/converter.rb#L1036-L1045. (I probably need to move that into a function, but that becomes clear in time)

**Comment by nvdl** [comment]
Seems plausible.

On a side track, I could not find any function regarding adding custom image to every PDF page.
For example, "Confidential".

I am relying on `pdftk` to add another PDF as the background.

**Comment by mojavelinux** [comment]
This is possible. The image is added at the bottom of the stack.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/60ac62d998d2f385bd0569a4200b787f8a66bd83/lib/asciidoctor-pdf/converter.rb#L1036-L1045

The primary use case is "draft" or "confidential" watermarks.

**Comment by nvdl** [comment]
Any pointer to that?

I get this hit:
https://groups.google.com/forum/#!topic/asciidoc/9rqO_YYkVrM

**Comment by mojavelinux** [comment]
That reference isn't relevant in this context. We aren't using the DocBook toolchain here.

Have you tried the theme setting I pointed to?

```
page:
  background_image: image:path/to/image/confidential-bg.jpg[]
```

I had pasted the wrong link. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-page.

**Comment by nvdl** [comment]
Yes, found it out.
It works. Picture blending does not work though.

If there are many pictures on a page, the watermark is invisible.
Not so important in my case though.

**Comment by mojavelinux** [comment]
Yep, that's unfortunately is either a limitation of PDF or of Prawn. If transparency in the image is respected (which I know was being worked on in Prawn at some point), then it's just a matter of being able to mark the background image to be at the top of the stack instead of the bottom. If image transparency is respected, then we should add that feature in Asciidoctor PDF. But first we have to see if image transparency is possible with Prawn (or PDF).

**Comment by mojavelinux** [comment]
I forgot that the page background can also be set in the AsciiDoc document header:

```
:page-background-image: image:watermark.png[]
```

It does appear that we need another setting for watermark-image, which would place the image on top of the text instead of under it. As long as the watermark has translucent text, the text under it will still be visible. Please open a separate issue so we can discuss it.

**Comment by mojavelinux** [comment]
It turned out that this wasn't all that difficult the fix. The logic was already there, we just needed to activate it.

**Comment by mojavelinux** [comment]
>  the logo image ends up at the end of the document

This was happening because the logic to advance the page in order to fit the image on the page was getting called. Unlike with images in content, we never want to advance away from the title page in this case.
