### ISSUE TITLE
Watermark Image Inclusion Through the Document Directive

### ISSUE THREAD

**Issue by nvdl** [asciidoctor/asciidoctor-pdf#717]
Directive inside the document does not work as expected.

This does not work.
`:page-background-image:image:confidential.png[]`

`asciidoctor-pdf 1.txt`
`asciidoctor: WARNING: allow-uri-read is not enabled; cannot embed remote image: image:confidential.png`

With `allow-uri-read`:

`asciidoctor-pdf -a allow-uri-read 1.txt`
`asciidoctor: WARNING: image to embed not found or not readable: image:confidential.png`

Am I missing the syntax?

Moreover, the following causes a silent ignore of the image directive.
`:page-background-image: image:confidential.png[]` (using space after :page-background-image:)

Need to clear spaces where not needed in directives?

**Comment by mojavelinux** [comment]
The space is required, so I'd ignore the first scenario.

When using the image macro, the target is resolved relative to imagesdir.
But since you don't get a warning, I think it does find the image.

Probably the image is not fitting in the bounds. Verify the aspect ratio
matches the aspect ratio of the page (A4 by default).

**Comment by nvdl** [comment]
Resized the image to 210x297 pixels.
Tried by converting to ".jpg".

Same issue with:

`:page-background-image: image:confidential.png[]`

Document:

= Title

:pdf-page-size: A4
:experimental:
:numbered:
:page-background-image: image:confidential.jpg[]
:title-page-background-image: image:confidential.jpg[]
:front-cover-image: image:confidential.jpg[]

== Section1

section 1

**Comment by mojavelinux** [comment]
The problem is the blank line after the document title. That ends the document header, so all the document-wide attributes after the blank line are effectively ignored. See http://asciidoctor.org/docs/user-manual/#doc-header

**Comment by nvdl** [comment]
That was it.

////
= Title
:pdf-page-size: A4
:numbered:
:page-background-image: image:confidential.png[]

== Section1

section 1
////

Why not strip away blank lines automatically or do they serve other purpose in header context?

**Comment by mojavelinux** [comment]
Blank lines are how we know when the header ends. Attribute entries outside
the header have a different meaning / purpose.
