### ISSUE TITLE
How to have a macro to execute only when generating pdf?

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-pdf#720]
I have an image that I'd like to execute only for PDF output. Is there a kind of attribute I can pass to image:: so that the image is processed for PDF generation, and ignored when generating epubs etc.?

**Comment by mojavelinux** [comment]
Absolutely. You are looking for the preprocessor conditional directive. http://asciidoctor.org/docs/user-manual/#conditional-preprocessor-directives

You can reference any document-scoped attribute. The attribute you're interested in here is `backend-pdf`.

```
ifdef::backend-pdf[]
only do this for PDF
endif::[]
```

**Comment by seinecle** [comment]
Thanks!

**Comment by mojavelinux** [comment]
:+1:
