### ISSUE TITLE
image from hyperlink ignored in pdf

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-pdf#721]
`image::https://docs.google.com/drawings/d/1j00khDpGCzHQNvtJMwr6W52yhgslnLWvQgXwuNUAtZo/pub?w=450["A diagram showing the authoring steps to create open, web friendly docs"]`

The html generated from this document shows the pic (which is a png format).

pdf and epub don't show it, probably because this is a link which is not directly to a .png binary, but something else.

Can steps be added to the pdf / epub processor for the image to be displayed?

**Comment by mojavelinux** [comment]
To allow the processor to read from a URI, you must enable the `allow-uri-read` attribute from the CLI or API. This is a security and performance feature.

See http://asciidoctor.org/docs/user-manual/#include-uri

(That section doesn't mention images in particular, though it probably should).

If for some reason the format cannot be detected, you can specify it explicitly:

```
image::<uri>[format=png]
```

**Comment by mojavelinux** [comment]
(Since png is assumed, the format is not required in this case. It would be required if it were an SVG).

**Comment by mojavelinux** [comment]
Can you verify the suggested fix worked?

**Comment by mojavelinux** [comment]
There's now a test in the test suite for this scenario.
