### ISSUE TITLE
Problem with attribute `a` in column of table

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor-pdf#723]
hi,

The attribute  `a` (table) doesn't work with asciidoctor-pdf, 

This code is rendered correctly in html (asciidoctor) but not in pdf
```
[width="100%", options="header"]
|=======================================================================
| header column

a|Mozilla Firefox is an open-source web browser.
It's designed for:

* standards compliance,
* performance and
* portability.
|=======================================================================

```

Jérôme

**Comment by mojavelinux** [comment]
Please be patient for the upcoming release of Asciidoctor PDF, which resolves this issue. You can also try to use the code from master if you want to test it.

**Comment by JBR69** [comment]
good, then i'm waiting ;-)
