### ISSUE TITLE
Disable printing of appendix content in table of contents

### ISSUE THREAD

**Issue by cascer1** [asciidoctor/asciidoctor-pdf#734]
I'm writing a report that has a few appendices. Some of these appendices are complete reports with their own table of contents.

I would like to be able to disable the printing of individual appendix items in the main table of contents.

So, instead of this:

* Heading 1
  * Heading 1.1
  * Heading 1.2
* Heading 2
* Appendix A: Lorem Ipsum
  * Heading 1
    * Heading 1.1
  * Heading 2
* Appendix B: Something
* Appendix C: Something else

I would like to get this:

* Heading 1
  * Heading 1.1
  * Heading 1.2
* Heading 2
* Appendix A: Lorem Ipsum
* Appendix B: Something
* Appendix C: Something else

**Comment by mojavelinux** [comment]
This seems reasonable, but I'm not going to be able to add the feature until we work out how to express the configuration.

One way would be to have an option on the section title to hide it from the table of contents:

```
[appendix]
== Appendix A: Lorem Ipsum

[opts=discrete]
=== Heading 1

content
```

(I'm open to other option names, like `unlisted`).

Another would be to try to express it in the `toclevels` somehow.

**Comment by mojavelinux** [comment]
Btw, another workaround is to define all headings in the appendix using the `discrete` (aka `float`) style. That alters the semantics of the document, but gives you what you need for display purposes.

**Comment by mojavelinux** [comment]
I suppose we could introduce `special-toclevels` to control the depth for special sections.

**Comment by mojavelinux** [comment]
I have an idea. What if we could set the `toclevels` attribute on the section as an override? It would override the global `toclevels`, but scope it that section and its descendans. For example:

```
= Document Title
:doctype: book
:toc:
:toclevels: 3

== Chapter A

=== Section A

=== Section B

[appendix,toclevels=1]
== Lorem Ipsum

=== Section A

==== More Detail

=== Section B
```

Then the toc will look like:

```
Chapter A
  Section A
  Section B
Appendix A: Lorem Ipsum
```

The benefit of this design is that it gives you fine-grained control and works for any section, not just special ones.

If you set the value of `toclevels` to less than the level of the section, then it hides the section itself from the table of contents.

**Comment by mojavelinux** [comment]
An open question is whether this would also apply to the document outline. That's more tricky, so we'll leave that for a separate issue.
