### ISSUE TITLE
Heading levels more than 3 are not being shown correctly when converting the asciidoc to pdf

### ISSUE THREAD

**Issue by sudhir-kumar2017** [asciidoctor/asciidoctor-pdf#736]
Heading levels more than 3 are not being shown correctly when converting the asciidoc to pdf.

```
sharing the snapshot of issue
====================
7.1. Functional Requirements
7.1.1. Conformance Class
Standard Modbus Supported Functions*
```

\* This heading should have been numbered as 7.1.1.1

Any help on the parameter which needs to be set in the theme file?

**Comment by mojavelinux** [comment]
This is controlled by the sectnumlevels attribute.

**Comment by barspi** [comment]
This is working for me, using `:sectnumlevels: 4`
What took me some time to find out is that, in order to the the headings in the toc as well, I should use the `:toclevels: 4` attribute :-)

**Comment by sudhir-kumar2017** [comment]
Thanks guys, it worked like a charm :)
