### ISSUE TITLE
Need a way to have indented content

### ISSUE THREAD

**Issue by barspi** [asciidoctor/asciidoctor-pdf#737]
I'm attaching an image to show what I want.
See how the paragraph is indented by a certain margin with respect to the headings.
(This PDF was generated by Apache FOP, from a DocBook file)

![screenshotproguide](https://cloud.githubusercontent.com/assets/1316018/22355204/17aa33fe-e408-11e6-8f38-93a0d0dc4cde.jpg)

**Comment by oddhack** [comment]
That would be awesome. The way I've been approximating this is by using the unlabelled :: list syntax ,which is an awful hack and not flexible.

**Comment by mojavelinux** [comment]
I've updated the title since this is actually a different thing from indented paragraphs. A paragraph indent is when the first line is intended from the subsequent lines...which is also a separate feature request.

What you're talking about here is being able to control the margins of the body text. This is certainly possible given that the section controls the rendering of its children and can offset the margins before proceeding.

**Comment by soiff** [comment]
@mojavelinux Hi, is there any plan to support indented first paragraph already?

**Comment by mojavelinux** [comment]
@cloorc indented first paragraph? Do you mean indenting the first line? Or do you mean indenting just the first paragraph in a section?

**Comment by mojavelinux** [comment]
How do you feel about the theme key `section_indent`?

```yml
section:
  indent: 1in
```

or

```yml
section:
  indent: [1in, 0]
```

**Comment by mojavelinux** [comment]
For the record, the DocBook toolchain uses the properties `body.start.indent` and `body.end.indent`. However, I don't think these names are very intuitive.

**Comment by mojavelinux** [comment]
Please review the proposed solution. See #1284.

**Comment by garyritchie** [comment]
Is it possible for blocks to "break out" of this section_indent? For example: wide tables, or images, even admonitions.

**Comment by mojavelinux** [comment]
No, that's not possible. We'd need a new issue to explore that kind of idea.

**Comment by alexandre-frey** [comment]
In an custom converter, I implemented a role `.pagestretch` for tables and figures that ensures the table/figure is stretch up to the page margins, not only the current content indent.

This allows writing extra wide tables like this:

    [.pagestretch]
    |===
    ...
    |===

Do you think such a role should be standard in asciidoctor-pdf ? See below the code in the extended converter, it's pretty simple...

Also, what do you think of the name "pagestretch". Any better idea?


````ruby
    #
    # Implement the role ".pagestretch" for tables, which allows the table to stretch 
    # to the page margins, instead of only to the section width
    #
    def convert_table node
        if (node.has_role? 'pagestretch')
            indent_l, indent_r = inflate_indent @theme[:section_indent]
        else 
            indent_l, indent_r = 0,0
        end
        indent -indent_l, -indent_r do
            super
        end
    end
````

**Comment by mojavelinux** [comment]
I will consider if you open an new issue. This issue is closed and therefore no more code changes will come of it.

When you submit that issue, I suggest proposing the name `pagewide` instead of `pagestretch`. The former name is more consistent with what I've run across in other systems.
