### ISSUE TITLE
latexmath blocks and inlines in table cells render nothing / don't render as math

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor-pdf#740]
Following on #707 , I've managed to experiment with stem blocks inside table cells in current github, using asciidoctor-mathematical. The attached sample produces non-intuitive results and I'm unsure if what I'm seeing is a markup error on my part, a known omission in the table/block support introduced via #707, or something that still needs to be fixed in that support. I've also attached an output PDF, generated via

asciidoctor -b pdf -d book -r path-to-github-asciidoctor-pdf.rb -r asciidoctor-mathematical -a mathematical-format=svg -a imagesoutdir=/tmp -o block.pdf block.txt

What I'm seeing is that a simple latexmath equation (outside of a table cell) renders correctly in the PDF.

A table cell containg nothing but a [latexmath] block renders nothing in that cell, and generates two lines of complaints:

asciidoctor: WARNING: conversion missing in backend pdf for stem
asciidoctor: WARNING: conversion missing in backend pdf for stem

Finally, a cell containing latexmath: inline macro surrounded by normal text renders the contents of the macro as text, rather than math.

[block.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/746934/block.txt)

[block.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/746936/block.pdf)

**Comment by mojavelinux** [comment]
This problem is explained in the following issue: https://github.com/asciidoctor/asciidoctor-mathematical/issues/20

**Comment by mojavelinux** [comment]
This is an upstream issue (either the responsibility of asciidoctor core or asciidoctor-mathematical) so I'm going to close the issue here.

**Comment by mojavelinux** [comment]
Just create an Ruby script named asciidoctor-mathematical-ext.rb and populate it with the following content:

```ruby
require 'asciidoctor/extensions'

Asciidoctor::Extensions.register do
  treeprocessor do
    process do |doc|
      mathematicalProcessor = MathematicalTreeprocessor.new
      (table_blocks = doc.find_by context: :table).each do |table|
        (table.rows[:body] + table.rows[:foot]).each do |row|
          row.each do |cell|
            mathematicalProcessor.process cell.inner_document if cell.style == :asciidoc
          end
        end
      end
    end
  end
end
```

Pass this script to a `-r` flag after `-r asciidoctor-mathematical`. Then stem blocks and inline macros in AsciiDoc table cells will get processed.
