### ISSUE TITLE
issue with dotted line in asciidoctor-diagram and SVG output

### ISSUE THREAD

**Issue by ssydorov** [asciidoctor/asciidoctor-pdf#741]
thank for help with issue #739. 
I have new one ;)
dotted line in PNG file looks ok, but in SVG version not 
please look on attached picture.
![diagramm-png](https://cloud.githubusercontent.com/assets/24498236/22583617/6653e5ec-e9f6-11e6-83b5-89e281e51bd0.png)
![diagramm-svg](https://cloud.githubusercontent.com/assets/24498236/22583626/73787cec-e9f6-11e6-9c73-b1a343ce1af2.png)

Thanks!
Sergiy

**Comment by ssydorov** [comment]
it connected with asciidoctor-pdf.
with asciidoctor everything is ok

**Comment by mojavelinux** [comment]
This looks like an issue with prawn-svg. Asciidoctor PDF delegates to that
library to render the SVG. It still makes mistakes sometimes.

I recommend filing an issue there and attaching the SVG.

**Comment by mojavelinux** [comment]
I don't see these lines when I produce the PDF. Can you be more specific about your setup:

* the AsciiDoc source
* the version of Asciidoctor PDF
* the version of Asciidoctor Diagram
* if you're using a custom PDF theme, your PDF theme file

**Comment by ssydorov** [comment]
It's strange for me. Did you see my pdf file?
source:
```
[plantuml, 4dan, svg]     
----
@startuml
Alice->Bob: Authentication Request
Bob --> Alice: Authentication Respone
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
----
```
asciidoctor-pdf
```
D:\temp>asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.13 using Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]) (lc:IBM866 fs:Windows-1251 in:- ex:IBM866)
```

asciidoctor-diagram
```
D:\temp>gem list asciidoctor-diagram
*** LOCAL GEMS ***
asciidoctor-diagram (1.5.4)
```
I am using standard PDF theme

Thanks.

**Comment by mojavelinux** [comment]
I tried exactly that setup and the dotted lines are correct. The only difference is that I'm using Ruby on Linux instead of Windows.

> (lc:IBM866 fs:Windows-1251 in:- ex:IBM866)

This part concerns me, but seems unrelated. You should always put Ruby into UTF-8 mode when using it. You can do that using:

> chcp 65001

**Comment by ssydorov** [comment]
Hi Dan,
sorry for delay with answer.
I changed codepade to utf... 
It's really unrelated. The same result,
What is strange for me: SVG file is ok, But image in PDF id not.

Regards,
Sergiy

**Comment by mojavelinux** [comment]
This turned out to be an issue with prawn-svg, visible in Adobe Acrobat. If the next version is a point release, it will be picked up automatically by Asciidoctor PDF. If it's a minor release, then we'll need to upgrade the version in the gemspec.

**Comment by mojavelinux** [comment]
See https://github.com/mogest/prawn-svg/issues/91.

**Comment by mojavelinux** [comment]
This fix will be available in alpha.16.
