### ISSUE TITLE
Text output problems using most TTF fonts

### ISSUE THREAD

**Issue by briandominick** [asciidoctor/asciidoctor-pdf#742]
When I use the default fonts of the asciidoctor-pdf default theme, the my document renders nicely. When I switch to fonts I prefer -- sticking to those downloaded directly from Google Fonts -- I get poor results.

One problem I encounter is the Prawn build error "CannotFit", which is supposed to be about box overflow, but which I have determined to actually be caused by glyphs. I do not understand why it is not using the fallback font for these characters, but at least it's an (apparently mislabeled) error I can understand.

In other cases, a font does not throw CannotFit errors, but the actual output hides _most_ characters. For instance:
<img width="838" alt="refguide_pdf__page_4_of_10_" src="https://cloud.githubusercontent.com/assets/1264177/22595438/79aedf44-e9f5-11e6-9365-770794a097d5.png">

I am interested in a nice sans-serif font and a more traditional (at least slightly serif) fixed-width font. These would be great additions to the default set, so I'd be happy to help construct them if that's what's needed, as Dan seems to have done with the included fonts. But I don't know where to begin, or what exactly is causing these fonts to have shortcomings in the eyes of Prawn/PDF.

**Comment by pwillard** [comment]
I'm currently using the UBUNTU font with OK results... except when using btn:[OK] which comes out messed up

**Comment by mchernosky** [comment]
I've used Open Sans successfully. I did get a `CannotFit` error trying to use square bullets, but using the (default) circular bullets worked okay.

**Comment by elburro1887** [comment]
I have used Lato, works great.

**Comment by briandominick** [comment]
Thanks for all the feedback here. I did eventually get Open Sans to work after eliminating all the square bullets. I could not get Ubuntu or Lato to work. I really dislike M+1, the default mono font, but so far I haven't found a suitable replacement.

**Comment by mojavelinux** [comment]
> I did get a CannotFit error trying to use square bullets, but using the (default) circular bullets worked okay.

This should now be resolved in alpha.15. I had made a calculation/logic error.

**Comment by mojavelinux** [comment]
I'm going to say the resolution of this error will come with #297. This issue certainly provides important context for me when writing that documentation. The CannotFit error should now be resolved with fixes in alpha.15. Therefore, I'm going to close. Continue to follow #297 and provide additional insight and examples there. These issues are now linked.
