### ISSUE TITLE
Links to relative files (on local disk) incorrect on Windows system

### ISSUE THREAD

**Issue by zhuermao** [asciidoctor/asciidoctor-pdf#744]
Links to relative files (on local disk) incorrect on Windows system.

`link-test.adoc`:
```
= Link Test

link:attachments/abc.docx[]
```

I put the result `link-test.pdf` into `D:\test` folder, open the file, and get this:
![link](https://cloud.githubusercontent.com/assets/3499765/22634580/0886befe-ec66-11e6-9ca8-a5cd5a76d813.png)

See that the link is `file:///D|test/attachments/abc.docx`.
I think `D|` should be `D:`.

**Comment by mojavelinux** [comment]
The pipe is how a drive letter is represented in a file URI. It should still work. And it's PDF reader that is doing this conversion, not Asciidoctor PDF.
