### ISSUE TITLE
table with horizontal borders only

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#757]
Is it possible to style table to have only horizontal borders between rows? Make them dashed?

**Comment by habamax** [comment]
Such as this one?

![default](https://cloud.githubusercontent.com/assets/234774/23131476/22c531e8-f79b-11e6-9fcc-f3b80170bb08.png)

**Comment by mojavelinux** [comment]
Yes. You'd define it as follows:

```
[cols="1s,1,1,1,1",frame=none,grid=rows,stripe=all]
|===
|Field Name |Description |Format |Archive |Lineage

|ID
|Numeric unique ID of the report
|Number
|
|

|Name
|Name of the report (short)
|Text
|
|
|===
```

It's not currently possible to change the border style. However, we could add support for that in the theme. I'll open an issue.

**Comment by mojavelinux** [comment]
See #766.

**Comment by habamax** [comment]
I was searching theme guide how to do it :)

With your I get almost what I need, I hope 766 will solve it.

BTW, I can't remove header grid.

![image](https://cloud.githubusercontent.com/assets/234774/23833054/5b98179a-0751-11e7-880f-dfa7d457ac70.png)


        table:
       background_color: $page_background_color
       head_background_color: 002060
       head_font_color: ffffff
       head_font_style: bold
       even_row_background_color: f2f2f2
       odd_row_background_color: f2f2f2
       foot_background_color: f0f0f0
       border_color: $base_border_color
       border_width: 0
       grid_width: 0.1
       grid_color: e2e2e2
       # HACK accounting for line-height
       cell_padding: [3, 3, 6, 3]

**Comment by mojavelinux** [comment]
What you've circled aren't actually borders.  I verified that Asciidoctor PDF is not adding borders on these cells. Instead, they are some sort of artifact that evince adds. If you open in Adobe Reader I think you'll find that they aren't there.

Likely this is some sort of rounding error in Prawn that is introducing a hairline gap, causing the background to be visible. I think this needs to be filed with Prawn.

**Comment by mojavelinux** [comment]
The way you can check that it isn't Asciidoctor PDF adding a border between header cells is by setting the grid width to a large value like 5. You can then see that the results are the same, so these two things are not linked.

**Comment by mojavelinux** [comment]
I'm going to close this issue since #766 covers the actual feature request. After testing against master, please comment there.

**Comment by habamax** [comment]
Well, indeed it is not asciidoctor-pdf/prawn fault -- there are no gaps in Acrobat Reader. Gaps are rendered in firefox PDF.js or whatever it is called.

Thx.

**Comment by mojavelinux** [comment]
I think the fact that there are gaps in some viewers indicates there's some sort of problem. We just need to figure out where the gaps get created. It's either a rounding error in Prawn / Prawn Table or it's a bug in the viewers (though I see the same thing in Evince). Tables are actually just adjacent boxes (since PDF doesn't have a table to my knowledge). That's why it seems to me like a rounding error.

**Comment by mojavelinux** [comment]
I think Adobe Reader is just being more intelligent about merging near-adjacent objects.
