### ISSUE TITLE
Color "Red" makes asciidoctor-pdf crash when using passthrough macro.

### ISSUE THREAD

**Issue by smru** [asciidoctor/asciidoctor-pdf#759]
**$** `echo 'pass:q[<span style="color: Red;"><strong>foo</strong></span>]' > test.adoc`
**$** `asciidoctor-pdf test.adoc`

**wrong number of arguments (1 for 0)
Use --trace for backtrace**

However, when using "Green" color, it succeeds.

**$** `echo 'pass:q[<span style="color: Green;"><strong>foo</strong></span>]' > test.adoc`
**$** `asciidoctor-pdf test.adoc`

**Comment by smru** [comment]
For now, OrangeRed does succeed.
However, the color is not rendered, i.e. the text stays black.

**Comment by mojavelinux** [comment]
Named colors are not recognized (or permitted). You need to use one of the color formats specified in the [theming guide](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#colors). For example, to make red, you can use `#ff0000`.

I agree that an invalid color shouldn't cause the processor to crash. I'll address that.

**Comment by mojavelinux** [comment]
Patch applied.
