### ISSUE TITLE
Can not have more than 2 levels in PDF TOC

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#764]
I'm creating a large document from various includes. I use leveloffset a lot to get the TOC to format in a usable fashion. 

No matter what I do I can not get more than two levels of numbered headings to be rendered in the TOC of the resulting PDF. 

I get something like:

```
1. Somestuff
1.1 A sub chapter
1.2 Another Sub chapter
2. More Stuff
```

But There is at least multiple 1.2.n points that I can not get displayed.

I have :toclevels: 5 and :sectnumlevels: 5 set in the main document but it doesn't change anything. Even the Atom previewer doesn't show more than 2 levels. What am I doing wrong?

The included files begin mostly with level 0. Is that the cause here?

**Comment by r0ckarong** [comment]
Turns out I made the same mistake someone else made and had empty lines in my document header. This dropped the attributes.

**Comment by mojavelinux** [comment]
:+1:

**Comment by matthieu-labas** [comment]
> Turns out I made the same mistake someone else made and had empty lines in my document header. This dropped the attributes.

What do you mean by "document header"? In the "main" .adoc? Or in the PDF theme .yml?

**Comment by mojavelinux** [comment]
See https://docs.asciidoctor.org/asciidoc/latest/document/header/#document-header-structure

**Comment by matthieu-labas** [comment]
> See https://docs.asciidoctor.org/asciidoc/latest/document/header/#document-header-structure

Thanks Dan!

To be more specific, I had to remove the empty line between my title and headers:

```
ifeval::["{lang}" == "fr"]
= Manuel de configuration
endif::[]
ifeval::["{lang}" != "fr"]
= Configuration Manual
endif::[]
                             <<<--- Need to remove this empty line
:sectnums:
:sectnumlevels: 4
:imagesdir: ./Pictures
:source-highlighter: rouge
:lang: fr
:toc:
:toclevels: 5
:toc-placement: macro
```

**Comment by mojavelinux** [comment]
Yep!

**Comment by mojavelinux** [comment]
In the future, please direct questions about usage to the project chat at https://chat.asciidoctor.org. Thanks!
