### ISSUE TITLE
Add option to scale background SVG to fit page

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#765]
Currently, an SVG used for the page background is not scaled. There should be an option to scale it to fit within the bounds of the page.

The workaround is to set the width and height of the SVG (or scale the view box) so that it fits within the page.

**Comment by ecki** [comment]
I found it helpful when designing the title page SVG that it was not scaled and so the coordinates translated 1:1. in my case I used a 210mm x 210mm viewport since it covered only the top of my page anyway. So scaling should be optional.

**Comment by mojavelinux** [comment]
I've updated the title.

**Comment by mojavelinux** [comment]
Though I think what I was suggesting is that it be scaled down automatically. I can't really see a case when you want it to exceed the limits of the page. So there are really two options at work here. First, that it be scaled down to fit within the page. That should be automatic. The second would be to have it scale to fit the dimensions of the page. That would involve stretching. And actually, I'm not sure we even want that.

**Comment by mojavelinux** [comment]
In running content, we implemented fit=contain (which scales either way until the image fits) and fit=scale-down (which scales down only). This is taking a page from [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) from CSS. We could also consider supporting cover in the future.

**Comment by mojavelinux** [comment]
It looks like this got implemented at some point, though now it's not possible to not scale. However, I think both pdfwidth and fit should be supported.

**Comment by mojavelinux** [comment]
Ah, I see. If the width and height attributes are set on the SVG itself, then it doesn't scale down. So we're just lacking a lot of consistency here.

**Comment by mojavelinux** [comment]
Now that I've had a chance to divide deep into this, I now understand the original motivation for the issue. The `svg` method provided by prawn-svg doesn't honor the `:fit` option. So while PNGs are being scaled down to fit the page, SVGs are not.

I think we have two separate issues here. First, to bring the behavior of SVG inline with raster images (e.g., PNG). Second, implement explicit sizing for the background image. Since the second isn't limited to SVG, I'm going to fix the first issue, then we'll address the second in a separate issue.

To conclude, the focus of this issue will be to automatically scale down a background SVG to fit the boundaries of the page.
