### ISSUE TITLE
Allow theme to control table border style

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#766]
Allow the theme to control the style of the table border. When the border is enabled using the frame and grid attributes, the border has a solid style. However, Prawn table also supports dashed and dotted lines. Allow the border style to be set on the table as a whole.

```
table:
  border_style: dashed
```

Prawn Table will be responsible for drawing the styled border, so any issues with it need to be taken up with that project. See https://github.com/prawnpdf/prawn-table.

(Note that Prawn Table does not support the double style).

**Comment by mojavelinux** [comment]
The theme should also be able to control the grid style:

```
table:
  grid_style: dashed
```

border is the outer borders (aka frame); grid is the inner borders.

**Comment by habamax** [comment]
It looks quite strange -- dashes are `small-long-small` and some spanned cells are unaffected:

![default](https://cloud.githubusercontent.com/assets/234774/23846879/aeeb8992-07e0-11e7-8238-d9c7854ccacc.png)

**Comment by habamax** [comment]
And the dotted style:

![default](https://cloud.githubusercontent.com/assets/234774/23846958/22dd0876-07e1-11e7-89dd-d5b67da5ab1a.png)

**Comment by habamax** [comment]
If you change grid_width from 0.1 to 1 (dotted):
![default](https://cloud.githubusercontent.com/assets/234774/23847041/8d9f92aa-07e1-11e7-91e1-447c694fac7d.png)
