### ISSUE TITLE
Allow theme to specify a border for block images

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#767]
Allow a border to be set for block images using the theme. This allows figures to be more clearly offset from the text.

**Comment by andraz-kozelj** [comment]
Any progress on this?
Dark themes are all across the place but mostly white images on paper need some border/delimitation!

**Comment by mojavelinux** [comment]
I don't have time to work on this right now, but I would accept a PR from the community as long as it has a test.

**Comment by mojavelinux** [comment]
Any advice on where the border would go? Is it just around the image, or around the caption too? Is it necessary to allow for space (i.e., padding) between the border and the image? Should the border stretch the width of the page?

**Comment by andraz-kozelj** [comment]
I would copy the HTML rendering behavior. There you can manipulate the CSS in a way to add box shadow, which is useful for white background images on white background page.

Border should delimit the image only, caption is separate. If the image is 500px wide and you define 2px wide border, shrink image to 496 - border is part of the image.

Border:

- color
- width
- style? (dotted, dashed, mixed, solid)
- transparency?

Can you produce a shadow-style border?

Can you make it consider the [role], to make images exempt of this rule?
For instance `[no-border]` would omit the border etc.

**Comment by mojavelinux** [comment]
> Can you produce a shadow-style border?

Not with Prawn.

I'm not really asking to expand the scope of this. I'm asking what the minimum functionality is that would make it useful. I really don't have a lot of time for this, so it's either minimum or nothing.

**Comment by mojavelinux** [comment]
We can implement the border as it already is available for other blocks (width, color, style). So the question is whether we need padding. It sounds like the answer is yes. What about the width? I'm assuming the width of the page?

This would be on or off. It can't be controlled by the document, at least not in the first iteration.

**Comment by andraz-kozelj** [comment]
Padding should be around the image - between the image and the border itself - like creating a frame. What is outside of the border is not the concern of this setting.

**Comment by owenh000** [comment]
In my case, I would be using this like CSS `img { border: 3px solid gray }`.

- The border goes around the image only, not the caption.
- The border size is approximately the same as the image itself; either slightly larger or the image is shrunk slightly to accommodate the border.
- I do not need any padding between the image and the border or any additional padding anywhere else.
- The resulting behavior would be the same as if I added a 3px border as part of the image itself.

I hope the above is helpful. It looks like @andraz-kozelj has given some feedback also. @mojavelinux, thanks for looking into this!

**Comment by mojavelinux** [comment]
Thank you both. I think the requirements are now clear.

Since there are cases for extending the border out to the page margins, what I'm thinking is adding support for "auto" padding on the left and right. The auto value means "take up the remaining space". In other words:

```
image:
  padding: 0 auto
```

The only remaining case to address is when the image already extends to the page margins (i.e., pdfwidth=100%). Do we shrink the image so that the border will fit? I think we need to.

**Comment by owenh000** [comment]
>The only remaining case to address is when the image already extends to the page margins (i.e., pdfwidth=100%). Do we shrink the image so that the border will fit? I think we need to.

Yes, it seems like it would be necessary to shrink the image in that case.

**Comment by mojavelinux** [comment]
While implementing this feature, I've learned that it would be incredibly complicated to shrink the image to fit inside the border (it's a bit of a chicken-egg problem and some of the logic lives inside Prawn and Prawn SVG). Therefore, we're going to draw the border on the inside of the box that is allocated for the image. If the border is thin, this will hardly be noticeable, so I think it's a fair trade off to get this feature implemented.
