### ISSUE TITLE
Disclaimer texts or additional defined texts for title page

### ISSUE THREAD

**Issue by gxurma** [asciidoctor/asciidoctor-pdf#771]
I added to the title a disclaimer that is always needed for the documents I produce. I added to the converter.rb after the revision info : 

	  disclaimer_info = (doc.attr 'disclaimer') || (@theme.title_page_disclaimer_content)
	  if disclaimer_info
	    if (disclaimer_top = @theme.title_page_disclaimer_top)
		  if disclaimer_top.end_with? 'vh'
		    disclaimer_top = page_height - page_height * disclaimer_top.to_f / 100.0
		  else
		    disclaimer_top = bounds.absolute_top - effective_page_height * disclaimer_top.to_f / 100.0
		  end
		  # FIXME delegate to method to convert page % to y value
		  @y = disclaimer_top
	    end
	    move_down (@theme.title_page_title_margin_top || 0)
		theme_font :title_page_disclaimer do
		  layout_prose(disclaimer_info,
                align: (@theme.title_page_disclaimer_align || @theme.title_page_align).to_sym,
                margin: 0,
                normalize: false)
		end
	  end

and to the theme something like:

    disclaimer:
      top: 80%
      align: justify
      font_color: 181818
      font_size: $base_font_size_small 
      font_style: normal
      content: |
        COMPANY PROPRIETARY INFORMATION:
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

It is possible to add

      :disclaimer: Some other disclaimer text or info

to the document with it.

Only thing I miss now is to add a fine lined box around this disclaimer (it is required in our stupid docx template)

Since I am not familiar with git, please add this disclaimer thing to the next releases, maybe someone needs it.

**Comment by mojavelinux** [comment]
Thank you for sharing. This seems very specific for a certain use case and is best left to custom code.
