### ISSUE TITLE
can't modify frozen Array (RuntimeError)

### ISSUE THREAD

**Issue by owenh000** [asciidoctor/asciidoctor-pdf#772]
I am unable to install a working asciidoctor-pdf on Debian Jessie. Any ideas? Thanks.

```
$ rm -rf ~/.gem
$ gem install --user-install asciidoctor-pdf --pre
...
$ which asciidoctor-pdf
/home/user/.gem/ruby/2.1.0/bin/asciidoctor-pdf
$ asciidoctor-pdf -v
/home/user/.gem/ruby/2.1.0/gems/prawn-templates-0.0.3/lib/prawn/templates.rb:246:in `<top (required)>': can't modify frozen Array (RuntimeError)
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/user/.gem/ruby/2.1.0/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf/converter.rb:10:in `<top (required)>'
    from /home/user/.gem/ruby/2.1.0/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf.rb:3:in `require_relative'
    from /home/user/.gem/ruby/2.1.0/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf.rb:3:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /home/user/.gem/ruby/2.1.0/gems/asciidoctor-pdf-1.5.0.alpha.14/bin/asciidoctor-pdf:4:in `<top (required)>'
    from /home/user/.gem/ruby/2.1.0/bin/asciidoctor-pdf:23:in `load'
    from /home/user/.gem/ruby/2.1.0/bin/asciidoctor-pdf:23:in `<main>'
```

**Comment by mojavelinux** [comment]
A new version of Prawn was just released today and it appears that that version of Prawn has broken prawn-templates by freezing an array that prawn-templates tries to modify.

You'll need to first install the older version of Prawn, then install Asciidoctor PDF to workaround:

```
gem install prawn --version 2.1.0
gem install asciidoctor-pdf --pre
```

**Comment by mojavelinux** [comment]
There also appear to be incompatibilities between Prawn 2.2.0 and TTFunk 1.5.0. That's solved by installing Prawn 2.1.0 as well.

**Comment by mojavelinux** [comment]
I have documented this in the README. I'll try to get Asciidoctor PDF to be compatible with Prawn 2.2.0. But that won't take effect until the next release.

...and this is why I lock dependencies, for those who ask me ;)

**Comment by mojavelinux** [comment]
I'm closing for now. I'll address the compatibility with Prawn 2.2.0 separately.

**Comment by mojavelinux** [comment]
I've opened a PR with the changes that need to be made in alpha.15 to get Asciidoctor PDF working with Prawn 2.2.0. See #773.

**Comment by owenh000** [comment]
Thank you!

**Comment by seregasheypak** [comment]
Hi, I have same issue with http://asciidoctor.org/docs/asciidoctor-gradle-plugin/

Is there any workaround? Does anyone know working set of dependency versions? I'm trying to generate UML png diagrams. Thanks!
