### ISSUE TITLE
Labeled lists missing styles (bold in term names)

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-pdf#776]
Comparing HTML and PDF renderings I noticed that labeled lists don't show term names in bold.

. PDF on the right, HTML on the left
![image](https://cloud.githubusercontent.com/assets/5781153/24080423/2bc1cb44-0c9f-11e7-9714-6ec6e4c896f4.png)

Also, I did not see any way to customise it with a style (https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc).
For me, not highlighting the term in bold breaks the readability and makes labeled list lest useful in PDF.

Is there a way to get it?

**Comment by mojavelinux** [comment]
What you are looking for is the [description list configuration](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-description-list), specifically term_font_style.

```
description_list:
  term:
    font_style: bold
```

However, I agree that this should be the default. The italic style is a carryover from the custom theme we had original done for Asciidoctor PDF and was not intended to align with the standard look. All the CSS frameworks, and HTML itself, use bold by default, and so should we.

**Comment by mojavelinux** [comment]
Btw, "labeled list" is an outdated term. The proper term is "description list" (according the wise people of the HTML specification).

**Comment by abelsromero** [comment]
> Btw, "labeled list" is an outdated term. The proper term is "description list" (according the wise people of the HTML specification).

Thanks for the appreciation, I really do. But should the manual include that also [here](https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/hack-asciidoctor-maven-plugin.adoc)? 
Something like _Labeled lists (also known as description list in HTML jargon)_.

**Comment by mojavelinux** [comment]
Yes, this chapter in the user manual named [Labeled list](http://asciidoctor.org/docs/user-manual/#labeled-list) needs to be renamed and the terminology updated. I'll file an issue in asciidoctor.org.
