### ISSUE TITLE
:toctitle: is not honoured

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor-pdf#786]
I have setup a custom `toctitle` but it does not reflect in the PDF export.

For example:

```
= Contenus & collaboration
:toc:
:toctitle: Sommaire
:hide-uri-scheme:
:idprefix:
:icons: font
:revnumber: v1.0
:revdate: 26 mars 2017
```

Displays the following:

<img width="347" alt="screen shot 2017-03-26 at 21 26 05" src="https://cloud.githubusercontent.com/assets/138627/24334878/daca6d14-126a-11e7-9e5e-8a9a95cc82d3.png">

```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.14 using Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
The correct name of the attribute is `toc-title`, not `toctitle`. If you fix the name, you should find that it works.

See http://asciidoctor.org/docs/user-manual/#user-toc-title

**Comment by oncletom** [comment]
Ah, I got confused by the `attribute` mentioned on this section of the doc: http://asciidoctor.org/docs/user-manual/#special-characters

I will double check this afternoon and will reopen it it needed :-)

Thanks a lot for the blazing fast support 👍

**Comment by mojavelinux** [comment]
Thanks for catching that, @oncletom! I fixed it.
