### ISSUE TITLE
Combine multiple *.adoc documents into a single PDF?

### ISSUE THREAD

**Issue by kytrinyx** [asciidoctor/asciidoctor-pdf#79]
Is it currently possible to combine multiple *.adoc documents (for example chapters in a book) into a single PDF?

If this is undocumented, but someone has working code, I'd be happy to work on turning that into documentation.

If not, I suppose it's a fairly trivial thing to write a build script that first combines the *.adoc files into a single file.

**Comment by chloerei** [comment]
Use `include` http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files

**Comment by kytrinyx** [comment]
Ah, of course. Thank you.

**Comment by kytrinyx** [comment]
Is there a common idiom for the top-level document for a book?

**Comment by leif81** [comment]
@kytrinyx I've seen `index.adoc` used often.

e.g. https://raw.githubusercontent.com/spring-projects/spring-boot/master/spring-boot-docs/src/main/asciidoc/index.adoc

**Comment by kytrinyx** [comment]
Thanks!

**Comment by fractalocity** [comment]
had the same exact question. This helped out a lot. Thanks for asking the question and for the chloerei answer.
