### ISSUE TITLE
Recto/Verso margins are applied to title page when cover is not used

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#793]
I finally figured out how to use the media=prepress argument to do proper margins on the alternating pages. I'm using a custom theme and unfortunately these margins are also applied to the title page and the table of contents. This means my title page with logo and title is skewed to the right because it apparently treats it as a recto page.

![selection_003](https://cloud.githubusercontent.com/assets/4920542/24466261/89913e12-14b0-11e7-9e45-4541b1a339b9.png)

I would like to keep the margins for the rest of the content but obviously not my title page.
Is there some way to suppress/override margins for certain pages?

**Comment by mojavelinux** [comment]
I think it depends on how you define "title page". If you think about a book, the title page is the first page you see when you lift the cover. In that scenario, it is a bound page and needs to be offset. However, if you use the "title page" as the cover page, then obviously you don't want that behavior. We would need some way to express that.

One way to fix this today is to first produce a 1-page PDF of your title page (without setting the media attribute). Then, in the main document, disable the title page using the "notitle" attribute and import the title page you generated as the cover page using "front-cover-image".

**Comment by mojavelinux** [comment]
My first instinct was to say if a cover page is not present, don't shift the content on the title page. However, I've worked with on publisher who generated the prepress file of only the bound pages...so in that case they do want the content on the title page shifted.

Perhaps we can introduce a "nocover" attribute. This not only ignores "front-cover-image", but it also assumes that the title page, if enabled, acts as the cover page. It seems to me like that would cover all scenarios.

**Comment by r0ckarong** [comment]
I want to be able to export documents that are completely generated by the underlying Asciidoc files. A cover image is a static resource that must be separately maintained and edited in a different application. For the approach we're following with reducing documents to "source code" as much as possible this isn't ideal. 

I would welcome such a "nocover" attribute that allows the title page to act as the de facto cover page.

**Comment by mojavelinux** [comment]
I skipped a step in my explanation which caused some confusion. I'm not suggesting that you introduce a static resource that must be separately maintained (although that is possible). I'm simply saying that you invoke Asciidoctor PDF twice. The first time, you run it without the media attribute set in order to create your cover page. The second time, you run it with the media attribute, the front-cover-image, and the notitle attributes set. That effectively generates a cover page and then uses it.

Here's a script you can use to do that:

```
asciidoctor-pdf -r ./extract-header.rb -o cover.pdf book.adoc &&
  asciidoctor-pdf -a media=prepress -a notitle -a front-cover-image=image:cover.pdf[] book.adoc
```

Where extract-header.rb contains an extension to skim off the document header:

```ruby
require 'asciidoctor/extensions'

Asciidoctor::Extensions.register do
  preprocessor do
    process do |document, reader|
      lines = []
      while reader.has_more_lines?
        break if (line = reader.read_line).empty?
        lines << line
      end
      Asciidoctor::Reader.new lines
    end
  end
end
```

**Comment by mojavelinux** [comment]
I think I'm going to invert the logic of my previous proposal. By default, the title page will not be offset unless there's also a cover. To render the document with an offset title page but without the cover pages, then you set the `nocover` attribute.

To clarify, I'll provide examples:

Scenario 1: Title page is not offset and title page is first page:

```
= Book Title
:doctype: book
:media: prepress

content
```

Scenario 2: Title page is offset and cover page is first page:

```
= Book Title
:doctype: book
:media: prepress
:front-cover-image: cover.jpg[]
```

Scenario 3: Title page is offset and title page is first page:

```
= Book Title
:doctype: book
:media: prepress
:front-cover-image: cover.jpg[]
:nocover:
```

So the `nocover` attribute expresses an intent to not include the cover, even though the cover is available.

Does that seem logical? cc: @mraible

**Comment by mojavelinux** [comment]
We could also consider `hidecover`. But since we've been using the "no" prefix for other attribute, it might make sense to stay consistent.

**Comment by mojavelinux** [comment]
If you approve this design, I'll proceed with implementation.

**Comment by r0ckarong** [comment]
Yes please add this and document how it's supposed to be used correctly. I can write something up if that helps.

**Comment by mojavelinux** [comment]
Instead of `nocover`, I decided to reuse the `front-cover-image` attribute. If the value of that attribute is `~`, it's meant to indicate a false front cover, so the title page should be considered an inner page.

**Comment by mojavelinux** [comment]
The proposal is up. See #1439.
