### ISSUE TITLE
Font doesn't fallback for non 1252 characters for indented list items

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#794]
I have lists with multiple levels in my documents. The font I'm using apparently lacks the glyph for "white bullet" &#x25E6;. This is replaced in the resulting PDF with the not glyph.

How can I either: 

Change the glyph used to display second level list items?
or
Make asciidoctor-pdf fall back to the M+ 1mn font (which I specified)?

I would rather not try to modify a publicly available font just to fix this issue for my local installation.

**Comment by r0ckarong** [comment]
Turns out all the levels below use glyphs that are unsupported as well so the question expands to anything below the first level in any unordered nested list.

**Comment by mojavelinux** [comment]
> The font I'm using apparently lacks the glyph for "white bullet" ◦. This is replaced in the resulting PDF with the not glyph.

This is a clear indication you're using an AFM font. The "not" glyph is only used as the substitute for a missing glyph in an AFM font (e.g., Helvetica, Times-Roman, etc). If you were using a non-AFM font, such as a TTF font, it would either use the glyph from the fallback font or render nothing if it's missing in the fallback font too.

> Change the glyph used to display second level list items?

This is an open issue. See #798 (which I just opened).

> Make asciidoctor-pdf fall back to the M+ 1mn font (which I specified)?

The fallback font is not used if the main font is an AFM font. In other words, the main font must be a TTF (or DFont) in order for the fallback font to be used.

> I would rather not try to modify a publicly available font just to fix this issue for my local installation.

That's just a requirement of using custom fonts in Asciidoctor PDF at the moment. Unfortunatley, most fonts (esp publicly available ones) lack essential glpyhs and are thus incomplete. We take for granted that browsers use a long list of fallback fonts to make up for this deficiency.

**Comment by mojavelinux** [comment]
I clarified this point in the theming guide. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#fallback-fonts

**Comment by marcotama** [comment]
I am running into the same issue, but the fonts I am using are TTF, or at least FontSquirrel claims they are.
