### ISSUE TITLE
Allow configuration of ulist spacing

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#799]
This is related to #798 if we get configuration for unordered lists would it be possible to also specify other rendering options? I find the line spacing in lists especially troublesome because they are really really big compared to some other content on the page (the way I have them configured). Currently I wouldn't know how to configure line_height for this. Could you implement some way to do something like:

```
ulist:
  line_height: $base_line_height
```

EDIT: Of course this would be wonderful for ordered lists as well.

**Comment by mojavelinux** [comment]
This is already possible using the outline_list_item_spacing setting. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-outline-list. That controls both ordered and unordered list items.

**Comment by r0ckarong** [comment]
Ok got it now. I didn't know the term outline list. Works now. Thank you.

**Comment by mojavelinux** [comment]
That's one of the reasons I plan on changing it. It's time to fix the
terminology ;)
