### ISSUE TITLE
Show author's name as a link on the title page if email or URL is specified

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#800]
If an e-mail or URL is provided for an author, the author's name should be shown as a clickable link on the title page.

```
= Document Title
Doc Writer <doc@example.com>; Junior Writer <https://github.com/ghost>
```

**Comment by mojavelinux** [comment]
I'm wondering whether we should only make the author's name a link if the value of the email attribute (the value between the angled brackets) is a URL or link macro. I don't see much point in making a link for an e-mail address.

Here's how I imagine the example shown above would be render with the default theme:

> Doc Writer &lt;doc(at)example.com&gt;, [Junior Writer](https://github.com/ghost)

(NOTE: (at) would be replaced with @, but I can't type it here without it being interpreted)

**Comment by sbrannen** [comment]
> I don't see much point in making a link for an e-mail address.

I'm rather indifferent on that subject, but I assume somebody will ask to have it converted into a link as soon as you decide to make it impossible. ;-)

**Comment by mojavelinux** [comment]
We might have something in the theme to specify whether the author information should be linkable or just plain.

**Comment by sbrannen** [comment]
> We might have something in the theme to specify whether the author information should be linkable or just plain.

Sounds like a plan.

**Comment by mojavelinux** [comment]
I just looked at it tonight and it seems like we're still trying to nail down the requirements.

> Would it also be possible to add icons? e.g. a Twitter icon?

I think that would be out of scope for this issue, unless it just happens to work because of the code change we make.

**Comment by mojavelinux** [comment]
This really opens a lot of questions:

1. Should the email/url be show next to the author's name, or should the author's name itself be a link? What about when media=print or prepress?
2. Should it be possible to customize the font color of the link? (perhaps using a role?)
3. Should it be possible to disable?

Perhaps we need to have a template string in the theme (which accepts pseudo-HTML). That would make all these things possible.

**Comment by mojavelinux** [comment]
Here's what I came up with. If you know all authors will have an email (which creates an implicit url) or a url, you can use:

```
title-page:
  authors:
    content: '{url}[{author}]'
```

If the authors have different metadata, you can define the template per variation:

```
title-page:
  authors:
    content:
      name_only: '{author}'
      with_email: '{author} <{email}>'
      with_url: '{url}[{author}]'
```

Note that you can also use any AsciiDoc document attribute:

```
title-page:
  authors:
    content: '{lastname}, {firstname}'
```

You can also throw in some icons (though make sure icons=font is set on the document):

```
title-page:
  authors;
    '{author} {url}[icon:twitter[set=fab]]'
```

**Comment by jnerlich** [comment]
Looks good to me.

**Comment by jnerlich** [comment]
Awesome, thanks. Will this also be available for the html output?

**Comment by mojavelinux** [comment]
Asciidoctor PDF uses a separate configuration / theming system from the HTML converter. And you can already use templates to change the HTML produced by the HTML converter. So these are different concerns.

**Comment by mojavelinux** [comment]
In other words, we introduced this configuration for Asciidoctor PDF because templates do not get used by this converter.

**Comment by mojavelinux** [comment]
...but I agree it should be easier to apply a similar configuration to the HTML output. If you file an issue in asciidoctor/asciidoctor, I'll see what I can do.

**Comment by jnerlich** [comment]
Issue created https://github.com/asciidoctor/asciidoctor/issues/3576
