### ISSUE TITLE
Info Dictionary, Metadata

### ISSUE THREAD

**Issue by MaWiMa** [asciidoctor/asciidoctor-pdf#804]
Only the :authors: tag does work to get metadata for/of Author(s) into the "Info Dictionary" of a pdf file.
The :authors: tag does not work for epub metadata. For epub the :author: tag has to be used.

**Comment by mojavelinux** [comment]
Regardless of whether the authors are defined using the implicit author line, the `author` attribute, or the `authors` attribute, they get assigned to the PDF :Author metadata field.
