### ISSUE TITLE
Fallback font lacks u202f (Narrow No-Break Space) character used for buttons

### ISSUE THREAD

**Issue by owenh000** [asciidoctor/asciidoctor-pdf#807]
When using the Open Sans font, the buttons do not render correctly. This is because the u202f "Narrow No-Break Space" glyph is missing from Open Sans font *and* from the the default fallback font (M+ 1P). This is not a problem when using the default Noto Serif, because that font contains the glyph.

Should the u202f "Narrow No-Break Space" glyph be added to the fallback font?

**Comment by mojavelinux** [comment]
Sounds reasonable.
