### ISSUE TITLE
A way to modify a YAML parameter before conversion ?

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor-pdf#808]
hello,

In the YAML, I defined in the footer an image (to specify the privacy policy).
But I want to be able to modify it according to a parameter of my asciidoc document.
Is it possible ? Either directly in the YAML, or from an extension (in an extension, I haven't found how to retrieve footer parameters).

Thank you.
Jérôme

**Comment by JBR69** [comment]
I found a solution by modifying the `converter.rb` but is really the best way ?

```
    if !(doc.attr 'confidentiality').nil? 
        if (doc.attr 'confidentiality')==''
            doc.set_attr 'confidentiality', 'public'  
        end
                
        @theme.footer_recto_left_content = "image:#{doc.attr 'commonresourcesdir'}/icons/confidential/#{doc.attr 'confidentiality'}.png[privacy, align=left]"
        @theme.footer_verso_right_content = @theme.footer_recto_left_content        
    end
```

**Comment by mojavelinux** [comment]
Shall we update the title to make this more specific?

**Comment by JBR69** [comment]
Yes, you can update the title.

The ideal would be to be able to use an attribute defined in the asciidoc document to specify the path of the image and to use it in the YAML like this : ```content:   image:{image-attribute}```
But the path to the image should be resolved from the document directory but not from the theme directory (Certainly the most difficult point).

**Comment by mojavelinux** [comment]
Btw, the Asciidoctor API now accepts the resolved theme via the pdf_theme option. So it's possible to read the theme in yourself, manipulated it as you see fit, then pass it to Asciidoctor (PDF). You can see tons of examples of this in the test suite since that's how all the theme overrides in the test suite are handled.

**Comment by mojavelinux** [comment]
Here's a method you can use (from the test suite) to build on an existing theme:

```rb
def build_pdf_theme overrides = {}, extends = nil
  (Asciidoctor::PDF::ThemeLoader.load_theme extends).tap {|theme| overrides.each {|k, v| theme[k] = v } }
end
```

You can then pass the result to the `pdf_theme` option of the Asciidoctor load or convert APIs.

Given that this is now possible, I'm going to close this issue.
