### ISSUE TITLE
Allow text decoration for headings

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#811]
Is there some way to enable text decoration (specifically underline) for headings?

If not could support be added in the future? Underlined headings are a very typical things in many types of documents. It kind of limits my ability to design the document after our corporate style.

**Comment by mojavelinux** [comment]
Would it be enough to be able to set a border, or does it need to be an underline?

The reason I ask is because I'm trying as much as possible to map to the constructs of CSS. So I'm just thinking about what we'd use in CSS to accomplish this styling.

Aside from that detail, I support the idea. We definitely want to allow you to match your branding requirements. That's the main idea of the theme system.

**Comment by r0ckarong** [comment]
https://www.w3schools.com/cssref/css3_pr_text-decoration-color.asp

No idea which version of CSS the prawn toolchain supports at the moment.

**Comment by mojavelinux** [comment]
Cool! I didn't realize the extended styles for text-decoration got accepted. That's great news.

> No idea which version of CSS the prawn toolchain supports at the moment.

Prawn doesn't support CSS at all. We're just designing a theming system (which is entirely an Asciidoctor PDF construct) to encompass the spirit / terminology of CSS so it feels familiar to designers and web developers. The only thing that CSS provides us is the terminology.

**Comment by mojavelinux** [comment]
Thanks for the clarification about your needs for border vs text decoration. It's clear to me that we'll need to provide both options, so I'll keep this as a discrete issue.

**Comment by r0ckarong** [comment]
I actually just realized that I misread your initial question. I read "border" as basically a horizontal rule. Not what I meant at all. Whatever is easier to implement I would be happy with a border. The difference to me is that a border is somewhat detached from the text whereas the underline with some glyphs runs "through" the text and therefore is more easily identified as an underline and not a style of the block the text sits in. It probably won't make a difference to must users. I would prefer underline. 

Having the other options available would be cool too. Having borders around certain elements defined in the theme.yaml would be amazing. I could add borders around filenames or paths.

Then I start thinking about all the ::before use cases ;)

**Comment by mojavelinux** [comment]
The other big difference of a border vs an underline is that the border extends to the width of the content area whereas the underline only extends to the end of the text.

Drawing borders around arbitrary elements is hard at the moment, but I'm working on finding a way to make it possible. With Prawn, we literally have to draw everything you see...so it's a lot of work to do what we're used to getting from CSS "for free".

**Comment by r0ckarong** [comment]
Sounds like a good argument for underline to me ^^

**Comment by mojavelinux** [comment]
I realized that text decoration and border are two separate concerns. We can add support for text decoration and then address the border separately. It looks like the framework is already in place, so this shouldn't be terribly difficult to add.
