### ISSUE TITLE
Allow text decoration color to be set

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#812]
Is it possible to allow setting the color of text decoration separate from the font color? We are using Black headings with orange underlines in the new corporate style and I would like to support that.

Relates to 
#811

**Comment by r0ckarong** [comment]
Sorry posted the answer to the wrong issue: https://www.w3schools.com/cssref/css3_pr_text-decoration-color.asp 

This allows you to set text decoration color in CSS. I would expect this to work just as described in the examples. Works well in HTML.

**Comment by mojavelinux** [comment]
I updated the link to point to MDN, which a the trusted source for information about CSS ;)

**Comment by r0ckarong** [comment]
Good to know =)

**Comment by mojavelinux** [comment]
There's also been interest in controlling the thickness of the line.

**Comment by mojavelinux** [comment]
I've submitted a PR with a prototype. See #1388.

Prawn uses the line width that is set on the document to draw the line for the underline and strikethrough styles. So we could solve the issue of the line being too thick simply by changing that value. I don't think that default value is used anywhere else.

**Comment by mojavelinux** [comment]
The problem with setting the line width globally to a value other than 1 is that the PDF generator than write the line width to the start of every content stream. That will break both tests and assumptions. So it's better to change the line width at the point of use.
