### ISSUE TITLE
Support running content side decision based on physical page number

### ISSUE THREAD

**Issue by fap-** [asciidoctor/asciidoctor-pdf#813]
We would like to have the option to decide whether a page is verto or recto based on the physical page number instead of the printed page number.
Setting the media to prepress is not an option for us since it bloats our large script(s) with too much empty paper.

I thought about 2 possible solutions:
1. make doctype book default to physical page numbers
2. introduce a global option

I'll attach a PR based on proposal 2.

**Comment by vogella** [comment]
@mojavelinux Could you review the PR? This would fix our issue that the page numbers are incorrect in the printed version.

**Comment by jnerlich** [comment]
I tested this solution and it works perfectly, it would be nice if this proposal would be merged.

**Comment by mojavelinux** [comment]
Glad to hear it. Thanks for testing, @jnerlich!

Right now, I'm heads down on getting 1.5.6 of core released, specifically the xref enhancements. As soon as I get that wrapped up, hopefully in the next few days, I'll turn my attention here.

**Comment by mojavelinux** [comment]
How about an attribute named `page-sides` that accepts one of two values:

* virtual - page side is based on page number label
* actual - page side is based on actual (i.e., physical) side

The default would be virtual for backwards compatibility.

**Comment by mojavelinux** [comment]
I was thinking about this a bit more and realized that if you wanted to invert the side, and the virtual and actual matched, you still wouldn't be able to do it. So I think we need four values:

* virtual
* virtual-inverted
* actual
* actual-inverted

I'll update the PR with this proposal.

**Comment by mojavelinux** [comment]
For now, I opted media=prepress out of this switch. (Instead, it always uses actual). If we decide that case should also be configurable, we can open the option to that scenario in the future.

**Comment by mojavelinux** [comment]
Once PR #814 is merged, I can release 1.5.0.alpha.16.

**Comment by mojavelinux** [comment]
I did a bit more research on this, and I think the attribute should be one of these two options:

* pdf-folio-distribution
* pdf-page-spread

The full (Latin) term for recto and verso is recto folio and verso folio. In this context, "folio" refers to the page (leaf) itself. What we're controlling is how the folio lines up with the pages of the PDF document, whether based on physical pages or page labels (default), and whether to start odd (default) or even.

The term page spread refers to the span from the left page to the right page when a book is open. In a sense, it's the inverse of a folio, because it spans across two sides.

I'm kind of leaning towards pdf-page-spread because it feels a bit more natural.

**Comment by mojavelinux** [comment]
Instead of `actual` and `virtual`, I'm also considering `physical` and `labels`. But I'm less convinced by that change.

**Comment by mojavelinux** [comment]
While the pdf-page-spread is tempting, I think the pdf-folio-placement attribute is more accurate. wdyt?

**Comment by fap-** [comment]
I'd also prefer `pdf-folio-placement`. Virtual and actual seems fine.
Couldn't we use `start-verso` and `start-recto` instead of the `ìnverted` options?

**Comment by fap-** [comment]
I just realised that you've already merged . Thank you.
I think we are happy with the given options, right? @jnerlich

**Comment by jnerlich** [comment]
If @fap- is happy, I'm happy. Will not be able to test until September due to vacations.

**Comment by mojavelinux** [comment]
Great. Thanks!
