### ISSUE TITLE
Table Column style asciidoc renders incorrectly when text wraps

### ISSUE THREAD

**Issue by BrianEmberling** [asciidoctor/asciidoctor-pdf#820]
I started by trying to get a "code" delimited block to work in a table cell, but 
even without that, this example renders badly.  (remove the "----" from the table
and it's still wrong).

Versions:   asciidoctor-pdf = 1.5.0.alpha15,    asciidoctor = 1.5.5.

% asciidoctor-pdf test.adoc -o test.pdf

```
My test doc
:doctype: article

[cols="a,a"]
|===
| col1 | col2
| abc  | text before

----
  Come and listen to my story about a man named Jed 
  A poor mountaineer, barely kept his family fed, 
  And then one day he was shootin at some food, 
  And up through the ground come a bubblin crude. 
  Oil that is, black gold, Texas tea.
----

  text after
|===
```

![image](https://cloud.githubusercontent.com/assets/28990171/26747082/684aaf7e-47a8-11e7-87f3-448f05c52a4a.png)

**Comment by mojavelinux** [comment]
It seems like the keep together logic isn't considering the width of the column.

**Comment by mojavelinux** [comment]
This turned out to be an easy fix. The width assignment wasn't working the way I expected inside the table cell.

**Comment by kral2** [comment]
I have similar issue when the asciidoc is rendered on GitHub.
Did you found a way to have the nested code block wrap & respect column width?

**Comment by mojavelinux** [comment]
> I have similar issue when the asciidoc is rendered on GitHub.

That's not in any way related to this converter. Please don't comment on closed issues. You can ask your question in the community chat at https://asciidoctor.zulipchat.com.
