### ISSUE TITLE
Tables no longer use frame and grid attributes at document level

### ISSUE THREAD

**Issue by idc101** [asciidoctor/asciidoctor-pdf#822]
(In alpha 11) This used to format all tables in the document with the correct frame and grid options:

```
= Table Test

:frame: topbot
:grid: cols

== Introduction

[cols="4,2,10",options="header",width="100%"]
|===
|Product |Version |Packages
|Product1 |1.20.0 |Package1
|Product2 |6.4.0 |Package2
|Product3 |5.26.0 |Package3
|===
```

![image](https://cloud.githubusercontent.com/assets/7188920/26782847/c48d78ce-4a38-11e7-8dba-0834cd5a6513.png)

This still works in *alpha 15* (but you have to specify the options on every table)

```
= Table Test

== Introduction

[cols="4,2,10",options="header",width="100%",frame="topbot",grid="cols"]
|===
|Product |Version |Packages
|Product1 |1.20.0 |Package1
|Product2 |6.4.0 |Package2
|Product3 |5.26.0 |Package3
|===
```

![image](https://cloud.githubusercontent.com/assets/7188920/26782782/828da96c-4a38-11e7-916e-c70522849081.png)

**Comment by mojavelinux** [comment]
We are moving away from block attributes inheriting from document attributes, at least under the same name. I'm willing to consider checking the document attribute if it's scoped. In this case, it would be `table-grid` and `table-frame`. Would that work for you?

I was testing this change in this case, but it's likely going to be part of a broader change for Asciidoctor 2.0.0.
