### ISSUE TITLE
Table caption is not be centered when the table is center.

### ISSUE THREAD

**Issue by ryuta46** [asciidoctor/asciidoctor-pdf#823]
I want a table and the caption to be center, so I write Asciidoc as follows.

```
.Table caption
[.center%header%autowidth]
|=======================
| H1 | H2 | H3
| Item1 | Item2 | Item3
|=======================
```

And I set align of caption to center in theme.yml
```
caption:
  align: center
```

This works fine when I use asciidoctor-pdf v1.5.0 alpha12.

<img width="1053" alt="2017-06-09 16 39 38" src="https://user-images.githubusercontent.com/18746908/26966678-140f0624-4d36-11e7-9c11-6007f8ce7eb9.png">

But when I use asciidoctor-pdf v1.5.0 alpha13 or later, the caption is placed right from the center.

<img width="1058" alt="2017-06-09 16 38 23" src="https://user-images.githubusercontent.com/18746908/26966689-1dca7a72-4d36-11e7-9f98-8388545574b5.png">

I think the fix of #469 is related. 
Is the caption placed in center between left edge of the table and right edge of the page?

**Comment by mojavelinux** [comment]
There's nothing that makes any sense about how the caption alignment for a table currently works. It needs to be rethought.

**Comment by mojavelinux** [comment]
This was fixed in beta.1. See #1138.
