### ISSUE TITLE
Move the title on the title page to the left

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor-pdf#824]
We would like to move the title (and other element of that bloc like the subtitle) of the cover to some pixels to the left. A property like `padding-left` or `marging-left` is missing.

![padding left example](https://user-images.githubusercontent.com/1222165/27068090-7ff2de62-500e-11e7-8750-34f6aca154ec.png)

As a workaround, we can align our titles to the right by using:

```
title_page:
  align: right
```

instead of

```
title_page:
  align: left
```

This way, we get something like this:

![align right](https://user-images.githubusercontent.com/1222165/27068097-89e05c4c-500e-11e7-9f33-777bc47eb3eb.png)

Sources to reproduce this example are pushed on the branch `theme-experiment` in the [asciidoctor-pdf-with-theme-example](https://github.com/jmini/asciidoctor-maven-examples/tree/theme-experiment) folder.

**Comment by mojavelinux** [comment]
You are correct that there is currently no such control. We support top, so it's logic that we'd support left and right too (absolute positions).

This may also relate to: #431.

**Comment by mojavelinux** [comment]
What do you think about being able to set the side margins on each element on the title page? It's already possible to set the top and bottom margins, so this seems like the simplest possible change.

See PR #1064.
