### ISSUE TITLE
Add a claim near to the Logo on the cover-page.

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor-pdf#825]
We would like to add a claim next to the logo on the cover-page. In my example:

> © The H company, {YEAR}

Preview:

![claim](https://user-images.githubusercontent.com/1222165/27094149-7577b524-5069-11e7-819f-68eefb20981d.png)

**Comment by mojavelinux** [comment]
This is something I strongly recommend adding to the background image. One way to make that dynamic is to make the background image an SVG so that you can easily write text into it in a pre-generate step.

Another idea is to use the title logo to insert this graphic, which would be possible once #431 is implemented.

Aside from a background or title logo, I don't think design elements should be handled by the theme.

**Comment by jmini** [comment]
The idea to use svg for the logo and to customize it during the build is great. I have tried it (see commit [9d7bc68](https://github.com/jmini/asciidoctor-maven-examples/commit/9d7bc68c79fa39dd83e7b3f739881a1c7ccbfcff)). The output looks like this:

![logo with claim](https://user-images.githubusercontent.com/1222165/27226475-8b35f564-529f-11e7-8e15-39007325173c.png)

I am wondering if there is any kind of limitation, because the original svg image looks like this:

![Preview of logo.svg](https://user-images.githubusercontent.com/1222165/27226489-9d263e6e-529f-11e7-836b-673a79715b49.png)

**Comment by jmini** [comment]
The idea to use svg for the logo and to customize it during the build is great. I have tried it (see commit [9d7bc68](https://github.com/jmini/asciidoctor-maven-examples/commit/9d7bc68c79fa39dd83e7b3f739881a1c7ccbfcff)). The output looks like this:

![logo with claim](https://user-images.githubusercontent.com/1222165/27226475-8b35f564-529f-11e7-8e15-39007325173c.png)

I am wondering if there is any kind of limitation, because the original svg image looks like this:

![Preview of logo.svg](https://user-images.githubusercontent.com/1222165/27226489-9d263e6e-529f-11e7-836b-673a79715b49.png)

**Comment by AlexanderZobkov** [comment]
asciidoctor-pdf uses [prawn-svg](https://github.com/mogest/prawn-svg) under the hood to render SVG images. it might just not support svg capabilies used in your svg image. I can suggest the following:

- Look inside your svg image and try to identify what SVG elements are used for these incorrectly rendered parts (Inkscape can help you)
- Replace them with SVG elements that supported by prawn-svg
- If nothing helps submit an issue for prawn-svg element

**Comment by mojavelinux** [comment]
The font used in the SVG has to match a font loaded in your theme. That's why it looks visually different. prawn-svg picks up any fonts loaded in Prawn (by way of the Asciidoctor PDF theme file). This is the same requirement anytime you use an SVG.
