### ISSUE TITLE
Allow images to be resolved from multiple locations

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#826]
Currently, it's necessary to get all images into the same catalog in order for the converter to locate and embed them into the output document. When dealing with images that come from multiple sources (for example, static vs generated), this requirement can be a burden.

Add the ability to resolve images from more than one location. This may be as simple as resolving images from both imagesdir and imagesoutdir, or we may allow a collection of catalog "roots" to be specified, in which images will be searched.

**Comment by vivien** [comment]
In the meantime, it seems like the [manual](https://asciidoctor.org/docs/user-manual/#setting-the-location-of-images) is wrongly stating that it is possible:
>  You can set the imagesdir attribute multiple times in your document. This technique is useful if you store images for different parts, chapters, or sections of your document in different locations.

**Comment by mojavelinux** [comment]
It is possible to use a different imagesdir for different images. It's just not possible to resolve the same image from multiple location. These are different scenarios.

**Comment by vivien** [comment]
Maybe I'm misunderstanding the usage. Here's an example:
````
/tmp/test $ find
.
./main.adoc
./img2
./img2/goat2.jpg
./img1
./img1/goat1.jpg
/tmp/test $ cat main.adoc
= Test

:imagesdir: img1
:imagesdir: img2

There's this goat image:goat1.jpg[] and this one image:goat2.jpg[].

/tmp/test $ asciidoctor main.adoc
````
which gives me this:
![](https://i.imgur.com/EEpjN8b.png)

**Comment by mojavelinux** [comment]
You are correct that you are not thinking about imagesdir the right way ;)

imagesdir is a setting on the document that applies at the time the image macro is visited. Thus, you can refer to the same image in two different directories using two different image references:

```
:imagesdir: img1

There's this goat image:goat.jpg[].

:imagesdir: img2

And there is this goat image:goat.jpg[].
```

But these references have to be in different blocks.

All that's happening underneath is that `imagesdir` is being prepended to the target value. It's not actually looking in two different places.

**Comment by mojavelinux** [comment]
By defining `imagesdir` twice, it's just like changing the value of a local variable.

**Comment by vivien** [comment]
OK so what is the proper syntax to specify multiple directories?

**Comment by mojavelinux** [comment]
There isn't one. That's why this issue exists ;)

**Comment by mojavelinux** [comment]
But we're still considering whether this is even the right thing to do. My thinking about imagesdir has evolved since I created this issue. In truth, imagesdir should be the base of all images, think of it like the images catalog. Then, if you have images grouped into folders, those folders would be part of the target. It's not bad to have directories in the target. You just don't want to have to set the *base* directory each time, which is an important abstraction to preserve for flexible deployment scenarios.

**Comment by vivien** [comment]
Sorry I missed one of your replies, hence my confusion about the syntax. I do agree with you about the global images catalog. It's easier to think in terms of deployment assets. This may require someone to "stage" the images before converting a document. For instance, you can use a theme from an external project, which has its own images (header, footer etc.). At least your document's images must be in an explicit subdirectory, so that you can overlay all images into a single images catalog before processing.

**Comment by pyssling** [comment]
Getting this issues fixed would be useful. Copying things around overly complicates the build system.

**Comment by tonk** [comment]
Although it is long standing I second this. We try to switch from something propriety to AsciiDoctor-pdf, but this is still keeping me back.

**Comment by mojavelinux** [comment]
You can allow images to be resolved from multiple locations using an extended converter. The method you are looking to override is `resolve_image_path`. All image resolution goes through this method. The method accepts a `relative_to` argument from which images are resolved. You can have this method retry if it cannot find the image in the first location and look for it in another. Or you could entirely rewrite the method.

```rb
class PDFConverterMultipleImageLocations < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def resolve_image_path node, image_path, image_format, relative_to = true
    if relative_to == true
      original_image_path = image_path
      unless File.file? image_path
        image_path = File.join 'images-1', original_image_path
        unless File.file? image_path
          image_path = File.join 'images-2', original_image_path
        end
      end
    end
    super
  end
end
```

We're not going to have the converter look for images in multiple places by default because that's not how the AsciiDoc language is designed. If it ends up defining multiple image locations, then this converter will implement that requirement at that time.
