### ISSUE TITLE
Changing Attributes in running Header & Footer

### ISSUE THREAD

**Issue by RobertdeLeeuw-IHomer** [asciidoctor/asciidoctor-pdf#827]
I'm building a document that consists of 3 parts.
I would like to have the name of the part in the header (or footer)
I can create a customer assidoc attribute, and place them at the start of every part:

`:my-document-part: Part1: Introduction`
`:my-document-part: Part2: Messages`
`:my-document-part: Part3: Datatypes`

I can then use this attribute in the header or footer.
But it will then show: `Part3: Datatypes` on every page of the document.
It looks like only the last value set to this attribute is used.

Is there another way to do this, that does work?

BTW: Thanks for creating and maintaining asciidoctor-pdf!!

**Comment by tkfu** [comment]
Have you considered using the built-in `{section-or-chapter-title}` attribute?

**Comment by RobertdeLeeuw-IHomer** [comment]
`{section-or-chapter-title}` will not work for me. All 3 parts have there own chapters and sections. That way the footer will change on almost every page.

**Comment by mojavelinux** [comment]
You can use `{part-title}` now. I just forgot to add it to the theming guide...I just added it.

**Comment by mojavelinux** [comment]
The only dynamic attributes you can use are the ones that are set by the converter. All other attributes are treated as static since the header and footer are written after the rest of the document is converted.

**Comment by RobertdeLeeuw-IHomer** [comment]
`{part-title}` only works with `:doctype: book`.
This has an unwanted side effect which I cannot seem to fix that easily: Now all chapter numbers are continuesly numberd. I want them to restart in every part.
So Part first Chapter starts with 1 again.

Any solutions for that? I could not find anything in the asciidoc and asciidoc-pdf documentation

**Comment by mojavelinux** [comment]
> `{part-title}` only works with `:doctype: book`.

correct

> Now all chapter numbers are continuesly numberd.

The fact that they were being reset is actually a side-effect of not setting the doctype correctly. Being able to control the numbering is an open issue in core. See https://github.com/asciidoctor/asciidoctor/issues/979

As a low-level workaround, you can reset the chapter-number attribute below each part. See https://github.com/asciidoctor/asciidoctor/issues/979#issuecomment-312588470 for an example. That should give you the behavior you are looking for.

**Comment by mojavelinux** [comment]
part-title is now documented. Therefore, I'm closing this issue. If you need further assistance, please reopen or submit a follow-up issue.
