### ISSUE TITLE
prawn-gmagick considered harmful

### ISSUE THREAD

**Issue by tkfu** [asciidoctor/asciidoctor-pdf#831]
Forgive the flippant title; I've now spent several hours tracking this bug down.
The bottom line is this: if you 
* use asciidoctor-pdf 
  * with prawn-gmagick installed 
    * on a file that includes PNG images containing an alpha channel

...you get a massively overweight PDF.
To minimally reproduce:
 Using [the attached test.png](https://user-images.githubusercontent.com/4501758/27843024-cb4cd41e-610f-11e7-85b1-90a6af63872c.png), run the following ruby script:

```ruby
require 'prawn'

pdf = Prawn::Document.new
pdf.text "Minimal test case"
pdf.image "test.png",:width => 500
pdf.render_file "test-prawn.pdf"

require 'prawn/gmagick'

pdf2 = Prawn::Document.new
pdf2.text "Minimal test case"
pdf2.image "test.png",:width => 500
pdf2.render_file "test-prawn-gmagick.pdf"
```
Then, look at the file sizes:
```
$ ls -lh *.pdf
-rw-rw-r-- 1 jon jon 884K Jul  4 23:16 test-prawn-gmagick.pdf
-rw-rw-r-- 1 jon jon  14K Jul  4 23:16 test-prawn.pdf
```
And check out the image object breakdown using the poppler suite:
```
$ pdfimages -list test-prawn.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    1804   499  rgb     3   8  image  no         7  0   260   260 3320B 0.1%
   1     1 smask    1804   499  gray    1   8  image  no         7  0   260   260 8869B 1.0%
$ pdfimages -list test-prawn-gmagick.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    1804   499  rgb     3   8  image  no         7  0   260   260 3528B 0.1%
   1     1 smask    1804   499  gray    1   8  image  no         7  0   260   260  879K 100%
```
Now, in this trivial case with a single tiny PNG using simple transparency, I added almost 900k to the pdf. When this first came up for real, I went from a 3MB pdf to an 80MB pdf.

I've uninstalled prawn-gmagick and everything's fine. (I only installed it in the first place because it was recommended in the README--I don't actually need it.) But I think it would be best to, at a minimum, make asciidoctor-pdf **not** use prawn-gmagick for png images. The file size penalty is pretty extreme.

**Comment by mojavelinux** [comment]
Would you be willing to submit this upstream? This is clearly an issue with prawn-gmagick. Asciidoctor PDF merely integrates with it (for the purpose of speeding up the process of embedding PNG). Thanks!

**Comment by tkfu** [comment]
I have opened up https://github.com/packetmonkey/prawn-gmagick/issues/14 over there, but I don't have high hopes that it'll get fixed--that repo hasn't been active for 2 years.

**Comment by mojavelinux** [comment]
Thanks Jon!

I'll do what I can do to encourage movement. It will certainly benefit this project, so we have a vested interest in seeing that happen.

**Comment by tkfu** [comment]
Huh, turned out to be trivially easy to fix, so I submitted a PR myself: https://github.com/packetmonkey/prawn-gmagick/pull/15

Let's see if the maintainer responds.

**Comment by mojavelinux** [comment]
That's fantastic news! Thanks!

**Comment by tkfu** [comment]
@mojavelinux There's been absolutely no movement on that PR for months now. At this point, I'm tempted to just fork the thing with a slightly different name and publish a new gem.

**Comment by mojavelinux** [comment]
@tkfu At this point, your best bet might be to just do that. Another option is to see if the prawn project would accept this gem so that other community members could collaborate on it. If you want to take that route, I recommend opening an issue in prawn to discuss.

**Comment by tkfu** [comment]
I sent an email to @packetmonkey directly, and he said he'd take a look at it in a few days.

**Comment by tkfu** [comment]
Closed by (finally) getting https://github.com/packetmonkey/prawn-gmagick/pull/15 merged. Users should make sure to update their local version of that gem to 0.0.9, but there's no change to the asciidoctor-pdf codebase required to benefit from this fix.

**Comment by mojavelinux** [comment]
@tkfu Thank you so much for your work and persistence to see this fix through. I really appreciate it!

I've added a note about the version to the README.
