### ISSUE TITLE
Index term in parentheses not rendering

### ISSUE THREAD

**Issue by ericis** [asciidoctor/asciidoctor-pdf#836]
I can't seem to get the text (term) to appear in both the index as well as in parentheses.

- `(term)` renders correctly, but doesn't appear in the index
- `((term))` appears in the index, but doesn't appear within parentheses
- `(((term)))` appears in the index and disappears from the text, because it processed as a concealed index term
- `\\(((term)))` almost works, but renders the backslash

I'm certain I'm just doing something wrong...

**Comment by ericis** [comment]
I stumbled across a working solution:
({zwsp}((term)){zwsp})

This renders correctly as "(term)" and displays in the index. It's horrible to maintain, but works.

Is there a better way?

**Comment by mojavelinux** [comment]
That doesn't seem right at all, and definitely not necessary. What does the index term you're trying to make look like in the context of a sentence?

**Comment by ericis** [comment]
Example: `The National Institute of Science and Technology ({zwsp}((NIST)){zwsp}) provides...`

Should add "NIST" to the index under "N" and also render: `The National Institute of Science and Technology (NIST) provides...`

This could be re-worded to `The National Institute of Science and Technology, or ((NIST)) provides...`, but I'm on a mission now 👍

**Comment by mojavelinux** [comment]
FYI: Only the first `{zwsp}` is required in your example.

In the short run, this is a textbook case of when you would use the indexterm2 macro.

```
The National Institute of Science and Technology (indexterm2:[NIST]) provides.
```

This makes the intent very clear to other authors (and yourself in the future) and gives you fine-grained control over how the content brackets are handled.

As for enhancements, it seems like we could make this work:

```
\(((NIST)))
```

If we make that change, to get the current behavior of the previous example, you'd instead have to type:

```
\(\((NIST)))
```

or

```
+(((NIST)))+
```

The first backslash escapes the outer bracket (the concealed term). The second one escapes the inner bracket (the flow term). That's different from AsciiDoc Python, but seems to make sense.

**Comment by mojavelinux** [comment]
Actually, better would be a double escape if you want to output literal triple brackets.

```
\\(((NIST)))
```

This is a tricky change, so this is just a proposal at this point.

**Comment by mojavelinux** [comment]
Actually, nevermind. Here's how I think it should be. To surround a visible index term in round brackets, you'd use:

```
\(((NIST)))
```

To output a term inside three round brackets, you'd use:

```
(\((NIST)))
```

The later already works, so we just need to change the behavior of the first one.

**Comment by mojavelinux** [comment]
I can confirm that I can make that work. It's a slight change to the syntax, but one that is very logical to me.

**Comment by mojavelinux** [comment]
However, this all needs to happen in core. I'll file a new issue to replace this one.

**Comment by mojavelinux** [comment]
Replaced by https://github.com/asciidoctor/asciidoctor/issues/2363.
