### ISSUE TITLE
Is :xrefstyle: working?

### ISSUE THREAD

**Issue by bameda** [asciidoctor/asciidoctor-pdf#837]
I have this

```asciidoc
:xrefstyle: short
:figure-caption: Figura

(...)

[[fig-control-chart]]
.Ejemplo de gráfico de control
image::kanban_control_chart.svg[Ejemplo de gráfico de control]

Un gráfico de control, como el de la <<fig-control-chart>>, muestra (...)
```
And I see the reference title instead of the signifier for the reference followed by the reference number.

In the html version of the document is working propperly.

**Comment by mojavelinux** [comment]
Can you verify the following two things are true?

* xrefstyle is defined in the document header
* you are using Asciidoctor PDF 1.5.0.alpha.16

**Comment by bameda** [comment]
Ouch! I was using `asciidoctor-pdf 1.5.0.alpha.15`. 

I've upgraded the gem and now is working like a charm.

Thank you very much for your support @mojavelinux

**Comment by mojavelinux** [comment]
Excellent!

The upgrade was required because xrefstyle requires coordination with the converter. In other words, the converter had to be updated to support it.

**Comment by pdb5627** [comment]
I have set ":xrefstyle: short" in my document header. It is looking correct with short references in my browser live preview of the document. However, I am getting basic style references in my PDF output.

My version of Asciidoctor and Asciidoctor-pdf:
`Asciidoctor PDF 1.5.0.beta.7 using Asciidoctor 1.5.5 [http://asciidoctor.org]`

Has there been a regression in this or some other change to how xrefstyle is supposed to work in asciidoctor-pdf?

**Comment by mojavelinux** [comment]
The version of Asciidoctor PDF you are using is correct, but the version of Asciidoctor you are using is too old. You'll need to upgrade to at least Asciidoctor 1.5.8, though 2.0.10 is preferred.

**Comment by pdb5627** [comment]
I uninstalled the Ubuntu 18.04 version and installed via gem, and now it seems to work. Thanks!

**Comment by mojavelinux** [comment]
Fantastic!
