### ISSUE TITLE
ToC with overlapping text and page numbers

### ISSUE THREAD

**Issue by GeraldLoeffler** [asciidoctor/asciidoctor-pdf#839]
The table of contents generated for my - admittedly very long - section headings shows those headings overlapping with the page numbers (see screenshot).
I'm on the latest release of asciidoctor-pdf and all dependencies.

<img width="790" alt="asciidoctor-pdf-toc-overflow" src="https://user-images.githubusercontent.com/1985716/29626941-aa1ad136-8830-11e7-8210-13c125cf8af7.png">

**Comment by franksauer** [comment]
I have the same problem. No solution for that? I could not find any possibilities to adjust the width of the section headings in the toc - only the indent can be changed in the theme.yml.

**Comment by mojavelinux** [comment]
This happens when section numbering is enabled. It seems we are not accounting for the width of the section number when determining where to initiate the wrap.

**Comment by mojavelinux** [comment]
Actually, that's not the case. It can run into the number even when sectnums are not enabled.
