### ISSUE TITLE
Differentiate theming for caption

### ISSUE THREAD

**Issue by ecki** [asciidoctor/asciidoctor-pdf#844]
The default theme for `caption` with the reduced italic font works well for table, listing and other labels. But inside normal text flow I would like to have captions slightly more prominent. (without using Hx)

Would it be possible to define an extra `caption_text` which be default inherits `caption` settings but allows to overwrite them?

**Comment by mojavelinux** [comment]
Captions can now be configured per category (table, listing, example, etc) as part of #307. The default caption is therefore the one that is used above paragraphs and open blocks.

Therefore, I'm going to marked this as a solved duplicate. If you find that the theming capabilities still can't meet your requirements, open a new issue with a specific example and we'll try to address it.
