### ISSUE TITLE
front-cover-image image path is not based on imagesDir

### ISSUE THREAD

**Issue by maybeec** [asciidoctor/asciidoctor-pdf#845]
As stated [here](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#theme-related-document-attributes), front-cover-image should resolve images based on the `imagesDir` configuration. The current behavior however is, that it depends on `baseDir` configuration.

What is the correct behavior? I would guess `imagesDir` should be the way to go.

**Comment by mojavelinux** [comment]
It uses imagesdir if you use the image macro syntax.

```
front-cover-image: image:cover.png[alt,width,height]
```

otherwise, yes, it is resolved relative to the pwd, which is the baseDir if set.

**Comment by maybeec** [comment]
I did it as you said:  `:front-cover-image: logo.png[pdfwidth=5in,align=center]`

However, it resolves from `baseDir` rather than `imagesDir`. As we implemented some custom pre-processing, our `imagesDir` is not sub path of `baseDir`. Therefore, I can simply determine what path is used for image resolution.
Interestingly, I tried to navigate to the real image location in the front-cover-image config by a relative path using `../`. The outcome was, that although the path was finally correct, the logo could not be inserted with the error message, it does not exist or is not readable.

**Comment by maybeec** [comment]
Just found a310307f6112cafa524a8fbb4b62ed028a31fd7b where it is also stated in the commit message.

**Comment by mojavelinux** [comment]
You are missing a part. It should be:

```
:front-cover-image: image:logo.png[pdfwidth=5in,align=center]
```

Notice the "image:" prefix.

The reason we do this is because we can't know this attribute value requires special handling unless it is wrapped in the image macro.

**Comment by maybeec** [comment]
Oh man... stupid me... sry for that

**Comment by mojavelinux** [comment]
No worries. I'm glad you got it sorted. I updated the theme guide to explain this is more detail.
