### ISSUE TITLE
Heading levels more than 2 do not occur in outline

### ISSUE THREAD

**Issue by maybeec** [asciidoctor/asciidoctor-pdf#847]
Heading levels more than 2 are not shown in PDF outline.
Although the headings are correctly numbered in the document like 

1.1.
1.1.1.
1.1.2.

, you will just see 

1.1. 

in the outline resp. document navigation.

**Comment by mojavelinux** [comment]
Check your toclevels attribute. It may be set too low. See http://asciidoctor.org/docs/user-manual/#user-toc-levels

**Comment by maybeec** [comment]
Thanks! I just set `:secnumlevels:`
