### ISSUE TITLE
Callouts only work up to 20

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-pdf#848]
When exporting to PDF, the callouts only work up to 20. If you have more, the numbers are empty:

![image](https://user-images.githubusercontent.com/1115823/30153280-61fe5382-93b6-11e7-85c4-2503910e7ed8.png)

You can test it with this document (I renamed it to .txt to be able to upload it to GitHub): [callout-test.adoc.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/1283924/callout-test.adoc.txt)

This is the PDF that gets generated: [callout-test.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/1283922/callout-test.pdf)

The default html5 backend renders it fine. Also the IntelliJ plugin renders it fine as well.

Version in use:
```
Asciidoctor PDF 1.5.0.alpha.15 using Asciidoctor 1.5.6 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]) (lc:US-ASCII fs:US-ASCII in:- ex:US-ASCII)
```

**Comment by wimdeblauwe** [comment]
Tested with a latest versions as well, but same issue.

```
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]) (lc:US-ASCII fs:US-ASCII in:- ex:US-ASCII)
```

**Comment by mojavelinux** [comment]
Unicode only defines circled numbers up to 20. I don't know of way to get circled numbers higher than that at the moment.

**Comment by wimdeblauwe** [comment]
What about http://graphemica.com/%E3%89%93 ?

**Comment by mojavelinux** [comment]
Oh, now I remember what it is. After 20 the sequence jumps somewhere else. I'll have to explore if I can follow where it leads.

**Comment by mojavelinux** [comment]
I think we just need to bite the bullet and resolve #133. The reason is, we have to jump around in the range and in order to know when to jump, we need to make it configurable. So we might as well let all the glyphs be specified.

**Comment by mojavelinux** [comment]
Now that #133 is resolved, it's possible to have an infinite number of callout numbers. You just need to specify the ranges you want to use in the theme file.
