### ISSUE TITLE
Set page width only

### ISSUE THREAD

**Issue by Kelvinlinzer** [asciidoctor/asciidoctor-pdf#851]
Hi,

I am trying to generate some shopping receipts pdfs, which has a fixed width, but no fixed height. Is there a way to set the page width only?

Thanks.

**Comment by mojavelinux** [comment]
I do not think that is possible. At least, I have no idea how it would be done. PDF is a fixed canvas medium.

**Comment by Kelvinlinzer** [comment]
Thanks for you information. I will try to calculate the height of the document before rendering the page.

Close the issue.
