### ISSUE TITLE
Description list term_font_style not respected for literal (mono) text

### ISSUE THREAD

**Issue by ctargett** [asciidoctor/asciidoctor-pdf#854]
We're using the description list for parameter names since we like it better than putting them in huge tables. Since these are parameters, we use monospace text for the names. When we generate the PDF, all description_list terms that aren't monospace are bold, but those that are monospace are not. This makes them get a little lost on the page

The font we're using for monospace is Inconsolata, and we have a bold definition for it.

Screenshots of the difference:

<img width="816" alt="non-monospace-descriptionlist" src="https://user-images.githubusercontent.com/450148/30764881-85197452-9fb2-11e7-940e-30d40a2524c9.png">

<img width="811" alt="monospace-descriptionlist" src="https://user-images.githubusercontent.com/450148/30764887-8a95af18-9fb2-11e7-863c-8a2858a5c37c.png">

We had the same problem with our HTML output (using jekyll-asciidoc), but that was easily fixed via CSS. There isn't such an obvious fix here, though. Any ideas?

**Comment by janosvitok** [comment]
Can you post source?

**Comment by ctargett** [comment]
Sure, all our source is in the Apache Lucene/Solr project, so open to everyone to read. The example above with monospace is from this file: https://github.com/apache/lucene-solr/blob/master/solr/solr-ref-guide/src/highlighting.adoc.

If you meant our PDF theme, it's in https://github.com/apache/lucene-solr/blob/master/solr/solr-ref-guide/src/pdf/themes/refguide-theme.yml.

**Comment by mojavelinux** [comment]
The reason behind this actually fairly complicated. When the text has inline formatting, the style set in the theme is not being passed on. I came up with a fairly simple workaround that uses explicit formatting, though I'd like to take this a bit further and fix the API.

See #862.

**Comment by mojavelinux** [comment]
Interestingly, there's an example of this in the chronicles example document. I just never noticed it.

**Comment by ctargett** [comment]
Thanks so much, I'll be excited to try it out. We use this in a ton of places.
