### ISSUE TITLE
Malformed URLs lead to failure to correctly parse the containing paragraph

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor-pdf#861]
Trying to port the progit 2 book to full asciidoctor edition chain, the compilation shows the following error:

```± bundle exec asciidoctor-pdf progit.asc  
Failed to parse formatted text: Maintenant que votre projet est hébergé sur GitHub, vous pouvez donner l&#8217;URL à toutes les personnes avec lesquelles vous voulez partager votre projet. Chaque projet est accessible via HTTP par <code><a href="https://github.com/&lt;utilisateur&gt;/&lt;nom_du_projet&gt" class="bare">https://github.com/&lt;utilisateur&gt;/&lt;nom_du_projet&gt</a>;</code> et via SSH par <code>git@github.com:&lt;utilisateur&gt;/&lt;nom_du_projet&gt;</code>. Git peut récupérer et pousser en utilisant les deux URL mais l&#8217;accès est contrôlé sur la base des paramètres d&#8217;authentification de l&#8217;utilisateur qui s&#8217;y connecte.
```
And the resulting PDF shows:
![image](https://user-images.githubusercontent.com/156172/31888964-52988702-b7fe-11e7-95d5-f1bd05f8d94d.png)

With the original text:
```
Maintenant que votre projet est hébergé sur GitHub, vous pouvez donner l'URL à toutes les personnes avec lesquelles vous voulez partager votre projet. Chaque projet est accessible via HTTP par `https://github.com/<utilisateur>/<nom_du_projet>` et via SSH par `git@github.com:<utilisateur>/<nom_du_projet>`. Git peut récupérer et pousser en utilisant les deux URL mais l'accès est contrôlé sur la base des paramètres d'authentification de l'utilisateur qui s'y connecte.
```

Note that the ebook compilation shows no warning, but the output also contains semi-colons not included in the original text. This URL is not intended to be well-formed, is there any way to indicate that it should be rendered as-is?

**Comment by mojavelinux** [comment]
You are being bitten by the change in syntax described on the migration page:

http://asciidoctor.org/docs/migration/

Specifically, backticks only format text as monospace. They do not prevent substitutions from being applied to the text. If you want to prevent substitutions (i.e., literal text), then you need to use the following syntax:

```
`+text+`
```

The plus enclosure prevents substitutions, while the backticks make the text monospace.

This is a difference from AsciiDoc Python. If you don't want that difference, you can enable compat mode.

Here's how the passage would be formatted using the modern syntax:

```
Maintenant que votre projet est hébergé sur GitHub, vous pouvez donner l'URL à toutes les personnes avec lesquelles vous voulez partager votre projet. Chaque projet est accessible via HTTP par `+https://github.com/<utilisateur>/<nom_du_projet>+` et via SSH par `+git@github.com:<utilisateur>/<nom_du_projet>+`. Git peut récupérer et pousser en utilisant les deux URL mais l'accès est contrôlé sur la base des paramètres d'authentification de l'utilisateur qui s'y connecte.
```

**Comment by jnavila** [comment]
Thank you very much for the analysis of the issue. With this latest fix, the book can be compiled without warnings!

**Comment by mojavelinux** [comment]
:tada:
