### ISSUE TITLE
asciidoctorj-pdf does not render images with special chars in title

### ISSUE THREAD

**Issue by matthiasbalke** [asciidoctor/asciidoctor-pdf#863]
*I moved this one from https://github.com/asciidoctor/asciidoctorj-pdf/issues/12.*

When using brackets within the title of an image, the image is not getting rendered with asciidocj-pdf.

```adoc
[[img.some-reference]]
image::images/image.png[title="Schaltfläche [Filter]"]
```
As soon as I remove the brackets it's rendering the image just fine. Also I can escape the last bracket, which also renders fine.
```adoc
[[img.some-reference]]
image::images/image.png[title="Schaltfläche [Filter\]"]
```

The image is also displayed fine without escaping when using the IntelliJ preview. 

**versions**
asciidoctor-gradle-plugin=1.5.3
asciidoctorj=1.6.0-alpha.4
asciidoctorj_pdf=1.5.0-alpha.15
AsciiDoc (IntelliJ plugin)=0.19.1

**Comment by mojavelinux** [comment]
I think this may have been an issue in core that has since been resolved. If you're still able to reproduce with AsciidoctorJ 1.6.0-alpha.7 and AsciidoctorJ PDF 1.5.0-alpha.16, then feel free to reopen.
