### ISSUE TITLE
Set size of image icons in admonition blocks

### ISSUE THREAD

**Issue by jonsfischer** [asciidoctor/asciidoctor-pdf#865]
Hi,

i'm trying to set up a template with a lot of different admonition icons. I did the following in the header:

:iconsdir: icons
:icons:

After that i am able to set the icons for the default admonition blocks by putting for example warning.png into the icons directory. This works like a charm.

And with the following code i'm able to replace the icons at the admonition blocks to custom ones.

[icon=m001]
NOTE: Here is some note!

After checking the code, i found out that it is possible to control the icon size of image icons in admonition blocks by following key:

admonition:
  label:
    min_width: 70

But if there are blocks with more or less text in it, the icon size will be reduced sometimes because of line 601 in converter.rb. This leads to different icon sizes which looks a bit ugly if there are more than one admonition block on a page with almost identical icons but different sizes.

**Comment by mojavelinux** [comment]
You have correctly identified that the admonition_label_min_width currently controls the size of the icon. (There's a note in the code to introduce a dedicated property, but it's not yet implemented).

The behavior you're describing about the icon being reduced to fit the size of the box is unfortunately just a limitation of the renderer and the design. The image has to be made to fit within the available space. My suggestion is to either add more content to your admonitions or make the line height bigger.
