### ISSUE TITLE
SVG is all black in PDF

### ISSUE THREAD

**Issue by chybz** [asciidoctor/asciidoctor-pdf#868]
Hi,

when converting to PDF, all my railroad diagrams (generated with [GrammKit](https://github.com/dundalek/GrammKit)) are all black, while perfectly fine in HTML5.

Thanks for any help !

![html-svg](https://user-images.githubusercontent.com/288894/33067650-180dde9e-ceaf-11e7-890b-535587ce6c42.png)
![pdf-dark-svg](https://user-images.githubusercontent.com/288894/33067651-182662de-ceaf-11e7-873b-c9eeb6d33055.png)
[query_format.svg.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/1490940/query_format.svg.txt)

**Comment by AlexanderZobkov** [comment]
Hello, 
Looking into the attached svg file I see that colors, labels and some other parts of the diagram are formed by def/style/css section of the svg file. You can try to delete def/style xml section from the svg file and you will be able to the diagram in all black :smile: 

Ascidoctor-pdf uses prawn-svg to render svg into pdf and it has limited support for css. 
I would say you have the following alternatives:
* Submit an issue to prawn-svg, probably little adjustments are needed
* Convert svg into png
* Configure GrammKit to avoid using css and generate "pure" SVG files

**Comment by mojavelinux** [comment]
Absolutely correct. Prawn SVG only supports "pure" SVGs, not the SVG/HTML/CSS hybrid that are sometimes targeted for web viewing. Diagram tools are notorious for creating non-standard SVGs.

**Comment by mojavelinux** [comment]
The problem is that prawn-svg doesn't support colors in hsl. If you choose another color system, it will work. In your case, the fill should be:

```css
svg.railroad-diagram rect {
  stroke-width: 3;
  stroke: black;
  fill: rgb(204,255,204);
}
```

If you want prawn-svg to support hsl, file an issue here: https://github.com/mogest/prawn-svg/issues
