### ISSUE TITLE
Ability to start page numbering from title page

### ISSUE THREAD

**Issue by terba** [asciidoctor/asciidoctor-pdf#869]
I would like to ask for the ability to change the page numbering scheme. I could not find any info on how to change this. In my country we use the physical page numbering scheme, so the title page is Nr. 1, first TOC page is Nr. 2 and so on. 

It is annoying also, that I have to calculate physical page numbers for printing only a part of a document. This is also stated in the README file.

I never understood why is page numbering made like this, but I'm just a software engineer :)

Thanks in advance!

**Comment by michael-o** [comment]
From a typographical approach, you always number non-content pages with Roman numbers and start content with European numbers from 1. That has been the regular case in every professional environment. LaTeX does the same, every book applies the same scheme.

**Comment by terba** [comment]
Thanks for your answer! I accept that in western countries this is the scheme, but not everywhere in the world and not for every document type. In LaTeX, Framemaker and [SDF](http://cpansearch.perl.org/src/IANC/sdf-2.001/doc/paper/sdfintro.html) I was able to change this.

**Comment by michael-o** [comment]
And this is different in Hungary? You don't consider Hungary being part of the Western world?

**Comment by terba** [comment]
There are 3 books (HU literature) on my nightstand currently: all of them is numbered from the title page, so content starts on page 7 in two and on page 5 in one. On the title page(s) the page number is not printed, but counted. So this is real page number, not an ID of the page.
I mean western in thinking. Like reverse name order, or addresses and date formats not in top-down scheme.

**Comment by michael-o** [comment]
Hugary is progressive in many ways. 
[Here](https://en.wikipedia.org/wiki/Page_numbering#Numbering_conventions) is a good read on it which basically applies to English and German publications. Out of curiousity, do you have any reference for Hungarian?

**Comment by terba** [comment]
I don't have and was not able to find one on the net.

**Comment by mojavelinux** [comment]
I believe this was implemented by #1041. The key is page_numbering_start_at. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-page for details.
