### ISSUE TITLE
Xref to a heading with icon results in error "not a known font".

### ISSUE THREAD

**Issue by struwwelPiet** [asciidoctor/asciidoctor-pdf#874]
When I reference a heading with a Font Awesome icon, i get the error "is not a known font" while rendering.

Here is what I tried:

**Working:**
```
[[reference]]
== Heading

Text <<reference, icon:cogs[] Heading>>
```

**Not working:**
```
[[reference]]
== icon:cogs[] Heading

Text <<reference>>
```

Both examples should give the same result. Or am I doing something wrong?

**Comment by mojavelinux** [comment]
While I agree this is a rendering bug, you probably don't want the icon showing up in the reference anyway. Therefore, you should set the reftext for the section title.

```
[[reference,Heading]]
== icon:cogs[] Heading

Text <<reference>>
```

**Comment by mojavelinux** [comment]
This turned out to be the same issue as #956. It's now fixed in master.
