### ISSUE TITLE
rouge theme selection

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#876]
Is it possible to select theme for rouge syntax highlighter?

There is asciidoctor-rouge extension that I use to emit highlighted code to HTML and it uses:

`:rouge-theme: github
`
Obviously it doesn't work with asciidoctor-pdf...

**Comment by mojavelinux** [comment]
Yes. You can set the Rouge theme. The correct attribute name is `rouge-style`. Please see the docs.

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#source-highlighting-theme

**Comment by habamax** [comment]
thx!

I am kind of embarassed -- it is not the first time I look for smth in the asciidoctor-pdf docs and can't find what I need although it is in the docs.

**Comment by mojavelinux** [comment]
Trust me, I understand. In fact, I think this information needs to be in the main README. I'll make a note to add it there too.
