### ISSUE TITLE
Generated PDF print page selection is not working

### ISSUE THREAD

**Issue by rrozestw** [asciidoctor/asciidoctor-pdf#88]
Default - printing all pages in a PDF file - works fine (both Foxit and Adobe Reader).

Selecting subset of pages to print (e.g. skipping cover page in my case) won't work - all pages after  ToC - share the same "internal" page number (2 in my case). Result is that you can only the print first "real" page.

Page numbers rendered on the bottom are numbered correctly.

**Comment by mojavelinux** [comment]
This seems to have something to do with the roman numeral page numbers we're using for front matter pages. I thought I had it right, but clearly it's throwing off the counts. This is either a bug / missing feature in Prawn or something about the metadata we aren't getting right. It requires low-level understanding of PDF metdata.

Here's the area of the code that could be problematic: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L1175

A simple workaround we could implement is to add an option to disable the use of roman numerals for front matter pages and just number pages normally starting at 1.

**Comment by mojavelinux** [comment]
I think this will be resolved as part of 1.5.0.alpha.13. I found out that it's necessary to assign a label to every "front matter" page in the document outline so that the reader knows when to start counting content pages.

**Comment by mojavelinux** [comment]
I'm going to mark as resolved. Please test with 1.5.0.alpha.13 and reopen if this is still a problem.

**Comment by mojavelinux** [comment]
I want to add that the page numbers in the print dialogue are not going to correspond to the page number labels. Rather, the print dialogue counts physical pages. (It doesn't know about or understand the labeled page numbering). Therefore, you have to add the number of front matter pages to the page number(s) specify in the print dialog in order to print the correct range of labeled pages.

**Comment by mojavelinux** [comment]
I'll add this point in the README.

**Comment by mojavelinux** [comment]
This is related to #458 and was resolved as part of the fix for #383.
