### ISSUE TITLE
Setting align: left for base font still renders justified

### ISSUE THREAD

**Issue by elisawyer** [asciidoctor/asciidoctor-pdf#880]
The doc for asciidoctor-pdf indicates that left aligned is default for the base font, however I have only seen justified.

I have a request for a document with left alignment. I have tried setting align: left and also leaving the field blank, and in both cases the pdf still renders text as justified.

**Comment by mojavelinux** [comment]
I believe this works in the latest version. If not, please reopen and submit a theme and sample document I can test.

The syntax should be:

```
base:
  align: left
```
