### ISSUE TITLE
Error message when I try "$asciidoctor-pdf basic-example.adoc" 

### ISSUE THREAD

**Issue by mrbig033** [asciidoctor/asciidoctor-pdf#883]
MX-Linux 17 upgrade to Debian Testing. 
`ruby 2.3.3p222` . 
Installed according to [this tutorial](http://asciidoctor.org/docs/asciidoctor-pdf/).
**bash**:
```
$ asciidoctor-pdf basic-example.adoc
uninitialized constant PDF::Core::Page::ZERO_INDENTS
Use --trace for backtrace
```

**Comment by mojavelinux** [comment]
I believe this will be resolved by the upgrades made in the upcoming 1.5.0.alpha.17 release. Please reopen that turns out not to be the case.
