### ISSUE TITLE
Unable to generate PDF if pygments is chosen as the source highlighter.

### ISSUE THREAD

**Issue by Muzamri** [asciidoctor/asciidoctor-pdf#884]
Hi,

This is actually a cross-post, the original issue can be found [here](https://github.com/asciidoctor/docker-asciidoctor/issues/68).

Basically, I am having problems generating a PDF when using pygments as the source code highlighter.

Thank you.

**Comment by mojavelinux** [comment]
Pygments can sometimes return nil if the underlying process fails or dies. We need to guard against that like we did in Asciidoctor core. See https://github.com/asciidoctor/asciidoctor/pull/2342.
