### ISSUE TITLE
white space around SVG generated from packetdiag

### ISSUE THREAD

**Issue by crumgary** [asciidoctor/asciidoctor-pdf#886]
This seems to only happen when processing a PDF and not with html processing.

It looks like when using packetdiag in SVG mode, there is whitespace around the image.  I haven't done a lot of experimenting, but when processing the pdf, it seems like the image is isolate on the page.  PNG mode seems to work and just doing a standard SVG with 'image' seems to work.  

Here's the code I've been trying:

```
= Packet Diag Test: Blank Space Issue in PDF
Test User
:doctype: book
// Settings:
:experimental:
:reproducible:
:listing-caption: Listing
:sectnums:
:toc: []
:toc-placement: preamble
:toclevels: 4
:icons: font
:numbered:
:website: github.com
:allow-uri-read:
ifdef::backend-pdf[]
:source-highlighter: rouge
endif::[]


== Packetdiag with png

With png formatting, the whitespace is correct between here and diagram


[packetdiag, testing, png]
....
packetdiag{
  colwidth = 32
  node_height = 72

  0-15: Source Port
  16-31: Destination Port

}
....

The whitespace is also ok after the diagram.




== Packetdiag with svg

With SVG mode - which is currently required when using rotate with packetdiag, There seems to be a lot of whitespace between this text and the diagram


[packetdiag, testing, svg]
....
packetdiag{
  colwidth = 32
  node_height = 72

  0-15: Source Port
  16-31: Destination Port

}
....

And a lot of whitespace after the diagram and before this text

But only in with PDF, html is ok.

== Using SVG as Image works

Test Text

image::https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg[Tux,100,100]


And more text
```

**Comment by mojavelinux** [comment]
The problem here is that Prawn SVG does not respect the viewBox when an explicit width is not specified. The workaround is to set the width on the block.

```
[packetdiag, testing, svg, pdfwidth=100%]
....
packetdiag{
  colwidth = 32
  node_height = 72

  0-15: Source Port
  16-31: Destination Port

}
....
```

You should find that setting this attribute resolves the problem you're observing.

**Comment by mojavelinux** [comment]
The general rule of thumb is, when in doubt, set a width (or pdfwidth). This gives you more control anyway.

**Comment by mojavelinux** [comment]
This can be resolved by upgrading prawn-svg. I will make that upgrade as part of the next release.
