### ISSUE TITLE
{checkedbox} and {uncheckedbox} are rendered as empty squared brackets  [ ]

### ISSUE THREAD

**Issue by kiptix** [asciidoctor/asciidoctor-pdf#889]
{checkedbox} and {uncheckedbox} are Rendered as empty squared brackets  [ ]
[✔] -> [  ]
[✗] -> [  ]

**Comment by mojavelinux** [comment]
The default font does not include these glyphs. However, you can use the checked and unchecked ballot boxes, which the default font does support.

☑
☐

**Comment by mojavelinux** [comment]
It's also possible to use checklists, which are supported:

```
* [x] checked
* [ ] unchecked
```
