### ISSUE TITLE
Font Awesome fixed width icons not rendering

### ISSUE THREAD

**Issue by berzley** [asciidoctor/asciidoctor-pdf#890]
Example of source
```asciidoc
Icon 1: icon:magic[]
Icon 2: icon:magic[fw]
```

In the above example only the first icon is generated. The second one, with `fw` (fixed width) set, displays no icon at all.

This doesn't look to be an intentional behavior. If fixed width cannot be applied in PDF rendering the flag should be ignored.

**Comment by mojavelinux** [comment]
I've proposed a more complete solution. You can test it using the following:

```
:icons: font

a icon:gitlab[fw] b
a icon:bolt[fw] b
```

a and b should be aligned.
