### ISSUE TITLE
Metadata attributes double quoted

### ISSUE THREAD

**Issue by ilvetz** [asciidoctor/asciidoctor-pdf#896]
When I add author's metadata to PDF documents, using `authors` attribute which is a clone of `author`, I get a double quoted field. The `keywords` attribute have the same behavior too. Others (subject) do not.

I think a better option is having no double quotes for every metadata field.

### Example

```
:author: I am the author, Company ABC
:authors: {author}
:keywords: docis:confidential;principles;standard;
```

### Output

A PDF document with:

Author metadata set to `"I am the author, Company ABC"`
Keywords metadata set to `"docis:confidential;principles;standard;"`

**Comment by mojavelinux** [comment]
I don't understand what you're referring to. Asciidoctor PDF does not put quotes around metadata fields. If the quotes are being added, it's being done so by the PDF client.

Here's the relevant snippet from the generated PDF file to show what Asciidoctor PDF outputs:

```
<< /Title (Document Title)
/Author (I am the author, Company ABC)
/Keywords (docis:confidential;principles;standard;)
/Creator (Asciidoctor PDF 1.5.0.alpha.17.dev, based on Prawn 2.2.2)
/Producer (I am the author, Company ABC)
/ModDate (D:20180311032432-06'00')
/CreationDate (D:20180311032432-06'00')
```

This is the formatting recommended by the PDF spec.

**Comment by mojavelinux** [comment]
I don't believe this is a valid bug report. If you can demonstrate the problem, please reopen.
