### ISSUE TITLE
Allow theme to control properties (width, color, and, style) of top, right, bottom and left table borders separately

### ISSUE THREAD

**Issue by zeusttu** [asciidoctor/asciidoctor-pdf#902]
Currently, a theme treats all borders of a table the same. You can specify one `border_style` and one `border_width`, which subsequently apply to *all* borders. I would like the ability to specify these separately for the top, bottom, left and right borders. I envision two possible ways to achieve this:

* Through individual attributes (`border_style_top`, `border_style_bottom` etc.)
* By passing a list to the existing attributes (e.g. `border_style: [solid, none, solid, none]`), where it is probably best to keep the order consistent with the order in which you specify page margins, so top - right - bottom - left.

I would be satisfied with either so I will leave it up to whoever will implement this to choose one.

**Comment by mojavelinux** [comment]
Are you looking to change the color, or turn borders on and off? If it's the latter, you can already do that using AsciiDoc. See https://asciidoctor.org/docs/user-manual/#table-borders.

**Comment by zeusttu** [comment]
That is actually part of what I wanted when I created this enhancement proposal. I would however still like the ability to have dotted row separators while having thicker horizontal table borders (and the top one thicker than the bottom one).

For now I abandoned the idea of going from Asciidoc directly to PDF with Asciidoctor-PDF. Instead I now use Asciidoctor to go from Asciidoc to HTML, CSS to style the HTML and a PDF printer to go from styled HTML to PDF, which works very well.

As is probably already clear, the document I use this for is one that has to obey some very specific styling requirements in order not to look out-of-place next to similar documents created in word processors. In hindsight I see that this is probably not a primary use case of Asciidoctor-PDF, and I understand if it is not one you wish to support, in which case you can close this enhancement proposal.

**Comment by mojavelinux** [comment]
Thanks for clarifying! Exactly the input I was looking for.
