### ISSUE TITLE
[Enhancement] Style horizontal and vertical table grids separately

### ISSUE THREAD

**Issue by zeusttu** [asciidoctor/asciidoctor-pdf#903]
Currently, a theme treats the horizontal and vertical grid lines of a table the same. You can specify one `grid_style` and one `grid_width`, which subsequently apply to *both* grids. I would like the ability to specify these separately for the horizontal and vertical grids. I envision two possible ways to achieve this:

* Through individual attributes (`grid_style_horizontal`, `grid_style_vertical` etc.)
* By passing a list to the existing attributes (e.g. `grid_style: [solid, none]`). Intuitively I would probably expect to specify the horizontal border first and the vertical one second.

I would be satisfied with either so I will leave it up to whoever will implement this to choose one.

Related to #902, and probably similar in terms of implementation.

**Comment by mojavelinux** [comment]
This behavior was implemented in the fix for #1875.
