### ISSUE TITLE
Several entries on same page results in index showing same page several times

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-pdf#904]
If an entry appears several times on the same page, the page should still be listed just once in the index for this entry. Otherwise, we get this strange looking result:

![clipboard01](https://user-images.githubusercontent.com/1244100/39621106-d581e970-4f8d-11e8-9a3c-488684f055c2.png)

(page 38 is mentioned twice, once would have been enough).

**Comment by mojavelinux** [comment]
Hmm. That's strange. There's actually logic to avoid duplicates. I wonder why it's slipping in. Do you have a single-page document that demonstrates the error you can share?

**Comment by seinecle** [comment]
Yes, here is a file. It differs from the one I used only in the fact that I deleted `image:: ` lines which refer to local pics.
[test index.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/1983366/test.index.txt)

**Comment by seinecle** [comment]
Added `:media: prepress`, worked great! Thx!

**Comment by mojavelinux** [comment]
Glad to hear it!
