### ISSUE TITLE
{counter: attribute} counts up by 2 when it's used inside admonition

### ISSUE THREAD

**Issue by aokiplayer** [asciidoctor/asciidoctor-pdf#907]
Counter value increments by 2 when I use {counter: attribute} inside admonition like NOTE, CAUTION.
I expected 0, 1, 2, 3, 4, 5. But actual values are 0, 1, 2, 4, 6, 7.

Source
```
:my-count: 0

== Initial value
Current number is {my-count}.

== One is expected
Current number is {counter:my-count}.

== Two is expected
Current number is {counter:my-count}.

== Three is expected
NOTE: Current number is {counter:my-count}.

== Four is expected
CAUTION: Current number is {counter:my-count}.

== Five is expected
Current number is {counter:my-count}.
```

Output
[example.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/2021269/example.pdf)

**Comment by mojavelinux** [comment]
This is due to the fact that admonitions blocks are rendered twice, once in a scratch document, then once in the main document.

There isn't an easy solution for this for counters since counters can be any attribute. But what could be done is to snapshot the attributes before rendering in the scratch document and restoring them afterwards. That feels a bit crude, but I can't think of another way right now.

Btw, this is going to be true for any block that uses the scratch document to determine its own dimensions.

**Comment by znerd** [comment]
To me (and my use-cases) this is a critical issue, as it basically stops me from being able to use counters when targeting PDF output.

**Comment by znerd** [comment]
@mojavelinux : That sounds like a useful workaround for the time being – thanks!

**Comment by aokiplayer** [comment]
My current workaround is same as @mojavelinux 's one.

**Comment by mojavelinux** [comment]
> it appears to be significant that the {counter2} macro is invoked outside of a rendered block.

You are exactly correct. If you look closely, that's what I was suggesting.

**Comment by mojavelinux** [comment]
Note that this side effect will mostly go away once we switch to breakable blocks by default in Asciidoctor PDF 2. The converter will not attempt to dry run the block and thus it won't be rendered multiple times. Unbreakable blocks will still be affected...and there's no much we can do to change that (at least not in this converter).

**Comment by mojavelinux** [comment]
This is now solved in Asciidoctor PDF 2, so I'm going to mark this as a duplicate with the label 2.0.0.

The following document renders as expected:

```
== Initial value

Current number is {counter:my-count:0}.

== One is expected

Current number is {counter:my-count}.

== Two is expected

Current number is {counter:my-count}.

== Three is expected

NOTE: Current number is {counter:my-count}.

== Four is expected

CAUTION: Current number is {counter:my-count}.

== Five is expected

Current number is {counter:my-count}.
```

Keep in mind that there are still known limitations with using counters if the text that contains the reference is converted multiple times. The scope of this fix is to avoid this side effect as a result of the converter arranging the block using the scratch document.
