### ISSUE TITLE
Unknown type of color: "transparent" for a code block that spills over

### ISSUE THREAD

**Issue by sytzek** [asciidoctor/asciidoctor-pdf#909]
If a code block is too big to fit on the page, asciidoctor-pdf will place a dashed horizontal rule on the bottom of the first page and on top of the second page.
When the code_background_color is transparent this will cause a fatal error: Unknown type of color: "transparent".

I use this trick to get a kind of watermark using the page_background_image. But then for tables and code blocks I need to set the background color to transparent.

Workaround: remove the code border by setting code_border_width to zero

**Comment by mojavelinux** [comment]
This is not enough information for me to reproduce. Please submit the following:

* a sample file that demonstrates the error
* your theme file if you are not using the default
* which source highlighter you are using, if any

Thanks!

**Comment by sytzek** [comment]
Using asciidoctor-pdf version '1.5.0.alpha.16'

Using a simple test file with big code block without source highlighter:

Using the default-theme.yml with only the code_background_color set to transparent.

Running: 
  bin/asciidoctor-pdf test.adoc -a pdf-stylesdir=./ -a pdf-style=transparent
results in:
  prawn-2.2.2/lib/prawn/graphics/color.rb:100:in `color_type': Unknown type of color: "transparent" (ArgumentError)

**Comment by sytzek** [comment]
I dropped the test file and theme file in the comment box, but don't see them. Hope it worked.

**Comment by mojavelinux** [comment]
> Using the default-theme.yml with only the code_background_color set to transparent.

That's the main piece of information I needed.

**Comment by mojavelinux** [comment]
This seems to have been resolved at some point. Feel free to reopen if it's still happening.
