### ISSUE TITLE
Numbered lists do not accommodate large numbers

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/asciidoctor-pdf#91]
Looks like numbered lists do not have enough spacing between the number and the list item text once the lists hit double digits.

**Comment by mojavelinux** [comment]
This is one of the things we take for granted that the browser does for us automatically that we have to solve manually in PDF :/ Fortunately, we know up front how many items are in the list, so we can allocate the amount of space necessary for the largest number. That way, lists with less than 10 times don't look like they have excess space.

**Comment by mojavelinux** [comment]
I updated the titled to reflect the crux of the issue.

**Comment by mojavelinux** [comment]
Once #143 is merged, you should be able to fix this by increasing the size of the outline_list_indent key in the theme.

```
outline_list:
  indent: 24
```

That at least provides a workaround. The indentation in the default theme is rather conservative.

**Comment by mojavelinux** [comment]
I updated the pull request to address this problem specifically. It turned out to be easier than expected. Now it will layout a number regardless of its length. The number will bleed into the left margin if it exceeds the indent size, but that's consistent with CSS.

**Comment by mojavelinux** [comment]
Note that I also squeezed the character spacing a bit in the numbers for a numbered list. This prevents the period from appearing far from the number and cuts down on bleed without sacrificing readability. If this becomes a problem, we could always let the theme control this behavior.
