### ISSUE TITLE
Need to reset chapter and section when starting part

### ISSUE THREAD

**Issue by gdamore** [asciidoctor/asciidoctor-pdf#910]
I have a multipart book, and I have major parts indicated by separate pages, e.g. "Section 3: Library Functions".  I've hacked up an extensions module to layout the library page properly, but I'm finding that I cannot use the running content (header, probably also footer, though I didn't test that) with the {chapter-title} or {section-title}, because what happens is that my otherwise nice clean part separator page now has a running header.  This is ugly, but it gets worse.  The running header now has the last chapter of the previous part (becauseI don't have any new chapters on this page.) 

The solution, after much gnashing of teeth, is to fix asciidoctor-pdf itself -- specifically we need to reset the chapter-title and section-title when starting a new part.  Probably a similar change should be to reset the section-title when starting a new chapter (*if* the chapter is starting on a new page).

With this change, the {chapter-title} evaluates to an empty string on a page containing a new part, but without a chapter.  This is 1000% better than having the bogus and incorrect chapter title that was before.

Here's the diff:

```
diff --git a/lib/asciidoctor-pdf/converter.rb b/lib/asciidoctor-pdf/converter.rb
index 0a66400..638297b 100644
--- a/lib/asciidoctor-pdf/converter.rb
+++ b/lib/asciidoctor-pdf/converter.rb
@@ -2482,6 +2482,8 @@ class Converter < ::Prawn::Document
       if is_book && ((sect_is_part = sect.part?) || sect.chapter?)
         if sect_is_part
           part_start_pages[page_num] ||= (sect.numbered_title formal: true)
+          chapter_start_pages[page_num] = ''
+          section_start_pages[page_num] = ''
         else
           chapter_start_pages[page_num] ||= (sect.numbered_title formal: true)
           if sect.sectname == 'appendix' && !part_start_pages.empty?
```

**Comment by gdamore** [comment]
If you'd prefer this in a PR, let me know.

**Comment by gdamore** [comment]
Ping!

I forgot I had this change locally, and accidentally produced a book with those running header/footer stuff.  That makes me unhappy.  Much better to have stuff upstreamed if at all possible.

I would like feedback on this at least.

**Comment by gdamore** [comment]
@mojavelinux ?

**Comment by mojavelinux** [comment]
If you send a PR, and that change doesn't break other scenarios, I'll merge it.

**Comment by gdamore** [comment]
Done. :-) I'm not sure how you validate the "other scenarios".  Do you have a test suite?

**Comment by gdamore** [comment]
YES!  It's precisely the problem I was trying to fix.

**Comment by mojavelinux** [comment]
Awesome! That gives me a lot of confidence in the solution. I'll review and merge today.

**Comment by gdamore** [comment]
Thanks. :-)

**Comment by mojavelinux** [comment]
When you get a chance, please verify the change works as you expect it to work.

**Comment by gdamore** [comment]
will do. thanks for doing this.

**Comment by gdamore** [comment]
I confirm that this works properly (as from master).

**Comment by mojavelinux** [comment]
Thanks for taking the time to verify!
