### ISSUE TITLE
Title image not rendered

### ISSUE THREAD

**Issue by emial18** [asciidoctor/asciidoctor-pdf#913]
The title image logo include the adoc file is ignored and not rendered. If the default theme is changed manually to include the logo, the logo is shown.

Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.7.1 

```
= Some book
Author <author@foo.com>
1.0, July 29, 2014, Template

:title-logo-image: image:test-logo.png[]

== Introduction
Lore ipsum
```

**Comment by mojavelinux** [comment]
The `title-logo-image` is a header attribute and therefore must be defined in the document header to be detected.

In your case, the blank line above the attribute entry causes it to fall outside of the document header. Remove that line and you should find that it works.

For more info about the document header, see https://asciidoctor.org/docs/user-manual/#doc-header
