### ISSUE TITLE
Callout is on one page and its text breaks to the next one

### ISSUE THREAD

**Issue by codenameone** [asciidoctor/asciidoctor-pdf#914]
I don't think this is easy to reproduce as it happens on my 400+ pg book. Here's a screenshot to clarify. Notice item 3 is a callout but the text shows on the next page:

<img width="821" alt="screen shot 2018-06-12 at 15 19 17" src="https://user-images.githubusercontent.com/2353641/41290030-4bea1c1a-6e54-11e8-8eb1-786e41f12279.png">

This is the callout, no line breaks or anything special:

````
<3> The following variables are used as configuration properties for the border
````

Everything is with the default theme on Mac OS X High Sierra:

````
$ asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]) (lc:US-ASCII fs:US-ASCII in:- ex:US-ASCII)
````

**Comment by mojavelinux** [comment]
This is not supposed to happen as we have specific checks to prevent it. However, it looks like the computation is off by one pixel.
