### ISSUE TITLE
problem with SVG imange in asciidoctor-pdf

### ISSUE THREAD

**Issue by ssydorov** [asciidoctor/asciidoctor-pdf#915]
Hi All,
I got next issue.

code in asciidoctor file:
`
image::server_room_1_floor.svg[Room1,align="center", title-align="center", width="400%"]
`

in html out look good
![image](https://user-images.githubusercontent.com/24498236/41353554-35f06de8-6f25-11e8-93d6-e14c70c46396.png)

but in pdf looks not so good
![image](https://user-images.githubusercontent.com/24498236/41353589-56d96b68-6f25-11e8-890e-2467b3bdf8fd.png)

could you help me with correct inserting of SVG file.
SVG file added

Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]) (lc:UTF-8 fs:Windows-1252 in:UTF-8 ex:UTF-8)

[server_room_1_floor.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/2098266/server_room_1_floor.zip)

Thanks

**Comment by AlexanderZobkov** [comment]
Hello @ssydorov ,

The way you use to include SVG seems correct. Here problem with interpreting SVG by prawn-svg library which is used for reading and rendering SVG .  These absent elements arerepresented by image svg elements that include embededed png in base64 encoding. This seems supported (from my experince). I  suggest you create an issue for prawn-svg library, probably the maintaineter can help you.

**Comment by mojavelinux** [comment]
@AlexanderZobkov Exactly. Asciidoctor PDF can only do what prawn-svg supports.

**Comment by mojavelinux** [comment]
This can be resolved by upgrading prawn-svg. I will make that upgrade as part of the next release.

**Comment by mojavelinux** [comment]
It turns out, the data-uri is malformed. In your SVG, the data-uri is written as:

```
href="data:image/PNG;base64,..."
```

If you change PNG to lowercase, it works.

```
href="data:image/png;base64,..."
```

Then your image looks exactly as it should.

I'm going to report this upstream (see https://github.com/mogest/prawn-svg/issues/108) and close the issue here since there is a workaround.
