### ISSUE TITLE
Support adding blank page between title page and TOC

### ISSUE THREAD

**Issue by free-easy** [asciidoctor/asciidoctor-pdf#916]
In a book there is usually a blank page between the front-cover and the internal title page, between the title page and the TOC and between the TOC and actual content of the book.
Does `asciidoctor-pdf` support this? I've googled without finding anything.

I'm not sure whether book pdfs come already with these blank pages or whether they are handled during the print process.
If it's the second, then feel free to close this issue.

**Comment by codenameone** [comment]
Not from the team but maybe I can answer this.

Try:

````
:doctype: book
:media: prepress
````

The reason for this blank page has to do with the book/press format where the page makes sure the chapter/ToC  start in the correct page when leafing through pages. If you pick prepress it arranges everything correctly so the left/right side margin changes based on the side of the page (you need more margin going into the book binding).  It also adds these blank pages as needed.

**Comment by free-easy** [comment]
Whao, fabulous!!
Thank you very much!
