### ISSUE TITLE
link bracket when prepress

### ISSUE THREAD

**Issue by alpapan** [asciidoctor/asciidoctor-pdf#919]
Hello
Using the current latest version of asciidoc:

When the media is set as prepress there is the issue of including the final ] in the embedded URL, for example: 
LINKED TEXT  [https://example.com/]

the LINKED TEXT is a clickable URL and works fine. The printed part within brackets however has a url like so
https://example.com/**]**

The HTML output works fine.

Thanks
a

**Comment by mojavelinux** [comment]
I cannot reproduce this. Can you provide a sample of a full paragraph that demonstrates this issue?

**Comment by mojavelinux** [comment]
Please reopen if you can provide a reproducible test case (a sample document).

It sounds like you may have conflicts in the formatting the surrounds the link. But I can only guess what's happening since you have not provided that detail.
