### ISSUE TITLE
Spacing between list entries

### ISSUE THREAD

**Issue by osterwood** [asciidoctor/asciidoctor-pdf#92]
Is there a way to prevent the vertical gaps between list entries?  In the attached image (from the chronicles example) I'd love for the list to have the same list spacing as the normal paragraph line wrapping.

![screen shot 2015-02-09 at 4 10 37 pm](https://cloud.githubusercontent.com/assets/10534/6115792/318e3b98-b076-11e4-888d-6029a3613abe.png)

**Comment by mojavelinux** [comment]
Not at the moment. We'll probably implement logic similar to what is described in https://github.com/asciidoctor/asciidoctor/issues/1087 or https://github.com/asciidoctor/asciidoctor/issues/1221. We may also consider supporting the "compact" option (which carries over from AsciiDoc Python).

**Comment by mojavelinux** [comment]
I've reduced the spacing by default. You can control the spacing using the following property in the theme:

```
outline_list:
  item_spacing: <value>
```

The default value is half the bottom margin on prose.

Note that this applies to simple lists. A simple list is a list that does not have any entries that contain block-level content other than a nested list. In other words, a list becomes a complex list when one of the list items contains a non-list block.

**Comment by mojavelinux** [comment]
Slight correction. The spacing is reduced for any list item that only has text, even if it occurs in a list that has other items containing complex content. In other words, we leave ample room between the text of the list item and block-level content attached to that list item, as you might expect.

**Comment by cup** [comment]
https://github.com/asciidoctor/asciidoctor/issues/1087
https://github.com/asciidoctor/asciidoctor/issues/1221
https://github.com/asciidoctor/asciidoctor/issues/1346

https://github.com/asciidoctor/asciidoctor-pdf/issues/92
https://github.com/asciidoctor/asciidoctor-pdf/pull/164

**Comment by siddjain** [comment]
this:

```
outline_list:
  item_spacing: <value>
```

seems to work for outline lists but not unordered lists. is there any equivalent setting for (un)ordered lists?

**Comment by mojavelinux** [comment]
The same key works for both ordered and unordered lists (that's what is meant by "outline list"). If you are observing different behavior, please report it with an example.
