### ISSUE TITLE
prepress email links

### ISSUE THREAD

**Issue by alpapan** [asciidoctor/asciidoctor-pdf#920]
Hello

When the media is set as prepress, email addresses appear as:
bob@example.com [mailto:bob@example.com]
or
my email [mailto:bob@example.com]

The 'bob@example.com' or 'my email' are clickable links in the PDF which is good. Then the [brackets] appear because it is prepress, and that is good too. However the mailto: part is not really something that makes sense in the context of emails. Just having the email address - without the mailto part - I think, would be better .

thank you!
a

**Comment by mojavelinux** [comment]
The reason this was done is to emulate the behavior of the DocBook toolchain (specifically Apache FO to PDF). The mailto: prefix indicates that the link was added to the document as a mailto: URI to distinguish it from a URL.

We could consider an attribute such as `hide-mailto-scheme` to force it to not be shown.
