### ISSUE TITLE
PDF with Wide URLs, for example, breaks justification

### ISSUE THREAD

**Issue by NormanDunbar** [asciidoctor/asciidoctor-pdf#921]
When a long URL, for example, is on a list item, or in a paragraph, and the URL is split over two lines, the ``align:justify`` setting in the pdf theme causes very wide spaces between words.

The attached zip file contains the following files:

- test.adoc - the source file showing the problem;
- test.justify.pdf - pdf showing the problem with ``align: justify`` in use.
- test.center.pdf - a pdf _not_ showing the problem when ``align: center`` is used. 
- test.left.pdf - a pdf showing the problem _not_ happening when ``align: left`` is used.

There is no test.right.pdf on the grounds that doing that makes the whole file unreadable!

[Justify.issue.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/2127238/Justify.issue.zip)

Cheers,
Norm.

**Comment by AlexVigogne** [comment]
Hello,

I have the same problem here:
For my project i needed to industrialize my documentation (installation sheet) and at one moment there is a wide URL to download a package from artifactory. The link is on three lines.
When I wan't to copy paste it on a console, the copy paste insert a carriage return at every end of line and it breaks my link..

Can you have a look on it ?

Cheers,
Alex.

**Comment by mojavelinux** [comment]
This is just the way text justification (text-align=justify) works. You can observe the same result in the browser.

The solution is either to switch the alignment from justify to left or to insert `{zwsp}` attribute references at strategic places in the URL to get it to break more naturally.

**Comment by mojavelinux** [comment]
> The link is on three lines. When I wan't to copy paste it on a console, the copy paste insert a carriage return at every end of line and it breaks my link

This is a limitation with the PDF reader. If you right click on the link and select "Copy Link Location" (or equivalent), it will paste fine into the browser. On the other hand, when you select and copy text in a PDF that spans multiple lines, the line break gets included.

**Comment by NormanDunbar** [comment]
Thanks.

Cheers,
Norm.
