### ISSUE TITLE
No way to pad footer numbering which are outside the printed region on KDP

### ISSUE THREAD

**Issue by codenameone** [asciidoctor/asciidoctor-pdf#922]
Steps to reproduce:

- Generate a PDF document with default settings for book
- Submit to KDP (Kindle Direct Publishing - Print on demand service) 

You will get errors as the numbering is outside of the printed range. 

Trying to fix that I changed:

````
footer:
  font_size: $base_font_size_small
  # NOTE if background_color is set, background and border will span width of page
  border_color: dddddd
  border_width: 0.25
  height: 1in
````

And the file resolution seems to be impacted as KDP will no longer accept it. Since height was increased physically and page count didn't change I'm guessing this added to the physical size of the page somehow.

**Comment by codenameone** [comment]
This seems to be a bug in KDP albeit a weird one...

**Comment by bguiz** [comment]
@codenameone I read your article about how you eventually managed to format your AsciiDoc book via Sketch ... but still curious whether you managed to get asciidoc to output a PDF file that would be accepted by Amazon?
https://medium.com/sketch-app-sources/using-sketch-and-asciidoc-to-generate-a-professional-tech-book-ef5b5d8dd410

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org as stated on the following page in the docs: https://docs.asciidoctor.org/about/get-help/
