### ISSUE TITLE
Is there a way to remove the TOC from an article doctype?

### ISSUE THREAD

**Issue by kastork** [asciidoctor/asciidoctor-pdf#924]

**Comment by mojavelinux** [comment]
You just need to unset the `toc` attribute.

```
= Document Title
:!toc:
```

(Unlike other converters, in PDF, the toc is enabled by default).

For details, see https://asciidoctor.org/docs/user-manual/#user-toc

**Comment by kastork** [comment]
Doh!

Thanks

**Comment by kastork** [comment]
Except...  it doesn't work.  The pdf still has a table of contents.

```
:authors: author one, author two
:date: 2018-07-20
:doctype: article
:doctitle: The Title
:!toc:
:revnumber: 1
:linkattrs:
:imagesdir: images
:stylesdir: styles
:linkcss:
ifdef::backend-pdf[:notitle:]
ifdef::backend-pdf[]
[discrete]
= {doctitle}
endif::[]
```

**Comment by mojavelinux** [comment]
Are you sure the command calling Asciidoctor is not passing the toc
attribute? Have you also verified these are the very first lines of the
file and they are followed by at least one blank line?

To check if the toc attribute is set, you can add this to the body.

{toc}

or

ifdef::toc[toc is set]

**Comment by kastork** [comment]
You nailed it... the gradle build had a `toc` attribute.

**Comment by mojavelinux** [comment]
Yee-ha!
