### ISSUE TITLE
A bug with indexing in report and articles.

### ISSUE THREAD

**Issue by NormanDunbar** [asciidoctor/asciidoctor-pdf#929]
Greetings.

If an index is used in an article or a report, then it must be arranged so that it appears on a separate page otherwise the index will not format correctly and ends up with random page throws etc.

### ASCIIDoctor-pdf Version
````
asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]) (lc:CP850 fs:Windows-1252
in:UTF-8 ex:UTF-8)
````

### Attachments

[IndexingFailure.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/2352996/IndexingFailure.pdf)
[IndexingWorked.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/2352997/IndexingWorked.pdf)
[IndexingFault.adoc.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/2353001/IndexingFault.adoc.txt)

* `Indexing.adoc.txt` a source file which highlights the problem. There are two parts of interest - never mind the text, it's just there to create a decent sized index. Please remove the .txt extension - GitHub doesn't like .adoc by itself.
* `IndexingFailure.pdf` shows the problem.
* `IndexingWorked.pdf` shows that the workaround worked.

### Reproducing the Fault

Run asciidoctor-pdf on `indexingFault.adoc` and view the pdf output.
* If the 'doctype' is book, the index is created correctly (and on a new page). 
* If the 'doctype' is article or report, then the index is corrupted, however:
  * If you uncomment the ``[%hardbreaks]`` on line 159 the index builds correctly as the heading for it is forced to a new page; OR
  * If you uncomment line 171 (``<<<`` a forced page break) then again, the index works fine.

### Workarounds

* Use `:doctype: book` - may not always be relevant.
* Arrange the text so that the index heading happens to land at the top of a new page. Difficult!
* Use `<<<` to force a page throw just before the `[index]` attribute. Works like a charm.

**Comment by mojavelinux** [comment]
Aha! We were missing an option that resets the top-margin of the columns when starting a new page.

**Comment by NormanDunbar** [comment]
Thank you.

Cheers,
Norm.

**Comment by mojavelinux** [comment]
You bet! Thanks for reporting!

**Comment by mojavelinux** [comment]
Btw, your sample document helped me so much. It made fixing the issue really easy.
