### ISSUE TITLE
Inline Code gets indexed - it should not be.

### ISSUE THREAD

**Issue by NormanDunbar** [asciidoctor/asciidoctor-pdf#932]
Me again! Sorry.

I have the following code in a document: `X = ~((1 << 2) | (1 << 4) | (1 << 6))` which renders correctly in a code block, but inline it renders as `X = ~  1 << 3) | (1 << 6) | (1 << 7` when the output is PDF or HTML. Not only that, it gets indexed because of the opening and closing double parentheses `((` and `))`. The index term is the same as the rendered output.

Cheers,
Norm.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor/issues/2858.
