### ISSUE TITLE
Attach file

### ISSUE THREAD

**Issue by geekscrapy** [asciidoctor/asciidoctor-pdf#933]
Is it possible to attach a file (or embed text even) in an asciidoc created pdf? I originally thought I could do something with the passthough mechanism, but this doesn't seem possible.

I'm intending on either attaching a .gz file, or failing that JSON text/file.

Like this I guess: https://helpx.adobe.com/acrobat/using/links-attachments-pdfs.html#add_an_attachment

TIA!

**Comment by mojavelinux** [comment]
This is not possible in Asciidoctor PDF. The feature would first need to be added to Prawn, which is the PDF generator we use. See https://github.com/prawnpdf/prawn
