### ISSUE TITLE
Image Caption Position

### ISSUE THREAD

**Issue by Serverfrog** [asciidoctor/asciidoctor-pdf#938]
Like #531 but for Images.

Need the Caption on the bottom side of the Image.

Also: how can all Images be centered through a Theme? 
```
image:
  align: center
```
does not work.

**Comment by mojavelinux** [comment]
You're asking two question here. Let's focus on one. The request is to control the side of the caption for images like tables.

> Need the Caption on the bottom side of the Image.

That's already the default. Do you want to be able to place the caption above the image?

**Comment by Alyaksej** [comment]
Different alignment of image_caption  &  table_caption. Is it posible?
For example:

...
table:
  caption:
     align: right

image:
  caption:
     align: center

**Comment by mojavelinux** [comment]
No, the layout for captions is currently global.

**Comment by Alyaksej** [comment]
It's a pity. More beautiful when caption of table **align: right or left** and caption of image **align: center**

**Comment by mojavelinux** [comment]
Thanks to #307 and #1459, it's now possible to control the position of image captions independent of other captions, and to have the caption inherit the alignment from the image. There are also more improvements coming in #1493.

**Comment by Alyaksej** [comment]
Thanks a lot!!!
