### ISSUE TITLE
How do I cross-reference to a particular section when there are a multiple sections with the same name?

### ISSUE THREAD

**Issue by cristobalito** [asciidoctor/asciidoctor-pdf#942]
Hi, 

Say I've got a file structure similar to below. The `<<Known Issues>>` always seems to reference the first instance of the Known Issues section, but I'd like it to reference the other one. 

```
= How can I cross-reference a duplicate section heading
:sectnums:
:xrefstyle: full

== Release A Patch 1
=== Known Issues
No further known issues have been introduced in this patch. Please refer to the <<Known Issues>> section of <<Release A>>

== Release A
=== Known Issues
- Known issue one
- Known issue two
```

This produces the content below. Ideally I'd like to reference `Section 2.1, "Known Issues"` instead of the underlined text.

![image](https://user-images.githubusercontent.com/140550/46881095-6efc6c00-ce42-11e8-951b-4de7f78cdaea.png)

Any tips \ suggestions appreciated.

Chris

**Comment by rockyallen** [comment]
See https://asciidoctor.org/docs/user-manual/#auto-generated-ids
So it looks like the automatic labels will be _known_issues and _known_issues1.
This may be confusing, so you might prefer to create explicit labels:
[[known_issues_a1]] and [[known_issues_a]]

**Comment by mojavelinux** [comment]
I agree with @rockyallen that this is where you definitely want to switch to explicit IDs. Once the auto-generated IDs start getting sequenced, it's a good idea not to rely on them.

```
= How can I cross-reference a duplicate section heading
:sectnums:
:xrefstyle: full

== Release A Patch 1

[#known-issues-release-a-p1]
=== Known Issues

No further known issues have been introduced in this patch.
Please refer to the <<known-issues-release-a>> section of <<Release A>>

== Release A

[#known-issues-release-a]
=== Known Issues

- Known issue one
- Known issue two
```

The text-based cross reference is only meant for quick prototyping. For any long-living document, it's a good ID to create cross references using the actual ID.

**Comment by cristobalito** [comment]
Thanks guys - that worked and appreciate the advice.

Sorry I wasn't able to gather how to do this from the docs - will have
another read and try to get it all straight in my head.

Chris

**Comment by mojavelinux** [comment]
We're glad to help! Every question helps us improve the docs a little bit more.
