### ISSUE TITLE
How to select the language using asciidoctor-pdf

### ISSUE THREAD

**Issue by julianofischer** [asciidoctor/asciidoctor-pdf#943]
I know we can select the language using:
`    asciidoctor -a lang=es -b docbook article.adoc`

I tried
`    asciidoctor -a lang=pt-br -r asciidoctor-pdf -b pdf book.adoc`

But it did not work.

Please, could someone help me?

**Comment by mojavelinux** [comment]
When using a pure Asciidoctor converter (whether HTML or PDF), you need to feed it the [translation file](https://github.com/asciidoctor/asciidoctor/blob/master/data/locale/attributes-pt_BR.adoc).

For more instructions, see https://asciidoctor.org/docs/user-manual/#customizing-labels

**Comment by mojavelinux** [comment]
Please reopen or file a new issue if you're still having trouble.
