### ISSUE TITLE
How to disable copy for the generated PDF?

### ISSUE THREAD

**Issue by chenryn** [asciidoctor/asciidoctor-pdf#946]

**Comment by mojavelinux** [comment]
That's not something that's possible, as far as I know. Though what you could do is run the PDF through `ghostscript` in print mode so each page is converted to an image (kind of like you scanned it).

**Comment by 7SW** [comment]
Well, this might be possible with post-processing through something like Adobe Acrobat. There are some other tools that can do this too (says Google). 
Maybe there even is some open-source tooling that can do this. If asciidoctor-pdf (prawn) can’t do it out-of-the-box that is the way to make it work for you I guess :-)

**Comment by mojavelinux** [comment]
As I said, the simple solution is to rasterize the document using imagemagick (or ghostscript). You can't copy and paste text from a picture (at least not in the normal way).
