### ISSUE TITLE
Images not aligning correctly in tables

### ISSUE THREAD

**Issue by norte73** [asciidoctor/asciidoctor-pdf#948]
Hi,

I have a problem with aresizing and aligning images placed in table cells as described below.

I've tried various setups for my asciidoc setup. Everything from asciidocFX to running asciidoctor on Windows. Now I believe I have settled for running on Linux (on Windows using WSL) since I want to build scripted publications toolchains.

Current setup:
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.7.1
Runtime Environment (ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu])

Using asciidocFX, I got my document layout pretty much as I wanted (using images in tables and save as PDF in asciidocFX). However, when I'm now using asciidoctor-pdf my notation doesn't seem to work the same way. I've tried to google for a solution and might have stumbled across it at some point but nothing I try now seems to work.

When using the code below the image gets the same width as the cell/column it is placed in which usually is quite good:

```asciidoc
[width="100%", frame="none", grid="none", cols="4,6"]`
|===
a|Text
a|image::image.jpg[]
|===
```

If I wish to change the image width, I use the command **pdfwidth**. But that messes up the image alignment. and the image aligns with the edge of the PDF page instead of the table where the image is placed:

```asciidoc
[width="100%", frame="none", grid="none", cols="4,6"]
|===
a|Text
a|image::image.jpg[pdfwidth='30vw', align='right']
|===
```

See attached PDF for code examples and layout.
[test.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/2502352/test.pdf)

**Comment by mojavelinux** [comment]
An assumption was being made that if you used `vw` units, it meant you wanted to align the image to the edge of the page (based on the value of the align attribute). This is useful for making a full-page image, but as you have discovered, it limits the usefulness of the `vw` units.

Instead, I propose to add an `align-to-page` option to restore the previous behavior. If this option is not specified, the image will align to its parent (as you are expecting).

Feel free to propose another name for this option.

In the meantime, you can use any units other than `vw` to get the behavior you desire. For example, you could use `width=30%` or `width=180pt`.

**Comment by mojavelinux** [comment]
see https://github.com/asciidoctor/asciidoctor-pdf/pull/950
