### ISSUE TITLE
Footnote doesn't render under paragraph

### ISSUE THREAD

**Issue by Solido** [asciidoctor/asciidoctor-pdf#952]
Screenshot from IntelliJ plugin preview
<img width="543" alt="screenshot 2018-10-28 at 12 06 51" src="https://user-images.githubusercontent.com/1295961/47618113-89d01100-dacf-11e8-92e0-d2b94ac2a0ea.png">

Screenshot from the rendered Pdf.
<img width="525" alt="screenshot 2018-10-28 at 12 07 12" src="https://user-images.githubusercontent.com/1295961/47618114-89d01100-dacf-11e8-8e2c-38e35109a99e.png">
 
Reading the other issues this maybe related to #73 ?

Thank you

**Comment by mojavelinux** [comment]
This is a duplicate of #85. It turns out, this is a really hard problem to solve. You can read about it in that issue.

**Comment by Solido** [comment]
Yep I understand why it's difficult to solve since there's only one pass. Thanks !
