### ISSUE TITLE
diacritics are not correctly rendered

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor-pdf#961]
When rendering a file in Vietnamese, the rendering of diacritics is truncated:

On the left, the pdf with missing signs and unwanted spaces, on the right the (correct) rendering in a browser.
![image](https://user-images.githubusercontent.com/156172/48551335-831a0a00-e8d5-11e8-847c-4acb81db19e5.png)

command line:
```
$ bundle exec asciidoctor-pdf -B vt vt/root_doc.adoc
$ bundle exec asciidoctor-pdf --version

Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.6.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by jnavila** [comment]
Found why. FTR: generating in pdf works best with NFC encoding of the text. Using `uconv`:

```
$ uconv -x any-nfd <file.adoc >file.fixed.adoc
```

**Comment by mojavelinux** [comment]
The document that you pass to Asciidoctor PDF should be encoded in UTF-8. Otherwise, the toolchain may fail to interpret the characters correctly.

**Comment by jnavila** [comment]
More precisely, this is not an issue of UTF-8. This is an issue of [normal form of unicode](https://en.wikipedia.org/wiki/Unicode_equivalence) for diacritics.

The toolchain only works correctly with precomposed characters. I don't know if it's a limitation of the PDF specification. It would be good to force the NFC form of unicode in any case.

**Comment by mojavelinux** [comment]
Ah, do you mean the characters are written as a single glyph?

Yes, that is very likely a limitation of Prawn (knowing how limited its support for font features is).

**Comment by jnavila** [comment]
Yes, characters must not be composed. I guess [pre-processing](https://ruby-doc.org/stdlib-2.2.1/libdoc/unicode_normalize/rdoc/String.html) the text in asciidoctor would prevent this.

**Comment by mojavelinux** [comment]
Gotcha!

You could certainly use a preprocessor, though the right way would be to get Prawn to recognize these character sequences.
