### ISSUE TITLE
Apparently DeviceRGB setup needed?

### ISSUE THREAD

**Issue by gdamore** [asciidoctor/asciidoctor-pdf#967]
I was getting warnings using pstill to convert the output to pre-press format (PDF/1x) and I got some warnings, which the pstill author described to me this way:

> from a quick look it seem the PDF is indeed partly invalid. In some elements it uses the 'scn'/'SCN'
> commands (sets the color components for the current colorspace) without previously defining the
> colorspace and it does it with 3 parameters. As the default color space of PDF is DeviceGray, but
> it only takes one parameter (for the gray value) but three are provided, the PDF parser notices a
> problem and refuses to set the color. It seems the setup of the colorspace to DeviceRGB in all
> those cases is missing.

The pstill author is going to implement a workaround to help with this, but it seems like this should really be fixed.  This may well be a problem in the underlying Prawn code.

**Comment by gdamore** [comment]
http://www.pstill.com/

**Comment by gdamore** [comment]
I wonder if some of my icons and use of colors (really just shades of grey) in the style sheet are to blame.  My whole book content is rather complex, with a bunch of machinery to build it, so I'm not sure that it would be terrifically productive for you to look at it.

**Comment by mojavelinux** [comment]
You'll need to distill it down to a reproducible test case if we have any hope of resolving it.

**Comment by gdamore** [comment]
I understand that.  Unfortunately, the document that creates this problem is fairly large and complex.  So it would take some time for me to isolate the specific changes that were responsible for creating the problem.

**Comment by mojavelinux** [comment]
This should be resolved now. It was a bug in Prawn that Prawn addressed. We also have workarounds in Asciidoctor PDF just in case.
