### ISSUE TITLE
Title_page_logo_image directory not correct

### ISSUE THREAD

**Issue by LilMouse** [asciidoctor/asciidoctor-pdf#976]
When using
```
title_page:
  logo_image: image:BigLogo.png[]
```
or
``` 
title_page:
  logo_image: BigLogo.png
```
It both generates the error: 
`asciidoctor: WARNING: image to embed not found or not readable: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/data/themes/BigLogo.png`
But the theme is in a different folder altogether (Somewhere in documents/Asccidoc)
In the adoc doument the imagedir is set but this seems to have no affect.

**Comment by LilMouse** [comment]
That fixed it! Thanks!

**Comment by mojavelinux** [comment]
Great!
