### ISSUE TITLE
HTML entitiy &quot; inside block causing 'Failed to parse formatted text'

### ISSUE THREAD

**Issue by mmattel** [asciidoctor/asciidoctor-pdf#977]
Following your fix at https://github.com/asciidoctor/asciidoctor/issues/2061 (Double quotes in alt text are not escaped)

pdf generator seems to ignore that solution, see the examples.

**adoc**
`image:enterprise/firewall/firewall-3.png[Protecting files tagged with "Confidential" from outside access]`

**html after build**
```
<p><span class="image"><img src="../../_images/enterprise/firewall/firewall-3.png" alt="Protecting files tagged with &quot;Confidential&quot; from outside access"></span></p>
```
**pdf generation error**
```
Failed to parse formatted text: <img src="/drone/src/modules/administration_manual/assets/images/enterprise/firewall/firewall-3.png" format="png" alt="[Protecting files tagged with "Confidential" from outside access]" tmp="false">
```

Any idea how to solve that ?

**Comment by mojavelinux** [comment]
Actually, it's because they are escaped that it's a problem. I'll look into why it's choking.

**Comment by mojavelinux** [comment]
Btw, this works if you use a block image. The problem is with the inline image.

**Comment by mmattel** [comment]
Thanks! @mojavelinux
Q: is there a planned release date for the fixes made ?
