### ISSUE TITLE
Missing sections

### ISSUE THREAD

**Issue by aalmiray** [asciidoctor/asciidoctor-pdf#98]
The rendered PDF skips showing sections that begin with a dot (.). HTML has no problems with them.

Sample document that reproduces the problem

    = Index page
    :toclevels: 3
    :numbered:

    == Section 1

    Lorem ipsum dolor sit amet consecutur.

    .Subsection 1.1

    Lorem ipsum dolor sit amet consecutur.

    == Section 2

    Lorem ipsum dolor sit amet consecutur.

gradle 2.3
asciidoctor 1.5.2
asciidoctorj-pdf 1.5.0-alpha.6

**Comment by DavidGamba** [comment]
Take a look at: https://github.com/asciidoctor/asciidoctor-pdf/issues/67

**Comment by mojavelinux** [comment]
Closing as duplicate. We'll get this for 1.5.0.
