### ISSUE TITLE
Using CSS to style PDF

### ISSUE THREAD

**Issue by elmajime** [asciidoctor/asciidoctor-pdf#981]
It would be great to be able to use CSS for styling the PDF output of asciidoctor-pdf.

Interesting source of information:

* https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/
* https://print-css.rocks/

This would offer :

. a single styling language to learn for users
. a single styling process to manage for developers
. functionnalities that are already present in the HTML output but not yet in the PDF output like kdb macros styling, etc.

What do you think?

**Comment by mojavelinux** [comment]
That's exactly the approach we're exploring here: https://github.com/mogztter/asciidoctor-pdf.js
