### ISSUE TITLE
How to add content to HTML output but not to PDF output?

### ISSUE THREAD

**Issue by psprint** [asciidoctor/asciidoctor-pdf#982]
Hello
I want to include a link in the HTML version of the converted document, to point to PDF version of the converted document (i.e. basically a http url to the pdf). I also want the link and possibly some surrounding text to appear only in the HTML version, i.e. no PDF pointing-link in the PDF. Is this possible?

**Comment by JGrenier** [comment]
Hi.

You can use conditional based on the backend.

Ifdef::backend-html5[]

the dedicated html output text

See https://asciidoctor.org/docs/user-manual/#ifdef-directive

endif::[]

**Comment by psprint** [comment]
Thanks, this works

**Comment by mojavelinux** [comment]
You can also use in inverse:

```
ifndef::backend-pdf[...]
```
