### ISSUE TITLE
Highlight with hashes isn't transfered to the rendered PDF.

### ISSUE THREAD

**Issue by MatteoCampinoti94** [asciidoctor/asciidoctor-pdf#984]
Hello,
I have a document with highlights in it that use the `#text to highlight#`syntax. The asciidoctor-generated html code has the highlight correctly displayed, but the pdf doesn't.

**Comment by mojavelinux** [comment]
That's correct. See #376 and #350.

**Comment by MatteoCampinoti94** [comment]
I see, thank you.
